import {
  PREFERRED_CAPTION_LANGUAGES,
  type YouTubeCaptionTrack,
  type YouTubePlayerResponse,
  type YouTubeTranscriptPayload,
} from "./VideoHandlerTypes.js";
import { VideoHandlerFetchSupport } from "./VideoHandlerFetchSupport.js";

import { VideoHandlerFormatSupport } from "./VideoHandlerFormatSupport.js";
import { logger } from '../../../logger';
export class VideoHandlerTranscriptSupport {
  public static extractYouTubePlayerResponse(html: string): YouTubePlayerResponse | null {
    const markers = [
      "var ytInitialPlayerResponse = ",
      "ytInitialPlayerResponse = ",
      'window["ytInitialPlayerResponse"] = ',
    ];

    for (const marker of markers) {
      const jsonText = this.extractJsonObjectAfterMarker(html, marker);
      if (!jsonText) {
        continue;
      }

      try {
        return VideoHandlerFetchSupport.parseJsonPayload(
          jsonText,
          "YouTube player response",
        ) as YouTubePlayerResponse;
      } catch (error: unknown) {continue;
      }
    }

    return null;
  }

  public static extractJsonObjectAfterMarker(
    content: string,
    marker: string,
  ): string | null {
    const markerIndex = content.indexOf(marker);
    if (markerIndex === -1) {
      return null;
    }

    const startIndex = content.indexOf("{", markerIndex + marker.length);
    if (startIndex === -1) {
      return null;
    }

    let depth = 0;
    let inString = false;
    let escaped = false;

    for (let i = startIndex; i < content.length; i += 1) {
      const char = content[i];

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (char === "\\") {
          escaped = true;
        } else if (char === '"') {
          inString = false;
        }
        continue;
      }

      if (char === '"') {
        inString = true;
        continue;
      }

      if (char === "{") {
        depth += 1;
      } else if (char === "}") {
        depth -= 1;
        if (depth === 0) {
          return content.slice(startIndex, i + 1);
        }
      }
    }

    return null;
  }

  public static chooseYouTubeCaptionTrack(
    tracks: YouTubeCaptionTrack[],
  ): YouTubeCaptionTrack | null {
    if (!tracks.length) {
      return null;
    }

    const rankedTracks = [...tracks].sort(
      (left, right) => this.getTrackRank(left) - this.getTrackRank(right),
    );
    return rankedTracks[0] || null;
  }

  public static getTrackRank(track: YouTubeCaptionTrack): number {
    const languageIndex = PREFERRED_CAPTION_LANGUAGES.indexOf(
      track.languageCode || "",
    );
    const normalizedLanguageIndex =
      languageIndex === -1 ? PREFERRED_CAPTION_LANGUAGES.length + 1
        : languageIndex;
    const isAutoGenerated =
      (track.vssId || "").startsWith("a.") || track.kind === "asr";
    return normalizedLanguageIndex * 10 + (isAutoGenerated ? 5 : 0);
  }

  public static async fetchYouTubeTranscript(baseUrl: string): Promise<string> {
    const jsonUrl = baseUrl.includes("fmt=") ? baseUrl : `${baseUrl}&fmt=json3`;

    try {
      const transcriptJson = await VideoHandlerFetchSupport.fetchJson(jsonUrl);
      const text = this.parseYouTubeJsonTranscript(transcriptJson as YouTubeTranscriptPayload);
      if (text) {
        return text;
      }
    } catch (error: unknown) {// Fallback to XML below.
      logger.warn('[Video  Transcript] network request failed', error);
    }

    const xmlText = await VideoHandlerFetchSupport.fetchText(baseUrl);
    return this.parseYouTubeXmlTranscript(xmlText);
  }

  public static parseYouTubeJsonTranscript(payload: YouTubeTranscriptPayload): string {
    const events = Array.isArray(payload?.events) ? payload.events : [];
    const lines: string[] = [];

    for (const event of events) {
      const segs = Array.isArray(event?.segs) ? event.segs : [];
      const text = segs
        .map((segment: { utf8?: string }) => String(segment?.utf8 || ""))
        .join("")
        .replace(/\s+/g, " ")
        .trim();

      if (!text) {
        continue;
      }

      const timestamp = VideoHandlerFormatSupport.formatTimestamp(
        typeof event?.tStartMs === "number" ? event.tStartMs : 0,
      );
      lines.push(`[${timestamp}] ${text}`);
    }

    return lines.join("\n").trim();
  }

  public static parseYouTubeXmlTranscript(xml: string): string {
    const matches = Array.from(
      xml.matchAll(/<text[^>]*start="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g),
    );
    const lines: string[] = [];

    for (const match of matches) {
      const startSeconds = parseFloat(match[1]);
      const rawText = this.decodeHtmlEntities(match[2])
        .replace(/<br\s*\/?>/gi, " ")
        .replace(/\s+/g, " ")
        .trim();

      if (!rawText) {
        continue;
      }

      lines.push(
        `[${VideoHandlerFormatSupport.formatTimestamp(startSeconds * 1000)}] ${rawText}`,
      );
    }

    return lines.join("\n").trim();
  }

  public static decodeHtmlEntities(value: string): string {
    const namedEntities: Record<string, string> = {
      amp: "&",
      lt: "<",
      gt: ">",
      quot: '"',
      after: "'",
      nbsp: " ",
      "#39": "'",
    };

    return value.replace(
      /&(#x?[0-9a-fA-F]+|[a-zA-Z]+);/g,
      (fullMatch, entity: string) => {
        if (namedEntities[entity]) {
          return namedEntities[entity];
        }

        if (entity.startsWith("#x")) {
          return String.fromCodePoint(parseInt(entity.slice(2), 16));
        }

        if (entity.startsWith("#")) {
          return String.fromCodePoint(parseInt(entity.slice(1), 10));
        }

        return fullMatch;
      },
    );
  }
}
