import { SessionReplayService } from '../../src/services/SessionReplayService.js';

describe('SessionReplayService', () => {
  it('builds a replay snapshot from continuity, workflows, permissions and artifacts', () => {
    const service = new SessionReplayService({
      now: () => new Date('2026-04-02T12:00:00.000Z'),
    });

    const snapshot = service.buildSnapshot({
      continuity: {
        generatedAt: '2026-04-02T11:59:00.000Z',
        sessionId: 'web-1',
        chatId: 'web:web-1',
        userId: 'u1',
        principalId: 'u1',
        runtimeUserId: 'u1',
        currentSurfaceTask: {
          taskId: 'task-web-1',
          shortId: 'task-web',
          source: 'web',
          commandType: '/task',
          status: 'waiting_approval',
          workspace: 'C:/repo',
          updatedAt: '2026-04-02T11:58:00.000Z',
          summary: 'Aguardando confirmacao para gravar a entrega.',
          execution: {
            traceId: 'trace-web-1',
            runId: 'run-web-1',
            sessionId: 'web-1',
            approvalId: 'perm-1',
            artifactId: null,
            workflowRunId: 'wf-1',
            latestStatus: 'approval_required',
            latestSummary: 'Aguardando confirmacao para gravar a entrega.',
            parentId: 'task-web-1',
            source: 'approval-manager',
            surface: 'web',
            lifecycle: [
              {
                kind: 'approval',
                id: 'perm-1',
                traceId: 'trace-web-1',
                runId: 'run-web-1',
                sessionId: 'web-1',
                approvalId: 'perm-1',
                artifactId: null,
                status: 'approval_required',
                summary: 'Precisa de aprovacao para gravar a entrega.',
                source: 'approval-manager',
                surface: 'web',
                parentId: 'task-web-1',
                createdAt: '2026-04-02T11:58:00.000Z',
                updatedAt: '2026-04-02T11:58:30.000Z',
                metadata: {},
              },
            ],
          },
        },
        activeTask: null,
        latestTelegramTask: {
          taskId: 'task-tg-1',
          shortId: 'task-tg',
          source: 'telegram',
          commandType: '/research',
          status: 'completed',
          workspace: 'C:/repo',
          updatedAt: '2026-04-02T11:40:00.000Z',
          summary: 'Pesquisa concluida.',
          execution: null,
        },
        latestWebTask: null,
        latestDiscordTask: null,
        latestWhatsAppTask: null,
        focusTask: {
          taskId: 'task-web-1',
          shortId: 'task-web',
          source: 'web',
          commandType: '/task',
          status: 'waiting_approval',
          workspace: 'C:/repo',
          updatedAt: '2026-04-02T11:58:00.000Z',
          summary: 'Aguardando confirmacao para gravar a entrega.',
          execution: {
            traceId: 'trace-web-1',
            runId: 'run-web-1',
            sessionId: 'web-1',
            approvalId: 'perm-1',
            artifactId: null,
            workflowRunId: 'wf-1',
            latestStatus: 'approval_required',
            latestSummary: 'Aguardando confirmacao para gravar a entrega.',
            parentId: 'task-web-1',
            source: 'approval-manager',
            surface: 'web',
            lifecycle: [
              {
                kind: 'approval',
                id: 'perm-1',
                traceId: 'trace-web-1',
                runId: 'run-web-1',
                sessionId: 'web-1',
                approvalId: 'perm-1',
                artifactId: null,
                status: 'approval_required',
                summary: 'Precisa de aprovacao para gravar a entrega.',
                source: 'approval-manager',
                surface: 'web',
                parentId: 'task-web-1',
                createdAt: '2026-04-02T11:58:00.000Z',
                updatedAt: '2026-04-02T11:58:30.000Z',
                metadata: {},
              },
            ],
          },
        },
        recentTasks: [
          {
            taskId: 'task-web-1',
            shortId: 'task-web',
            source: 'web',
            commandType: '/task',
            status: 'waiting_approval',
            workspace: 'C:/repo',
            updatedAt: '2026-04-02T11:58:00.000Z',
            summary: 'Aguardando confirmacao para gravar a entrega.',
            execution: {
              traceId: 'trace-web-1',
              runId: 'run-web-1',
              sessionId: 'web-1',
              approvalId: 'perm-1',
              artifactId: null,
              workflowRunId: 'wf-1',
              latestStatus: 'approval_required',
              latestSummary: 'Aguardando confirmacao para gravar a entrega.',
              parentId: 'task-web-1',
              source: 'approval-manager',
              surface: 'web',
              lifecycle: [
                {
                  kind: 'approval',
                  id: 'perm-1',
                  traceId: 'trace-web-1',
                  runId: 'run-web-1',
                  sessionId: 'web-1',
                  approvalId: 'perm-1',
                  artifactId: null,
                  status: 'approval_required',
                  summary: 'Precisa de aprovacao para gravar a entrega.',
                  source: 'approval-manager',
                  surface: 'web',
                  parentId: 'task-web-1',
                  createdAt: '2026-04-02T11:58:00.000Z',
                  updatedAt: '2026-04-02T11:58:30.000Z',
                  metadata: {},
                },
              ],
            },
          },
          {
            taskId: 'task-tg-1',
            shortId: 'task-tg',
            source: 'telegram',
            commandType: '/research',
            status: 'completed',
            workspace: 'C:/repo',
            updatedAt: '2026-04-02T11:40:00.000Z',
            summary: 'Pesquisa concluida.',
            execution: null,
          },
        ],
        surfaces: {
          telegram: 1,
          web: 1,
          other: 0,
        },
        surfaceBreakdown: {
          web: 1,
          telegram: 1,
        },
        linkedSurfaces: [
          {
            source: 'telegram',
            sourceUserId: 'telegram-admin',
            linkedAt: '2026-04-02T11:00:00.000Z',
          },
        ],
        suggestedAction: {
          kind: 'resume-active',
          label: 'Retomar task-web',
          reason: 'A entrega mais recente ainda esta esperando sua confirmacao.',
          prompt: 'Retome a entrega e confira o arquivo final.',
        },
        workspaceContext: null,
      },
      tasks: [
        {
          task_id: 'task-web-1',
          source: 'web',
          command_type: '/task',
          status: 'waiting_approval',
          workspace: 'C:/repo',
          updated_at: '2026-04-02T11:58:00.000Z',
          result_summary: 'Aguardando confirmacao para gravar a entrega.',
          artifacts: [
            {
              id: 'artifact-1',
              name: 'briefing-final.md',
              kind: 'doc',
              path: 'artifacts/briefing-final.md',
              summary: 'Briefing final pronto para entrega.',
              createdAt: '2026-04-02T11:58:00.000Z',
            },
          ],
        },
      ],
      permissions: [
        {
          permission_id: 'perm-1',
          executor: 'external_executor',
          kind: 'workspace_access',
          status: 'pending',
          reason: 'Precisa gravar o briefing final.',
          updated_at: '2026-04-02T11:58:30.000Z',
        },
      ],
      workflowRuns: [
        {
          workflow_run_id: 'wf-1',
          workflow_name: 'ship',
          objective: 'Fechar briefing final',
          workspace: 'C:/repo',
          workspace_context: null,
          created_at: '2026-04-02T11:50:00.000Z',
          updated_at: '2026-04-02T11:57:00.000Z',
          status: 'approval_pending',
          stages: [],
          resume_stage: {
            id: 'review',
            label: 'ExternalExecutor Review',
            executor: 'external_executor',
            status: 'approval_pending',
            index: 1,
            attempt_count: 1,
            task_id: 'task-web-1',
            objective: 'Revisar briefing',
            handoff_summary: 'Briefing consolidado.',
            result_summary: 'Aguardando sua confirmacao para seguir.',
            reason: 'Existe aprovacao pendente na etapa final.',
          },
          resume_prompt: 'Retome a revisao final.',
          artifacts: [],
          artifacts_manifest: {},
        },
      ],
    });

    expect(snapshot).toEqual(
      expect.objectContaining({
        generatedAt: '2026-04-02T12:00:00.000Z',
        headline: expect.stringContaining('task-web'),
        operatorSummary: expect.stringContaining('1 tarefa(s) recentes'),
        dominantSurface: 'web',
        executionContext: expect.objectContaining({
          traceId: 'trace-web-1',
          runId: 'run-web-1',
          sessionId: 'web-1',
          workflowRunId: 'wf-1',
        }),
        stats: expect.objectContaining({
          tasks: 1,
          workflowRuns: 1,
          pendingPermissions: 1,
          artifacts: 1,
          linkedSurfaces: 1,
        }),
        recommendedEntry: expect.objectContaining({
          kind: 'task',
          targetId: 'task-web-1',
        }),
        recentArtifacts: expect.arrayContaining([
          expect.objectContaining({
            label: 'briefing-final.md',
          }),
        ]),
        timeline: expect.arrayContaining([
          expect.objectContaining({
            kind: 'focus',
            targetId: 'task-web-1',
          }),
          expect.objectContaining({
            kind: 'permission',
            targetId: 'perm-1',
          }),
          expect.objectContaining({
            kind: 'workflow',
            targetId: 'wf-1',
          }),
        ]),
        lifecycle: expect.arrayContaining([
          expect.objectContaining({
            kind: 'approval',
            id: 'perm-1',
            approvalId: 'perm-1',
            status: 'approval_required',
            traceId: 'trace-web-1',
            runId: 'run-web-1',
            sessionId: 'web-1',
            source: 'session-replay',
          }),
          expect.objectContaining({
            kind: 'run',
            id: 'wf-1',
            status: 'approval_required',
            parentId: 'task-web-1',
          }),
          expect.objectContaining({
            kind: 'artifact',
            artifactId: 'artifact-1',
            status: 'completed',
            metadata: expect.objectContaining({
              replayStepId: 'artifact:artifact-1',
              targetId: 'task-web-1',
            }),
          }),
        ]),
      }),
    );
  });
});
