import { WebAppOperationsDepsBridgeService } from '../../src/services/WebAppOperationsDepsBridgeService.js';

describe('WebAppOperationsDepsBridgeService', () => {
  it('builds the WebApp operations deps from the dashboard composition source', () => {
    const bridge = new WebAppOperationsDepsBridgeService();
    const adapters = [{ id: 'web' }, { id: 'telegram' }] as any;
    const source = {
      channelActions: { id: 'channelActions' },
      channelMesh: { id: 'channelMesh' },
      gateway: { id: 'gateway' },
      hookPipeline: { id: 'hookPipeline' },
      hookPlane: { id: 'hookPlane' },
      memoryPlane: { id: 'memoryPlane' },
      layeredMemory: { id: 'layeredMemory' },
      learningPlane: { id: 'learningPlane' },
      nodeMesh: { id: 'nodeMesh' },
      nodeHeartbeat: { id: 'nodeHeartbeat' },
      nodeInvoke: { id: 'nodeInvoke' },
      nodePairing: { id: 'nodePairing' },
      pluginActions: { id: 'pluginActions' },
      platformActions: { id: 'platformActions' },
      pluginRegistry: { id: 'pluginRegistry' },
      platformRegistry: { id: 'platformRegistry' },
      platformCatalogSync: { id: 'platformCatalogSync' },
      platformPublisher: { id: 'platformPublisher' },
      remoteTransportDoctor: { id: 'remoteTransportDoctor' },
      remoteTransportActions: { id: 'remoteTransportActions' },
      remoteTransports: { id: 'remoteTransports' },
      securityMesh: { id: 'securityMesh' },
      sessionPlane: { id: 'sessionPlane' },
      sessionTools: { id: 'sessionTools' },
      agentOperatingSystem: { id: 'agentOperatingSystem' },
      agentOperatingSystemActions: { id: 'agentOperatingSystemActions' },
      toolSurface: { id: 'toolSurface' },
      capabilityCatalog: { id: 'capabilityCatalog' },
      runtimeModes: { id: 'runtimeModes' },
      teamCatalog: { id: 'teamCatalog' },
      tenantGovernance: { id: 'tenantGovernance' },
      tenantGovernanceActions: { id: 'tenantGovernanceActions' },
      codexRemote: { id: 'codexRemote' },
      codexRemoteActions: { id: 'codexRemoteActions' },
      integrationHub: { id: 'integrationHub' },
      providerControlPlane: { id: 'providerControlPlane' },
      workspaceExtensions: { id: 'workspaceExtensions' },
      operatorBrief: { id: 'operatorBrief' },
      operationsHealth: { id: 'operationsHealth' },
      operationsActions: { id: 'operationsActions' },
      productObservability: { id: 'productObservability' },
      zavorthBridgeMobileAccess: { id: 'zavorthBridgeMobileAccess' },
      mcpCapabilityControlPlane: { id: 'mcpCapabilityControlPlane' },
      mcpRuntime: { id: 'mcpRuntime' },
      mcpBrowserDoctor: { id: 'mcpBrowserDoctor' },
      AIGatewayGateway: { id: 'AIGatewayGateway' },
      AIGatewayGatewayLauncher: { id: 'AIGatewayGatewayLauncher' },
      AIGatewayCompatibilityDoctor: { id: 'AIGatewayCompatibilityDoctor' },
      AIGatewayUpstreamSync: { id: 'AIGatewayUpstreamSync' },
      buildRuntimeChannelAdapters: jest.fn(() => adapters),
    } as any;

    const deps = bridge.build(source);

    expect(source.buildRuntimeChannelAdapters).toHaveBeenCalledTimes(1);
    expect(deps.runtimeChannelAdapters).toEqual(adapters);
    expect(deps.runtimeChannelAdapters).not.toBe(adapters);
    expect(deps).toEqual({
      channelActionService: source.channelActions,
      channelMeshService: source.channelMesh,
      gatewayService: source.gateway,
      hookPipelineService: source.hookPipeline,
      hookPlaneService: source.hookPlane,
      memoryPlaneService: source.memoryPlane,
      layeredMemoryService: source.layeredMemory,
      learningPlaneService: source.learningPlane,
      nodeMeshService: source.nodeMesh,
      nodeHeartbeatService: source.nodeHeartbeat,
      nodeInvokeService: source.nodeInvoke,
      nodePairingService: source.nodePairing,
      pluginActionService: source.pluginActions,
      platformActionService: source.platformActions,
      pluginRegistryService: source.pluginRegistry,
      platformRegistryService: source.platformRegistry,
      platformCatalogSyncService: source.platformCatalogSync,
      platformPublisherService: source.platformPublisher,
      remoteTransportDoctorService: source.remoteTransportDoctor,
      remoteTransportActionService: source.remoteTransportActions,
      remoteTransportService: source.remoteTransports,
      securityMeshService: source.securityMesh,
      sessionPlaneService: source.sessionPlane,
      sessionToolsService: source.sessionTools,
      agentOperatingSystemService: source.agentOperatingSystem,
      agentOperatingSystemActionService: source.agentOperatingSystemActions,
      toolSurfaceService: source.toolSurface,
      capabilityCatalogService: source.capabilityCatalog,
      runtimeModesService: source.runtimeModes,
      teamCatalogService: source.teamCatalog,
      tenantGovernanceService: source.tenantGovernance,
      tenantGovernanceActionService: source.tenantGovernanceActions,
      codexRemoteControlPlaneService: source.codexRemote,
      codexRemoteActionService: source.codexRemoteActions,
      integrationHubService: source.integrationHub,
      providerControlPlaneService: source.providerControlPlane,
      workspaceExtensionRegistryService: source.workspaceExtensions,
      operatorBriefService: source.operatorBrief,
      operationsHealthService: source.operationsHealth,
      operationsActionService: source.operationsActions,
      productObservabilityService: source.productObservability,
      zavorthBridgeMobileAccessService: source.zavorthBridgeMobileAccess,
      mcpCapabilityControlPlaneService: source.mcpCapabilityControlPlane,
      mcpRuntimeService: source.mcpRuntime,
      mcpBrowserDoctorService: source.mcpBrowserDoctor,
      AIGatewayGatewayService: source.AIGatewayGateway,
      AIGatewayGatewayLauncherService: source.AIGatewayGatewayLauncher,
      GatewayCompatibilityDoctorService: source.AIGatewayCompatibilityDoctor,
      GatewayUpstreamSyncService: source.AIGatewayUpstreamSync,
      runtimeChannelAdapters: adapters,
    });
  });
});
