import type { ZavorthProviderReadinessMatrixSnapshot } from '../../src/contracts/ZavorthProviderReadinessMatrixContract.js';
import { ZavorthProviderModelCatalogService } from '../../src/services/ZavorthProviderModelCatalogService.js';

describe('ZavorthProviderModelCatalogService', () => {
  it('merges provider readiness, static catalog models, and sanitized live evidence', async () => {
    const service = new ZavorthProviderModelCatalogService({
      now: () => new Date('2026-05-17T12:00:00.000Z'),
      providerReadiness: {
        buildLiveSnapshot: jest.fn(async () => matrixFixture()),
      },
      modelCatalog: {
        aggregate: jest.fn(() => ({
          schemaVersion: 1,
          generatedAt: '2026-05-17T12:00:00.000Z',
          catalogs: [],
          families: [],
          models: [
            {
              id: 'openrouter/openrouter/auto',
              object: 'model',
              providerId: 'openrouter',
              providerAlias: 'openrouter',
              providerLabel: 'OpenRouter',
              routeId: 'openrouter',
              familyId: 'openrouter',
              ownedBy: 'openrouter',
              root: 'openrouter/auto',
              parent: null,
              name: 'OpenRouter Auto',
              type: 'chat',
              custom: false,
              imported: false,
              source: 'provider_catalog',
              active: true,
              capabilities: { chat: true, tool_use: true },
              modalities: ['text', 'tool'],
              contextLength: null,
              dimensions: null,
              supportedEndpoints: [],
              supportedSizes: [],
              subtype: null,
              apiFormat: null,
            },
            {
              id: 'nanobanana/nanobanana-image',
              object: 'model',
              providerId: 'nanobanana',
              providerAlias: 'nanobanana',
              providerLabel: 'Nano Banana',
              routeId: 'nanobanana',
              familyId: 'nanobanana',
              ownedBy: 'nanobanana',
              root: 'nanobanana-image',
              parent: null,
              name: 'Nano Banana Image',
              type: 'image',
              custom: false,
              imported: false,
              source: 'provider_catalog',
              active: false,
              capabilities: { vision: true },
              modalities: ['image'],
              contextLength: null,
              dimensions: null,
              supportedEndpoints: [],
              supportedSizes: [],
              subtype: null,
              apiFormat: null,
            },
          ],
          sources: ['provider_catalog'],
          sourceCounts: { provider_catalog: 2 },
        })),
      },
    });

    const snapshot = await service.buildSnapshot();

    expect(snapshot).toEqual(expect.objectContaining({
      contractVersion: '2026-05-17.provider-model-catalog.v1',
      surface: 'provider-model-catalog',
      status: 'attention',
      dashboardProjection: expect.objectContaining({
        endpoint: '/api/providers/model-catalog',
        executionAuthority: false,
        normalRenderMakesNoNetworkCalls: true,
      }),
      safety: expect.objectContaining({
        noRawProviderSecrets: true,
        catalogIsNotLiveProof: true,
      }),
    }));
    expect(snapshot.summary).toEqual(expect.objectContaining({
      providerRoutes: 2,
      liveReadyRoutes: 1,
      staticCatalogModels: 2,
      liveDiscoveredModels: 356,
      effectiveModelSurface: 357,
    }));
    expect(snapshot.sections.aggregators).toContain('openrouter');
    expect(snapshot.sections.mediaCapable).toContain('nanobanana');
    expect(snapshot.providers.find((entry) => entry.id === 'openrouter')).toEqual(expect.objectContaining({
      liveDiscoveredModelCount: 356,
      effectiveModelCount: 356,
      modelSample: expect.arrayContaining(['openrouter/auto']),
    }));
    expect(JSON.stringify(snapshot)).not.toContain('sk-test');
  });
});

function matrixFixture(): ZavorthProviderReadinessMatrixSnapshot {
  return {
    contractVersion: '2026-05-14.checkpoint-3-live-completion',
    schemaVersion: 1,
    surface: 'provider-readiness-matrix',
    generatedAt: '2026-05-17T12:00:00.000Z',
    status: 'ready',
    activeProvider: 'openrouter',
    activeModel: 'openrouter/auto',
    summary: {
      total: 2,
      ready: 1,
      livePassed: 1,
      liveFailed: 0,
      liveBlocked: 1,
      liveNotRun: 0,
      liveReady: 1,
      catalogReadyButNotLive: 1,
      defaultRouteAllowed: 1,
      missingAuth: 0,
      missingBaseUrl: 0,
      needsProbe: 0,
      degraded: 0,
      unsupported: 0,
      blocked: 0,
    },
    entries: [
      {
        id: 'openrouter',
        label: 'OpenRouter',
        providerName: 'openrouter',
        providerId: 'openrouter',
        familyIds: ['openrouter'],
        routeKind: 'aggregator',
        routeClass: 'aggregator',
        mode: 'cloud',
        credentialKind: 'api_key',
        credentialRefs: ['OPENROUTER_API_KEY'],
        requirements: ['OPENROUTER_API_KEY'],
        currentModelName: 'openrouter/auto',
        capabilities: ['chat', 'tool_use'],
        status: 'ready',
        catalogReady: true,
        liveReady: true,
        defaultRouteAllowed: true,
        readinessProof: 'live_probe',
        defaultBlockReason: null,
        authConfigured: true,
        baseUrlConfigured: true,
        discoverySupported: true,
        health: null,
        issue: null,
        explanation: [],
        userAction: 'Provider can be selected.',
        testCommand: 'zavorth providers test openrouter',
        probe: {
          status: 'passed',
          mode: 'explicit_live_probe',
          liveNetworkUsed: true,
          requestedAt: '2026-05-17T12:00:00.000Z',
          completedAt: '2026-05-17T12:00:01.000Z',
          durationMs: 200,
          target: 'https://openrouter.ai/api/v1/models',
          httpStatus: 200,
          modelCount: 356,
          evidenceHash: 'sha256:evidence',
          summary: 'Live probe passed; listed 356 model(s).',
        },
        rawSecretsPresent: false,
      },
      {
        id: 'nanobanana',
        label: 'Nano Banana',
        providerName: 'nanobanana',
        providerId: 'nanobanana',
        familyIds: ['nanobanana'],
        routeKind: 'partner',
        routeClass: 'partner',
        mode: 'cloud',
        credentialKind: 'api_key',
        credentialRefs: ['NANOBANANA_API_KEY'],
        requirements: ['NANOBANANA_API_KEY'],
        currentModelName: 'nanobanana-image',
        capabilities: ['vision', 'multimodal'],
        status: 'ready',
        catalogReady: true,
        liveReady: false,
        defaultRouteAllowed: false,
        readinessProof: 'catalog',
        defaultBlockReason: 'Provider is configured, but default routing requires live health evidence or an explicit live probe.',
        authConfigured: true,
        baseUrlConfigured: true,
        discoverySupported: false,
        health: null,
        issue: null,
        explanation: [],
        userAction: 'Run live proof before default routing.',
        testCommand: 'zavorth providers test nanobanana',
        probe: {
          status: 'ready_to_probe',
          mode: 'catalog_only',
          liveNetworkUsed: false,
          requestedAt: null,
          completedAt: null,
          durationMs: null,
          target: null,
          httpStatus: null,
          modelCount: null,
          evidenceHash: null,
          summary: 'Ready for explicit probe.',
        },
        rawSecretsPresent: false,
      },
    ],
    profiles: [],
    simpleCatalog: {
      fastAndCheap: ['openrouter'],
      higherIntelligence: ['openrouter'],
      localPrivate: [],
      openAiCompatible: ['openrouter'],
    },
    liveCompletion: {
      providerSelectionRequiresLiveProof: true,
      catalogSupportIsNotLiveProof: true,
      liveProbeRequiresExplicitOperatorAction: true,
      rawSecretsSerialized: false,
      publicApiProviderTestEndpoint: '/api/v1/providers/:id/test',
      defaultRoutingPolicy: 'ready-and-live-proof',
      counts: {
        catalogReady: 1,
        liveReady: 1,
        catalogReadyButNotLive: 1,
        defaultRouteAllowed: 1,
      },
    },
    commands: [],
    dashboardProjection: {
      route: '/zavorthControl',
      endpoint: '/api/providers/readiness',
      executionAuthority: false,
      canRenderTestButtons: true,
    },
    invariants: [],
    nextAction: 'Provider live evidence is available.',
  };
}
