import type {
  UniversalAgentExecutorResult,
  UniversalAgentRequest,
  UniversalAgentRun,
} from './UniversalAgentRuntimeTypes.js';

export const NATURAL_FIRST_LLM_RUNTIME_CONTRACT_VERSION = 'natural-first-llm-runtime/5' as const;

export type NaturalFirstLlmRuntimeSnapshot = {
  contractVersion: typeof NATURAL_FIRST_LLM_RUNTIME_CONTRACT_VERSION;
  source: 'NaturalFirstLlmRuntime';
  stage: 5;
  gate: 'source-memory-document-terminal-pack';
  route: 'llm-reply';
  providerConfigured: boolean;
  providerUsed: boolean;
  fallbackUsed: boolean;
  generatedBy: 'llm-runtime' | 'honest-local-fallback';
  summary: string;
  nextSafeAction: string;
  safety: {
    noToolExecution: true;
    noApprovalBypass: true;
    noExternalProviderCall: boolean;
    didNotClaimExecution: true;
  };
};

function normalizeText(value: unknown): string {
  return String(value ?? '').trim();
}

function recordOrNull(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

export function isNaturalFirstLlmReplyRun(run: UniversalAgentRun): boolean {
  return recordOrNull(run.metadata.naturalFirstRoute)?.route === 'llm-reply';
}

export function buildNaturalFirstLlmRuntimeSnapshot(input: {
  providerConfigured: boolean;
  providerUsed: boolean;
  fallbackUsed: boolean;
  generatedBy: NaturalFirstLlmRuntimeSnapshot['generatedBy'];
  providerName?: string | null;
  modelName?: string | null;
}): NaturalFirstLlmRuntimeSnapshot & {
  providerName?: string | null;
  modelName?: string | null;
} {
  const providerName = normalizeText(input.providerName) || null;
  const modelName = normalizeText(input.modelName) || null;
  return {
    contractVersion: NATURAL_FIRST_LLM_RUNTIME_CONTRACT_VERSION,
    source: 'NaturalFirstLlmRuntime',
    stage: 5,
    gate: 'source-memory-document-terminal-pack',
    route: 'llm-reply',
    providerConfigured: input.providerConfigured,
    providerUsed: input.providerUsed,
    fallbackUsed: input.fallbackUsed,
    generatedBy: input.generatedBy,
    ...(providerName ? { providerName } : {}),
    ...(modelName ? { modelName } : {}),
    summary: input.providerUsed ? 'Natural answer generated by the configured model.'
      : 'A model is not configured yet, so Zavorth answered with setup guidance only.',
    nextSafeAction: input.providerUsed ? 'Continue normally. Tools stay governed when needed.'
      : 'Connect a model, choose a local model, or ask Zavorth to guide setup.',
    safety: {
      noToolExecution: true,
      noApprovalBypass: true,
      noExternalProviderCall: !input.providerUsed,
      didNotClaimExecution: true,
    },
  };
}

export class NaturalFirstLlmFallbackService {
  public shouldHandle(run: UniversalAgentRun): boolean {
    return isNaturalFirstLlmReplyRun(run);
  }

  public buildResult(
    run: UniversalAgentRun,
    request: UniversalAgentRequest,
  ): UniversalAgentExecutorResult {
    const snapshot = buildNaturalFirstLlmRuntimeSnapshot({
      providerConfigured: false,
      providerUsed: false,
      fallbackUsed: true,
      generatedBy: 'honest-local-fallback',
    });
    const text = normalizeText(request.text || run.input);
    const replyText = [
      'Zavorth can receive this request, but no model is configured yet.',
      '',
      text ? `Received: "${text}".`
        : 'I did not receive enough text to answer precisely.',
      '',
      'Next: tell me which provider to use, choose a local model, or run the guided setup.',
    ].join('\n');

    return {
      status: 'completed',
      summary: snapshot.summary,
      replyText,
      events: [
        {
          kind: 'reply',
          title: 'Model setup needed',
          detail: 'No model was configured; Zavorth did not call tools or pretend a model answered.',
          status: 'done',
          metadata: snapshot,
        },
      ],
      metadata: {
        naturalFirstLlmRuntime: snapshot,
        executorResolution: {
          source: 'NaturalFirstLlmFallbackService',
          status: 'missing-llm-provider',
          route: 'llm-reply',
          gracefulFallback: true,
          requires: ['llmRuntime'],
        },
      },
    };
  }
}
