import type {
  CapabilityNormalizationFamily,
  CapabilityPrimitiveDefinition,
} from '../contracts/CapabilityNormalizationContract.js';
import type {
  ZavorthPluginModuleKind,
  ZavorthPluginPermission,
} from '../contracts/PluginManifestContract.js';

export type SourceGroup = {
  family: CapabilityNormalizationFamily;
  primitiveId: string;
  moduleKind: ZavorthPluginModuleKind;
  names: string[];
};

const permission = (
  kind: ZavorthPluginPermission['kind'],
  scope: ZavorthPluginPermission['scope'],
  reason: string,
  required = true,
): ZavorthPluginPermission => ({
  kind,
  scope,
  reason,
  required,
});

export const PRIMITIVES: CapabilityPrimitiveDefinition[] = [
  primitive({
    primitiveId: 'agent.runtime',
    label: 'Agent Runtime',
    family: 'agent',
    intent: 'agent_runtime',
    summary: 'Runs governed agent harnesses, model catalogs, tools, approvals, transcripts, and runtime control planes.',
    moduleKind: 'agent',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/CodexRuntimeContract.ts',
    serviceTarget: 'src/services/CodexRuntimePlaneService.ts',
    adapterTarget: 'src/adapters/codex',
    policyTarget: 'src/security',
    commandName: 'agent',
    artifactKinds: ['agent.session', 'agent.transcript', 'agent.trajectory'],
    receiptKinds: ['agent.runtime.receipt'],
    permissions: [
      permission('provider.call', 'external', 'Agent runtimes can route model calls through governed provider surfaces.'),
      permission('process.spawn', 'workspace', 'Agent runtimes may launch local runtime sidecars or CLI brokers.', true),
      permission('filesystem.read', 'workspace', 'Agent runtimes read scoped workspace context and runtime state.', false),
      permission('artifact.read', 'workspace', 'Agent runtimes can consume artifacts as run input.', false),
      permission('artifact.write', 'workspace', 'Agent runtimes write transcripts, trajectories, and run receipts.', true),
      permission('secret.read', 'workspace', 'Agent runtimes may need scoped profile or account references.', true),
    ],
  }),
  primitive({
    primitiveId: 'provider.call',
    label: 'Provider Call',
    family: 'provider',
    intent: 'provider_routing',
    summary: 'Routes model, embedding, rerank, and multimodal provider calls through Provider Mesh.',
    moduleKind: 'provider',
    runtimeStatus: 'needs-runtime-proof',
    contractTarget: 'src/contracts/ModelPickerContract.ts',
    serviceTarget: 'src/services/providers',
    adapterTarget: 'src/providers',
    policyTarget: 'src/security',
    commandName: null,
    artifactKinds: ['provider.response'],
    receiptKinds: ['provider.call.receipt'],
    permissions: [
      permission('provider.call', 'external', 'Provider modules call external or local model runtimes.'),
      permission('secret.read', 'workspace', 'Provider modules need scoped credentials.', true),
      permission('artifact.write', 'workspace', 'Provider responses can be captured as artifacts.', false),
    ],
  }),
  primitive({
    primitiveId: 'channel.message',
    label: 'Channel Message',
    family: 'channel',
    intent: 'channel_messaging',
    summary: 'Normalizes inbound and outbound channel messages into the Channel Mesh.',
    moduleKind: 'channel',
    runtimeStatus: 'needs-runtime-proof',
    contractTarget: 'src/contracts/ChannelMeshContract.ts',
    serviceTarget: 'src/services/GatewayChannelRegistryService.ts',
    adapterTarget: 'src/channels',
    policyTarget: 'src/security',
    commandName: null,
    artifactKinds: ['channel.message', 'channel.attachment'],
    receiptKinds: ['channel.delivery.receipt'],
    permissions: [
      permission('channel.send', 'external', 'Channel modules send outbound messages.'),
      permission('secret.read', 'workspace', 'Channel modules need scoped bot or webhook credentials.', true),
      permission('artifact.read', 'workspace', 'Channel modules can render artifacts into messages.', false),
    ],
  }),
  primitive({
    primitiveId: 'media.generate',
    label: 'Media Generate',
    family: 'media',
    intent: 'media_generation',
    summary: 'Generates image, video, or audio outputs as Zavorth artifacts.',
    moduleKind: 'media',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MediaGenerationContract.ts',
    serviceTarget: 'src/services/MediaGenerationService.ts',
    adapterTarget: 'src/adapters/media',
    policyTarget: 'src/security',
    commandName: 'imagine',
    artifactKinds: ['media.image', 'media.video', 'media.audio'],
    receiptKinds: ['media.generate.receipt'],
    permissions: [
      permission('provider.call', 'external', 'Media generation delegates to a governed provider adapter.'),
      permission('artifact.write', 'workspace', 'Generated media must be stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'media.understand',
    label: 'Media Understand',
    family: 'media',
    intent: 'media_understanding',
    summary: 'Analyzes image, audio, or video artifacts and returns structured findings.',
    moduleKind: 'media',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MediaUnderstandingContract.ts',
    serviceTarget: 'src/services/MediaUnderstandingService.ts',
    adapterTarget: 'src/adapters/media',
    policyTarget: 'src/security',
    commandName: 'analyze',
    artifactKinds: ['media.analysis'],
    receiptKinds: ['media.understand.receipt'],
    permissions: [
      permission('artifact.read', 'workspace', 'Media understanding reads local artifacts.'),
      permission('provider.call', 'external', 'Analysis can call vision, audio, or video models.'),
      permission('artifact.write', 'workspace', 'Structured analysis is written as an artifact.'),
    ],
  }),
  primitive({
    primitiveId: 'search.query',
    label: 'Search Query',
    family: 'search',
    intent: 'web_search',
    summary: 'Runs search with normalized results, citations, and provider evidence.',
    moduleKind: 'search',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/SearchQueryContract.ts',
    serviceTarget: 'src/services/SearchQueryService.ts',
    adapterTarget: 'src/adapters/search',
    policyTarget: 'src/security',
    commandName: 'search',
    artifactKinds: ['search.result', 'search.citation'],
    receiptKinds: ['search.query.receipt'],
    permissions: [
      permission('network.external', 'external', 'Search modules call external or self-hosted search APIs.'),
      permission('artifact.write', 'workspace', 'Search results and citations can be stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'web.extract',
    label: 'Web Extract',
    family: 'browser',
    intent: 'web_extraction',
    summary: 'Extracts readable page content, browser captures, or crawl evidence.',
    moduleKind: 'tool',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/SearchQueryContract.ts',
    serviceTarget: 'src/services/WebExtractService.ts',
    adapterTarget: 'src/adapters/search',
    policyTarget: 'src/security',
    commandName: 'extract',
    artifactKinds: ['web.page', 'web.excerpt', 'browser.capture'],
    receiptKinds: ['web.extract.receipt'],
    permissions: [
      permission('network.external', 'external', 'Web extraction fetches pages or browser targets.'),
      permission('artifact.write', 'workspace', 'Extracted pages are stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'sandbox.remote',
    label: 'Remote Sandbox',
    family: 'sandbox',
    intent: 'remote_sandbox',
    summary: 'Runs remote sandbox backends with governed lifecycle, shell transport, workspace bridging, artifacts, and approvals.',
    moduleKind: 'sandbox',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/RemoteSandboxContract.ts',
    serviceTarget: 'src/services/OpenShellRemoteSandboxService.ts',
    adapterTarget: 'src/adapters/sandbox',
    policyTarget: 'src/services/sandbox/SandboxPolicyService.ts',
    commandName: 'sandbox',
    artifactKinds: ['sandbox.session', 'sandbox.command', 'sandbox.workspace-delta'],
    receiptKinds: ['sandbox.remote.receipt'],
    permissions: [
      permission('process.spawn', 'workspace', 'Remote sandbox modules may launch local CLI or SSH transport helpers.', true),
      permission('network.local', 'local', 'Remote sandbox modules can connect to local or configured sandbox gateways.', true),
      permission('filesystem.read', 'workspace', 'Remote sandbox modules stage scoped workspace input.', false),
      permission('filesystem.write', 'workspace', 'Remote sandbox modules can apply approved workspace deltas.', false),
      permission('artifact.write', 'workspace', 'Remote sandbox results and deltas are captured as artifacts.', true),
    ],
  }),
  primitive({
    primitiveId: 'speech.transcribe',
    label: 'Speech Transcribe',
    family: 'voice',
    intent: 'speech_transcription',
    summary: 'Transcribes audio artifacts or streams into structured text artifacts.',
    moduleKind: 'voice',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/SpeechContract.ts',
    serviceTarget: 'src/services/SpeechRuntimeService.ts',
    adapterTarget: 'src/voice',
    policyTarget: 'src/security',
    commandName: 'transcribe',
    artifactKinds: ['speech.transcript'],
    receiptKinds: ['speech.transcribe.receipt'],
    permissions: [
      permission('artifact.read', 'workspace', 'Speech modules read audio artifacts.'),
      permission('provider.call', 'external', 'Speech modules can call transcription providers.'),
      permission('artifact.write', 'workspace', 'Transcripts are written as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'speech.synthesize',
    label: 'Speech Synthesize',
    family: 'voice',
    intent: 'speech_synthesis',
    summary: 'Synthesizes speech as governed audio artifacts.',
    moduleKind: 'voice',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/SpeechContract.ts',
    serviceTarget: 'src/services/SpeechRuntimeService.ts',
    adapterTarget: 'src/voice',
    policyTarget: 'src/security',
    commandName: 'speak',
    artifactKinds: ['speech.audio'],
    receiptKinds: ['speech.synthesize.receipt'],
    permissions: [
      permission('provider.call', 'external', 'Speech synthesis can call TTS providers.'),
      permission('artifact.write', 'workspace', 'Generated speech is stored as an artifact.'),
    ],
  }),
  primitive({
    primitiveId: 'voice.session',
    label: 'Voice Session',
    family: 'voice',
    intent: 'voice_session',
    summary: 'Runs consent-aware voice or call sessions with receipts.',
    moduleKind: 'voice',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/VoiceSessionContract.ts',
    serviceTarget: 'src/services/VoiceSessionService.ts',
    adapterTarget: 'src/voice',
    policyTarget: 'src/security',
    commandName: 'voice',
    artifactKinds: ['voice.session', 'speech.transcript'],
    receiptKinds: ['voice.session.receipt'],
    permissions: [
      permission('channel.send', 'external', 'Voice sessions can bridge channel or call providers.'),
      permission('provider.call', 'external', 'Voice sessions can call speech providers.'),
      permission('artifact.write', 'workspace', 'Voice session transcripts are stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'memory.vector',
    label: 'Vector Memory',
    family: 'memory',
    intent: 'memory_vector',
    summary: 'Stores and retrieves vectorized memory anchored to artifacts and receipts.',
    moduleKind: 'memory',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MemoryArtifactsRuntimeLiveClosureContract.ts',
    serviceTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    adapterTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    policyTarget: 'src/security',
    commandName: 'memory',
    artifactKinds: ['memory.entry', 'memory.index'],
    receiptKinds: ['memory.vector.receipt'],
    permissions: [
      permission('memory.read', 'workspace', 'Vector memory retrieves scoped memory entries.'),
      permission('memory.write', 'workspace', 'Vector memory stores scoped memory entries.'),
    ],
  }),
  primitive({
    primitiveId: 'memory.active',
    label: 'Active Memory',
    family: 'memory',
    intent: 'memory_active',
    summary: 'Maintains active working memory for sessions, projects, and operators.',
    moduleKind: 'memory',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MemoryArtifactsRuntimeLiveClosureContract.ts',
    serviceTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    adapterTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    policyTarget: 'src/security',
    commandName: 'memory',
    artifactKinds: ['memory.active'],
    receiptKinds: ['memory.active.receipt'],
    permissions: [
      permission('memory.read', 'workspace', 'Active memory reads scoped context.'),
      permission('memory.write', 'workspace', 'Active memory writes scoped context.'),
    ],
  }),
  primitive({
    primitiveId: 'memory.wiki',
    label: 'Wiki Memory',
    family: 'memory',
    intent: 'memory_wiki',
    summary: 'Maintains durable knowledge pages and structured recall surfaces.',
    moduleKind: 'memory',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MemoryArtifactsRuntimeLiveClosureContract.ts',
    serviceTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    adapterTarget: 'src/services/MemoryWikiService.ts',
    policyTarget: 'src/security',
    commandName: 'wiki',
    artifactKinds: ['memory.wiki-page'],
    receiptKinds: ['memory.wiki.receipt'],
    permissions: [
      permission('memory.read', 'workspace', 'Wiki memory reads durable knowledge.'),
      permission('memory.write', 'workspace', 'Wiki memory writes durable knowledge.'),
    ],
  }),
  primitive({
    primitiveId: 'file.transfer',
    label: 'File Transfer',
    family: 'file',
    intent: 'file_transfer',
    summary: 'Transfers files through governed workspace and artifact boundaries.',
    moduleKind: 'tool',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/FileTransferContract.ts',
    serviceTarget: 'src/services/FileTransferService.ts',
    adapterTarget: 'src/adapters/file',
    policyTarget: 'src/security',
    commandName: 'transfer',
    artifactKinds: ['file.transfer'],
    receiptKinds: ['file.transfer.receipt'],
    permissions: [
      permission('filesystem.read', 'workspace', 'File transfer reads selected workspace files.'),
      permission('filesystem.write', 'workspace', 'File transfer writes selected workspace files.', true),
      permission('artifact.write', 'workspace', 'Transferred files are tracked as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'document.extract',
    label: 'Document Extract',
    family: 'document',
    intent: 'document_extraction',
    summary: 'Extracts text, tables, and metadata from documents into artifacts.',
    moduleKind: 'tool',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/DocumentExtractContract.ts',
    serviceTarget: 'src/services/DocumentExtractService.ts',
    adapterTarget: 'src/adapters/document',
    policyTarget: 'src/security',
    commandName: 'extract-document',
    artifactKinds: ['document.extracted'],
    receiptKinds: ['document.extract.receipt'],
    permissions: [
      permission('filesystem.read', 'workspace', 'Document extraction reads selected files.'),
      permission('artifact.write', 'workspace', 'Extracted document content is stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'artifact.diff',
    label: 'Artifact Diff',
    family: 'artifact',
    intent: 'artifact_diff',
    summary: 'Creates governed diffs for files, artifacts, and proposed changes.',
    moduleKind: 'tool',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/ArtifactDiffContract.ts',
    serviceTarget: 'src/services/ArtifactDiffService.ts',
    adapterTarget: 'src/adapters/files/FileDocumentDiffLiveAdapters.ts',
    policyTarget: 'src/security',
    commandName: 'diff',
    artifactKinds: ['artifact.diff'],
    receiptKinds: ['artifact.diff.receipt'],
    permissions: [
      permission('filesystem.read', 'workspace', 'Diff tools read selected files.'),
      permission('artifact.write', 'workspace', 'Diff outputs are stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'diagnostics.trace',
    label: 'Diagnostics Trace',
    family: 'diagnostics',
    intent: 'diagnostics_trace',
    summary: 'Exports traces, metrics, and health signals through observability adapters.',
    moduleKind: 'diagnostics',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/DiagnosticsContract.ts',
    serviceTarget: 'src/services/DiagnosticsTraceService.ts',
    adapterTarget: 'src/adapters/diagnostics/DiagnosticsQaMigrationLiveAdapters.ts',
    policyTarget: 'src/security',
    commandName: 'diagnostics',
    artifactKinds: ['diagnostics.report'],
    receiptKinds: ['diagnostics.trace.receipt'],
    permissions: [
      permission('network.local', 'local', 'Diagnostics can expose local scrape or trace endpoints.', false),
      permission('artifact.write', 'workspace', 'Diagnostics snapshots are stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'qa.scenario',
    label: 'QA Scenario',
    family: 'qa',
    intent: 'qa_scenario',
    summary: 'Runs simulated provider, channel, capability, and release parity scenarios.',
    moduleKind: 'qa',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/QaSmokeMatrixContract.ts',
    serviceTarget: 'src/services/QaSmokeMatrixService.ts',
    adapterTarget: 'src/services/QaSmokeMatrixService.ts',
    policyTarget: 'src/security',
    commandName: 'qa',
    artifactKinds: ['qa.report'],
    receiptKinds: ['qa.scenario.receipt'],
    permissions: [
      permission('artifact.write', 'workspace', 'QA scenario results are stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'device.invoke',
    label: 'Device Invoke',
    family: 'device',
    intent: 'device_invocation',
    summary: 'Invokes paired Node Mesh or Satellite devices through governed capabilities.',
    moduleKind: 'bridge',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/SatelliteDeviceLivePlaneContract.ts',
    serviceTarget: 'src/services/SatelliteDeviceLiveService.ts',
    adapterTarget: 'src/services/NodeHostCapabilityService.ts',
    policyTarget: 'src/security',
    commandName: 'satellite',
    artifactKinds: ['device.invocation', 'satellite.device.receipt'],
    receiptKinds: ['device.invoke.receipt', 'satellite.device.live.receipt'],
    permissions: [
      permission('node.invoke', 'workspace', 'Device modules invoke approved Node Mesh capabilities.'),
      permission('artifact.write', 'workspace', 'Device invocation receipts are stored as artifacts.', false),
    ],
  }),
  primitive({
    primitiveId: 'bridge.protocol',
    label: 'Bridge Protocol',
    family: 'bridge',
    intent: 'bridge_protocol',
    summary: 'Bridges MCP, ACP, and external protocol capabilities through quarantine policy.',
    moduleKind: 'bridge',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MemoryArtifactsRuntimeLiveClosureContract.ts',
    serviceTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    adapterTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    policyTarget: 'src/security',
    commandName: 'mcp',
    artifactKinds: ['bridge.protocol'],
    receiptKinds: ['bridge.protocol.receipt'],
    permissions: [
      permission('network.local', 'local', 'Bridge modules can connect to local protocol servers.'),
      permission('process.spawn', 'workspace', 'Bridge modules may launch local protocol sidecars.', true),
    ],
  }),
  primitive({
    primitiveId: 'migration.import',
    label: 'Migration Import',
    family: 'migration',
    intent: 'migration_import',
    summary: 'Imports private inventories, settings, or compatibility state into Zavorth forms.',
    moduleKind: 'tool',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MigrationContract.ts',
    serviceTarget: 'src/services/MigrationImportService.ts',
    adapterTarget: 'src/services/MigrationImportService.ts',
    policyTarget: 'src/security',
    commandName: 'migrate',
    artifactKinds: ['migration.report'],
    receiptKinds: ['migration.import.receipt'],
    permissions: [
      permission('filesystem.read', 'workspace', 'Migration reads selected private source files.'),
      permission('artifact.write', 'workspace', 'Migration reports are stored as artifacts.'),
    ],
  }),
  primitive({
    primitiveId: 'workspace.command',
    label: 'Workspace Command',
    family: 'workspace',
    intent: 'workspace_command',
    summary: 'Exposes workspace-local commands and module authoring helpers through review policy.',
    moduleKind: 'workspace',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MemoryArtifactsRuntimeLiveClosureContract.ts',
    serviceTarget: 'src/services/PluginRegistryService.ts',
    adapterTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    policyTarget: 'src/security',
    commandName: 'workspace',
    artifactKinds: ['workspace.command'],
    receiptKinds: ['workspace.command.receipt'],
    permissions: [
      permission('process.spawn', 'workspace', 'Workspace commands may spawn local commands after policy review.', true),
      permission('filesystem.read', 'workspace', 'Workspace commands read local workspace context.', false),
    ],
  }),
  primitive({
    primitiveId: 'task.orchestrate',
    label: 'Task Orchestrate',
    family: 'task',
    intent: 'task_orchestration',
    summary: 'Normalizes task plugins into agent workflow and task orchestration services.',
    moduleKind: 'module',
    runtimeStatus: 'native-contract',
    contractTarget: 'src/contracts/MemoryArtifactsRuntimeLiveClosureContract.ts',
    serviceTarget: 'src/services/WorkflowRunService.ts',
    adapterTarget: 'src/services/MemoryArtifactsRuntimeLiveService.ts',
    policyTarget: 'src/security',
    commandName: 'tasks',
    artifactKinds: ['task.plan', 'task.result'],
    receiptKinds: ['task.orchestrate.receipt'],
    permissions: [
      permission('artifact.write', 'workspace', 'Task orchestration writes plan and result artifacts.'),
    ],
  }),
];

export const GROUPS: SourceGroup[] = [
  group('agent', 'agent.runtime', 'agent', [
    'codex',
  ]),
  group('provider', 'provider.call', 'provider', [
    'alibaba', 'amazon-bedrock', 'amazon-bedrock-mantle', 'anthropic', 'anthropic-vertex',
    'arcee', 'cerebras', 'chutes', 'cloudflare-ai-gateway', 'copilot-proxy', 'deepinfra',
    'deepseek', 'fireworks', 'github-copilot', 'google', 'gradium', 'groq', 'huggingface',
    'kilocode', 'kimi-coding', 'litellm', 'lmstudio', 'microsoft', 'microsoft-foundry',
    'mistral', 'moonshot', 'nvidia', 'ollama', 'openai', 'opencode', 'opencode-go',
    'openrouter', 'perplexity', 'qianfan', 'qwen', 'sglang', 'stepfun', 'tencent',
    'together', 'tokenjuice', 'venice', 'vercel-ai-gateway', 'vllm', 'voyage', 'xai',
    'xiaomi', 'zai',
  ]),
  group('channel', 'channel.message', 'channel', [
    'bluebubbles', 'discord', 'feishu', 'googlechat', 'imessage', 'irc', 'line', 'matrix',
    'mattermost', 'msteams', 'nextcloud-talk', 'nostr', 'qqbot', 'signal', 'slack',
    'synology-chat', 'telegram', 'tlon', 'twitch', 'webhooks', 'whatsapp', 'zalo', 'zalouser',
  ]),
  group('media', 'media.generate', 'media', [
    'byteplus', 'comfy', 'fal', 'image-generation-core', 'minimax', 'runway',
    'video-generation-core', 'volcengine',
  ]),
  group('media', 'media.understand', 'media', [
    'media-understanding-core',
  ]),
  group('search', 'search.query', 'search', [
    'brave', 'duckduckgo', 'exa', 'searxng', 'tavily',
  ]),
  group('browser', 'web.extract', 'tool', [
    'browser', 'firecrawl', 'web-readability',
  ]),
  group('sandbox', 'sandbox.remote', 'sandbox', [
    'openshell',
  ]),
  group('voice', 'speech.transcribe', 'voice', [
    'azure-speech', 'deepgram', 'senseaudio', 'speech-core',
  ]),
  group('voice', 'speech.synthesize', 'voice', [
    'elevenlabs', 'tts-local-cli',
  ]),
  group('voice', 'voice.session', 'voice', [
    'google-meet', 'inworld', 'talk-voice', 'voice-call',
  ]),
  group('memory', 'memory.active', 'memory', [
    'active-memory', 'memory-core', 'thread-ownership',
  ]),
  group('memory', 'memory.vector', 'memory', [
    'memory-lancedb',
  ]),
  group('memory', 'memory.wiki', 'memory', [
    'memory-wiki',
  ]),
  group('file', 'file.transfer', 'tool', [
    'file-transfer',
  ]),
  group('document', 'document.extract', 'tool', [
    'document-extract', 'lobster', 'open-prose',
  ]),
  group('artifact', 'artifact.diff', 'tool', [
    'diffs',
  ]),
  group('diagnostics', 'diagnostics.trace', 'diagnostics', [
    'diagnostics-otel', 'diagnostics-prometheus',
  ]),
  group('qa', 'qa.scenario', 'qa', [
    'qa-channel', 'qa-lab', 'qa-matrix', 'synthetic', 'test-support',
  ]),
  group('device', 'device.invoke', 'bridge', [
    'bonjour', 'device-pair', 'phone-control',
  ]),
  group('bridge', 'bridge.protocol', 'bridge', [
    'acpx',
  ]),
  group('migration', 'migration.import', 'tool', [
    'migrate-claude', 'migrate-hermes',
  ]),
  group('workspace', 'workspace.command', 'workspace', [
    'skill-workshop',
  ]),
  group('task', 'task.orchestrate', 'module', [
    'llm-task', 'vydra',
  ]),
];

export const DEFAULT_PRIVATE_CAPABILITY_SOURCE_MODULES = GROUPS
  .flatMap((groupItem) => groupItem.names)
  .sort((left, right) => left.localeCompare(right));


function primitive(definition: CapabilityPrimitiveDefinition): CapabilityPrimitiveDefinition {
  return definition;
}

function group(
  family: CapabilityNormalizationFamily,
  primitiveId: string,
  moduleKind: ZavorthPluginModuleKind,
  names: string[],
): SourceGroup {
  return {
    family,
    primitiveId,
    moduleKind,
    names,
  };
}
