import {
  ZAVORTH_DELEGATED_WORKER_BRIDGE_CONTRACT_VERSION,
  type ZavorthDelegatedTaskEnvelope,
  type ZavorthDelegatedTaskEnvelopeInput,
  type ZavorthDelegatedWorkerBridgeSnapshot,
  type ZavorthDelegatedWorkerBridgeStatus,
  type ZavorthDelegatedWorkerZavorthControlProjection,
  type ZavorthExecutorResultInput,
  type ZavorthExecutorResultMappingReceipt,
  type ZavorthSourceWorkerLaunchGateReceipt,
  type ZavorthWorkerDescriptor,
  type ZavorthWorkerDescriptorInput,
  type ZavorthWorkerLifecycleDryRunReceipt,
  type ZavorthWorkerTimeoutCancellationReceipt,
} from '../contracts/ZavorthDelegatedWorkerBridgeContract.js';
import type {
  ZavorthSessionMemoryContinuationStatus,
} from '../contracts/ZavorthSessionMemoryContinuationContract.js';

type Runtime = {
  now?: () => Date;
  sessionMemoryStatus?: ZavorthSessionMemoryContinuationStatus;
};

type SnapshotInput = {
  sessionMemoryStatus?: ZavorthSessionMemoryContinuationStatus | null;
};

const DEFAULT_WORKERS: ZavorthWorkerDescriptorInput[] = [
  {
    sourceRuntimeId: 'reference-runtime-a',
    sourceWorkerId: 'reader-worker',
    role: 'reader',
    health: 'ready',
    capabilities: ['read-repo', 'summarize-context'],
    maxRuntimeMs: 120000,
    canMutateFiles: false,
    requiresApprovalToLaunch: true,
  },
  {
    sourceRuntimeId: 'reference-runtime-b',
    sourceWorkerId: 'runner-worker',
    role: 'runner',
    health: 'degraded',
    capabilities: ['run-tests', 'inspect-output'],
    maxRuntimeMs: 180000,
    canMutateFiles: false,
    requiresApprovalToLaunch: true,
  },
];

export class ZavorthDelegatedWorkerBridgeService {
  private readonly now: () => Date;
  private readonly defaultSessionMemoryStatus: ZavorthSessionMemoryContinuationStatus;

  constructor(runtime: Runtime = {}) {
    this.now = runtime.now || (() => new Date());
    this.defaultSessionMemoryStatus = runtime.sessionMemoryStatus || 'session-memory-continuation-ready';
  }

  public buildSnapshot(input: SnapshotInput = {}): ZavorthDelegatedWorkerBridgeSnapshot {
    const previousSessionMemoryStatus = input.sessionMemoryStatus || this.defaultSessionMemoryStatus;
    const workerDescriptors = DEFAULT_WORKERS.map((worker) => this.normalizeWorkerDescriptor(worker));
    const delegatedTaskEnvelope = this.buildDelegatedTaskEnvelope({
      taskId: 'task-fixture-001',
      workerId: workerDescriptors[0].workerId,
      requestedBySessionId: 'zavorth.session.telegram.thread-fixture-001',
      objective: 'Read repository metadata and return a bounded summary artifact.',
      resourceRefs: ['repo://current', 'docs/product-direction.md'],
      risk: 'medium',
      timeoutMs: 120000,
      cancellationToken: 'cancel-task-fixture-001',
    });
    const timeoutCancellationReceipt = this.buildTimeoutCancellation(delegatedTaskEnvelope);
    const sourceWorkerLaunchGateReceipt = this.blockSourceWorkerLaunch(workerDescriptors[0], false);
    const lifecycleDryRunReceipt = this.buildLifecycleDryRun(delegatedTaskEnvelope, sourceWorkerLaunchGateReceipt);
    const executorResultMappingReceipt = this.mapExecutorResult({
      delegatedTaskId: delegatedTaskEnvelope.delegatedTaskId,
      workerId: delegatedTaskEnvelope.workerId,
      status: 'success',
      exitCode: 0,
      stdoutPreview: 'Repository summary generated by delegated worker fixture.',
      stderrPreview: '',
      artifactRefs: ['artifact://worker-summary-fixture'],
    });
    const acceptanceMatrix = buildAcceptanceMatrix(
      previousSessionMemoryStatus,
      workerDescriptors,
      delegatedTaskEnvelope,
      timeoutCancellationReceipt,
      sourceWorkerLaunchGateReceipt,
      lifecycleDryRunReceipt,
      executorResultMappingReceipt,
    );
    const status = resolveStatus(previousSessionMemoryStatus, acceptanceMatrix);
    const zavorthControlProjection = this.buildZavorthControlProjection({
      status,
      workerDescriptors,
      delegatedTaskEnvelope,
      timeoutCancellationReceipt,
      sourceWorkerLaunchGateReceipt,
      lifecycleDryRunReceipt,
      executorResultMappingReceipt,
    });

    return {
      generatedAt: this.now().toISOString(),
      contractVersion: ZAVORTH_DELEGATED_WORKER_BRIDGE_CONTRACT_VERSION,
      status,
      planId: 'Zavorth External Runtime Integration',
      phase: 'delegated-workers',
      previousSessionMemoryStatus,
      workerDescriptors,
      delegatedTaskEnvelope,
      timeoutCancellationReceipt,
      sourceWorkerLaunchGateReceipt,
      lifecycleDryRunReceipt,
      executorResultMappingReceipt,
      zavorthControlProjection,
      acceptanceMatrix,
      summary: {
        workerDescriptors: workerDescriptors.length,
        delegatedTaskEnvelopes: delegatedTaskEnvelope.status === 'dry-run-ready' ? 1 : 0,
        dryRunLifecycleReceipts: lifecycleDryRunReceipt.status === 'dry-run-ready' ? 1 : 0,
        timeoutPolicies: timeoutCancellationReceipt.timeoutPolicy ? 1 : 0,
        cancellationPolicies: timeoutCancellationReceipt.cancellationAvailable ? 1 : 0,
        sourceWorkerLaunchesBlocked: sourceWorkerLaunchGateReceipt.sourceWorkerLaunchBlocked ? 1 : 0,
        executorResultsMapped: executorResultMappingReceipt.status === 'mapped' ? 1 : 0,
        artifactEventsReturned: executorResultMappingReceipt.artifactEvents.length,
        liveWorkersStarted: 0,
        sourceRuntimeCodeExecuted: false,
        toolExecutionPerformed: false,
      },
      safety: {
        workerBridgeOnly: true,
        dispatchMode: 'zavorth-gateway-delegated-only',
        noSourceRuntimeCodeExecuted: true,
        noWorkerLaunchPerformed: true,
        noToolExecutionPerformed: true,
        noArtifactWritePerformed: true,
        noMemoryWritePerformed: true,
        approvalBypassAllowed: false,
        publicIdentityChanged: false,
      },
      commands: {
        inspect: 'npm run zavorth:delegated-worker-bridge',
        inspectJson: 'npm run zavorth:delegated-worker-bridge:json',
        check: 'npm run zavorth:delegated-worker-bridge:check --silent',
        nextStage: '291 ZavorthControl controls - Native Replacement And Decommission',
      },
    };
  }

  public normalizeWorkerDescriptor(input: ZavorthWorkerDescriptorInput): ZavorthWorkerDescriptor {
    return {
      workerId: `zavorth.worker.${safeId(input.sourceWorkerId)}`,
      sourceRuntimeId: input.sourceRuntimeId,
      sourceWorkerId: input.sourceWorkerId,
      sourceRuntimeDiagnosticsOnly: true,
      publicName: 'Zavorth',
      role: input.role,
      health: input.health,
      capabilities: input.capabilities.map((entry) => safeId(entry)),
      maxRuntimeMs: Math.max(1000, input.maxRuntimeMs),
      canMutateFiles: input.canMutateFiles,
      dispatchMode: 'zavorth-gateway-delegated-only',
      directSourceLaunchAllowed: false,
      approvalRequiredForLiveLaunch: input.requiresApprovalToLaunch || input.canMutateFiles,
      safety: {
        sourceWorkerNotCanonical: true,
        noDirectLaunch: true,
        noSourceRuntimeCodeExecuted: true,
      },
    };
  }

  public buildDelegatedTaskEnvelope(input: ZavorthDelegatedTaskEnvelopeInput): ZavorthDelegatedTaskEnvelope {
    const approvalRequired = input.risk === 'high' || input.risk === 'critical';
    const approvalGranted = input.approvalGranted === true;
    const blocked = approvalRequired && !approvalGranted;
    return {
      delegatedTaskId: `zavorth.delegated-task.${safeId(input.taskId)}`,
      workerId: input.workerId,
      requestedBySessionId: input.requestedBySessionId,
      objective: input.objective.trim(),
      resourceRefs: input.resourceRefs,
      risk: input.risk,
      timeoutMs: Math.max(1000, input.timeoutMs),
      cancellationToken: input.cancellationToken.trim() || `cancel.${safeId(input.taskId)}`,
      status: blocked ? 'blocked' : 'dry-run-ready',
      dispatchMode: 'zavorth-gateway-delegated-only',
      gatewayEntrypoint: 'ZavorthAgentGateway',
      approvalRequired,
      approvalGranted,
      directSourceWorkerLaunchAllowed: false,
      liveDispatchPerformed: false,
      safety: {
        boundedTaskEnvelope: true,
        noWorkerLaunch: true,
        noToolExecution: true,
        noApprovalBypass: true,
      },
    };
  }

  public buildTimeoutCancellation(
    envelope: ZavorthDelegatedTaskEnvelope,
  ): ZavorthWorkerTimeoutCancellationReceipt {
    return {
      delegatedTaskId: envelope.delegatedTaskId,
      timeoutMs: envelope.timeoutMs,
      cancellationToken: envelope.cancellationToken,
      timeoutPolicy: 'cancel-task-and-return-status',
      cancellationAvailable: true,
      timerStarted: false,
      safety: {
        dryRunOnly: true,
        noBackgroundTimerStarted: true,
        cancellationTokenRequired: true,
      },
    };
  }

  public blockSourceWorkerLaunch(
    worker: ZavorthWorkerDescriptor,
    approvalGranted: boolean,
  ): ZavorthSourceWorkerLaunchGateReceipt {
    return {
      workerId: worker.workerId,
      status: approvalGranted ? 'approval-required' : 'blocked',
      approvalRequired: true,
      approvalGranted,
      sourceWorkerLaunchBlocked: true,
      reason: approvalGranted
        ? 'Live source worker launch is deferred to a later explicit activation gate.'
        : 'Source worker launch remains blocked until a later explicit approval and activation gate exists.',
      safety: {
        noSourceWorkerLaunch: true,
        laterGateRequired: true,
        noApprovalBypass: true,
      },
    };
  }

  public buildLifecycleDryRun(
    envelope: ZavorthDelegatedTaskEnvelope,
    launchGate: ZavorthSourceWorkerLaunchGateReceipt,
  ): ZavorthWorkerLifecycleDryRunReceipt {
    return {
      delegatedTaskId: envelope.delegatedTaskId,
      workerId: envelope.workerId,
      status: 'dry-run-ready',
      lifecycle: [
        { state: 'queued', dryRunOnly: true, detail: 'Task envelope accepted by Zavorth gateway delegation queue.' },
        { state: 'leased', dryRunOnly: true, detail: 'Worker lease is previewed only; no worker is launched.' },
        { state: 'blocked', dryRunOnly: true, detail: 'Source worker launch is blocked until a later activation gate.' },
      ],
      sourceWorkerLaunchBlocked: launchGate.sourceWorkerLaunchBlocked,
      liveWorkerStarted: false,
      safety: {
        lifecyclePreviewOnly: true,
        noWorkerLaunch: true,
        noSourceRuntimeCodeExecuted: true,
      },
    };
  }

  public mapExecutorResult(input: ZavorthExecutorResultInput): ZavorthExecutorResultMappingReceipt {
    return {
      delegatedTaskId: input.delegatedTaskId,
      workerId: input.workerId,
      status: 'mapped',
      artifactEvents: input.artifactRefs.map((sourceRef) => ({
        artifactId: `zavorth.artifact.${safeId(input.delegatedTaskId)}.${safeId(sourceRef)}`,
        sourceRef,
        artifactType: 'worker-output',
      })),
      event: {
        eventId: `zavorth.event.${safeId(input.delegatedTaskId)}.result`,
        eventType: 'delegated-worker-result',
        status: input.status,
      },
      runStatus: {
        statusId: `zavorth.status.${safeId(input.delegatedTaskId)}`,
        state: input.status === 'success' ? 'completed' : input.status,
        exitCode: input.exitCode,
        stdoutPreview: input.stdoutPreview.slice(0, 200),
        stderrPreview: input.stderrPreview.slice(0, 200),
      },
      safety: {
        resultMappingOnly: true,
        noArtifactWritePerformed: true,
        noMemoryWritePerformed: true,
      },
    };
  }

  public buildZavorthControlProjection(input: {
    status: ZavorthDelegatedWorkerBridgeStatus;
    workerDescriptors: ZavorthWorkerDescriptor[];
    delegatedTaskEnvelope: ZavorthDelegatedTaskEnvelope;
    timeoutCancellationReceipt: ZavorthWorkerTimeoutCancellationReceipt;
    sourceWorkerLaunchGateReceipt: ZavorthSourceWorkerLaunchGateReceipt;
    lifecycleDryRunReceipt: ZavorthWorkerLifecycleDryRunReceipt;
    executorResultMappingReceipt: ZavorthExecutorResultMappingReceipt;
  }): ZavorthDelegatedWorkerZavorthControlProjection {
    return {
      title: 'Delegated Worker Bridge',
      status: input.status,
      tone: input.status === 'delegated-worker-bridge-ready' ? 'ready' : input.status === 'attention' ? 'attention' : 'blocked',
      cards: [
        card('workers', 'Workers', String(input.workerDescriptors.length), 'External/local workers represented as Zavorth descriptors'),
        card('task', 'Task Envelope', input.delegatedTaskEnvelope.status, input.delegatedTaskEnvelope.dispatchMode),
        card('timeout', 'Timeout', `${input.timeoutCancellationReceipt.timeoutMs}ms`, 'Cancellation available; no timer started in dry-run'),
        card('launch', 'Source Launch', input.sourceWorkerLaunchGateReceipt.status, 'Source worker launch blocked until later gate'),
        card('lifecycle', 'Lifecycle Dry Run', input.lifecycleDryRunReceipt.status, 'Lifecycle preview only, no worker started'),
        card('result', 'Result Mapping', input.executorResultMappingReceipt.runStatus.state, 'Worker result mapped to artifact/event/status'),
        card('live-workers', 'Live Workers', '0', 'Surface controls does not start workers'),
      ],
      policyPills: [
        'zavorth-gateway-delegated-only',
        'bounded task envelope',
        'timeout/cancellation',
        'source launch blocked',
        'dry-run lifecycle',
        'artifact/event/status mapping',
      ],
      nextSafeAction: input.status === 'delegated-worker-bridge-ready'
        ? 'Proceed to 291 ZavorthControl controls - Native Replacement And Decommission.'
        : 'Fix failed worker delegation gates before native replacement.',
    };
  }

  public formatSnapshotText(snapshot: ZavorthDelegatedWorkerBridgeSnapshot): string {
    const lines = [
      'Zavorth Delegated Worker Bridge - Surface controls',
      '',
      `Status: ${snapshot.status}`,
      `Previous session memory: ${snapshot.previousSessionMemoryStatus}`,
      `Worker descriptors: ${snapshot.summary.workerDescriptors}`,
      `Task envelopes: ${snapshot.summary.delegatedTaskEnvelopes}`,
      `Dry-run lifecycles: ${snapshot.summary.dryRunLifecycleReceipts}`,
      `Timeout policies: ${snapshot.summary.timeoutPolicies}`,
      `Cancellation policies: ${snapshot.summary.cancellationPolicies}`,
      `Source worker launches blocked: ${snapshot.summary.sourceWorkerLaunchesBlocked}`,
      `Executor results mapped: ${snapshot.summary.executorResultsMapped}`,
      `Artifact events returned: ${snapshot.summary.artifactEventsReturned}`,
      `Live workers started: ${snapshot.summary.liveWorkersStarted}`,
      '',
      'ZavorthControl:',
      ...snapshot.zavorthControlProjection.cards.map((entry) => `- ${entry.label}: ${entry.value} (${entry.detail})`),
      '',
      'Acceptance:',
      ...snapshot.acceptanceMatrix.map((entry) => `- ${entry.status} ${entry.requirementId}: ${entry.evidence}`),
      '',
      `Next: ${snapshot.commands.nextStage}`,
    ];
    return lines.join('\n');
  }
}

function buildAcceptanceMatrix(
  previousSessionMemoryStatus: ZavorthSessionMemoryContinuationStatus,
  workerDescriptors: ZavorthWorkerDescriptor[],
  delegatedTaskEnvelope: ZavorthDelegatedTaskEnvelope,
  timeoutCancellationReceipt: ZavorthWorkerTimeoutCancellationReceipt,
  sourceWorkerLaunchGateReceipt: ZavorthSourceWorkerLaunchGateReceipt,
  lifecycleDryRunReceipt: ZavorthWorkerLifecycleDryRunReceipt,
  executorResultMappingReceipt: ZavorthExecutorResultMappingReceipt,
): ZavorthDelegatedWorkerBridgeSnapshot['acceptanceMatrix'] {
  return [
    acceptance('sessions-memory-continuation-ready', previousSessionMemoryStatus === 'session-memory-continuation-ready', `previousSessionMemoryStatus=${previousSessionMemoryStatus}`),
    acceptance('worker-descriptors-normalized', workerDescriptors.length >= 2
      && workerDescriptors.every((entry) => entry.workerId.startsWith('zavorth.worker.') && entry.dispatchMode === 'zavorth-gateway-delegated-only' && !entry.directSourceLaunchAllowed), `${workerDescriptors.length} worker descriptor(s)`),
    acceptance('delegated-task-envelope-gateway-only', delegatedTaskEnvelope.status === 'dry-run-ready'
      && delegatedTaskEnvelope.dispatchMode === 'zavorth-gateway-delegated-only'
      && delegatedTaskEnvelope.gatewayEntrypoint === 'ZavorthAgentGateway'
      && !delegatedTaskEnvelope.liveDispatchPerformed, `${delegatedTaskEnvelope.delegatedTaskId}, dispatch=${delegatedTaskEnvelope.dispatchMode}`),
    acceptance('timeout-and-cancellation-policy-ready', timeoutCancellationReceipt.timeoutPolicy === 'cancel-task-and-return-status'
      && timeoutCancellationReceipt.cancellationAvailable
      && !timeoutCancellationReceipt.timerStarted, `${timeoutCancellationReceipt.timeoutMs}ms, token=${timeoutCancellationReceipt.cancellationToken}`),
    acceptance('source-worker-launch-blocked-until-later-gate', sourceWorkerLaunchGateReceipt.sourceWorkerLaunchBlocked
      && sourceWorkerLaunchGateReceipt.approvalRequired
      && sourceWorkerLaunchGateReceipt.safety.laterGateRequired
      && sourceWorkerLaunchGateReceipt.safety.noSourceWorkerLaunch, `${sourceWorkerLaunchGateReceipt.status}, approvalRequired=${sourceWorkerLaunchGateReceipt.approvalRequired}`),
    acceptance('lifecycle-status-dry-run-first', lifecycleDryRunReceipt.status === 'dry-run-ready'
      && lifecycleDryRunReceipt.lifecycle.every((entry) => entry.dryRunOnly)
      && lifecycleDryRunReceipt.liveWorkerStarted === false, `${lifecycleDryRunReceipt.lifecycle.length} lifecycle state(s)`),
    acceptance('executor-result-mapped-to-artifact-event-status', executorResultMappingReceipt.status === 'mapped'
      && executorResultMappingReceipt.artifactEvents.length > 0
      && executorResultMappingReceipt.event.eventType === 'delegated-worker-result'
      && !!executorResultMappingReceipt.runStatus.statusId, `${executorResultMappingReceipt.artifactEvents.length} artifact event(s), state=${executorResultMappingReceipt.runStatus.state}`),
    acceptance('no-worker-tool-artifact-memory-execution', workerDescriptors.every((entry) => entry.safety.noSourceRuntimeCodeExecuted)
      && delegatedTaskEnvelope.safety.noWorkerLaunch
      && lifecycleDryRunReceipt.safety.noWorkerLaunch
      && executorResultMappingReceipt.safety.noArtifactWritePerformed
      && executorResultMappingReceipt.safety.noMemoryWritePerformed, 'all worker receipts are dry-run/no-write'),
  ];
}

function acceptance(
  requirementId: string,
  passed: boolean,
  evidence: string,
): ZavorthDelegatedWorkerBridgeSnapshot['acceptanceMatrix'][number] {
  return {
    requirementId,
    status: passed ? 'passed' : 'failed',
    evidence,
  };
}

function resolveStatus(
  previousSessionMemoryStatus: ZavorthSessionMemoryContinuationStatus,
  acceptanceMatrix: ZavorthDelegatedWorkerBridgeSnapshot['acceptanceMatrix'],
): ZavorthDelegatedWorkerBridgeStatus {
  if (previousSessionMemoryStatus !== 'session-memory-continuation-ready') {
    return 'blocked';
  }
  if (acceptanceMatrix.some((entry) => entry.status === 'failed')) {
    return 'blocked';
  }
  return 'delegated-worker-bridge-ready';
}

function safeId(value: string): string {
  const clean = value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return clean || 'item';
}

function card(
  id: string,
  label: string,
  value: string,
  detail: string,
): ZavorthDelegatedWorkerZavorthControlProjection['cards'][number] {
  return { id, label, value, detail };
}
