export const PLUGIN_HELP_LINES = [
  'Zavorth Plugin OS commands (alias: zavorth plugin ...):',
  '  list                         Show local + bridged Plugin OS state',
  '  install <path|url|marketplace:id> [--yes] [--enable]',
  '  uninstall <id> [--yes]       Remove bridge state + .zavorth/plugins package',
  '  enable|disable <id> [--yes]',
  '  inspect <id>                 Bridge + discovery detail',
  '  preview <id>                 Permission / risk preview (never auto-enables)',
  '  doctor [id]                  Validation / eligibility checks',
  '  marketplace|search [query] [--curated] [--remote]  Unified catalog (curated+bundled+remote)',
  '  marketplace show <id>        Preview install path (bundled copy / URL / materialize)',
  '  marketplace install <id> [--yes] [--enable]  Install from marketplace catalog',
  '  marketplace refresh-remote   Fetch ZAVORTH_PLUGIN_MARKETPLACE_URL into cache',
  '  create <id> --kind <kind> [--dir path] [--yes]  Scaffold via create-zavorth-plugin',
  '  new <id> [--kind tool] [--run] [--yes]   Minimal ping scaffold (+ install/enable with --run)',
  '  recommend <intent> [--limit N] [--llm]   Rank plugins for an intent (no auto-enable)',
  '  suggest <intent>                 Suggest-to-enable (Enable vs Recommend-only CTAs)',
  '  receipts [limit]                 Human activity timeline (forge/enable/onboarding)',
  '  inject-mode [compact|standard|full|ab|off] [--sample N]  Prompt inject prefs',
  '  forge [plan] "<intent>" [--id id] [--apply --yes] [--enable]',
  '  forge apply <previewDir|id> --yes [--enable]',
  '  mcp list|status [serverId]   List configured MCP servers',
  '  mcp materialize <serverId> --yes [--force]',
  '  dev <path> [--watch] [--write-manifest] [--watch-ms N] [--trust review|trusted]',
  '  scaffold <id> --yes [--kind tool|channel|memory|provider|agent|diagnostics] [--ts]',
  '  trust <id> <review|trusted|blocked> [--yes]',
  '  sign <path> [--yes]          Write SIGNATURE (sha256 + ed25519 if private key set)',
  '  os|runtime                   Discovery + bridge snapshot',
  '  plane|status                 Control-plane summary (includes metrics + curated catalog)',
  '  metrics [--persist]          Load funnel / marketplace / MCP observability',
  '  telemetry [windowHours]      Aggregated Plugin OS telemetry rollup',
  '  agent-surface [--inject]     Compact catalog block for agent prompts',
  '  onboarding status|plan|apply|undo [profile] [--optional id,id] [--yes] [--force]',
  '  wizard [start|next|back|profile|optional|inject|apply|show]  Multi-step onboarding wizard',
  '  telemetry history [--hours N] [--bucket N]   Time-series buckets',
  '  test <path>                  Run Plugin OS test harness',
  '  create-plugin                Alias of create (third-party scaffold CLI)',
  '',
  'Env: ZAVORTH_PLUGIN_WATCH=1  ZAVORTH_PLUGIN_REQUIRE_SIGNATURE=1',
  '     ZAVORTH_PLUGIN_HMAC_SECRET=...  ZAVORTH_LOCALE=pt-BR',
  '     ZAVORTH_PLUGIN_ED25519_PUBLIC_KEY=...  ZAVORTH_PLUGIN_ED25519_PRIVATE_KEY=...',
  '     ZAVORTH_PLUGIN_DEV=1  ZAVORTH_PLUGIN_ROUTER_LLM=1  ZAVORTH_PLUGIN_FORGE_LLM=1',
  '     ZAVORTH_PLUGIN_OS_BOOTSTRAP=0  ZAVORTH_PLUGIN_OS_RUNTIME=0',
  '     ZAVORTH_PLUGIN_OS_PROMPT=0     Disable agent system-prompt injection',
];
