apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zavorth
  labels:
    app: zavorth
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zavorth.local
      secretName: zavorth-tls
  rules:
    - host: zavorth.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zavorth
                port:
                  number: 80
