import { getDefaultCapabilityRegistry } from '../../../capabilities/CapabilityRegistry.js';
import {
  EXTERNAL_EXECUTOR_COMMAND,
  EXTERNAL_REVIEW_COMMAND,
  EXTERNAL_REVIEW_DASH_COMMAND,
  LEGACY_EXTERNAL_COMMAND,
  LEGACY_EXTERNAL_REVIEW_COMMAND,
  LEGACY_EXTERNAL_REVIEW_DASH_COMMAND,
  LEGACY_EXTERNAL_SHORT_COMMAND,
} from '../../../gateways/channels/telegram/ExternalExecutorIdentity.js';

export type CommandSection =
  | 'entry'
  | 'execution'
  | 'monitoring'
  | 'permissions'
  | 'zavorthBridge'
  | 'skills'
  | 'search'
  | 'memory'
  | 'fun'
  | 'group_admin';

export type CommandCatalogEntry = {
  command: string;
  description: string;
  section: CommandSection;
  usage?: string;
  hidden?: boolean;
  privateMenu?: boolean;
  groupMenu?: boolean;
};

const capabilityRegistry = getDefaultCapabilityRegistry();

const STATIC_COMMAND_ALIASES: Record<string, string> = {
  '/menu': '/zavorth',
  '/remote': '/remote',
  '/selfmodify': '/selfmod',
  '/reload': '/selfupdate',
  '/repair': '/autorepair',
  '/agent': '/agents',
  '/subagent': '/agents',
  '/subagents': '/agents',
  '/externalagents': '/externalagent',
  '/agentgateway': '/externalagent',
  '/agent_onboarding': '/agentonboarding',
  '/sessions_spawn': '/agents',
  '/invocar': '/invoke',
  '/aigateway': '/AIGateway',
  // Legacy web-surface aliases still resolve to /dashboard (ops handleDashboard).
  '/app': '/dashboard',
  '/miniapp': '/dashboard',
  [LEGACY_EXTERNAL_COMMAND]: EXTERNAL_EXECUTOR_COMMAND,
  [LEGACY_EXTERNAL_SHORT_COMMAND]: EXTERNAL_EXECUTOR_COMMAND,
  [EXTERNAL_REVIEW_DASH_COMMAND]: EXTERNAL_REVIEW_COMMAND,
  [LEGACY_EXTERNAL_REVIEW_COMMAND]: EXTERNAL_REVIEW_COMMAND,
  [LEGACY_EXTERNAL_REVIEW_DASH_COMMAND]: EXTERNAL_REVIEW_COMMAND,
};

const STATIC_COMMAND_EXECUTORS: Record<string, string | null> = {
  '/plan': 'planner',
  '/run': 'local_executor',
  '/dryrun': 'local_executor',
  '/approve': 'approval_manager',
  '/reject': 'approval_manager',
};

const CAPABILITY_COMMAND_CATALOG: CommandCatalogEntry[] = capabilityRegistry
  .getCommandCatalogEntries()
  .map((entry) => ({
    command: entry.command,
    description: entry.description,
    section: (entry.section || 'execution') as CommandSection,
    usage: entry.usage,
    hidden: entry.hidden,
    privateMenu: entry.privateMenu,
    groupMenu: entry.groupMenu,
  }));

const STATIC_COMMAND_CATALOG: CommandCatalogEntry[] = [
  {
    command: 'start',
    description: 'Welcome / hub (speak naturally after this).',
    section: 'entry',
    usage: '[fix|recipes|security|settings]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'zavorth',
    description: 'Interactive hub with dashboard, actions, and settings.',
    section: 'entry',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'dashboard',
    description: 'Legacy alias for the web control surface.',
    section: 'entry',
    privateMenu: false,
    groupMenu: false,
    hidden: true,
  },
  { command: 'help', description: 'Complete command guide.', section: 'entry', privateMenu: true, groupMenu: true },
  {
    command: 'commands',
    description: 'Paginated command catalog by channel.',
    section: 'entry',
    usage: '[filter|page N]',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'plan',
    description: 'Plans before executing any action.',
    section: 'execution',
    usage: '<task>',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'task',
    description: 'Orchestrated conversation about a task.',
    section: 'execution',
    usage: '<request>',
    hidden: true,
  },
  {
    command: 'auto',
    description: 'Automation-oriented conversation.',
    section: 'execution',
    usage: '<request>',
    hidden: true,
  },
  {
    command: 'selfmod',
    description: 'Guarded Zavorth self-modification.',
    section: 'execution',
    usage: '[preview <file> -- <instruction>|goal -- <objective>|apply <preview_id>|rollback <change_id>]',
    hidden: true,
    privateMenu: false,
  },
  {
    command: 'run',
    description: 'Executes a direct local shell command.',
    section: 'execution',
    usage: '<command>',
    privateMenu: false,
  },
  {
    command: 'dryrun',
    description: 'Previews a command without executing it.',
    section: 'execution',
    usage: '<command>',
    privateMenu: false,
  },
  {
    command: 'status',
    description: 'Health, uptime, and general state.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'ready',
    description: 'Zavorth Ready To Go: checks whether remote use is available now.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'stayonline',
    description: 'Zavorth Stay Online: monitors remote availability and alerts on drops.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'agentonboarding',
    description: 'External Agent Onboarding: registers consented hints for external agents.',
    section: 'monitoring',
    usage: '[path|approx|command|endpoint] <value>',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'externalagent',
    description: 'External Agent Gateway: lists, registers, and invokes external agents with approval.',
    section: 'monitoring',
    usage: '[list|run <id> -- <prompt> approve-external-execution]',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'readiness',
    description: 'Shows ready, attention, or blocked state for daily use.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'zavorthControl',
    description: 'Opens or shows the daily zavorthControl URL.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'doctor',
    description: 'Diagnostics for local desktop, WSL, Docker, and companions.',
    section: 'monitoring',
    usage: '[desktop]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'companion',
    description: 'Supervised control plane for WSL, Docker, ZavorthBridge, and Codex.',
    section: 'monitoring',
    usage:
      '[list|inspect <id>|hibernate <id>|resume <id>|stop-idle <id>|trim <id>|restart-safe <id>|optimize <preset> [apply <planId>]]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'workspace',
    description: 'Doctor and light preset for Zavorth workspaces in companion IDEs.',
    section: 'monitoring',
    usage: '[doctor|optimize <zavorthBridge|vscode|vscode-derivative> [apply <planId>]]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'profile',
    description: 'Shows or changes the light runtime profile.',
    section: 'monitoring',
    usage: '[core|ops|full]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'enable',
    description: 'Enables an on-demand capability.',
    section: 'monitoring',
    usage: '<capability> [once|session|host]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'disable',
    description: 'Disables an on-demand capability.',
    section: 'monitoring',
    usage: '<capability>',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'models',
    description: 'Summarizes active models and providers.',
    section: 'monitoring',
    privateMenu: false,
  },
  {
    command: 'codexremote',
    description: 'Remote Codex CLI control plane with profiles and sessions.',
    section: 'monitoring',
    usage:
      '[status|profiles|profile <id>|start [title] -- <prompt>|sessions|inspect <id>|tail <id>|resume <id> [-- <prompt>]|stop <id>|web <id>]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'teams',
    description: 'Shows composed workflows and availability by surface.',
    section: 'monitoring',
    usage: '[id]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'tenants',
    description: 'Summarizes governance, onboarding, and tenant allowlists.',
    section: 'monitoring',
    usage: '[tenant|surface]|run <tenantId> <actionId>',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'gateway',
    description: 'Canonical snapshot of the unified Gateway.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'tools',
    description: 'Official surface for tools, skills, and plugins.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'hooks',
    description: 'Official hooks, events, and workspace records plan.',
    section: 'monitoring',
    usage: '[filter]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'runtime',
    description: 'Official Runtime & Security Mesh posture.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'access',
    description: 'Official local and remote access manifest.',
    section: 'monitoring',
    usage: '[local|remote]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'bootstrap',
    description: 'Official bootstrap and installation checklist.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'transports',
    description: 'Bridges, sidecars, and node hosts for the remote plane.',
    section: 'monitoring',
    usage: '[id]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'model',
    description: 'Shows or sets providers/models and default/strong roles.',
    section: 'monitoring',
    usage: '[status|setup|default <p/m>|strong <p/m>|background <p/m>|fallback on|off|<provider|model>]',
    privateMenu: false,
  },
  {
    command: 'strong',
    description: 'Uses the strong model role for the next turns until off.',
    section: 'monitoring',
    usage: '[on|off]',
    privateMenu: false,
  },
  {
    command: 'remote',
    description: 'Turns remote mode on or off.',
    section: 'monitoring',
    usage: '[on|off|status]',
    privateMenu: false,
  },
  {
    command: 'audit',
    description: 'Recent audit log events.',
    section: 'monitoring',
    usage: '[count]',
    privateMenu: false,
  },
  {
    command: 'mode',
    description: 'Shows/changes product mode or resolves Zavorth elevations.',
    section: 'monitoring',
    usage: '[chat|assistant|builder|operator|approve <requestId> [once|session|host]|reject <requestId>]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'operator',
    description: 'Turns operator mode on or off.',
    section: 'monitoring',
    usage: '[on|off|status]',
    privateMenu: false,
  },
  {
    command: 'presentation',
    description: 'Turns presentation mode on or off.',
    section: 'monitoring',
    usage: '[on|off|status]',
    privateMenu: false,
  },
  {
    command: 'demo',
    description: 'Controls and shows the Zavorth demo script.',
    section: 'monitoring',
    usage: '[on|off|status|start|next|reset|short|pitch|checklist|research|files|workflow|stitch|full]',
    privateMenu: false,
  },
  {
    command: 'dailyreport',
    description: 'Turns the daily report on/off or sends it now.',
    section: 'monitoring',
    usage: '[status|on|off|now]',
    privateMenu: false,
  },
  {
    command: 'channels',
    description: 'Official Channel Mesh and first-class channel summary.',
    section: 'monitoring',
    usage: '[id]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'memoryplane',
    description: 'Resume points, deliveries, and memories in one official plane.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'sessions',
    description: 'Official sessions and resume points plan.',
    section: 'monitoring',
    usage: '[sessionId|chatId]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'sessionhistory',
    description: 'Replay and handoff for the target session.',
    section: 'monitoring',
    usage: '[sessionId|chatId]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'sessionsend',
    description: 'Dispatches a message to another session.',
    section: 'monitoring',
    usage: '<sessionId|chatId> -- <message>',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'sessionspawn',
    description: 'Opens a traceable derived session.',
    section: 'monitoring',
    usage: '[web]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'nodes',
    description: 'Official Node Mesh and remote transport summary.',
    section: 'monitoring',
    usage: '[nodeId]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'nodepair',
    description: 'Creates a pairing draft for a node host.',
    section: 'monitoring',
    usage: '[label]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'nodeinvoke',
    description: 'Queues a remote invocation for a paired node.',
    section: 'monitoring',
    usage: '<nodeId> <capabilityId> [action] [payload-json]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'plugins',
    description: 'Official plugin, skill, and Zavorth extension plan.',
    section: 'monitoring',
    usage: '[id|filter]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'platform',
    description: 'Unified plugin, skill, and MCP plan for Zavorth.',
    section: 'monitoring',
    usage: '[id|filter]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'hub',
    description: 'Consolidated integrations, plugins, skills, platform, and MCP plan.',
    section: 'monitoring',
    usage: '[id|filter|sync|doctor|run <actionId>|recommend <objective>]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'evals',
    description: 'Eval observability: scorecards, traces, and operational history.',
    section: 'monitoring',
    usage: '[workspace X|surface Y|executor Z|workflow W]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'qa',
    description: 'Budgets, smokes, regressions, and QA release gates.',
    section: 'monitoring',
    usage: '[alpha|beta]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'governance',
    description: 'Tenants, trust decisions, allowlists, and Governance policy.',
    section: 'monitoring',
    usage: '[limit N]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'replayloop',
    description: 'Replay, reusable artifacts, and Replay Learning loop.',
    section: 'monitoring',
    usage: '[limit N]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'ecosystem',
    description: 'SDKs, guides, publishing, and public Ecosystem recipes.',
    section: 'monitoring',
    usage: '[id|filter]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'fleet',
    description: 'Channels, fleet, transports, and Distributed Runtime surfaces.',
    section: 'monitoring',
    usage: '[id|filter]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'stability',
    description: 'Keepalive, doctor, and supervised fleet recovery.',
    section: 'monitoring',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'rolloutqa',
    description: 'Persistent QA, distributed runtime, and rollout readiness.',
    section: 'monitoring',
    usage: '[alpha|beta]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'setupagent',
    description: 'Natural setup: natural-first channel setup through human language.',
    section: 'monitoring',
    usage: '[natural request]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'watchmode',
    description: 'Watch mode: policy, approvals, and supervised Watch Mode replay.',
    section: 'monitoring',
    usage: '[status|strict on|strict off|allow-app <window>|allow-site <host>]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'swarm',
    description: 'Runs a short supervised multi-agent team.',
    section: 'execution',
    usage: '<objective>',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'echo',
    description: 'Turns Echo Mode on or off (voice response).',
    section: 'execution',
    usage: '[on|off]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'learn',
    description: 'Skill drafts from multi-tool workflows (experience loop). Not candidates — use /learning.',
    section: 'skills',
    usage: '[status|list|show 1|run 1|promote 1|forget 1]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'learning',
    description: 'Learning plane candidates with explicit gates. Not skill drafts — use /learn.',
    section: 'monitoring',
    usage: '[list|approve 1|reject 1|promote 1|forget 1]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'integrations',
    description: 'Zavorth connector and recipe catalog.',
    section: 'monitoring',
    usage: '[id]',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'skills',
    description: 'Curated catalog of skills, recipes, plans, and MCP sidecar.',
    section: 'skills',
    usage: '[library|plan <id>|plan recipe <id>|id|filter|recipe <id>|recommend <objective>|mcp]',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'agents',
    description: 'Governed live subagents: spawn, status, history, read, summarize, and cancel.',
    section: 'execution',
    usage: '[spawn|status|history|wait|cancel|read|summarize] [latest|sessionId] [--live] <task>',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'invoke',
    description: 'Routes natural language to skills, subagents, or governed absorption.',
    section: 'execution',
    usage: '<natural request>',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'teams',
    description: 'Composed workflows and availability by surface.',
    section: 'monitoring',
    usage: '[id]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'tenants',
    description: 'Governance, onboarding, and allowlists by tenant.',
    section: 'monitoring',
    usage: '[tenant|surface]|run <tenantId> <actionId>',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'trust',
    description: 'Trust Plane with MCP, skills, plugins, and supervised runtime.',
    section: 'monitoring',
    usage: '[status|mcp safe|mcp trusted|skills deny]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'connect',
    description: 'Starts secure onboarding for an integration.',
    section: 'monitoring',
    usage: '<integration> [mode]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'changes',
    description: 'Summarizes local changes and runtime state.',
    section: 'monitoring',
    privateMenu: false,
  },
  { command: 'reload', description: 'Restarts supervised Zavorth.', section: 'monitoring', privateMenu: false },
  {
    command: 'selfupdate',
    description: 'Requests a supervised Zavorth reload.',
    section: 'monitoring',
    usage: '[status|summary|force]',
    hidden: true,
    privateMenu: false,
  },
  {
    command: 'autorepair',
    description: 'Repairs, validates, updates, and reconnects Zavorth autonomously.',
    section: 'monitoring',
    usage: '[status]',
    privateMenu: false,
  },
  {
    command: 'wsl',
    description: 'Turns WSL and external runtimes on or off.',
    section: 'monitoring',
    usage: '[on|off|status]',
    privateMenu: false,
  },
  {
    command: 'schedule',
    description: 'Schedules a recurring command.',
    section: 'monitoring',
    usage: '<every Xh|Xm> <command>',
    privateMenu: false,
  },
  { command: 'schedules', description: 'Lists active schedules.', section: 'monitoring', privateMenu: false },
  {
    command: 'unschedule',
    description: 'Cancels a schedule.',
    section: 'monitoring',
    usage: '<id>',
    privateMenu: false,
  },
  {
    command: 'automations',
    description: 'Scheduled runs: natural automations, maintenance, and scheduled runs.',
    section: 'monitoring',
    usage:
      '[status|maintenance on|maintenance off|maintenance run|pause <id>|resume <id>|remove <id>|<natural request>]',
    privateMenu: true,
    groupMenu: false,
  },
  { command: 'settings', description: 'Quick mode and model settings.', section: 'monitoring', privateMenu: false },
  { command: 'cleanup', description: 'Closes non-essential apps.', section: 'monitoring', privateMenu: false },
  { command: 'clear', description: 'Deletes bot messages in this chat.', section: 'monitoring', privateMenu: false },
  {
    command: 'report',
    description: 'Schedules an automatic briefing.',
    section: 'search',
    usage: 'every <Xm|Xh> <topic>',
    privateMenu: false,
  },
  {
    command: 'perm',
    description: 'Manages permissions and policies.',
    section: 'permissions',
    usage: 'list|show|approve|reject|edit ...',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'echoapprovals',
    description: 'Lists pending Echo approvals with inline buttons.',
    section: 'permissions',
    usage: '[list] (prefer inline Approve/Deny buttons)',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'lock',
    description: 'Locks Zavorth.',
    section: 'permissions',
    usage: '<password>',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'unlock',
    description: 'Unlocks Zavorth.',
    section: 'permissions',
    usage: '<password>',
    privateMenu: true,
    groupMenu: true,
  },
  {
    command: 'hostauth',
    description: 'Status/reauthorization for the current host.',
    section: 'permissions',
    usage: '[status|trust]',
    privateMenu: false,
  },
  {
    command: 'permallow',
    description: 'Creates a persistent policy.',
    section: 'permissions',
    usage: 'executor=<name> kind=<folder|command|ui> ...',
    privateMenu: false,
  },
  {
    command: 'permrevoke',
    description: 'Revokes a permission by id.',
    section: 'permissions',
    usage: '<id>',
    privateMenu: false,
  },
  {
    command: 'approve',
    description: 'Approves a pending task by id.',
    section: 'permissions',
    usage: '<task_id>',
    privateMenu: false,
  },
  {
    command: 'reject',
    description: 'Rejects a pending task by id.',
    section: 'permissions',
    usage: '<task_id>',
    privateMenu: false,
  },
  {
    command: 'undo',
    description: 'Attempts to undo a task by id.',
    section: 'permissions',
    usage: '<task_id>',
    privateMenu: false,
  },
  {
    command: 'agfocus',
    description: 'Focuses the ZavorthBridge window.',
    section: 'zavorthBridge',
    privateMenu: false,
  },
  { command: 'agaccept', description: 'Approves a ZavorthBridge step.', section: 'zavorthBridge', privateMenu: false },
  {
    command: 'agnudge',
    description: 'Sends a nudge to the ZavorthBridge conversation.',
    section: 'zavorthBridge',
    usage: '<text>',
    privateMenu: false,
  },
  { command: 'agbridge', description: 'ZavorthBridge bridge state.', section: 'zavorthBridge', privateMenu: false },
  {
    command: 'agclean',
    description: 'Cleans the ZavorthBridge session.',
    section: 'zavorthBridge',
    privateMenu: false,
  },
  {
    command: 'agreset',
    description: 'Restarts the ZavorthBridge conversation.',
    section: 'zavorthBridge',
    privateMenu: false,
  },
  {
    command: 'agmodel',
    description: 'Changes the ZavorthBridge model.',
    section: 'zavorthBridge',
    usage: '<model>',
    privateMenu: false,
  },
  {
    command: 'agmobile',
    description: 'Prepares ZavorthBridge for mobile use.',
    section: 'zavorthBridge',
    usage: '[start|status|guide|stop]',
    privateMenu: false,
  },
  {
    command: 'AIGateway',
    description: 'Operates the own route and upstream for AIGateway.',
    section: 'monitoring',
    usage: '[status|route|start|doctor|sync|promote|rollback]',
    privateMenu: false,
  },
  {
    command: 'save',
    description: 'Saves a text snippet.',
    section: 'memory',
    usage: '<name> <content>',
    privateMenu: false,
  },
  {
    command: 'snippet',
    description: 'Retrieves a saved snippet.',
    section: 'memory',
    usage: '<name>',
    privateMenu: false,
  },
  { command: 'snippets', description: 'Lists all snippets.', section: 'memory', privateMenu: false },
  {
    command: 'remember',
    description: 'Saves a fact in memory.',
    section: 'memory',
    usage: '<key> <value>',
    privateMenu: false,
  },
  {
    command: 'recall',
    description: 'Retrieves a fact from memory.',
    section: 'memory',
    usage: '<key>',
    privateMenu: false,
  },
  {
    command: 'memory',
    description: 'Layered memory with episodic, semantic, and procedural search.',
    section: 'memory',
    usage: '[status|search <query>|procedures]',
    privateMenu: true,
    groupMenu: false,
  },
  {
    command: 'forget',
    description: 'Removes a fact from memory.',
    section: 'memory',
    usage: '<key>',
    privateMenu: false,
  },
  {
    command: 'roll',
    description: 'Rolls a die.',
    section: 'fun',
    usage: '[sides]',
    privateMenu: false,
    groupMenu: true,
  },
  { command: 'coinflip', description: 'Heads or tails.', section: 'fun', privateMenu: false, groupMenu: true },
  {
    command: '8ball',
    description: 'Sarcastic magic ball.',
    section: 'fun',
    usage: '<question>',
    privateMenu: false,
    groupMenu: true,
  },
  { command: 'joke', description: 'Tells a joke.', section: 'fun', privateMenu: false, groupMenu: true },
  { command: 'roulette', description: 'Dramatic chat roulette.', section: 'fun', privateMenu: false, groupMenu: true },
  {
    command: 'ban',
    description: 'Bans a member.',
    section: 'group_admin',
    usage: '<user_id|reply>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'kick',
    description: 'Kicks a member.',
    section: 'group_admin',
    usage: '<user_id|reply>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'mute',
    description: 'Mutes a member.',
    section: 'group_admin',
    usage: '<user_id|reply> [duration]',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'unmute',
    description: 'Removes mute.',
    section: 'group_admin',
    usage: '<user_id|reply>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'warn',
    description: 'Applies a warning.',
    section: 'group_admin',
    usage: '<user_id|reply> [reason]',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'warns',
    description: 'Lists warnings.',
    section: 'group_admin',
    usage: '<user_id|reply>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'clearwarns',
    description: 'Clears warnings.',
    section: 'group_admin',
    usage: '<user_id|reply>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'rules',
    description: 'Sets or shows group rules.',
    section: 'group_admin',
    usage: '[text]',
    privateMenu: false,
    groupMenu: true,
  },
  { command: 'stats', description: 'Group statistics.', section: 'group_admin', privateMenu: false, groupMenu: true },
  {
    command: 'setwelcome',
    description: 'Sets the welcome message.',
    section: 'group_admin',
    usage: '<message>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'setbye',
    description: 'Sets the goodbye message.',
    section: 'group_admin',
    usage: '<message>',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'antispam',
    description: 'Configures anti-spam.',
    section: 'group_admin',
    usage: '[subcommand]',
    privateMenu: false,
    groupMenu: true,
  },
  {
    command: 'filter',
    description: 'Message type filter.',
    section: 'group_admin',
    usage: '<type> [on|off]',
    privateMenu: false,
    groupMenu: true,
  },
];

export const COMMAND_ALIASES: Record<string, string> = {
  ...STATIC_COMMAND_ALIASES,
  ...capabilityRegistry.getAliasMap(),
};

export const COMMAND_EXECUTORS: Record<string, string | null> = {
  ...STATIC_COMMAND_EXECUTORS,
  ...capabilityRegistry.getExplicitExecutorMap(),
};

export const TELEGRAM_COMMAND_CATALOG: CommandCatalogEntry[] = [
  ...STATIC_COMMAND_CATALOG,
  ...CAPABILITY_COMMAND_CATALOG.filter(
    (entry) => !STATIC_COMMAND_CATALOG.some((staticEntry) => staticEntry.command === entry.command),
  ),
];

export const KNOWN_COMMANDS = new Set(TELEGRAM_COMMAND_CATALOG.map((entry) => `/${entry.command}`));

export function resolveCommandAlias(commandType: string): string {
  return COMMAND_ALIASES[commandType] || commandType;
}

export function getExplicitExecutorForCommand(commandType: string): string | null {
  return commandType in COMMAND_EXECUTORS ? COMMAND_EXECUTORS[commandType] : null;
}

export function isKnownCommand(commandType: string): boolean {
  return KNOWN_COMMANDS.has(commandType);
}
