import { CapabilityDefinition } from '../../contracts/CapabilityContract.js';

export const EXECUTOR_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'executor-codex',
    label: 'Codex CLI',
    type: 'executor',
    description: 'Runs local code tasks through Codex.',
    intent: 'code_execution',
    executor_preference: 'codex',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit Codex command.',
    routing_confidence: 1,
    command: {
      command: 'codex',
      description: 'Runs a local code task.',
      usage: '<task>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'codex',
    },
  },
  {
    id: 'executor.external',
    label: 'External Code Executor',
    type: 'executor',
    description: 'Runs code and review tasks through the governed external executor.',
    intent: 'code_execution',
    executor_preference: 'external_executor',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit governed external executor command.',
    routing_confidence: 1,
    command: {
      command: 'external',
      aliases: ['ext'],
      description: 'Delegates a task to the governed external executor.',
      usage: '<task>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'external_executor',
    },
  },
  {
    id: 'executor-zavorthBridge',
    label: 'ZavorthBridge',
    type: 'executor',
    description: 'Runs tasks through ZavorthBridge.',
    intent: 'plan_execution',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Explicit ZavorthBridge command.',
    routing_confidence: 1,
    command: {
      command: 'ag',
      aliases: ['aga'],
      description: 'Runs a task through ZavorthBridge.',
      usage: '<task>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'zavorthBridge',
    },
  },
  {
    id: 'executor-bridge',
    label: 'Zavorth Bridge',
    type: 'executor',
    description: 'Explicit alias for the ZavorthBridge flow.',
    intent: 'plan_execution',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Explicit ZavorthBridge/bridge command.',
    routing_confidence: 1,
    command: {
      command: 'bridge',
      description: 'Compatibility alias for ZavorthBridge.',
      usage: '<task>',
      section: 'execution',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: 'zavorthBridge',
    },
  },
  {
    id: 'executor-gemini-cli',
    label: 'Gemini CLI',
    type: 'executor',
    description: 'Runs tasks through Gemini CLI.',
    intent: 'code_execution',
    executor_preference: 'gemini_cli',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit Gemini CLI command.',
    routing_confidence: 1,
    command: {
      command: 'gemini',
      aliases: ['gcli', 'geminicli', 'codeassist', 'gca'],
      description: 'Runs a task through Gemini CLI.',
      usage: '<task>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'gemini_cli',
    },
  },
  {
    id: 'executor-aistudio',
    label: 'Google AI Studio',
    type: 'executor',
    description: 'Runs tasks through Google AI Studio.',
    intent: 'research_and_generation',
    executor_preference: 'aistudio',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit Google AI Studio command.',
    routing_confidence: 1,
    command: {
      command: 'aistudio',
      aliases: ['gaistudio', 'gstudio', 'ais'],
      description: 'Runs a task through Google AI Studio with configurable model and tools.',
      usage: 'model=<model> [tools=search,code] <task>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'aistudio',
    },
  },
  {
    id: 'executor-jules',
    label: 'Jules',
    type: 'executor',
    description: 'Runs tasks through Jules.',
    intent: 'code_execution',
    executor_preference: 'jules',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Explicit Jules command.',
    routing_confidence: 1,
    command: {
      command: 'jules',
      description: 'Delegates a task to Jules.',
      usage: '<task>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'jules',
    },
  },
  {
    id: 'executor-stitch',
    label: 'Google Stitch',
    type: 'executor',
    description: 'Generates UI/apps through Google Stitch.',
    intent: 'design_generation',
    executor_preference: 'stitch',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit Google Stitch command.',
    routing_confidence: 1,
    command: {
      command: 'stitch',
      aliases: ['stich'],
      description: 'Generates an app/UI in Google Stitch and returns screenshot plus HTML.',
      usage: '<app brief>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'stitch',
    },
  },
];
