import { CapabilityDefinition } from '../../contracts/CapabilityContract.js';

export const EXECUTOR_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'executor-codex',
    label: 'Codex CLI',
    type: 'executor',
    description: 'Executa tarefas locais de codigo pelo Codex.',
    intent: 'code_execution',
    executor_preference: 'codex',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Codex.',
    routing_confidence: 1,
    command: {
      command: 'codex',
      description: 'Executa tarefa local de codigo.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'codex',
    },
  },
  {
    id: 'executor.external',
    label: 'External Code Executor',
    type: 'executor',
    description: 'Executa tarefas de codigo e revisao via executor externo governado.',
    intent: 'code_execution',
    executor_preference: 'external_executor',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para executor externo governado.',
    routing_confidence: 1,
    command: {
      command: 'external',
      aliases: ['ext'],
      description: 'Delega tarefa ao executor externo governado.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'external_executor',
    },
  },
  {
    id: 'executor-zavorthBridge',
    label: 'ZavorthBridge',
    type: 'executor',
    description: 'Executa tarefas via ZavorthBridge.',
    intent: 'plan_execution',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Comando explicito do ZavorthBridge.',
    routing_confidence: 1,
    command: {
      command: 'ag',
      aliases: ['aga'],
      description: 'Executa tarefa via ZavorthBridge.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'zavorthBridge',
    },
  },
  {
    id: 'executor-bridge',
    label: 'Zavorth Bridge',
    type: 'executor',
    description: 'Alias explicito para o fluxo do ZavorthBridge.',
    intent: 'plan_execution',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Comando explicito do ZavorthBridge/bridge.',
    routing_confidence: 1,
    command: {
      command: 'bridge',
      description: 'Alias de compatibilidade para ZavorthBridge.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: 'zavorthBridge',
    },
  },
  {
    id: 'executor-gemini-cli',
    label: 'Gemini CLI',
    type: 'executor',
    description: 'Executa tarefas via Gemini CLI.',
    intent: 'code_execution',
    executor_preference: 'gemini_cli',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Gemini CLI.',
    routing_confidence: 1,
    command: {
      command: 'gemini',
      aliases: ['gcli', 'geminicli', 'codeassist', 'gca'],
      description: 'Executa tarefa via Gemini CLI.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'gemini_cli',
    },
  },
  {
    id: 'executor-aistudio',
    label: 'Google AI Studio',
    type: 'executor',
    description: 'Executa tarefas via Google AI Studio.',
    intent: 'research_and_generation',
    executor_preference: 'aistudio',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Google AI Studio.',
    routing_confidence: 1,
    command: {
      command: 'aistudio',
      aliases: ['gaistudio', 'gstudio', 'ais'],
      description: 'Executa tarefa via Google AI Studio com modelo e tools configuraveis.',
      usage: 'model=<modelo> [tools=search,code] <tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'aistudio',
    },
  },
  {
    id: 'executor-jules',
    label: 'Jules',
    type: 'executor',
    description: 'Executa tarefas via Jules.',
    intent: 'code_execution',
    executor_preference: 'jules',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Comando explicito do Jules.',
    routing_confidence: 1,
    command: {
      command: 'jules',
      description: 'Delega tarefa ao Jules (Google AI Agent).',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'jules',
    },
  },
  {
    id: 'executor-stitch',
    label: 'Google Stitch',
    type: 'executor',
    description: 'Gera UI/app via Google Stitch.',
    intent: 'design_generation',
    executor_preference: 'stitch',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Google Stitch.',
    routing_confidence: 1,
    command: {
      command: 'stitch',
      aliases: ['stich'],
      description: 'Gera app/UI no Google Stitch e entrega screenshot + HTML.',
      usage: '<briefing do app>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'stitch',
    },
  },
];
