import { CapabilityDefinition } from '../../contracts/CapabilityContract.js';

/**
 * Integration capabilities (slash commands + policies).
 *
 * Free-text capability activation is dead: CapabilityRegistry.matchImplicit
 * always returns null. Tool selection for free text is LLM full_toolset.
 * Slash commands, aliases, and explicit command handlers remain intact.
 */
export const INTEGRATION_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'command-file-delivery',
    label: 'File Delivery',
    type: 'integration',
    description: 'Finds and sends a local file.',
    intent: 'file_delivery',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command to locate and send a file.',
    routing_confidence: 1,
    command: {
      command: 'file',
      aliases: ['sendfile'],
      description: 'Finds and sends a local file.',
      usage: '<request|path>',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'file_delivery',
    },
  },
  {
    id: 'command-task-files',
    label: 'Task Files',
    type: 'integration',
    description: 'Shows task files or performs natural file inspection.',
    intent: 'file_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit file inspection command.',
    routing_confidence: 1,
    command: {
      command: 'files',
      description: 'Shows files for a task.',
      usage: '[task_id|natural request]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_files',
    },
  },
  {
    id: 'command-task-diff',
    label: 'Task Diff',
    type: 'integration',
    description: 'Shows the diff for a task.',
    intent: 'file_diff',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command to inspect a task diff.',
    routing_confidence: 1,
    command: {
      command: 'diff',
      description: 'Shows a task diff.',
      usage: '[task_id]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_diff',
    },
  },
  {
    id: 'command-tasks',
    label: 'Tasks',
    type: 'integration',
    description: 'Shows the recent task center.',
    intent: 'task_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit task inspection command.',
    routing_confidence: 1,
    command: {
      command: 'tasks',
      description: 'Lists recent tasks.',
      usage: '[active|approval|failed|completed|N]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_tasks',
    },
  },
  {
    id: 'command-logs',
    label: 'Logs',
    type: 'integration',
    description: 'Shows recent runtime logs.',
    intent: 'log_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit log inspection command.',
    routing_confidence: 1,
    command: {
      command: 'logs',
      description: 'Shows recent logs.',
      usage: '[count]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_logs',
    },
  },
  {
    id: 'command-capabilities',
    label: 'Capabilities',
    type: 'integration',
    description: 'Lists loaded capabilities and plugins.',
    intent: 'capability_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command to list loaded capabilities.',
    routing_confidence: 1,
    command: {
      command: 'capabilities',
      description: 'Lists loaded capabilities and plugins.',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'ops_capabilities',
    },
  },
  {
    id: 'command-zavorthControl',
    label: 'ZavorthControl',
    type: 'integration',
    description: 'Opens the Zavorth web panel.',
    intent: 'zavorthControl_access',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command to open ZavorthControl.',
    routing_confidence: 1,
    command: {
      command: 'zavorthControl',
      aliases: ['app', 'miniapp'],
      description: 'Opens the Zavorth web panel.',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'ops_zavorthControl',
    },
  },
  {
    id: 'command-mcp',
    label: 'MCP Servers',
    type: 'integration',
    description: 'Manages MCP servers: install, remove, list, and check status.',
    intent: 'mcp_management',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command for MCP server management.',
    routing_confidence: 1,
    command: {
      command: 'mcp',
      description: 'Manages MCP servers (install, remove, status, enable, disable).',
      usage: '<install|remove|status|enable|disable> [id] [command] [args...]',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'mcp_management',
    },
  },
  {
    id: 'media.generate',
    label: 'Media Generation',
    type: 'integration',
    description: 'Generates images, video, or audio from a text prompt.',
    intent: 'media_generation',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit media generation command.',
    routing_confidence: 0.9,
    priority: 90,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'imagine',
      aliases: ['img', 'gerar_imagem', 'generate_image'],
      description: 'Generates images from a text prompt.',
      usage: '<descriptive prompt>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'media_generate',
    },
    // No free-text matchers — LLM full_toolset selects media tools.
    policy: {
      executor: 'media.generate',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['image', 'video', 'audio'],
    },
  },
  {
    id: 'media.understand',
    label: 'Media Analysis',
    type: 'integration',
    description:
      'Analyzes images, audio, and video: describes, extracts text (OCR), classifies, and answers questions about content.',
    intent: 'media_understanding',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit media analysis command.',
    routing_confidence: 0.88,
    priority: 88,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'analyze',
      aliases: ['ocr', 'analyze_media', 'analyze media'],
      description: 'Analyzes media (image, audio, video) with AI.',
      usage: '<file path> [type=describe|extract|classify|qa] [prompt]',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'media_understand',
    },
    // No free-text matchers — LLM full_toolset selects media tools.
    policy: {
      executor: 'media.understand',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['analysis-result'],
    },
  },
  {
    id: 'satellite.connect',
    label: 'Zavorth Satellite',
    type: 'integration',
    description: 'Manages Zavorth Satellite PWA connections via Node Mesh WebSocket.',
    intent: 'satellite_management',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit Satellite / remote PWA management command.',
    routing_confidence: 0.85,
    priority: 80,
    command: {
      command: 'satellite',
      aliases: ['sat', 'pwa'],
      description: 'Manages the Zavorth Satellite PWA (status, active sessions, URL).',
      usage: '[status|sessions|url]',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'satellite_connect',
    },
    policy: {
      executor: 'satellite.connect',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'local',
      lifecycle: 'session',
      artifactKinds: [],
    },
  },
  {
    id: 'search.query',
    label: 'Unified Web Search',
    type: 'integration',
    description: 'Unified web search with quick, deep, and grounded modes.',
    intent: 'web_search',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit web search command.',
    routing_confidence: 0.92,
    priority: 92,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'search',
      aliases: ['web_search', 'search web'],
      description: 'Unified web search with evidence ranking.',
      usage: '<query> [mode=quick|deep|grounded]',
      section: 'search',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'search_query',
    },
    // No free-text matchers — LLM full_toolset selects search tools.
    policy: {
      executor: 'search.query',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['search-result'],
    },
  },
];
