import { CapabilityDefinition } from '../../contracts/CapabilityContract.js';

export const INTEGRATION_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'command-file-delivery',
    label: 'File Delivery',
    type: 'integration',
    description: 'Finds and sends a local file.',
    intent: 'file_delivery',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command to locate and send a file.',
    routing_confidence: 1,
    command: {
      command: 'file',
      aliases: ['sendfile', 'arquivo'],
      description: 'Finds and sends a local file.',
      usage: '<request|path>',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'file_delivery',
    },
  },
  {
    id: 'command-task-files',
    label: 'Task Files',
    type: 'integration',
    description: 'Shows task files or performs natural file inspection.',
    intent: 'file_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit file inspection command.',
    routing_confidence: 1,
    command: {
      command: 'files',
      description: 'Shows files for a task.',
      usage: '[task_id|natural request]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_files',
    },
  },
  {
    id: 'command-task-diff',
    label: 'Task Diff',
    type: 'integration',
    description: 'Shows the diff for a task.',
    intent: 'file_diff',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit command to inspect a task diff.',
    routing_confidence: 1,
    command: {
      command: 'diff',
      description: 'Shows a task diff.',
      usage: '[task_id]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_diff',
    },
  },
  {
    id: 'command-tasks',
    label: 'Tasks',
    type: 'integration',
    description: 'Shows the recent task center.',
    intent: 'task_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit task inspection command.',
    routing_confidence: 1,
    command: {
      command: 'tasks',
      description: 'Lists recent tasks.',
      usage: '[active|approval|failed|completed|N]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_tasks',
    },
  },
  {
    id: 'command-logs',
    label: 'Logs',
    type: 'integration',
    description: 'Shows recent runtime logs.',
    intent: 'log_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Explicit log inspection command.',
    routing_confidence: 1,
    command: {
      command: 'logs',
      description: 'Mostra logs recentes.',
      usage: '[quantidade]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_logs',
    },
  },
  {
    id: 'command-capabilities',
    label: 'Capabilities',
    type: 'integration',
    description: 'Lista capabilities e plugins carregados.',
    intent: 'capability_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para ver capabilities carregadas.',
    routing_confidence: 1,
    command: {
      command: 'capabilities',
      description: 'Lista capabilities e plugins carregados.',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'ops_capabilities',
    },
  },
  {
    id: 'command-zavorthControl',
    label: 'ZavorthControl',
    type: 'integration',
    description: 'Abre o painel web do Zavorth.',
    intent: 'zavorthControl_access',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para abrir o zavorthControl.',
    routing_confidence: 1,
    command: {
      command: 'zavorthControl',
      aliases: ['app', 'miniapp'],
      description: 'Abre o painel web do Zavorth.',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'ops_zavorthControl',
    },
  },
  {
    id: 'command-mcp',
    label: 'MCP Servers',
    type: 'integration',
    description: 'Gerencia servidores MCP: instalar, remover, listar e verificar status.',
    intent: 'mcp_management',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para gerenciamento de servidores MCP.',
    routing_confidence: 1,
    command: {
      command: 'mcp',
      description: 'Gerencia servidores MCP (install, remove, status, enable, disable).',
      usage: '<install|remove|status|enable|disable> [id] [command] [args...]',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'mcp_management',
    },
  },
  {
    id: 'media.generate',
    label: 'Geracao de Midia',
    type: 'integration',
    description: 'Gera imagens, videos ou audio a partir de prompt textual.',
    intent: 'media_generation',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve geracao de midia visual ou sonora.',
    routing_confidence: 0.90,
    priority: 90,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'imagine',
      aliases: ['img', 'gerar_imagem', 'generate_image'],
      description: 'Gera imagens a partir de um prompt textual.',
      usage: '<prompt descritivo>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'media_generate',
    },
    matchers: [
      {
        patterns: [
          '\\b(gere|gerar|crie|criar|faca|fazer|produza|produzir|desenhe|desenhar)\\b.*\\b(imagem|imagens|foto|fotos|ilustracao|ilustracoes|arte|artwork|picture|image|icon|icone|banner|thumbnail|wallpaper)\\b',
          '\\b(imagem|foto|ilustracao|arte|picture|image)\\b.*\\b(de|do|da|com|sobre|mostrando|showing)\\b',
          '\\b(imagine|visualize|render|renderize)\\b',
        ],
      },
    ],
    policy: {
      executor: 'media.generate',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['image', 'video', 'audio'],
    },
  },
  {
    id: 'media.understand',
    label: 'Media Analysis',
    type: 'integration',
    description: 'Analyzes images, audio, and video: describes, extracts text (OCR), classifies, and answers questions about content.',
    intent: 'media_understanding',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Request involves analysis, description, or understanding of received media.',
    routing_confidence: 0.88,
    priority: 88,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'analyze',
      aliases: ['analisar', 'analise', 'descrever', 'ocr', 'analyze_media'],
      description: 'Analyzes media (image, audio, video) with AI.',
      usage: '<file path> [type=describe|extract|classify|qa] [prompt]',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'media_understand',
    },
    matchers: [
      {
        patterns: [
          '\\b(analise|analisar|descreva|descrever|identifique|identificar|leia|ler)\\b.*\\b(imagem|foto|imagens|fotos|screenshot|print|captura|tela|audio|video|midia)\\b',
          '\\b(o que|que|quem|qual|como)\\b.*\\b(tem|esta|aparece|mostra|diz|fala)\\b.*\\b(imagem|foto|audio|video|arquivo|midia)\\b',
          '\\b(ocr|transcrever|transcreva|extrair texto|extraia texto)\\b',
        ],
      },
    ],
    policy: {
      executor: 'media.understand',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['analysis-result'],
    },
  },
  {
    id: 'satellite.connect',
    label: 'Zavorth Satellite',
    type: 'integration',
    description: 'Gerencia conexoes do Zavorth Satellite PWA via Node Mesh WebSocket.',
    intent: 'satellite_management',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve gerenciamento do Satellite ou acesso remoto via PWA.',
    routing_confidence: 0.85,
    priority: 80,
    command: {
      command: 'satellite',
      aliases: ['sat', 'pwa'],
      description: 'Gerencia o Zavorth Satellite PWA (status, sessoes ativas, URL).',
      usage: '[status|sessions|url]',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'satellite_connect',
    },
    policy: {
      executor: 'satellite.connect',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'local',
      lifecycle: 'session',
      artifactKinds: [],
    },
  },
  {
    id: 'search.query',
    label: 'Busca Web Unificada',
    type: 'integration',
    description: 'Busca web unificada com modos rapido, profundo e grounded.',
    intent: 'web_search',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve pesquisa, busca ou consulta na web.',
    routing_confidence: 0.92,
    priority: 92,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'search',
      aliases: ['busca', 'pesquisa', 'web_search'],
      description: 'Busca web unificada com ranking de evidencia.',
      usage: '<consulta> [mode=quick|deep|grounded]',
      section: 'search',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'search_query',
    },
    matchers: [
      {
        patterns: [
          '\\b(pesquise|pesquisa|pesquisar|busque|buscar|procure|procurar|search|find)\\b.*\\b(web|internet|online|google|na web)\\b',
          '\\b(noticias|noticia|news)\\b.*\\b(hoje|do dia|na web|online|internet|recentes|ultimas)\\b',
        ],
      },
    ],
    policy: {
      executor: 'search.query',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['search-result'],
    },
  },
];
