import * as fs from 'fs';
import * as path from 'path';
import { SecurityLockService } from '../services/SecurityLockService.js';
import { asErrorLike } from '../utils/errorLike.js';

/**
 * HoneypotMonitor - creates and watches canary decoy files.
 *
 * Watching happens at the directory level, not on the file itself, so the
 * monitor survives delete/rename/recreate cycles for the decoy file.
 *
 * Important: the honeypot never locks the bot on its own.
 * It only alerts the admin so they can decide what to do.
 */
export class HoneypotMonitor {
  private readonly honeyPath: string;
  private readonly dirPath: string;
  private watcher: fs.FSWatcher | null = null;
  private triggeredAt = 0;

  /**
   * Timestamp of the latest write performed by this monitor.
   * Watcher events received within SELF_WRITE_WINDOW_MS after this
   * mark are treated as self-generated and ignored.
   */
  private lastSelfWriteAt = 0;
  private static readonly SELF_WRITE_WINDOW_MS = 300;

  /**
   * Timestamp captured when the monitor starts.
   * Events during the first GRACE_MS milliseconds are ignored
   * to absorb filesystem noise during startup.
   */
  private startedAt = 0;
  private static readonly GRACE_MS = 2000;

  constructor(
    private securityLock: SecurityLockService,
    private botAlertCallback: (message: string) => Promise<void>,
    dataDir?: string,
  ) {
    this.dirPath = dataDir || path.resolve(process.cwd(), 'data');
    this.honeyPath = path.join(this.dirPath, 'secrets_honey.txt');
  }

  public start(): void {
    try {
      if (!fs.existsSync(this.dirPath)) {
        fs.mkdirSync(this.dirPath, { recursive: true });
      }

      this.stop();
      this.createDecoyFile();
      this.startedAt = Date.now();

      const honeyFileName = path.basename(this.honeyPath);

      this.watcher = fs.watch(this.dirPath, { persistent: false }, async (eventType, filename) => {
        // Ignore events generated by the monitor's own write.
        if (Date.now() - this.lastSelfWriteAt < HoneypotMonitor.SELF_WRITE_WINDOW_MS) {
          return;
        }

        const normalizedName = String(filename ?? '').replace(/\u0000/g, '');

        if (normalizedName && path.basename(normalizedName) !== honeyFileName) {
          return;
        }

        await this.handleAccess(eventType);
      });

      this.watcher.on('error', (err) => {
        console.error('Honeypot watcher error:', err);
      });

      console.log('Honeypot armed at:', this.honeyPath);
    } catch (error: unknown) {console.error('Failed to start honeypot:', error);
    }
  }

  public stop(): void {
    if (this.watcher) {
      this.watcher.close();
      this.watcher = null;
    }
  }

  private createDecoyFile(): void {
    const decoyContent = [
      '# MIGRATED SECRETS - DO NOT DELETE',
      '# This file contains unencrypted legacy backups of API keys.',
      'GEMINI_MASTER_KEY=<decoy-gemini-key-redacted>',
      'OPENAI_ADMIN_KEY=<decoy-openai-key-redacted>',
      'DB_ROOT_PASSWORD=<decoy-password-redacted>',
      'SSH_PRIVATE_KEY_PASSPHRASE=zavorth_is_watching',
    ].join('\n');

    try {
      fs.writeFileSync(this.honeyPath, decoyContent, 'utf-8');
      this.lastSelfWriteAt = Date.now();
    } catch (error: unknown) {console.error('Failed to write honeypot decoy:', error);
    }
  }

  private async handleAccess(eventType: string): Promise<void> {
    // Decoy self-healing must not depend on debounce.
    if (eventType === 'rename' || !fs.existsSync(this.honeyPath)) {
      this.createDecoyFile();
      // Return without alerting because the event was generated by recreation.
      return;
    }

    // Alert debounce avoids flooding the operator.
    const now = Date.now();

    // Startup grace period absorbs filesystem noise.
    if (now - this.startedAt < HoneypotMonitor.GRACE_MS) {
      return;
    }

    if (now - this.triggeredAt < 30000) {
      return;
    }
    this.triggeredAt = now;

    // Never lock the bot automatically.
    // Only notify the admin so they can decide.
    try {
      const alertMessage =
        `**SECURITY NOTICE: Honeypot triggered**\n\n` +
        `The sensitive canary file (\`secrets_honey.txt\`) was accessed.\n` +
        `This may indicate that an autonomous agent is exploring directories.\n\n` +
        `Zavorth is still operating normally.\n` +
        `Use \`/lock\` if you need to lock it manually.`;

      await this.botAlertCallback(alertMessage);
      console.warn('Honeypot: canary file access detected (alert only, no lock).');
    } catch (error: unknown) {
      const err = asErrorLike(error);
      console.error('Failed to process honeypot alert:', err.message);
    }
  }
}
