/**
 * ChannelScaffoldCommand — Generates boilerplate for new channel adapters.
 *
 * Usage:
 *   zavorth scaffold channel my-channel --type=webhook --name="My Channel"
 *
 * This command creates:
 * 1. Channel adapter template (src/gateways/channels/my-channel/)
 * 2. Gateway template
 * 3. Capabilities configuration
 * 4. Registration in channel mesh
 */

import fs from 'fs';
import path from 'path';

export interface ChannelScaffoldOptions {
  name: string;
  type?: 'webhook' | 'bot' | 'bridge';
  channelName?: string;
  supportsMarkdown?: boolean;
  supportsButtons?: boolean;
  maxLength?: number;
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}


function generateAdapterTemplate(name: string, pascalName: string, type: string): string {
  return `/**
 * ${pascalName}ChannelAdapter — Channel adapter for ${name}.
 *
 * Generated by: zavorth scaffold channel ${name}
 * Type: ${type}
 */

import { GatewayChannelAdapter } from '../../../gateway/channels/GatewayChannelAdapter.js';
import { GatewayEventBus } from '../../../gateway/events/GatewayEventBus.js';
import {
  buildInboundChannelEvent,
  buildOutboundChannelEnvelope,
  persistChannelOutboxEnvelope,
} from '../../../channels/contracts/ChannelMessageContract.js';

export class ${pascalName}ChannelAdapter implements GatewayChannelAdapter {
  id = '${name}';
  name = '${name}';
  type: 'async' = 'async';

  constructor(
    private eventBus: GatewayEventBus,
    private policyManager: ChannelPolicyManager,
    private apiKey: string,
  ) {}

  async initialize(): Promise<void> {
    console.log('[ChannelMesh] ${name} adapter initialized.');
  }

  async shutdown(): Promise<void> {
    console.log('[ChannelMesh] ${name} adapter shut down.');
  }

  async onMessageReceived(payload: Record<string, unknown>): Promise<void> {
    const userId = String(payload.userId || payload.from || '').trim();
    const chatId = String(payload.chatId || payload.to || '${name}').trim();
    const rawText = String(payload.text || payload.message || '').trim();

    if (!rawText) return;

    const isAllowed = await this.policyManager.verifyChatAccess('${name}', chatId, userId);
    if (!isAllowed) {
      console.warn(\`[Security] Blocked unauthorized ${name} interaction from \${userId}\`);
      return;
    }

    await this.eventBus.emit(buildInboundChannelEvent({
      platform: '${name}' as any,
      userId,
      chatId,
      rawText,
      now: new Date(),
    }));
  }

  async sendMessage(text: string, chatId: string): Promise<void> {
    const envelope = buildOutboundChannelEnvelope({
      platform: '${name}' as any,
      transport: 'local-outbox',
      recipients: [chatId],
      message: text,
      now: new Date(),
    });
    // Persist to outbox for processing
    console.log(\`[${name}] Message queued for \${chatId}: \${text.slice(0, 50)}...\`);
  }
}
`;
}

function generateGatewayTemplate(name: string, pascalName: string, type: string): string {
  return `/**
 * ${pascalName}Gateway — Gateway for ${name} channel.
 *
 * Generated by: zavorth scaffold channel ${name}
 * Type: ${type}
 */

import { WebhookGateway, type WebhookGatewayOptions } from '../../WebhookGateway.js';

export class ${pascalName}Gateway extends WebhookGateway {
  public readonly id = '${name}';
  public readonly name = '${name}';
  public readonly type: 'async' = 'async';

  constructor(options: WebhookGatewayOptions) {
    super(options);
  }

  public handleWebhookVerification(url: URL): { statusCode: number; textBody: string } {
    // Implement verification logic for your channel
    return { statusCode: 200, textBody: 'ok' };
  }

  public async handleWebhookEvent(input: { body: Record<string, unknown> }): Promise<{ statusCode: number; body: unknown }> {
    const ok = await this.onMessageReceived(input.body);
    return { statusCode: ok ? 200 : 400, body: { ok } };
  }

  public resolveConfigured(): boolean {
    // Return true if the channel is properly configured
    return Boolean(process.env.${name.toUpperCase()}_API_KEY || process.env.${name.toUpperCase()}_WEBHOOK_URL);
  }
}
`;
}

function generateCapabilitiesConfig(name: string, options: ChannelScaffoldOptions): string {
  return `{
  "id": "${name}",
  "label": "${options.channelName || name}",
  "supportsMarkdown": ${options.supportsMarkdown ?? true},
  "supportsButtons": ${options.supportsButtons ?? false},
  "supportsRichEmbeds": false,
  "supportsImages": true,
  "supportsAudio": false,
  "supportsVideo": false,
  "supportsReactions": false,
  "supportsHTML": false,
  "supportsThreads": false,
  "supportsMessageEditing": false,
  "supportsPinning": false,
  "maxMessageLength": ${options.maxLength ?? 4096},
  "maxButtonsPerMessage": ${options.supportsButtons ? 8 : 0},
  "maxAttachmentsPerMessage": 10,
  "supportsEphemeral": false,
  "supportsScheduledMessages": false,
  "supportsTypingIndicator": false,
  "supportsPresence": false
}`;
}

/**
 * Scaffold a new channel adapter.
 */
export function scaffoldChannel(
  projectRoot: string,
  options: ChannelScaffoldOptions,
): { files: string[]; success: boolean } {
  const name = options.name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const pascalName = toPascalCase(name);
  const channelDir = path.join(projectRoot, 'src', 'gateways', 'channels', name);

  try {
    // Create directory
    fs.mkdirSync(channelDir, { recursive: true });

    // Generate adapter
    const adapterContent = generateAdapterTemplate(name, pascalName, options.type || 'webhook');
    fs.writeFileSync(path.join(channelDir, `${pascalName}ChannelAdapter.ts`), adapterContent);

    // Generate gateway
    const gatewayContent = generateGatewayTemplate(name, pascalName, options.type || 'webhook');
    fs.writeFileSync(path.join(channelDir, `${pascalName}Gateway.ts`), gatewayContent);

    // Generate capabilities config
    const capsContent = generateCapabilitiesConfig(name, options);
    fs.writeFileSync(path.join(channelDir, 'capabilities.json'), capsContent);

    // Generate index file
    const indexContent = `export { ${pascalName}ChannelAdapter } from './${pascalName}ChannelAdapter.js';\nexport { ${pascalName}Gateway } from './${pascalName}Gateway.js';\n`;
    fs.writeFileSync(path.join(channelDir, 'index.ts'), indexContent);

    return {
      files: [
        `${pascalName}ChannelAdapter.ts`,
        `${pascalName}Gateway.ts`,
        'capabilities.json',
        'index.ts',
      ],
      success: true,
    };
  } catch (error: unknown) {
    return { files: [], success: false };
  }
}
