import * as path from 'path';
import { config } from '../config/index.js';

export const CLI_REPL_HISTORY_LIMIT = 200;
export const CLI_REPL_HISTORY_FILE = path.resolve(
  config.projectRoot,
  'data',
  'runtime',
  'zavorth-cli-history.txt',
);

export const CLI_REPL_SUGGESTIONS = [
  '...',
  'help',
  'chat',
  'run ',
  'continue',
  'approve ',
  'reject ',
  'resume ',
  'restart-stage ',
  'close-workflow ',
  'context',
  'status',
  'status --live',
  'doctor',
  'brief',
  'brief --live',
  'cockpit',
  'ops',
  'ops --live',
  'ops quality',
  'ops actions',
  'ops access',
  'ops bootstrap',
  'ops bootstrap repair dryrun',
  'ops changes',
  'ops autorepair status',
  'heal --preview',
  'heal --apply',
  'heal report',
  'release status',
  'release diff previous latest',
  'release rollback --preview',
  'release presence',
  'gateway',
  'gateway status',
  'gateway providers',
  'gateway models',
  'gateway combos',
  'gateway combo test ',
  'gateway cache stats',
  'gateway rate-limits',
  'gateway doctor',
  'workspace init',
  'workspace doctor',
  'workspace status',
  'workspace up --dry-run',
  'workspace up --approve',
  'workspace stop --all --approve',
  'workspace restart ',
  'domains',
  'learning status',
  'learning candidates',
  'learning metrics',
  'learning approve ',
  'learning reject ',
  'learning promote ',
  'memory status',
  'memory metrics',
  'memory search ',
  'memory procedures',
  'memory review',
  'memory resolve continue this thread',
  'memory forget ',
  'memory correct ',
  'memoryplane',
  'sessions list',
  'sessions history ',
  'sessions send ',
  'sessions spawn',
  'sessions',
  'sessionhistory ',
  'sessionsend ',
  'sessionspawn',
  'nodes list',
  'nodes',
  'nodes profiles',
  'nodes capabilities',
  'nodes queue',
  'nodes history',
  'nodes doctor',
  'nodes pair browser ',
  'nodepair browser ',
  'nodeinvoke ',
  'tools',
  'skills',
  'skills recipe ',
  'skills mcp',
  'hooks',
  'workflow resume ',
  'workflow restart-stage ',
  'workflow close ',
  'AIGateway',
  'AIGateway status',
  'AIGateway route',
  'AIGateway start',
  'AIGateway route start',
  'AIGateway doctor',
  'AIGateway sync',
  'AIGateway promote',
  'AIGateway rollback',
  'plugins list',
  'plugins doctor ',
  'plugins install ',
  'plugins trust ',
  'platform',
  'platform sync',
  'platform publish ',
  'platform install ',
  'platform trust ',
  'platform review ',
  'platform remove ',
  'transports',
  'channels',
  'runtime',
  'agmobile status',
  'task ',
  'dryrun ',
  'run ',
  'workflow ',
  'codex ',
  'external_executor ',
  'gemini ',
  'aistudio ',
  'stitch ',
  'jules ',
  'ag ',
  'bridge ',
  'quit',
  'exit',
];
