import type { Bot } from 'grammy';
import type { ChannelCommandParser } from '../../../../channels/commands/ChannelCommandParser.js';
import type { AudioHandler } from '../../../../gateways/channels/telegram/AudioHandler.js';
import type { VideoHandler } from '../../../../services/media/VideoHandler.js';
import type { ExecutionGateway } from '../../../../execution/ExecutionGateway.js';
import type { AuditLogger } from '../../../../monitoring/AuditLogger.js';
import type { ZavorthBridgePreferenceStore } from '../../../../agents/ZavorthBridgePreferenceStore.js';
import type { RemoteModeManager } from '../../../../services/RemoteModeManager.js';
import type { ZavorthBridgeControlService } from '../../../../services/ZavorthBridgeControlService.js';
import type { ZavorthBridgePromptService } from '../../../../services/ZavorthBridgePromptService.js';
import type { WslControlService } from '../../../../services/WslControlService.js';
import type { SystemCleanupService } from '../../../../services/SystemCleanupService.js';
import type { ChatCleanupService } from '../../../../services/ChatCleanupService.js';
import type { PermissionService } from '../../../../services/PermissionService.js';
import type { SecurityLockService } from '../../../../services/SecurityLockService.js';
import type { HoneypotMonitor } from '../../../../monitoring/HoneypotMonitor.js';
import type { SchedulerService } from '../../../../services/SchedulerService.js';
import type { FunGamesService } from '../../../../services/FunGamesService.js';
import type { WelcomeService } from '../../../../services/WelcomeService.js';
import type { AntiSpamService } from '../../../../services/AntiSpamService.js';
import type { MessageFilterService } from '../../../../services/MessageFilterService.js';
import type { WarnService } from '../../../../services/WarnService.js';
import type { GroupModerationService } from '../../../../services/GroupModerationService.js';
import type { GroupStatsService } from '../../../../services/GroupStatsService.js';
import type { ZavorthControlService } from '../../../../services/ZavorthControlService.js';
import type { DailyReportService } from '../../../../services/DailyReportService.js';
import type { DemoGuideService } from '../../../../services/DemoGuideService.js';
import type { DemoModeService } from '../../../../services/DemoModeService.js';
import type { OperatorModeService } from '../../../../services/OperatorModeService.js';
import type { PresentationModeService } from '../../../../services/PresentationModeService.js';
import type { RuntimeDiagnosticsService } from '../../../../services/RuntimeDiagnosticsService.js';
import type { RuntimeCompositionService } from '../../../../services/RuntimeCompositionService.js';
import type { TelemetryRuntimeService } from '../../../../observability/telemetry/TelemetryRuntimeService.js';
import type { WorkspaceProfileService } from '../../../../services/WorkspaceProfileService.js';
import type { WorkspaceCommandService } from '../../../../services/WorkspaceCommandService.js';
import type { JulesQueueWorker } from '../../../../orchestrator/JulesQueueWorker.js';
import type { TelegramMenuController } from '../../../../gateways/channels/telegram/controllers/TelegramMenuController.js';
import type { TelegramOpsController } from '../../../../gateways/channels/telegram/controllers/TelegramOpsController.js';
import type { TelegramFunController } from '../../../../gateways/channels/telegram/controllers/TelegramFunController.js';
import type { ResearchQueueWorker } from '../../../../orchestrator/ResearchQueueWorker.js';
import type { TelegramMediaController } from '../../../../gateways/channels/telegram/controllers/TelegramMediaController.js';
import type { TelegramZavorthBridgeController } from '../../../../gateways/channels/telegram/controllers/TelegramZavorthBridgeController.js';
import type { TelegramHubController } from '../../../../gateways/channels/telegram/controllers/TelegramHubController.js';
import type { TelegramPermissionController } from '../../../../gateways/channels/telegram/controllers/TelegramPermissionController.js';
import type { TelegramEchoApprovalController } from '../../../../gateways/channels/telegram/controllers/TelegramEchoApprovalController.js';
import type { TelegramCallbackController } from '../../../../gateways/channels/telegram/controllers/TelegramCallbackController.js';
import type { TelegramKnowledgeController } from '../../../../gateways/channels/telegram/controllers/TelegramKnowledgeController.js';
import type { TelegramSchedulerController } from '../../../../gateways/channels/telegram/controllers/TelegramSchedulerController.js';
import type { TelegramInspectionController } from '../../../../gateways/channels/telegram/controllers/TelegramInspectionController.js';
import type { TelegramSecurityController } from '../../../../gateways/channels/telegram/controllers/TelegramSecurityController.js';
import type { TelegramExecutionController } from '../../../../gateways/channels/telegram/controllers/TelegramExecutionController.js';
import type { TelegramChainController } from '../../../../gateways/channels/telegram/controllers/TelegramChainController.js';
import type { TelegramGroupAdminController } from '../../../../gateways/channels/telegram/controllers/TelegramGroupAdminController.js';
import type { TelegramGroupEventController } from '../../../../gateways/channels/telegram/controllers/TelegramGroupEventController.js';
import type { TelegramTaskOrchestrationController } from '../../../../gateways/channels/telegram/controllers/TelegramTaskOrchestrationController.js';
import type { TelegramLifecycleController } from '../../../../gateways/channels/telegram/controllers/TelegramLifecycleController.js';
import type { TelegramProviderController } from '../../../../gateways/channels/telegram/controllers/TelegramProviderController.js';
import type { TelegramResearchController } from '../../../../gateways/channels/telegram/controllers/TelegramResearchController.js';
import type { TelegramPipelineController } from '../../../../gateways/channels/telegram/controllers/TelegramPipelineController.js';
import type { TelegramCapabilityController } from '../../../../gateways/channels/telegram/controllers/TelegramCapabilityController.js';
import type { TelegramSelfModificationController } from '../../../../gateways/channels/telegram/controllers/TelegramSelfModificationController.js';
import type { TelegramFileDeliveryController } from '../../../../gateways/channels/telegram/controllers/TelegramFileDeliveryController.js';
import type { TelegramSkillCatalogController } from '../../../../gateways/channels/telegram/controllers/TelegramSkillCatalogController.js';
import type { SupervisedRuntimeNotificationService } from '../../../../services/SupervisedRuntimeNotificationService.js';
import type { HostIdentityService } from '../../../../services/HostIdentityService.js';
import type { SurfaceIdentityService } from '../../../../services/SurfaceIdentityService.js';
import type { SurfaceTaskDispatchService } from '../../../../services/SurfaceTaskDispatchService.js';
import type { TelegramCommandRoutingService } from '../../../../gateways/channels/telegram/TelegramCommandRoutingService.js';
import type { TelegramPriorityCommandService } from '../../../../gateways/channels/telegram/TelegramPriorityCommandService.js';
import type { SurfaceCommandBoundary } from '../../../../api/internal/InternalSurfaceApiCompat.js';
import type { CapabilityLifecycleService } from '../../../../services/CapabilityLifecycleService.js';
import type { RuntimeProfileService } from '../../../../services/RuntimeProfileService.js';
import type { TelegramChannelContractService } from '../../../../gateways/channels/telegram/TelegramChannelContractService.js';
import type { BotGatewaySupport } from '../../../../gateways/channels/telegram/bot-gateway/BotGatewaySupport.js';
import type { EchoOutputStageService } from '../../../../services/EchoOutputStageService.js';

export abstract class BotGatewayState {
  public readonly platform = 'telegram';
  public readonly supportsRoleAwareBroadcast = true;
  protected bot!: Bot;
  protected parser!: ChannelCommandParser;
  protected audioHandler!: AudioHandler;
  protected echoOutputStage!: EchoOutputStageService;
  protected videoHandler!: VideoHandler;
  protected zavorthBridgePreferenceStore!: ZavorthBridgePreferenceStore;
  protected remoteModeManager!: RemoteModeManager;
  protected zavorthBridgeControlService!: ZavorthBridgeControlService;
  protected zavorthBridgePromptService!: ZavorthBridgePromptService;
  protected executionGateway!: ExecutionGateway;
  protected auditLogger!: AuditLogger;
  protected wslControl!: WslControlService;
  protected systemCleanup!: SystemCleanupService;
  protected chatCleanup!: ChatCleanupService;
  protected permissionService!: PermissionService;
  protected securityLock!: SecurityLockService;
  protected honeypot!: HoneypotMonitor;
  protected schedulerService!: SchedulerService;
  protected funGamesService!: FunGamesService;
  protected zavorthControlService!: ZavorthControlService;
  protected dailyReportService!: DailyReportService;
  protected demoGuideService!: DemoGuideService;
  protected demoModeService!: DemoModeService;
  protected operatorModeService!: OperatorModeService;
  protected presentationModeService!: PresentationModeService;
  protected runtimeDiagnostics!: RuntimeDiagnosticsService;
  protected workspaceProfileService!: WorkspaceProfileService;
  protected workspaceCommandService!: WorkspaceCommandService;
  protected menuController!: TelegramMenuController;
  protected opsController!: TelegramOpsController;
  protected funController!: TelegramFunController;
  protected mediaController!: TelegramMediaController;
  protected zavorthBridgeController!: TelegramZavorthBridgeController;
  protected hubController!: TelegramHubController;
  protected skillCatalogController!: TelegramSkillCatalogController;
  protected permissionController!: TelegramPermissionController;
  protected echoApprovalController!: TelegramEchoApprovalController;
  protected callbackController!: TelegramCallbackController;
  protected knowledgeController!: TelegramKnowledgeController;
  protected schedulerController!: TelegramSchedulerController;
  protected inspectionController!: TelegramInspectionController;
  protected securityController!: TelegramSecurityController;
  protected executionController!: TelegramExecutionController;
  protected chainController!: TelegramChainController;
  protected taskOrchestrationController!: TelegramTaskOrchestrationController;
  protected lifecycleController!: TelegramLifecycleController;
  protected providerController!: TelegramProviderController;
  protected researchController!: TelegramResearchController;
  protected researchQueueWorker!: ResearchQueueWorker;
  protected julesQueueWorker!: JulesQueueWorker;
  protected pipelineController!: TelegramPipelineController;
  protected capabilityController!: TelegramCapabilityController;
  protected groupAdminController!: TelegramGroupAdminController;
  protected groupEventController!: TelegramGroupEventController;
  protected commandRoutingService!: TelegramCommandRoutingService;
  protected priorityCommandService!: TelegramPriorityCommandService;
  protected welcomeService!: WelcomeService;
  protected antiSpamService!: AntiSpamService;
  protected messageFilterService!: MessageFilterService;
  protected warnService!: WarnService;
  protected groupModerationService!: GroupModerationService;
  protected groupStatsService!: GroupStatsService;
  protected selfModificationController!: TelegramSelfModificationController;
  protected fileDeliveryController!: TelegramFileDeliveryController;
  protected swarmController!: import('../controllers/TelegramSwarmController.js').TelegramSwarmController;
  protected hostIdentityService!: HostIdentityService;
  protected runtimeComposition!: RuntimeCompositionService;
  protected telemetryRuntime!: TelemetryRuntimeService;
  protected supervisedRuntimeNotificationService!: SupervisedRuntimeNotificationService;
  protected surfaceIdentityService!: SurfaceIdentityService;
  protected surfaceTaskDispatcher!: SurfaceTaskDispatchService;
  protected sharedSurfaceCommandService: SurfaceCommandBoundary | null = null;
  protected readonly runtimeProfileService!: RuntimeProfileService;
  protected readonly capabilityLifecycleService!: CapabilityLifecycleService;
  protected readonly telegramChannelContractService!: TelegramChannelContractService;
  protected botGatewaySupport!: BotGatewaySupport;
}
