import { asErrorLike } from '../../utils/errorLike';
export const runtimeShellScriptPart2Seg2: string = [
    "  for (const artifact of (Array.isArray(replay?.recentArtifacts) ? replay.recentArtifacts : []).slice(0, 2)) {",
    "    const artifactLabel = escapeHtml(artifact?.label || artifact?.path || artifact?.id || 'Entrega recente');",
    "    const artifactSummary = normalizeText(artifact?.summary) ? escapeHtml(artifact.summary) : '';",
    "    items.push(",
    "      '<strong>Artifact:</strong> '",
    "      + artifactLabel",
    "      + (artifactSummary ? ' ? ' + artifactSummary : '')",
    "      + buildSessionReplayButtonHtml(",
    "        'summarize artifact',",
    "        'resume-artifact',",
    "        artifactLabel,",
    "        artifactSummary,",
    "      ),",
    "    );",
    "  }",
    "  if (items.length < 4 && (normalizeText(handoff?.headline) || normalizeText(handoff?.operatorSummary))) {",
    "    items.push(",
    "      '<strong>Handoff:</strong> '",
    "      + escapeHtml(handoff?.headline || 'Handoff ready')",
    "      + (normalizeText(handoff?.operatorSummary) ? ' ? ' + escapeHtml(handoff.operatorSummary) : ''),",
    "    );",
    "  }",
    "  const timeline = Array.isArray(replay?.timeline) ? replay.timeline : [];",
    "  if (timeline.length > 1) {",
    "    const compareText = timeline",
    "      .slice(0, 3)",
    "      .map((step) => normalizeText(step?.label || step?.id || 'Evento'))",
    "      .filter(Boolean)",
    "      .join(' | ');",
    "    items.push(",
    "      '<strong>Comparar runs:</strong> '",
    "      + escapeHtml(compareText || 'Latest execucoes do replay')",
    "      + buildSessionReplayButtonHtml('Comparar runs', 'compare-runs', compareText, ''),",
    "    );",
    "  }",
    "  if (recommendedPrompt) {",
    "    items.push(",
    "      '<strong>resume agora:</strong> '",
    "      + escapeHtml(recommendedEntry?.label || handoff?.headline || 'Continuar a session')",
    "      + buildSessionReplayButtonHtml('resume agora', 'resume-recommended', recommendedPrompt, ''),",
    "    );",
    "  }",
    "  return items;",
    "}",
    "",
    "function readSessionWorkspaceToolRuns(statePayload, toolRunsPayload) {",
    "  const fromToolPlane = Array.isArray(toolRunsPayload?.toolRuns) ? toolRunsPayload.toolRuns : [];",
    "  if (fromToolPlane.length > 0) {",
    "    return fromToolPlane;",
    "  }",
    "  return Array.isArray(statePayload?.snapshot?.toolRuns) ? statePayload.snapshot.toolRuns : [];",
    "}",
    "",
    "function buildSessionToolDiffButtonHtml(runId) {",
    "  const normalized = normalizeText(runId);",
    "  if (!normalized) {",
    "    return '';",
    "  }",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action inline-choice-button\"'",
    "    + ' data-session-tool-diff=\"' + escapeHtml(normalized) + '\">'",
    "    + 'Ver diff'",
    "    + '</button>';",
    "}",
    "",
    "function buildSessionWorkspaceToolItems(toolRuns) {",
    "  if (!Array.isArray(toolRuns) || toolRuns.length === 0) {",
    "    return ['No recent tool runs in this session. When Zavorth edits files, runs commands, or generates artifacts, they appear here.'];",
    "  }",
    "  return toolRuns.slice(0, 6).map((run) => {",
    "    const runId = normalizeText(run?.runId);",
    "    const toolName = normalizeText(run?.toolName || run?.tool_name || run?.name || 'tool');",
    "    const status = normalizeText(run?.status || 'unknown');",
    "    const files = Array.isArray(run?.filesTouched) ? run.filesTouched.filter(Boolean) : [];",
    "    const artifacts = Array.isArray(run?.artifacts) ? run.artifacts : [];",
    "    const patches = Array.isArray(run?.diff?.patches) ? run.diff.patches : [];",
    "    const primaryFile = normalizeText(files[0] || patches[0]?.path || '');",
    "    const diffSummary = normalizeText(run?.diff?.summary || patches[0]?.summary || run?.summary || '');",
    "    const detailParts = [",
    "      primaryFile ? 'file ' + escapeHtml(primaryFile) : '',",
    "      patches.length ? String(patches.length) + ' patch(es)' : '',",
    "      artifacts.length ? String(artifacts.length) + ' artifact(s)' : '',",
    "    ].filter(Boolean);",
    "    return '<strong>' + escapeHtml(toolName) + '</strong>'",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(status) + ']</span>'",
    "      + (detailParts.length ? '<br><span class=\"muted-inline\">' + detailParts.join(' | ') + '</span>' : '')",
    "      + (diffSummary ? '<br><span class=\"muted-inline\">' + escapeHtml(diffSummary.slice(0, 220)) + '</span>' : '')",
    "      + buildSessionToolDiffButtonHtml(runId);",
    "  });",
    "}",
    "",
    "function buildSessionWorkspaceDiffItems(toolRuns) {",
    "  if (!Array.isArray(toolRuns) || toolRuns.length === 0) {",
    "    return ['No consolidated diff appeared in this session yet. When a patch exists, it will be visible here.'];",
    "  }",
    "  const runsWithDiff = toolRuns.filter((run) => Array.isArray(run?.diff?.patches) && run.diff.patches.length > 0);",
    "  if (runsWithDiff.length === 0) {",
    "    return ['As tools executaram, mas ainda none patch textual consolidado para mostrar neste momento.'];",
    "  }",
    "  return runsWithDiff.slice(0, 6).map((run) => {",
    "    const runId = normalizeText(run?.runId);",
    "    const patches = Array.isArray(run?.diff?.patches) ? run.diff.patches : [];",
    "    const firstPatch = patches[0] || null;",
    "    const path = normalizeText(firstPatch?.path || run?.filesTouched?.[0] || 'file without path');",
    "    const summary = normalizeText(run?.diff?.summary || firstPatch?.summary || run?.summary || 'Recent patch ready for review.');",
    "    const artifactCount = Array.isArray(run?.artifacts) ? run.artifacts.length : 0;",
    "    return '<strong>' + escapeHtml(path) + '</strong>'",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(run?.toolName || 'tool')) + ']</span>'",
    "      + '<br><span class=\"muted-inline\">' + escapeHtml(summary.slice(0, 220)) + '</span>'",
    "      + '<br><span class=\"muted-inline\">' + String(patches.length) + ' patch(es) | ' + String(artifactCount) + ' artifact(s)</span>'",
    "      + buildSessionToolDiffButtonHtml(runId);",
    "  });",
    "}",
    "",
    "function formatSessionWorkspaceMb(value) {",
    "  const numeric = Number(value || 0);",
    "  if (!Number.isFinite(numeric)) {",
    "    return '0';",
    "  }",
    "  return String(Math.round(numeric));",
    "}",
    "",
    "function buildSessionWorkspaceCompanionActionButtonHtml(companionId, actionId, label, requiresApproval = false) {",
    "  const normalizedCompanionId = normalizeText(companionId);",
    "  const normalizedActionId = normalizeText(actionId);",
    "  if (!normalizedCompanionId || !normalizedActionId) {",
    "    return '';",
    "  }",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action inline-choice-button\"'",
    "    + ' data-session-companion-id=\"' + escapeHtml(normalizedCompanionId) + '\"'",
    "    + ' data-session-companion-action=\"' + escapeHtml(normalizedActionId) + '\"'",
    "    + ' data-session-companion-approval=\"' + escapeHtml(requiresApproval ? 'true' : 'false') + '\">'",
    "    + escapeHtml(label)",
    "    + '</button>';",
    "}",
    "",
    "function buildSessionWorkspaceResourceItems(resourcePlane, actionRecommendations) {",
    "  const host = resourcePlane?.host || null;",
    "  const groups = Array.isArray(resourcePlane?.groups) ? resourcePlane.groups : [];",
    "  const topConsumers = Array.isArray(resourcePlane?.topConsumers) ? resourcePlane.topConsumers : [];",
    "  const recommendedActions = Array.isArray(resourcePlane?.recommendedActions) ? resourcePlane.recommendedActions : [];",
    "  const items = [];",
    "",
    "  if (host) {",
    "    items.push(",
    "      '<strong>Host:</strong> '",
    "      + formatSessionWorkspaceMb(host.usedPhysicalMemoryMb) + '/' + formatSessionWorkspaceMb(host.totalVisibleMemoryMb)",
    "      + ' MB | carga ' + escapeHtml(normalizeText(host.memoryLoadPercent) || 'n/d') + '%'",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(host.pressure) || 'unknown') + ']</span>',",
    "    );",
    "  }",
    "",
    "  for (const group of groups.slice(0, 3)) {",
    "    items.push(",
    "      '<strong>' + escapeHtml(normalizeText(group?.label || group?.id || 'Grupo')) + ':</strong> '",
    "      + formatSessionWorkspaceMb(group?.metrics?.workingSetMb) + ' MB'",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(group?.pressure || group?.owner || 'n/d')) + ']</span>'",
    "      + '<br><span class=\"muted-inline\">' + escapeHtml(normalizeText(group?.summary || 'No additional summary.')) + '</span>',",
    "    );",
    "  }",
    "",
    "  for (const item of topConsumers.slice(0, 3)) {",
    "    items.push(",
    "      '<strong>Top consumer:</strong> '",
    "      + escapeHtml(normalizeText(item?.label || item?.id || 'Processo'))",
    "      + ' - ' + formatSessionWorkspaceMb(item?.metrics?.workingSetMb) + ' MB'",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(item?.owner || item?.kind || 'unknown')) + ']</span>',",
    "    );",
    "  }",
    "",
    "  const buttons = [];",
    "  for (const action of recommendedActions.slice(0, 2)) {",
    "    if (normalizeText(action?.controlId) && normalizeText(action?.actionId)) {",
    "      buttons.push(",
    "        buildSessionWorkspaceCompanionActionButtonHtml(",
    "          action.controlId,",
    "          action.actionId,",
    "          action.label || action.actionId,",
    "          action.requiresApproval === true,",
    "        ),",
    "      );",
    "    } else if (normalizeText(action?.command)) {",
    "      buttons.push(buildOperationalCopyButtonHtml(action.label || 'Copy action', action.command));",
    "    }",
    "  }",
    "",
    "  if (buttons.length === 0) {",
    "    for (const recommendation of (Array.isArray(actionRecommendations) ? actionRecommendations : []).slice(0, 2)) {",
    "      if (normalizeText(recommendation?.controlId) && normalizeText(recommendation?.actionId)) {",
    "        buttons.push(",
    "          buildSessionWorkspaceCompanionActionButtonHtml(",
    "            recommendation.controlId,",
    "            recommendation.actionId,",
    "            recommendation.label || recommendation.actionId,",
    "            recommendation.requiresApproval === true,",
    "          ),",
    "        );",
    "      }",
    "    }",
    "  }",
    "",
    "  if (buttons.length > 0) {",
    "    items.push('<strong>Actions sugeridas:</strong>' + buildOperationalInlineButtons(buttons));",
    "  }",
    "",
    "  return items.length > 0",
    "    - items",
    "    : ['Desktop Resource Plane unavailable para is session agora.'];",
    "}",
    "",
    "function buildSessionWorkspaceCompanionItems(companionPlane) {",
    "  const companions = Array.isArray(companionPlane?.companions) ? companionPlane.companions : [];",
    "  if (companions.length === 0) {",
    "    return ['No companion relevante apareceu on this host agora. when WSL, Docker, ZavorthBridge or Codex pesarem, eles aparecem aqui.'];",
    "  }",
    "  return companions.slice(0, 6).map((companion) => {",
    "    const buttons = (Array.isArray(companion?.actions) ? companion.actions : [])",
    "      .filter((action) => action?.available)",
    "      .slice(0, 2)",
    "      .map((action) => buildSessionWorkspaceCompanionActionButtonHtml(",
    "        companion?.id,",
    "        action?.actionId,",
    "        action?.label || action?.actionId || 'Action',",
    "        action?.requiresApproval === true,",
    "      ));",
    "    return '<strong>' + escapeHtml(normalizeText(companion?.label || companion?.id || 'Companion')) + ':</strong> '",
    "      + formatSessionWorkspaceMb(companion?.workingSetMb) + ' MB em ' + String(Number(companion?.processCount || 0) || 0) + ' process(s)'",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(companion?.status || 'unknown')) + ']</span>'",
    "      + '<br><span class=\"muted-inline\">' + escapeHtml(normalizeText(companion?.summary || 'No additional summary.')) + '</span>'",
    "      + buildOperationalInlineButtons(buttons);",
    "  });",
    "}",
    "",
    "function buildSessionWorkspaceHealthItems(runtimeWarnings, actionRecommendations) {",
    "  const warnings = Array.isArray(runtimeWarnings) ? runtimeWarnings : [];",
    "  const items = warnings.slice(0, 4).map((warning) => '<strong>Warning:</strong> ' + escapeHtml(normalizeText(warning || 'Warning operational.')));",
    "  for (const recommendation of (Array.isArray(actionRecommendations) ? actionRecommendations : []).slice(0, 4)) {",
    "    const buttons = [];",
    "    if (normalizeText(recommendation?.controlId) && normalizeText(recommendation?.actionId)) {",
    "      buttons.push(",
    "        buildSessionWorkspaceCompanionActionButtonHtml(",
    "          recommendation.controlId,",
    "          recommendation.actionId,",
    "          recommendation.label || recommendation.actionId,",
    "          recommendation.requiresApproval === true,",
    "        ),",
    "      );",
    "    } else if (normalizeText(recommendation?.command)) {",
    "      buttons.push(buildOperationalCopyButtonHtml(recommendation.label || 'Copy action', recommendation.command));",
    "    }",
    "    items.push(",
    "      '<strong>Action:</strong> ' + escapeHtml(normalizeText(recommendation?.label || 'Ajuste recomendado'))",
    "      + ' - <span class=\"muted-inline\">' + escapeHtml(normalizeText(recommendation?.summary || 'No additional summary.')) + '</span>'",
    "      + buildOperationalInlineButtons(buttons),",
    "    );",
    "  }",
    "  return items.length > 0",
    "    - items",
    "    : ['No warning operational importante apareceu nesta session agora.'];",
    "}",
    "",
    "function buildSessionWorkspaceCapabilityItems(capabilityPlane) {",
    "  const capabilities = Array.isArray(capabilityPlane?.capabilities) ? capabilityPlane.capabilities : [];",
    "  const pendingPlans = Array.isArray(capabilityPlane?.pendingPlans) ? capabilityPlane.pendingPlans : [];",
    "  const items = capabilities",
    "    .slice(0, 4)",
    "    .map((entry) => '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Capability')) + ':</strong> '",
    "      + escapeHtml(normalizeText(entry?.state || 'declared'))",
    "      + (normalizeText(entry?.estimatedFootprint?.notes || entry?.category)",
    "        - ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(entry?.estimatedFootprint?.notes || entry?.category)) + ']</span>'",
    "        : ''));",
    "  for (const plan of pendingPlans.slice(0, 2)) {",
    "    items.push(",
    "      '<strong>Plan pending:</strong> '",
    "      + escapeHtml(normalizeText(plan?.title || plan?.actionId || 'capability.enable'))",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(plan?.status || 'waiting_approval')) + ']</span>',",
    "    );",
    "  }",
    "  return items.length > 0",
    "    - items",
    "    : ['No capability optional apareceu para is session ainda.'];",
    "}",
    "",
    "function buildSessionWorkspaceSelfmodItems(selfmodPlane) {",
    "  const plans = Array.isArray(selfmodPlane?.recentPlans) ? selfmodPlane.recentPlans : [];",
    "  if (plans.length === 0) {",
    "    return ['No preview or rollback de selfmod associado a is session agora.'];",
    "  }",
    "  return plans.slice(0, 4).map((plan) => '<strong>' + escapeHtml(normalizeText(plan?.title || plan?.actionId || 'Selfmod')) + ':</strong> '",
    "    + escapeHtml(normalizeText(plan?.status || 'draft'))",
    "    + (normalizeText(plan?.summary)",
    "      - ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(plan.summary)) + ']</span>'",
    "      : ''));",
    "}",
    "",
    "function buildSessionToolDiffPreview(payload) {",
    "  const patches = Array.isArray(payload?.diff?.patches) ? payload.diff.patches : [];",
    "  if (patches.length === 0) {",
    "    return ['This tool run did not include a textual patch in the current snapshot.'];",
    "  }",
    "  return patches.slice(0, 3).map((patch) => {",
    "    const path = normalizeText(patch?.path || 'file without path');",
    "    const diff = normalizeText(patch?.diff || '').slice(0, 1400);",
    "    const summary = normalizeText(patch?.summary);",
    "    return '<strong>' + escapeHtml(path) + '</strong>'",
    "      + (summary ? '<br><span class=\"muted-inline\">' + escapeHtml(summary) + '</span>' : '')",
    "      + '<pre class=\"inline-diff-preview\">' + escapeHtml(diff || '(diff vazio)') + '</pre>';",
    "  });",
    "}",
    "",
    "function readSessionWorkspaceSessionId() {",
    "  let urlSessionId = '';",
    "  try {",
    "    urlSessionId = normalizeText(new URL(window.location.href).searchParams.get('sessionId'));",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err; console.warn('[auto-fix] Empty catch block', err); }",
    "  return pickFirstText([",
    "    urlSessionId,",
    "    sessionWorkspaceData.session?.sessionId,",
    "    sessionWorkspaceData.state?.session?.sessionId,",
    "    sessionWorkspaceData.history?.session?.sessionId,",
    "  ]);",
    "}",
    "",
    "function buildOperationalButtonHtml(kind, action, label, targetId = '', extra = '') {",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action inline-choice-button\"'",
    "    + ' data-operational-kind=\"' + escapeHtml(kind) + '\"'",
    "    + ' data-operational-action=\"' + escapeHtml(action) + '\"'",
    "    + ' data-operational-target=\"' + escapeHtml(targetId) + '\"'",
    "    + ' data-operational-extra=\"' + escapeHtml(extra) + '\">'",
    "    + escapeHtml(label)",
    "    + '</button>';",
    "}",
    "",
    "function buildOperationalCopyButtonHtml(label, value) {",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action inline-choice-button\"'",
    "    + ' data-operational-copy=\"' + escapeHtml(value) + '\">'",
    "    + escapeHtml(label)",
    "    + '</button>';",
    "}",
    "",
    "function buildSessionReplayButtonHtml(label, action, prompt = '', summary = '') {",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action inline-choice-button\"'",
    "    + ' data-session-replay-action=\"' + escapeHtml(action) + '\"'",
    "    + ' data-session-replay-prompt=\"' + escapeHtml(prompt) + '\"'",
    "    + ' data-session-replay-summary=\"' + escapeHtml(summary) + '\">'",
    "    + escapeHtml(label)",
    "    + '</button>';",
    "}",
    "",
    "function buildOperationalInlineButtons(buttons) {",
    "  return Array.isArray(buttons) && buttons.length > 0",
    "    - '<div class=\"inline-action-row\">' + buttons.join('') + '</div>'",
    "    : '';",
    "}",
    "",
    "function buildOperationalSelectorHtml(kind, entries, selectedId) {",
    "  if (!Array.isArray(entries) || entries.length <= 1) {",
    "    return '';",
    "  }",
    "",
    "  const buttons = entries",
    "    .map((entry) => {",
    "      const id = normalizeText(entry?.id);",
    "      const label = normalizeText(entry?.label || entry?.id);",
    "      if (!id || !label) {",
    "        return '';",
    "      }",
    "      return '<button type=\"button\" class=\"action-button secondary compact-action inline-choice-button'",
    "        + (id === selectedId ? ' is-active' : '')",
    "        + '\" data-operational-kind=\"' + escapeHtml(kind) + '\"'",
    "        + ' data-operational-action=\"select\"'",
    "        + ' data-operational-target=\"' + escapeHtml(id) + '\">'",
    "        + escapeHtml(label)",
    "        + '</button>';",
    "    })",
    "    .filter(Boolean)",
    "    .slice(0, 6)",
    "    .join('');",
    "",
    "  return buttons ? '<div class=\"inline-choice-row\">' + buttons + '</div>' : '';",
    "}",
    "",
    "function renderSessionWorkspace(payload) {",
    "  sessionWorkspaceData = {",
    "    session: payload?.session || null,",
    "    state: payload?.state || null,",
    "    history: payload?.history || null,",
    "    toolRuns: payload?.toolRuns || null,",
    "  };",
    "",
    "  const sessionPayload = sessionWorkspaceData.session;",
    "  const statePayload = sessionWorkspaceData.state;",
    "  const historyPayload = sessionWorkspaceData.history;",
    "  const toolRunsPayload = sessionWorkspaceData.toolRuns;",
    "",
    "  const sessionId = pickFirstText([",
    "    sessionPayload?.sessionId,",
    "    statePayload?.session?.sessionId,",
    "    historyPayload?.session?.sessionId,",
    "  ]);",
    "  const chatId = pickFirstText([",
    "    sessionPayload?.chatId,",
    "    statePayload?.session?.chatId,",
    "    historyPayload?.session?.chatId,",
    "  ], 'without chat associado');",
    "  if (protectedShellUnlocked && sessionId && sessionId !== gatewayControlSocketSessionId) {",
    "    const liveToken = normalizeText(readStoredToken() || authInput?.value);",
    "    if (liveToken) {",
    "      ensureGatewayControlSocket(liveToken, sessionId);",
    "    }",
    "  }",
    "  const continuity = historyPayload?.session?.continuity || statePayload?.snapshot?.continuity || sessionPayload?.continuity || null;",
    "  const focusTask = continuity?.focusTask",
    "    || continuity?.activeTask",
    "    || continuity?.currentSurfaceTask",
    "    || continuity?.latestTelegramTask",
    "    || continuity?.latestWebTask",
    "    || continuity?.latestDiscordTask",
    "    || null;",
    "  const continuityReason = pickFirstText([",
    "    continuity?.suggestedAction?.reason,",
    "    statePayload?.session?.continuity?.suggestedAction?.reason,",
    "    historyPayload?.sessionPlane?.narrative?.operatorSummary,",
    "    statePayload?.sessionPlane?.narrative?.operatorSummary,",
    "  ]);",
    "  const replay = historyPayload?.session?.replay || null;",
    "  const handoff = historyPayload?.session?.handoff || null;",
    "  const replayHeadline = pickFirstText([",
    "    replay?.headline,",
    "    replay?.operatorSummary,",
    "    statePayload?.memoryPlane?.narrative?.operatorSummary,",
    "  ]);",
    "  const handoffHeadline = pickFirstText([",
    "    handoff?.headline,",
    "    handoff?.operatorSummary,",
    "    statePayload?.sessionPlane?.narrative?.operatorSummary,",
    "  ]);",
    "  const tools = Array.isArray(historyPayload?.gatewaySessionTools?.tools)",
    "    - historyPayload.gatewaySessionTools.tools",
    "    : [];",
    "  const counts = readSessionWorkspaceCounts(statePayload, historyPayload);",
    "  const permissions = Array.isArray(historyPayload?.session?.permissions) ? historyPayload.session.permissions : [];",
    "  const tasks = Array.isArray(historyPayload?.session?.tasks) ? historyPayload.session.tasks : [];",
    "  const approvalItems = buildSessionWorkspaceApprovalItems(permissions, tasks);",
    "  const toolRuns = readSessionWorkspaceToolRuns(statePayload, toolRunsPayload);",
    "  const artifactPlane = statePayload?.artifactPlane || historyPayload?.artifactPlane || null;",
    "  const capabilityPlane = statePayload?.capabilityPlane || historyPayload?.capabilityPlane || null;",
    "  const selfmodPlane = statePayload?.selfmodPlane || historyPayload?.selfmodPlane || null;",
    "  const resourcePlane = statePayload?.resourcePlane || historyPayload?.resourcePlane || null;",
    "  const companionPlane = statePayload?.companionPlane || historyPayload?.companionPlane || null;",
    "  const runtimeWarnings = Array.isArray(statePayload?.runtimeWarnings)",
    "    - statePayload.runtimeWarnings",
    "    : Array.isArray(historyPayload?.runtimeWarnings)",
    "      - historyPayload.runtimeWarnings",
    "      : [];",
    "  const actionRecommendations = Array.isArray(statePayload?.actionRecommendations)",
    "    - statePayload.actionRecommendations",
    "    : Array.isArray(historyPayload?.actionRecommendations)",
    "      - historyPayload.actionRecommendations",
    "      : [];",
    "  const sessionOptions = buildSessionWorkspaceSessionOptions(statePayload, sessionId);",
    "  if (!counts.toolRuns && toolRuns.length > 0) {",
    "    counts.toolRuns = toolRuns.length;",
    "  }",
    "  if (!counts.filesTouched && toolRuns.length > 0) {",
    "    counts.filesTouched = Array.from(new Set(",
    "      toolRuns.flatMap((run) => Array.isArray(run?.filesTouched) ? run.filesTouched : []),",
    "    )).length;",
    "  }",
    "  if (!counts.pendingPermissions && approvalItems.total > 0) {",
    "    counts.pendingPermissions = approvalItems.total;",
    "  }",
    "",
    "  if (!sessionId) {",
    "    setText(sessionWorkspaceState, 'Workspace unavailable');",
    "    setText(",
    "      sessionWorkspaceSummary,",
    "      sessionPayload?.error || 'Could not resolve the active session for this host right now.',",
    "    );",
    "    setText(sessionWorkspaceApprovalsState, 'Fila unavailable');",
    "    setText(",
    "      sessionWorkspaceApprovalsSummary,",
    "      historyPayload?.error || 'A queue pending de approvals aparece aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceReplayState, 'Replay unavailable');",
    "    setText(",
    "      sessionWorkspaceReplaySummary,",
    "      historyPayload?.error || 'O summary de replay aparece aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceToolsState, 'Tool plane unavailable');",
    "    setText(",
    "      sessionWorkspaceToolsSummary,",
    "      statePayload?.error || 'Tool cards, diffs e artifacts aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceDiffsState, 'Diff plane unavailable');",
    "    setText(",
    "      sessionWorkspaceDiffsSummary,",
    "      statePayload?.error || 'Diffs e artifacts canonicals aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceCapabilitiesState, 'Capabilities indisponiveis');",
    "    setText(",
    "      sessionWorkspaceCapabilitiesSummary,",
    "      statePayload?.error || 'Capabilities sob demanda aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceSelfmodState, 'Selfmod unavailable');",
    "    setText(",
    "      sessionWorkspaceSelfmodSummary,",
    "      statePayload?.error || 'Selfmod preview/apply/rollback aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceResourcesState, 'Resources indisponiveis');",
    "    setText(",
    "      sessionWorkspaceResourcesSummary,",
    "      statePayload?.error || 'Host pressure e top consumers aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceCompanionsState, 'Companions indisponiveis');",
    "    setText(",
    "      sessionWorkspaceCompanionsSummary,",
    "      statePayload?.error || 'WSL, Docker, ZavorthBridge e Codex aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(sessionWorkspaceHealthState, 'Health unavailable');",
    "    setText(",
    "      sessionWorkspaceHealthSummary,",
    "      statePayload?.error || 'Warnings e recomendoperational actions aparecem aqui when the active session is resolved.',",
    "    );",
    "    setText(",
    "      sessionWorkspaceStatus,",
    "      sessionPayload?.error || statePayload?.error || historyPayload?.error || 'Validate the token e try again para carregar a session ativa.',",
    "    );",
    "    renderList(sessionWorkspaceDetails, [",
    "      'The shell still could not resolve <strong>/api/web/session</strong> for this host.',",
    "      'when isso carregar, este card mostra session ativa, approvals, replay e session tools canonicalmente.',",
    "    ]);",
    "    renderList(sessionWorkspaceApprovals, ['A queue pending de approvals aparece aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceReplay, ['O summary de replay e handoff aparece aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceTools, ['Tool cards e diffs aparecem aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceDiffs, ['Diffs e artifacts aparecem aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceCapabilities, ['Capabilities e packs sob demanda aparecem aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceSelfmod, ['Previews e rollback de selfmod aparecem aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceResources, ['Host pressure, top consumers e actions de cleanup aparecem aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceCompanions, ['Companions aparecem aqui when the active session is resolved.']);",
    "    renderList(sessionWorkspaceHealth, ['Warnings canonicals e next actions aparecem aqui when the active session is resolved.']);",
    "    if (sessionWorkspaceAction instanceof HTMLButtonElement) {",
    "      sessionWorkspaceAction.hidden = false;",
    "      sessionWorkspaceAction.textContent = 'Atualizar workspace';",
    "    }",
    "    return;",
    "  }",
    "",
    "  setText(sessionWorkspaceState, 'Session active ready');",
    "  setText(",
    "    sessionWorkspaceSummary,",
    "    'chat ' + chatId + ' | ' + counts.taskCount + ' task(s) | ' + counts.pendingPermissions + ' approval(s) em aberto.',",
    "  );",
    "  setText(sessionWorkspaceApprovalsState, approvalItems.total > 0 ? String(approvalItems.total) + ' pending(s)' : 'without pending items');",
    "  setText(",
    "    sessionWorkspaceApprovalsSummary,",
    "    approvalItems.total > 0",
    "      - String(approvalItems.permissions) + ' permission(s) and ' + String(approvalItems.tasks) + ' task gate(s) requesting decision.'",
    "      : 'No approval pending na session ativa agora.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceReplayState,",
    "    replayHeadline ? 'Replay resolvido' : handoffHeadline ? 'Handoff ready' : 'Replay leve',",
    "  );",
    "  setText(",
    "    sessionWorkspaceReplaySummary,",
    "    replayHeadline || handoffHeadline || continuityReason || 'Use this block to review replay, continuity, and resume signals.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceToolsState,",
    "    counts.toolRuns > 0 ? String(counts.toolRuns) + ' tool run(s)' : 'without tool runs',",
    "  );",
    "  setText(",
    "    sessionWorkspaceToolsSummary,",
    "    counts.toolRuns > 0",
    "      - String(counts.filesTouched || 0) + ' file(s) tocado(s) | diffs e artifacts sob demanda.'",
    "      : 'when a tool runs, edits a file, or publishes an artifact, the card appears here.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceDiffsState,",
    "    counts.filesTouched > 0 ? String(counts.filesTouched) + ' file(s)' : 'No diffs',",
    "  );",
    "  setText(",
    "    sessionWorkspaceDiffsSummary,",
    "    counts.filesTouched > 0",
    "      ? String(Array.isArray(artifactPlane?.artifacts) ? artifactPlane.artifacts.length : 0) + ' artifact(s) canonicals | diff viewer sob demanda.'",
    "      : 'when houver patch or artifact importante, ele aparece aqui separado do summary das tools.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceCapabilitiesState,",
    "    capabilityPlane?.summary",
    "      - String(capabilityPlane.summary.active || 0) + ' ativa(s)'",
    "      : 'No reading',",
    "  );",
    "  setText(",
    "    sessionWorkspaceCapabilitiesSummary,",
    "    capabilityPlane?.summary",
    "      - String(capabilityPlane.summary.dormant || 0) + ' dormant(s) | '",
    "        + String(capabilityPlane.summary.requiringApproval || 0) + ' pedem approval.'",
    "      : 'On-demand capabilities appear here when the gateway publishes this plan.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceSelfmodState,",
    "    Array.isArray(selfmodPlane?.recentPlans) && selfmodPlane.recentPlans.length > 0",
    "      - String(selfmodPlane.recentPlans.length) + ' plan(s)'",
    "      : 'without plans',",
].join('\n');
