export const runtimeShellScriptPart3Seg2: string = [
    "    setCardEmphasis(hubControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(hubControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      hubControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado do Hub + MCP ainda nao respondeu neste runtime.'",
    "        : 'O consolidado do Hub + MCP aparece aqui assim que o shell protegido for liberado.',",
    "    );",
    "    setText(hubControlPlaneIntegrationsState, 'Sem leitura');",
    "    setText(hubControlPlaneIntegrationsSummary, 'Conectores, plugins trusted e itens configuraveis aparecem aqui.');",
    "    setText(hubControlPlanePlatformState, 'Sem leitura');",
    "    setText(hubControlPlanePlatformSummary, 'Registry remoto, colecoes, recipes e skills prontas aparecem aqui.');",
    "    setText(hubControlPlaneMcpState, 'Sem leitura');",
    "    setText(hubControlPlaneMcpSummary, 'Servidores MCP, tools, resources e doctor ficam consolidados aqui.');",
    "    setText(hubControlPlaneStatus, errorMessage || 'Valide o token para revisar surfaces, acoes e itens em destaque do Hub + MCP.');",
    "    renderList(hubControlPlaneSurfaces, [errorMessage || 'Valide o token para ver o plano consolidado de surfaces.']);",
    "    renderList(hubControlPlaneActions, [errorMessage || 'Valide o token para revisar sync, doctor e proximos passos deste ecossistema.']);",
    "    renderList(hubControlPlaneFeatured, [errorMessage || 'Valide o token para revisar conectores, plugins, skills e MCPs destacados.']);",
    "    if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      hubControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    if (hubControlPlaneSyncAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneSyncAction.hidden = !protectedShellUnlocked;",
    "      hubControlPlaneSyncAction.disabled = false;",
    "    }",
    "    if (hubControlPlaneMcpDoctorAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneMcpDoctorAction.hidden = !protectedShellUnlocked;",
    "      hubControlPlaneMcpDoctorAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const surfaces = Array.isArray(snapshot.surfaces) ? snapshot.surfaces : [];",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const featured = Array.isArray(snapshot.featured) ? snapshot.featured : [];",
    "  const highlights = Array.isArray(snapshot.highlights) ? snapshot.highlights : [];",
    "  const sync = snapshot.sync || {};",
    "",
    "  setCardEmphasis(hubControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(hubControlPlaneState, posture);",
    "  setText(hubControlPlaneSummary, normalizeText(snapshot?.narrative?.operatorSummary) || 'Hub consolidado atualizado.');",
    "  setText(",
    "    hubControlPlaneIntegrationsState,",
    "    String(summary.integrations || 0) + ' conectore(s) | ' + String(summary.plugins || 0) + ' plugin(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneIntegrationsSummary,",
    "    String(summary.providersReady || 0) + ' provider(s) prontos | ' + String(summary.pluginsTrusted || 0) + ' plugin(s) trusted',",
    "  );",
    "  setText(",
    "    hubControlPlanePlatformState,",
    "    String(summary.platformEntries || 0) + ' entrada(s) | sync ' + normalizeText(sync.status || 'disabled'),",
    "  );",
    "  setText(",
    "    hubControlPlanePlatformSummary,",
    "    String(summary.skillsVisible || 0) + ' skill(s) | ' + String(summary.skillRecipesReady || 0) + ' recipe(s) pronta(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneMcpState,",
    "    String(summary.mcpConnected || 0) + '/' + String(summary.mcpServers || 0) + ' server(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneMcpSummary,",
    "    String(summary.mcpTools || 0) + ' tool(s) | ' + String(summary.mcpResources || 0) + ' resource(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction)",
    "      || normalizeText(sync.summary)",
    "      || 'Hub consolidado atualizado.',",
    "  );",
    "  renderList(",
    "    hubControlPlaneSurfaces,",
    "    surfaces.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Surface')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'healthy'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.primary || 'Sem resumo.'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.secondary || 'Sem detalhe.')),",
    "    ).concat(highlights.slice(0, 2).map((entry) => '<strong>Highlight:</strong> ' + escapeHtml(normalizeText(entry))))",
    "      .concat(surfaces.length === 0 ? ['Sem surfaces consolidadas neste runtime.'] : []),",
    "  );",
    "  renderList(",
    "    hubControlPlaneActions,",
    "    actions.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.rationale || 'Sem racional.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(actions.length === 0 ? ['Sem acoes sugeridas neste recorte.'] : []),",
    "  );",
    "  renderList(",
    "    hubControlPlaneFeatured,",
    "    featured.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Item')) + '</strong> [' + escapeHtml(normalizeText(entry?.surface || 'surface')) + ']: '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(featured.length === 0 ? ['Sem destaques suficientes neste recorte.'] : []),",
    "  );",
    "  if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneRefreshAction.hidden = false;",
    "    hubControlPlaneRefreshAction.disabled = false;",
    "  }",
    "  if (hubControlPlaneSyncAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneSyncAction.hidden = false;",
    "    hubControlPlaneSyncAction.disabled = false;",
    "  }",
    "  if (hubControlPlaneMcpDoctorAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneMcpDoctorAction.hidden = false;",
    "    hubControlPlaneMcpDoctorAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderQaControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    qaControlPlaneData = payload;",
    "  }",
    "  const snapshot = qaControlPlaneData?.qa || qaControlPlaneData?.snapshot || qaControlPlaneData || null;",
    "  const errorMessage = normalizeText(qaControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(qaControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(qaControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      qaControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado de QA ainda nao respondeu neste runtime.'",
    "        : 'O consolidado de budgets e release gates aparece aqui assim que o shell protegido for liberado.',",
    "    );",
    "    setText(qaControlPlaneBenchmarksState, 'Sem leitura');",
    "    setText(qaControlPlaneBenchmarksSummary, 'Boot, runtime flow e sidecars aparecem aqui com budget e idade do relatorio.');",
    "    setText(qaControlPlaneRegressionsState, 'Sem leitura');",
    "    setText(qaControlPlaneRegressionsSummary, 'Smokes e regressions aparecem aqui com falhas, ausencia e stale.');",
    "    setText(qaControlPlaneReleaseState, 'Sem leitura');",
    "    setText(qaControlPlaneReleaseSummary, 'Alpha e beta aparecem aqui com gate pronto ou pendente.');",
    "    setText(qaControlPlaneStatus, errorMessage || 'Valide o token para revisar budgets, relatorios e gates de release deste host.');",
    "    renderList(qaControlPlaneBenchmarks, [errorMessage || 'Valide o token para revisar benchmarks e budgets versionados.']);",
    "    renderList(qaControlPlaneSmokes, [errorMessage || 'Valide o token para revisar smoke suite e regressions criticas.']);",
    "    renderList(qaControlPlaneReleaseGates, [errorMessage || 'Valide o token para revisar alpha e beta sem ler logs manualmente.']);",
    "    if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      qaControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      qaControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const benchmarks = Array.isArray(snapshot.benchmarks) ? snapshot.benchmarks : [];",
    "  const regressions = Array.isArray(snapshot.regressions) ? snapshot.regressions : [];",
    "  const smokes = Array.isArray(snapshot.smokes) ? snapshot.smokes : [];",
    "  const releaseGates = Array.isArray(snapshot.releaseGates) ? snapshot.releaseGates : [];",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "",
    "  setCardEmphasis(qaControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(qaControlPlaneState, posture);",
    "  setText(",
    "    qaControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'QA control plane atualizado.',",
    "  );",
    "  setText(",
    "    qaControlPlaneBenchmarksState,",
    "    String(benchmarks.length) + ' benchmark(s)',",
    "  );",
    "  setText(",
    "    qaControlPlaneBenchmarksSummary,",
    "    String(benchmarks.filter((entry) => normalizeText(entry?.status) === 'healthy').length)",
    "      + ' healthy | '",
    "      + String(benchmarks.filter((entry) => normalizeText(entry?.status) === 'attention').length)",
    "      + ' attention | '",
    "      + String(benchmarks.filter((entry) => ['critical', 'missing'].includes(normalizeText(entry?.status))).length)",
    "      + ' fora do gate',",
    "  );",
    "  setText(",
    "    qaControlPlaneRegressionsState,",
    "    String(smokes.length) + ' smoke(s) | ' + String(regressions.length) + ' regressao(oes)',",
    "  );",
    "  setText(",
    "    qaControlPlaneRegressionsSummary,",
    "    String(summary.stale || 0) + ' stale | '",
    "      + String(summary.missing || 0) + ' missing | '",
    "      + String(summary.critical || 0) + ' critical',",
    "  );",
    "  const releasePrimary = releaseGates.find((entry) => normalizeText(entry?.profile) === normalizeText(snapshot.profile)) || releaseGates[0] || null;",
    "  setText(",
    "    qaControlPlaneReleaseState,",
    "    releasePrimary",
    "      ? normalizeText(releasePrimary.profile || 'alpha')",
    "      : 'Sem leitura',",
    "  );",
    "  setText(",
    "    qaControlPlaneReleaseSummary,",
    "    releasePrimary",
    "      ? normalizeText(releasePrimary.summary)",
    "      : 'Sem gate principal neste recorte.',",
    "  );",
    "  setText(",
    "    qaControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction)",
    "      || 'QA control plane atualizado.',",
    "  );",
    "  renderList(",
    "    qaControlPlaneBenchmarks,",
    "    benchmarks.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Benchmark')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.status || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.actual || 'Sem leitura.'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.budget || 'Sem budget.')),",
    "    ).concat(",
    "      benchmarks.length === 0 ? ['Sem benchmarks suficientes neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    qaControlPlaneSmokes,",
    "    smokes.slice(0, 4).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Smoke')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.')),",
    "    ).concat(",
    "      regressions.slice(0, 4).map((entry) =>",
    "        '<strong>' + escapeHtml(normalizeText(entry?.label || 'Regression')) + '</strong>: '",
    "        + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.')),",
    "      ),",
    "    ).concat(",
    "      actions.slice(0, 2).map((entry) =>",
    "        '<strong>Acao:</strong> '",
    "        + escapeHtml(normalizeText(entry?.label || 'Acao'))",
    "        + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "      ),",
    "    ).concat(",
    "      smokes.length === 0 && regressions.length === 0 ? ['Sem smokes ou regressions suficientes neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    qaControlPlaneReleaseGates,",
    "    releaseGates.slice(0, 4).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.profile || 'release')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      releaseGates.length === 0 ? ['Sem release profiles suficientes neste recorte.'] : [],",
    "    ),",
    "  );",
    "  if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    qaControlPlaneRefreshAction.hidden = false;",
    "    qaControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderGovernanceControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    governanceControlPlaneData = payload;",
    "  }",
    "  const snapshot = governanceControlPlaneData?.governance || governanceControlPlaneData?.snapshot || governanceControlPlaneData || null;",
    "  const errorMessage = normalizeText(governanceControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(governanceControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(governanceControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      governanceControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado de governance ainda nao respondeu neste runtime.'",
    "        : 'A postura consolidada da Governance aparece aqui assim que o shell protegido for liberado.',",
    "    );",
    "    setText(governanceControlPlaneTenantsState, 'Sem leitura');",
    "    setText(governanceControlPlaneTenantsSummary, 'Tenants compartilhados, pessoais, onboarding e public servers aparecem aqui.');",
    "    setText(governanceControlPlaneTrustState, 'Sem leitura');",
    "    setText(governanceControlPlaneTrustSummary, 'Approvals, MCP, plugins trusted e capabilities sensiveis aparecem neste resumo.');",
    "    setText(governanceControlPlanePolicyState, 'Sem leitura');",
    "    setText(governanceControlPlanePolicySummary, 'Channels, nodes, platform, transports e teams ficam conectados ao mesmo contrato.');",
    "    setText(governanceControlPlaneStatus, errorMessage || 'Valide o token para revisar decisions, allowlists e policy por superficie.');",
    "    renderList(governanceControlPlaneDecisions, [errorMessage || 'Valide o token para ver decisoes allow/ask/deny/defer/audit.']);",
    "    renderList(governanceControlPlaneSurfaces, [errorMessage || 'Valide o token para ver tenants, trust, channels, nodes, plugins, platform, transports e teams.']);",
    "    renderList(governanceControlPlaneActions, [errorMessage || 'Valide o token para revisar proximos passos de governanca.']);",
    "    if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      governanceControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      governanceControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const surfaces = Array.isArray(snapshot.surfaces) ? snapshot.surfaces : [];",
    "  const decisions = Array.isArray(snapshot.decisions) ? snapshot.decisions : [];",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "",
    "  setCardEmphasis(governanceControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(governanceControlPlaneState, posture);",
    "  setText(",
    "    governanceControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Governance control plane atualizado.',",
    "  );",
    "  setText(",
    "    governanceControlPlaneTenantsState,",
    "    String(summary.sharedTenants || 0) + ' shared | ' + String(summary.personalTenants || 0) + ' personal',",
    "  );",
    "  setText(",
    "    governanceControlPlaneTenantsSummary,",
    "    String(summary.pendingOnboarding || 0) + ' onboarding pendente | '",
    "      + String(summary.restrictedShared || 0) + ' restrito(s) | '",
    "      + String(summary.publicServers || 0) + ' public server(s)',",
    "  );",
    "  setText(",
    "    governanceControlPlaneTrustState,",
    "    'MCP ' + normalizeText(summary.mcpProfile || 'safe'),",
    "  );",
    "  setText(",
    "    governanceControlPlaneTrustSummary,",
    "    String(summary.pendingApprovals || 0) + ' approval(s) | '",
    "      + String(summary.highRiskCapabilities || 0) + ' high-risk | '",
    "      + String(summary.trustedPlugins || 0) + '/' + String(summary.installedPlugins || 0) + ' plugin(s) trusted',",
    "  );",
    "  setText(",
    "    governanceControlPlanePolicyState,",
    "    String(summary.readyChannels || 0) + '/' + String(summary.totalChannels || 0) + ' canais | '",
    "      + String(summary.pairedNodes || 0) + ' nodes',",
    "  );",
    "  setText(",
    "    governanceControlPlanePolicySummary,",
    "    String(summary.remoteAttention || 0) + ' transporte(s) com atencao real | '",
    "      + String(summary.decisions || 0) + ' decision(s)',",
    "  );",
    "  setText(",
    "    governanceControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Governance control plane atualizado.',",
    "  );",
    "  renderList(",
    "    governanceControlPlaneDecisions,",
    "    decisions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Decision')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.decision || 'audit'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.severity || 'info'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.rationale || 'Sem racional.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      decisions.length === 0 ? ['Sem trust decisions destacadas no recorte atual.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    governanceControlPlaneSurfaces,",
    "    surfaces.slice(0, 9).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Surface')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'healthy'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.allowlistState || 'Sem allowlist state.'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.nextAction || 'Sem proximo passo.')),",
    "    ).concat(",
    "      surfaces.length === 0 ? ['Sem superficies de policy suficientes neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    governanceControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['Sem acoes sugeridas; mantenha revisao periodica de tenants e allowlists.'] : [],",
    "    ),",
    "  );",
    "  if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    governanceControlPlaneRefreshAction.hidden = false;",
    "    governanceControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderReplayLearningControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    replayLearningControlPlaneData = payload;",
    "  }",
    "  const snapshot = replayLearningControlPlaneData?.replayLearning || replayLearningControlPlaneData?.snapshot || replayLearningControlPlaneData || null;",
    "  const errorMessage = normalizeText(replayLearningControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(replayLearningControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(replayLearningControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      replayLearningControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado de replay/learning ainda nao respondeu neste runtime.'",
    "        : 'Timeline, compare runs e restore context aparecem aqui assim que o shell protegido for liberado.',",
    "    );",
    "    setText(replayLearningControlPlaneArtifactsState, 'Sem leitura');",
    "    setText(replayLearningControlPlaneArtifactsSummary, 'Artifacts reutilizaveis e resume prompts ficam visiveis neste recorte.');",
    "    setText(replayLearningControlPlaneLearningState, 'Sem leitura');",
    "    setText(replayLearningControlPlaneLearningSummary, 'Candidatos pendentes, promovidos e de alta confianca aparecem com proximo passo claro.');",
    "    setText(replayLearningControlPlaneMemoryState, 'Sem leitura');",
    "    setText(replayLearningControlPlaneMemorySummary, 'Pressao da memoria, procedimentos e pontos de restore ficam ligados ao mesmo plano.');",
    "    setText(replayLearningControlPlaneStatus, errorMessage || 'Valide o token para revisar timeline, artifacts reutilizaveis, learning promotions e memory pressure.');",
    "    renderList(replayLearningControlPlaneActions, [errorMessage || 'Valide o token para revisar compare, resume e learning promotions.']);",
    "    renderList(replayLearningControlPlaneArtifacts, [errorMessage || 'Valide o token para ver artifacts com prompt de retomada.']);",
    "    renderList(replayLearningControlPlaneTimeline, [errorMessage || 'Valide o token para comparar replay, workflows e artifacts recentes.']);",
    "    if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      replayLearningControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      replayLearningControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const artifacts = Array.isArray(snapshot.artifacts) ? snapshot.artifacts : [];",
    "  const timeline = Array.isArray(snapshot.timeline) ? snapshot.timeline : [];",
    "",
    "  setCardEmphasis(replayLearningControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(replayLearningControlPlaneState, posture);",
    "  setText(",
    "    replayLearningControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Replay/learning control plane atualizado.',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneArtifactsState,",
    "    String(summary.reusableArtifacts || 0) + '/' + String(summary.recentArtifacts || 0) + ' reutilizavel(is)',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneArtifactsSummary,",
    "    String(summary.resumeReady ? 'Resume pronto' : 'Sem resume forte')",
    "      + ' | restore '",
    "      + String(summary.restoreReady ? 'pronto' : 'pendente'),",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneLearningState,",
    "    String(summary.pendingLearning || 0) + ' pendente(s)',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneLearningSummary,",
    "    String(summary.learningCandidates || 0) + ' candidato(s) | '",
    "      + String(summary.promotedLearning || 0) + ' promovido(s) | '",
    "      + String(summary.highConfidenceLearning || 0) + ' high-confidence',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneMemoryState,",
    "    normalizeText(summary.memoryPressure || 'ok'),",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneMemorySummary,",
    "    String(summary.memoryEntries || 0) + ' entrada(s) | '",
    "      + String(summary.proceduralEntries || 0) + ' procedimento(s)',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Replay/learning control plane atualizado.',",
    "  );",
    "  renderList(",
    "    replayLearningControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : '')",
    "      + (normalizeText(entry?.prompt) ? ' | ' + escapeHtml(normalizeText(entry.prompt)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['Sem acoes sugeridas; mantenha revisao periodica de replay, artifacts e learning.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    replayLearningControlPlaneArtifacts,",
    "    artifacts.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Artifact')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.kind || 'file'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (entry?.reusable ? ' | reutilizavel' : ' | registrado'),",
    "    ).concat(",
    "      artifacts.length === 0 ? ['Sem artifacts reutilizaveis suficientes neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    replayLearningControlPlaneTimeline,",
    "    timeline.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Evento')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.kind || 'timeline'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.status || 'sem status'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.')),",
    "    ).concat(",
    "      timeline.length === 0 ? ['Sem timeline suficiente para compare runs neste recorte.'] : [],",
    "    ),",
    "  );",
    "  if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    replayLearningControlPlaneRefreshAction.hidden = false;",
    "    replayLearningControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderEcosystemControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    ecosystemControlPlaneData = payload;",
    "  }",
    "  const snapshot = ecosystemControlPlaneData?.ecosystem || ecosystemControlPlaneData?.snapshot || ecosystemControlPlaneData || null;",
    "  const errorMessage = normalizeText(ecosystemControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(ecosystemControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(ecosystemControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      ecosystemControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado do ecossistema ainda nao respondeu neste runtime.'",
    "        : 'SDKs, guides e publish aparecem aqui assim que o shell protegido for liberado.',",
    "    );",
    "    setText(ecosystemControlPlaneSdkState, 'Sem leitura');",
    "    setText(ecosystemControlPlaneSdkSummary, 'O estado dos SDKs TypeScript e Python fica visivel aqui.');",
    "    setText(ecosystemControlPlaneRegistryState, 'Sem leitura');",
    "    setText(ecosystemControlPlaneRegistrySummary, 'Registry remoto, colecoes, recipes e itens em review ficam consolidados aqui.');",
    "    setText(ecosystemControlPlanePublishState, 'Sem leitura');",
    "    setText(ecosystemControlPlanePublishSummary, 'Bundles preparados, publicados e warnings de provenance aparecem aqui.');",
    "    setText(ecosystemControlPlaneStatus, errorMessage || 'Valide o token para revisar SDKs, guides, recipes e artefatos de publish do ecossistema.');",
    "    renderList(ecosystemControlPlaneActions, [errorMessage || 'Valide o token para revisar SDKs, guides e proximos passos do ecossistema.']);",
    "    renderList(ecosystemControlPlaneGuides, [errorMessage || 'Valide o token para ver client, node, plugin e recipe num plano unico.']);",
    "    renderList(ecosystemControlPlanePublish, [errorMessage || 'Valide o token para revisar bundles, signatures e readiness do publish.']);",
    "    if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      ecosystemControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      ecosystemControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const guides = Array.isArray(snapshot.guides) ? snapshot.guides : [];",
    "  const publishArtifacts = Array.isArray(snapshot.publishArtifacts) ? snapshot.publishArtifacts : [];",
    "",
    "  setCardEmphasis(ecosystemControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(ecosystemControlPlaneState, posture);",
    "  setText(",
    "    ecosystemControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Ecossistema atualizado.',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneSdkState,",
    "    String(summary.sdkFilesReady || 0) + '/' + String(summary.sdkFilesExpected || 0) + ' arquivo(s)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneSdkSummary,",
    "    'TypeScript ' + (summary.sdkTypescriptReady ? 'pronto' : 'pendente')",
    "      + ' | Python ' + (summary.sdkPythonReady ? 'pronto' : 'pendente'),",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneRegistryState,",
    "    String(summary.registryEntries || 0) + ' item(ns) | ' + String(summary.collections || 0) + ' colecao(oes)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneRegistrySummary,",
    "    String(summary.recipes || 0) + ' recipe(s) | review ' + String(summary.reviewPending || 0),",
    "  );",
    "  setText(",
    "    ecosystemControlPlanePublishState,",
    "    String(summary.publishArtifacts || 0) + ' artefato(s)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlanePublishSummary,",
    "    String(summary.publishedArtifacts || 0) + ' publicado(s) | ' + String(summary.preparedArtifacts || 0) + ' preparado(s)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Ecossistema atualizado.',",
    "  );",
    "  renderList(",
    "    ecosystemControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['Sem acoes sugeridas; mantenha SDKs, guides e publish sob revisao periodica.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    ecosystemControlPlaneGuides,",
    "    guides.map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Guia')) + '</strong>: '",
    "      + escapeHtml(entry?.exists ? 'publicado' : 'pendente')",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.path) ? ' | ' + escapeHtml(normalizeText(entry.path)) : ''),",
    "    ).concat(",
    "      guides.length === 0 ? ['Nenhum guia mapeado neste runtime.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    ecosystemControlPlanePublish,",
    "    publishArtifacts.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.releaseId || 'Bundle')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.uploadStatus || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(String(entry?.fileCount || 0) + ' arquivo(s)')",
].join('\n');
