export const runtimeShellScriptPart7Seg1: string = [
    "    return;",
    "  }",
    "",
    "  const buttons = [journeyTrustActionButton, journeyRefreshActionButton].filter((target) => target instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    setJourneyActionStatus('Atualizando manifesto, journey e remoto deste host...');",
    "    await refreshProtectedShellState(token);",
    "    setJourneyActionStatus('Host atualizado com sucesso.');",
    "  } catch (error) {",
    "    setJourneyActionStatus(error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installRemoteActionControls() {",
    "  if (remoteRecommendedActionButton instanceof HTMLButtonElement) {",
    "    remoteRecommendedActionButton.addEventListener('click', () => {",
    "      void runOfficialRemoteAction(",
    "        normalizeText(remoteRecommendedActionButton.dataset.action),",
    "        normalizeText(remoteRecommendedActionButton.dataset.provider),",
    "      );",
    "    });",
    "  }",
    "",
    "  if (remoteVerifyActionButton instanceof HTMLButtonElement) {",
    "    remoteVerifyActionButton.addEventListener('click', () => {",
    "      void runOfficialRemoteAction(",
    "        normalizeText(remoteVerifyActionButton.dataset.action || 'verify'),",
    "        normalizeText(remoteVerifyActionButton.dataset.provider),",
    "      );",
    "    });",
    "  }",
    "}",
    "",
    "function installJourneyActionControls() {",
    "  if (journeyTrustActionButton instanceof HTMLButtonElement) {",
    "    journeyTrustActionButton.addEventListener('click', () => {",
    "      void runJourneyTrustAction();",
    "    });",
    "  }",
    "",
    "  if (journeyRefreshActionButton instanceof HTMLButtonElement) {",
    "    journeyRefreshActionButton.addEventListener('click', () => {",
    "      void refreshJourneyState();",
    "    });",
    "  }",
    "}",
    "",
    "async function runPriorityPrimaryAction() {",
    "  const mode = normalizeText(priorityPrimaryAction?.dataset.mode);",
    "  const action = normalizeText(priorityPrimaryAction?.dataset.action);",
    "  const provider = normalizeText(priorityPrimaryAction?.dataset.provider);",
    "  if (!mode || !action || !(priorityPrimaryAction instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "",
    "  priorityPrimaryAction.disabled = true;",
    "  try {",
    "    if (mode === 'journey') {",
    "      setText(",
    "        priorityReason,",
    "        action === 'trust'",
    "          ? 'Autorizando este host e atualizando o shell oficial...'",
    "          : 'Executando a jornada local recomendada para este host...',",
    "      );",
    "      if (journeyTrustActionButton instanceof HTMLButtonElement) {",
    "        journeyTrustActionButton.dataset.mode = action === 'trust' ? 'trust' : 'journey';",
    "        journeyTrustActionButton.dataset.action = action === 'trust' ? '' : action;",
    "      }",
    "      await runJourneyTrustAction();",
    "      return;",
    "    }",
    "",
    "    if (mode === 'remote') {",
    "      setText(priorityReason, 'Executando o passo remoto recomendado para este host...');",
    "      if (remoteRecommendedActionButton instanceof HTMLButtonElement) {",
    "        remoteRecommendedActionButton.dataset.action = action;",
    "        remoteRecommendedActionButton.dataset.provider = provider;",
    "      }",
    "      await runOfficialRemoteAction(action, provider);",
    "    }",
    "  } finally {",
    "    priorityPrimaryAction.disabled = false;",
    "  }",
    "}",
    "",
    "function buildPriorityReason(plan, manifest, report) {",
    "  switch (plan?.primaryAction) {",
    "    case 'go':",
    "      return 'Este host ainda precisa passar pelo atalho oficial para instalar, subir o runtime e abrir a melhor superficie pronta.';",
    "    case 'trust':",
    "      return 'O runtime local ja esta no ar, mas o host ainda precisa de trust antes de acoes mutaveis, escrita local ou entregas persistidas.';",
    "    case 'remote':",
    "      return normalizeText(report?.recommendedPathReason)",
    "        || 'O runtime local esta pronto, mas o acesso remoto oficial ainda pede rollout guiado.';",
    "    case 'open-local':",
    "      return 'O runtime local e o shell oficial ja estao prontos. Abra o shell agora e deixe o remoto como rota secundaria.';",
    "    default:",
    "      return normalizeText(manifest?.summary) || 'Use a recomendacao oficial deste host para evitar rotas paralelas.';",
    "  }",
    "}",
    "",
    "function formatReadinessStep(step) {",
    "  const title = normalizeText(step?.title || step?.id || 'passo');",
    "  const description = normalizeText(step?.description);",
    "  return '<strong>' + title + ':</strong> ' + (description || 'Sem descricao.');",
    "}",
    "",
    "function formatJourneyPhase(phase) {",
    "  const title = normalizeText(phase?.title || phase?.id || 'etapa');",
    "  const command = normalizeText(phase?.command);",
    "  const summary = normalizeText(phase?.summary);",
    "  return '<strong>' + title + ':</strong> ' + (command || summary || 'Sem resumo.');",
    "}",
    "",
    "function renderPriorityActions(manifest, report) {",
    "  const plan = manifest?.recommendedPlan;",
    "  const primaryAction = normalizeText(plan?.primaryAction);",
    "  const localAppUrl = normalizeText(manifest?.local?.appUrl);",
    "  const remoteAppUrl = normalizeText(plan?.remoteRecommendation?.appUrl || report?.actions?.open?.appUrl || report?.actions?.open?.url);",
    "  const remoteCommand = normalizeText(plan?.remoteRecommendation?.command || report?.actions?.go?.command || report?.actions?.apply?.command);",
    "  const launcherCommand = normalizeText(plan?.launcherRecommendation?.command);",
    "  const recommendedRemoteAction = normalizeText(report?.actions?.recommendedAction);",
    "  const recommendedRemoteProvider = normalizeText(report?.actions?.recommendedProvider);",
    "  const recommendedRemoteConfig = recommendedRemoteAction ? report?.actions?.[recommendedRemoteAction] : null;",
    "",
    "  resetPriorityActions();",
    "",
    "  if (primaryAction === 'go') {",
    "    showPriorityRunAction(priorityPrimaryAction, 'Executar atalho oficial', 'journey', 'go', '');",
    "  } else if (primaryAction === 'trust') {",
    "    showPriorityRunAction(priorityPrimaryAction, 'Autorizar este host', 'journey', 'trust', '');",
    "  } else if (primaryAction === 'remote' && recommendedRemoteAction && recommendedRemoteConfig) {",
    "    showPriorityRunAction(",
    "      priorityPrimaryAction,",
    "      normalizeText(recommendedRemoteConfig.label) || normalizeText(plan?.primaryLabel) || 'Executar passo remoto',",
    "      'remote',",
    "      recommendedRemoteAction,",
    "      recommendedRemoteProvider,",
    "    );",
    "  } else if (normalizeText(plan?.primaryCommand)) {",
    "    showCopyAction(",
    "      priorityPrimaryCopy,",
    "      normalizeText(plan?.primaryLabel) || 'Copiar comando principal',",
    "      normalizeText(plan.primaryCommand),",
    "    );",
    "  } else if (normalizeText(plan?.openTarget)) {",
    "    showOpenAction(",
    "      priorityPrimaryOpen,",
    "      normalizeText(plan?.primaryLabel) || 'Abrir agora',",
    "      normalizeText(plan.openTarget),",
    "    );",
    "  }",
    "",
    "  if (primaryAction === 'go' || primaryAction === 'trust') {",
    "    if (!showOpenAction(prioritySecondaryOpen, 'Abrir shell local', localAppUrl) && launcherCommand) {",
    "      showCopyAction(prioritySecondaryCopy, 'Instalar launcher oficial', launcherCommand);",
    "    }",
    "    return;",
    "  }",
    "",
    "  if (primaryAction === 'remote') {",
    "    if (!showOpenAction(prioritySecondaryOpen, 'Abrir shell local', localAppUrl) && launcherCommand) {",
    "      showCopyAction(prioritySecondaryCopy, 'Instalar launcher oficial', launcherCommand);",
    "    }",
    "    return;",
    "  }",
    "",
    "  if (remoteAppUrl) {",
    "    if (showOpenAction(prioritySecondaryOpen, 'Abrir shell remoto', remoteAppUrl)) {",
    "      return;",
    "    }",
    "  }",
    "",
    "  if (remoteCommand) {",
    "    if (showCopyAction(prioritySecondaryCopy, 'Copiar caminho remoto', remoteCommand)) {",
    "      return;",
    "    }",
    "  }",
    "",
    "  if (launcherCommand) {",
    "    showCopyAction(prioritySecondaryCopy, 'Instalar launcher oficial', launcherCommand);",
    "  }",
    "}",
    "",
    "function renderProfileRoute(summaryTarget, actionTarget, summary, command, fallbackCommand) {",
    "  setText(summaryTarget, summary);",
    "  if (!(actionTarget instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  actionTarget.hidden = false;",
    "  actionTarget.setAttribute('data-copy', command || fallbackCommand || '');",
    "}",
    "",
    "function renderRouteCard(titleTarget, summaryTarget, stepsTarget, actionTarget, config) {",
    "  setText(titleTarget, config.title);",
    "  setText(summaryTarget, config.summary);",
    "  renderList(stepsTarget, config.steps || []);",
    "  if (actionTarget instanceof HTMLButtonElement) {",
    "    actionTarget.hidden = false;",
    "    actionTarget.textContent = config.actionLabel;",
    "    actionTarget.setAttribute('data-copy', config.actionCommand || '');",
    "  }",
    "}",
    "",
    "function renderProfileRecommendations(manifest, report) {",
    "  const commands = manifest?.commands || {};",
    "  const localReady = manifest?.local?.ready === true;",
    "  const hostAuthorized = manifest?.auth?.authorizedHost;",
    "  const remoteReady = manifest?.officialRemote?.ready === true;",
    "",
    "  const devSummary = localReady",
    "    ? 'Runtime local pronto. Abra o shell oficial e use o repo para iterar no contrato.'",
    "    : 'Suba o runtime local pelo atalho oficial para fechar setup, build e shell do runtime.';",
    "  const devCommand = localReady ? (commands.start || commands.go || 'npm run ops:start') : (commands.go || 'npm run ops:go');",
    "",
    "  const operatorSummary = hostAuthorized === false",
    "    ? 'Este host ainda precisa trust. Valide readiness com trust local antes de operar nodes, channels e transportes.'",
    "    : remoteReady",
    "      ? 'Host e remoto oficial estao prontos. Use a malha operacional abaixo para revisar nodes, transportes e extensoes antes do ready check completo.'",
    "      : 'Host local pronto. Feche o acesso remoto oficial antes de abrir operacao fora da maquina.';",
    "  const operatorCommand = hostAuthorized === false",
    "    ? (commands.ready || 'npm run ops:ready -- --trust-local')",
    "    : remoteReady",
    "      ? (commands.ready || 'npm run ops:ready -- --trust-local')",
    "      : (commands.remoteGo || 'npm run ops:remote:go');",
    "",
    "  const headlessSummary = localReady",
    "    ? 'Use a CLI e o REPL como harness principal para diagnostico, automacao e operacao sem shell grafico.'",
    "    : 'Comece pela CLI para checar o host e avance para o REPL quando o runtime estiver pronto.';",
    "  const headlessCommand = localReady ? 'npm run cli:repl' : (commands.ready || 'npm run cli -- status');",
    "",
    "  renderProfileRoute(priorityDevSummary, priorityDevAction, devSummary, devCommand, 'npm run ops:go');",
    "  renderProfileRoute(",
    "    priorityOperatorSummary,",
    "    priorityOperatorAction,",
    "    operatorSummary,",
    "    operatorCommand,",
    "    'npm run ops:ready -- --trust-local',",
    "  );",
    "  renderProfileRoute(",
    "    priorityHeadlessSummary,",
    "    priorityHeadlessAction,",
    "    headlessSummary,",
    "    headlessCommand,",
    "    'npm run cli -- status',",
    "  );",
    "}",
    "",
    "function renderAlternativeRoutes(manifest, report) {",
    "  const commands = manifest?.commands || {};",
    "  const localReady = manifest?.local?.ready === true;",
    "  const localAppUrl = normalizeText(manifest?.local?.appUrl);",
    "  const remoteReady = manifest?.officialRemote?.ready === true;",
    "  const remoteAppUrl = normalizeText(manifest?.officialRemote?.appUrl || report?.remote?.appUrl);",
    "  const hostAuthorized = manifest?.auth?.authorizedHost;",
    "",
    "  const devConfig = localReady",
    "    ? {",
    "        title: 'Abra o shell e continue no repo',",
    "        summary: localAppUrl",
    "          ? 'O runtime local ja esta pronto. Abra o shell oficial, valide o contrato e siga iterando no repo.'",
    "          : 'O runtime local ja esta pronto. Siga pelo shell oficial e continue no repo.',",
    "        steps: [",
    "          '<code>' + normalizeText(commands.start || 'npm run ops:start') + '</code>',",
    "          localAppUrl ? '<strong>Shell local:</strong> ' + localAppUrl : '<code>npm run cli -- status</code>',",
    "          '<code>npm run qa:regression</code>',",
    "        ],",
    "        actionLabel: 'Copiar rota Dev',",
    "        actionCommand: normalizeText(commands.start || commands.go || 'npm run ops:start'),",
    "      }",
    "    : {",
    "        title: 'Suba o runtime e valide o contrato',",
    "        summary: 'Melhor para quem esta desenvolvendo no repo oficial e ainda precisa fechar setup, build e shell local.',",
    "        steps: [",
    "          '<code>npm install</code>',",
    "          '<code>npm run setup</code>',",
    "          '<code>' + normalizeText(commands.go || 'npm run ops:go') + '</code>',",
    "        ],",
    "        actionLabel: 'Copiar rota Dev',",
    "        actionCommand: normalizeText(commands.go || 'npm run ops:go'),",
    "      };",
    "",
    "  const operatorConfig = hostAuthorized === false",
    "    ? {",
    "        title: 'Liberar host e revisar a malha',",
    "        summary: 'O runtime local responde, mas este host ainda precisa trust antes de acoes mutaveis e operacao supervisionada.',",
    "        steps: [",
    "          '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "          '<code>' + normalizeText(commands.trust || '/hostauth trust') + '</code>',",
    "          '<code>npm run test:nodes:smoke</code>',",
    "        ],",
    "        actionLabel: 'Copiar rota Operator',",
    "        actionCommand: normalizeText(commands.ready || 'npm run ops:ready -- --trust-local'),",
    "      }",
    "    : !remoteReady",
    "      ? {",
    "          title: 'Feche o acesso remoto oficial',",
    "          summary: 'O host local esta pronto. O melhor proximo corte operacional e fechar a rota remota oficial antes de abrir operacao fora da maquina.',",
    "          steps: [",
    "            '<code>' + normalizeText(commands.remoteGo || 'npm run ops:remote:go') + '</code>',",
    "            remoteAppUrl ? '<strong>Shell remoto esperado:</strong> ' + remoteAppUrl : '<strong>Remoto:</strong> rollout ainda pendente',",
    "            '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "          ],",
    "          actionLabel: 'Copiar rota Operator',",
    "          actionCommand: normalizeText(commands.remoteGo || 'npm run ops:remote:go'),",
    "        }",
    "      : {",
    "          title: 'Valide malha, acesso e providers',",
    "          summary: 'Host e remoto oficial estao prontos. Primeiro use a malha operacional do shell para revisar nodes, transportes e extensoes; depois feche a checagem completa.',",
    "          steps: [",
    "            '<strong>Malha operacional:</strong> use os cards compactos de nodes, transportes e extensoes na ZavorthControl.',",
    "            '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "            '<code>npm run nodes:doctor -- --json</code>',",
    "            '<code>npm run test:nodes:smoke</code>',",
    "          ],",
    "          actionLabel: 'Copiar rota Operator',",
    "          actionCommand: normalizeText(commands.ready || 'npm run ops:ready -- --trust-local'),",
    "        };",
    "",
    "  const headlessConfig = localReady",
    "    ? {",
    "        title: 'Operar so por terminal',",
    "        summary: 'O runtime local ja esta pronto. Use a CLI e o REPL como harness principal para diagnostico, automacao e operacao sem shell grafico.',",
    "        steps: [",
    "          '<code>npm run cli -- status</code>',",
    "          '<code>npm run cli:repl</code>',",
    "          '<code>npm run nodes:doctor -- --json</code>',",
    "        ],",
    "        actionLabel: 'Copiar rota Headless',",
    "        actionCommand: 'npm run cli:repl',",
    "      }",
    "    : {",
    "        title: 'Checar o host pelo terminal',",
    "        summary: 'Melhor para quem quer validar o host sem depender do shell grafico antes de subir tudo.',",
    "        steps: [",
    "          '<code>npm run cli -- status</code>',",
    "          '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "          '<code>npm run cli:repl</code>',",
    "        ],",
    "        actionLabel: 'Copiar rota Headless',",
    "        actionCommand: 'npm run cli -- status',",
    "      };",
    "",
    "  renderRouteCard(altDevTitle, altDevSummary, altDevSteps, altDevAction, devConfig);",
    "  renderRouteCard(",
    "    altOperatorTitle,",
    "    altOperatorSummary,",
    "    altOperatorSteps,",
    "    altOperatorAction,",
    "    operatorConfig,",
    "  );",
    "  renderRouteCard(",
    "    altHeadlessTitle,",
    "    altHeadlessSummary,",
    "    altHeadlessSteps,",
    "    altHeadlessAction,",
    "    headlessConfig,",
    "  );",
    "}",
    "",
    "function renderPriorityState(manifestPayload, journeyPayload, remotePayload) {",
    "  const manifest = manifestPayload?.manifest;",
    "  const journeyReport = journeyPayload?.report;",
    "  const remoteReport = remotePayload?.report;",
    "  const plan = manifest?.recommendedPlan;",
    "",
    "  setText(",
    "    prioritySummary,",
    "    normalizeText(plan?.primarySummary)",
    "      || normalizeText(manifest?.summary)",
    "      || normalizeText(remoteReport?.summary)",
    "      || 'Use a recomendacao oficial deste host para seguir sem ambiguidade.',",
    "  );",
    "  setText(priorityReason, buildPriorityReason(plan, manifest, remoteReport));",
    "",
    "  let items = [];",
    "  if (plan?.primaryAction === 'remote' && Array.isArray(remoteReport?.nextSteps) && remoteReport.nextSteps.length > 0) {",
    "    items = remoteReport.nextSteps.slice(0, 3).map((entry) => normalizeText(entry));",
    "  } else if ((plan?.primaryAction === 'go' || plan?.primaryAction === 'trust') && Array.isArray(journeyReport?.phases) && journeyReport.phases.length > 0) {",
    "    items = journeyReport.phases.slice(0, 3).map((phase) => formatJourneyPhase(phase));",
    "  } else if (Array.isArray(manifest?.nextSteps) && manifest.nextSteps.length > 0) {",
    "    items = manifest.nextSteps.slice(0, 3).map((step) => formatReadinessStep(step));",
    "  } else if (Array.isArray(journeyReport?.phases) && journeyReport.phases.length > 0) {",
    "    items = journeyReport.phases.slice(0, 3).map((phase) => formatJourneyPhase(phase));",
    "  } else if (Array.isArray(remoteReport?.nextSteps) && remoteReport.nextSteps.length > 0) {",
    "    items = remoteReport.nextSteps.slice(0, 3).map((entry) => normalizeText(entry));",
    "  }",
    "",
    "  renderList(priorityNextSteps, items.length > 0 ? items : ['Nada extra para fazer agora.']);",
    "  renderPriorityActions(manifest, remoteReport);",
    "  renderProfileRecommendations(manifest, remoteReport);",
    "  renderAlternativeRoutes(manifest, remoteReport);",
    "  renderProtectedCardHierarchy(manifest, remoteReport);",
    "  renderRemoteActionControls(remoteReport);",
    "}",
    "",
    "async function validateProtectedAccess(token, persist) {",
    "  if (!token) {",
    "    setText(authCopy, 'Cole um token valido antes de continuar.');",
    "    return;",
    "  }",
    "",
    "  if (authValidateButton) {",
    "    authValidateButton.disabled = true;",
    "  }",
    "",
    "  try {",
    "    const validationResponse = await fetch('/api/auth/validate', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify({ token }),",
    "    });",
    "    const validationPayload = await validationResponse.json().catch(() => null);",
    "    if (!validationResponse.ok || !validationPayload?.ok) {",
    "      throw new Error(validationPayload?.error || 'Token invalido.');",
    "    }",
    "",
    "    if (persist) {",
    "      writeStoredToken(token);",
    "    }",
    "",
    "    await refreshProtectedShellState(token);",
    "    setText(authCopy, 'Token validado. Manifesto, journey e acesso remoto oficial carregados.');",
    "  } catch (error) {",
    "    writeStoredToken('');",
    "    protectedShellUnlocked = false;",
    "    closeGatewayControlSocket('Token necessario');",
    "    setText(prioritySummary, 'Valide o token para ver a recomendacao oficial deste host.');",
    "    setText(priorityReason, 'O shell usa o manifesto oficial para dizer o que fazer agora, por que este e o melhor caminho e o que acontece depois.');",
    "    renderList(priorityNextSteps, ['Token nao validado.']);",
    "    renderProfileRecommendations(null, null);",
    "    renderAlternativeRoutes(null, null);",
    "    renderProtectedCardHierarchy(null, null);",
    "    renderJourneyActionControls(null, null);",
    "    renderRemoteActionControls(null);",
    "    resetPriorityActions();",
    "    renderList(manifestLaunchers, ['Token nao validado.']);",
    "    renderList(installJourney, ['Token nao validado.']);",
    "    renderList(remoteAccessSummary, ['Token nao validado.']);",
    "    operationalMeshExpanded.nodes = false;",
    "    operationalMeshExpanded.channels = false;",
    "    operationalMeshExpanded.transports = false;",
    "    operationalMeshExpanded.extensions = false;",
    "    renderOperationalMeshSummary(null, null, null, null, null, null, null, null, null, null);",
    "    renderSessionWorkspace(null);",
    "    renderLearningMemory(null, null, null);",
    "    renderReplayLearningControlPlanePanel(null);",
    "    renderDistributedRuntimeControlPlanePanel(null);",
    "    renderOperatorCockpit();",
    "    setText(authCopy, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (authValidateButton) {",
    "      authValidateButton.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installProtectedAccessForm() {",
    "  if (!(authInput instanceof HTMLInputElement) || !authValidateButton) {",
    "    return;",
    "  }",
    "",
    "  authValidateButton.addEventListener('click', () => {",
    "    void validateProtectedAccess(authInput.value.trim(), true);",
    "  });",
    "",
    "  authInput.addEventListener('keydown', (event) => {",
    "    if (event.key === 'Enter') {",
    "      event.preventDefault();",
    "      void validateProtectedAccess(authInput.value.trim(), true);",
    "    }",
    "  });",
    "",
    "  const storedToken = readStoredToken();",
    "  if (storedToken) {",
    "    authInput.value = storedToken;",
    "    void validateProtectedAccess(storedToken, false);",
    "  }",
    "}",
    "",
    "async function runOperationalMeshAction(kind) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    if (kind === 'nodes') {",
    "      setOperationalActionStatus(opsNodesStatus, 'Valide o token antes de revisar o Node Mesh.');",
    "    } else if (kind === 'channels') {",
    "      setOperationalActionStatus(opsChannelsStatus, 'Valide o token antes de revisar o Channel Mesh.');",
    "    } else if (kind === 'transports') {",
    "      setOperationalActionStatus(opsTransportsStatus, 'Valide o token antes de revisar o plano remoto.');",
    "    } else {",
    "      setOperationalActionStatus(opsExtensionsStatus, 'Valide o token antes de atualizar o catalogo de extensoes.');",
    "    }",
    "    return;",
    "  }",
    "",
    "  const button = kind === 'nodes'",
    "    ? opsNodesAction",
    "    : kind === 'channels'",
    "      ? opsChannelsAction",
    "    : kind === 'transports'",
    "      ? opsTransportsAction",
    "      : opsExtensionsAction;",
    "  if (!(button instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "",
    "  const mode = normalizeText(button.dataset.mode) || 'collapse';",
    "  const targetId = normalizeText(button.dataset.targetId);",
    "  if (mode === 'collapse') {",
    "    operationalMeshExpanded[kind] = false;",
    "    if (kind === 'nodes') {",
    "      renderNodesOperationalCard();",
    "    } else if (kind === 'channels') {",
    "      renderChannelsOperationalCard();",
    "    } else if (kind === 'transports') {",
    "      renderTransportsOperationalCard();",
    "    } else {",
    "      renderExtensionsOperationalCard();",
    "    }",
    "    return;",
    "  }",
    "",
    "  button.disabled = true;",
    "  try {",
    "    if (kind === 'nodes') {",
    "      const selectedId = normalizeText(targetId || operationalMeshSelection.nodes);",
    "      const includeDoctor = mode === 'nodes-open' || mode === 'nodes-doctor';",
    "      setOperationalActionStatus(",
    "        opsNodesStatus,",
    "        includeDoctor ? 'Carregando painel do Node Mesh...' : 'Atualizando foco do Node Mesh...',",
    "      );",
    "      const payload = await fetchNodeOperationalPanel(token, selectedId, includeDoctor);",
    "      operationalMeshData.nodeDoctor = payload.doctorPayload || operationalMeshData.nodeDoctor;",
    "      operationalMeshData.nodeActivity = payload.activityPayload || null;",
    "      operationalMeshData.nodeCapabilities = payload.capabilitiesPayload || null;",
    "      operationalMeshData.nodeBootstrap = payload.nodeBootstrapPayload || null;",
    "      if (payload.nodeMeshPayload?.ok !== false) {",
    "        operationalMeshData.nodes = payload.nodeMeshPayload;",
    "      }",
    "      operationalMeshExpanded.nodes = true;",
    "      renderNodesOperationalCard();",
    "      setOperationalActionStatus(",
    "        opsNodesStatus,",
    "        normalizeText(payload?.doctorPayload?.doctor?.summary)",
    "          || (selectedId ? 'Painel do Node Mesh atualizado para o foco selecionado.' : 'Painel do Node Mesh aberto.'),",
    "      );",
    "      return;",
    "    }",
    "",
    "    if (kind === 'channels') {",
    "      const selectedId = normalizeText(targetId || operationalMeshSelection.channels);",
    "      setOperationalActionStatus(",
    "        opsChannelsStatus,",
    "        mode === 'channels-open' ? 'Abrindo painel do Channel Mesh...' : 'Atualizando foco do Channel Mesh...',",
    "      );",
    "      const payload = await fetchChannelOperationalPanel(token, selectedId);",
    "      operationalMeshExpanded.channels = true;",
    "      operationalMeshData.channels = payload.channelMeshPayload;",
    "      operationalMeshData.channelInstall = payload.channelInstallPayload;",
    "      operationalMeshData.channelDoctor = payload.channelDoctorPayload;",
    "      operationalMeshData.channelAssistant = payload.channelAssistantPayload;",
    "      operationalMeshData.channelDetail = payload.channelDetailPayload;",
    "      renderChannelsOperationalCard();",
    "      setOperationalActionStatus(",
    "        opsChannelsStatus,",
    "        normalizeText(payload?.channelDoctorPayload?.doctor?.summary)",
    "          || (selectedId ? 'Channel Mesh atualizado para o foco selecionado.' : 'Painel do Channel Mesh aberto.'),",
    "      );",
    "      return;",
    "    }",
    "",
    "    if (kind === 'transports') {",
    "      const selectedId = normalizeText(targetId || operationalMeshSelection.transports);",
    "      setOperationalActionStatus(",
    "        opsTransportsStatus,",
    "        mode === 'transports-open' ? 'Abrindo painel remoto...' : 'Atualizando plano remoto...',",
    "      );",
    "      const payload = await fetchTransportOperationalPanel(token, selectedId, Boolean(selectedId));",
    "      operationalMeshData.transports = payload.transportPayload;",
    "      operationalMeshData.transportHistory = payload.historyPayload;",
    "      operationalMeshExpanded.transports = true;",
    "      renderTransportsOperationalCard();",
    "      setOperationalActionStatus(",
    "        opsTransportsStatus,",
    "        selectedId ? 'Painel remoto atualizado para o foco selecionado.' : 'Plano remoto atualizado.',",
    "      );",
    "      return;",
    "    }",
    "",
    "    const selectedId = normalizeText(targetId || operationalMeshSelection.extensions);",
    "    setOperationalActionStatus(",
    "      opsExtensionsStatus,",
].join('\n');
