export const runtimeShellScriptPart7Seg2: string = [
    "      mode === 'extensions-open' ? 'Abrindo painel das extensoes...' : 'Atualizando catalogo de extensoes...',",
    "    );",
    "    const payload = await fetchExtensionOperationalPanel(token, selectedId);",
    "    operationalMeshExpanded.extensions = true;",
    "    operationalMeshData.extensions = payload.extensionPayload;",
    "    operationalMeshData.plugins = payload.pluginsPayload;",
    "    operationalMeshData.hooks = payload.hooksPayload;",
    "    renderExtensionsOperationalCard();",
    "    setOperationalActionStatus(",
    "      opsExtensionsStatus,",
    "      selectedId ? 'Catalogo atualizado para o workspace selecionado.' : 'Catalogo de extensoes atualizado.',",
    "    );",
    "  } catch (error: unknown) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    if (kind === 'nodes') {",
    "      setOperationalActionStatus(opsNodesStatus, message);",
    "    } else if (kind === 'channels') {",
    "      setOperationalActionStatus(opsChannelsStatus, message);",
    "    } else if (kind === 'transports') {",
    "      setOperationalActionStatus(opsTransportsStatus, message);",
    "    } else {",
    "      setOperationalActionStatus(opsExtensionsStatus, message);",
    "    }",
    "  } finally {",
    "    button.disabled = false;",
    "  }",
    "}",
    "",
    "async function runOperationalMeshInlineAction(kind, mode, targetId, extra = '') {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    return;",
    "  }",
    "",
    "  try {",
    "      if (kind === 'nodes') {",
    "        if (mode === 'doctor' || mode === 'nodes-doctor') {",
    "          const selectedId = normalizeText(targetId || operationalMeshSelection.nodes);",
    "          setOperationalActionStatus(opsNodesStatus, 'Rodando doctor do Node Mesh...');",
    "        const payload = await fetchNodeOperationalPanel(token, selectedId, true);",
    "        if (payload.nodeMeshPayload?.ok !== false) {",
    "          operationalMeshData.nodes = payload.nodeMeshPayload;",
    "        }",
    "        operationalMeshData.nodeDoctor = payload.doctorPayload || operationalMeshData.nodeDoctor;",
    "        operationalMeshData.nodeActivity = payload.activityPayload || null;",
    "        operationalMeshData.nodeCapabilities = payload.capabilitiesPayload || null;",
    "        operationalMeshData.nodeBootstrap = payload.nodeBootstrapPayload || null;",
    "        operationalMeshExpanded.nodes = true;",
    "        renderNodesOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsNodesStatus,",
    "          normalizeText(payload?.doctorPayload?.doctor?.summary) || 'Doctor do Node Mesh completed.',",
    "        );",
    "        return;",
    "      }",
    "",
    "      if (mode === 'select' || mode === 'node-select') {",
    "        operationalMeshSelection.nodes = normalizeText(targetId);",
    "        const payload = await fetchNodeOperationalPanel(token, operationalMeshSelection.nodes, true);",
    "        operationalMeshData.nodes = payload.nodeMeshPayload;",
    "        operationalMeshData.nodeDoctor = payload.doctorPayload || operationalMeshData.nodeDoctor;",
    "        operationalMeshData.nodeActivity = payload.activityPayload || null;",
    "        operationalMeshData.nodeCapabilities = payload.capabilitiesPayload || null;",
    "        operationalMeshData.nodeBootstrap = payload.nodeBootstrapPayload || null;",
    "        operationalMeshExpanded.nodes = true;",
    "        renderNodesOperationalCard();",
    "          setOperationalActionStatus(opsNodesStatus, 'Node foco atualizado.');",
    "          return;",
    "        }",
    "",
    "        if ((mode === 'bootstrap' || mode === 'node-bootstrap') && targetId) {",
    "          setOperationalActionStatus(opsNodesStatus, 'Carregando bootstrap canonico do node foco...');",
    "          const payload = await fetchProtectedJsonOptional('/api/web/nodes/' + encodeURIComponent(targetId) + '/bootstrap', token);",
    "          operationalMeshData.nodeBootstrap = payload || null;",
    "          if (payload?.nodeMesh) {",
    "            operationalMeshData.nodes = {",
    "              ok: true,",
    "              nodeMesh: payload.nodeMesh,",
    "            };",
    "          }",
    "          operationalMeshExpanded.nodes = true;",
    "          renderNodesOperationalCard();",
    "          const bootstrapCommand = normalizeText(payload?.draft?.bootstrap?.command);",
    "          if (bootstrapCommand) {",
    "            await copyTextWithFallback(bootstrapCommand, 'Copie o bootstrap abaixo:');",
    "            setOperationalActionStatus(opsNodesStatus, 'Bootstrap do node foco copiado.');",
    "          } else {",
    "            setOperationalActionStatus(opsNodesStatus, 'Nenhum bootstrap pendente para este node.');",
    "          }",
    "          return;",
    "        }",
    "",
    "        if ((mode === 'policy-all' || mode === 'policy-safe' || mode === 'policy-clear' || mode === 'policy-custom') && targetId) {",
    "          const selected = operationalMeshData.nodes?.nodeMesh?.selected || null;",
    "          const capabilityEntries = buildNodeCapabilityEntries(selected, operationalMeshData.nodeCapabilities?.capabilities || null);",
    "          const currentApproved = Array.isArray(selected?.approvedCapabilityIds)",
    "            ? selected.approvedCapabilityIds.map((entry) => normalizeText(entry)).filter(Boolean)",
    "            : [];",
    "          let approvedCapabilityIds = [];",
    "          if (mode === 'policy-all') {",
    "            approvedCapabilityIds = parseOperationalIdList(extra || capabilityEntries.map((entry) => entry.id).join(','));",
    "          } else if (mode === 'policy-safe') {",
    "            approvedCapabilityIds = parseOperationalIdList(",
    "              extra || capabilityEntries.filter((entry) => !entry.risky).map((entry) => entry.id).join(','),",
    "            );",
    "          } else if (mode === 'policy-clear') {",
    "            approvedCapabilityIds = [];",
    "          } else {",
    "            const suggested = extra || currentApproved.join(', ');",
    "            const input = window.prompt(",
    "              'Informe as capabilityIds aprovadas para este node, separadas por virgula.',",
    "              suggested,",
    "            );",
    "            if (input === null) {",
    "              setOperationalActionStatus(opsNodesStatus, 'Edicao da allowlist cancelada.');",
    "              return;",
    "            }",
    "            approvedCapabilityIds = parseOperationalIdList(input);",
    "          }",
    "",
    "          setOperationalActionStatus(opsNodesStatus, 'Salvando allowlist do node foco...');",
    "          const reasonMap = {",
    "            'policy-all': 'Allowlist alinhada ao catalogo declarado do node.',",
    "            'policy-safe': 'Allowlist reduzida para capabilities seguras do node.',",
    "            'policy-clear': 'Allowlist limpa by the operator no shell oficial.',",
    "            'policy-custom': 'Allowlist ajustada manualmente no shell oficial.',",
    "          };",
    "          await postProtectedJson('/api/web/nodes/' + encodeURIComponent(targetId) + '/approved-capabilities', token, {",
    "            approvedCapabilityIds,",
    "            reason: reasonMap[mode] || 'Allowlist atualizada no shell oficial.',",
    "            mode: mode.replace('policy-', ''),",
    "          });",
    "          const payload = await fetchNodeOperationalPanel(token, targetId, true);",
    "          operationalMeshData.nodes = payload.nodeMeshPayload;",
    "          operationalMeshData.nodeDoctor = payload.doctorPayload || operationalMeshData.nodeDoctor;",
    "          operationalMeshData.nodeActivity = payload.activityPayload || null;",
    "          operationalMeshData.nodeCapabilities = payload.capabilitiesPayload || null;",
    "          operationalMeshData.nodeBootstrap = payload.nodeBootstrapPayload || null;",
    "          operationalMeshExpanded.nodes = true;",
    "          renderNodesOperationalCard();",
    "          setOperationalActionStatus(",
    "            opsNodesStatus,",
    "            approvedCapabilityIds.length > 0",
    "              ? 'Allowlist atualizada para ' + String(approvedCapabilityIds.length) + ' capability(s) aprovada(s).'",
    "              : 'Allowlist limpa para o node foco.',",
    "          );",
    "          return;",
    "        }",
    "",
    "        if ((mode === 'recover' || mode === 'node-recover') && targetId) {",
    "          setOperationalActionStatus(opsNodesStatus, 'Aplicando recover no node foco...');",
    "          const selected = operationalMeshData.nodes?.nodeMesh?.selected || null;",
    "          const recoverKind = normalizeText(extra || selected?.maintenance?.recoverKind || 'release-stale-claims');",
    "          await postProtectedJson('/api/web/nodes/recover', token, {",
    "          kind: recoverKind,",
    "          nodeId: targetId,",
    "        });",
    "        const payload = await fetchNodeOperationalPanel(token, targetId, true);",
    "        operationalMeshData.nodes = payload.nodeMeshPayload;",
    "        operationalMeshData.nodeDoctor = payload.doctorPayload || operationalMeshData.nodeDoctor;",
    "        operationalMeshData.nodeActivity = payload.activityPayload || null;",
    "        operationalMeshData.nodeCapabilities = payload.capabilitiesPayload || null;",
    "        operationalMeshData.nodeBootstrap = payload.nodeBootstrapPayload || null;",
    "        operationalMeshExpanded.nodes = true;",
    "        renderNodesOperationalCard();",
    "        setOperationalActionStatus(opsNodesStatus, 'Recover do node foco completed.');",
    "      }",
    "      return;",
    "    }",
    "",
    "    if (kind === 'channels') {",
    "      if (mode === 'select' || mode === 'channel-select') {",
    "        operationalMeshSelection.channels = normalizeText(targetId);",
    "        const payload = await fetchChannelOperationalPanel(token, operationalMeshSelection.channels);",
    "        operationalMeshData.channels = payload.channelMeshPayload;",
    "        operationalMeshData.channelInstall = payload.channelInstallPayload;",
    "        operationalMeshData.channelDoctor = payload.channelDoctorPayload;",
    "        operationalMeshData.channelAssistant = payload.channelAssistantPayload;",
    "        operationalMeshData.channelDetail = payload.channelDetailPayload;",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(opsChannelsStatus, 'Canal foco atualizado.');",
    "        return;",
    "      }",
    "",
    "      if (mode === 'doctor' || mode === 'channels-doctor') {",
    "        const payload = await fetchChannelOperationalPanel(token, normalizeText(targetId || operationalMeshSelection.channels));",
    "        operationalMeshData.channels = payload.channelMeshPayload;",
    "        operationalMeshData.channelInstall = payload.channelInstallPayload;",
    "        operationalMeshData.channelDoctor = payload.channelDoctorPayload;",
    "        operationalMeshData.channelAssistant = payload.channelAssistantPayload;",
    "        operationalMeshData.channelDetail = payload.channelDetailPayload;",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsChannelsStatus,",
    "          normalizeText(payload?.channelDoctorPayload?.doctor?.summary) || 'Doctor dos canais atualizado.',",
    "        );",
    "        return;",
    "      }",
    "",
    "      if ((mode === 'inspect' || mode === 'status' || mode === 'policy' || mode === 'prepare' || mode === 'broadcast-test' || mode === 'send-test' || mode === 'login-qr' || mode === 'relink' || mode === 'logout' || mode === 'channel-action') && targetId) {",
    "        const actionId = normalizeText(extra || mode);",
    "        setOperationalActionStatus(opsChannelsStatus, 'Executando acao do Channel Mesh...');",
    "        const payload = await postProtectedJson('/api/web/channels/actions', token, {",
    "          channelId: targetId,",
    "          actionId,",
    "        });",
    "        operationalMeshData.channels = {",
    "          ok: true,",
    "          channels: payload?.channels || null,",
    "        };",
    "        operationalMeshData.channelAction = payload?.result || null;",
    "        const detailPayload = await fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(targetId), token);",
    "        operationalMeshData.channelDetail = detailPayload;",
    "        operationalMeshData.channelAssistant = await fetchChannelSetupAssistant(token, targetId);",
    "        if (actionId === 'prepare') {",
    "          operationalMeshData.channelInstall = await fetchProtectedJsonOptional('/api/web/channels/install?selectedId=' + encodeURIComponent(targetId), token);",
    "        }",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsChannelsStatus,",
    "          normalizeText(payload?.result?.summary) || 'Acao do Channel Mesh concluida.',",
    "        );",
    "        return;",
    "      }",
    "",
    "      if ((mode === 'channel-assistant' || mode === 'channel-assistant-doctor') && targetId) {",
    "        if (mode === 'channel-assistant-doctor') {",
    "          setOperationalActionStatus(opsChannelsStatus, 'Rodando doctor assistido do canal foco...');",
    "          const payload = await postProtectedJson('/api/web/channels/setup-assistant/doctor', token, {",
    "            selectedId: targetId,",
    "            localOnly: true,",
    "          });",
    "          operationalMeshData.channelAssistant = payload?.assistant ? payload : null;",
    "          operationalMeshData.channelDoctor = payload?.doctor ? { ok: true, doctor: payload.doctor } : operationalMeshData.channelDoctor;",
    "          operationalMeshData.channels = {",
    "            ok: true,",
    "            channels: payload?.channels || operationalMeshData.channels?.channels || null,",
    "          };",
    "          operationalMeshData.channelDetail = await fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(targetId), token);",
    "          operationalMeshExpanded.channels = true;",
    "          renderChannelsOperationalCard();",
    "          setOperationalActionStatus(",
    "            opsChannelsStatus,",
    "            normalizeText(payload?.selectedItem?.summary || payload?.doctor?.summary) || 'Doctor assistido completed.',",
    "          );",
    "          return;",
    "        }",
    "",
    "        setOperationalActionStatus(opsChannelsStatus, 'Carregando assistente do canal foco...');",
    "        const payload = await fetchChannelSetupAssistant(token, targetId, extra);",
    "        operationalMeshData.channelAssistant = payload || null;",
    "        if (payload?.channels) {",
    "          operationalMeshData.channels = {",
    "            ok: true,",
    "            channels: payload.channels,",
    "          };",
    "        }",
    "        operationalMeshData.channelInstall = payload?.assistant?.report",
    "          ? { ok: true, report: payload.assistant.report }",
    "          : operationalMeshData.channelInstall;",
    "        operationalMeshData.channelDetail = await fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(targetId), token);",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsChannelsStatus,",
    "          normalizeText(payload?.assistant?.naturalReply) || 'Assistente do canal carregado.',",
    "        );",
    "        return;",
    "      }",
    "",
    "      if (mode === 'channel-assistant-apply' && targetId) {",
    "        const selectedMode = normalizeText(",
    "          extra",
    "          || operationalMeshData.channelAssistant?.assistant?.selected?.setupMode",
    "          || operationalMeshData.channelAssistant?.selected?.setupMode,",
    "        );",
    "        setOperationalActionStatus(opsChannelsStatus, 'Aplicando scaffold pelo assistente...');",
    "        const payload = await postProtectedJson('/api/web/channels/setup-assistant/apply', token, {",
    "          channelId: targetId,",
    "          mode: selectedMode,",
    "        });",
    "        operationalMeshData.channelAssistant = payload?.assistant ? payload : null;",
    "        operationalMeshData.channels = {",
    "          ok: true,",
    "          channels: payload?.channels || operationalMeshData.channels?.channels || null,",
    "        };",
    "        operationalMeshData.channelInstall = {",
    "          ok: true,",
    "          report: payload?.assistant?.report || payload?.applyReport?.report || null,",
    "        };",
    "        operationalMeshData.channelAction = {",
    "          summary: 'Assistente aplicou scaffold para ' + targetId + (selectedMode ? ' em modo ' + selectedMode : '') + '.',",
    "          details: Array.isArray(payload?.applyReport?.nextSteps) ? payload.applyReport.nextSteps : [],",
    "        };",
    "        operationalMeshData.channelDoctor = await fetchProtectedJsonOptional(",
    "          '/api/web/channels/setup-assistant/doctor',",
    "          token,",
    "          { method: 'POST', body: JSON.stringify({ selectedId: targetId, localOnly: true }) },",
    "        );",
    "        operationalMeshData.channelDetail = await fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(targetId), token);",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsChannelsStatus,",
    "          normalizeText(payload?.assistant?.naturalReply || payload?.applyReport?.nextSteps?.[0])",
    "            || ('Assistente aplicou scaffold para ' + targetId + '.'),",
    "        );",
    "        return;",
    "      }",
    "",
    "      if (mode === 'channel-apply-mode' && targetId) {",
    "        const selectedMode = normalizeText(extra);",
    "        setOperationalActionStatus(opsChannelsStatus, 'Aplicando scaffold do canal foco...');",
    "        const payload = await postProtectedJson('/api/web/channels/setup-assistant/apply', token, {",
    "          channelId: targetId,",
    "          mode: selectedMode,",
    "        });",
    "        operationalMeshData.channelAssistant = payload?.assistant ? payload : null;",
    "        operationalMeshData.channels = {",
    "          ok: true,",
    "          channels: payload?.channels || operationalMeshData.channels?.channels || null,",
    "        };",
    "        operationalMeshData.channelInstall = {",
    "          ok: true,",
    "          report: payload?.assistant?.report || payload?.report || payload?.applyReport?.report || null,",
    "        };",
    "        operationalMeshData.channelAction = {",
    "          summary: 'Scaffold aplicado para ' + targetId + ' em modo ' + selectedMode + '.',",
    "          details: Array.isArray(payload?.applyReport?.nextSteps) ? payload.applyReport.nextSteps : [],",
    "        };",
    "        operationalMeshData.channelDoctor = await fetchProtectedJsonOptional(",
    "          '/api/web/channels/setup-assistant/doctor',",
    "          token,",
    "          { method: 'POST', body: JSON.stringify({ selectedId: targetId, localOnly: true }) },",
    "        );",
    "        operationalMeshData.channelDetail = await fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(targetId), token);",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsChannelsStatus,",
    "          normalizeText(payload?.applyReport?.nextSteps?.[0])",
    "            || ('Scaffold aplicado para ' + targetId + ' em modo ' + selectedMode + '.'),",
    "        );",
    "        return;",
    "      }",
    "",
    "      if (mode === 'channel-configure-mode' && targetId) {",
    "        const selectedMode = normalizeText(extra);",
    "        if (!selectedMode) {",
    "          setOperationalActionStatus(opsChannelsStatus, 'Escolha um modo valido antes de configurar o canal.');",
    "          return;",
    "        }",
    "        setOperationalActionStatus(opsChannelsStatus, 'Carregando scaffold do modo escolhido...');",
    "        const planPayload = await fetchChannelInstallPlan(token, targetId, selectedMode);",
    "        const selectedPlan = planPayload?.selected || null;",
    "        const scaffoldEntries = Array.isArray(selectedPlan?.scaffoldEntries) ? selectedPlan.scaffoldEntries : [];",
    "        const defaultLines = scaffoldEntries",
    "          .map((entry) => normalizeText(entry?.key) ? normalizeText(entry.key) + '=' + String(entry?.value || '') : '')",
    "          .filter(Boolean)",
    "          .join('\\n');",
    "        const promptText =",
    "          'Revise os campos KEY=value para ' + targetId + ' em modo ' + selectedMode + '.\\n'",
    "          + 'Deixe em branco o que ainda vai preencher depois. Cancelar aborta sem alterar o host.';",
    "        const input = window.prompt(promptText, defaultLines);",
    "        if (input === null) {",
    "          setOperationalActionStatus(opsChannelsStatus, 'Configuraction do canal cancelada.');",
    "          return;",
    "        }",
    "        const extraEntries = parseOperationalEnvEntries(input);",
    "        setOperationalActionStatus(opsChannelsStatus, 'Aplicando scaffold configurado no shell oficial...');",
    "        const payload = await postProtectedJson('/api/web/channels/setup-assistant/apply', token, {",
    "          channelId: targetId,",
    "          mode: selectedMode,",
    "          extraEntries,",
    "        });",
    "        operationalMeshData.channelAssistant = payload?.assistant ? payload : null;",
    "        operationalMeshData.channels = {",
    "          ok: true,",
    "          channels: payload?.channels || operationalMeshData.channels?.channels || null,",
    "        };",
    "        operationalMeshData.channelInstall = {",
    "          ok: true,",
    "          report: payload?.assistant?.report || payload?.report || payload?.applyReport?.report || null,",
    "        };",
    "        operationalMeshData.channelAction = {",
    "          summary: 'Canal ' + targetId + ' configurado em modo ' + selectedMode + ' pela ZavorthControl.',",
    "          details: Array.isArray(payload?.applyReport?.nextSteps) ? payload.applyReport.nextSteps : [],",
    "        };",
    "        operationalMeshData.channelDoctor = await fetchProtectedJsonOptional(",
    "          '/api/web/channels/setup-assistant/doctor',",
    "          token,",
    "          { method: 'POST', body: JSON.stringify({ selectedId: targetId, localOnly: true }) },",
    "        );",
    "        operationalMeshData.channelDetail = await fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(targetId), token);",
    "        operationalMeshExpanded.channels = true;",
    "        renderChannelsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsChannelsStatus,",
    "          normalizeText(payload?.applyReport?.nextSteps?.[0])",
    "            || ('Canal ' + targetId + ' configurado em modo ' + selectedMode + '.'),",
    "        );",
    "        return;",
    "      }",
    "",
    "      return;",
    "    }",
    "",
    "    if (kind === 'transports') {",
    "      if (mode === 'select' || mode === 'transport-select') {",
    "        operationalMeshSelection.transports = normalizeText(targetId);",
    "        const payload = await fetchTransportOperationalPanel(token, operationalMeshSelection.transports, true);",
    "        operationalMeshData.transports = payload.transportPayload;",
    "        operationalMeshData.transportHistory = payload.historyPayload;",
    "        operationalMeshExpanded.transports = true;",
    "        renderTransportsOperationalCard();",
    "        setOperationalActionStatus(opsTransportsStatus, 'Transporte foco atualizado.');",
    "        return;",
    "      }",
    "",
    "      if ((mode === 'doctor' || mode === 'transport-doctor') && targetId) {",
    "        setOperationalActionStatus(opsTransportsStatus, 'Rodando doctor do transporte foco...');",
    "        const payload = await postProtectedJson('/api/web/transports/' + encodeURIComponent(targetId) + '/doctor', token, null);",
    "        operationalMeshData.transports = {",
    "          ok: true,",
    "          transports: payload?.transports || null,",
    "        };",
    "        operationalMeshData.transportDoctor = payload || null;",
    "        const historyPayload = await fetchProtectedJsonOptional('/api/web/transports/' + encodeURIComponent(targetId) + '/history', token);",
    "        operationalMeshData.transportHistory = historyPayload;",
    "        operationalMeshExpanded.transports = true;",
    "        renderTransportsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsTransportsStatus,",
    "          normalizeText(payload?.report?.summary || payload?.error) || 'Doctor do transporte foco completed.',",
    "        );",
    "        return;",
    "      }",
    "",
    "      if ((mode === 'recover' || mode === 'transport-recover') && targetId) {",
    "        setOperationalActionStatus(opsTransportsStatus, 'Aplicando recover no transporte foco...');",
    "        const payload = await postProtectedJson('/api/web/transports/' + encodeURIComponent(targetId) + '/recover', token, null);",
    "        operationalMeshData.transports = {",
    "          ok: true,",
    "          transports: payload?.transports || null,",
    "        };",
    "        operationalMeshData.transportHistory = await fetchProtectedJsonOptional('/api/web/transports/' + encodeURIComponent(targetId) + '/history', token);",
    "        operationalMeshExpanded.transports = true;",
    "        renderTransportsOperationalCard();",
    "        setOperationalActionStatus(opsTransportsStatus, 'Recover do transporte foco completed.');",
    "      }",
    "",
    "      if (mode === 'remote-action' && targetId) {",
    "        setOperationalActionStatus(opsTransportsStatus, 'Executando acao remota do transporte foco...');",
    "        const payload = await postProtectedJson('/api/web/transports/actions', token, {",
    "          transportId: targetId,",
    "          actionId: normalizeText(extra),",
    "        });",
    "        operationalMeshData.transports = {",
    "          ok: true,",
    "          transports: payload?.transports || null,",
    "        };",
    "        operationalMeshData.transportHistory = await fetchProtectedJsonOptional('/api/web/transports/' + encodeURIComponent(targetId) + '/history', token);",
    "        operationalMeshExpanded.transports = true;",
    "        renderTransportsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsTransportsStatus,",
    "          normalizeText(payload?.result?.summary || payload?.result?.status || 'Acao remota concluida.'),",
    "        );",
    "        return;",
    "      }",
    "      return;",
    "    }",
    "",
    "    if (kind === 'extensions' && (mode === 'select' || mode === 'extension-select')) {",
    "      operationalMeshSelection.extensions = normalizeText(targetId);",
    "      const payload = await fetchExtensionOperationalPanel(token, operationalMeshSelection.extensions);",
    "      operationalMeshData.extensions = payload.extensionPayload;",
    "      operationalMeshData.plugins = payload.pluginsPayload;",
    "      operationalMeshData.hooks = payload.hooksPayload;",
    "      operationalMeshExpanded.extensions = true;",
    "      renderExtensionsOperationalCard();",
    "      setOperationalActionStatus(opsExtensionsStatus, 'Workspace foco atualizado.');",
    "      return;",
    "    }",
    "",
    "      if (kind === 'extensions' && mode === 'refresh') {",
    "        const payload = await fetchExtensionOperationalPanel(token, normalizeText(targetId || operationalMeshSelection.extensions));",
    "        operationalMeshData.extensions = payload.extensionPayload;",
    "        operationalMeshData.plugins = payload.pluginsPayload;",
    "        operationalMeshData.hooks = payload.hooksPayload;",
    "        operationalMeshExpanded.extensions = true;",
    "        renderExtensionsOperationalCard();",
    "        setOperationalActionStatus(opsExtensionsStatus, 'Catalogo local atualizado.');",
    "        return;",
    "      }",
    "",
    "      if (kind === 'extensions' && mode === 'platform-sync') {",
    "        setOperationalActionStatus(opsExtensionsStatus, 'Sincronizando registry de extensoes...');",
    "        const payload = await postProtectedJson('/api/web/platform/sync', token, {});",
    "        const refreshed = await fetchExtensionOperationalPanel(token, normalizeText(targetId || operationalMeshSelection.extensions));",
    "        operationalMeshData.extensions = refreshed.extensionPayload;",
    "        operationalMeshData.plugins = refreshed.pluginsPayload;",
    "        operationalMeshData.hooks = refreshed.hooksPayload;",
    "        operationalMeshExpanded.extensions = true;",
    "        renderExtensionsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsExtensionsStatus,",
    "          normalizeText(payload?.result?.summary || payload?.result?.status || 'Registry sincronizado.'),",
    "        );",
    "        return;",
    "      }",
    "",
    "      if (kind === 'extensions' && mode === 'plugin-action' && targetId) {",
    "        setOperationalActionStatus(opsExtensionsStatus, 'Executando acao do plugin foco...');",
    "        const payload = await postProtectedJson('/api/web/plugins/actions', token, {",
    "          pluginId: targetId,",
    "          actionId: normalizeText(extra),",
    "        });",
    "        const refreshed = await fetchExtensionOperationalPanel(token, normalizeText(operationalMeshSelection.extensions));",
    "        operationalMeshData.extensions = refreshed.extensionPayload;",
    "        operationalMeshData.plugins = payload?.plugins ? { ok: true, plugins: payload.plugins } : refreshed.pluginsPayload;",
    "        operationalMeshData.hooks = refreshed.hooksPayload;",
    "        operationalMeshExpanded.extensions = true;",
    "        renderExtensionsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsExtensionsStatus,",
    "          normalizeText(payload?.result?.summary || payload?.result?.status || 'Acao do plugin concluida.'),",
    "        );",
    "        return;",
    "      }",
    "",
    "      if (kind === 'extensions' && mode === 'hook-dry-run' && targetId) {",
    "        setOperationalActionStatus(opsExtensionsStatus, 'Rodando dry-run do hook principal...');",
    "        const payload = await postProtectedJson('/api/web/hooks/run', token, {",
    "          workspace: targetId,",
    "          event: normalizeText(extra),",
    "        });",
    "        const refreshed = await fetchExtensionOperationalPanel(token, normalizeText(operationalMeshSelection.extensions));",
    "        operationalMeshData.extensions = refreshed.extensionPayload;",
    "        operationalMeshData.plugins = refreshed.pluginsPayload;",
    "        operationalMeshData.hooks = payload?.hooks ? { ok: true, hooks: payload.hooks, pipeline: payload.pipeline, run: payload.run } : refreshed.hooksPayload;",
    "        operationalMeshExpanded.extensions = true;",
    "        renderExtensionsOperationalCard();",
    "        setOperationalActionStatus(",
    "          opsExtensionsStatus,",
    "          normalizeText(payload?.run?.executions?.[0]?.results?.[0]?.status || payload?.run?.summary || 'Dry-run do hook completed.'),",
    "        );",
    "        return;",
    "      }",
    "    } catch (error: unknown) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    if (kind === 'nodes') {",
    "      setOperationalActionStatus(opsNodesStatus, message);",
    "    } else if (kind === 'transports') {",
    "      setOperationalActionStatus(opsTransportsStatus, message);",
    "    } else {",
    "      setOperationalActionStatus(opsExtensionsStatus, message);",
    "    }",
    "  }",
    "}",
    "",
    "function installOperationalMeshActions() {",
    "  if (opsNodesAction instanceof HTMLButtonElement) {",
    "    opsNodesAction.addEventListener('click', () => {",
    "      void runOperationalMeshAction('nodes');",
    "    });",
    "  }",
    "",
    "  if (opsChannelsAction instanceof HTMLButtonElement) {",
    "    opsChannelsAction.addEventListener('click', () => {",
    "      void runOperationalMeshAction('channels');",
    "    });",
    "  }",
    "",
    "  if (opsTransportsAction instanceof HTMLButtonElement) {",
    "    opsTransportsAction.addEventListener('click', () => {",
    "      void runOperationalMeshAction('transports');",
    "    });",
    "  }",
    "",
    "  if (opsExtensionsAction instanceof HTMLButtonElement) {",
    "    opsExtensionsAction.addEventListener('click', () => {",
    "      void runOperationalMeshAction('extensions');",
    "    });",
    "  }",
    "",
    "  if (opsMeshCard instanceof HTMLElement) {",
    "    opsMeshCard.addEventListener('click', (event) => {",
    "      const copyTarget = event.target instanceof HTMLElement",
    "        ? event.target.closest('[data-operational-copy]')",
    "        : null;",
    "      if (copyTarget instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        const value = normalizeText(copyTarget.dataset.operationalCopy);",
    "        if (!value) {",
].join('\n');
