export const runtimeShellScriptPart8Seg1: string = [
    "          return;",
    "        }",
    "        void copyTextWithFallback(value, 'Copie o comando abaixo:');",
    "        return;",
    "      }",
    "",
    "      const target = event.target instanceof HTMLElement",
    "        ? event.target.closest('[data-operational-kind][data-operational-mode][data-target-id],[data-operational-kind][data-operational-action][data-operational-target]')",
    "        : null;",
    "      if (!(target instanceof HTMLButtonElement)) {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      const kind = normalizeText(target.dataset.operationalKind);",
    "      const mode = normalizeText(target.dataset.operationalMode || target.dataset.operationalAction);",
    "      const targetId = normalizeText(target.dataset.targetId || target.dataset.operationalTarget);",
    "      const extra = normalizeText(target.dataset.operationalExtra);",
    "      if (!kind || !mode) {",
    "        return;",
    "      }",
    "      void runOperationalMeshInlineAction(kind, mode, targetId, extra);",
    "    });",
    "  }",
    "}",
    "",
    "async function runSessionWorkspaceAction() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(sessionWorkspaceStatus, 'Valide o token antes de atualizar o workspace da sessao.');",
    "    return;",
    "  }",
    "",
    "  if (!(sessionWorkspaceAction instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "",
    "  sessionWorkspaceAction.disabled = true;",
    "  try {",
    "    setText(sessionWorkspaceStatus, 'Atualizando sessao ativa, approvals e replay...');",
    "    const payload = await refreshSessionWorkspaceViaGateway(token, '', {",
    "      replayMode: 'full',",
    "    });",
    "    renderSessionWorkspace(payload);",
    "    setText(",
    "      sessionWorkspaceStatus,",
    "      pickFirstText([",
    "        payload?.state?.sessionPlane?.narrative?.operatorSummary,",
    "        payload?.history?.sessionPlane?.narrative?.operatorSummary,",
    "        payload?.history?.session?.handoff?.operatorSummary,",
    "        payload?.history?.session?.replay?.operatorSummary,",
    "      ], 'Workspace da sessao atualizado.'),",
    "    );",
    "  } catch (error: any) {",
    "    setText(sessionWorkspaceStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    sessionWorkspaceAction.disabled = false;",
    "  }",
    "}",
    "",
    "async function runSessionWorkspaceApprovalAction(kind, decision, identifier) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(sessionWorkspaceStatus, 'Valide o token antes de decidir approvals da sessao.');",
    "    return;",
    "  }",
    "  if (!identifier) {",
    "    setText(sessionWorkspaceStatus, 'Approval sem identificador valido.');",
    "    return;",
    "  }",
    "",
    "  try {",
    "    if (kind !== 'permission' && kind !== 'task') {",
    "      setText(sessionWorkspaceStatus, 'Tipo de approval nao suportado no shell.');",
    "      return;",
    "    }",
    "    const body = {",
    "      approvalId: identifier,",
    "      decision,",
    "      sessionId: readSessionWorkspaceSessionId() || undefined,",
    "      scope: 'once',",
    "    };",
    "    if (decision === 'approve') {",
    "      const approvalCode = window.prompt('Se esta approval exigir PIN, informe agora. Pode deixar em branco.', '') || '';",
    "      if (approvalCode) {",
    "        body.approvalCode = approvalCode;",
    "      }",
    "    }",
    "    setText(sessionWorkspaceStatus, (decision === 'approve' ? 'Aprovando' : 'Rejeitando') + ' approval pendente...');",
    "    if (gatewayControlSocket instanceof WebSocket && gatewayControlSocket.readyState === WebSocket.OPEN) {",
    "      await requestGatewayControlSocket('approval.resolve', body);",
    "    } else if (kind === 'permission') {",
    "      await postProtectedJson(",
    "        '/api/web/permissions/' + (decision === 'approve' ? 'approve' : 'reject'),",
    "        token,",
    "        {",
    "          permissionId: identifier,",
    "          sessionId: readSessionWorkspaceSessionId() || undefined,",
    "        },",
    "      );",
    "    } else {",
    "      await postProtectedJson(",
    "        '/api/web/tasks/' + (decision === 'approve' ? 'approve' : 'reject'),",
    "        token,",
    "        {",
    "          taskId: identifier,",
    "          sessionId: readSessionWorkspaceSessionId() || undefined,",
    "          approvalCode: body.approvalCode,",
    "        },",
    "      );",
    "    }",
    "",
    "    const payload = await refreshSessionWorkspaceViaGateway(token, readSessionWorkspaceSessionId(), {",
    "      replayMode: 'full',",
    "    });",
    "    renderSessionWorkspace(payload);",
    "    setText(",
    "      sessionWorkspaceStatus,",
    "      decision === 'approve'",
    "        ? 'Approval registrada e workspace atualizado.'",
    "        : 'Rejeicao registrada e workspace atualizado.',",
    "    );",
    "  } catch (error: any) {",
    "    setText(sessionWorkspaceStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSessionWorkspaceToolDiffAction(runId) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(sessionWorkspaceStatus, 'Valide o token antes de revisar diff de tool run.');",
    "    return;",
    "  }",
    "  const sessionId = readSessionWorkspaceSessionId();",
    "  if (!sessionId) {",
    "    setText(sessionWorkspaceStatus, 'Sessao ativa indisponivel para revisar diff.');",
    "    return;",
    "  }",
    "  const normalizedRunId = normalizeText(runId);",
    "  if (!normalizedRunId) {",
    "    setText(sessionWorkspaceStatus, 'Tool run sem identificador valido.');",
    "    return;",
    "  }",
    "",
    "  try {",
    "    setText(sessionWorkspaceStatus, 'Carregando diff do tool run...');",
    "    const payload = gatewayControlSocket instanceof WebSocket && gatewayControlSocket.readyState === WebSocket.OPEN",
    "      ? await requestGatewayControlSocket('artifact.diff', {",
    "          sessionId,",
    "          toolRunId: normalizedRunId,",
    "        })",
    "      : await fetchProtectedJsonOptional(",
    "          '/api/web/tool-runs/' + encodeURIComponent(normalizedRunId) + '/diff?sessionId=' + encodeURIComponent(sessionId),",
    "          token,",
    "        );",
    "    if (!payload?.ok) {",
    "      throw new Error(payload?.error || 'Nao foi possivel carregar o diff deste tool run.');",
    "    }",
    "    const currentToolRuns = readSessionWorkspaceToolRuns(sessionWorkspaceData.state, sessionWorkspaceData.toolRuns);",
    "    renderList(sessionWorkspaceDiffs, [",
    "      '<strong>Diff de ' + escapeHtml(normalizedRunId) + '</strong>',",
    "      ...buildSessionToolDiffPreview(payload),",
    "      ...buildSessionWorkspaceDiffItems(currentToolRuns).slice(0, 3),",
    "    ]);",
    "    setText(sessionWorkspaceDiffsState, 'Diff carregado');",
    "    setText(",
    "      sessionWorkspaceDiffsSummary,",
    "      'Mostrando patch consolidado deste tool run. Atualize o workspace para voltar ao resumo completo.',",
    "    );",
    "    setText(sessionWorkspaceStatus, 'Diff do tool run carregado.');",
    "  } catch (error: any) {",
    "    setText(sessionWorkspaceStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSessionWorkspaceCompanionAction(companionId, actionId, requiresApproval = false) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(sessionWorkspaceStatus, 'Valide o token antes de operar companions deste host.');",
    "    return;",
    "  }",
    "  const normalizedCompanionId = normalizeText(companionId);",
    "  const normalizedActionId = normalizeText(actionId);",
    "  if (!normalizedCompanionId || !normalizedActionId) {",
    "    setText(sessionWorkspaceStatus, 'Companion action invalida para este workspace.');",
    "    return;",
    "  }",
    "",
    "  try {",
    "    setText(",
    "      sessionWorkspaceStatus,",
    "      'Executando acao supervisionada em ' + normalizedCompanionId + '...',",
    "    );",
    "    const payload = await postProtectedJson(",
    "      '/api/web/runtime/companions/' + encodeURIComponent(normalizedCompanionId) + '/actions',",
    "      token,",
    "      {",
    "        actionId: normalizedActionId,",
    "        requestedBy: 'web-operator',",
    "        dryRun: false,",
    "        force: requiresApproval === true ? false : undefined,",
    "      },",
    "    );",
    "    const result = payload?.result || payload;",
    "    const refreshed = await refreshSessionWorkspaceViaGateway(token, readSessionWorkspaceSessionId(), {",
    "      replayMode: 'full',",
    "    });",
    "    renderSessionWorkspace(refreshed);",
    "    setText(",
    "      sessionWorkspaceStatus,",
    "      normalizeText(result?.summary || result?.reason || payload?.error)",
    "        || ('Acao ' + normalizedActionId + ' enviada para ' + normalizedCompanionId + '.'),",
    "    );",
    "  } catch (error: any) {",
    "    setText(sessionWorkspaceStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSessionWorkspaceSwitchAction(nextSessionId) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  const normalizedSessionId = normalizeText(nextSessionId);",
    "  if (!token || !normalizedSessionId) {",
    "    setText(sessionWorkspaceStatus, 'Sessao alvo invalida para reidratacao.');",
    "    return;",
    "  }",
    "",
    "  try {",
    "    setText(sessionWorkspaceStatus, 'Reidratando a sessao selecionada pelo Gateway...');",
    "    const payload = await refreshSessionWorkspaceViaGateway(token, normalizedSessionId, {",
    "      activate: true,",
    "      replayMode: 'full',",
    "    });",
    "    renderSessionWorkspace(payload);",
    "    gatewayControlSocketSessionId = normalizedSessionId;",
    "    setText(sessionWorkspaceStatus, 'Sessao reidratada sem recarregar a pagina.');",
    "  } catch (error: any) {",
    "    setText(sessionWorkspaceStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "function buildReplayComparePrompt(replay) {",
    "  const timeline = Array.isArray(replay?.timeline) ? replay.timeline : [];",
    "  if (timeline.length === 0) {",
    "    return 'Compare o contexto das execucoes recentes e aponte o que precisa ser retomado agora.';",
    "  }",
    "  const labels = timeline",
    "    .slice(0, 4)",
    "    .map((step) => normalizeText(step?.label || step?.id || step?.summary))",
    "    .filter(Boolean)",
    "    .join(' | ');",
    "  return 'Compare estes runs recentes: ' + labels + '. Foque em diferencas, entrega principal e proximo passo.';",
    "}",
    "",
    "async function runSessionWorkspaceReplayAction(action, promptValue, summaryValue) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(sessionWorkspaceStatus, 'Valide o token antes de operar replay e artifacts.');",
    "    return;",
    "  }",
    "  const sessionId = readSessionWorkspaceSessionId();",
    "  if (!sessionId) {",
    "    setText(sessionWorkspaceStatus, 'Sessao ativa indisponivel para replay.');",
    "    return;",
    "  }",
    "",
    "  const replay = sessionWorkspaceData?.history?.session?.replay || null;",
    "  let seedMessage = '';",
    "  if (action === 'compare-runs') {",
    "    seedMessage = normalizeText(promptValue) || buildReplayComparePrompt(replay);",
    "  } else if (action === 'resume-artifact') {",
    "    const label = normalizeText(promptValue || 'artefato recente');",
    "    const summary = normalizeText(summaryValue);",
    "    seedMessage = ('Retome a partir do artefato ' + label + '. ' + (summary ? ('Contexto: ' + summary + '.') : '')).trim();",
    "  } else if (action === 'resume-recommended') {",
    "    seedMessage = normalizeText(promptValue)",
    "      || normalizeText(replay?.recommendedEntry?.prompt)",
    "      || normalizeText(sessionWorkspaceData?.history?.session?.handoff?.handoffPrompt)",
    "      || 'Retome o contexto principal e entregue o proximo passo sugerido.';",
    "  } else {",
    "    setText(sessionWorkspaceStatus, 'Acao de replay nao reconhecida.');",
    "    return;",
    "  }",
    "",
    "  const edited = window.prompt('Edite o prompt de retomada se quiser:', seedMessage);",
    "  if (edited === null) {",
    "    return;",
    "  }",
    "  const finalMessage = String(edited || '').trim();",
    "  if (!finalMessage) {",
    "    setText(sessionWorkspaceStatus, 'Prompt vazio; nada foi enviado.');",
    "    return;",
    "  }",
    "",
    "  try {",
    "    setText(sessionWorkspaceStatus, 'Abrindo nova sessao a partir do replay...');",
    "    const payload = await postProtectedJson('/api/web/gateway/sessions/spawn', token, {",
    "      sessionId,",
    "      message: finalMessage,",
    "      platform: 'web',",
    "    });",
    "    const newSessionId = normalizeText(payload?.spawn?.sessionId || payload?.sessionId);",
    "    setText(",
    "      sessionWorkspaceStatus,",
    "      newSessionId",
    "        ? ('Sessao nova aberta: ' + newSessionId + '.')",
    "        : 'Sessao nova aberta a partir do replay.',",
    "    );",
    "    const refreshed = await fetchSessionWorkspacePayload(token);",
    "    renderSessionWorkspace(refreshed);",
    "  } catch (error: any) {",
    "    setText(sessionWorkspaceStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runLearningAction(actionId, candidateId) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(learningStatus, 'Valide o token antes de decidir candidates do learning plane.');",
    "    return;",
    "  }",
    "  if (!candidateId || !actionId) {",
    "    setText(learningStatus, 'Candidate ou acao invalida para o learning plane.');",
    "    return;",
    "  }",
    "",
    "  setText(learningStatus, 'Aplicando ' + actionId + ' em ' + candidateId + '...');",
    "  try {",
    "    const payload = await postProtectedJson('/api/web/learning/actions', token, {",
    "      candidateId,",
    "      actionId,",
    "    });",
    "    await refreshProtectedShellState(token);",
    "    setText(",
    "      learningStatus,",
    "      pickFirstText([",
    "        payload?.execution?.summary,",
    "        'Learning atualizado com sucesso.',",
    "      ], 'Learning atualizado com sucesso.'),",
    "    );",
    "  } catch (error: any) {",
    "    setText(learningStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runLayeredMemorySearch(options = {}) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(memoryLayeredStatus, 'Valide o token antes de buscar na layered memory.');",
    "    return;",
    "  }",
    "  const query = normalizeText(options.query || memoryLayeredQuery?.value);",
    "  learningMemoryData.lastQuery = query;",
    "  if (!query) {",
    "    renderLayeredMemorySearchResults(null);",
    "    setText(memoryLayeredStatus, 'Informe uma busca curta para consultar episodios, fatos e procedimentos.');",
    "    return;",
    "  }",
    "",
    "  if (memoryLayeredSearchAction instanceof HTMLButtonElement) {",
    "    memoryLayeredSearchAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(memoryLayeredStatus, 'Buscando recall em episodic, semantic e procedural memory...');",
    "    const payload = await fetchProtectedJsonOptional(",
    "      '/api/web/memory/search?q=' + encodeURIComponent(query),",
    "      token,",
    "    );",
    "    renderLayeredMemorySearchResults(payload?.search || null);",
    "    setText(",
    "      memoryLayeredStatus,",
    "      'Busca concluida para \"' + query + '\" com ' + String(Number(payload?.search?.total || 0)) + ' resultado(s).',",
    "    );",
    "  } catch (error: any) {",
    "    setText(memoryLayeredStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (memoryLayeredSearchAction instanceof HTMLButtonElement) {",
    "      memoryLayeredSearchAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshLearningMemoryPanels() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(learningStatus, 'Valide o token antes de atualizar learning e memoria.');",
    "    setText(memoryLayeredStatus, 'Valide o token antes de atualizar learning e memoria.');",
    "    return;",
    "  }",
    "",
    "  if (learningRefreshAction instanceof HTMLButtonElement) {",
    "    learningRefreshAction.disabled = true;",
    "  }",
    "  if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {",
    "    memoryLayeredRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(learningStatus, 'Atualizando learning, budgets e procedimentos...');",
    "    setText(memoryLayeredStatus, 'Atualizando learning, budgets e procedimentos...');",
    "    await refreshProtectedShellState(token);",
    "    if (normalizeText(memoryLayeredQuery?.value || learningMemoryData.lastQuery)) {",
    "      await runLayeredMemorySearch({",
    "        query: normalizeText(memoryLayeredQuery?.value || learningMemoryData.lastQuery),",
    "      });",
    "    }",
    "  } catch (error: any) {",
    "    const message = error instanceof Error ? error.message : String(error);",
    "    setText(learningStatus, message);",
    "    setText(memoryLayeredStatus, message);",
    "  } finally {",
    "    if (learningRefreshAction instanceof HTMLButtonElement) {",
    "      learningRefreshAction.disabled = false;",
    "    }",
    "    if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {",
    "      memoryLayeredRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installSessionWorkspaceInteractions() {",
    "  if (sessionWorkspaceAction instanceof HTMLButtonElement) {",
    "    sessionWorkspaceAction.addEventListener('click', () => {",
    "      void runSessionWorkspaceAction();",
    "    });",
    "  }",
    "",
    "  if (sessionWorkspaceCard instanceof HTMLElement) {",
    "    sessionWorkspaceCard.addEventListener('click', (event) => {",
    "      if (!(event.target instanceof Element)) {",
    "        return;",
    "      }",
    "      const copyButton = event.target.closest('[data-operational-copy]');",
    "      if (copyButton instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        const value = normalizeText(copyButton.dataset.operationalCopy);",
    "        if (value) {",
    "          void copyTextWithFallback(value, 'Copie o comando abaixo:');",
    "        }",
    "        return;",
    "      }",
    "      const selectorButton = event.target.closest('[data-operational-kind=\"session-workspace\"][data-operational-action=\"select\"]');",
    "      if (selectorButton instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        void runSessionWorkspaceSwitchAction(",
    "          normalizeText(selectorButton.dataset.operationalTarget),",
    "        );",
    "        return;",
    "      }",
    "      const toolDiffButton = event.target.closest('[data-session-tool-diff]');",
    "      if (toolDiffButton instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        void runSessionWorkspaceToolDiffAction(",
    "          normalizeText(toolDiffButton.dataset.sessionToolDiff),",
    "        );",
    "        return;",
    "      }",
    "      const companionActionButton = event.target.closest('[data-session-companion-id][data-session-companion-action]');",
    "      if (companionActionButton instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        void runSessionWorkspaceCompanionAction(",
    "          normalizeText(companionActionButton.dataset.sessionCompanionId),",
    "          normalizeText(companionActionButton.dataset.sessionCompanionAction),",
    "          normalizeText(companionActionButton.dataset.sessionCompanionApproval) === 'true',",
    "        );",
    "        return;",
    "      }",
    "      const replayButton = event.target.closest('[data-session-replay-action]');",
    "      if (replayButton instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        void runSessionWorkspaceReplayAction(",
    "          normalizeText(replayButton.dataset.sessionReplayAction),",
    "          normalizeText(replayButton.dataset.sessionReplayPrompt),",
    "          normalizeText(replayButton.dataset.sessionReplaySummary),",
    "        );",
    "        return;",
    "      }",
    "      const button = event.target.closest('[data-session-approval-kind]');",
    "      if (!(button instanceof HTMLButtonElement)) {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runSessionWorkspaceApprovalAction(",
    "        normalizeText(button.dataset.sessionApprovalKind),",
    "        normalizeText(button.dataset.sessionApprovalDecision),",
    "        normalizeText(button.dataset.sessionApprovalId),",
    "      );",
    "    });",
    "  }",
    "}",
    "",
    "function installLearningMemoryInteractions() {",
    "  if (learningRefreshAction instanceof HTMLButtonElement) {",
    "    learningRefreshAction.addEventListener('click', () => {",
    "      void refreshLearningMemoryPanels();",
    "    });",
    "  }",
    "",
    "  if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {",
    "    memoryLayeredRefreshAction.addEventListener('click', () => {",
    "      void refreshLearningMemoryPanels();",
    "    });",
    "  }",
    "",
    "  if (memoryLayeredSearchAction instanceof HTMLButtonElement) {",
    "    memoryLayeredSearchAction.addEventListener('click', () => {",
    "      void runLayeredMemorySearch();",
    "    });",
    "  }",
    "",
    "  if (memoryLayeredQuery instanceof HTMLInputElement) {",
].join('\n');
