export const runtimeShellScriptPart2Seg1: string = [
    "      learningDetails,",
    "      items.length > 0",
    "        ? (metricSummary ? [metricSummary, ...items] : items)",
    "        : ['No candidate elegivel foi derivado das runs recentes.'],",
    "    );",
    "  }",
    "",
    "  if (!layeredMemory) {",
    "    setText(memoryLayeredState, 'Unavailable');",
    "    setText(memoryLayeredSummary, 'Protected layered memory unavailable in this runtime.');",
    "    setText(memoryLayeredStatus, 'Validate the token para carregar budgets e procedimentos.');",
    "    renderList(memoryLayeredDetails, ['The current runtime did not return any layered memory snapshot.']);",
    "    renderList(memoryLayeredSearchResults, ['Memory search becomes available when the protected runtime exposes layered memory.']);",
    "  } else {",
    "    const memorySummary = layeredMemory.summary || {};",
    "    const memoryBudgets = layeredMemory.budgets || {};",
    "    const memoryMetricsSummary = layeredMemoryMetrics?.summary || null;",
    "    const memoryItems = Array.isArray(procedures?.data)",
    "      - procedures.data.slice(0, 3).map((procedure) => {",
    "        const steps = Array.isArray(procedure?.steps) ? procedure.steps.slice(0, 2) : [];",
    "        return '<strong>' + escapeHtml(procedure?.label || procedure?.id || 'Procedimento') + ':</strong> '",
    "          + escapeHtml(procedure?.summary || 'No summary.')",
    "          + ' <span class=\"muted-inline\">['",
    "          + escapeHtml(procedure?.memoryLayer || 'procedural')",
    "          + ' | score '",
    "          + escapeHtml(Number(procedure?.confidence || 0).toFixed(3))",
    "          + ']</span>'",
    "          + (steps.length > 0",
    "            - '<br><span class=\"muted-inline\">' + steps.map((step) => escapeHtml(step)).join(' -> ') + '</span>'",
    "            : '');",
    "      })",
    "      : [];",
    "",
    "    setText(",
    "      memoryLayeredState,",
    "      String((memoryMetricsSummary?.totalEntries ?? memorySummary.total) || 0) + ' recall(s) | '",
    "        + String((memoryMetricsSummary?.procedural ?? memorySummary.procedural) || 0) + ' procedural',",
    "    );",
    "    setText(",
    "      memoryLayeredSummary,",
    "      pickFirstText([",
    "        layeredMemory?.narrative?.operatorSummary,",
    "        layeredMemory?.narrative?.headline,",
    "      ], 'Layered memory loaded.'),",
    "    );",
    "    setText(",
    "      memoryLayeredStatus,",
    "      'Budget por camada ' + String(memoryBudgets.perLayer || 0)",
    "        + ' | episodic ' + String(memorySummary.episodic || 0)",
    "        + ' | semantic ' + String(memorySummary.semantic || 0)",
    "        + ' | procedural ' + String(memorySummary.procedural || 0)",
    "        + (memoryMetricsSummary",
    "          - ' | pressure ' + String(memoryMetricsSummary.pressure || 'ok')",
    "            + ' | usage medio ' + String(Number(memoryMetricsSummary.averageBudgetUsage || 0).toFixed(3))",
    "          : '')",
    "        + '.',",
    "    );",
    "    const memoryMetricLine = layeredMemoryMetrics",
    "      - '<strong>Budgets:</strong> episodic '",
    "        + escapeHtml(String(Number(layeredMemoryMetrics.budgets?.episodicUsage || 0).toFixed(3)))",
    "        + ' | semantic '",
    "        + escapeHtml(String(Number(layeredMemoryMetrics.budgets?.semanticUsage || 0).toFixed(3)))",
    "        + ' | procedural '",
    "        + escapeHtml(String(Number(layeredMemoryMetrics.budgets?.proceduralUsage || 0).toFixed(3)))",
    "      : '';",
    "    renderList(",
    "      memoryLayeredDetails,",
    "      memoryItems.length > 0",
    "        ? (memoryMetricLine ? [memoryMetricLine, ...memoryItems] : memoryItems)",
    "        : ['No consolidated procedure has appeared in procedural memory yet.'],",
    "    );",
    "    if (!learningMemoryData.search) {",
    "      renderList(",
    "        memoryLayeredSearchResults,",
    "        ['Use the search above to query episodes, facts, and procedures by layer.'],",
    "      );",
    "    } else {",
    "      renderLayeredMemorySearchResults(learningMemoryData.search);",
    "    }",
    "  }",
    "",
    "  if (!opsQuality) {",
    "    setText(opsQualityState, 'Unavailable');",
    "    setText(opsQualitySummary, 'Protected quality gate unavailable in this runtime.');",
    "    setText(opsQualityStatus, 'Validate the token to review score, readiness, and memory pressure.');",
    "    renderList(opsQualityDetails, ['The current runtime did not return the ops quality snapshot.']);",
    "    return;",
    "  }",
    "",
    "  setText(",
    "    opsQualityState,",
    "    String(opsQuality?.gate?.state || (opsQuality.healthy ? 'pass' : 'block')).toUpperCase()",
    "      + ' | score '",
    "      + String(Number(opsQuality.score || 0).toFixed(3)),",
    "  );",
    "  setText(",
    "    opsQualitySummary,",
    "    pickFirstText([",
    "      opsQuality?.gate?.nextStep,",
    "      opsQuality?.summary?.recoveryState === 'ready'",
    "        - 'Runtime in recovery state ready to keep learning with active gate.'",
    "        : 'Runtime with degraded recovery state; review bottlenecks before promoting new capabilities.',",
    "    ], 'Ops quality loaded.'),",
    "  );",
    "  setText(",
    "    opsQualityStatus,",
    "    'Promotes ' + String(opsQuality?.gate?.allowsPromotion ? 'yes' : 'no')",
    "      + ' | publishes ' + String(opsQuality?.gate?.allowsPublishing ? 'yes' : 'no')",
    "      + ' | pending de learning ' + String(opsQuality?.summary?.learningPending || 0)",
    "      + ' | itens quarantined ' + String(opsQuality?.summary?.quarantinedItems || 0)",
    "      + ' | memory pressure ' + String(opsQuality?.summary?.memoryPressure || 'ok') + '.',",
    "  );",
    "  renderList(",
    "    opsQualityDetails,",
    "    [",
    "      '<strong>Gate:</strong> ' + escapeHtml(String(opsQuality?.gate?.state || 'n/d'))",
    "        + ' | promotes=' + escapeHtml(String(opsQuality?.gate?.allowsPromotion ? 'yes' : 'no'))",
    "        + ' | publishes=' + escapeHtml(String(opsQuality?.gate?.allowsPublishing ? 'yes' : 'no')),",
    "      '<strong>Operations:</strong> uptime ' + escapeHtml(String(opsQuality?.operations?.uptime || 0))",
    "        + 's | db ' + escapeHtml(String(opsQuality?.operations?.components?.database || 'n/d'))",
    "        + ' | eventBus ' + escapeHtml(String(opsQuality?.operations?.components?.eventBus || 'n/d')),",
    "      '<strong>Learning:</strong> total ' + escapeHtml(String(opsQuality?.learning?.totalCandidates || 0))",
    "        + ' | promovidos ' + escapeHtml(String(opsQuality?.learning?.promotedRate || 0))",
    "        + ' | score medio ' + escapeHtml(String(opsQuality?.learning?.averageScore || 0)),",
    "      '<strong>Platform:</strong> trusted ' + escapeHtml(String(opsQuality?.platform?.trusted || 0))",
    "        + ' | review ' + escapeHtml(String(opsQuality?.platform?.reviewPending || 0))",
    "        + ' | learned local ' + escapeHtml(String(opsQuality?.platform?.learnedLocal || 0)),",
    "      (Array.isArray(opsQuality?.gate?.blockers) && opsQuality.gate.blockers[0])",
    "        - '<strong>Blocker principal:</strong> ' + escapeHtml(String(opsQuality.gate.blockers[0]))",
    "        : null,",
    "      (Array.isArray(opsQuality?.gate?.warnings) && opsQuality.gate.warnings[0])",
    "        - '<strong>Warning principal:</strong> ' + escapeHtml(String(opsQuality.gate.warnings[0]))",
    "        : null,",
    "    ],",
    "  );",
    "}",
    "",
    "function renderLayeredMemorySearchResults(searchPayload) {",
    "  const query = normalizeText(searchPayload?.query);",
    "  const entries = Array.isArray(searchPayload?.data) ? searchPayload.data : [];",
    "  learningMemoryData.search = searchPayload || null;",
    "  if (!query) {",
    "    renderList(memoryLayeredSearchResults, ['Use the search above to query episodes, facts, and procedures by layer.']);",
    "    return;",
    "  }",
    "  if (entries.length === 0) {",
    "    renderList(memoryLayeredSearchResults, ['No result found for \"' + escapeHtml(query) + '\".']);",
    "    return;",
    "  }",
    "  renderList(",
    "    memoryLayeredSearchResults,",
    "    entries.slice(0, 5).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || entry?.id || 'Memory') + ':</strong> '",
    "      + escapeHtml(entry?.summary || 'No summary.')",
    "      + ' <span class=\"muted-inline\">['",
    "      + escapeHtml(entry?.memoryLayer || 'unknown')",
    "      + ' | conf '",
    "      + escapeHtml(Number(entry?.confidence || 0).toFixed(3))",
    "      + ' | '",
    "      + escapeHtml(entry?.source || 'n/d')",
    "      + ']</span>'",
    "    ),",
    "  );",
    "}",
    "",
    "function formatWorkspaceCount(label, value, fallback = '0') {",
    "  const normalized = Number.isFinite(Number(value)) ? String(Number(value)) : String(value ?? '').trim();",
    "  return '<strong>' + label + ':</strong> ' + (normalized || fallback);",
    "}",
    "",
    "function formatSessionToolList(sessionTools) {",
    "  if (!Array.isArray(sessionTools) || sessionTools.length === 0) {",
    "    return 'without tools canonicamente expostas agora.';",
    "  }",
    "  return sessionTools",
    "    .map((tool) => normalizeText(tool?.id || tool?.name))",
    "    .filter(Boolean)",
    "    .slice(0, 4)",
    "    .join(', ');",
    "}",
    "",
    "function pickFirstText(values, fallback = '') {",
    "  for (const value of values) {",
    "    const normalized = normalizeText(value);",
    "    if (normalized) {",
    "      return normalized;",
    "    }",
    "  }",
    "  return fallback;",
    "}",
    "",
    "function buildOperationalInlineButton(kind, mode, targetId, label) {",
    "  const safeKind = escapeHtml(kind);",
    "  const safeMode = escapeHtml(mode);",
    "  const safeTargetId = escapeHtml(targetId || '');",
    "  const safeLabel = escapeHtml(label);",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action\" data-operational-kind=\"' + safeKind + '\" data-operational-mode=\"' + safeMode + '\" data-target-id=\"' + safeTargetId + '\">' + safeLabel + '</button>';",
    "}",
    "",
    "function buildOperationalSelectorRow(kind, entries, selectedId, readId, readLabel) {",
    "  if (!Array.isArray(entries) || entries.length === 0) {",
    "    return '';",
    "  }",
    "",
    "  const buttons = entries",
    "    .slice(0, 4)",
    "    .map((entry) => {",
    "      const entryId = normalizeText(readId(entry));",
    "      if (!entryId) {",
    "        return '';",
    "      }",
    "      const entryLabel = normalizeText(readLabel(entry)) || entryId;",
    "      const label = entryId === selectedId ? 'Foco: ' + entryLabel : entryLabel;",
    "      return buildOperationalButtonHtml(kind, 'select', label, entryId);",
    "    })",
    "    .filter(Boolean);",
    "  if (buttons.length === 0) {",
    "    return '';",
    "  }",
    "  return '<div class=\"inline-action-row\">' + buttons.join('') + '</div>';",
    "}",
    "",
    "async function fetchNodeOperationalPanel(token, selectedId, includeDoctor = false) {",
    "  const selectedNodeId = normalizeText(selectedId);",
    "  const nodeRoute = selectedNodeId",
    "    - '/api/web/nodes...selectedId=' + encodeURIComponent(selectedNodeId)",
    "    : '/api/web/nodes';",
    "  const requests = [",
    "    fetchProtectedJsonOptional(nodeRoute, token),",
    "    includeDoctor",
    "      - fetchProtectedJsonOptional('/api/web/nodes/doctor', token)",
    "      : Promise.resolve(operationalMeshData.nodeDoctor),",
    "    selectedNodeId",
    "      - fetchProtectedJsonOptional('/api/web/nodes/' + encodeURIComponent(selectedNodeId) + '/activity', token)",
    "      : Promise.resolve(null),",
    "    selectedNodeId",
    "      - fetchProtectedJsonOptional('/api/web/nodes/' + encodeURIComponent(selectedNodeId) + '/capabilities', token)",
    "      : Promise.resolve(null),",
    "    selectedNodeId",
    "      - fetchProtectedJsonOptional('/api/web/nodes/' + encodeURIComponent(selectedNodeId) + '/bootstrap', token)",
    "      : Promise.resolve(null),",
    "  ];",
    "  const [nodeMeshPayload, doctorPayload, activityPayload, capabilitiesPayload, nodeBootstrapPayload] = await Promise.all(requests);",
    "  return {",
    "    nodeMeshPayload,",
    "    doctorPayload,",
    "    activityPayload,",
    "    capabilitiesPayload,",
    "    nodeBootstrapPayload,",
    "  };",
    "}",
    "",
    "async function fetchChannelOperationalPanel(token, selectedId) {",
    "  const selectedChannelId = normalizeText(selectedId);",
    "  const channelRoute = selectedChannelId",
    "    - '/api/web/channels...selectedId=' + encodeURIComponent(selectedChannelId)",
    "    : '/api/web/channels';",
    "  const requests = [",
    "    fetchProtectedJsonOptional(channelRoute, token),",
    "    fetchProtectedJsonOptional(",
    "      '/api/web/channels/install' + (selectedChannelId ? '...selectedId=' + encodeURIComponent(selectedChannelId) : ''),",
    "      token,",
    "    ),",
    "    fetchProtectedJsonOptional(",
    "      '/api/web/channels/doctor',",
    "      token,",
    "      { method: 'POST', body: JSON.stringify({ selectedId: selectedChannelId || undefined }) },",
    "    ),",
    "    fetchProtectedJsonOptional(",
    "      '/api/web/channels/setup-assistant' + (selectedChannelId ? '...channelId=' + encodeURIComponent(selectedChannelId) : ''),",
    "      token,",
    "    ),",
    "    selectedChannelId",
    "      - fetchProtectedJsonOptional('/api/web/channels/' + encodeURIComponent(selectedChannelId), token)",
    "      : Promise.resolve(null),",
    "  ];",
    "  const [channelMeshPayload, channelInstallPayload, channelDoctorPayload, channelAssistantPayload, channelDetailPayload] = await Promise.all(requests);",
    "  return {",
    "    channelMeshPayload,",
    "    channelInstallPayload,",
    "    channelDoctorPayload,",
    "    channelAssistantPayload,",
    "    channelDetailPayload,",
    "  };",
    "}",
    "",
    "async function fetchTransportOperationalPanel(token, selectedId, includeHistory = true) {",
    "  const transportId = normalizeText(selectedId);",
    "  const transportRoute = transportId",
    "    - '/api/web/transports...selectedId=' + encodeURIComponent(transportId)",
    "    : '/api/web/transports';",
    "  const transportPayload = await fetchProtectedJsonOptional(transportRoute, token);",
    "  let historyPayload = null;",
    "  if (includeHistory && transportId) {",
    "    historyPayload = await fetchProtectedJsonOptional('/api/web/transports/' + encodeURIComponent(transportId) + '/history', token);",
    "  }",
    "  return {",
    "    transportPayload,",
    "    historyPayload,",
    "  };",
    "}",
    "",
    "async function fetchExtensionOperationalPanel(token, selectedId) {",
    "  const extensionId = normalizeText(selectedId);",
    "  const route = extensionId",
    "    - '/api/web/workspace/extensions...selectedId=' + encodeURIComponent(extensionId)",
    "    : '/api/web/workspace/extensions';",
    "  const [extensionPayload, pluginsPayload, hooksPayload] = await Promise.all([",
    "    fetchProtectedJsonOptional(route, token),",
    "    fetchProtectedJsonOptional('/api/web/plugins', token),",
    "    fetchProtectedJsonOptional('/api/web/hooks', token),",
    "  ]);",
    "  return {",
    "    extensionPayload,",
    "    pluginsPayload,",
    "    hooksPayload,",
    "  };",
    "}",
    "",
    "function parseOperationalIdList(rawValue) {",
    "  return String(rawValue || '')",
    "    .split(/[\\r\\n,;]+/)",
    "    .map((entry) => normalizeText(entry))",
    "    .filter(Boolean);",
    "}",
    "",
    "function parseOperationalEnvEntries(rawValue) {",
    "  return String(rawValue || '')",
    "    .split(/\\r...\\n/)",
    "    .map((line) => String(line || '').trim())",
    "    .filter((line) => Boolean(line) && !line.startsWith('#'))",
    "    .map((line) => {",
    "      const separatorIndex = line.indexOf('=');",
    "      if (separatorIndex < 0) {",
    "        return null;",
    "      }",
    "      const key = normalizeText(line.slice(0, separatorIndex));",
    "      const value = line.slice(separatorIndex + 1);",
    "      if (!key) {",
    "        return null;",
    "      }",
    "      return {",
    "        key,",
    "        value,",
    "        overwrite: true,",
    "      };",
    "    })",
    "    .filter(Boolean);",
    "}",
    "",
    "async function fetchChannelInstallPlan(token, channelId, mode = '') {",
    "  const selectedChannelId = normalizeText(channelId);",
    "  const selectedMode = normalizeText(mode);",
    "  if (!selectedChannelId) {",
    "    return null;",
    "  }",
    "  const query = '...selectedId=' + encodeURIComponent(selectedChannelId)",
    "    + (selectedMode ? '&mode=' + encodeURIComponent(selectedMode) : '');",
    "  return fetchProtectedJsonOptional('/api/web/channels/install' + query, token);",
    "}",
    "",
    "async function fetchChannelSetupAssistant(token, channelId, mode = '') {",
    "  const selectedChannelId = normalizeText(channelId);",
    "  const selectedMode = normalizeText(mode);",
    "  if (!selectedChannelId) {",
    "    return null;",
    "  }",
    "  const query = '...channelId=' + encodeURIComponent(selectedChannelId)",
    "    + (selectedMode ? '&mode=' + encodeURIComponent(selectedMode) : '');",
    "  return fetchProtectedJsonOptional('/api/web/channels/setup-assistant' + query, token);",
    "}",
    "",
    "function buildNodeCapabilityEntries(selected, capabilities) {",
    "  const descriptorList = Array.isArray(capabilities?.capabilities) ? capabilities.capabilities : [];",
    "  const descriptorMap = new Map(",
    "    descriptorList",
    "      .map((entry) => [normalizeText(entry?.id), entry])",
    "      .filter(([id]) => Boolean(id)),",
    "  );",
    "  const declaredIds = Array.isArray(selected?.capabilityIds)",
    "    - selected.capabilityIds.map((entry) => normalizeText(entry)).filter(Boolean)",
    "    : [];",
    "  const fallbackIds = Array.from(descriptorMap.keys());",
    "  const orderedIds = declaredIds.length > 0 ? declaredIds : fallbackIds;",
    "  return orderedIds.map((id) => {",
    "    const descriptor = descriptorMap.get(id) || null;",
    "    return {",
    "      id,",
    "      label: normalizeText(descriptor?.label || id) || id,",
    "      summary: normalizeText(descriptor?.summary || descriptor?.category || 'Capability declarada on this host.'),",
    "      risky: Boolean(descriptor?.risky),",
    "    };",
    "  });",
    "}",
    "",
    "function buildNodePolicyActionRow(selected, capabilities) {",
    "  const nodeId = normalizeText(selected?.id);",
    "  if (!nodeId) {",
    "    return '';",
    "  }",
    "  const entries = buildNodeCapabilityEntries(selected, capabilities);",
    "  if (entries.length === 0) {",
    "    return '';",
    "  }",
    "  const approvedIds = Array.isArray(selected?.approvedCapabilityIds)",
    "    - selected.approvedCapabilityIds.map((entry) => normalizeText(entry)).filter(Boolean)",
    "    : [];",
    "  const safeIds = entries.filter((entry) => !entry.risky).map((entry) => entry.id);",
    "  const buttons = [",
    "    buildOperationalButtonHtml('nodes', 'policy-all', 'Approve declared', nodeId, entries.map((entry) => entry.id).join(',')),",
    "    safeIds.length > 0",
    "      - buildOperationalButtonHtml('nodes', 'policy-safe', 'Safe only', nodeId, safeIds.join(','))",
    "      : '',",
    "    buildOperationalButtonHtml('nodes', 'policy-clear', 'Clear allowlist', nodeId),",
    "    buildOperationalButtonHtml('nodes', 'policy-custom', 'Edit allowlist', nodeId, approvedIds.join(',')),",
    "  ].filter(Boolean);",
    "  return buildOperationalInlineButtons(buttons);",
    "}",
    "",
    "function resolvePluginFocusEntry(plugins) {",
    "  if (plugins?.selected && Array.isArray(plugins.selected.actions) && plugins.selected.actions.length > 0) {",
    "    return plugins.selected;",
    "  }",
    "  if (!Array.isArray(plugins?.entries)) {",
    "    return null;",
    "  }",
    "  return plugins.entries.find((entry) => Array.isArray(entry?.actions) && entry.actions.length > 0) || null;",
    "}",
    "",
    "function buildExtensionActionRow(selected, plugins) {",
    "  const selectedWorkspace = normalizeText(selected?.workspace || '');",
    "  const primaryHook = Array.isArray(selected?.hooks) && selected.hooks.length > 0 ? selected.hooks[0] : null;",
    "  const pluginFocus = resolvePluginFocusEntry(plugins);",
    "  const pluginButtons = Array.isArray(pluginFocus?.actions)",
    "    - pluginFocus.actions",
    "        .slice(0, 3)",
    "        .map((action) =>",
    "          buildOperationalButtonHtml(",
    "            'extensions',",
    "            'plugin-action',",
    "            normalizeText(action?.label || action?.kind || action?.id || 'Action do plugin'),",
    "            normalizeText(pluginFocus?.id || ''),",
    "            normalizeText(action?.kind || action?.id || ''),",
    "          ),",
    "        )",
    "        .filter(Boolean)",
    "    : [];",
    "  const buttons = [",
    "    buildOperationalButtonHtml('extensions', 'refresh', 'Atualizar catalog', normalizeText(selected?.slug || '')),",
    "    buildOperationalButtonHtml('extensions', 'platform-sync', 'Sincronizar registry', normalizeText(selected?.slug || '')),",
    "    ...pluginButtons,",
    "    selectedWorkspace && normalizeText(primaryHook?.event)",
    "      - buildOperationalButtonHtml('extensions', 'hook-dry-run', 'Dry-run do hook principal', selectedWorkspace, normalizeText(primaryHook?.event))",
    "      : '',",
    "  ].filter(Boolean);",
    "  return buildOperationalInlineButtons(buttons);",
    "}",
    "",
    "function readSessionWorkspaceCounts(statePayload, historyPayload) {",
    "  const snapshot = statePayload?.snapshot || {};",
    "  const session = statePayload?.session || {};",
    "  const historySession = historyPayload?.session || {};",
    "  const replay = historySession?.replay || {};",
    "  const sessionPlane = statePayload?.sessionPlane || historyPayload?.sessionPlane || {};",
    "  const sessionPlaneSummary = sessionPlane?.summary || {};",
    "  const approvalPlane = statePayload?.approvalPlane || {};",
    "  const artifactPlane = statePayload?.artifactPlane || {};",
    "  const workflowRuns = Array.isArray(snapshot?.workflowRuns)",
    "    - snapshot.workflowRuns.length",
    "    : Number(replay?.stats?.workflowRuns || 0);",
    "  const toolRuns = Array.isArray(snapshot?.toolRuns)",
    "    - snapshot.toolRuns.length",
    "    : (Array.isArray(artifactPlane?.toolRuns) ? artifactPlane.toolRuns.length : Number(snapshot?.toolRunCount || 0));",
    "  const filesTouched = Array.isArray(snapshot?.filesTouched)",
    "    - snapshot.filesTouched.length",
    "    : (Array.isArray(artifactPlane?.filesTouched) ? artifactPlane.filesTouched.length : 0);",
    "  return {",
    "    taskCount: Number(snapshot?.taskCount ?? session?.tasksCount ?? historySession?.tasks?.length ?? replay?.stats?.tasks ?? 0) || 0,",
    "    pendingPermissions: Number(",
    "      snapshot?.pendingPermissions",
    "      ?? approvalPlane?.summary?.pending",
    "      ?? session?.permissionsCount",
    "      ?? sessionPlaneSummary?.pendingPermissions",
    "      ?? replay?.stats?.pendingPermissions",
    "      ?? 0,",
    "    ) || 0,",
    "    workflowRuns: Number(workflowRuns || 0) || 0,",
    "    toolRuns: Number(toolRuns || 0) || 0,",
    "    filesTouched: Number(filesTouched || 0) || 0,",
    "    sessionsTotal: Number(historyPayload?.sessionsSummary?.total ?? historyPayload?.sessions?.total ?? sessionPlaneSummary?.sessions ?? 0) || 0,",
    "    linkedSurfaces: Number(",
    "      sessionPlaneSummary?.linkedSurfaces",
    "      ?? (Array.isArray(historySession?.continuity?.linkedSurfaces) ? historySession.continuity.linkedSurfaces.length : 0)",
    "      ?? 0,",
    "    ) || 0,",
    "  };",
    "}",
    "",
    "function buildSessionWorkspaceSessionOptions(statePayload, activeSessionId) {",
    "  const entries = Array.isArray(statePayload?.sessions?.entries) ? statePayload.sessions.entries : [];",
    "  return entries.slice(0, 6).map((entry) => {",
    "    const sessionId = normalizeText(entry?.sessionId || entry?.id);",
    "    const label = normalizeText(entry?.label || entry?.latestTaskLabel || entry?.chatId || sessionId);",
    "    if (!sessionId || !label) {",
    "      return null;",
    "    }",
    "    return {",
    "      id: sessionId,",
    "      label,",
    "      active: sessionId === activeSessionId,",
    "    };",
    "  }).filter(Boolean);",
    "}",
    "",
    "function shortIdentifier(value, fallback = 'item') {",
    "  const normalized = normalizeText(value);",
    "  return normalized ? normalized.slice(0, 8) : fallback;",
    "}",
    "",
    "function buildSessionWorkspacePendingTaskEntries(tasks, permissions) {",
    "  const permissionIds = new Set(",
    "    (Array.isArray(permissions) ? permissions : [])",
    "      .map((entry) => normalizeText(entry?.permission_id))",
    "      .filter(Boolean),",
    "  );",
    "  return (Array.isArray(tasks) ? tasks : []).filter((task) => {",
    "    const approvalStatus = normalizeText(task?.approval_status).toLowerCase();",
    "    const status = normalizeText(task?.status).toLowerCase();",
    "    const pendingPermissionId = normalizeText(task?.pending_permission_id);",
    "    const pendingTask =",
    "      approvalStatus === 'pending'",
    "      || status === 'waiting_approval'",
    "      || (task?.requires_approval === true && !['approved', 'rejected', 'not_required'].includes(approvalStatus));",
    "    return pendingTask && !permissionIds.has(pendingPermissionId);",
    "  });",
    "}",
    "",
    "function buildSessionWorkspaceApprovalItems(permissions, tasks) {",
    "  const pendingPermissions = (Array.isArray(permissions) ? permissions : [])",
    "    .filter((entry) => normalizeText(entry?.status).toLowerCase() === 'pending');",
    "  const pendingTasks = buildSessionWorkspacePendingTaskEntries(tasks, pendingPermissions);",
    "  const items = [];",
    "",
    "  for (const permission of pendingPermissions.slice(0, 2)) {",
    "    const permissionId = normalizeText(permission?.permission_id);",
    "    items.push(",
    "      '<strong>' + escapeHtml(permission?.short_id || shortIdentifier(permissionId, 'perm')) + ':</strong> '",
    "      + escapeHtml(permission?.reason || permission?.kind || 'Pending permission.')",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(permission?.workspace || permission?.executor || 'current scope') + ']</span>'",
    "      + '<div class=\"inline-action-row\">'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-session-approval-kind=\"permission\" data-session-approval-decision=\"approve\" data-session-approval-id=\"' + escapeHtml(permissionId) + '\">Approve</button>'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-session-approval-kind=\"permission\" data-session-approval-decision=\"reject\" data-session-approval-id=\"' + escapeHtml(permissionId) + '\">Reject</button>'",
    "      + '</div>',",
    "    );",
    "  }",
    "",
    "  for (const task of pendingTasks.slice(0, 2)) {",
    "    const taskId = normalizeText(task?.task_id);",
    "    items.push(",
    "      '<strong>' + escapeHtml(shortIdentifier(taskId, 'task')) + ':</strong> '",
    "      + escapeHtml(task?.result_summary || task?.raw_message || task?.command_type || 'Pending task gate.')",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(task?.status || task?.approval_status || 'pending') + ']</span>'",
    "      + '<div class=\"inline-action-row\">'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-session-approval-kind=\"task\" data-session-approval-decision=\"approve\" data-session-approval-id=\"' + escapeHtml(taskId) + '\">Approve</button>'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-session-approval-kind=\"task\" data-session-approval-decision=\"reject\" data-session-approval-id=\"' + escapeHtml(taskId) + '\">Reject</button>'",
    "      + '</div>',",
    "    );",
    "  }",
    "",
    "  return {",
    "    permissions: pendingPermissions.length,",
    "    tasks: pendingTasks.length,",
    "    total: pendingPermissions.length + pendingTasks.length,",
    "    items,",
    "  };",
    "}",
    "",
    "function buildSessionWorkspaceReplayItems(replay, handoff, continuity) {",
    "  const items = [];",
    "  const recommendedEntry = replay?.recommendedEntry || null;",
    "  const recommendedPrompt = pickFirstText([",
    "    recommendedEntry?.prompt,",
    "    handoff?.handoffPrompt,",
    "    continuity?.suggestedAction?.prompt,",
    "  ]);",
    "  if (normalizeText(recommendedEntry?.label) || normalizeText(recommendedEntry?.reason)) {",
    "    items.push(",
    "      '<strong>Better entrada:</strong> '",
    "      + escapeHtml(recommendedEntry?.label || 'resume contexto')",
    "      + (normalizeText(recommendedEntry?.reason) ? ' ? ' + escapeHtml(recommendedEntry.reason) : ''),",
    "    );",
    "  }",
    "  for (const step of (Array.isArray(replay?.timeline) ? replay.timeline : []).slice(0, 3)) {",
    "    items.push(",
    "      '<strong>' + escapeHtml(step?.label || step?.id || 'Evento') + ':</strong> '",
    "      + escapeHtml(step?.detail || step?.summary || step?.source || 'No additional detail.'),",
    "    );",
    "  }",
].join('\n');
