export const runtimeShellScriptPart6Seg1: string = [
    "  if (channelId === 'discord') {",
    "    return 'Discord pede token, policy e primeira pairing approval. Use o wizard para alinhar guilds/canais e depois feche a DM inicial.';",
    "  }",
    "  if (channelId === 'web') {",
    "    return 'Web e a surface principal deste runtime. Use sessions_send e sessions_spawn para abrir novas trilhas sem sair do control plane.';",
    "  }",
    "  return 'Use o wizard oficial para ligar ou promover este canal antes de ampliar rollout no mesh.';",
    "}",
    "",
    "function renderChannelsOperationalCard() {",
    "  const channelMesh = operationalMeshData.channels?.channels || null;",
    "  const detail = operationalMeshData.channelDetail || null;",
    "  const latestAction = operationalMeshData.channelAction?.result || operationalMeshData.channelAction || null;",
    "  const installReport = operationalMeshData.channelInstall?.report || operationalMeshData.channelInstall || null;",
    "  const channelDoctor = operationalMeshData.channelDoctor?.doctor || operationalMeshData.channelDoctor || null;",
    "  const channelAssistant = operationalMeshData.channelAssistant?.assistant || operationalMeshData.channelAssistant || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.channels?.error",
    "    || operationalMeshData.channelDetail?.error",
    "    || operationalMeshData.channelAction?.error",
    "    || operationalMeshData.channelInstall?.error",
    "    || operationalMeshData.channelDoctor?.error",
    "    || operationalMeshData.channelAssistant?.error,",
    "  );",
    "",
    "  if (!channelMesh) {",
    "    setText(opsChannelsState, 'Indisponivel');",
    "    setText(opsChannelsSummary, errorMessage || 'Channel Mesh protegido indisponivel neste runtime.');",
    "    renderList(opsChannelsDetails, [errorMessage || 'Valide o token para revisar readiness, pairing e promocao dos canais sem cair no legado.']);",
    "    hideOperationalAction(opsChannelsAction);",
    "    hideOperationalPanel(opsChannelsPanel, opsChannelsPanelActions, opsChannelsPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = channelMesh.summary || {};",
    "  const selected = detail?.channel || channelMesh.selected || null;",
    "  const registry = detail?.registry || null;",
    "  const selectedId = normalizeText(selected?.id || operationalMeshSelection.channels);",
    "  const selectedLabel = normalizeText(selected?.label || selected?.id || '');",
    "  const selectedSummary = normalizeText(selected?.operatorSummary || selected?.summary || selected?.actionHint);",
    "  const selectedTransport = normalizeText(selected?.transport || registry?.transport || 'unknown');",
    "  const selectedInstallPlan = Array.isArray(installReport?.channels)",
    "    ? installReport.channels.find((entry) => normalizeText(entry?.channelId) === selectedId) || null",
    "    : null;",
    "  const assistantSelected = channelAssistant?.selected || null;",
    "  const assistantStatus = normalizeText(channelAssistant?.status || '');",
    "  const assistantReply = normalizeText(channelAssistant?.naturalReply || '');",
    "  const assistantQuestion = Array.isArray(channelAssistant?.nextQuestions)",
    "    ? normalizeText(channelAssistant.nextQuestions[0] || '')",
    "    : '';",
    "  const assistantAction = Array.isArray(channelAssistant?.nextActions)",
    "    ? channelAssistant.nextActions[0] || null",
    "    : null;",
    "  const doctorItems = Array.isArray(channelDoctor?.items) ? channelDoctor.items : [];",
    "  const selectedDoctor = doctorItems.find((entry) => normalizeText(entry?.channelId) === selectedId) || null;",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'channels',",
    "    Array.isArray(channelMesh.entries) ? channelMesh.entries : [],",
    "    selectedId,",
    "    (entry) => entry?.id,",
    "    (entry) => entry?.label || entry?.id,",
    "  );",
    "  const promotionHint = buildChannelPromotionHint(selected, selectedInstallPlan);",
    "  operationalMeshSelection.channels = selectedId;",
    "",
    "  setText(",
    "    opsChannelsState,",
    "    summary.total",
    "      ? String(summary.ready || 0) + '/' + String(summary.total || 0) + ' prontos'",
    "      : 'Sem canais',",
    "  );",
    "  setText(",
    "    opsChannelsSummary,",
    "    selectedLabel",
    "      ? selectedLabel + ': ' + (selectedSummary || 'sem observacao operacional agora.')",
    "      : summary.total",
    "        ? String(summary.configured || 0) + ' configurado(s), ' + String(summary.partial || 0) + ' parcial(is) e ' + String(summary.planned || 0) + ' planejado(s).'",
    "        : 'Nenhum canal registrado neste host.',",
    "  );",
    "",
    "  const fleetPreview = Array.isArray(channelMesh.entries)",
    "    ? channelMesh.entries.slice(0, 5).map((entry) => {",
    "      const label = normalizeText(entry?.label || entry?.id || 'canal');",
    "      const readiness = normalizeText(entry?.readiness || 'unknown');",
    "      const transport = normalizeText(entry?.transport || 'unknown');",
    "      return escapeHtml(label) + ' [' + escapeHtml(readiness) + '; ' + escapeHtml(transport) + ']';",
    "    }).join(' Ã‚Â· ')",
    "    : '';",
    "  const selectedActions = Array.isArray(selected?.actions) ? selected.actions : [];",
    "  const selectedFeatures = selected?.features || registry?.features || null;",
    "  const featureSummary = selectedFeatures",
    "    ? [",
    "        selectedFeatures.sessionSend ? 'sessions_send' : '',",
    "        selectedFeatures.sessionSpawn ? 'sessions_spawn' : '',",
    "        selectedFeatures.attachments ? 'attachments' : '',",
    "        selectedFeatures.threads ? 'threads' : '',",
    "        selectedFeatures.groupPolicy ? 'group-policy' : '',",
    "      ].filter(Boolean).join(', ')",
    "    : '';",
    "  const latestActionSummary = pickFirstText([",
    "    latestAction?.summary,",
    "    Array.isArray(latestAction?.details) ? latestAction.details[0] : '',",
    "  ]);",
    "  const installSummary = selectedInstallPlan",
    "    ? [",
    "        'modo atual ' + normalizeText(selectedInstallPlan.currentMode || 'nao configurado'),",
    "        'recomendado ' + normalizeText(selectedInstallPlan.recommendedMode || 'n/a'),",
    "      ].join(' | ')",
    "    : '';",
    "  const doctorSummary = pickFirstText([",
    "    selectedDoctor?.summary,",
    "    channelDoctor?.summary,",
    "  ]);",
    "  const assistantSummary = pickFirstText([",
    "    assistantReply,",
    "    assistantSelected?.operatorNextStep,",
    "    assistantQuestion,",
    "  ]);",
    "  const modeButtons = selectedInstallPlan && Array.isArray(selectedInstallPlan.modes)",
    "    ? selectedInstallPlan.modes.slice(0, 4).map((mode) => {",
    "        const normalizedMode = normalizeText(mode);",
    "        const label = normalizedMode === normalizeText(selectedInstallPlan.currentMode)",
    "          ? 'Reaplicar ' + normalizedMode",
    "          : normalizedMode === normalizeText(selectedInstallPlan.recommendedMode)",
    "            ? 'Promover: ' + normalizedMode",
    "            : 'Usar ' + normalizedMode;",
    "        return buildOperationalButtonHtml('channels', 'channel-apply-mode', label, selectedId, normalizedMode);",
    "      })",
    "    : [];",
    "  const modeConfigButtons = selectedInstallPlan && Array.isArray(selectedInstallPlan.modes)",
    "    ? selectedInstallPlan.modes.slice(0, 4).map((mode) => {",
    "        const normalizedMode = normalizeText(mode);",
    "        const label = normalizedMode === normalizeText(selectedInstallPlan.currentMode)",
    "          ? 'Editar ' + normalizedMode",
    "          : 'Configurar ' + normalizedMode;",
    "        return buildOperationalButtonHtml('channels', 'channel-configure-mode', label, selectedId, normalizedMode);",
    "      })",
    "    : [];",
    "",
    "  const items = operationalMeshExpanded.channels",
    "    ? [",
    "        fleetPreview",
    "          ? '<strong>Frota visivel:</strong> ' + fleetPreview",
    "          : '<strong>Frota visivel:</strong> nenhum canal registrado agora.',",
    "        selectedLabel",
    "          ? '<strong>Foco:</strong> ' + escapeHtml(selectedLabel) + ' [' + escapeHtml(normalizeText(selected?.readiness || 'unknown')) + '; ' + escapeHtml(selectedTransport) + ']'",
    "          : '<strong>Foco:</strong> nenhum canal selecionado agora.',",
    "        selectedSummary",
    "          ? '<strong>Status:</strong> ' + escapeHtml(selectedSummary)",
    "          : '<strong>Status:</strong> sem observacao operacional agora.',",
    "        selected?.actionHint",
    "          ? '<strong>Proximo passo:</strong> ' + escapeHtml(normalizeText(selected.actionHint))",
    "          : '<strong>Proximo passo:</strong> sem hint operacional para este canal.',",
    "        featureSummary",
    "          ? '<strong>Surface disponivel:</strong> ' + escapeHtml(featureSummary)",
    "          : '<strong>Surface disponivel:</strong> sem features registradas neste foco.',",
    "        selectorRow",
    "          ? '<strong>Alternar foco:</strong> ' + selectorRow",
    "          : '<strong>Alternar foco:</strong> nenhum canal registrado agora.',",
    "        latestActionSummary",
    "          ? '<strong>Ultima acao:</strong> ' + escapeHtml(latestActionSummary)",
    "          : '<strong>Ultima acao:</strong> nenhuma acao operacional rodada nesta sessao do shell.',",
    "        installSummary",
    "          ? '<strong>Scaffold:</strong> ' + escapeHtml(installSummary)",
    "          : '<strong>Scaffold:</strong> use <code>npm run setup:channels</code> para gerar o plano deste canal.',",
    "        assistantSummary",
    "          ? '<strong>Assistente:</strong> ' + escapeHtml(assistantSummary)",
    "          : '<strong>Assistente:</strong> abra o assistente para receber o proximo passo em linguagem natural.',",
    "        doctorSummary",
    "          ? '<strong>Doctor:</strong> ' + escapeHtml(doctorSummary)",
    "          : '<strong>Doctor:</strong> rode o doctor do canal para validar o modo atual neste host.',",
    "        '<strong>Promocao:</strong> ' + escapeHtml(promotionHint),",
    "      ]",
    "    : [",
    "        selectedLabel",
    "          ? '<strong>Foco:</strong> ' + escapeHtml(selectedLabel) + ' - ' + escapeHtml(selectedSummary || promotionHint)",
    "          : '<strong>Configurados:</strong> ' + String(summary.configured || 0) + ' de ' + String(summary.total || 0) + '.',",
    "        '<strong>Setup guiado:</strong> use <code>npm run setup:channels</code> para ligar ou promover canais sem editar env manualmente.',",
    "        assistantSummary",
    "          ? '<strong>Assistente:</strong> ' + escapeHtml(assistantSummary)",
    "          : '<strong>Assistente:</strong> abra o painel para receber modo, variaveis e proximo passo.',",
    "      ];",
    "  renderList(opsChannelsDetails, items);",
    "",
    "  if (operationalMeshExpanded.channels) {",
    "    const panelButtons = [",
    "      buildOperationalCopyButtonHtml('Copiar setup guiado', 'npm run setup:channels'),",
    "      buildOperationalCopyButtonHtml(",
    "        'Copiar assistente CLI',",
    "        'npm run channels:assistant -- --channel ' + selectedId,",
    "      ),",
    "      buildOperationalButtonHtml('channels', 'channel-assistant', 'Abrir assistente', selectedId),",
    "      buildOperationalButtonHtml(",
    "        'channels',",
    "        'channel-assistant-apply',",
    "        assistantStatus === 'needs_scaffold' ? 'Aplicar assistente' : 'Reaplicar scaffold seguro',",
    "        selectedId,",
    "        normalizeText(assistantSelected?.setupMode || selectedInstallPlan?.currentMode || selectedInstallPlan?.recommendedMode || ''),",
    "      ),",
    "      buildOperationalButtonHtml('channels', 'channel-assistant-doctor', 'Doctor assistido', selectedId),",
    "      buildOperationalButtonHtml('channels', 'channels-doctor', 'Rodar doctor', selectedId),",
    "      ...selectedActions.slice(0, 4).map((entry) =>",
    "        buildOperationalButtonHtml(",
    "          'channels',",
    "          'channel-action',",
    "          normalizeText(entry?.label || entry?.kind || entry?.id || 'Acao'),",
    "          selectedId,",
    "          normalizeText(entry?.id || entry?.kind),",
    "        ),",
    "      ),",
    "      ...modeButtons,",
    "      ...modeConfigButtons,",
    "    ];",
    "    showOperationalPanel(",
    "      opsChannelsPanel,",
    "      opsChannelsPanelTitle,",
    "      opsChannelsPanelSummary,",
    "      opsChannelsPanelActions,",
    "      opsChannelsPanelDetails,",
    "      {",
    "        title: selectedLabel || 'Channel Mesh',",
    "        summary: pickFirstText([",
    "          selectedSummary,",
    "          selected?.actionHint,",
    "          promotionHint,",
    "        ], 'Sem detalhe adicional para o canal foco.'),",
    "        actionsHtml: [",
    "          selectorRow,",
    "          buildOperationalInlineButtons(panelButtons),",
    "        ].filter(Boolean).join(''),",
    "        details: [",
    "          selected",
    "            ? '<strong>Readiness:</strong> ' + escapeHtml(normalizeText(selected?.readiness || 'unknown')) + ' | <strong>Transport:</strong> ' + escapeHtml(selectedTransport)",
    "            : '<strong>Readiness:</strong> nenhum canal em foco agora.',",
    "          '<strong>Configurado:</strong> ' + escapeHtml(selected?.configured ? 'sim' : 'nao') + ' | <strong>Implementacao:</strong> ' + escapeHtml(normalizeText(selected?.implementationState || 'n/a')),",
    "          selectedInstallPlan",
    "            ? '<strong>Modo atual:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.currentMode || 'nao configurado'))",
    "              + ' | <strong>Recomendado:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.recommendedMode || 'n/a'))",
    "            : '<strong>Modo atual:</strong> use o scaffold para descobrir o modo recomendado deste canal.',",
    "          selectedInstallPlan?.scaffoldEntries?.length",
    "            ? '<strong>Edicao inline:</strong> use os botoes Configurar para revisar campos <code>KEY=value</code> do modo escolhido antes de aplicar o scaffold.'",
    "            : '<strong>Edicao inline:</strong> este canal nao expoe scaffold extra alem do modo atual.',",
    "          channelAssistant",
    "            ? '<strong>Assistente:</strong> ' + escapeHtml(assistantStatus || 'sem status') + ' - ' + escapeHtml(assistantReply || 'sem resposta natural agora.')",
    "            : '<strong>Assistente:</strong> abra o assistente para consolidar scaffold, doctor e proximo passo.',",
    "          assistantQuestion",
    "            ? '<strong>Pergunta do assistente:</strong> ' + escapeHtml(assistantQuestion)",
    "            : '<strong>Pergunta do assistente:</strong> sem pergunta pendente agora.',",
    "          assistantSelected?.operatorNextStep",
    "            ? '<strong>Proximo passo assistido:</strong> ' + escapeHtml(normalizeText(assistantSelected.operatorNextStep))",
    "            : '<strong>Proximo passo assistido:</strong> sem acao assistida calculada agora.',",
    "          assistantAction?.command",
    "            ? '<strong>Acao assistida:</strong> ' + escapeHtml(normalizeText(assistantAction.label || assistantAction.id)) + ' - ' + escapeHtml(normalizeText(assistantAction.command))",
    "            : '<strong>Acao assistida:</strong> nenhuma acao calculada agora.',",
    "          selectedInstallPlan?.missingEnvKeys?.length",
    "            ? '<strong>Faltando:</strong> ' + escapeHtml(selectedInstallPlan.missingEnvKeys.join(', '))",
    "            : '<strong>Faltando:</strong> nenhum campo obrigatorio pendente para o scaffold atual.',",
    "          selectedInstallPlan?.localWebhookUrl",
    "            ? '<strong>Webhook local:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.localWebhookUrl))",
    "            : '<strong>Webhook local:</strong> nao se aplica ao modo atual deste canal.',",
    "          selectedInstallPlan?.publicWebhookUrl",
    "            ? '<strong>Webhook publico:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.publicWebhookUrl))",
    "            : '<strong>Webhook publico:</strong> publique quando quiser operar fora do host local.',",
    "          featureSummary",
    "            ? '<strong>Features:</strong> ' + escapeHtml(featureSummary)",
    "            : '<strong>Features:</strong> nenhuma feature registrada neste foco.',",
    "          '<strong>Promocao oficial:</strong> ' + escapeHtml(promotionHint),",
    "          doctorSummary",
    "            ? '<strong>Doctor:</strong> ' + escapeHtml(doctorSummary)",
    "            : '<strong>Doctor:</strong> sem relatorio recente deste canal no shell.',",
    "          selectedDoctor?.recommendedAction",
    "            ? '<strong>Acao sugerida:</strong> ' + escapeHtml(normalizeText(selectedDoctor.recommendedAction))",
    "            : '<strong>Acao sugerida:</strong> sem acao de doctor adicional agora.',",
    "          selected?.actionHint",
    "            ? '<strong>Hint do mesh:</strong> ' + escapeHtml(normalizeText(selected.actionHint))",
    "            : '<strong>Hint do mesh:</strong> sem hint operacional para este canal.',",
    "          registry",
    "            ? '<strong>Registry canonico:</strong> ' + escapeHtml(normalizeText(registry?.label || selectedLabel || selectedId || 'canal')) + ' com transporte ' + escapeHtml(normalizeText(registry?.transport || selectedTransport))",
    "            : '<strong>Registry canonico:</strong> sem detalhe adicional neste runtime.',",
    "          latestActionSummary",
    "            ? '<strong>Ultima acao:</strong> ' + escapeHtml(latestActionSummary)",
    "            : '<strong>Ultima acao:</strong> nenhuma acao operacional rodada nesta sessao do shell.',",
    "          selectedInstallPlan?.commands?.apply",
    "            ? '<strong>CLI canonica:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.commands.apply))",
    "            : '<strong>CLI canonica:</strong> use npm run setup:channels para o caminho guiado.',",
    "          ...((Array.isArray(selected?.notes) ? selected.notes : []).slice(0, 4).map((note) =>",
    "            '<strong>Nota:</strong> ' + escapeHtml(normalizeText(note)),",
    "          )),",
    "          ...((Array.isArray(selectedInstallPlan?.notes) ? selectedInstallPlan.notes : []).slice(0, 3).map((note) =>",
    "            '<strong>Setup:</strong> ' + escapeHtml(normalizeText(note)),",
    "          )),",
    "          ...((Array.isArray(latestAction?.details) ? latestAction.details : []).slice(0, 3).map((detailLine) =>",
    "            '<strong>Acao:</strong> ' + escapeHtml(normalizeText(detailLine)),",
    "          )),",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsChannelsPanel, opsChannelsPanelActions, opsChannelsPanelDetails);",
    "  }",
    "",
    "  setOperationalActionStatus(",
    "    opsChannelsStatus,",
    "    operationalMeshExpanded.channels",
    "      ? 'Painel do Channel Mesh aberto com foco, policy, hints de promocao e acoes inline do canal selecionado.'",
    "      : 'Abra o Channel Mesh para revisar policy, pairing e promocao dos canais no mesmo estilo do Control UI.',",
    "  );",
    "  showOperationalAction(",
    "    opsChannelsAction,",
    "    operationalMeshExpanded.channels ? 'Voltar ao resumo' : 'Abrir painel dos channels',",
    "    operationalMeshExpanded.channels ? 'collapse' : 'channels-open',",
    "    selectedId,",
    "  );",
    "}",
    "",
    "function renderTransportsOperationalCard() {",
    "  const transports = operationalMeshData.transports?.transports || null;",
    "  const history = Array.isArray(operationalMeshData.transportHistory?.history?.entries)",
    "    ? operationalMeshData.transportHistory.history.entries",
    "    : [];",
    "  const doctor = operationalMeshData.transportDoctor?.report || operationalMeshData.transportHistory?.doctor || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.transports?.error",
    "    || operationalMeshData.transportHistory?.error",
    "    || operationalMeshData.transportDoctor?.error,",
    "  );",
    "",
    "  if (!transports) {",
    "    setText(opsTransportsState, 'Indisponivel');",
    "    setText(opsTransportsSummary, errorMessage || 'Plano remoto protegido indisponivel neste runtime.');",
    "    renderList(opsTransportsDetails, [errorMessage || 'Valide o token para revisar health, attention e recover do plano remoto.']);",
    "    hideOperationalAction(opsTransportsAction);",
    "    hideOperationalPanel(opsTransportsPanel, opsTransportsPanelActions, opsTransportsPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = transports.summary || {};",
    "  const focus = transports.selected",
    "    || (Array.isArray(transports.entries)",
    "      ? transports.entries.find((entry) => entry?.readiness !== 'ready' || Number(entry?.telemetry?.pendingWork || 0) > 0 || normalizeText(entry?.telemetry?.lastError))",
    "        || transports.entries[0]",
    "      : null);",
    "  const focusLabel = normalizeText(focus?.label || focus?.id || '');",
    "  const focusSummary = normalizeText(focus?.operatorSummary || focus?.telemetry?.statusLine || focus?.actionHint);",
    "  const focusId = normalizeText(focus?.id || operationalMeshSelection.transports);",
    "  operationalMeshSelection.transports = focusId;",
    "  const suggestedAction = Array.isArray(transports?.suggestedActions) && transports.suggestedActions.length > 0",
    "    ? transports.suggestedActions[0]",
    "    : null;",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'transports',",
    "    Array.isArray(transports.entries) ? transports.entries : [],",
    "    focusId,",
    "    (entry) => entry?.id,",
    "    (entry) => entry?.label || entry?.id,",
    "  );",
    "  const historyItems = history.slice(0, 2).map((entry) => {",
    "    const action = normalizeText(entry?.action || 'acao');",
    "    const status = normalizeText(entry?.status || 'unknown');",
    "    const summaryText = normalizeText(entry?.summary || entry?.resultSummary || entry?.command || 'Sem detalhe.');",
    "    return '<strong>' + escapeHtml(action) + ' [' + escapeHtml(status) + ']:</strong> ' + escapeHtml(summaryText);",
    "  });",
    "  const needsRecover = Boolean(",
    "    focusId",
    "    && (",
    "      normalizeText(focus?.telemetry?.lastError)",
    "      || Number(focus?.telemetry?.pendingWork || 0) > 0",
    "      || normalizeText(focus?.readiness) !== 'ready'",
    "    ),",
    "  );",
    "  const transportActionButtons = focusId",
    "    ? '<div class=\"inline-action-row\">'",
    "      + buildOperationalInlineButton('transports', 'transport-doctor', focusId, 'Rodar doctor do foco')",
    "      + (needsRecover ? buildOperationalInlineButton('transports', 'transport-recover', focusId, 'Aplicar recover') : '')",
    "      + '</div>'",
    "    : '';",
    "  const fleetPreview = Array.isArray(transports.entries)",
    "    ? transports.entries.slice(0, 4).map((entry) => {",
    "        const label = normalizeText(entry?.label || entry?.id || 'transporte');",
    "        const readiness = normalizeText(entry?.readiness || 'unknown');",
    "        const pending = Number(entry?.telemetry?.pendingWork || 0);",
    "        return escapeHtml(label) + ' [' + escapeHtml(readiness) + (pending ? '; ' + String(pending) + ' pend.' : '') + ']';",
    "      }).join(' Â· ')",
    "    : '';",
    "  const focusActions = Array.isArray(focus?.actions) ? focus.actions : [];",
    "  setText(",
    "    opsTransportsState,",
    "    summary.total",
    "      ? String(summary.ready || 0) + '/' + String(summary.total || 0) + ' prontos'",
    "      : 'Sem transportes',",
    "  );",
    "  setText(",
    "    opsTransportsSummary,",
    "    focusLabel",
    "      ? focusLabel + ': ' + (focusSummary || 'sem observacao operacional agora.')",
    "      : summary.total",
    "        ? String(summary.attentionRequired || 0) + ' pedem atencao; ' + String(summary.pendingWork || 0) + ' item(ns) pendentes.'",
    "      : 'Nenhum transporte remoto registrado neste host.',",
    "  );",
    "",
    "  const items = operationalMeshExpanded.transports",
    "    ? [",
    "        fleetPreview",
    "          ? '<strong>Frota visivel:</strong> ' + fleetPreview",
    "          : '<strong>Frota visivel:</strong> nenhum transporte remoto registrado agora.',",
    "        focusLabel",
    "          ? '<strong>Foco:</strong> ' + escapeHtml(focusLabel) + (focus?.readiness ? ' [' + escapeHtml(normalizeText(focus.readiness)) + ']' : '')",
    "          : '<strong>Foco:</strong> nenhum transporte selecionado.',",
    "        focusSummary",
    "          ? '<strong>Status:</strong> ' + escapeHtml(focusSummary)",
    "          : '<strong>Status:</strong> sem observacao operacional agora.',",
    "        doctor?.summary",
    "          ? '<strong>Doctor:</strong> ' + escapeHtml(normalizeText(doctor.summary))",
    "          : '<strong>Doctor:</strong> sem relatorio dedicado para o foco atual.',",
    "        historyItems.length > 0",
    "          ? '<strong>Historico recente:</strong><br>' + historyItems.join('<br>')",
    "          : '<strong>Historico recente:</strong> ainda nao ha ciclos registrados para o foco atual.',",
    "        selectorRow",
    "          ? '<strong>Alternar foco:</strong> ' + selectorRow",
    "          : '<strong>Alternar foco:</strong> nenhum transporte remoto registrado agora.',",
    "        focusActions.length > 0",
    "          ? '<strong>Acoes inline:</strong> ' + escapeHtml(focusActions.slice(0, 3).map((entry) => normalizeText(entry?.label || entry?.id || 'acao')).filter(Boolean).join(', '))",
    "          : '<strong>Acoes inline:</strong> nenhum action exposto neste foco agora.',",
    "        transportActionButtons || '<strong>Acoes:</strong> selecione um transporte para rodar doctor ou recover.',",
    "        ...((transports?.suggestedActions || []).slice(0, 2).map((entry) =>",
    "          '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao sugerida')) + ':</strong> '",
    "          + escapeHtml(normalizeText(entry?.reason || entry?.command || 'Sem detalhe.'))",
    "        )),",
    "      ]",
    "    : [",
    "        focusLabel",
    "          ? '<strong>Foco:</strong> ' + escapeHtml(focusLabel) + (focus?.readiness ? ' [' + escapeHtml(normalizeText(focus.readiness)) + ']' : '') + (focusSummary ? ' - ' + escapeHtml(focusSummary) : '.')",
    "          : '<strong>Parciais:</strong> ' + String(summary.partial || 0) + ' | <strong>planned:</strong> ' + String(summary.planned || 0) + '.',",
    "        suggestedAction",
    "          ? '<strong>Proxima acao:</strong> ' + escapeHtml(normalizeText(suggestedAction?.label || suggestedAction?.id || 'Acao sugerida')) + ' - ' + escapeHtml(normalizeText(suggestedAction?.reason || suggestedAction?.command || 'Sem detalhe.'))",
    "          : '<strong>Ao vivo:</strong> ' + String(summary.live || 0) + ' | <strong>reachable:</strong> ' + String(summary.reachable || 0) + '.',",
    "      ];",
    "  renderList(opsTransportsDetails, items);",
    "  if (operationalMeshExpanded.transports) {",
    "    const panelButtons = [",
    "      buildOperationalButtonHtml('transports', 'doctor', 'Rodar doctor do foco', focusId),",
    "      ...((Array.isArray(focus?.actions) ? focus.actions : []).slice(0, 2).map((entry) =>",
    "        buildOperationalButtonHtml(",
    "          'transports',",
    "          'remote-action',",
    "          normalizeText(entry?.label || entry?.id || 'Acao remota'),",
    "          focusId,",
    "          normalizeText(entry?.id),",
    "        ),",
    "      )),",
    "    ];",
    "    if (needsRecover) {",
    "      panelButtons.push(buildOperationalButtonHtml('transports', 'recover', 'Aplicar recover', focusId));",
    "    }",
    "    showOperationalPanel(",
    "      opsTransportsPanel,",
    "      opsTransportsPanelTitle,",
    "      opsTransportsPanelSummary,",
    "      opsTransportsPanelActions,",
    "      opsTransportsPanelDetails,",
    "      {",
    "        title: focusLabel || 'Plano remoto',",
    "        summary: pickFirstText([",
    "          focusSummary,",
    "          doctor?.summary,",
    "          transports?.narrative?.operatorSummary,",
    "        ], 'Sem detalhe adicional para o transporte foco.'),",
    "        actionsHtml: [",
    "          selectorRow,",
    "          buildOperationalInlineButtons(panelButtons),",
    "        ].filter(Boolean).join(''),",
    "        details: [",
    "          focus",
    "            ? '<strong>Readiness:</strong> ' + escapeHtml(normalizeText(focus?.readiness || 'unknown')) + ' | <strong>Transport:</strong> ' + escapeHtml(normalizeText(focus?.transport || 'n/a'))",
    "            : '<strong>Readiness:</strong> nenhum transporte em foco agora.',",
    "          focus?.endpoint",
    "            ? '<strong>Endpoint:</strong> ' + escapeHtml(normalizeText(focus.endpoint))",
    "            : '<strong>Endpoint:</strong> sem endpoint publico neste foco.',",
    "          focus?.telemetry",
    "            ? '<strong>Telemetry:</strong> ' + escapeHtml(normalizeText(focus.telemetry.statusLine || 'Sem status line.')) + ' | pendencias: ' + String(focus.telemetry.pendingWork || 0)",
    "            : '<strong>Telemetry:</strong> sem telemetry recente para o foco atual.',",
    "          normalizeText(focus?.telemetry?.lastError)",
    "            ? '<strong>Ultimo erro:</strong> ' + escapeHtml(normalizeText(focus.telemetry.lastError))",
    "            : '<strong>Ultimo erro:</strong> sem erro recente exposto para este foco.',",
    "          focusActions.length > 0",
    "            ? '<strong>Acoes operacionais:</strong> ' + escapeHtml(focusActions.slice(0, 4).map((entry) => normalizeText(entry?.label || entry?.id || 'acao')).filter(Boolean).join(', '))",
    "            : '<strong>Acoes operacionais:</strong> nenhum action remoto exposto agora.',",
    "          Array.isArray(transports?.suggestedActions) && transports.suggestedActions.length > 0",
    "            ? '<strong>Proxima acao sugerida:</strong> ' + escapeHtml(normalizeText(transports.suggestedActions[0]?.label || transports.suggestedActions[0]?.id || 'acao')) + ' - '",
    "              + escapeHtml(normalizeText(transports.suggestedActions[0]?.reason || transports.suggestedActions[0]?.command || 'Sem detalhe.'))",
    "            : '<strong>Proxima acao sugerida:</strong> sem recomendacao adicional para o plano remoto.',",
    "          ...((Array.isArray(focus?.details) ? focus.details : []).slice(0, 2).map((detail) =>",
    "            '<strong>Detalhe:</strong> ' + escapeHtml(normalizeText(detail)),",
    "          )),",
    "          ...historyItems,",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsTransportsPanel, opsTransportsPanelActions, opsTransportsPanelDetails);",
    "  }",
    "  setOperationalActionStatus(",
    "    opsTransportsStatus,",
    "    operationalMeshExpanded.transports",
    "      ? 'Painel remoto aberto com foco, doctor, historico e recover do transporte selecionado.'",
    "      : 'Abra o painel remoto para revisar foco, historico e recover sem sair do shell.',",
    "  );",
    "  showOperationalAction(",
    "    opsTransportsAction,",
    "    operationalMeshExpanded.transports ? 'Voltar ao resumo' : 'Abrir painel dos transportes',",
    "    operationalMeshExpanded.transports ? 'collapse' : 'transports-open',",
    "    focusId,",
    "  );",
    "}",
    "",
    "function renderExtensionsOperationalCard() {",
    "  const extensions = operationalMeshData.extensions?.workspaceExtensions || null;",
    "  const plugins = operationalMeshData.plugins?.plugins || null;",
    "  const hooks = operationalMeshData.hooks?.hooks || null;",
    "  const latestHookRun = operationalMeshData.hooks?.run || null;",
    "  const latestHookPipeline = operationalMeshData.hooks?.pipeline || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.extensions?.error",
    "    || operationalMeshData.plugins?.error",
    "    || operationalMeshData.hooks?.error,",
    "  );",
    "",
    "  if (!extensions) {",
    "    setText(opsExtensionsState, 'Indisponivel');",
    "    setText(opsExtensionsSummary, errorMessage || 'Catalogo protegido de integrations indisponivel neste runtime.');",
    "    renderList(opsExtensionsDetails, [errorMessage || 'Valide o token para revisar workspaces, plugins, comandos e hooks carregados.']);",
    "    hideOperationalAction(opsExtensionsAction);",
    "    hideOperationalPanel(opsExtensionsPanel, opsExtensionsPanelActions, opsExtensionsPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = extensions.summary || {};",
    "  const selected = extensions.selected",
    "    || (Array.isArray(extensions.entries) ? extensions.entries[0] : null);",
    "  const selectedId = normalizeText(selected?.slug || operationalMeshSelection.extensions);",
    "  operationalMeshSelection.extensions = selectedId;",
    "  const selectedLabel = normalizeText(selected?.workspaceName || selected?.slug || '');",
    "  const selectedLead = normalizeText(",
    "    selected?.instructionSummary",
    "      || selected?.instructionFile",
    "      || selected?.commands?.[0]?.template",
    "      || selected?.hooks?.[0]?.command,",
    "  );",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'extensions',",
    "    Array.isArray(extensions.entries) ? extensions.entries : [],",
    "    selectedId,",
    "    (entry) => entry?.slug,",
    "    (entry) => entry?.workspaceName || entry?.slug,",
    "  );",
    "  const commandItems = Array.isArray(selected?.commands)",
    "    ? selected.commands.slice(0, 2).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.name || 'Comando')) + ':</strong> ' + escapeHtml(normalizeText(entry?.template || 'Sem template.')),",
    "    )",
    "    : [];",
    "  const hookItems = Array.isArray(selected?.hooks)",
    "    ? selected.hooks.slice(0, 2).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.event || 'Hook')) + ':</strong> ' + escapeHtml(normalizeText(entry?.command || 'Sem comando.')),",
    "    )",
    "    : [];",
    "  const workspacePreview = Array.isArray(extensions.entries)",
    "    ? extensions.entries.slice(0, 4).map((entry) => {",
    "        const label = normalizeText(entry?.workspaceName || entry?.slug || 'workspace');",
    "        const counts = String(entry?.commandCount || 0) + ' cmd / ' + String(entry?.hookCount || 0) + ' hook';",
    "        return escapeHtml(label) + ' [' + escapeHtml(counts) + ']';",
    "      }).join(' Â· ')",
    "    : '';",
    "  const pluginFocus = resolvePluginFocusEntry(plugins);",
    "  const extensionActionRow = buildExtensionActionRow(selected, plugins);",
    "  setText(",
    "    opsExtensionsState,",
    "    summary.workspaces",
    "      ? String(summary.workspaces) + ' workspace(s)'",
    "      : 'Sem extensoes',",
    "  );",
    "  setText(",
    "    opsExtensionsSummary,",
    "    selectedLabel",
    "      ? selectedLabel + ': ' + (selectedLead || (String(selected?.commandCount || 0) + ' comando(s) e ' + String(selected?.hookCount || 0) + ' hook(s).'))",
    "      : summary.workspaces",
    "        ? String(summary.commands || 0) + ' comando(s), ' + String(summary.hooks || 0) + ' hook(s) e ' + String(summary.withInstructions || 0) + ' com instrucoes.'",
    "      : 'Nenhuma integration de workspace registrada neste host.',",
    "  );",
    "",
    "  const items = operationalMeshExpanded.extensions",
    "    ? [",
    "        workspacePreview",
    "          ? '<strong>Workspaces visiveis:</strong> ' + workspacePreview",
    "          : '<strong>Workspaces visiveis:</strong> nenhum workspace registrado agora.',",
    "        selectedLabel",
    "          ? '<strong>Workspace:</strong> ' + escapeHtml(selectedLabel)",
    "            + ' - ' + String(selected?.commandCount || 0) + ' comando(s), ' + String(selected?.hookCount || 0) + ' hook(s).'",
    "          : '<strong>Workspace:</strong> nenhum workspace selecionado agora.',",
    "        selectedLead",
    "          ? '<strong>Instrucao principal:</strong> ' + escapeHtml(selectedLead)",
].join('\n');
