export const runtimeShellScriptPart6Seg2: string = [
    "          : '<strong>Instrucao principal:</strong> without instrucao destacada para o foco current.',",
    "        selectorRow",
    "          - '<strong>Switch focus:</strong> ' + selectorRow",
    "          : '<strong>Switch focus:</strong> no workspace registered now.',",
    "        commandItems.length > 0",
    "          - '<strong>Commands:</strong><br>' + commandItems.join('<br>')",
    "          : '<strong>Commands:</strong> no command registered in this workspace.',",
    "        hookItems.length > 0",
    "          - '<strong>Hooks:</strong><br>' + hookItems.join('<br>')",
    "          : '<strong>Hooks:</strong> no hook registered in this workspace.',",
    "        pluginFocus",
    "          - '<strong>Plugin foco:</strong> ' + escapeHtml(normalizeText(pluginFocus?.label || pluginFocus?.id || 'plugin')) + ' ? '",
    "            + escapeHtml(normalizeText(pluginFocus?.summary || pluginFocus?.actionHint || 'Use inline actions to operate o plugin.'))",
    "          : '<strong>Plugin foco:</strong> no plugin with action exposed now.',",
    "        latestHookRun?.summary",
    "          - '<strong>Last dry-run:</strong> ' + escapeHtml(normalizeText(latestHookRun.summary))",
    "          : '<strong>Last dry-run:</strong> there has been no operational hook execution in this shell session yet.',",
    "        normalizeText(extensions?.narrative?.operatorSummary)",
    "          - '<strong>catalog:</strong> ' + escapeHtml(normalizeText(extensions.narrative.operatorSummary))",
    "          : '<strong>catalog:</strong> without narrativa operational agora.',",
    "      ]",
    "    : [",
    "        selectedLabel",
    "          - '<strong>Selected:</strong> ' + escapeHtml(selectedLabel) + '.'",
    "          : '<strong>Visible instruction:</strong> ' + String(summary.withInstructions || 0) + ' workspace(s).',",
    "        selectedLead",
    "          - '<strong>Main entry:</strong> ' + escapeHtml(selectedLead)",
    "          : '<strong>catalog:</strong> ' + escapeHtml(normalizeText(extensions?.narrative?.operatorSummary || 'No main instruction visible now.')),",
    "      ];",
    "  renderList(opsExtensionsDetails, items);",
    "    if (operationalMeshExpanded.extensions) {",
    "      showOperationalPanel(",
    "        opsExtensionsPanel,",
    "        opsExtensionsPanelTitle,",
    "        opsExtensionsPanelSummary,",
    "        opsExtensionsPanelActions,",
    "      opsExtensionsPanelDetails,",
    "      {",
    "        title: selectedLabel || 'catalog de integrations',",
    "          summary: pickFirstText([",
    "            selectedLead,",
    "            extensions?.narrative?.operatorSummary,",
    "            plugins?.narrative?.operatorSummary,",
    "            hooks?.narrative?.operatorSummary,",
    "          ], 'No additional detail para o workspace foco.'),",
    "          actionsHtml: [",
    "            selectorRow,",
    "            extensionActionRow,",
    "          ].filter(Boolean).join(''),",
    "          details: [",
    "            selected",
    "              - '<strong>Workspace:</strong> ' + escapeHtml(selectedLabel)",
    "              : '<strong>Workspace:</strong> no workspace on focus now.',",
    "          '<strong>Extensions:</strong> ' + String(selected?.commandCount || 0) + ' command(s), ' + String(selected?.hookCount || 0) + ' hook(s).',",
    "          selected?.instructionFile",
    "            - '<strong>Instrucao:</strong> ' + escapeHtml(normalizeText(selected.instructionFile))",
    "            : '<strong>Instrucao:</strong> no ZAVORTH.md visible on this focus.',",
    "            plugins?.summary",
    "              - '<strong>Plugin plane:</strong> ' + String(plugins.summary.total || 0) + ' total, ' + String(plugins.summary.installed || 0) + ' installed e ' + String(plugins.summary.trusted || 0) + ' trusted.'",
    "              : '<strong>Plugin plane:</strong> unavailable in this runtime.',",
    "            pluginFocus",
    "              - '<strong>Plugin foco:</strong> ' + escapeHtml(normalizeText(pluginFocus?.label || pluginFocus?.id || 'plugin')) + ' ? '",
    "                + escapeHtml(normalizeText(pluginFocus?.summary || pluginFocus?.actionHint || 'Trigger inline actions to operate o plugin.'))",
    "              : '<strong>Plugin foco:</strong> no plugin with visible actions now.',",
    "            pluginFocus && Array.isArray(pluginFocus?.actions) && pluginFocus.actions.length > 0",
    "              - '<strong>Actions do plugin:</strong> ' + escapeHtml(pluginFocus.actions.slice(0, 4).map((entry) => normalizeText(entry?.label || entry?.kind || entry?.id || 'action')).filter(Boolean).join(', '))",
    "              : '<strong>Actions do plugin:</strong> nenhum action exposto para o plugin foco.',",
    "            hooks?.summary",
    "              - '<strong>Hook plane:</strong> ' + String(hooks.summary.registeredHooks || 0) + ' hook(s) registrados em ' + String(hooks.summary.workspaces || 0) + ' workspace(s).'",
    "              : '<strong>Hook plane:</strong> unavailable in this runtime.',",
    "            latestHookRun?.summary",
    "              - '<strong>Last dry-run:</strong> ' + escapeHtml(normalizeText(latestHookRun.summary))",
    "              : '<strong>Last dry-run:</strong> no hook run operationally in this session.',",
    "            latestHookPipeline?.narrative?.operatorSummary",
    "              - '<strong>Pipeline de hook:</strong> ' + escapeHtml(normalizeText(latestHookPipeline.narrative.operatorSummary))",
    "              : '<strong>Pipeline de hook:</strong> without pipeline operational capturado nesta session.',",
    "          ...commandItems,",
    "          ...hookItems,",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsExtensionsPanel, opsExtensionsPanelActions, opsExtensionsPanelDetails);",
    "  }",
    "  setOperationalActionStatus(",
    "    opsExtensionsStatus,",
    "    operationalMeshExpanded.extensions",
    "      - 'expanded catalog with focus, commands, and hooks from the selected workspace.'",
    "      : 'Refresh the catalog when ZAVORTH.md, plugins, commands, or hooks change on this host.',",
    "  );",
    "  showOperationalAction(",
    "    opsExtensionsAction,",
    "    operationalMeshExpanded.extensions ? 'Back to summary' : 'Open integrations panel',",
    "    operationalMeshExpanded.extensions ? 'collapse' : 'extensions-open',",
    "  );",
    "}",
    "",
    "function renderOperationalMeshSummary(channelMeshPayload, channelInstallPayload, channelDoctorPayload, channelAssistantPayload, nodeMeshPayload, nodeDoctorPayload, transportPayload, extensionPayload, pluginPayload, hookPayload) {",
    "  operationalMeshData = {",
    "    nodes: nodeMeshPayload || null,",
    "    nodeDoctor: nodeDoctorPayload || null,",
    "    nodeActivity: null,",
    "    nodeCapabilities: null,",
    "    nodeBootstrap: null,",
    "    channels: channelMeshPayload || null,",
    "    channelDetail: null,",
    "    channelAction: null,",
    "    channelInstall: channelInstallPayload || null,",
    "    channelDoctor: channelDoctorPayload || null,",
    "    channelAssistant: channelAssistantPayload || null,",
    "    transports: transportPayload || null,",
    "    transportHistory: null,",
    "    transportDoctor: null,",
    "    extensions: extensionPayload || null,",
    "    plugins: pluginPayload || null,",
    "    hooks: hookPayload || null,",
    "  };",
    "  renderNodesOperationalCard();",
    "  renderChannelsOperationalCard();",
    "  renderTransportsOperationalCard();",
    "  renderExtensionsOperationalCard();",
    "  renderOperatorCockpit();",
    "}",
    "",
    "function renderProtectedCardHierarchy(manifest, report) {",
    "  const plan = manifest?.recommendedPlan;",
    "  const action = normalizeText(plan?.primaryAction);",
    "",
    "  setCardEmphasis(manifestCard, 'subtle');",
    "  setCardEmphasis(journeyCard, 'subtle');",
    "  setCardEmphasis(remoteCard, 'subtle');",
    "",
    "  setText(",
    "    journeyCardNote,",
    "    action === 'go' || action === 'trust'",
    "      - 'This is the main deep path now: complete setup, trust, and local readiness before continuing.'",
    "      : 'Use this path when the local runtime is not yet ready or when este host ainda need trust.',",
    "  );",
    "  setText(",
    "    remoteCardNote,",
    "    action === 'remote'",
    "      - 'Este e o aprofundamento principal agora: feche o rollout remote oficial before operar outside da machine.'",
    "      : 'Use this path when you want to operate outside this machine or publish the official remote shell.',",
    "  );",
    "",
    "  if (action === 'go' || action === 'trust') {",
    "    setCardEmphasis(journeyCard, 'focus');",
    "    return;",
    "  }",
    "",
    "  if (action === 'remote') {",
    "    setCardEmphasis(remoteCard, 'focus');",
    "    return;",
    "  }",
    "}",
    "",
    "function hideJourneyActionButtons() {",
    "  if (journeyTrustActionButton instanceof HTMLButtonElement) {",
    "    journeyTrustActionButton.hidden = true;",
    "    journeyTrustActionButton.dataset.mode = '';",
    "    journeyTrustActionButton.dataset.action = '';",
    "  }",
    "  if (journeyRefreshActionButton instanceof HTMLButtonElement) {",
    "    journeyRefreshActionButton.hidden = true;",
    "  }",
    "}",
    "",
    "function detectJourneyActionFromCommand(command) {",
    "  const normalized = normalizeText(command).toLowerCase();",
    "  if (!normalized) {",
    "    return '';",
    "  }",
    "  if (normalized.includes('ops:go')) {",
    "    return 'go';",
    "  }",
    "  if (normalized.includes('ops:install') || normalized.includes('ops:bootstrap')) {",
    "    return 'install';",
    "  }",
    "  if (normalized.includes('ops:start') || normalized.includes('ops:up')) {",
    "    return 'start';",
    "  }",
    "  if (normalized.includes('ops:ready')) {",
    "    return 'ready';",
    "  }",
    "  return '';",
    "}",
    "",
    "function buildJourneyPrimaryAction(manifest, journeyReport) {",
    "  if (!manifest) {",
    "    return null;",
    "  }",
    "",
    "  const hostAuthorized = manifest?.auth?.authorizedHost;",
    "  const localReady = manifest?.local?.ready === true;",
    "  if (hostAuthorized === false) {",
    "    return {",
    "      mode: 'trust',",
    "      action: '',",
    "      label: 'Autorizar este host',",
    "      status: 'This host still needs trust before mutable actions.',",
    "    };",
    "  }",
    "",
    "  const phases = Array.isArray(journeyReport?.phases) ? journeyReport.phases : [];",
    "  const nextStepStage = phases.find((stage) => normalizeText(stage?.id) === 'next-step' && String(stage?.status || '').trim().toLowerCase() !== 'ready');",
    "  const actionableStage = phases.find((stage) => {",
    "    const status = String(stage?.status || '').trim().toLowerCase();",
    "    return status === 'action' || status === 'failed';",
    "  });",
    "  const stage = nextStepStage || actionableStage || null;",
    "  const detectedAction = detectJourneyActionFromCommand(stage?.command);",
    "  const fallbackAction = localReady ? 'ready' : 'go';",
    "  const action = detectedAction || fallbackAction;",
    "",
    "  if (action === 'install') {",
    "    return {",
    "      mode: 'journey',",
    "      action,",
    "      label: 'Repair local bootstrap',",
    "      status: normalizeText(stage?.summary) || 'Use this step to repair secure local bootstrap for this host.',",
    "    };",
    "  }",
    "",
    "  if (action === 'start') {",
    "    return {",
    "      mode: 'journey',",
    "      action,",
    "      label: 'Start local runtime',",
    "      status: normalizeText(stage?.summary) || 'Use this step to start the supervised runtime and validate the local shell.',",
    "    };",
    "  }",
    "",
    "  if (action === 'ready') {",
    "    return {",
    "      mode: 'journey',",
    "      action,",
    "      label: localReady ? 'Revalidate official readiness' : 'Review official readiness',",
    "      status: normalizeText(stage?.summary) || (localReady",
    "        - 'Local host is ready. Run the official check to review readiness and trust.'",
    "        : 'Use this step to review local readiness and official host state.'),",
    "    };",
    "  }",
    "",
    "  return {",
    "    mode: 'journey',",
    "    action: 'go',",
    "    label: 'Run official shortcut',",
    "    status: normalizeText(stage?.summary) || 'Use this shortcut to complete setup, runtime startup, and official host shell readiness.',",
    "  };",
    "}",
    "",
    "function renderJourneyActionControls(manifest, journeyReport) {",
    "  hideJourneyActionButtons();",
    "  if (!manifest) {",
    "    setJourneyActionStatus('Validate the token para usar as actions do host oficial.');",
    "    return;",
    "  }",
    "",
    "  const primaryAction = buildJourneyPrimaryAction(manifest, journeyReport);",
    "  const localReady = manifest?.local?.ready === true;",
    "",
    "  if (journeyTrustActionButton instanceof HTMLButtonElement && primaryAction) {",
    "    journeyTrustActionButton.hidden = false;",
    "    journeyTrustActionButton.textContent = primaryAction.label;",
    "    journeyTrustActionButton.dataset.mode = primaryAction.mode;",
    "    journeyTrustActionButton.dataset.action = primaryAction.action || '';",
    "  }",
    "",
    "  if (journeyRefreshActionButton instanceof HTMLButtonElement) {",
    "    journeyRefreshActionButton.hidden = false;",
    "    journeyRefreshActionButton.textContent = localReady ? 'Revalidate host' : 'Update host';",
    "  }",
    "",
    "  setJourneyActionStatus(primaryAction?.status || (localReady",
    "    - 'local host ready. Use this card only to review readiness and trust.'",
    "    : 'Use this card to review local readiness e atualizar o estado do host.'));",
    "}",
    "",
    "function hideRemoteActionButtons() {",
    "  if (remoteRecommendedActionButton instanceof HTMLButtonElement) {",
    "    remoteRecommendedActionButton.hidden = true;",
    "    remoteRecommendedActionButton.dataset.action = '';",
    "    remoteRecommendedActionButton.dataset.provider = '';",
    "  }",
    "  if (remoteVerifyActionButton instanceof HTMLButtonElement) {",
    "    remoteVerifyActionButton.hidden = true;",
    "    remoteVerifyActionButton.dataset.action = '';",
    "  }",
    "}",
    "",
    "function renderRemoteActionControls(report) {",
    "  hideRemoteActionButtons();",
    "  if (!report?.actions) {",
    "    setRemoteActionStatus('Validate the token para usar a guided action from the official remote.');",
    "    return;",
    "  }",
    "",
    "  const recommendedAction = normalizeText(report.actions.recommendedAction);",
    "  const recommendedProvider = normalizeText(report.actions.recommendedProvider);",
    "  const recommendedConfig = recommendedAction ? report.actions[recommendedAction] : null;",
    "",
    "  if (remoteRecommendedActionButton instanceof HTMLButtonElement && recommendedAction && recommendedConfig) {",
    "    remoteRecommendedActionButton.hidden = false;",
    "    remoteRecommendedActionButton.textContent = normalizeText(recommendedConfig.label) || 'Run next step remote';",
    "    remoteRecommendedActionButton.dataset.action = recommendedAction;",
    "    remoteRecommendedActionButton.dataset.provider = recommendedProvider;",
    "  }",
    "",
    "  if (remoteVerifyActionButton instanceof HTMLButtonElement && report.actions.canVerify) {",
    "    remoteVerifyActionButton.hidden = false;",
    "    remoteVerifyActionButton.textContent = normalizeText(report.actions.verify?.label) || 'Verificar remote';",
    "    remoteVerifyActionButton.dataset.action = 'verify';",
    "    remoteVerifyActionButton.dataset.provider = recommendedProvider;",
    "  }",
    "}",
    "",
    "async function runOfficialRemoteAction(action, provider) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setRemoteActionStatus('Validate the token before acionar o remote oficial.');",
    "    return;",
    "  }",
    "",
    "  const buttons = [remoteRecommendedActionButton, remoteVerifyActionButton].filter((target) => target instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    setRemoteActionStatus('Executing remote action oficial...');",
    "    const response = await fetch('/api/web/host/official-remote-access/actions', {",
    "      method: 'POST',",
    "      headers: {",
    "        Accept: 'application/json',",
    "        'Content-Type': 'application/json',",
    "        'X-Zavorth-Token': token,",
    "      },",
    "      body: JSON.stringify({",
    "        action,",
    "        provider: provider || undefined,",
    "      }),",
    "    });",
    "    const payload = await response.json().catch(() => null);",
    "    if (!response.ok || !payload?.ok) {",
    "      throw new Error(payload?.error || 'Failed to run a official remote action.');",
    "    }",
    "",
    "    await refreshProtectedShellState(token, {",
    "      manifest: payload.manifest,",
    "      officialRemoteAccess: payload.report,",
    "    });",
    "    setRemoteActionStatus(normalizeText(payload?.report?.summary) || 'Remote action completed.');",
    "  } catch (error: unknown) {",
    "    setRemoteActionStatus(error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function fetchSessionWorkspacePayload(token, requestedSessionId = '') {",
    "  const query = normalizeText(requestedSessionId)",
    "    - '?sessionId=' + encodeURIComponent(normalizeText(requestedSessionId))",
    "    : '';",
    "  const sessionPayload = await fetchProtectedJsonOptional('/api/web/session' + query, token, { timeoutMs: 8000 });",
    "  const sessionId = normalizeText(sessionPayload?.sessionId) || normalizeText(requestedSessionId);",
    "  if (!sessionId) {",
    "    return {",
    "      session: sessionPayload,",
    "      state: null,",
    "      history: null,",
    "      toolRuns: null,",
    "    };",
    "  }",
    "",
    "  const sessionQuery = '?sessionId=' + encodeURIComponent(sessionId);",
    "  const [statePayload, historyPayload, toolRunsPayload] = await Promise.all([",
    "    fetchProtectedJsonOptional('/api/web/gateway/sessions' + sessionQuery, token),",
    "    fetchProtectedJsonOptional('/api/web/gateway/sessions/history' + sessionQuery, token),",
    "    fetchProtectedJsonOptional('/api/web/tool-runs' + sessionQuery, token),",
    "  ]);",
    "",
    "  return {",
    "    session: sessionPayload,",
    "    state: statePayload,",
    "    history: historyPayload,",
    "    toolRuns: toolRunsPayload,",
    "  };",
    "}",
    "",
    "async function refreshProtectedShellState(token, seed = {}) {",
    "  const manifestPayloadPromise = seed.manifest",
    "    - Promise.resolve({ manifest: seed.manifest })",
    "    : fetchProtectedJsonOptional('/api/web/host/access-manifest', token, { timeoutMs: 7000 });",
    "  const journeyPayloadPromise = seed.installJourney",
    "    - Promise.resolve({ report: seed.installJourney })",
    "    : fetchProtectedJsonOptional('/api/web/host/install-journey', token, { timeoutMs: 7000 });",
    "  const remotePayloadPromise = seed.officialRemoteAccess",
    "    - Promise.resolve({ report: seed.officialRemoteAccess })",
    "    : fetchProtectedJsonOptional('/api/web/host/official-remote-access', token, { timeoutMs: 7000 });",
    "  const channelMeshPayloadPromise = fetchProtectedJsonOptional('/api/web/channels', token);",
    "  const channelInstallPayloadPromise = fetchProtectedJsonOptional('/api/web/channels/install', token);",
    "  const channelDoctorPayloadPromise = fetchProtectedJsonOptional('/api/web/channels/doctor', token, { method: 'POST' });",
    "  const channelAssistantPayloadPromise = fetchProtectedJsonOptional('/api/web/channels/setup-assistant', token);",
    "  const nodeMeshPayloadPromise = fetchProtectedJsonOptional('/api/web/nodes', token);",
    "  const nodeDoctorPayloadPromise = fetchProtectedJsonOptional('/api/web/nodes/doctor', token);",
    "  const transportPayloadPromise = fetchProtectedJsonOptional('/api/web/transports', token);",
    "  const extensionPayloadPromise = fetchProtectedJsonOptional('/api/web/workspace/extensions', token);",
    "  const pluginPayloadPromise = fetchProtectedJsonOptional('/api/web/plugins', token);",
    "  const hookPayloadPromise = fetchProtectedJsonOptional('/api/web/hooks', token);",
    "  const sessionWorkspacePayloadPromise = fetchSessionWorkspacePayload(token, readSessionWorkspaceSessionId());",
    "  const learningPayloadPromise = fetchProtectedJsonOptional('/api/web/learning', token);",
    "  const memoryProceduresPayloadPromise = fetchProtectedJsonOptional('/api/web/memory/procedures', token);",
    "  const evalControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/evals', token);",
    "  const qaControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/qa', token);",
    "  const governanceControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/governance', token);",
    "  const replayLearningControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/replay-learning', token);",
    "  const ecosystemControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/ecosystem', token);",
    "  const distributedRuntimeControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/distributed-runtime', token);",
    "  const runtimeStabilityControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/runtime-stability', token);",
    "  const rolloutReadinessControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/rollout-readiness', token);",
    "  const automationControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/automations...limit=8', token);",
    "  const hubControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/hub', token);",
    "  const trustPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/trust-plane', token);",
    "  const watchModePayloadPromise = fetchProtectedJsonOptional('/api/web/watch-mode...limit=8', token);",
    "  const systemSupervisorPayloadPromise = fetchProtectedJsonOptional('/api/web/system-supervisor...limit=20', token);",
    "",
    "  const [",
    "    manifestPayload,",
    "    journeyPayload,",
    "    remotePayload,",
    "    channelMeshPayload,",
    "    channelInstallPayload,",
    "    channelDoctorPayload,",
    "    channelAssistantPayload,",
    "    nodeMeshPayload,",
    "    nodeDoctorPayload,",
    "    transportPayload,",
    "    extensionPayload,",
    "    pluginPayload,",
    "    hookPayload,",
    "    sessionWorkspacePayload,",
    "    learningPayload,",
    "    memoryProceduresPayload,",
    "    evalControlPlanePayload,",
    "    qaControlPlanePayload,",
    "    governanceControlPlanePayload,",
    "    replayLearningControlPlanePayload,",
    "    ecosystemControlPlanePayload,",
    "    distributedRuntimeControlPlanePayload,",
    "    runtimeStabilityControlPlanePayload,",
    "    rolloutReadinessControlPlanePayload,",
    "    automationControlPlanePayload,",
    "    hubControlPlanePayload,",
    "    trustPlanePayload,",
    "    watchModePayload,",
    "    systemSupervisorPayload,",
    "  ] = await Promise.all([",
    "    manifestPayloadPromise,",
    "    journeyPayloadPromise,",
    "    remotePayloadPromise,",
    "    channelMeshPayloadPromise,",
    "    channelInstallPayloadPromise,",
    "    channelDoctorPayloadPromise,",
    "    channelAssistantPayloadPromise,",
    "    nodeMeshPayloadPromise,",
    "    nodeDoctorPayloadPromise,",
    "    transportPayloadPromise,",
    "    extensionPayloadPromise,",
    "    pluginPayloadPromise,",
    "    hookPayloadPromise,",
    "    sessionWorkspacePayloadPromise,",
    "    learningPayloadPromise,",
    "    memoryProceduresPayloadPromise,",
    "    evalControlPlanePayloadPromise,",
    "    qaControlPlanePayloadPromise,",
    "    governanceControlPlanePayloadPromise,",
    "    replayLearningControlPlanePayloadPromise,",
    "    ecosystemControlPlanePayloadPromise,",
    "    distributedRuntimeControlPlanePayloadPromise,",
    "    runtimeStabilityControlPlanePayloadPromise,",
    "    rolloutReadinessControlPlanePayloadPromise,",
    "    automationControlPlanePayloadPromise,",
    "    hubControlPlanePayloadPromise,",
    "    trustPlanePayloadPromise,",
    "    watchModePayloadPromise,",
    "    systemSupervisorPayloadPromise,",
    "  ]);",
    "",
    "  renderPriorityState(manifestPayload, journeyPayload, remotePayload);",
    "  renderManifest(manifestPayload);",
    "  renderJourney(journeyPayload);",
    "  renderRemoteAccess(remotePayload);",
    "  renderJourneyActionControls(manifestPayload?.manifest, journeyPayload?.report);",
    "  renderRemoteActionControls(remotePayload?.report);",
    "  renderOperationalMeshSummary(",
    "    channelMeshPayload,",
    "    channelInstallPayload,",
    "    channelDoctorPayload,",
    "    channelAssistantPayload,",
    "    nodeMeshPayload,",
    "    nodeDoctorPayload,",
    "    transportPayload,",
    "    extensionPayload,",
    "    pluginPayload,",
    "    hookPayload,",
    "  );",
    "  renderSessionWorkspace(sessionWorkspacePayload);",
    "  renderLearningMemory(sessionWorkspacePayload?.state, learningPayload, memoryProceduresPayload);",
    "  protectedShellUnlocked = true;",
    "  renderEvalControlPlanePanel(evalControlPlanePayload);",
    "  renderQaControlPlanePanel(qaControlPlanePayload);",
    "  renderGovernanceControlPlanePanel(governanceControlPlanePayload);",
    "  renderReplayLearningControlPlanePanel(replayLearningControlPlanePayload);",
    "  renderEcosystemControlPlanePanel(ecosystemControlPlanePayload);",
    "  renderDistributedRuntimeControlPlanePanel(distributedRuntimeControlPlanePayload);",
    "  renderRuntimeStabilityControlPlanePanel(runtimeStabilityControlPlanePayload);",
    "  renderRolloutReadinessControlPlanePanel(rolloutReadinessControlPlanePayload);",
    "  renderAutomationControlPlanePanel(automationControlPlanePayload);",
    "  renderHubControlPlanePanel(hubControlPlanePayload);",
    "  renderTrustPlanePanel(trustPlanePayload);",
    "  renderWatchModePanel(watchModePayload);",
    "  rendersystemSupervisorPanel(systemSupervisorPayload);",
    "  renderOperatorCockpit();",
    "  ensureGatewayControlSocket(token, readSessionWorkspaceSessionId());",
    "}",
    "",
    "async function runJourneyTrustAction() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setJourneyActionStatus('Validate the token before acionar o host oficial.');",
    "    return;",
    "  }",
    "",
    "  const buttons = [journeyTrustActionButton, journeyRefreshActionButton].filter((target) => target instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    const mode = normalizeText(journeyTrustActionButton?.dataset.mode) || 'trust';",
    "    if (mode === 'journey') {",
    "      const action = normalizeText(journeyTrustActionButton?.dataset.action) || 'ready';",
    "      setJourneyActionStatus('Executando jornada local of the host...');",
    "      const response = await fetch('/api/web/host/install-journey/actions', {",
    "        method: 'POST',",
    "        headers: {",
    "          Accept: 'application/json',",
    "          'Content-Type': 'application/json',",
    "          'X-Zavorth-Token': token,",
    "        },",
    "        body: JSON.stringify({ action }),",
    "      });",
    "      const payload = await response.json().catch(() => null);",
    "      if (!response.ok || !payload?.ok) {",
    "        throw new Error(payload?.error || 'Failed to run a jornada local do host.');",
    "      }",
    "",
    "      await refreshProtectedShellState(token, {",
    "        manifest: payload.manifest,",
    "        installJourney: payload.installJourney,",
    "        officialRemoteAccess: payload.officialRemoteAccess,",
    "      });",
    "      setJourneyActionStatus(normalizeText(payload?.report?.summary) || 'local journey updated.');",
    "      return;",
    "    }",
    "",
    "    setJourneyActionStatus('Autorizanof the host e atualizando readiness...');",
    "    const response = await fetch('/api/web/host/trust', {",
    "      method: 'POST',",
    "      headers: {",
    "        Accept: 'application/json',",
    "        'X-Zavorth-Token': token,",
    "      },",
    "    });",
    "    const payload = await response.json().catch(() => null);",
    "    if (!response.ok || !payload?.ok) {",
    "      throw new Error(payload?.error || 'Failed to authorize this host.');",
    "    }",
    "",
    "    await refreshProtectedShellState(token, {",
    "      manifest: payload.manifest,",
    "      installJourney: payload.installJourney,",
    "      officialRemoteAccess: payload.officialRemoteAccess,",
    "    });",
    "    setJourneyActionStatus('Host authorized and local state updated.');",
    "  } catch (error: unknown) {",
    "    setJourneyActionStatus(error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshJourneyState() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setJourneyActionStatus('Validate the token before atualizar o host.');",
].join('\n');
