export const runtimeShellScriptPart7Seg1: string = [
    "    return;",
    "  }",
    "",
    "  const buttons = [journeyTrustActionButton, journeyRefreshActionButton].filter((target) => target instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    setJourneyActionStatus('Atualizando manifest, journey and remote from this host...');",
    "    await refreshProtectedShellState(token);",
    "    setJourneyActionStatus('Host updated successfully.');",
    "  } catch (error: unknown) {",
    "    setJourneyActionStatus(error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installRemoteActionControls() {",
    "  if (remoteRecommendedActionButton instanceof HTMLButtonElement) {",
    "    remoteRecommendedActionButton.addEventListener('click', () => {",
    "      void runOfficialRemoteAction(",
    "        normalizeText(remoteRecommendedActionButton.dataset.action),",
    "        normalizeText(remoteRecommendedActionButton.dataset.provider),",
    "      );",
    "    });",
    "  }",
    "",
    "  if (remoteVerifyActionButton instanceof HTMLButtonElement) {",
    "    remoteVerifyActionButton.addEventListener('click', () => {",
    "      void runOfficialRemoteAction(",
    "        normalizeText(remoteVerifyActionButton.dataset.action || 'verify'),",
    "        normalizeText(remoteVerifyActionButton.dataset.provider),",
    "      );",
    "    });",
    "  }",
    "}",
    "",
    "function installJourneyActionControls() {",
    "  if (journeyTrustActionButton instanceof HTMLButtonElement) {",
    "    journeyTrustActionButton.addEventListener('click', () => {",
    "      void runJourneyTrustAction();",
    "    });",
    "  }",
    "",
    "  if (journeyRefreshActionButton instanceof HTMLButtonElement) {",
    "    journeyRefreshActionButton.addEventListener('click', () => {",
    "      void refreshJourneyState();",
    "    });",
    "  }",
    "}",
    "",
    "async function runPriorityPrimaryAction() {",
    "  const mode = normalizeText(priorityPrimaryAction?.dataset.mode);",
    "  const action = normalizeText(priorityPrimaryAction?.dataset.action);",
    "  const provider = normalizeText(priorityPrimaryAction?.dataset.provider);",
    "  if (!mode || !action || !(priorityPrimaryAction instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "",
    "  priorityPrimaryAction.disabled = true;",
    "  try {",
    "    if (mode === 'journey') {",
    "      setText(",
    "        priorityReason,",
    "        action === 'trust'",
    "          - 'Autorizando this host and currentizando o shell oficial...'",
    "          : 'Executing the recommended local journey for this host...',",
    "      );",
    "      if (journeyTrustActionButton instanceof HTMLButtonElement) {",
    "        journeyTrustActionButton.dataset.mode = action === 'trust' ? 'trust' : 'journey';",
    "        journeyTrustActionButton.dataset.action = action === 'trust' ? '' : action;",
    "      }",
    "      await runJourneyTrustAction();",
    "      return;",
    "    }",
    "",
    "    if (mode === 'remote') {",
    "      setText(priorityReason, 'Executing the recommended remote step for this host...');",
    "      if (remoteRecommendedActionButton instanceof HTMLButtonElement) {",
    "        remoteRecommendedActionButton.dataset.action = action;",
    "        remoteRecommendedActionButton.dataset.provider = provider;",
    "      }",
    "      await runOfficialRemoteAction(action, provider);",
    "    }",
    "  } finally {",
    "    priorityPrimaryAction.disabled = false;",
    "  }",
    "}",
    "",
    "function buildPriorityReason(plan, manifest, report) {",
    "  switch (plan?.primaryAction) {",
    "    case 'go':",
    "      return 'This host still needs the official shortcut to install, start the runtime, and open the best ready surface.';",
    "    case 'trust':",
    "      return 'The local runtime is already up, but this host still needs trust before mutable actions, local writes, or persisted deliveries.';",
    "    case 'remote':",
    "      return normalizeText(report?.recommendedPathReason)",
    "        || 'O runtime local is ready, but o access remote oficial still pede rollout guiado.';",
    "    case 'open-local':",
    "      return 'The local runtime and official shell are already ready. Open the shell now and keep remote as a secondary route.';",
    "    default:",
    "      return normalizeText(manifest?.summary) || 'Use the official recommendation of this host to avoid routes paralelas.';",
    "  }",
    "}",
    "",
    "function formatReadinessStep(step) {",
    "  const title = normalizeText(step?.title || step?.id || 'step');",
    "  const description = normalizeText(step?.description);",
    "  return '<strong>' + title + ':</strong> ' + (description || 'No description.');",
    "}",
    "",
    "function formatJourneyStage(stage) {",
    "  const title = normalizeText(stage?.title || stage?.id || 'stage');",
    "  const command = normalizeText(stage?.command);",
    "  const summary = normalizeText(stage?.summary);",
    "  return '<strong>' + title + ':</strong> ' + (command || summary || 'No summary.');",
    "}",
    "",
    "function renderPriorityActions(manifest, report) {",
    "  const plan = manifest?.recommendedPlan;",
    "  const primaryAction = normalizeText(plan?.primaryAction);",
    "  const localAppUrl = normalizeText(manifest?.local?.appUrl);",
    "  const remoteAppUrl = normalizeText(plan?.remoteRecommendation?.appUrl || report?.actions?.open?.appUrl || report?.actions?.open?.url);",
    "  const remoteCommand = normalizeText(plan?.remoteRecommendation?.command || report?.actions?.go?.command || report?.actions?.apply?.command);",
    "  const launcherCommand = normalizeText(plan?.launcherRecommendation?.command);",
    "  const recommendedRemoteAction = normalizeText(report?.actions?.recommendedAction);",
    "  const recommendedRemoteProvider = normalizeText(report?.actions?.recommendedProvider);",
    "  const recommendedRemoteConfig = recommendedRemoteAction ? report?.actions?.[recommendedRemoteAction] : null;",
    "",
    "  resetPriorityActions();",
    "",
    "  if (primaryAction === 'go') {",
    "    showPriorityRunAction(priorityPrimaryAction, 'Run official shortcut', 'journey', 'go', '');",
    "  } else if (primaryAction === 'trust') {",
    "    showPriorityRunAction(priorityPrimaryAction, 'Autorizar this host', 'journey', 'trust', '');",
    "  } else if (primaryAction === 'remote' && recommendedRemoteAction && recommendedRemoteConfig) {",
    "    showPriorityRunAction(",
    "      priorityPrimaryAction,",
    "      normalizeText(recommendedRemoteConfig.label) || normalizeText(plan?.primaryLabel) || 'Run remote step',",
    "      'remote',",
    "      recommendedRemoteAction,",
    "      recommendedRemoteProvider,",
    "    );",
    "  } else if (normalizeText(plan?.primaryCommand)) {",
    "    showCopyAction(",
    "      priorityPrimaryCopy,",
    "      normalizeText(plan?.primaryLabel) || 'Copy main command',",
    "      normalizeText(plan.primaryCommand),",
    "    );",
    "  } else if (normalizeText(plan?.openTarget)) {",
    "    showOpenAction(",
    "      priorityPrimaryOpen,",
    "      normalizeText(plan?.primaryLabel) || 'Abrir now',",
    "      normalizeText(plan.openTarget),",
    "    );",
    "  }",
    "",
    "  if (primaryAction === 'go' || primaryAction === 'trust') {",
    "    if (!showOpenAction(prioritySecondaryOpen, 'Abrir shell local', localAppUrl) && launcherCommand) {",
    "      showCopyAction(prioritySecondaryCopy, 'Instalar launcher oficial', launcherCommand);",
    "    }",
    "    return;",
    "  }",
    "",
    "  if (primaryAction === 'remote') {",
    "    if (!showOpenAction(prioritySecondaryOpen, 'Abrir shell local', localAppUrl) && launcherCommand) {",
    "      showCopyAction(prioritySecondaryCopy, 'Instalar launcher oficial', launcherCommand);",
    "    }",
    "    return;",
    "  }",
    "",
    "  if (remoteAppUrl) {",
    "    if (showOpenAction(prioritySecondaryOpen, 'Abrir shell remote', remoteAppUrl)) {",
    "      return;",
    "    }",
    "  }",
    "",
    "  if (remoteCommand) {",
    "    if (showCopyAction(prioritySecondaryCopy, 'Copiar path remote', remoteCommand)) {",
    "      return;",
    "    }",
    "  }",
    "",
    "  if (launcherCommand) {",
    "    showCopyAction(prioritySecondaryCopy, 'Instalar launcher oficial', launcherCommand);",
    "  }",
    "}",
    "",
    "function renderProfileRoute(summaryTarget, actionTarget, summary, command, fallbackCommand) {",
    "  setText(summaryTarget, summary);",
    "  if (!(actionTarget instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  actionTarget.hidden = false;",
    "  actionTarget.setAttribute('data-copy', command || fallbackCommand || '');",
    "}",
    "",
    "function renderRouteCard(titleTarget, summaryTarget, stepsTarget, actionTarget, config) {",
    "  setText(titleTarget, config.title);",
    "  setText(summaryTarget, config.summary);",
    "  renderList(stepsTarget, config.steps || []);",
    "  if (actionTarget instanceof HTMLButtonElement) {",
    "    actionTarget.hidden = false;",
    "    actionTarget.textContent = config.actionLabel;",
    "    actionTarget.setAttribute('data-copy', config.actionCommand || '');",
    "  }",
    "}",
    "",
    "function renderProfileRecommendations(manifest, report) {",
    "  const commands = manifest?.commands || {};",
    "  const localReady = manifest?.local?.ready === true;",
    "  const hostAuthorized = manifest?.auth?.authorizedHost;",
    "  const remoteReady = manifest?.officialRemote?.ready === true;",
    "",
    "  const devSummary = localReady",
    "    - 'Local runtime is ready. Open the official shell and use the repository to iterate on the contract.'",
    "    : 'Start the local runtime through the official shortcut to finish setup, build, and runtime shell.';",
    "  const devCommand = localReady ? (commands.start || commands.go || 'npm run ops:start') : (commands.go || 'npm run ops:go');",
    "",
    "  const operatorSummary = hostAuthorized === false",
    "    - 'This host still needs trust. Validate readiness with local trust before operating nodes, channels, and transports.'",
    "    : remoteReady",
    "      - 'Host and official remote are ready. Use the operational mesh below to review nodes, transports and extensions before of the ready check completo.'",
    "      : 'local host ready. Complete the official remote access path before opening operation outside this machine.';",
    "  const operatorCommand = hostAuthorized === false",
    "    - (commands.ready || 'npm run ops:ready -- --trust-local')",
    "    : remoteReady",
    "      - (commands.ready || 'npm run ops:ready -- --trust-local')",
    "      : (commands.remoteGo || 'npm run ops:remote:go');",
    "",
    "  const headlessSummary = localReady",
    "    - 'Use the CLI and REPL as the main harness for diagnostics, automation, and operation without a graphical shell.'",
    "    : 'Start with the CLI to check the host and move to the REPL when the runtime is ready.';",
    "  const headlessCommand = localReady ? 'npm run cli:repl' : (commands.ready || 'npm run cli -- status');",
    "",
    "  renderProfileRoute(priorityDevSummary, priorityDevAction, devSummary, devCommand, 'npm run ops:go');",
    "  renderProfileRoute(",
    "    priorityOperatorSummary,",
    "    priorityOperatorAction,",
    "    operatorSummary,",
    "    operatorCommand,",
    "    'npm run ops:ready -- --trust-local',",
    "  );",
    "  renderProfileRoute(",
    "    priorityHeadlessSummary,",
    "    priorityHeadlessAction,",
    "    headlessSummary,",
    "    headlessCommand,",
    "    'npm run cli -- status',",
    "  );",
    "}",
    "",
    "function renderAlternativeRoutes(manifest, report) {",
    "  const commands = manifest?.commands || {};",
    "  const localReady = manifest?.local?.ready === true;",
    "  const localAppUrl = normalizeText(manifest?.local?.appUrl);",
    "  const remoteReady = manifest?.officialRemote?.ready === true;",
    "  const remoteAppUrl = normalizeText(manifest?.officialRemote?.appUrl || report?.remote?.appUrl);",
    "  const hostAuthorized = manifest?.auth?.authorizedHost;",
    "",
    "  const devConfig = localReady",
    "    - {",
    "        title: 'Open the shell and continue in the repo',",
    "        summary: localAppUrl",
    "          - 'O runtime local already is ready. Open the official shell, valide o contrato and siga iterando in the repo.'",
    "          : 'O runtime local already is ready. Follow via the official shell and continue in the repo.',",
    "        steps: [",
    "          '<code>' + normalizeText(commands.start || 'npm run ops:start') + '</code>',",
    "          localAppUrl ? '<strong>Shell local:</strong> ' + localAppUrl : '<code>npm run cli -- status</code>',",
    "          '<code>npm run qa:regression</code>',",
    "        ],",
    "        actionLabel: 'Copy Dev',",
    "        actionCommand: normalizeText(commands.start || commands.go || 'npm run ops:start'),",
    "      }",
    "    : {",
    "        title: 'Start the runtime and validate the contract',",
    "        summary: 'Best for people developing in the official repo who still need to complete setup, build, and local shell.',",
    "        steps: [",
    "          '<code>npm install</code>',",
    "          '<code>npm run setup</code>',",
    "          '<code>' + normalizeText(commands.go || 'npm run ops:go') + '</code>',",
    "        ],",
    "        actionLabel: 'Copy Dev',",
    "        actionCommand: normalizeText(commands.go || 'npm run ops:go'),",
    "      };",
    "",
    "  const operatorConfig = hostAuthorized === false",
    "    - {",
    "        title: 'Release host and review the mesh',",
    "        summary: 'The local runtime responds, but this host still needs trust before mutable actions and supervised operation.',",
    "        steps: [",
    "          '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "          '<code>' + normalizeText(commands.trust || '/hostauth trust') + '</code>',",
    "          '<code>npm run test:nodes:smoke</code>',",
    "        ],",
    "        actionLabel: 'Copy Operator',",
    "        actionCommand: normalizeText(commands.ready || 'npm run ops:ready -- --trust-local'),",
    "      }",
    "    : !remoteReady",
    "      - {",
    "          title: 'Feche o access remote oficial',",
    "          summary: 'The local host is ready. The best next operational cut is completing the official remote route before opening operation outside this machine.',",
    "          steps: [",
    "            '<code>' + normalizeText(commands.remoteGo || 'npm run ops:remote:go') + '</code>',",
    "            remoteAppUrl ? '<strong>Expected remote shell:</strong> ' + remoteAppUrl : '<strong>remote:</strong> rollout still pending',",
    "            '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "          ],",
    "          actionLabel: 'Copy Operator',",
    "          actionCommand: normalizeText(commands.remoteGo || 'npm run ops:remote:go'),",
    "        }",
    "      : {",
    "          title: 'Validate mesh, access, and providers',",
    "          summary: 'Host and official remote are ready. First use the shell operational mesh to review nodes, transports and extensions; then close a checagem completa.',",
    "          steps: [",
    "            '<strong>Operational mesh:</strong> use os cards compactos de nodes, transports and extensions in the ZavorthControl.',",
    "            '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "            '<code>npm run nodes:doctor -- --json</code>',",
    "            '<code>npm run test:nodes:smoke</code>',",
    "          ],",
    "          actionLabel: 'Copy Operator',",
    "          actionCommand: normalizeText(commands.ready || 'npm run ops:ready -- --trust-local'),",
    "        };",
    "",
    "  const headlessConfig = localReady",
    "    - {",
    "        title: 'Operar only por terminal',",
    "        summary: 'O runtime local already is ready. Use the CLI and REPL as the main harness for diagnostics, automation, and operation without a graphical shell.',",
    "        steps: [",
    "          '<code>npm run cli -- status</code>',",
    "          '<code>npm run cli:repl</code>',",
    "          '<code>npm run nodes:doctor -- --json</code>',",
    "        ],",
    "        actionLabel: 'Copy Headless',",
    "        actionCommand: 'npm run cli:repl',",
    "      }",
    "    : {",
    "        title: 'Checar o host by the terminal',",
    "        summary: 'Best for those who want to validate the host without depending on of the shell grafico before subir tudo.',",
    "        steps: [",
    "          '<code>npm run cli -- status</code>',",
    "          '<code>' + normalizeText(commands.ready || 'npm run ops:ready -- --trust-local') + '</code>',",
    "          '<code>npm run cli:repl</code>',",
    "        ],",
    "        actionLabel: 'Copy Headless',",
    "        actionCommand: 'npm run cli -- status',",
    "      };",
    "",
    "  renderRouteCard(altDevTitle, altDevSummary, altDevSteps, altDevAction, devConfig);",
    "  renderRouteCard(",
    "    altOperatorTitle,",
    "    altOperatorSummary,",
    "    altOperatorSteps,",
    "    altOperatorAction,",
    "    operatorConfig,",
    "  );",
    "  renderRouteCard(",
    "    altHeadlessTitle,",
    "    altHeadlessSummary,",
    "    altHeadlessSteps,",
    "    altHeadlessAction,",
    "    headlessConfig,",
    "  );",
    "}",
    "",
    "function renderPriorityState(manifestPayload, journeyPayload, remotePayload) {",
    "  const manifest = manifestPayload?.manifest;",
    "  const journeyReport = journeyPayload?.report;",
    "  const remoteReport = remotePayload?.report;",
    "  const plan = manifest?.recommendedPlan;",
    "",
    "  setText(",
    "    prioritySummary,",
    "    normalizeText(plan?.primarySummary)",
    "      || normalizeText(manifest?.summary)",
    "      || normalizeText(remoteReport?.summary)",
    "      || 'Use the official recommendation of this host to continue without ambiguidade.',",
    "  );",
    "  setText(priorityReason, buildPriorityReason(plan, manifest, remoteReport));",
    "",
    "  let items = [];",
    "  if (plan?.primaryAction === 'remote' && Array.isArray(remoteReport?.nextSteps) && remoteReport.nextSteps.length > 0) {",
    "    items = remoteReport.nextSteps.slice(0, 3).map((entry) => normalizeText(entry));",
    "  } else if ((plan?.primaryAction === 'go' || plan?.primaryAction === 'trust') && Array.isArray(journeyReport?.phases) && journeyReport.phases.length > 0) {",
    "    items = journeyReport.phases.slice(0, 3).map((stage) => formatJourneyStage(stage));",
    "  } else if (Array.isArray(manifest?.nextSteps) && manifest.nextSteps.length > 0) {",
    "    items = manifest.nextSteps.slice(0, 3).map((step) => formatReadinessStep(step));",
    "  } else if (Array.isArray(journeyReport?.phases) && journeyReport.phases.length > 0) {",
    "    items = journeyReport.phases.slice(0, 3).map((stage) => formatJourneyStage(stage));",
    "  } else if (Array.isArray(remoteReport?.nextSteps) && remoteReport.nextSteps.length > 0) {",
    "    items = remoteReport.nextSteps.slice(0, 3).map((entry) => normalizeText(entry));",
    "  }",
    "",
    "  renderList(priorityNextSteps, items.length > 0 ? items : ['Nothing else to do now.']);",
    "  renderPriorityActions(manifest, remoteReport);",
    "  renderProfileRecommendations(manifest, remoteReport);",
    "  renderAlternativeRoutes(manifest, remoteReport);",
    "  renderProtectedCardHierarchy(manifest, remoteReport);",
    "  renderRemoteActionControls(remoteReport);",
    "}",
    "",
    "async function validateProtectedAccess(token, persist) {",
    "  if (!token) {",
    "    setText(authCopy, 'Paste a valid token before continuing.');",
    "    return;",
    "  }",
    "",
    "  if (authValidateButton) {",
    "    authValidateButton.disabled = true;",
    "  }",
    "",
    "  try {",
    "    const validationResponse = await fetch('/api/auth/validate', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify({ token }),",
    "    });",
    "    const validationPayload = await validationResponse.json().catch(() => null);",
    "    if (!validationResponse.ok || !validationPayload?.ok) {",
    "      throw new Error(validationPayload?.error || 'Token invalid.');",
    "    }",
    "",
    "    if (persist) {",
    "      writeStoredToken(token);",
    "    }",
    "",
    "    await refreshProtectedShellState(token);",
    "    setText(authCopy, 'Token validated. manifest, journey and access remote oficial carregados.');",
    "  } catch (error: unknown) {",
    "    writeStoredToken('');",
    "    protectedShellUnlocked = false;",
    "    closeGatewayControlSocket('Token required');",
    "    setText(prioritySummary, 'Validate the token to see this host official recommendation.');",
    "    setText(priorityReason, 'The shell uses the official manifest to explain what to of the now, why this is the best path, and what happens next.');",
    "    renderList(priorityNextSteps, ['Token not validated.']);",
    "    renderProfileRecommendations(null, null);",
    "    renderAlternativeRoutes(null, null);",
    "    renderProtectedCardHierarchy(null, null);",
    "    renderJourneyActionControls(null, null);",
    "    renderRemoteActionControls(null);",
    "    resetPriorityActions();",
    "    renderList(manifestLaunchers, ['Token not validated.']);",
    "    renderList(installJourney, ['Token not validated.']);",
    "    renderList(remoteAccessSummary, ['Token not validated.']);",
    "    operationalMeshExpanded.nodes = false;",
    "    operationalMeshExpanded.channels = false;",
    "    operationalMeshExpanded.transports = false;",
    "    operationalMeshExpanded.extensions = false;",
    "    renderOperationalMeshSummary(null, null, null, null, null, null, null, null, null, null);",
    "    renderSessionWorkspace(null);",
    "    renderLearningMemory(null, null, null);",
    "    renderReplayLearningControlPlanePanel(null);",
    "    renderDistributedRuntimeControlPlanePanel(null);",
    "    renderOperatorCockpit();",
    "    setText(authCopy, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (authValidateButton) {",
    "      authValidateButton.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installProtectedAccessForm() {",
    "  if (!(authInput instanceof HTMLInputElement) || !authValidateButton) {",
    "    return;",
    "  }",
    "",
    "  authValidateButton.addEventListener('click', () => {",
    "    void validateProtectedAccess(authInput.value.trim(), true);",
    "  });",
    "",
    "  authInput.addEventListener('keydown', (event) => {",
    "    if (event.key === 'Enter') {",
    "      event.preventDefault();",
    "      void validateProtectedAccess(authInput.value.trim(), true);",
    "    }",
    "  });",
    "",
    "  const storedToken = readStoredToken();",
    "  if (storedToken) {",
    "    authInput.value = storedToken;",
    "    void validateProtectedAccess(storedToken, false);",
    "  }",
    "}",
    "",
    "async function runOperationalMeshAction(kind) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    if (kind === 'nodes') {",
    "      setOperationalActionStatus(opsNodesStatus, 'Validate the token before reviewing the Node Mesh.');",
    "    } else if (kind === 'channels') {",
    "      setOperationalActionStatus(opsChannelsStatus, 'Validate the token before reviewing the Channel Mesh.');",
    "    } else if (kind === 'transports') {",
    "      setOperationalActionStatus(opsTransportsStatus, 'Validate the token before reviewing the remote plan.');",
    "    } else {",
    "      setOperationalActionStatus(opsExtensionsStatus, 'Validate the token before currentizar o catalog de extensions.');",
    "    }",
    "    return;",
    "  }",
    "",
    "  const button = kind === 'nodes'",
    "    - opsNodesAction",
    "    : kind === 'channels'",
    "      - opsChannelsAction",
    "    : kind === 'transports'",
    "      - opsTransportsAction",
    "      : opsExtensionsAction;",
    "  if (!(button instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "",
    "  const mode = normalizeText(button.dataset.mode) || 'collapse';",
    "  const targetId = normalizeText(button.dataset.targetId);",
    "  if (mode === 'collapse') {",
    "    operationalMeshExpanded[kind] = false;",
    "    if (kind === 'nodes') {",
    "      renderNodesOperationalCard();",
    "    } else if (kind === 'channels') {",
    "      renderChannelsOperationalCard();",
    "    } else if (kind === 'transports') {",
    "      renderTransportsOperationalCard();",
    "    } else {",
    "      renderExtensionsOperationalCard();",
    "    }",
    "    return;",
    "  }",
    "",
    "  button.disabled = true;",
    "  try {",
    "    if (kind === 'nodes') {",
    "      const selectedId = normalizeText(targetId || operationalMeshSelection.nodes);",
    "      const includeDoctor = mode === 'nodes-open' || mode === 'nodes-doctor';",
    "      setOperationalActionStatus(",
    "        opsNodesStatus,",
    "        includeDoctor ? 'Loading Node Mesh panel...' : 'Updating Node Mesh focus...',",
    "      );",
    "      const payload = await fetchNodeOperationalPanel(token, selectedId, includeDoctor);",
    "      operationalMeshData.nodeDoctor = payload.doctorPayload || operationalMeshData.nodeDoctor;",
    "      operationalMeshData.nodeActivity = payload.activityPayload || null;",
    "      operationalMeshData.nodeCapabilities = payload.capabilitiesPayload || null;",
    "      operationalMeshData.nodeBootstrap = payload.nodeBootstrapPayload || null;",
    "      if (payload.nodeMeshPayload?.ok !== false) {",
    "        operationalMeshData.nodes = payload.nodeMeshPayload;",
    "      }",
    "      operationalMeshExpanded.nodes = true;",
    "      renderNodesOperationalCard();",
    "      setOperationalActionStatus(",
    "        opsNodesStatus,",
    "        normalizeText(payload?.doctorPayload?.doctor?.summary)",
    "          || (selectedId ? 'Node Mesh panel updated for the selected focus.' : 'Node Mesh Panel aberto.'),",
    "      );",
    "      return;",
    "    }",
    "",
    "    if (kind === 'channels') {",
    "      const selectedId = normalizeText(targetId || operationalMeshSelection.channels);",
    "      setOperationalActionStatus(",
    "        opsChannelsStatus,",
    "        mode === 'channels-open' ? 'Opening Channel Mesh panel...' : 'Updating Channel Mesh focus...',",
    "      );",
    "      const payload = await fetchChannelOperationalPanel(token, selectedId);",
    "      operationalMeshExpanded.channels = true;",
    "      operationalMeshData.channels = payload.channelMeshPayload;",
    "      operationalMeshData.channelInstall = payload.channelInstallPayload;",
    "      operationalMeshData.channelDoctor = payload.channelDoctorPayload;",
    "      operationalMeshData.channelAssistant = payload.channelAssistantPayload;",
    "      operationalMeshData.channelDetail = payload.channelDetailPayload;",
    "      renderChannelsOperationalCard();",
    "      setOperationalActionStatus(",
    "        opsChannelsStatus,",
    "        normalizeText(payload?.channelDoctorPayload?.doctor?.summary)",
    "          || (selectedId ? 'Channel Mesh panel updated for the selected focus.' : 'Channel Mesh Panel aberto.'),",
    "      );",
    "      return;",
    "    }",
    "",
    "    if (kind === 'transports') {",
    "      const selectedId = normalizeText(targetId || operationalMeshSelection.transports);",
    "      setOperationalActionStatus(",
    "        opsTransportsStatus,",
    "        mode === 'transports-open' ? 'Opening remote panel...' : 'Updating remote plan...',",
    "      );",
    "      const payload = await fetchTransportOperationalPanel(token, selectedId, Boolean(selectedId));",
    "      operationalMeshData.transports = payload.transportPayload;",
    "      operationalMeshData.transportHistory = payload.historyPayload;",
    "      operationalMeshExpanded.transports = true;",
    "      renderTransportsOperationalCard();",
    "      setOperationalActionStatus(",
    "        opsTransportsStatus,",
    "        selectedId ? 'Remote panel updated for the selected focus.' : 'Remote plan updated.',",
    "      );",
    "      return;",
    "    }",
    "",
    "    const selectedId = normalizeText(targetId || operationalMeshSelection.extensions);",
    "    setOperationalActionStatus(",
    "      opsExtensionsStatus,",
].join('\n');
