import { asErrorLike } from '../../utils/errorLike';
export const runtimeShellScriptPart1Seg1: string = [
    "const root = document.querySelector('#runtime-handoff');",
    "const runtimeStatus = document.querySelector('#runtime-shell-status');",
    "const authStatus = document.querySelector('#runtime-shell-auth');",
    "const originLabel = document.querySelector('#runtime-shell-origin');",
    "const gatewayStatus = document.querySelector('#runtime-shell-gateway');",
    "const meshStatus = document.querySelector('#runtime-shell-mesh');",
    "const gatewayStatusDetail = document.querySelector('#gateway-status-detail');",
    "const gatewayDomainDetail = document.querySelector('#gateway-domain-detail');",
    "const nodeCountDetail = document.querySelector('#node-count-detail');",
    "const transportCountDetail = document.querySelector('#transport-count-detail');",
    "const externalWebLink = document.querySelector('#open-external-web-client');",
    "const externalDocsLink = document.querySelector('#open-external-docs');",
    "const externalWebCopy = document.querySelector('#external-web-copy');",
    "const authInput = document.querySelector('#runtime-auth-token');",
    "const authValidateButton = document.querySelector('#runtime-auth-validate');",
    "const authCopy = document.querySelector('#runtime-auth-copy');",
    "const manifestLaunchers = document.querySelector('#manifest-launchers');",
    "const installJourney = document.querySelector('#install-journey');",
    "const remoteAccessSummary = document.querySelector('#remote-access-summary');",
    "const manifestCard = document.querySelector('#manifest-card');",
    "const journeyCard = document.querySelector('#journey-card');",
    "const remoteCard = document.querySelector('#remote-card');",
    "const journeyCardNote = document.querySelector('#journey-card-note');",
    "const remoteCardNote = document.querySelector('#remote-card-note');",
    "const journeyTrustActionButton = document.querySelector('#journey-trust-action');",
    "const journeyRefreshActionButton = document.querySelector('#journey-refresh-action');",
    "const journeyActionStatus = document.querySelector('#journey-action-status');",
    "const remoteRecommendedActionButton = document.querySelector('#remote-recommended-action');",
    "const remoteVerifyActionButton = document.querySelector('#remote-verify-action');",
    "const remoteActionStatus = document.querySelector('#remote-action-status');",
    "const opsNodesState = document.querySelector('#ops-nodes-state');",
    "const opsNodesSummary = document.querySelector('#ops-nodes-summary');",
    "const opsNodesStatus = document.querySelector('#ops-nodes-status');",
    "const opsNodesDetails = document.querySelector('#ops-nodes-details');",
    "const opsNodesAction = document.querySelector('#ops-nodes-action');",
    "const opsNodesPanel = document.querySelector('#ops-nodes-panel');",
    "const opsNodesPanelTitle = document.querySelector('#ops-nodes-panel-title');",
    "const opsNodesPanelSummary = document.querySelector('#ops-nodes-panel-summary');",
    "const opsNodesPanelActions = document.querySelector('#ops-nodes-panel-actions');",
    "const opsNodesPanelDetails = document.querySelector('#ops-nodes-panel-details');",
    "const opsChannelsState = document.querySelector('#ops-channels-state');",
    "const opsChannelsSummary = document.querySelector('#ops-channels-summary');",
    "const opsChannelsStatus = document.querySelector('#ops-channels-status');",
    "const opsChannelsDetails = document.querySelector('#ops-channels-details');",
    "const opsChannelsAction = document.querySelector('#ops-channels-action');",
    "const opsChannelsPanel = document.querySelector('#ops-channels-panel');",
    "const opsChannelsPanelTitle = document.querySelector('#ops-channels-panel-title');",
    "const opsChannelsPanelSummary = document.querySelector('#ops-channels-panel-summary');",
    "const opsChannelsPanelActions = document.querySelector('#ops-channels-panel-actions');",
    "const opsChannelsPanelDetails = document.querySelector('#ops-channels-panel-details');",
    "const opsKeepaliveState = document.querySelector('#ops-keepalive-state');",
    "const opsKeepaliveSummary = document.querySelector('#ops-keepalive-summary');",
    "const opsKeepaliveStatus = document.querySelector('#ops-keepalive-status');",
    "const opsKeepaliveDetails = document.querySelector('#ops-keepalive-details');",
    "const opsTransportsState = document.querySelector('#ops-transports-state');",
    "const opsTransportsSummary = document.querySelector('#ops-transports-summary');",
    "const opsTransportsStatus = document.querySelector('#ops-transports-status');",
    "const opsTransportsDetails = document.querySelector('#ops-transports-details');",
    "const opsTransportsAction = document.querySelector('#ops-transports-action');",
    "const opsTransportsPanel = document.querySelector('#ops-transports-panel');",
    "const opsTransportsPanelTitle = document.querySelector('#ops-transports-panel-title');",
    "const opsTransportsPanelSummary = document.querySelector('#ops-transports-panel-summary');",
    "const opsTransportsPanelActions = document.querySelector('#ops-transports-panel-actions');",
    "const opsTransportsPanelDetails = document.querySelector('#ops-transports-panel-details');",
    "const opsExtensionsState = document.querySelector('#ops-extensions-state');",
    "const opsExtensionsSummary = document.querySelector('#ops-extensions-summary');",
    "const opsExtensionsStatus = document.querySelector('#ops-extensions-status');",
    "const opsExtensionsDetails = document.querySelector('#ops-extensions-details');",
    "const opsExtensionsAction = document.querySelector('#ops-extensions-action');",
    "const opsExtensionsPanel = document.querySelector('#ops-extensions-panel');",
    "const opsExtensionsPanelTitle = document.querySelector('#ops-extensions-panel-title');",
    "const opsExtensionsPanelSummary = document.querySelector('#ops-extensions-panel-summary');",
    "const opsExtensionsPanelActions = document.querySelector('#ops-extensions-panel-actions');",
    "const opsExtensionsPanelDetails = document.querySelector('#ops-extensions-panel-details');",
    "const operatorCockpitCard = document.querySelector('#operator-cockpit-card');",
    "const operatorActionRail = document.querySelector('#operator-action-rail');",
    "const operatorCockpitStatus = document.querySelector('#operator-cockpit-status');",
    "const cockpitRuntimeState = document.querySelector('#cockpit-runtime-state');",
    "const cockpitRuntimeSummary = document.querySelector('#cockpit-runtime-summary');",
    "const cockpitSessionsState = document.querySelector('#cockpit-sessions-state');",
    "const cockpitSessionsSummary = document.querySelector('#cockpit-sessions-summary');",
    "const cockpitApprovalsState = document.querySelector('#cockpit-approvals-state');",
    "const cockpitApprovalsSummary = document.querySelector('#cockpit-approvals-summary');",
    "const cockpitResourcesState = document.querySelector('#cockpit-resources-state');",
    "const cockpitResourcesSummary = document.querySelector('#cockpit-resources-summary');",
    "const cockpitCompanionsState = document.querySelector('#cockpit-companions-state');",
    "const cockpitCompanionsSummary = document.querySelector('#cockpit-companions-summary');",
    "const cockpitHealthState = document.querySelector('#cockpit-health-state');",
    "const cockpitHealthSummary = document.querySelector('#cockpit-health-summary');",
    "const cockpitNodesState = document.querySelector('#cockpit-nodes-state');",
    "const cockpitNodesSummary = document.querySelector('#cockpit-nodes-summary');",
    "const cockpitTransportsState = document.querySelector('#cockpit-transports-state');",
    "const cockpitTransportsSummary = document.querySelector('#cockpit-transports-summary');",
    "const cockpitIntegrationsState = document.querySelector('#cockpit-integrations-state');",
    "const cockpitIntegrationsSummary = document.querySelector('#cockpit-integrations-summary');",
    "const opsMeshCard = document.querySelector('#ops-mesh-card');",
    "const sessionWorkspaceCard = document.querySelector('#session-workspace-card');",
    "const sessionWorkspaceState = document.querySelector('#session-workspace-state');",
    "const sessionWorkspaceSummary = document.querySelector('#session-workspace-summary');",
    "const sessionWorkspaceStatus = document.querySelector('#session-workspace-status');",
    "const sessionWorkspaceDetails = document.querySelector('#session-workspace-details');",
    "const sessionWorkspaceAction = document.querySelector('#session-workspace-action');",
    "const sessionWorkspaceApprovalsState = document.querySelector('#session-workspace-approvals-state');",
    "const sessionWorkspaceApprovalsSummary = document.querySelector('#session-workspace-approvals-summary');",
    "const sessionWorkspaceApprovals = document.querySelector('#session-workspace-approvals');",
    "const sessionWorkspaceReplayState = document.querySelector('#session-workspace-replay-state');",
    "const sessionWorkspaceReplaySummary = document.querySelector('#session-workspace-replay-summary');",
    "const sessionWorkspaceReplay = document.querySelector('#session-workspace-replay');",
    "const sessionWorkspaceToolsState = document.querySelector('#session-workspace-tools-state');",
    "const sessionWorkspaceToolsSummary = document.querySelector('#session-workspace-tools-summary');",
    "const sessionWorkspaceTools = document.querySelector('#session-workspace-tools');",
    "const sessionWorkspaceDiffsState = document.querySelector('#session-workspace-diffs-state');",
    "const sessionWorkspaceDiffsSummary = document.querySelector('#session-workspace-diffs-summary');",
    "const sessionWorkspaceDiffs = document.querySelector('#session-workspace-diffs');",
    "const sessionWorkspaceCapabilitiesState = document.querySelector('#session-workspace-capabilities-state');",
    "const sessionWorkspaceCapabilitiesSummary = document.querySelector('#session-workspace-capabilities-summary');",
    "const sessionWorkspaceCapabilities = document.querySelector('#session-workspace-capabilities');",
    "const sessionWorkspaceSelfmodState = document.querySelector('#session-workspace-selfmod-state');",
    "const sessionWorkspaceSelfmodSummary = document.querySelector('#session-workspace-selfmod-summary');",
    "const sessionWorkspaceSelfmod = document.querySelector('#session-workspace-selfmod');",
    "const sessionWorkspaceResourcesState = document.querySelector('#session-workspace-resources-state');",
    "const sessionWorkspaceResourcesSummary = document.querySelector('#session-workspace-resources-summary');",
    "const sessionWorkspaceResources = document.querySelector('#session-workspace-resources');",
    "const sessionWorkspaceCompanionsState = document.querySelector('#session-workspace-companions-state');",
    "const sessionWorkspaceCompanionsSummary = document.querySelector('#session-workspace-companions-summary');",
    "const sessionWorkspaceCompanions = document.querySelector('#session-workspace-companions');",
    "const sessionWorkspaceHealthState = document.querySelector('#session-workspace-health-state');",
    "const sessionWorkspaceHealthSummary = document.querySelector('#session-workspace-health-summary');",
    "const sessionWorkspaceHealth = document.querySelector('#session-workspace-health');",
    "const learningMemoryCard = document.querySelector('#learning-memory-card');",
    "const learningState = document.querySelector('#learning-state');",
    "const learningSummary = document.querySelector('#learning-summary');",
    "const learningStatus = document.querySelector('#learning-status');",
    "const learningDetails = document.querySelector('#learning-details');",
    "const learningRefreshAction = document.querySelector('#learning-refresh-action');",
    "const memoryLayeredState = document.querySelector('#memory-layered-state');",
    "const memoryLayeredSummary = document.querySelector('#memory-layered-summary');",
    "const memoryLayeredStatus = document.querySelector('#memory-layered-status');",
    "const memoryLayeredDetails = document.querySelector('#memory-layered-details');",
    "  const memoryLayeredRefreshAction = document.querySelector('#memory-layered-refresh-action');",
    "  const memoryLayeredQuery = document.querySelector('#memory-layered-query');",
    "  const memoryLayeredSearchAction = document.querySelector('#memory-layered-search-action');",
    "  const memoryLayeredSearchResults = document.querySelector('#memory-layered-search-results');",
    "  const opsQualityState = document.querySelector('#ops-quality-state');",
    "  const opsQualitySummary = document.querySelector('#ops-quality-summary');",
    "  const opsQualityStatus = document.querySelector('#ops-quality-status');",
    "  const opsQualityDetails = document.querySelector('#ops-quality-details');",
    "const systemOverlordCard = document.querySelector('#system-overlord-card');",
    "const trustPlaneCard = document.querySelector('#trust-plane-card');",
    "const trustPlaneHostState = document.querySelector('#trust-plane-host-state');",
    "const trustPlaneHostSummary = document.querySelector('#trust-plane-host-summary');",
    "const trustPlaneMcpState = document.querySelector('#trust-plane-mcp-state');",
    "const trustPlaneMcpSummary = document.querySelector('#trust-plane-mcp-summary');",
    "const trustPlaneSkillsState = document.querySelector('#trust-plane-skills-state');",
    "const trustPlaneSkillsSummary = document.querySelector('#trust-plane-skills-summary');",
    "const trustPlaneRuntimeState = document.querySelector('#trust-plane-runtime-state');",
    "const trustPlaneRuntimeSummary = document.querySelector('#trust-plane-runtime-summary');",
    "const trustPlaneRefreshAction = document.querySelector('#trust-plane-refresh-action');",
    "const trustPlanePromoteTrustedAction = document.querySelector('#trust-plane-promote-trusted-action');",
    "const trustPlaneHardenSafeAction = document.querySelector('#trust-plane-harden-safe-action');",
    "const trustPlaneSkillsDenyAction = document.querySelector('#trust-plane-skills-deny-action');",
    "const trustPlaneStatus = document.querySelector('#trust-plane-status');",
    "const trustPlaneHighlights = document.querySelector('#trust-plane-highlights');",
    "const trustPlaneActions = document.querySelector('#trust-plane-actions');",
    "const trustPlaneSurfaces = document.querySelector('#trust-plane-surfaces');",
    "const systemOverlordState = document.querySelector('#system-overlord-state');",
    "const systemOverlordSummary = document.querySelector('#system-overlord-summary');",
    "const systemOverlordAutonomyState = document.querySelector('#system-overlord-autonomy-state');",
    "const systemOverlordAutonomySummary = document.querySelector('#system-overlord-autonomy-summary');",
    "const systemOverlordAdaptersState = document.querySelector('#system-overlord-adapters-state');",
    "const systemOverlordAdaptersSummary = document.querySelector('#system-overlord-adapters-summary');",
    "const systemOverlordKillSwitchState = document.querySelector('#system-overlord-kill-switch-state');",
    "const systemOverlordKillSwitchSummary = document.querySelector('#system-overlord-kill-switch-summary');",
    "const systemOverlordRefreshAction = document.querySelector('#system-overlord-refresh-action');",
    "const systemOverlordKillSwitchEnable = document.querySelector('#system-overlord-kill-switch-enable');",
    "const systemOverlordKillSwitchRelease = document.querySelector('#system-overlord-kill-switch-release');",
    "const systemOverlordCapability = document.querySelector('#system-overlord-capability');",
    "const systemOverlordProfile = document.querySelector('#system-overlord-profile');",
    "const systemOverlordAutonomy = document.querySelector('#system-overlord-autonomy');",
    "const systemOverlordCommand = document.querySelector('#system-overlord-command');",
    "const systemOverlordDryRun = document.querySelector('#system-overlord-dry-run');",
    "const systemOverlordApproved = document.querySelector('#system-overlord-approved');",
    "const systemOverlordRunAction = document.querySelector('#system-overlord-run-action');",
    "const systemOverlordStatus = document.querySelector('#system-overlord-status');",
    "const systemOverlordApprovals = document.querySelector('#system-overlord-approvals');",
    "const systemOverlordCapabilities = document.querySelector('#system-overlord-capabilities');",
    "const systemOverlordActions = document.querySelector('#system-overlord-actions');",
    "const automationControlPlaneCard = document.querySelector('#automation-control-plane-card');",
    "const automationControlPlaneState = document.querySelector('#automation-control-plane-state');",
    "const automationControlPlaneSummary = document.querySelector('#automation-control-plane-summary');",
    "const automationControlPlaneTasksState = document.querySelector('#automation-control-plane-tasks-state');",
    "const automationControlPlaneTasksSummary = document.querySelector('#automation-control-plane-tasks-summary');",
    "const automationControlPlaneMaintenanceState = document.querySelector('#automation-control-plane-maintenance-state');",
    "const automationControlPlaneMaintenanceSummary = document.querySelector('#automation-control-plane-maintenance-summary');",
    "const automationControlPlaneDeliveriesState = document.querySelector('#automation-control-plane-deliveries-state');",
    "const automationControlPlaneDeliveriesSummary = document.querySelector('#automation-control-plane-deliveries-summary');",
    "const automationControlPlaneIntent = document.querySelector('#automation-control-plane-intent');",
    "const automationControlPlaneCreateAction = document.querySelector('#automation-control-plane-create-action');",
    "const automationControlPlaneRefreshAction = document.querySelector('#automation-control-plane-refresh-action');",
    "const automationControlPlaneMaintenanceOnAction = document.querySelector('#automation-control-plane-maintenance-on-action');",
    "const automationControlPlaneMaintenanceOffAction = document.querySelector('#automation-control-plane-maintenance-off-action');",
    "const automationControlPlaneMaintenanceRunAction = document.querySelector('#automation-control-plane-maintenance-run-action');",
    "const automationControlPlaneStatus = document.querySelector('#automation-control-plane-status');",
    "const automationControlPlaneActions = document.querySelector('#automation-control-plane-actions');",
    "const automationControlPlaneTasks = document.querySelector('#automation-control-plane-tasks');",
    "const automationControlPlaneDeliveries = document.querySelector('#automation-control-plane-deliveries');",
    "const watchModeCard = document.querySelector('#watch-mode-card');",
    "const watchModeState = document.querySelector('#watch-mode-state');",
    "const watchModeSummary = document.querySelector('#watch-mode-summary');",
    "const watchModePolicyState = document.querySelector('#watch-mode-policy-state');",
    "const watchModePolicySummary = document.querySelector('#watch-mode-policy-summary');",
    "const watchModeApprovalState = document.querySelector('#watch-mode-approval-state');",
    "const watchModeApprovalSummary = document.querySelector('#watch-mode-approval-summary');",
    "const watchModeReplayState = document.querySelector('#watch-mode-replay-state');",
    "const watchModeReplaySummary = document.querySelector('#watch-mode-replay-summary');",
    "const watchModeTargetWindow = document.querySelector('#watch-mode-target-window');",
    "const watchModeSiteUrl = document.querySelector('#watch-mode-site-url');",
    "const watchModeObjective = document.querySelector('#watch-mode-objective');",
    "const watchModeStrictApproval = document.querySelector('#watch-mode-strict-approval');",
    "const watchModeStartAction = document.querySelector('#watch-mode-start-action');",
    "const watchModeRefreshAction = document.querySelector('#watch-mode-refresh-action');",
    "const watchModeAllowAppAction = document.querySelector('#watch-mode-allow-app-action');",
    "const watchModeAllowSiteAction = document.querySelector('#watch-mode-allow-site-action');",
    "const watchModeStrictOnAction = document.querySelector('#watch-mode-strict-on-action');",
    "const watchModeStrictOffAction = document.querySelector('#watch-mode-strict-off-action');",
    "const watchModeCopyCommand = document.querySelector('#watch-mode-copy-command');",
    "const watchModePauseAction = document.querySelector('#watch-mode-pause-action');",
    "const watchModeResumeAction = document.querySelector('#watch-mode-resume-action');",
    "const watchModeStopAction = document.querySelector('#watch-mode-stop-action');",
    "const watchModeStatus = document.querySelector('#watch-mode-status');",
    "const watchModePreview = document.querySelector('#watch-mode-preview');",
    "const watchModePreviewEmpty = document.querySelector('#watch-mode-preview-empty');",
    "const watchModeNextStep = document.querySelector('#watch-mode-next-step');",
    "const watchModeApprovals = document.querySelector('#watch-mode-approvals');",
    "const watchModeTimeline = document.querySelector('#watch-mode-timeline');",
    "const evalControlPlaneCard = document.querySelector('#eval-control-plane-card');",
    "const evalControlPlaneState = document.querySelector('#eval-control-plane-state');",
    "const evalControlPlaneSummary = document.querySelector('#eval-control-plane-summary');",
    "const evalControlPlaneScorecardsState = document.querySelector('#eval-control-plane-scorecards-state');",
    "const evalControlPlaneScorecardsSummary = document.querySelector('#eval-control-plane-scorecards-summary');",
    "const evalControlPlaneDatasetsState = document.querySelector('#eval-control-plane-datasets-state');",
    "const evalControlPlaneDatasetsSummary = document.querySelector('#eval-control-plane-datasets-summary');",
    "const evalControlPlaneCoverageState = document.querySelector('#eval-control-plane-coverage-state');",
    "const evalControlPlaneCoverageSummary = document.querySelector('#eval-control-plane-coverage-summary');",
    "const evalControlPlaneRefreshAction = document.querySelector('#eval-control-plane-refresh-action');",
    "const evalControlPlaneStatus = document.querySelector('#eval-control-plane-status');",
    "const evalControlPlaneScorecards = document.querySelector('#eval-control-plane-scorecards');",
    "const evalControlPlaneRegressions = document.querySelector('#eval-control-plane-regressions');",
    "const evalControlPlaneDatasets = document.querySelector('#eval-control-plane-datasets');",
    "const hubControlPlaneCard = document.querySelector('#hub-control-plane-card');",
    "const hubControlPlaneState = document.querySelector('#hub-control-plane-state');",
    "const hubControlPlaneSummary = document.querySelector('#hub-control-plane-summary');",
    "const hubControlPlaneIntegrationsState = document.querySelector('#hub-control-plane-integrations-state');",
    "const hubControlPlaneIntegrationsSummary = document.querySelector('#hub-control-plane-integrations-summary');",
    "const hubControlPlanePlatformState = document.querySelector('#hub-control-plane-platform-state');",
    "const hubControlPlanePlatformSummary = document.querySelector('#hub-control-plane-platform-summary');",
    "const hubControlPlaneMcpState = document.querySelector('#hub-control-plane-mcp-state');",
    "const hubControlPlaneMcpSummary = document.querySelector('#hub-control-plane-mcp-summary');",
    "const hubControlPlaneRefreshAction = document.querySelector('#hub-control-plane-refresh-action');",
    "const hubControlPlaneSyncAction = document.querySelector('#hub-control-plane-sync-action');",
    "const hubControlPlaneMcpDoctorAction = document.querySelector('#hub-control-plane-mcp-doctor-action');",
    "const hubControlPlaneStatus = document.querySelector('#hub-control-plane-status');",
    "const hubControlPlaneSurfaces = document.querySelector('#hub-control-plane-surfaces');",
    "const hubControlPlaneActions = document.querySelector('#hub-control-plane-actions');",
    "const hubControlPlaneFeatured = document.querySelector('#hub-control-plane-featured');",
    "const qaControlPlaneCard = document.querySelector('#qa-control-plane-card');",
    "const qaControlPlaneState = document.querySelector('#qa-control-plane-state');",
    "const qaControlPlaneSummary = document.querySelector('#qa-control-plane-summary');",
    "const qaControlPlaneBenchmarksState = document.querySelector('#qa-control-plane-benchmarks-state');",
    "const qaControlPlaneBenchmarksSummary = document.querySelector('#qa-control-plane-benchmarks-summary');",
    "const qaControlPlaneRegressionsState = document.querySelector('#qa-control-plane-regressions-state');",
    "const qaControlPlaneRegressionsSummary = document.querySelector('#qa-control-plane-regressions-summary');",
    "const qaControlPlaneReleaseState = document.querySelector('#qa-control-plane-release-state');",
    "const qaControlPlaneReleaseSummary = document.querySelector('#qa-control-plane-release-summary');",
    "const qaControlPlaneRefreshAction = document.querySelector('#qa-control-plane-refresh-action');",
    "const qaControlPlaneStatus = document.querySelector('#qa-control-plane-status');",
    "const qaControlPlaneBenchmarks = document.querySelector('#qa-control-plane-benchmarks');",
    "const qaControlPlaneSmokes = document.querySelector('#qa-control-plane-smokes');",
    "const qaControlPlaneReleaseGates = document.querySelector('#qa-control-plane-release-gates');",
    "const governanceControlPlaneCard = document.querySelector('#governance-control-plane-card');",
    "const governanceControlPlaneState = document.querySelector('#governance-control-plane-state');",
    "const governanceControlPlaneSummary = document.querySelector('#governance-control-plane-summary');",
    "const governanceControlPlaneTenantsState = document.querySelector('#governance-control-plane-tenants-state');",
    "const governanceControlPlaneTenantsSummary = document.querySelector('#governance-control-plane-tenants-summary');",
    "const governanceControlPlaneTrustState = document.querySelector('#governance-control-plane-trust-state');",
    "const governanceControlPlaneTrustSummary = document.querySelector('#governance-control-plane-trust-summary');",
    "const governanceControlPlanePolicyState = document.querySelector('#governance-control-plane-policy-state');",
    "const governanceControlPlanePolicySummary = document.querySelector('#governance-control-plane-policy-summary');",
    "const governanceControlPlaneRefreshAction = document.querySelector('#governance-control-plane-refresh-action');",
    "const governanceControlPlaneStatus = document.querySelector('#governance-control-plane-status');",
    "const governanceControlPlaneDecisions = document.querySelector('#governance-control-plane-decisions');",
    "const governanceControlPlaneSurfaces = document.querySelector('#governance-control-plane-surfaces');",
    "const governanceControlPlaneActions = document.querySelector('#governance-control-plane-actions');",
    "const replayLearningControlPlaneCard = document.querySelector('#replay-learning-control-plane-card');",
    "const replayLearningControlPlaneState = document.querySelector('#replay-learning-state');",
    "const replayLearningControlPlaneSummary = document.querySelector('#replay-learning-summary');",
    "const replayLearningControlPlaneArtifactsState = document.querySelector('#replay-learning-artifacts-state');",
    "const replayLearningControlPlaneArtifactsSummary = document.querySelector('#replay-learning-artifacts-summary');",
    "const replayLearningControlPlaneLearningState = document.querySelector('#replay-learning-learning-state');",
    "const replayLearningControlPlaneLearningSummary = document.querySelector('#replay-learning-learning-summary');",
    "const replayLearningControlPlaneMemoryState = document.querySelector('#replay-learning-memory-state');",
    "const replayLearningControlPlaneMemorySummary = document.querySelector('#replay-learning-memory-summary');",
    "const replayLearningControlPlaneRefreshAction = document.querySelector('#replay-learning-refresh-action');",
    "const replayLearningControlPlaneStatus = document.querySelector('#replay-learning-status');",
    "const replayLearningControlPlaneActions = document.querySelector('#replay-learning-actions');",
    "const replayLearningControlPlaneArtifacts = document.querySelector('#replay-learning-artifacts');",
    "const replayLearningControlPlaneTimeline = document.querySelector('#replay-learning-timeline');",
    "const ecosystemControlPlaneCard = document.querySelector('#ecosystem-control-plane-card');",
    "const ecosystemControlPlaneState = document.querySelector('#ecosystem-control-plane-state');",
    "const ecosystemControlPlaneSummary = document.querySelector('#ecosystem-control-plane-summary');",
    "const ecosystemControlPlaneSdkState = document.querySelector('#ecosystem-control-plane-sdk-state');",
    "const ecosystemControlPlaneSdkSummary = document.querySelector('#ecosystem-control-plane-sdk-summary');",
    "const ecosystemControlPlaneRegistryState = document.querySelector('#ecosystem-control-plane-registry-state');",
    "const ecosystemControlPlaneRegistrySummary = document.querySelector('#ecosystem-control-plane-registry-summary');",
    "const ecosystemControlPlanePublishState = document.querySelector('#ecosystem-control-plane-publish-state');",
    "const ecosystemControlPlanePublishSummary = document.querySelector('#ecosystem-control-plane-publish-summary');",
    "const ecosystemControlPlaneRefreshAction = document.querySelector('#ecosystem-control-plane-refresh-action');",
    "const ecosystemControlPlaneStatus = document.querySelector('#ecosystem-control-plane-status');",
    "const ecosystemControlPlaneActions = document.querySelector('#ecosystem-control-plane-actions');",
    "const ecosystemControlPlaneGuides = document.querySelector('#ecosystem-control-plane-guides');",
    "const ecosystemControlPlanePublish = document.querySelector('#ecosystem-control-plane-publish');",
    "const distributedRuntimeControlPlaneCard = document.querySelector('#distributed-runtime-control-plane-card');",
    "const distributedRuntimeControlPlaneState = document.querySelector('#distributed-runtime-control-plane-state');",
    "const distributedRuntimeControlPlaneSummary = document.querySelector('#distributed-runtime-control-plane-summary');",
    "const distributedRuntimeChannelsState = document.querySelector('#distributed-runtime-channels-state');",
    "const distributedRuntimeChannelsSummary = document.querySelector('#distributed-runtime-channels-summary');",
    "const distributedRuntimeFleetState = document.querySelector('#distributed-runtime-fleet-state');",
    "const distributedRuntimeFleetSummary = document.querySelector('#distributed-runtime-fleet-summary');",
    "const distributedRuntimeTransportsState = document.querySelector('#distributed-runtime-transports-state');",
    "const distributedRuntimeTransportsSummary = document.querySelector('#distributed-runtime-transports-summary');",
    "const distributedRuntimeSurfacesState = document.querySelector('#distributed-runtime-surfaces-state');",
    "const distributedRuntimeSurfacesSummary = document.querySelector('#distributed-runtime-surfaces-summary');",
    "const distributedRuntimeControlPlaneRefreshAction = document.querySelector('#distributed-runtime-control-plane-refresh-action');",
    "const distributedRuntimeControlPlaneStatus = document.querySelector('#distributed-runtime-control-plane-status');",
    "const distributedRuntimeControlPlaneActions = document.querySelector('#distributed-runtime-control-plane-actions');",
    "const distributedRuntimeControlPlaneChannels = document.querySelector('#distributed-runtime-control-plane-channels');",
    "const distributedRuntimeControlPlaneFleet = document.querySelector('#distributed-runtime-control-plane-fleet');",
    "const distributedRuntimeControlPlaneSurfaces = document.querySelector('#distributed-runtime-control-plane-surfaces');",
    "const runtimeStabilityControlPlaneCard = document.querySelector('#runtime-stability-control-plane-card');",
    "const runtimeStabilityControlPlaneState = document.querySelector('#runtime-stability-control-plane-state');",
    "const runtimeStabilityControlPlaneSummary = document.querySelector('#runtime-stability-control-plane-summary');",
    "const runtimeStabilityFleetState = document.querySelector('#runtime-stability-fleet-state');",
    "const runtimeStabilityFleetSummary = document.querySelector('#runtime-stability-fleet-summary');",
    "const runtimeStabilityTransportsState = document.querySelector('#runtime-stability-transports-state');",
    "const runtimeStabilityTransportsSummary = document.querySelector('#runtime-stability-transports-summary');",
    "const runtimeStabilityKeepaliveState = document.querySelector('#runtime-stability-keepalive-state');",
    "const runtimeStabilityKeepaliveSummary = document.querySelector('#runtime-stability-keepalive-summary');",
    "const runtimeStabilityRecoverState = document.querySelector('#runtime-stability-recover-state');",
    "const runtimeStabilityRecoverSummary = document.querySelector('#runtime-stability-recover-summary');",
    "const runtimeStabilityControlPlaneRefreshAction = document.querySelector('#runtime-stability-control-plane-refresh-action');",
    "const runtimeStabilityControlPlaneStatus = document.querySelector('#runtime-stability-control-plane-status');",
    "const runtimeStabilityControlPlaneActions = document.querySelector('#runtime-stability-control-plane-actions');",
    "const runtimeStabilityControlPlaneCards = document.querySelector('#runtime-stability-control-plane-cards');",
    "const runtimeStabilityControlPlaneProcesses = document.querySelector('#runtime-stability-control-plane-processes');",
    "const rolloutReadinessControlPlaneCard = document.querySelector('#rollout-readiness-control-plane-card');",
    "const rolloutReadinessControlPlaneState = document.querySelector('#rollout-readiness-control-plane-state');",
    "const rolloutReadinessControlPlaneSummary = document.querySelector('#rollout-readiness-control-plane-summary');",
    "const rolloutReadinessQaState = document.querySelector('#rollout-readiness-qa-state');",
    "const rolloutReadinessQaSummary = document.querySelector('#rollout-readiness-qa-summary');",
    "const rolloutReadinessDistributedState = document.querySelector('#rollout-readiness-distributed-state');",
    "const rolloutReadinessDistributedSummary = document.querySelector('#rollout-readiness-distributed-summary');",
    "const rolloutReadinessMaintenanceState = document.querySelector('#rollout-readiness-maintenance-state');",
    "const rolloutReadinessMaintenanceSummary = document.querySelector('#rollout-readiness-maintenance-summary');",
    "const rolloutReadinessPublishState = document.querySelector('#rollout-readiness-publish-state');",
    "const rolloutReadinessPublishSummary = document.querySelector('#rollout-readiness-publish-summary');",
    "const rolloutReadinessControlPlaneRefreshAction = document.querySelector('#rollout-readiness-control-plane-refresh-action');",
    "const rolloutReadinessControlPlaneStatus = document.querySelector('#rollout-readiness-control-plane-status');",
    "const rolloutReadinessControlPlaneActions = document.querySelector('#rollout-readiness-control-plane-actions');",
    "const rolloutReadinessControlPlaneCards = document.querySelector('#rollout-readiness-control-plane-cards');",
    "const rolloutReadinessControlPlanePublish = document.querySelector('#rollout-readiness-control-plane-publish');",
    "const prioritySummary = document.querySelector('#priority-summary');",
    "const priorityReason = document.querySelector('#priority-reason');",
    "const priorityNextSteps = document.querySelector('#priority-next-steps');",
    "const priorityPrimaryAction = document.querySelector('#priority-primary-action');",
    "const priorityPrimaryCopy = document.querySelector('#priority-primary-copy');",
    "const priorityPrimaryOpen = document.querySelector('#priority-primary-open');",
    "const prioritySecondaryCopy = document.querySelector('#priority-secondary-copy');",
    "const prioritySecondaryOpen = document.querySelector('#priority-secondary-open');",
    "const priorityDevSummary = document.querySelector('#priority-dev-summary');",
    "const priorityOperatorSummary = document.querySelector('#priority-operator-summary');",
    "const priorityHeadlessSummary = document.querySelector('#priority-headless-summary');",
    "const priorityDevAction = document.querySelector('#priority-dev-action');",
    "const priorityOperatorAction = document.querySelector('#priority-operator-action');",
    "const priorityHeadlessAction = document.querySelector('#priority-headless-action');",
    "const altDevTitle = document.querySelector('#alt-dev-title');",
    "const altDevSummary = document.querySelector('#alt-dev-summary');",
    "const altDevSteps = document.querySelector('#alt-dev-steps');",
    "const altDevAction = document.querySelector('#alt-dev-action');",
    "const altOperatorTitle = document.querySelector('#alt-operator-title');",
    "const altOperatorSummary = document.querySelector('#alt-operator-summary');",
    "const altOperatorSteps = document.querySelector('#alt-operator-steps');",
    "const altOperatorAction = document.querySelector('#alt-operator-action');",
    "const altHeadlessTitle = document.querySelector('#alt-headless-title');",
    "const altHeadlessSummary = document.querySelector('#alt-headless-summary');",
    "const altHeadlessSteps = document.querySelector('#alt-headless-steps');",
    "const altHeadlessAction = document.querySelector('#alt-headless-action');",
    "const copyButtons = Array.from(document.querySelectorAll('[data-copy]'));",
    "const AUTH_STORAGE_KEY = 'zavorth.runtime.webToken';",
    "const operationalMeshExpanded = {",
    "  nodes: false,",
    "  channels: false,",
    "  transports: false,",
    "  extensions: false,",
    "};",
    "const operationalMeshSelection = {",
    "  nodes: '',",
    "  channels: '',",
    "  transports: '',",
    "  extensions: '',",
    "};",
    "let operationalMeshData = {",
    "  nodes: null,",
    "  nodeDoctor: null,",
    "  nodeActivity: null,",
    "  nodeCapabilities: null,",
    "  nodeBootstrap: null,",
    "  channels: null,",
    "  channelDetail: null,",
    "  channelAction: null,",
    "  channelInstall: null,",
    "  channelDoctor: null,",
    "  channelAssistant: null,",
    "  transports: null,",
    "  transportHistory: null,",
    "  transportDoctor: null,",
    "  extensions: null,",
    "  plugins: null,",
    "  hooks: null,",
    "};",
    "let sessionWorkspaceData = {",
    "  session: null,",
    "  state: null,",
    "  history: null,",
    "  toolRuns: null,",
    "};",
    "let learningMemoryData = {",
    "  learning: null,",
    "  procedures: null,",
    "  search: null,",
    "  lastQuery: '',",
    "};",
    "let systemOverlordData = null;",
    "let watchModeData = null;",
    "let evalControlPlaneData = null;",
    "let automationControlPlaneData = null;",
    "let hubControlPlaneData = null;",
    "let qaControlPlaneData = null;",
    "let governanceControlPlaneData = null;",
    "let replayLearningControlPlaneData = null;",
    "let ecosystemControlPlaneData = null;",
    "let distributedRuntimeControlPlaneData = null;",
    "let runtimeStabilityControlPlaneData = null;",
    "let rolloutReadinessControlPlaneData = null;",
    "let protectedShellUnlocked = false;",
    "let gatewayControlSocket = null;",
    "let gatewayControlSocketSessionId = '';",
    "let gatewayControlSocketExpectedClose = false;",
    "let gatewayControlSocketReconnectTimer = null;",
    "let gatewayControlSocketRefreshTimer = null;",
    "let gatewayControlSocketRequestSequence = 0;",
    "const gatewayControlSocketPendingRequests = new Map();",
    "let publicShellSnapshot = {",
    "  gatewayLabel: 'Verificando',",
    "  initializedDomains: 'Detectando',",
    "  nodeCount: 'Detectando',",
    "  transportCount: 'Detectando',",
    "};",
    "",
    "function setText(target, value) {",
    "  if (target) {",
    "    target.textContent = value;",
    "  }",
    "}",
    "",
    "async function copyTextWithFallback(value, promptLabel = 'Copie o value abaixo:') {",
    "  const text = String(value || '').trim();",
    "  if (!text) {",
    "    return false;",
    "  }",
    "  try {",
    "    if (navigator.clipboard?.writeText) {",
    "      await navigator.clipboard.writeText(text);",
    "      return true;",
    "    }",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err; console.warn('[auto-fix] Empty catch block', err); }",
    "  window.prompt(promptLabel, text);",
    "  return false;",
    "}",
    "",
    "function installCopyButtons() {",
    "  for (const button of copyButtons) {",
    "    button.addEventListener('click', async () => {",
    "      const command = button.getAttribute('data-copy') || '';",
    "      if (!command) {",
    "        return;",
    "      }",
    "      const copied = await copyTextWithFallback(command, 'Copy the command below:');",
    "      if (copied) {",
    "        const previous = button.textContent;",
    "        button.textContent = 'Copiado';",
    "        window.setTimeout(() => {",
    "          button.textContent = previous;",
    "        }, 1500);",
    "      }",
    "    });",
    "  }",
    "}",
    "",
    "function renderList(target, items) {",
    "  if (!target) {",
    "    return;",
    "  }",
    "  if (!Array.isArray(items) || items.length === 0) {",
    "    target.innerHTML = '<li>Nada para mostrar agora.</li>';",
    "    return;",
    "  }",
    "  target.innerHTML = items",
    "    .map((item) => '<li>' + sanitizePanelHtml(item) + '</li>')",
    "    .join('');",
    "}",
    "",
    "function normalizeText(value) {",
    "  return String(value || '').trim();",
    "}",
    "",
    "function escapeHtml(value) {",
    "  return normalizeText(value)",
    "    .replace(/&/g, '&amp;')",
    "    .replace(/</g, '&lt;')",
    "    .replace(/>/g, '&gt;')",
    "    .replace(/\"/g, '&quot;')",
    "    .replace(/'/g, '&#39;');",
    "}",
    "",
    "function sanitizePanelHtml(value) {",
    "  const template = document.createElement('template');",
    "  template.innerHTML = String(value || '');",
    "  const allowedTags = new Set(['STRONG', 'SPAN', 'DIV', 'BUTTON', 'CODE', 'PRE', 'BR', 'SMALL', 'SELECT', 'OPTION']);",
    "  const allowedAttrs = new Set([",
    "    'class',",
    "    'type',",
    "    'value',",
    "    'selected',",
    "    'data-copy',",
    "    'data-cockpit-action',",
    "    'data-cockpit-target',",
    "    'data-operational-kind',",
    "    'data-operational-action',",
    "    'data-operational-target',",
    "    'data-operational-extra',",
    "    'data-operational-copy',",
    "    'data-session-replay-action',",
    "    'data-session-replay-prompt',",
    "    'data-session-replay-summary',",
    "    'data-watch-mode-approval',",
    "    'data-watch-mode-approval-id',",
    "  ]);",
    "  const clean = (root) => {",
    "    for (const child of Array.from(root.childNodes)) {",
    "      if (child.nodeType === Node.TEXT_NODE) {",
    "        continue;",
    "      }",
    "      if (child.nodeType !== Node.ELEMENT_NODE) {",
    "        child.remove();",
    "        continue;",
    "      }",
    "      const element = child;",
    "      if (!allowedTags.has(element.tagName)) {",
    "        element.replaceWith(document.createTextNode(element.textContent || ''));",
    "        continue;",
    "      }",
    "      for (const attr of Array.from(element.attributes)) {",
    "        const name = attr.name.toLowerCase();",
    "        if (name.startsWith('on') || !allowedAttrs.has(name)) {",
    "          element.removeAttribute(attr.name);",
    "        }",
    "      }",
    "      if (element.tagName === 'BUTTON') {",
    "        element.setAttribute('type', 'button');",
    "      }",
    "      clean(element);",
    "    }",
    "  };",
    "  clean(template.content);",
    "  return template.innerHTML;",
    "}",
    "",
    "function hideCopyAction(target) {",
    "  if (!(target instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  target.hidden = true;",
    "  target.setAttribute('data-copy', '');",
    "}",
    "",
    "function hideOpenAction(target) {",
    "  if (!(target instanceof HTMLAnchorElement)) {",
    "    return;",
    "  }",
    "  target.hidden = true;",
    "  target.href = '#';",
    "}",
    "",
    "function hidePriorityRunAction(target) {",
    "  if (!(target instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  target.hidden = true;",
    "  target.disabled = false;",
    "  target.dataset.mode = '';",
    "  target.dataset.action = '';",
    "  target.dataset.provider = '';",
    "}",
    "",
    "function showPriorityRunAction(target, label, mode, action, provider) {",
    "  if (!(target instanceof HTMLButtonElement) || !mode || !action) {",
    "    return false;",
    "  }",
    "  target.hidden = false;",
    "  target.textContent = label;",
    "  target.dataset.mode = mode;",
    "  target.dataset.action = action;",
    "  target.dataset.provider = provider || '';",
    "  return true;",
    "}",
    "",
    "function showCopyAction(target, label, command) {",
    "  if (!(target instanceof HTMLButtonElement) || !command) {",
    "    return false;",
    "  }",
    "  target.hidden = false;",
    "  target.textContent = label;",
    "  target.setAttribute('data-copy', command);",
    "  return true;",
    "}",
    "",
    "function showOpenAction(target, label, href) {",
    "  if (!(target instanceof HTMLAnchorElement) || !href) {",
    "    return false;",
    "  }",
    "  target.hidden = false;",
    "  target.textContent = label;",
    "  target.href = href;",
    "  target.target = '_blank';",
    "  target.rel = 'noreferrer';",
    "  return true;",
    "}",
    "",
    "function resetPriorityActions() {",
    "  hidePriorityRunAction(priorityPrimaryAction);",
    "  hideCopyAction(priorityPrimaryCopy);",
    "  hideOpenAction(priorityPrimaryOpen);",
    "  hideCopyAction(prioritySecondaryCopy);",
].join('\n');
