export const runtimeShellScriptPart5Seg2: string = [
    "  const runId = normalizeText(watchModeData?.run?.runId || watchModeData?.snapshot?.activeRun?.runId);",
    "  if (!runId) {",
    "    setText(watchModeStatus, 'Nao existe run visual ativo para esta acao.');",
    "    return;",
    "  }",
    "",
    "  const button = mode === 'pause'",
    "    ? watchModePauseAction",
    "    : mode === 'resume'",
    "      ? watchModeResumeAction",
    "      : watchModeStopAction;",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    const payload = await postProtectedJson('/api/web/watch-mode/runs/' + encodeURIComponent(runId) + '/' + mode, token, {",
    "      requestedBy: 'web-watch-mode',",
    "    });",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      mode === 'pause'",
    "        ? 'Watch Mode pausado.'",
    "        : mode === 'resume'",
    "          ? 'Watch Mode retomado.'",
    "          : 'Watch Mode parado.',",
    "    );",
    "  } catch (error: unknown) {",
    "    setText(watchModeStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModeApprovalDecision(approvalId, decision) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Valide o token antes de decidir um approval visual.');",
    "    return;",
    "  }",
    "  const runId = normalizeText(watchModeData?.run?.runId || watchModeData?.snapshot?.activeRun?.runId);",
    "  if (!runId || !approvalId) {",
    "    setText(watchModeStatus, 'Approval visual indisponivel neste momento.');",
    "    return;",
    "  }",
    "  try {",
    "    const payload = await postProtectedJson(",
    "      '/api/web/watch-mode/runs/' + encodeURIComponent(runId) + '/approvals/' + encodeURIComponent(approvalId),",
    "      token,",
    "      {",
    "        decision,",
    "        requestedBy: 'web-watch-mode',",
    "      },",
    "    );",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      decision === 'approve'",
    "        ? 'Approval visual liberado.'",
    "        : 'Approval visual negado; o agente vai observar de novo antes de agir.',",
    "    );",
    "  } catch (error: unknown) {",
    "    setText(watchModeStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSystemOverlordSupervisedAction() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Valide o token antes de executar uma acao supervisionada.');",
    "    return;",
    "  }",
    "  const command = normalizeText(systemOverlordCommand?.value);",
    "  if (!command) {",
    "    setText(systemOverlordStatus, 'Informe um comando ou payload curto antes de executar.');",
    "    return;",
    "  }",
    "",
    "  if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "    systemOverlordRunAction.disabled = true;",
    "  }",
    "  try {",
    "    const dryRun = !(systemOverlordDryRun instanceof HTMLInputElement) || systemOverlordDryRun.checked;",
    "    setText(systemOverlordStatus, dryRun ? 'Simulando acao supervisionada...' : 'Executando acao supervisionada...');",
    "    const payload = await postProtectedJson('/api/web/system-overlord/actions', token, {",
    "      capability: normalizeText(systemOverlordCapability?.value) || 'host.shell',",
    "      profile: normalizeText(systemOverlordProfile?.value) || 'safe',",
    "      autonomyLevel: Number(systemOverlordAutonomy?.value || 1) || 1,",
    "      command,",
    "      dryRun,",
    "      approved: systemOverlordApproved instanceof HTMLInputElement ? systemOverlordApproved.checked : false,",
    "      requestedBy: 'web-operator',",
    "      metadata: {",
    "        source: 'web-system-overlord-panel',",
    "      },",
    "    });",
    "    renderSystemOverlordPanel(payload);",
    "    const action = payload?.action || null;",
    "    setText(",
    "      systemOverlordStatus,",
    "      action",
    "        ? 'Acao ' + normalizeText(action.actionId || 'supervisionada') + ' ficou como ' + normalizeText(action.status || 'n/d') + '.'",
    "        : 'Acao supervisionada enviada.',",
    "    );",
    "  } catch (error: unknown) {",
    "    setText(systemOverlordStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "      systemOverlordRunAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runSystemOverlordApprovalDecision(actionId, mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Valide o token antes de decidir approvals.');",
    "    return;",
    "  }",
    "  const normalizedActionId = normalizeText(actionId);",
    "  const normalizedMode = normalizeText(mode);",
    "  if (!normalizedActionId || !normalizedMode) {",
    "    setText(systemOverlordStatus, 'Approval invalido para decisao.');",
    "    return;",
    "  }",
    "",
    "  const decision = normalizedMode === 'reject' ? 'reject' : 'approve';",
    "  const dryRun = normalizedMode === 'approve-dry-run';",
    "  try {",
    "    setText(",
    "      systemOverlordStatus,",
    "      decision === 'reject'",
    "        ? 'Rejeitando approval supervisionado...'",
    "        : dryRun",
    "          ? 'Aprovando approval em dry-run...'",
    "          : 'Aprovando e executando acao supervisionada...',",
    "    );",
    "    const payload = await postProtectedJson(",
    "      '/api/web/system-overlord/approvals/' + encodeURIComponent(normalizedActionId),",
    "      token,",
    "      {",
    "        decision,",
    "        dryRun,",
    "        requestedBy: 'web-operator',",
    "        reason: decision === 'reject'",
    "          ? 'Rejeitado pelo operador na ZavorthControl web.'",
    "          : dryRun",
    "            ? 'Aprovado como dry-run pelo operador na ZavorthControl web.'",
    "            : 'Aprovado para execucao pelo operador na ZavorthControl web.',",
    "      },",
    "    );",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      payload?.approval",
    "        ? 'Approval ' + normalizedActionId + ' ficou como ' + normalizeText(payload.approval.status || 'n/d') + '.'",
    "        : 'Approval decidido.',",
    "    );",
    "  } catch (error: unknown) {",
    "    setText(systemOverlordStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSystemOverlordKillSwitch(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Valide o token antes de operar o kill switch supervisionado.');",
    "    return;",
    "  }",
    "  const activate = normalizeText(mode) !== 'release';",
    "  const button = activate ? systemOverlordKillSwitchEnable : systemOverlordKillSwitchRelease;",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(",
    "      systemOverlordStatus,",
    "      activate",
    "        ? 'Ativando kill switch supervisionado...'",
    "        : 'Liberando kill switch supervisionado...',",
    "    );",
    "    const payload = await postProtectedJson('/api/web/system-overlord/kill-switch', token, {",
    "      active: activate,",
    "      cancelActive: activate,",
    "      requestedBy: 'web-operator',",
    "      reason: activate",
    "        ? 'Kill switch ativado pelo operador na ZavorthControl web.'",
    "        : 'Kill switch liberado pelo operador na ZavorthControl web.',",
    "    });",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      payload?.killSwitch?.active",
    "        ? 'Kill switch ativo. ' + String((payload?.affectedActions || []).length || 0) + ' acao(oes) cancelada(s) ao ativar.'",
    "        : 'Kill switch liberado. Novas acoes supervisionadas podem voltar a rodar.',",
    "    );",
    "  } catch (error: unknown) {",
    "    setText(systemOverlordStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runSystemOverlordActionMutation(actionId, mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Valide o token antes de cancelar ou reverter acoes supervisionadas.');",
    "    return;",
    "  }",
    "  const normalizedActionId = normalizeText(actionId);",
    "  const normalizedMode = normalizeText(mode);",
    "  if (!normalizedActionId || !normalizedMode) {",
    "    setText(systemOverlordStatus, 'Acao supervisionada invalida para mutacao.');",
    "    return;",
    "  }",
    "  const endpoint = normalizedMode === 'rollback'",
    "    ? '/api/web/system-overlord/actions/' + encodeURIComponent(normalizedActionId) + '/rollback'",
    "    : '/api/web/system-overlord/actions/' + encodeURIComponent(normalizedActionId) + '/cancel';",
    "  try {",
    "    setText(",
    "      systemOverlordStatus,",
    "      normalizedMode === 'rollback'",
    "        ? 'Executando rollback supervisionado...'",
    "        : 'Cancelando acao supervisionada...',",
    "    );",
    "    const payload = await postProtectedJson(endpoint, token, {",
    "      requestedBy: 'web-operator',",
    "      reason: normalizedMode === 'rollback'",
    "        ? 'Rollback solicitado pelo operador na ZavorthControl web.'",
    "        : 'Cancelamento solicitado pelo operador na ZavorthControl web.',",
    "    });",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      payload?.action",
    "        ? 'Acao ' + normalizedActionId + ' agora aparece como ' + normalizeText(payload.action.status || 'n/d') + '.'",
    "        : 'Mutacao supervisionada concluida.',",
    "    );",
    "  } catch (error: unknown) {",
    "    setText(systemOverlordStatus, error instanceof Error ? error.message : String(error));",
    "  }",
    "}",
    "",
    "function scrollToCockpitTarget(targetId) {",
    "  const target = document.getElementById(targetId);",
    "  if (!(target instanceof HTMLElement)) {",
    "    return;",
    "  }",
    "  target.scrollIntoView({ behavior: 'smooth', block: 'start' });",
    "  setText(operatorCockpitStatus, 'Saltando para o bloco operacional escolhido.');",
    "  setCardEmphasis(target, 'focus');",
    "  window.setTimeout(() => {",
    "    target.classList.remove('card-focus', 'card-subtle');",
    "  }, 1800);",
    "}",
    "",
    "async function runOperatorCockpitRefresh(button) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(operatorCockpitStatus, 'Valide o token antes de atualizar o cockpit protegido.');",
    "    return;",
    "  }",
    "",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(operatorCockpitStatus, 'Atualizando cockpit, sessions e malha operacional...');",
    "    await refreshProtectedShellState(token);",
    "    setText(operatorCockpitStatus, 'Cockpit atualizado com o estado protegido mais recente.');",
    "  } catch (error: unknown) {",
    "    setText(operatorCockpitStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installOperatorCockpitActions() {",
    "  if (!(operatorActionRail instanceof HTMLElement)) {",
    "    return;",
    "  }",
    "",
    "  operatorActionRail.addEventListener('click', (event) => {",
    "    if (!(event.target instanceof Element)) {",
    "      return;",
    "    }",
    "    const button = event.target.closest('[data-cockpit-action],[data-cockpit-target]');",
    "    if (!(button instanceof HTMLButtonElement)) {",
    "      return;",
    "    }",
    "    event.preventDefault();",
    "    const action = normalizeText(button.dataset.cockpitAction);",
    "    const targetId = normalizeText(button.dataset.cockpitTarget);",
    "    if (action === 'refresh') {",
    "      void runOperatorCockpitRefresh(button);",
    "      return;",
    "    }",
    "    if (targetId) {",
    "      scrollToCockpitTarget(targetId);",
    "    }",
    "  });",
    "}",
    "",
    "function hideOperationalAction(target) {",
    "  if (!(target instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  target.hidden = true;",
    "  target.disabled = false;",
    "  target.dataset.mode = '';",
    "  target.dataset.targetId = '';",
    "}",
    "",
    "function showOperationalAction(target, label, mode = 'collapse', targetId = '') {",
    "  if (!(target instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  target.hidden = false;",
    "  target.textContent = label;",
    "  target.dataset.mode = mode;",
    "  target.dataset.targetId = targetId || '';",
    "}",
    "",
    "function setOperationalActionStatus(target, value) {",
    "  setText(target, value);",
    "}",
    "",
    "function hideOperationalPanel(panel, actionsTarget, detailsTarget) {",
    "  if (panel) {",
    "    panel.hidden = true;",
    "  }",
    "  if (actionsTarget) {",
    "    actionsTarget.innerHTML = '';",
    "  }",
    "  renderList(detailsTarget, ['Abra o painel para revisar o foco operacional deste host.']);",
    "}",
    "",
    "function showOperationalPanel(panel, titleTarget, summaryTarget, actionsTarget, detailsTarget, config) {",
    "  if (panel) {",
    "    panel.hidden = false;",
    "  }",
    "  setText(titleTarget, normalizeText(config?.title) || 'Painel operacional');",
    "  setText(",
    "    summaryTarget,",
    "    normalizeText(config?.summary) || 'Sem detalhe adicional para o foco operacional atual.',",
    "  );",
    "  if (actionsTarget) {",
    "    actionsTarget.innerHTML = normalizeText(config?.actionsHtml) ? sanitizePanelHtml(config.actionsHtml) : '';",
    "  }",
    "  renderList(",
    "    detailsTarget,",
    "    Array.isArray(config?.details) && config.details.length > 0",
    "      ? config.details",
    "      : ['Sem detalhe adicional para o foco operacional atual.'],",
    "  );",
    "}",
    "",
    "function renderNodesOperationalCard() {",
    "  const nodeMesh = operationalMeshData.nodes?.nodeMesh || null;",
    "  const doctor = operationalMeshData.nodeDoctor?.doctor || null;",
    "  const activity = operationalMeshData.nodeActivity?.activity || null;",
    "  const capabilities = operationalMeshData.nodeCapabilities?.capabilities || null;",
    "  const bootstrapDraft = operationalMeshData.nodeBootstrap?.draft || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.nodes?.error",
    "    || operationalMeshData.nodeDoctor?.error",
    "    || operationalMeshData.nodeActivity?.error",
    "    || operationalMeshData.nodeCapabilities?.error,",
    "  );",
    "",
    "  if (!nodeMesh) {",
    "    setText(opsNodesState, 'Indisponivel');",
    "    setText(opsNodesSummary, errorMessage || 'Node Mesh protegido indisponivel neste runtime.');",
    "    renderList(opsNodesDetails, [errorMessage || 'Valide o token para revisar nodes, fila e pairing do host atual.']);",
    "    hideOperationalAction(opsNodesAction);",
    "    hideOperationalPanel(opsNodesPanel, opsNodesPanelActions, opsNodesPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = nodeMesh.summary || {};",
    "  const selected = nodeMesh.selected || null;",
    "  const selectedActivity = nodeMesh.selectedActivity || null;",
    "  const firstIssue = Array.isArray(doctor?.issues) && doctor.issues.length > 0 ? doctor.issues[0] : null;",
    "  const selectedLabel = normalizeText(selected?.label || selected?.id || '');",
    "  const selectedAction = normalizeText(selected?.nextAction || selected?.operatorSummary);",
    "  const selectedId = normalizeText(selected?.id || operationalMeshSelection.nodes);",
    "  const allowlistAudit = selected?.allowlistAudit || null;",
    "  const hostHints = selected?.hostHints || {};",
    "  operationalMeshSelection.nodes = selectedId;",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'nodes',",
    "    Array.isArray(nodeMesh.entries) ? nodeMesh.entries : [],",
    "    selectedId,",
    "    (entry) => entry?.id,",
    "    (entry) => entry?.label || entry?.id,",
    "  );",
    "  setText(",
    "    opsNodesState,",
    "    summary.total",
    "      ? String(summary.online || 0) + '/' + String(summary.total || 0) + ' online'",
    "      : 'Sem nodes',",
    "  );",
    "  setText(",
    "    opsNodesSummary,",
    "    doctor?.status === 'attention'",
    "      ? ((selectedLabel",
    "        ? selectedLabel + ': '",
    "        : '')",
    "        + (normalizeText(firstIssue?.summary || firstIssue?.actionHint) || String((doctor.issues || []).length) + ' pendencia(s) no doctor do Node Mesh.'))",
    "      : selectedLabel",
    "        ? selectedLabel + ': ' + (selectedAction || 'sem proxima acao operacional agora.')",
    "      : (summary.total",
    "        ? String(summary.paired || 0) + ' pareado(s), ' + String(summary.queued || 0) + ' item(ns) na fila.'",
    "        : 'Nenhum node registrado neste host.'),",
    "  );",
    "",
    "  const items = operationalMeshExpanded.nodes",
    "    ? [",
    "        Array.isArray(nodeMesh.entries) && nodeMesh.entries.length > 0",
    "          ? '<strong>Frota visivel:</strong> ' + nodeMesh.entries",
    "            .slice(0, 4)",
    "            .map((entry) => {",
    "              const trust = normalizeText(entry?.trustLabel || entry?.pairingStatus || 'sem trust');",
    "              const label = normalizeText(entry?.label || entry?.id || 'node');",
    "              const status = normalizeText(entry?.status || 'unknown');",
    "              return escapeHtml(label) + ' [' + escapeHtml(status) + '; ' + escapeHtml(trust) + ']';",
    "            })",
    "            .join(' Ã‚Â· ')",
    "          : '<strong>Frota visivel:</strong> nenhum node registrado agora.',",
    "        selectedLabel",
    "          ? '<strong>Selecionado:</strong> ' + escapeHtml(selectedLabel) + ' [' + escapeHtml(normalizeText(selected?.status || 'unknown')) + ']'",
    "          : '<strong>Selecionado:</strong> Nenhum node em foco agora.',",
    "        selected",
    "          ? '<strong>Trust:</strong> ' + escapeHtml(normalizeText(selected?.trustLabel || 'sem policy visivel')) + ' | <strong>Pairing:</strong> ' + escapeHtml(normalizeText(selected?.pairingStatus || 'unknown'))",
    "          : '<strong>Pairing:</strong> Nenhum node selecionado.',",
    "        selectedActivity?.narrative?.operatorSummary",
    "          ? '<strong>Activity:</strong> ' + escapeHtml(normalizeText(selectedActivity.narrative.operatorSummary))",
    "          : '<strong>Activity:</strong> sem fila viva para o node foco.',",
    "        capabilities?.summary",
    "          ? '<strong>Capabilities:</strong> ' + String(capabilities.summary.total || 0) + ' totais, ' + String(capabilities.summary.risky || 0) + ' arriscadas e categorias ' + escapeHtml((capabilities.summary.categories || []).join(', ') || 'n/a') + '.'",
    "          : '<strong>Capabilities:</strong> selecione um node para revisar allowlist e catalogo.',",
    "        selectorRow",
    "          ? '<strong>Alternar foco:</strong> ' + selectorRow",
    "          : '<strong>Alternar foco:</strong> nenhum node registrado agora.',",
    "        normalizeText(doctor?.summary)",
    "          ? '<strong>Doctor:</strong> ' + escapeHtml(normalizeText(doctor.summary))",
    "          : '<strong>Doctor:</strong> sem issues abertas agora.',",
    "        bootstrapDraft?.bootstrap?.command",
    "          ? '<strong>Bootstrap:</strong> draft pendente pronto para copiar no host selecionado.'",
    "          : '<strong>Bootstrap:</strong> sem bootstrap pendente para o node foco.',",
    "        ...((doctor?.issues || []).slice(0, 2).map((issue) =>",
    "          '<strong>' + escapeHtml(normalizeText(issue?.label || issue?.nodeId || 'Node')) + ':</strong> '",
    "          + escapeHtml(normalizeText(issue?.summary || issue?.actionHint || 'Sem observacao.'))",
    "        )),",
    "        '<div class=\"inline-action-row\">' + buildOperationalInlineButton('nodes', 'nodes-doctor', selectedId, 'Rodar doctor do mesh') + '</div>',",
    "      ]",
    "    : [",
    "        selectedLabel",
    "          ? '<strong>Foco:</strong> ' + escapeHtml(selectedLabel) + (selectedAction ? ' - ' + escapeHtml(selectedAction) : '.')",
    "          : '<strong>Pareados:</strong> ' + String(summary.paired || 0) + ' de ' + String(summary.total || 0) + '.',",
    "        firstIssue",
    "          ? '<strong>Proxima acao:</strong> ' + escapeHtml(normalizeText(firstIssue?.actionHint || firstIssue?.recoverKind || doctor?.summary || 'Revisar doctor do mesh.'))",
    "          : '<strong>Doctor:</strong> ' + escapeHtml(normalizeText(doctor?.summary || ('Fila antiga: ' + String(summary.staleQueued || 0) + ' item(ns) e ' + String(summary.expiredDrafts || 0) + ' draft(s) expirado(s).'))),",
    "      ];",
    "  renderList(opsNodesDetails, items);",
    "    if (operationalMeshExpanded.nodes) {",
    "      const approvedCount = Array.isArray(selected?.approvedCapabilityIds) ? selected.approvedCapabilityIds.length : 0;",
    "      const declaredCount = Array.isArray(selected?.capabilityIds) ? selected.capabilityIds.length : 0;",
    "      const maintenance = activity?.maintenance || selectedActivity?.maintenance || selected?.maintenance || null;",
    "      const recoverKind = normalizeText(maintenance?.recoverKind || firstIssue?.recoverKind || '');",
    "      const nodePolicyActionRow = buildNodePolicyActionRow(selected, capabilities);",
    "      const panelButtons = [",
    "        buildOperationalButtonHtml('nodes', 'doctor', 'Rodar doctor do mesh', selectedId),",
    "      ];",
    "      if (selectedId && normalizeText(selected?.pairingStatus) === 'pending') {",
    "        panelButtons.push(buildOperationalButtonHtml('nodes', 'bootstrap', 'Copiar bootstrap', selectedId));",
    "      }",
    "      if (selectedId && recoverKind) {",
    "        panelButtons.push(buildOperationalButtonHtml('nodes', 'recover', 'Aplicar recover', selectedId, recoverKind));",
    "    }",
    "    showOperationalPanel(",
    "      opsNodesPanel,",
    "      opsNodesPanelTitle,",
    "      opsNodesPanelSummary,",
    "      opsNodesPanelActions,",
    "      opsNodesPanelDetails,",
    "      {",
    "        title: selectedLabel || 'Node Mesh',",
    "          summary: pickFirstText([",
    "            activity?.narrative?.operatorSummary,",
    "            selectedActivity?.narrative?.operatorSummary,",
    "            capabilities?.narrative?.operatorSummary,",
    "            selectedAction,",
    "          doctor?.summary,",
    "        ], 'Sem detalhe adicional para o node foco.'),",
    "          actionsHtml: [",
    "            selectorRow,",
    "            buildOperationalInlineButtons(panelButtons),",
    "            nodePolicyActionRow,",
    "          ].filter(Boolean).join(''),",
    "          details: [",
    "            selected",
    "              ? '<strong>Status:</strong> ' + escapeHtml(normalizeText(selected?.status || 'unknown')) + ' | <strong>Trust:</strong> ' + escapeHtml(normalizeText(selected?.trustLabel || 'sem policy visivel'))",
    "              : '<strong>Status:</strong> nenhum node em foco agora.',",
    "            normalizeText(hostHints?.hostname || hostHints?.deviceModel || hostHints?.locationLabel)",
    "              ? '<strong>Host:</strong> ' + escapeHtml(",
    "                [",
    "                  normalizeText(hostHints?.hostname || hostHints?.deviceModel || hostHints?.locationLabel),",
    "                  normalizeText(hostHints?.nodeVersion) ? 'node ' + normalizeText(hostHints.nodeVersion) : '',",
    "                  normalizeText(hostHints?.appVersion) ? 'app ' + normalizeText(hostHints.appVersion) : '',",
    "                ].filter(Boolean).join(' Ã‚Â· '),",
    "              )",
    "              : '<strong>Host:</strong> sem identidade detalhada no snapshot atual.',",
    "            declaredCount",
    "              ? '<strong>Allowlist:</strong> ' + String(approvedCount) + '/' + String(declaredCount) + ' capability(s) aprovada(s) neste host.'",
    "              : '<strong>Allowlist:</strong> nenhum catalogo de capability declarado agora.',",
    "            approvedCount > 0",
    "              ? '<strong>Aprovadas agora:</strong> ' + escapeHtml((selected?.approvedCapabilityIds || []).map((entry) => normalizeText(entry)).filter(Boolean).slice(0, 6).join(', ') || 'n/a')",
    "              : '<strong>Aprovadas agora:</strong> nenhuma capability aprovada neste host.',",
    "            allowlistAudit",
    "              ? '<strong>Ultima policy:</strong> ' + escapeHtml([",
    "                normalizeText(allowlistAudit?.approvedBy) || 'operador nao informado',",
    "                normalizeText(allowlistAudit?.mode) || 'modo nao informado',",
    "                normalizeText(allowlistAudit?.approvedAt) || '',",
    "              ].filter(Boolean).join(' Ã‚Â· '))",
    "              : '<strong>Ultima policy:</strong> sem auditoria recente da allowlist.',",
    "            normalizeText(allowlistAudit?.reason)",
    "              ? '<strong>Motivo da policy:</strong> ' + escapeHtml(normalizeText(allowlistAudit.reason))",
    "              : '<strong>Motivo da policy:</strong> sem justificativa registrada para esta allowlist.',",
    "            (activity?.summary || selectedActivity?.summary)",
    "              ? '<strong>Fila:</strong> ' + String((activity?.summary?.pending ?? selectedActivity?.summary?.pending) || 0) + ' pendente(s), '",
    "                + String((activity?.summary?.claimed ?? selectedActivity?.summary?.claimed) || 0) + ' claimed e '",
    "                + String((activity?.summary?.completedRecently ?? selectedActivity?.summary?.completedRecently) || 0) + ' concluida(s) recentemente.'",
    "              : '<strong>Fila:</strong> sem activity recente para o node foco.',",
    "          maintenance?.supported",
    "            ? '<strong>Maintenance:</strong> ' + escapeHtml(",
    "              pickFirstText([",
    "                maintenance?.latestResultSummary,",
    "                maintenance?.latestAction ? maintenance.latestAction + ' em ' + normalizeText(maintenance.latestStatus || 'estado desconhecido') : '',",
    "                maintenance?.recoverKind,",
    "              ], 'Capability node.maintenance disponivel para repair local.'),",
    "            )",
    "            : '<strong>Maintenance:</strong> node.maintenance nao esta habilitado neste host.',",
    "          bootstrapDraft?.bootstrap?.command",
    "            ? '<strong>Bootstrap pendente:</strong> ' + escapeHtml(",
    "              bootstrapDraft.bootstrap.packageScript",
    "                ? bootstrapDraft.bootstrap.packageScript + ' Ã‚Â· ' + normalizeText(bootstrapDraft.bootstrap.workspaceHint || '')",
    "                : normalizeText(bootstrapDraft.bootstrap.command),",
    "            )",
    "            : '<strong>Bootstrap pendente:</strong> nenhum draft pendente para copiar neste host.',",
    "          ...((Array.isArray(capabilities?.capabilities) ? capabilities.capabilities : []).slice(0, 4).map((entry) =>",
    "            '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Capability')) + ':</strong> '",
    "            + escapeHtml(normalizeText(entry?.description || entry?.category || 'Sem detalhe adicional.')),",
    "          )),",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsNodesPanel, opsNodesPanelActions, opsNodesPanelDetails);",
    "  }",
    "  setOperationalActionStatus(",
    "    opsNodesStatus,",
    "    operationalMeshExpanded.nodes",
    "      ? 'Painel do Node Mesh aberto com foco, activity, capabilities e doctor do mesh atual.'",
    "      : 'Abra o painel do Node Mesh para revisar foco, allowlist e hints operacionais sem cair no legado.',",
    "  );",
    "  showOperationalAction(",
    "    opsNodesAction,",
    "    operationalMeshExpanded.nodes ? 'Voltar ao resumo' : 'Abrir painel dos nodes',",
    "    operationalMeshExpanded.nodes ? 'collapse' : 'nodes-open',",
    "    selectedId,",
    "  );",
    "}",
    "",
    "function buildChannelPromotionHint(selected, installPlan = null) {",
    "  const channelId = normalizeText(selected?.id);",
    "  const currentMode = normalizeText(installPlan?.currentMode || '');",
    "  const recommendedMode = normalizeText(installPlan?.recommendedMode || '');",
    "  if (channelId && currentMode && recommendedMode && currentMode !== recommendedMode) {",
    "    return 'Promocao oficial: este host esta em ' + currentMode + ' e o modo recomendado e ' + recommendedMode + '. Use o painel para promover sem sair do shell.';",
    "  }",
    "  if (channelId === 'slack') {",
    "    return normalizeText(selected?.transport) === 'native'",
    "      ? 'Slack ja esta em modo oficial. Use prepare/policy para revisar o rollout antes de ampliar canais ou DMs.'",
    "      : 'Promocao oficial: rode npm run setup:channels para sair do stub e ligar Slack native (socket/http) com tokens e webhook reais.';",
    "  }",
    "  if (channelId === 'whatsapp') {",
    "    return normalizeText(selected?.transport) === 'webhook'",
    "      ? 'WhatsApp ja esta em modo oficial. Revise chats permitidos e callback antes de ampliar o rollout.'",
    "      : 'Promocao oficial: rode npm run setup:channels para migrar WhatsApp para Cloud API ou fechar o bootstrap supervisionado do provider escolhido.';",
    "  }",
    "  if (channelId === 'telegram') {",
    "    return 'Telegram costuma ser o canal mais rapido para ligar. Use o wizard para alinhar token e users permitidos.';",
    "  }",
].join('\n');
