export const runtimeShellScriptPart8Seg2: string = [
    "    memoryLayeredQuery.addEventListener('keydown', (event) => {",
    "      if (event.key !== 'Enter') {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runLayeredMemorySearch();",
    "    });",
    "  }",
    "",
    "  if (learningMemoryCard instanceof HTMLElement) {",
    "    learningMemoryCard.addEventListener('click', (event) => {",
    "      if (!(event.target instanceof Element)) {",
    "        return;",
    "      }",
    "      const button = event.target.closest('[data-learning-action][data-learning-candidate]');",
    "      if (!(button instanceof HTMLButtonElement)) {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runLearningAction(",
    "        normalizeText(button.dataset.learningAction),",
    "        normalizeText(button.dataset.learningCandidate),",
    "      );",
    "    });",
    "  }",
    "}",
    "",
    "function installSystemOverlordInteractions() {",
    "  if (systemOverlordCapability instanceof HTMLSelectElement && systemOverlordCommand instanceof HTMLInputElement) {",
    "    const applyCapabilityPlaceholder = () => {",
    "      const capability = normalizeText(systemOverlordCapability.value);",
    "      const examples = {",
    "        'host.shell': 'Ex.: git status',",
    "        'host.install': '{\"command\":\"npm\",\"args\":[\"install\",\"left-pad\"]}',",
    "        'docker.exec': '{\"container\":\"web\",\"command\":\"node\",\"args\":[\"-v\"]}',",
    "        'wsl.exec': '{\"distribution\":\"Ubuntu-24.04\",\"command\":\"bash\",\"args\":[\"-lc\",\"pwd\"]}',",
    "        'network.tunnel': '{\"action\":\"inspect\"}',",
    "        'node.invoke': '{\"nodeId\":\"node-1\",\"capabilityId\":\"system.run\",\"action\":\"exec\",\"payload\":{\"command\":\"echo ok\"}}',",
    "        'secrets.read': '{\"secretName\":\"SLACK_BOT_TOKEN\"}',",
    "        'browser.control': '{\"action\":\"navigate\",\"url\":\"https://example.com\"}',",
    "        'desktop.automation': '{\"action\":\"list-elements\",\"windowTitle\":\"Notepad\"}',",
    "        'computer_use.visual_action': '{\"action\":\"run\",\"targetWindow\":\"Chrome\",\"objective\":\"abrir docs\",\"maxIterations\":3}',",
    "      };",
    "      systemOverlordCommand.placeholder = examples[capability] || 'Ex.: git status';",
    "    };",
    "    applyCapabilityPlaceholder();",
    "    systemOverlordCapability.addEventListener('change', applyCapabilityPlaceholder);",
    "  }",
    "  if (systemOverlordCard instanceof HTMLElement) {",
    "    systemOverlordCard.addEventListener('click', (event) => {",
    "      if (!(event.target instanceof Element)) {",
    "        return;",
    "      }",
    "      const approvalButton = event.target.closest('[data-overlord-approval][data-overlord-action-id]');",
    "      if (approvalButton instanceof HTMLButtonElement) {",
    "        event.preventDefault();",
    "        void runSystemOverlordApprovalDecision(",
    "          normalizeText(approvalButton.dataset.overlordActionId),",
    "          normalizeText(approvalButton.dataset.overlordApproval),",
    "        );",
    "        return;",
    "      }",
    "      const actionButton = event.target.closest('[data-overlord-action-mode][data-overlord-action-id]');",
    "      if (!(actionButton instanceof HTMLButtonElement)) {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runSystemOverlordActionMutation(",
    "        normalizeText(actionButton.dataset.overlordActionId),",
    "        normalizeText(actionButton.dataset.overlordActionMode),",
    "      );",
    "    });",
    "  }",
    "  if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "    systemOverlordRefreshAction.addEventListener('click', () => {",
    "      void refreshSystemOverlordPanel();",
    "    });",
    "  }",
    "  if (systemOverlordKillSwitchEnable instanceof HTMLButtonElement) {",
    "    systemOverlordKillSwitchEnable.addEventListener('click', () => {",
    "      void runSystemOverlordKillSwitch('activate');",
    "    });",
    "  }",
    "  if (systemOverlordKillSwitchRelease instanceof HTMLButtonElement) {",
    "    systemOverlordKillSwitchRelease.addEventListener('click', () => {",
    "      void runSystemOverlordKillSwitch('release');",
    "    });",
    "  }",
    "  if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "    systemOverlordRunAction.addEventListener('click', () => {",
    "      void runSystemOverlordSupervisedAction();",
    "    });",
    "  }",
    "  if (systemOverlordCommand instanceof HTMLInputElement) {",
    "    systemOverlordCommand.addEventListener('keydown', (event) => {",
    "      if (event.key !== 'Enter') {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runSystemOverlordSupervisedAction();",
    "    });",
    "  }",
    "}",
    "",
    "function installAutomationControlPlaneInteractions() {",
    "  if (automationControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshAutomationControlPlanePanel();",
    "    });",
    "  }",
    "  if (automationControlPlaneCreateAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneCreateAction.addEventListener('click', () => {",
    "      void runAutomationControlPlaneAction('create');",
    "    });",
    "  }",
    "  if (automationControlPlaneMaintenanceOnAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneMaintenanceOnAction.addEventListener('click', () => {",
    "      void runAutomationControlPlaneAction('maintenance-on');",
    "    });",
    "  }",
    "  if (automationControlPlaneMaintenanceOffAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneMaintenanceOffAction.addEventListener('click', () => {",
    "      void runAutomationControlPlaneAction('maintenance-off');",
    "    });",
    "  }",
    "  if (automationControlPlaneMaintenanceRunAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneMaintenanceRunAction.addEventListener('click', () => {",
    "      void runAutomationControlPlaneAction('maintenance-run');",
    "    });",
    "  }",
    "  if (automationControlPlaneIntent instanceof HTMLInputElement) {",
    "    automationControlPlaneIntent.addEventListener('keydown', (event) => {",
    "      if (event.key !== 'Enter') {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runAutomationControlPlaneAction('create');",
    "    });",
    "  }",
    "  if (automationControlPlaneCard instanceof HTMLElement) {",
    "    automationControlPlaneCard.addEventListener('click', (event) => {",
    "      if (!(event.target instanceof Element)) {",
    "        return;",
    "      }",
    "      const taskButton = event.target.closest('[data-automation-action][data-automation-task-id]');",
    "      if (!(taskButton instanceof HTMLButtonElement)) {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      if (automationControlPlaneIntent instanceof HTMLInputElement) {",
    "        automationControlPlaneIntent.value = normalizeText(taskButton.dataset.automationTaskId);",
    "      }",
    "      void runAutomationControlPlaneAction(normalizeText(taskButton.dataset.automationAction));",
    "    });",
    "  }",
    "}",
    "",
    "function installWatchModeInteractions() {",
    "  if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "    watchModeRefreshAction.addEventListener('click', () => {",
    "      void refreshWatchModePanel();",
    "    });",
    "  }",
    "  if (watchModeAllowAppAction instanceof HTMLButtonElement) {",
    "    watchModeAllowAppAction.addEventListener('click', () => {",
    "      void runWatchModePolicyAction('allow-app');",
    "    });",
    "  }",
    "  if (watchModeAllowSiteAction instanceof HTMLButtonElement) {",
    "    watchModeAllowSiteAction.addEventListener('click', () => {",
    "      void runWatchModePolicyAction('allow-site');",
    "    });",
    "  }",
    "  if (watchModeStrictOnAction instanceof HTMLButtonElement) {",
    "    watchModeStrictOnAction.addEventListener('click', () => {",
    "      void runWatchModePolicyAction('strict-on');",
    "    });",
    "  }",
    "  if (watchModeStrictOffAction instanceof HTMLButtonElement) {",
    "    watchModeStrictOffAction.addEventListener('click', () => {",
    "      void runWatchModePolicyAction('strict-off');",
    "    });",
    "  }",
    "  if (watchModeStartAction instanceof HTMLButtonElement) {",
    "    watchModeStartAction.addEventListener('click', () => {",
    "      void runWatchModeStart();",
    "    });",
    "  }",
    "  if (watchModePauseAction instanceof HTMLButtonElement) {",
    "    watchModePauseAction.addEventListener('click', () => {",
    "      void runWatchModeMutation('pause');",
    "    });",
    "  }",
    "  if (watchModeResumeAction instanceof HTMLButtonElement) {",
    "    watchModeResumeAction.addEventListener('click', () => {",
    "      void runWatchModeMutation('resume');",
    "    });",
    "  }",
    "  if (watchModeStopAction instanceof HTMLButtonElement) {",
    "    watchModeStopAction.addEventListener('click', () => {",
    "      void runWatchModeMutation('stop');",
    "    });",
    "  }",
    "  if (watchModeObjective instanceof HTMLInputElement) {",
    "    watchModeObjective.addEventListener('keydown', (event) => {",
    "      if (event.key !== 'Enter') {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runWatchModeStart();",
    "    });",
    "  }",
    "  if (watchModeCard instanceof HTMLElement) {",
    "    watchModeCard.addEventListener('click', (event) => {",
    "      if (!(event.target instanceof Element)) {",
    "        return;",
    "      }",
    "      const button = event.target.closest('[data-watch-mode-approval][data-watch-mode-approval-id]');",
    "      if (!(button instanceof HTMLButtonElement)) {",
    "        return;",
    "      }",
    "      event.preventDefault();",
    "      void runWatchModeApprovalDecision(",
    "        normalizeText(button.dataset.watchModeApprovalId),",
    "        normalizeText(button.dataset.watchModeApproval),",
    "      );",
    "    });",
    "  }",
    "}",
    "",
    "function installEvalControlPlaneInteractions() {",
    "  if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    evalControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshEvalControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installQaControlPlaneInteractions() {",
    "  if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    qaControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshQaControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installGovernanceControlPlaneInteractions() {",
    "  if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    governanceControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshGovernanceControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installReplayLearningControlPlaneInteractions() {",
    "  if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    replayLearningControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshReplayLearningControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installEcosystemControlPlaneInteractions() {",
    "  if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    ecosystemControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshEcosystemControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installDistributedRuntimeControlPlaneInteractions() {",
    "  if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    distributedRuntimeControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshDistributedRuntimeControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installRuntimeStabilityControlPlaneInteractions() {",
    "  if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    runtimeStabilityControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshRuntimeStabilityControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installRolloutReadinessControlPlaneInteractions() {",
    "  if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    rolloutReadinessControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshRolloutReadinessControlPlanePanel();",
    "    });",
    "  }",
    "}",
    "",
    "function installHubControlPlaneInteractions() {",
    "  if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshHubControlPlanePanel();",
    "    });",
    "  }",
    "  if (hubControlPlaneSyncAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneSyncAction.addEventListener('click', () => {",
    "      void runHubControlPlaneAction('platform-sync');",
    "    });",
    "  }",
    "  if (hubControlPlaneMcpDoctorAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneMcpDoctorAction.addEventListener('click', () => {",
    "      void runHubControlPlaneAction('mcp-doctor');",
    "    });",
    "  }",
    "}",
    "",
    "function installTrustPlaneInteractions() {",
    "  if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    trustPlaneRefreshAction.addEventListener('click', () => {",
    "      void refreshTrustPlanePanel();",
    "    });",
    "  }",
    "  if (trustPlanePromoteTrustedAction instanceof HTMLButtonElement) {",
    "    trustPlanePromoteTrustedAction.addEventListener('click', () => {",
    "      void runTrustPlaneAction('set-mcp-profile', { profile: 'trusted' });",
    "    });",
    "  }",
    "  if (trustPlaneHardenSafeAction instanceof HTMLButtonElement) {",
    "    trustPlaneHardenSafeAction.addEventListener('click', () => {",
    "      void runTrustPlaneAction('set-mcp-profile', { profile: 'safe' });",
    "    });",
    "  }",
    "  if (trustPlaneSkillsDenyAction instanceof HTMLButtonElement) {",
    "    trustPlaneSkillsDenyAction.addEventListener('click', () => {",
    "      void runTrustPlaneAction('set-skill-default', { defaultPolicy: 'deny' });",
    "    });",
    "  }",
    "}",
    "",
    "if (priorityPrimaryAction instanceof HTMLButtonElement) {",
    "  priorityPrimaryAction.addEventListener('click', () => {",
    "    void runPriorityPrimaryAction();",
    "  });",
    "}",
    "",
    "async function fetchPublicSnapshot() {",
    "  try {",
    "    const [gatewayResponse, domainsResponse, nodesResponse, transportsResponse] = await Promise.all([",
    "      fetch('/api/v1/gateway/status', { headers: { Accept: 'application/json' } }),",
    "      fetch('/api/v1/gateway/domains', { headers: { Accept: 'application/json' } }),",
    "      fetch('/api/v1/nodes', { headers: { Accept: 'application/json' } }),",
    "      fetch('/api/v1/transports', { headers: { Accept: 'application/json' } }),",
    "    ]);",
    "",
    "    const gatewayPayload = gatewayResponse.ok ? await gatewayResponse.json() : null;",
    "    const domainsPayload = domainsResponse.ok ? await domainsResponse.json() : null;",
    "    const nodesPayload = nodesResponse.ok ? await nodesResponse.json() : null;",
    "    const transportsPayload = transportsResponse.ok ? await transportsResponse.json() : null;",
    "",
    "    const gatewayLabel = gatewayPayload?.status ? String(gatewayPayload.status) : 'Indisponivel';",
    "    const initializedDomains = domainsPayload?.summary",
    "      ? String(domainsPayload.summary.initialized) + '/' + String(domainsPayload.summary.total)",
    "      : 'Indisponivel';",
    "    const nodeCount = typeof nodesPayload?.total === 'number' ? String(nodesPayload.total) : 'Indisponivel';",
    "    const transportCount = typeof transportsPayload?.total === 'number'",
    "      ? String(transportsPayload.total)",
    "      : Array.isArray(transportsPayload?.data)",
    "        ? String(transportsPayload.data.length)",
    "        : 'Indisponivel';",
    "    publicShellSnapshot = {",
    "      gatewayLabel,",
    "      initializedDomains,",
    "      nodeCount,",
    "      transportCount,",
    "    };",
    "",
    "    setText(gatewayStatus, gatewayLabel);",
    "    setText(meshStatus, 'dominios ' + initializedDomains + ' | nodes ' + nodeCount + ' | transports ' + transportCount);",
    "    setText(gatewayStatusDetail, gatewayLabel);",
    "    setText(gatewayDomainDetail, initializedDomains);",
    "    setText(nodeCountDetail, nodeCount);",
    "    setText(transportCountDetail, transportCount);",
    "    renderOperatorCockpit();",
    "  } catch (error: unknown) {",
    "    publicShellSnapshot = {",
    "      gatewayLabel: 'Indisponivel',",
    "      initializedDomains: 'Indisponivel',",
    "      nodeCount: 'Indisponivel',",
    "      transportCount: 'Indisponivel',",
    "    };",
    "    setText(gatewayStatus, 'Indisponivel');",
    "    setText(meshStatus, 'snapshot publico indisponivel');",
    "    setText(gatewayStatusDetail, 'Indisponivel');",
    "    setText(gatewayDomainDetail, 'Indisponivel');",
    "    setText(nodeCountDetail, 'Indisponivel');",
    "    setText(transportCountDetail, 'Indisponivel');",
    "    renderOperatorCockpit();",
    "  }",
    "}",
    "",
    "function formatClock(value) {",
    "  if (!value) {",
    "    return 'indisponivel';",
    "  }",
    "  const date = new Date(value);",
    "  if (Number.isNaN(date.getTime())) {",
    "    return 'indisponivel';",
    "  }",
    "  return date.toLocaleTimeString('en-US');",
    "}",
    "",
    "function summarizeProcess(process) {",
    "  if (!process) {",
    "    return 'indisponivel';",
    "  }",
    "  return process.ready ? 'ok' : 'offline';",
    "}",
    "",
    "async function fetchKeepaliveSnapshot() {",
    "  if (!opsKeepaliveState) {",
    "    return;",
    "  }",
    "  try {",
    "    const response = await fetch('/api/web/ops/keepalive', { headers: { Accept: 'application/json' } });",
    "    if (!response.ok) {",
    "      throw new Error('snapshot indisponivel');",
    "    }",
    "    const payload = await response.json();",
    "    const snapshot = payload?.snapshot || null;",
    "    const processes = snapshot?.processes || {};",
    "    const upstream = processes['AIGateway-upstream'];",
    "    const gateway = processes['ai-gateway'];",
    "    const nodeHost = processes['node-host'];",
    "    const stale = Boolean(payload?.stale);",
    "    const allReady = Boolean(upstream?.ready && gateway?.ready && nodeHost?.ready);",
    "    const stateLabel = stale",
    "      ? 'Stale'",
    "      : allReady",
    "        ? 'OK'",
    "        : 'Atencao';",
    "",
    "    setText(opsKeepaliveState, stateLabel);",
    "    setText(",
    "      opsKeepaliveSummary,",
    "      'Upstream ' + summarizeProcess(upstream)",
    "      + ' | Gateway ' + summarizeProcess(gateway)",
    "      + ' | Node-host ' + summarizeProcess(nodeHost),",
    "    );",
    "    setText(",
    "      opsKeepaliveStatus,",
    "      'Ultimo sinal ' + formatClock(snapshot?.updatedAt)",
    "      + ' | intervalo ' + (snapshot?.intervalMs ? (snapshot.intervalMs / 1000) + 's' : 'indisponivel')",
    "      + (stale ? ' | snapshot desatualizado' : ''),",
    "    );",
    "",
    "    renderList(opsKeepaliveDetails, [",
    "      'Upstream: ' + summarizeProcess(upstream) + ' (ultimo ready ' + formatClock(upstream?.lastReadyAt) + ')',",
    "      'Gateway: ' + summarizeProcess(gateway) + ' (ultimo ready ' + formatClock(gateway?.lastReadyAt) + ')',",
    "      'Node-host: ' + summarizeProcess(nodeHost) + ' (ultimo ready ' + formatClock(nodeHost?.lastReadyAt) + ')',",
    "    ]);",
    "    renderOperatorCockpit();",
    "  } catch (error: unknown) {",
    "    setText(opsKeepaliveState, 'Indisponivel');",
    "    setText(opsKeepaliveSummary, 'Snapshot local nao encontrado.');",
    "    setText(opsKeepaliveStatus, 'Rode o keepalive para habilitar este painel.');",
    "    renderList(opsKeepaliveDetails, [",
    "      'Execute npm run ops:remote:keepalive para gerar o snapshot supervisionado.',",
    "      'Cheque o log em data/runtime/ops-remote-keepalive.out.log se continuar falhando.',",
    "    ]);",
    "    renderOperatorCockpit();",
    "  }",
    "}",
    "",
    "applyExternalLinks();",
    "installCopyButtons();",
    "installProtectedAccessForm();",
    "installJourneyActionControls();",
    "installRemoteActionControls();",
    "installOperatorCockpitActions();",
    "installOperationalMeshActions();",
    "installSessionWorkspaceInteractions();",
    "installLearningMemoryInteractions();",
    "installEvalControlPlaneInteractions();",
    "installQaControlPlaneInteractions();",
    "installGovernanceControlPlaneInteractions();",
    "    installReplayLearningControlPlaneInteractions();",
    "    installEcosystemControlPlaneInteractions();",
    "    installDistributedRuntimeControlPlaneInteractions();",
    "    installRuntimeStabilityControlPlaneInteractions();",
    "    installRolloutReadinessControlPlaneInteractions();",
    "    installAutomationControlPlaneInteractions();",
    "    installHubControlPlaneInteractions();",
    "installTrustPlaneInteractions();",
    "installWatchModeInteractions();",
    "installSystemOverlordInteractions();",
    "renderOperatorCockpit();",
    "renderEvalControlPlanePanel();",
    "renderQaControlPlanePanel();",
    "renderGovernanceControlPlanePanel();",
    "renderReplayLearningControlPlanePanel();",
    "renderEcosystemControlPlanePanel();",
    "renderDistributedRuntimeControlPlanePanel();",
    "renderRuntimeStabilityControlPlanePanel();",
    "renderRolloutReadinessControlPlanePanel();",
    "renderAutomationControlPlanePanel();",
    "renderHubControlPlanePanel();",
    "renderTrustPlanePanel();",
    "renderWatchModePanel();",
    "renderSystemOverlordPanel();",
    "void fetchRuntimeStatus();",
    "void fetchPublicSnapshot();",
    "void fetchKeepaliveSnapshot();",
].join('\n');
