import { asErrorLike } from '../../utils/errorLike';
export const runtimeShellScriptPart1Seg2: string = [
    "  hideOpenAction(prioritySecondaryOpen);",
    "}",
    "",
    "function setCardEmphasis(target, mode) {",
    "  if (!(target instanceof HTMLElement)) {",
    "    return;",
    "  }",
    "  target.classList.remove('card-focus', 'card-subtle');",
    "  if (mode === 'focus') {",
    "    target.classList.add('card-focus');",
    "    return;",
    "  }",
    "  if (mode === 'subtle') {",
    "    target.classList.add('card-subtle');",
    "  }",
    "}",
    "",
    "function setRemoteActionStatus(value) {",
    "  setText(remoteActionStatus, value);",
    "}",
    "",
    "function setJourneyActionStatus(value) {",
    "  setText(journeyActionStatus, value);",
    "}",
    "",
    "function readStoredToken() {",
    "  try {",
    "    const sessionToken = window.sessionStorage.getItem(AUTH_STORAGE_KEY) || '';",
    "    if (sessionToken) {",
    "      return sessionToken;",
    "    }",
    "    const legacyToken = window.localStorage.getItem(AUTH_STORAGE_KEY) || '';",
    "    if (legacyToken) {",
    "      window.sessionStorage.setItem(AUTH_STORAGE_KEY, legacyToken);",
    "      window.localStorage.removeItem(AUTH_STORAGE_KEY);",
    "    }",
    "    return legacyToken;",
    "  } catch (error: unknown) {",
    "    return '';",
    "  }",
    "}",
    "",
    "function writeStoredToken(value) {",
    "  try {",
    "    if (!value) {",
    "      window.sessionStorage.removeItem(AUTH_STORAGE_KEY);",
    "      window.localStorage.removeItem(AUTH_STORAGE_KEY);",
    "      return;",
    "    }",
    "    window.sessionStorage.setItem(AUTH_STORAGE_KEY, value);",
    "    window.localStorage.removeItem(AUTH_STORAGE_KEY);",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err; console.warn('[auto-fix] Empty catch block', err); }",
    "}",
    "",
    "function applyExternalLinks() {",
    "  const externalWebUrl = root?.dataset.externalWebClientUrl || '';",
    "  const externalDocsUrl = root?.dataset.externalDocsUrl || '';",
    "",
    "  setText(originLabel, window.location.origin);",
    "",
    "  if (externalWebUrl && externalWebLink instanceof HTMLAnchorElement) {",
    "    externalWebLink.href = externalWebUrl;",
    "    externalWebLink.hidden = false;",
    "    externalWebLink.target = '_blank';",
    "    externalWebLink.rel = 'noreferrer';",
    "    if (externalWebCopy) {",
    "      externalWebCopy.textContent = 'Cliente web externo detectado e pronto para ser aberto fora do repo oficial.';",
    "    }",
    "  }",
    "",
    "  if (externalDocsUrl && externalDocsLink instanceof HTMLAnchorElement) {",
    "    externalDocsLink.href = externalDocsUrl;",
    "    externalDocsLink.hidden = false;",
    "    externalDocsLink.target = '_blank';",
    "    externalDocsLink.rel = 'noreferrer';",
    "  }",
    "}",
    "",
    "async function fetchRuntimeStatus() {",
    "  try {",
    "    const response = await fetch('/api/auth/status', { headers: { Accept: 'application/json' } });",
    "    const payload = await response.json();",
    "    if (!response.ok || !payload?.ok) {",
    "      throw new Error(payload?.error || 'Falha ao consultar status do runtime.');",
    "    }",
    "",
    "    setText(runtimeStatus, payload.webReady ? 'Pronto' : 'Sem runtime anexado');",
    "    setText(authStatus, payload.authRequired ? 'Token exigido' : 'Livre');",
    "    if (authInput instanceof HTMLInputElement && !authInput.value) {",
    "      authInput.value = readStoredToken();",
    "    }",
    "    renderOperatorCockpit();",
    "  } catch (error: unknown) {",
    "    setText(runtimeStatus, 'Indisponivel');",
    "    setText(authStatus, 'Falha na checagem');",
    "",
    "    if (externalWebCopy) {",
    "      externalWebCopy.textContent = error instanceof Error ? error.message : String(error);",
    "    }",
    "    renderOperatorCockpit();",
    "  }",
    "}",
    "",
    "async function fetchProtectedJson(pathname, token, init = null) {",
    "  const requestInit = init && typeof init === 'object' ? init : {};",
    "  const timeoutMs = Number(requestInit.timeoutMs || 15000) || 15000;",
    "  const controller = new AbortController();",
    "  const timeoutId = window.setTimeout(() => controller.abort(), timeoutMs);",
    "  const extraHeaders = requestInit.headers && typeof requestInit.headers === 'object'",
    "    ? requestInit.headers",
    "    : {};",
    "  const { timeoutMs: _timeoutMs, ...safeRequestInit } = requestInit;",
    "  try {",
    "    const response = await fetch(pathname, {",
    "      ...safeRequestInit,",
    "      signal: controller.signal,",
    "      headers: {",
    "        Accept: 'application/json',",
    "        'X-Zavorth-Token': token,",
    "        ...extraHeaders,",
    "      },",
    "    });",
    "    const payload = await response.json().catch(() => null);",
    "    if (!response.ok || !payload?.ok) {",
    "      throw new Error(payload?.error || 'Falha ao consultar ' + pathname + '.');",
    "    }",
    "    return payload;",
    "  } catch (error: unknown) {",
    "    if (error && error.name === 'AbortError') {",
    "      throw new Error('Timeout consultando ' + pathname + '.');",
    "    }",
    "    throw error;",
    "  } finally {",
    "    window.clearTimeout(timeoutId);",
    "  }",
    "}",
    "",
    "async function fetchProtectedJsonOptional(pathname, token, init = null) {",
    "  try {",
    "    const requestInit = init && typeof init === 'object' ? init : {};",
    "    return await fetchProtectedJson(pathname, token, { timeoutMs: 4500, ...requestInit });",
    "  } catch (error: unknown) {",
    "    return {",
    "      ok: false,",
    "      error: error instanceof Error ? error.message : String(error),",
    "    };",
    "  }",
    "}",
    "",
    "function clearGatewayControlSocketReconnectTimer() {",
    "  if (gatewayControlSocketReconnectTimer) {",
    "    window.clearTimeout(gatewayControlSocketReconnectTimer);",
    "    gatewayControlSocketReconnectTimer = null;",
    "  }",
    "}",
    "",
    "function clearGatewayControlSocketRefreshTimer() {",
    "  if (gatewayControlSocketRefreshTimer) {",
    "    window.clearTimeout(gatewayControlSocketRefreshTimer);",
    "    gatewayControlSocketRefreshTimer = null;",
    "  }",
    "}",
    "",
    "function buildGatewayControlSocketUrl(token, sessionId = '') {",
    "  const origin = new URL(window.location.origin);",
    "  origin.protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';",
    "  origin.pathname = '/api/web/gateway/ws';",
    "  origin.searchParams.set('token', token);",
    "  if (sessionId) {",
    "    origin.searchParams.set('sessionId', sessionId);",
    "  }",
    "  origin.searchParams.set('replay', 'state');",
    "  return origin.toString();",
    "}",
    "",
    "function buildSessionWorkspacePayloadFromGateway(statePayload, historyPayload = null) {",
    "  const sessionId = pickFirstText([",
    "    statePayload?.session?.sessionId,",
    "    historyPayload?.session?.sessionId,",
    "  ]);",
    "  const chatId = pickFirstText([",
    "    statePayload?.session?.chatId,",
    "    historyPayload?.session?.chatId,",
    "  ]);",
    "  return {",
    "    session: sessionId || chatId",
    "      ? {",
    "          ok: true,",
    "          sessionId: sessionId || null,",
    "          chatId: chatId || null,",
    "          continuity: statePayload?.session?.continuity || historyPayload?.session?.continuity || null,",
    "        }",
    "      : null,",
    "    state: statePayload || null,",
    "    history: historyPayload || statePayload || null,",
    "    toolRuns: statePayload?.artifactPlane || null,",
    "  };",
    "}",
    "",
    "function settleGatewayControlSocketRequest(id, payload) {",
    "  const entry = gatewayControlSocketPendingRequests.get(id);",
    "  if (!entry) {",
    "    return;",
    "  }",
    "  gatewayControlSocketPendingRequests.delete(id);",
    "  window.clearTimeout(entry.timeoutId);",
    "  if (payload?.ok === false) {",
    "    entry.reject(new Error(payload?.error?.message || 'Falha ao processar request do Gateway.'));",
    "    return;",
    "  }",
    "  entry.resolve(payload?.result);",
    "}",
    "",
    "function requestGatewayControlSocket(method, params = null, options = {}) {",
    "  const socket = gatewayControlSocket;",
    "  if (!(socket instanceof WebSocket) || socket.readyState !== WebSocket.OPEN) {",
    "    return Promise.reject(new Error('Gateway WS indisponivel; usando fallback HTTP.'));",
    "  }",
    "",
    "  gatewayControlSocketRequestSequence += 1;",
    "  const id = 'gw-' + String(Date.now()) + '-' + String(gatewayControlSocketRequestSequence);",
    "  const timeoutMs = Number(options.timeoutMs || 8000) || 8000;",
    "",
    "  return new Promise((resolve, reject) => {",
    "    const timeoutId = window.setTimeout(() => {",
    "      gatewayControlSocketPendingRequests.delete(id);",
    "      reject(new Error('Timeout aguardando resposta do Gateway WS.'));",
    "    }, timeoutMs);",
    "    gatewayControlSocketPendingRequests.set(id, {",
    "      resolve,",
    "      reject,",
    "      timeoutId,",
    "    });",
    "    socket.send(JSON.stringify({",
    "      id,",
    "      method,",
    "      params: params && typeof params === 'object' ? params : {},",
    "    }));",
    "  });",
    "}",
    "",
    "async function refreshSessionWorkspaceViaGateway(token, sessionId = '', options = {}) {",
    "  const normalizedSessionId = normalizeText(sessionId || readSessionWorkspaceSessionId());",
    "  const allowHttpFallback = options.allowHttpFallback !== false;",
    "  if (gatewayControlSocket instanceof WebSocket && gatewayControlSocket.readyState === WebSocket.OPEN) {",
    "    const statePayload = await requestGatewayControlSocket('session.state', {",
    "      sessionId: normalizedSessionId || undefined,",
    "      activate: options.activate === true,",
    "      replayMode: options.replayMode || 'full',",
    "    });",
    "    return buildSessionWorkspacePayloadFromGateway(statePayload, statePayload);",
    "  }",
    "  if (!allowHttpFallback) {",
    "    throw new Error('Gateway WS indisponivel para atualizar a sessao.');",
    "  }",
    "  return fetchSessionWorkspacePayload(token, normalizedSessionId);",
    "}",
    "",
    "function closeGatewayControlSocket(statusMessage = '') {",
    "  gatewayControlSocketExpectedClose = true;",
    "  clearGatewayControlSocketReconnectTimer();",
    "  clearGatewayControlSocketRefreshTimer();",
    "  gatewayControlSocketPendingRequests.forEach((entry, id) => {",
    "    window.clearTimeout(entry.timeoutId);",
    "    entry.reject(new Error('Gateway WS encerrado antes da resposta.'));",
    "    gatewayControlSocketPendingRequests.delete(id);",
    "  });",
    "  if (gatewayControlSocket) {",
    "    try {",
    "      gatewayControlSocket.close();",
    "    } catch (error: unknown) {",
    "      // Ignore close failures while the shell falls back to HTTP.",
    "    }",
    "  }",
    "  gatewayControlSocket = null;",
    "  if (statusMessage) {",
    "    setText(gatewayStatus, statusMessage);",
    "  }",
    "}",
    "",
    "function scheduleGatewayControlSocketRefresh(token, sessionId = '') {",
    "  clearGatewayControlSocketRefreshTimer();",
    "  gatewayControlSocketRefreshTimer = window.setTimeout(async () => {",
    "    if (!protectedShellUnlocked) {",
    "      return;",
    "    }",
    "    try {",
    "      const payload = await refreshSessionWorkspaceViaGateway(token, sessionId, {",
    "        replayMode: 'full',",
    "      });",
    "      renderSessionWorkspace(payload);",
    "      const refreshedSessionId = pickFirstText([",
    "        payload?.session?.sessionId,",
    "        payload?.state?.session?.sessionId,",
    "        payload?.history?.session?.sessionId,",
    "        sessionId,",
    "      ]);",
    "      if (refreshedSessionId && refreshedSessionId !== gatewayControlSocketSessionId) {",
    "        ensureGatewayControlSocket(token, refreshedSessionId);",
    "      }",
    "    } catch (error: unknown) {",
    "      setText(",
    "        sessionWorkspaceStatus,",
    "        error instanceof Error ? error.message : String(error),",
    "      );",
    "    }",
    "  }, 150);",
    "}",
    "",
    "function ensureGatewayControlSocket(token, sessionId = '') {",
    "  const normalizedToken = normalizeText(token);",
    "  const normalizedSessionId = normalizeText(sessionId);",
    "  if (!normalizedToken || !protectedShellUnlocked) {",
    "    closeGatewayControlSocket('Gateway protegido.');",
    "    return;",
    "  }",
    "",
    "  const existing = gatewayControlSocket;",
    "  const sameSession = !normalizedSessionId || gatewayControlSocketSessionId === normalizedSessionId;",
    "  const liveReadyState = existing ? existing.readyState : WebSocket.CLOSED;",
    "  const isLive = liveReadyState === WebSocket.OPEN || liveReadyState === WebSocket.CONNECTING;",
    "  if (existing && isLive && sameSession) {",
    "    return;",
    "  }",
    "",
    "  closeGatewayControlSocket('');",
    "  gatewayControlSocketExpectedClose = false;",
    "  gatewayControlSocketSessionId = normalizedSessionId || gatewayControlSocketSessionId;",
    "  const socket = new WebSocket(buildGatewayControlSocketUrl(normalizedToken, gatewayControlSocketSessionId));",
    "  gatewayControlSocket = socket;",
    "  setText(gatewayStatus, 'Conectando WS');",
    "",
    "  socket.addEventListener('open', () => {",
    "    setText(gatewayStatus, 'Gateway WS online');",
    "  });",
    "",
    "  socket.addEventListener('message', (rawEvent) => {",
    "    let payload = null;",
    "    try {",
    "      payload = JSON.parse(String(rawEvent.data || 'null'));",
    "    } catch (error: unknown) {",
    "      return;",
    "    }",
    "",
    "    if (payload?.type === 'response') {",
    "      settleGatewayControlSocketRequest(normalizeText(payload?.id), payload);",
    "      return;",
    "    }",
    "",
    "    if (payload?.type === 'ready') {",
    "      gatewayControlSocketSessionId = normalizeText(payload.sessionId) || gatewayControlSocketSessionId;",
    "      setText(gatewayStatus, 'Gateway WS online');",
    "      void requestGatewayControlSocket('subscribe', {",
    "        sessionId: gatewayControlSocketSessionId || undefined,",
    "        replayMode: 'full',",
    "      }).catch(() => undefined);",
    "      return;",
    "    }",
    "",
    "    if (payload?.type === 'runtime') {",
    "      const preferred = normalizeText(payload?.payload?.controlPlane?.preferredTransport || 'ws').toUpperCase();",
    "      setText(gatewayStatus, 'Gateway ' + preferred + ' online');",
    "      return;",
    "    }",
    "",
    "    if (payload?.type === 'hydrate') {",
    "      gatewayControlSocketSessionId = normalizeText(payload.sessionId) || gatewayControlSocketSessionId;",
    "      renderSessionWorkspace(buildSessionWorkspacePayloadFromGateway(payload?.state, payload?.history));",
    "      return;",
    "    }",
    "",
    "    if (payload?.type === 'event' && payload?.channel === 'realtime') {",
    "      const eventType = normalizeText(payload?.event?.type);",
    "      const eventKind = normalizeText(payload?.event?.kind);",
    "      if (eventType === 'snapshot' || eventType === 'message' || eventType === 'task' || eventType === 'permission' || eventType === 'workflow' || eventType === 'tool') {",
    "        scheduleGatewayControlSocketRefresh(normalizedToken, gatewayControlSocketSessionId);",
    "      } else if (eventKind === 'session' || eventKind === 'chat' || eventKind === 'agent' || eventKind === 'approval' || eventKind === 'tool') {",
    "        scheduleGatewayControlSocketRefresh(normalizedToken, gatewayControlSocketSessionId);",
    "      }",
    "      return;",
    "    }",
    "",
    "    if (payload?.type === 'warning') {",
    "      setText(",
    "        sessionWorkspaceStatus,",
    "        normalizeText(payload?.message) || 'O gateway WebSocket enviou um aviso.',",
    "      );",
    "    }",
    "  });",
    "",
    "  socket.addEventListener('error', () => {",
    "    setText(gatewayStatus, 'WS indisponivel, fallback HTTP');",
    "  });",
    "",
    "  socket.addEventListener('close', () => {",
    "    gatewayControlSocket = null;",
    "    const shouldReconnect = !gatewayControlSocketExpectedClose && protectedShellUnlocked;",
    "    gatewayControlSocketExpectedClose = false;",
    "    if (!shouldReconnect) {",
    "      return;",
    "    }",
    "    setText(gatewayStatus, 'WS offline, fallback HTTP');",
    "    clearGatewayControlSocketReconnectTimer();",
    "    gatewayControlSocketReconnectTimer = window.setTimeout(() => {",
    "      const latestToken = normalizeText(readStoredToken() || authInput?.value);",
    "      if (latestToken) {",
    "        ensureGatewayControlSocket(latestToken, gatewayControlSocketSessionId);",
    "      }",
    "    }, 1500);",
    "  });",
    "}",
    "",
    "async function postProtectedJson(pathname, token, body) {",
    "  const response = await fetch(pathname, {",
    "    method: 'POST',",
    "    headers: {",
    "      Accept: 'application/json',",
    "      'Content-Type': 'application/json',",
    "      'X-Zavorth-Token': token,",
    "    },",
    "    body: body ? JSON.stringify(body) : undefined,",
    "  });",
    "  const payload = await response.json().catch(() => null);",
    "  if (!payload) {",
    "    throw new Error('Falha ao consultar ' + pathname + '.');",
    "  }",
    "  if (!response.ok && !payload?.report) {",
    "    throw new Error(payload?.error || 'Falha ao consultar ' + pathname + '.');",
    "  }",
    "  return payload;",
    "}",
    "",
    "function renderManifest(payload) {",
    "  const manifest = payload?.manifest;",
    "  if (!manifest) {",
    "    renderList(manifestLaunchers, ['Manifesto indisponivel.']);",
    "    return;",
    "  }",
    "",
    "  const items = [];",
    "  if (Array.isArray(manifest.surfaces) && manifest.surfaces.length > 0) {",
    "    for (const surface of manifest.surfaces.slice(0, 4)) {",
    "      const label = String(surface?.label || surface?.id || 'Superficie');",
    "      const ready = surface?.ready ? 'pronta' : 'pendente';",
    "      const entry = normalizeText(surface?.remoteEntry || surface?.entry);",
    "      const description = normalizeText(surface?.description);",
    "      items.push('<strong>' + label + ' [' + ready + ']:</strong> ' + (entry || description || 'Sem entrada.'));",
    "    }",
    "  } else if (Array.isArray(manifest.launchers)) {",
    "    for (const entry of manifest.launchers.filter((item) => item?.id !== 'best').slice(0, 4)) {",
    "      const label = String(entry?.label || 'Launcher');",
    "      const ready = entry?.ready ? 'pronto' : 'pendente';",
    "      const value = String(entry?.value || '').trim();",
    "      const description = String(entry?.description || '').trim();",
    "      items.push('<strong>' + label + ' [' + ready + ']:</strong> ' + (value || description || 'Sem valor.'));",
    "    }",
    "  }",
    "  if (items.length === 0 && Array.isArray(manifest.guides?.local)) {",
    "    for (const entry of manifest.guides.local.slice(0, 3)) {",
    "      items.push(String(entry));",
    "    }",
    "  }",
    "  renderList(manifestLaunchers, items);",
    "}",
    "",
    "function renderJourney(payload) {",
    "  const report = payload?.report;",
    "  if (!report) {",
    "    renderList(installJourney, ['Journey indisponivel.']);",
    "    return;",
    "  }",
    "  const items = [];",
    "  if (Array.isArray(report.phases)) {",
    "    const actionablePhases = report.phases.filter((phase) => String(phase?.status || '') !== 'ready');",
    "    const phases = actionablePhases.length > 0 ? actionablePhases : report.phases.slice(0, 3);",
    "    for (const phase of phases.slice(0, 4)) {",
    "      const title = String(phase?.title || phase?.id || 'etapa');",
    "      const status = String(phase?.status || 'unknown');",
    "      const command = String(phase?.command || '').trim();",
    "      const summary = String(phase?.summary || '').trim();",
    "      items.push('<strong>' + title + ' [' + status + ']:</strong> ' + (command || summary || 'Sem resumo.'));",
    "    }",
    "  }",
    "  if (items.length === 0 && report.summary) {",
    "    items.push('<strong>Estado:</strong> ' + String(report.summary));",
    "  }",
    "  renderList(installJourney, items);",
    "}",
    "",
    "function renderRemoteAccess(payload) {",
    "  const report = payload?.report;",
    "  if (!report) {",
    "    setRemoteActionStatus('Acesso remoto oficial indisponivel.');",
    "    renderList(remoteAccessSummary, ['Acesso remoto oficial indisponivel.']);",
    "    return;",
    "  }",
    "  const items = [];",
    "  const remoteReady = report?.remote?.ready === true;",
    "  items.push('<strong>Estado:</strong> ' + (remoteReady ? 'pronto' : 'pendente'));",
    "  if (normalizeText(report?.remote?.appUrl || report?.remote?.baseUrl)) {",
    "    items.push('<strong>Entrada:</strong> ' + normalizeText(report.remote.appUrl || report.remote.baseUrl));",
    "  }",
    "  const preferredCommand = normalizeText(",
    "    report?.actions?.go?.command",
    "      || report?.actions?.apply?.command",
    "      || report?.actions?.verify?.command,",
    "  );",
    "  if (preferredCommand) {",
    "    items.push('<strong>Comando:</strong> ' + preferredCommand);",
    "  }",
    "  if (Array.isArray(report.nextSteps)) {",
    "    for (const step of report.nextSteps.slice(0, 2)) {",
    "      items.push(String(step));",
    "    }",
    "  }",
    "  if (items.length === 0 && report.summary) {",
    "    items.push('<strong>Estado:</strong> ' + String(report.summary));",
    "  }",
    "  renderList(remoteAccessSummary, items);",
    "  setRemoteActionStatus(normalizeText(report?.summary) || 'Acesso remoto oficial carregado.');",
    "}",
    "",
    "function buildLearningActionButton(action, candidateId, label) {",
    "  const safeAction = escapeHtml(action);",
    "  const safeCandidateId = escapeHtml(candidateId);",
    "  const safeLabel = escapeHtml(label);",
    "  return '<button type=\"button\" class=\"action-button secondary compact-action\"'",
    "    + ' data-learning-action=\"' + safeAction + '\"'",
    "    + ' data-learning-candidate=\"' + safeCandidateId + '\">'",
    "    + safeLabel",
    "    + '</button>';",
    "}",
    "",
    "function renderLearningMemory(statePayload, learningPayload, memoryProceduresPayload) {",
    "  const layeredMemory = statePayload?.layeredMemory || null;",
    "  const layeredMemoryMetrics = statePayload?.layeredMemoryMetrics || null;",
    "  const learningSnapshot = learningPayload?.snapshot || statePayload?.learningPlane || null;",
    "  const learningMetrics = learningPayload?.metrics || statePayload?.learningMetrics || null;",
    "  const procedures = memoryProceduresPayload?.procedures || null;",
    "  const opsQuality = statePayload?.opsQuality || null;",
    "  learningMemoryData = {",
    "    learning: learningSnapshot,",
    "    procedures,",
    "    search: learningMemoryData.search || null,",
    "    lastQuery: learningMemoryData.lastQuery || '',",
    "  };",
    "",
    "  if (learningRefreshAction instanceof HTMLButtonElement) {",
    "    learningRefreshAction.hidden = false;",
    "  }",
    "  if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {",
    "    memoryLayeredRefreshAction.hidden = false;",
    "  }",
    "  if (memoryLayeredSearchAction instanceof HTMLButtonElement) {",
    "    memoryLayeredSearchAction.hidden = false;",
    "  }",
    "  if (learningMemoryCard instanceof HTMLElement) {",
    "    learningMemoryCard.hidden = false;",
    "  }",
    "",
    "  if (!learningSnapshot) {",
    "    setText(learningState, 'Indisponivel');",
    "    setText(learningSummary, 'Learning plane protegido indisponivel neste runtime.');",
    "    setText(learningStatus, 'Valide o token para carregar os candidatos aprendidos.');",
    "    renderList(learningDetails, ['O runtime atual nao retornou nenhum snapshot de learning plane.']);",
    "  } else {",
    "    const summary = learningSnapshot.summary || {};",
    "    const candidates = Array.isArray(learningSnapshot.candidates) ? learningSnapshot.candidates : [];",
    "    setText(",
    "      learningState,",
    "      Number(summary.total || 0) > 0",
    "        ? String(summary.total || 0) + ' candidato(s)'",
    "        : 'Sem candidatos agora',",
    "    );",
    "    setText(",
    "      learningSummary,",
    "      pickFirstText([",
    "        learningSnapshot?.narrative?.operatorSummary,",
    "        learningSnapshot?.narrative?.headline,",
    "      ], 'Learning plane carregado.'),",
    "    );",
    "    setText(",
    "      learningStatus,",
    "      String(summary.pending || 0) + ' pendente(s) | '",
    "        + String(summary.promoted || 0) + ' trusted local | '",
    "        + String(summary.quarantined || 0) + ' em quarentena.'",
    "        + (learningMetrics?.summary",
    "          ? ' | score medio ' + String(Number(learningMetrics.summary.averageScore || 0).toFixed(3))",
    "          : ''),",
    "    );",
    "    const metricSummary = learningMetrics?.summary",
    "      ? '<strong>Metricas:</strong> aceitos '",
    "        + escapeHtml(String(learningMetrics.summary.acceptedRate || 0))",
    "        + ' | rejeitados '",
    "        + escapeHtml(String(learningMetrics.summary.rejectedRate || 0))",
    "        + ' | promovidos '",
    "        + escapeHtml(String(learningMetrics.summary.promotedRate || 0))",
    "      : '';",
    "    const items = candidates.slice(0, 3).map((candidate) => {",
    "      const candidateId = normalizeText(candidate?.id);",
    "      const score = Number(candidate?.score || 0);",
    "      const buttons = [];",
    "      if (normalizeText(candidate?.reviewState) === 'pending') {",
    "        buttons.push(buildLearningActionButton('approve', candidateId, 'Aprovar'));",
    "      }",
    "      if (normalizeText(candidate?.lifecycle) !== 'trusted_local' && normalizeText(candidate?.lifecycle) !== 'published') {",
    "        buttons.push(buildLearningActionButton('promote', candidateId, 'Promover'));",
    "      }",
    "      if (normalizeText(candidate?.lifecycle) !== 'quarantined') {",
    "        buttons.push(buildLearningActionButton('reject', candidateId, 'Quarentena'));",
    "      }",
    "      const actionRow = buttons.length > 0",
    "        ? '<div class=\"inline-action-row\">' + buttons.join('') + '</div>'",
    "        : '';",
    "      return '<strong>' + escapeHtml(candidate?.title || candidateId || 'Candidate') + ':</strong> '",
    "        + escapeHtml(candidate?.summary || 'Sem resumo.')",
    "        + ' <span class=\"muted-inline\">[score '",
    "        + escapeHtml(score ? score.toFixed(3) : '0.000')",
    "        + ' | '",
    "        + escapeHtml(candidate?.reviewState || 'pending')",
    "        + ' | '",
    "        + escapeHtml(candidate?.lifecycle || 'learned_draft')",
    "        + ']</span>'",
    "        + actionRow;",
    "    });",
    "    renderList(",
].join('\n');
