export const runtimeShellScriptPart4Seg1: string = [
    "      + ' | warnings ' + escapeHtml(String(entry?.validationWarnings || 0))",
    "      + (normalizeText(entry?.file) ? ' | ' + escapeHtml(normalizeText(entry.file)) : ''),",
    "    ).concat(",
    "      publishArtifacts.length === 0 ? ['Nenhum bundle recente salvo ainda neste host.'] : [],",
    "    ),",
    "  );",
    "  if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    ecosystemControlPlaneRefreshAction.hidden = false;",
    "    ecosystemControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderDistributedRuntimeControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    distributedRuntimeControlPlaneData = payload;",
    "  }",
    "  const snapshot = distributedRuntimeControlPlaneData?.distributedRuntime",
    "    || distributedRuntimeControlPlaneData?.snapshot",
    "    || distributedRuntimeControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(distributedRuntimeControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(distributedRuntimeControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(distributedRuntimeControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      distributedRuntimeControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado do runtime distribuido ainda nao respondeu neste host.'",
    "        : 'Channel Mesh, fleet, transports e surfaces oficiais aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(distributedRuntimeChannelsState, 'Sem leitura');",
    "    setText(distributedRuntimeChannelsSummary, 'Slack, WhatsApp, Signal, iMessage, Teams e Email aparecem neste recorte.');",
    "    setText(distributedRuntimeFleetState, 'Sem leitura');",
    "    setText(distributedRuntimeFleetSummary, 'Online, fila, stale e cobertura das capabilities avancadas aparecem aqui.');",
    "    setText(distributedRuntimeTransportsState, 'Sem leitura');",
    "    setText(distributedRuntimeTransportsSummary, 'Bridges, sidecars e node-hosts remotos aparecem aqui.');",
    "    setText(distributedRuntimeSurfacesState, 'Sem leitura');",
    "    setText(distributedRuntimeSurfacesSummary, 'Shell web, CLI, Telegram, Discord e remoto oficial aparecem aqui.');",
    "    setText(",
    "      distributedRuntimeControlPlaneStatus,",
    "      errorMessage || 'Valide o token para revisar channels, fleet, transports e surfaces da Distributed runtime.',",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneActions,",
    "      [errorMessage || 'Valide o token para revisar o proximo passo do runtime distribuido.'],",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneChannels,",
    "      [errorMessage || 'Valide o token para ver channels avancados sob o mesmo contrato canonico.'],",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneFleet,",
    "      [errorMessage || 'Valide o token para ver a cobertura das capabilities avancadas da fleet.'],",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneSurfaces,",
    "      [errorMessage || 'Valide o token para revisar shell web, CLI, Telegram, Discord e remoto oficial.'],",
    "    );",
    "    if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      distributedRuntimeControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      distributedRuntimeControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const advancedChannels = Array.isArray(snapshot.advancedChannels) ? snapshot.advancedChannels : [];",
    "  const fleetCapabilities = Array.isArray(snapshot.fleetCapabilities) ? snapshot.fleetCapabilities : [];",
    "  const surfaces = Array.isArray(snapshot.surfaces) ? snapshot.surfaces : [];",
    "",
    "  setCardEmphasis(distributedRuntimeControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(distributedRuntimeControlPlaneState, posture);",
    "  setText(",
    "    distributedRuntimeControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Runtime distribuido atualizado.',",
    "  );",
    "  setText(",
    "    distributedRuntimeChannelsState,",
    "    String(summary.readyAdvancedChannels || 0) + '/' + String(summary.advancedChannels || 0) + ' avancado(s)',",
    "  );",
    "  setText(",
    "    distributedRuntimeChannelsSummary,",
    "    String(summary.readyChannels || 0) + '/' + String(summary.totalChannels || 0)",
    "      + ' no contrato geral | attachments ' + String(summary.channelsWithAttachments || 0)",
    "      + ' | threads ' + String(summary.channelsWithThreads || 0),",
    "  );",
    "  setText(",
    "    distributedRuntimeFleetState,",
    "    String(summary.onlineNodes || 0) + '/' + String(summary.totalNodes || 0) + ' online',",
    "  );",
    "  setText(",
    "    distributedRuntimeFleetSummary,",
    "    'fila ' + String(summary.queuedInvocations || 0)",
    "      + ' | stale ' + String(summary.staleQueued || 0)",
    "      + ' | caps ' + String(summary.advancedCapabilityCoverage || 0) + '/8',",
    "  );",
    "  setText(",
    "    distributedRuntimeTransportsState,",
    "    String(summary.readyTransports || 0) + '/' + String(summary.totalTransports || 0) + ' pronto(s)',",
    "  );",
    "  setText(",
    "    distributedRuntimeTransportsSummary,",
    "    'live ' + String(summary.liveTransports || 0)",
    "      + ' | attention ' + String(summary.transportAttention || 0),",
    "  );",
    "  setText(",
    "    distributedRuntimeSurfacesState,",
    "    String(summary.readySurfaces || 0) + '/' + String(summary.totalSurfaces || 0) + ' pronta(s)',",
    "  );",
    "  setText(",
    "    distributedRuntimeSurfacesSummary,",
    "    'primaria ' + (summary.primarySurfaceReady ? 'ok' : 'pendente')",
    "      + ' | remoto ' + (summary.remoteReady ? 'ok' : 'pendente'),",
    "  );",
    "  setText(",
    "    distributedRuntimeControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Distributed runtime atualizada.',",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['Sem acoes sugeridas; mantenha a malha distribuida sob revisao periodica.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneChannels,",
    "    advancedChannels.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Channel')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.readiness || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || entry?.operatorSummary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.operatorNextStep || entry?.actionHint)",
    "        ? ' | ' + escapeHtml(normalizeText(entry?.operatorNextStep || entry?.actionHint))",
    "        : ''),",
    "    ).concat(",
    "      advancedChannels.length === 0 ? ['Nenhum channel avancado visivel neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneFleet,",
    "    fleetCapabilities.map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Capability')) + '</strong>: '",
    "      + escapeHtml(String(entry?.supportedNodes || 0) + ' node(s)')",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.category || 'misc'))",
    "      + (entry?.risky ? ' | sensivel' : ' | liberada')",
    "      + (normalizeText(entry?.actionHint) ? ' | ' + escapeHtml(normalizeText(entry.actionHint)) : ''),",
    "    ).concat(",
    "      fleetCapabilities.length === 0 ? ['Nenhuma capability avancada mapeada neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneSurfaces,",
    "    surfaces.map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Surface')) + '</strong>: '",
    "      + escapeHtml(entry?.ready ? 'pronta' : 'pendente')",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.description || 'Sem resumo.'))",
    "      + (normalizeText(entry?.entry) ? ' | ' + escapeHtml(normalizeText(entry.entry)) : '')",
    "      + (normalizeText(entry?.remoteEntry) ? ' | remoto ' + escapeHtml(normalizeText(entry.remoteEntry)) : ''),",
    "    ).concat(",
    "      surfaces.length === 0 ? ['Nenhuma superficie oficial mapeada neste recorte.'] : [],",
    "    ),",
    "  );",
    "  if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    distributedRuntimeControlPlaneRefreshAction.hidden = false;",
    "    distributedRuntimeControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderRuntimeStabilityControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    runtimeStabilityControlPlaneData = payload;",
    "  }",
    "  const snapshot = runtimeStabilityControlPlaneData?.runtimeStability",
    "    || runtimeStabilityControlPlaneData?.snapshot",
    "    || runtimeStabilityControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(runtimeStabilityControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(runtimeStabilityControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(runtimeStabilityControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      runtimeStabilityControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado de estabilidade ainda nao respondeu neste host.'",
    "        : 'Fleet, transports, keepalive e recovery aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(runtimeStabilityFleetState, 'Sem leitura');",
    "    setText(runtimeStabilityFleetSummary, 'Online, paired, fila e stale do Node Mesh aparecem aqui.');",
    "    setText(runtimeStabilityTransportsState, 'Sem leitura');",
    "    setText(runtimeStabilityTransportsSummary, 'Readiness, attention e doctor dos transports aparecem aqui.');",
    "    setText(runtimeStabilityKeepaliveState, 'Sem leitura');",
    "    setText(runtimeStabilityKeepaliveSummary, 'Processos supervisionados, restarts e staleness aparecem aqui.');",
    "    setText(runtimeStabilityRecoverState, 'Sem leitura');",
    "    setText(runtimeStabilityRecoverSummary, 'Issues recuperaveis e repair canonico aparecem aqui.');",
    "    setText(",
    "      runtimeStabilityControlPlaneStatus,",
    "      errorMessage || 'Valide o token para revisar keepalive, doctor e recovery supervisionado.',",
    "    );",
    "    renderList(",
    "      runtimeStabilityControlPlaneActions,",
    "      [errorMessage || 'Valide o token para revisar o proximo passo da estabilidade supervisionada.'],",
    "    );",
    "    renderList(",
    "      runtimeStabilityControlPlaneCards,",
    "      [errorMessage || 'Valide o token para ver fleet, transports, keepalive e recovery no mesmo quadro.'],",
    "    );",
    "    renderList(",
    "      runtimeStabilityControlPlaneProcesses,",
    "      [errorMessage || 'Valide o token para revisar proxy, gateway e node-host supervisionados.'],",
    "    );",
    "    if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      runtimeStabilityControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      runtimeStabilityControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const cards = Array.isArray(snapshot.cards) ? snapshot.cards : [];",
    "  const processes = Array.isArray(snapshot.keepalive?.processes) ? snapshot.keepalive.processes : [];",
    "",
    "  setCardEmphasis(runtimeStabilityControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(runtimeStabilityControlPlaneState, posture);",
    "  setText(",
    "    runtimeStabilityControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Estabilidade supervisionada atualizada.',",
    "  );",
    "  setText(",
    "    runtimeStabilityFleetState,",
    "    String(summary.onlineNodes || 0) + '/' + String(summary.totalNodes || 0) + ' online',",
    "  );",
    "  setText(",
    "    runtimeStabilityFleetSummary,",
    "    'paired ' + String(summary.pairedNodes || 0)",
    "      + ' | fila ' + String(summary.queuedInvocations || 0)",
    "      + ' | stale ' + String(summary.staleQueued || 0),",
    "  );",
    "  setText(",
    "    runtimeStabilityTransportsState,",
    "    String(summary.readyTransports || 0) + '/' + String(summary.totalTransports || 0) + ' pronto(s)',",
    "  );",
    "  setText(",
    "    runtimeStabilityTransportsSummary,",
    "    'attention ' + String(summary.transportAttention || 0)",
    "      + ' | recoverable ' + String(summary.recoverableIssues || 0),",
    "  );",
    "  setText(",
    "    runtimeStabilityKeepaliveState,",
    "    summary.keepaliveActive ? (summary.keepaliveStale ? 'stale' : 'ativo') : 'ausente',",
    "  );",
    "  setText(",
    "    runtimeStabilityKeepaliveSummary,",
    "    String(summary.keepaliveReadyProcesses || 0) + '/' + String(summary.keepaliveTotalProcesses || 0)",
    "      + ' processo(s) ready',",
    "  );",
    "  setText(",
    "    runtimeStabilityRecoverState,",
    "    String(summary.recoverableIssues || 0) + ' issue(s)',",
    "  );",
    "  setText(",
    "    runtimeStabilityRecoverSummary,",
    "    (summary.recoverableIssues || 0) > 0",
    "      ? 'Ha recovery pendente para limpar a malha supervisionada.'",
    "      : 'Sem repair urgente; mantenha doctor e keepalive em dia.',",
    "  );",
    "  setText(",
    "    runtimeStabilityControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Estabilidade supervisionada atualizada.',",
    "  );",
    "  renderList(",
    "    runtimeStabilityControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['Sem acoes sugeridas; mantenha keepalive e doctor recorrentes.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    runtimeStabilityControlPlaneCards,",
    "    cards.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Card')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      cards.length === 0 ? ['Nenhum card operacional gerado neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    runtimeStabilityControlPlaneProcesses,",
    "    processes.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.name || 'Processo')) + '</strong>: '",
    "      + escapeHtml(entry?.ready ? 'ready' : 'unhealthy')",
    "      + ' | restart ' + escapeHtml(String(entry?.restarts || 0))",
    "      + (normalizeText(entry?.lastError) ? ' | ' + escapeHtml(normalizeText(entry.lastError)) : ''),",
    "    ).concat(",
    "      processes.length === 0 ? ['Nenhum processo keepalive listado neste host.'] : [],",
    "    ),",
    "  );",
    "  if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    runtimeStabilityControlPlaneRefreshAction.hidden = false;",
    "    runtimeStabilityControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderAutomationControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    automationControlPlaneData = payload;",
    "  }",
    "  const snapshot = automationControlPlaneData?.automations",
    "    || automationControlPlaneData?.snapshot",
    "    || automationControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(automationControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(automationControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(automationControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      automationControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado de automacoes ainda nao respondeu neste host.'",
    "        : 'Automacoes naturais, maintenance e deliveries aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(automationControlPlaneTasksState, 'Sem leitura');",
    "    setText(automationControlPlaneTasksSummary, 'Scheduled runs ativos, pausados e com falha recente aparecem aqui.');",
    "    setText(automationControlPlaneMaintenanceState, 'Sem leitura');",
    "    setText(automationControlPlaneMaintenanceSummary, 'A manutencao recorrente e o proximo disparo aparecem aqui.');",
    "    setText(automationControlPlaneDeliveriesState, 'Sem leitura');",
    "    setText(automationControlPlaneDeliveriesSummary, 'App, email e webhook recentes aparecem aqui.');",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      errorMessage || 'Valide o token para criar automacoes e revisar o estado recorrente do host.',",
    "    );",
    "    renderList(",
    "      automationControlPlaneActions,",
    "      [errorMessage || 'Valide o token para revisar o proximo passo das automacoes.'],",
    "    );",
    "    renderList(",
    "      automationControlPlaneTasks,",
    "      [errorMessage || 'Valide o token para ver os agendamentos deste host.'],",
    "    );",
    "    renderList(",
    "      automationControlPlaneDeliveries,",
    "      [errorMessage || 'Valide o token para revisar entregas por app, email ou webhook.'],",
    "    );",
    "    if (automationControlPlaneCreateAction instanceof HTMLButtonElement) {",
    "      automationControlPlaneCreateAction.hidden = !protectedShellUnlocked;",
    "      automationControlPlaneCreateAction.disabled = false;",
    "    }",
    "    for (const button of [",
    "      automationControlPlaneRefreshAction,",
    "      automationControlPlaneMaintenanceOnAction,",
    "      automationControlPlaneMaintenanceOffAction,",
    "      automationControlPlaneMaintenanceRunAction,",
    "    ]) {",
    "      if (button instanceof HTMLButtonElement) {",
    "        button.hidden = !protectedShellUnlocked;",
    "        button.disabled = false;",
    "      }",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const tasks = Array.isArray(snapshot.tasks) ? snapshot.tasks : [];",
    "  const deliveries = Array.isArray(snapshot.deliveries) ? snapshot.deliveries : [];",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "",
    "  setCardEmphasis(automationControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(automationControlPlaneState, posture);",
    "  setText(",
    "    automationControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Automacoes atualizadas.',",
    "  );",
    "  setText(",
    "    automationControlPlaneTasksState,",
    "    String(summary.activeTasks || 0) + ' ativa(s)',",
    "  );",
    "  setText(",
    "    automationControlPlaneTasksSummary,",
    "    'pausadas ' + String(summary.pausedTasks || 0)",
    "      + ' | falhas ' + String(summary.failedTasks || 0),",
    "  );",
    "  setText(",
    "    automationControlPlaneMaintenanceState,",
    "    snapshot?.maintenance?.enabled ? 'ativa' : 'desligada',",
    "  );",
    "  setText(",
    "    automationControlPlaneMaintenanceSummary,",
    "    normalizeText(snapshot?.maintenance?.nextPlannedAt)",
    "      ? 'proxima ' + escapeHtml(formatRelativeTime(snapshot.maintenance.nextPlannedAt))",
    "      : 'sem proxima janela registrada',",
    "  );",
    "  setText(",
    "    automationControlPlaneDeliveriesState,",
    "    String(summary.deliveries || deliveries.length || 0) + ' recente(s)',",
    "  );",
    "  setText(",
    "    automationControlPlaneDeliveriesSummary,",
    "    deliveries.length > 0",
    "      ? 'ultimo canal: ' + normalizeText(deliveries[0]?.delivery || 'app')",
    "      : 'nenhuma entrega recente registrada.',",
    "  );",
    "  setText(",
    "    automationControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Scheduled runs atualizada.',",
    "  );",
    "  renderList(",
    "    automationControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(actions.length === 0 ? ['Sem acoes sugeridas; o plano recorrente esta estavel.'] : []),",
    "  );",
    "  renderList(",
    "    automationControlPlaneTasks,",
    "    tasks.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.shortId || entry?.id || 'task')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.schedule || 'sem agenda'))",
    "      + ' | ' + escapeHtml(normalizeText(entry?.prompt || 'sem prompt'))",
    "      + ' | ' + escapeHtml(normalizeText(entry?.delivery || 'telegram'))",
    "      + ' | ' + escapeHtml(normalizeText(entry?.status || 'idle'))",
    "      + (normalizeText(entry?.lastError) ? ' | ' + escapeHtml(normalizeText(entry.lastError)) : '')",
    "      + ' <button type=\"button\" class=\"inline-chip-button\" data-automation-action=\"pause\" data-automation-task-id=\"' + escapeHtml(normalizeText(entry?.shortId || '')) + '\">Pausar</button>'",
    "      + ' <button type=\"button\" class=\"inline-chip-button\" data-automation-action=\"resume\" data-automation-task-id=\"' + escapeHtml(normalizeText(entry?.shortId || '')) + '\">Retomar</button>'",
    "      + ' <button type=\"button\" class=\"inline-chip-button\" data-automation-action=\"remove\" data-automation-task-id=\"' + escapeHtml(normalizeText(entry?.shortId || '')) + '\">Remover</button>',",
    "    ).concat(tasks.length === 0 ? ['Nenhuma automacao cadastrada neste host.'] : []),",
    "  );",
    "  renderList(",
    "    automationControlPlaneDeliveries,",
    "    deliveries.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.delivery || 'app')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.target) ? ' | ' + escapeHtml(normalizeText(entry.target)) : ''),",
    "    ).concat(deliveries.length === 0 ? ['Nenhuma entrega recente registrada.'] : []),",
    "  );",
    "  if (automationControlPlaneCreateAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneCreateAction.hidden = false;",
    "    automationControlPlaneCreateAction.disabled = false;",
    "  }",
    "  for (const button of [",
    "    automationControlPlaneRefreshAction,",
    "    automationControlPlaneMaintenanceOnAction,",
    "    automationControlPlaneMaintenanceOffAction,",
    "    automationControlPlaneMaintenanceRunAction,",
    "  ]) {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.hidden = false;",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function renderRolloutReadinessControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    rolloutReadinessControlPlaneData = payload;",
    "  }",
    "  const snapshot = rolloutReadinessControlPlaneData?.rolloutReadiness",
    "    || rolloutReadinessControlPlaneData?.snapshot",
    "    || rolloutReadinessControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(rolloutReadinessControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(rolloutReadinessControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(rolloutReadinessControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      rolloutReadinessControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O consolidado de rollout readiness ainda nao respondeu neste host.'",
    "        : 'QA, maintenance e rollout persistente aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(rolloutReadinessQaState, 'Sem leitura');",
    "    setText(rolloutReadinessQaSummary, 'Gates de alpha/beta, regressions e readiness aparecem aqui.');",
    "    setText(rolloutReadinessDistributedState, 'Sem leitura');",
    "    setText(rolloutReadinessDistributedSummary, 'A postura do runtime distribuido entra como requisito do rollout.');",
    "    setText(rolloutReadinessMaintenanceState, 'Sem leitura');",
    "    setText(rolloutReadinessMaintenanceSummary, 'Maintenance recorrente e keepalive persistente aparecem aqui.');",
    "    setText(rolloutReadinessPublishState, 'Sem leitura');",
    "    setText(rolloutReadinessPublishSummary, 'Historico de publish e comparacoes com baseline aparecem aqui.');",
    "    setText(",
    "      rolloutReadinessControlPlaneStatus,",
    "      errorMessage || 'Valide o token para revisar gates, maintenance e publish do rollout persistente.',",
    "    );",
    "    renderList(",
    "      rolloutReadinessControlPlaneActions,",
    "      [errorMessage || 'Valide o token para revisar o proximo passo do rollout persistente.'],",
    "    );",
    "    renderList(",
    "      rolloutReadinessControlPlaneCards,",
    "      [errorMessage || 'Valide o token para ver QA, runtime, maintenance e publish no mesmo painel.'],",
    "    );",
    "    renderList(",
    "      rolloutReadinessControlPlanePublish,",
    "      [errorMessage || 'Valide o token para revisar o historico de publish do host.'],",
    "    );",
    "    if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      rolloutReadinessControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      rolloutReadinessControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const cards = Array.isArray(snapshot.cards) ? snapshot.cards : [];",
    "  const publishEntries = Array.isArray(snapshot.sourceSnapshots?.publishHistory)",
    "    ? snapshot.sourceSnapshots.publishHistory",
    "    : [];",
    "",
    "  setCardEmphasis(rolloutReadinessControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(rolloutReadinessControlPlaneState, posture);",
    "  setText(",
    "    rolloutReadinessControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Rollout persistente atualizado.',",
    "  );",
    "  setText(",
    "    rolloutReadinessQaState,",
    "    normalizeText(summary.qaPosture || 'unknown'),",
    "  );",
    "  setText(",
    "    rolloutReadinessQaSummary,",
    "    snapshot?.summary?.releaseReady ? 'Release pronto para promover.' : 'Ainda existem gates pendentes antes do release.',",
    "  );",
    "  setText(",
    "    rolloutReadinessDistributedState,",
    "    normalizeText(summary.distributedPosture || 'unknown'),",
    "  );",
    "  setText(",
    "    rolloutReadinessDistributedSummary,",
    "    'keepalive ' + (summary.keepaliveActive ? 'ok' : 'pendente')",
    "      + ' | runtime ' + normalizeText(summary.distributedPosture || 'unknown'),",
    "  );",
    "  setText(",
    "    rolloutReadinessMaintenanceState,",
    "    summary.maintenanceFresh ? 'fresco' : 'pendente',",
    "  );",
    "  setText(",
    "    rolloutReadinessMaintenanceSummary,",
    "    summary.maintenanceFresh",
    "      ? 'Maintenance recorrente recente para sustentar rollout longo.'",
    "      : 'O ciclo recorrente precisa ser renovado antes do rollout.',",
    "  );",
    "  setText(",
    "    rolloutReadinessPublishState,",
    "    String(summary.publishEntries || 0) + ' release(s)',",
    "  );",
    "  setText(",
    "    rolloutReadinessPublishSummary,",
    "    String(summary.publishComparisons || 0) + ' comparacao(oes) com baseline anterior',",
    "  );",
    "  setText(",
    "    rolloutReadinessControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Rollout persistente atualizado.',",
    "  );",
    "  renderList(",
    "    rolloutReadinessControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Acao')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'Sem motivo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['Sem acoes sugeridas; mantenha QA, maintenance e publish sob revisao periodica.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    rolloutReadinessControlPlaneCards,",
    "    cards.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Card')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'Sem resumo.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      cards.length === 0 ? ['Nenhum card operacional gerado neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    rolloutReadinessControlPlanePublish,",
    "    publishEntries.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.releaseId || entry?.packageId || 'Release')) + '</strong>: '",
].join('\n');
