export const runtimeShellScriptPart6Seg1: string = [
    "  if (channelId === 'discord') {",
    "    return 'Discord needs token, policy, and first pairing approval. Use the wizard to align guilds/channels and then close the initial DM.';",
    "  }",
    "  if (channelId === 'web') {",
    "    return 'Web is the main surface of this runtime. Use sessions_send and sessions_spawn to open new tracks without leaving the control plane.';",
    "  }",
    "  return 'Use the official wizard to connect or promote this channel before expanding mesh rollout.';",
    "}",
    "",
    "function renderChannelsOperationalCard() {",
    "  const channelMesh = operationalMeshData.channels?.channels || null;",
    "  const detail = operationalMeshData.channelDetail || null;",
    "  const latestAction = operationalMeshData.channelAction?.result || operationalMeshData.channelAction || null;",
    "  const installReport = operationalMeshData.channelInstall?.report || operationalMeshData.channelInstall || null;",
    "  const channelDoctor = operationalMeshData.channelDoctor?.doctor || operationalMeshData.channelDoctor || null;",
    "  const channelAssistant = operationalMeshData.channelAssistant?.assistant || operationalMeshData.channelAssistant || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.channels?.error",
    "    || operationalMeshData.channelDetail?.error",
    "    || operationalMeshData.channelAction?.error",
    "    || operationalMeshData.channelInstall?.error",
    "    || operationalMeshData.channelDoctor?.error",
    "    || operationalMeshData.channelAssistant?.error,",
    "  );",
    "",
    "  if (!channelMesh) {",
    "    setText(opsChannelsState, 'Unavailable');",
    "    setText(opsChannelsSummary, errorMessage || 'Channel Mesh protegido unavailable in this runtime.');",
    "    renderList(opsChannelsDetails, [errorMessage || 'Validate the token to review channel readiness, pairing, and promotion without falling back to legacy paths.']);",
    "    hideOperationalAction(opsChannelsAction);",
    "    hideOperationalPanel(opsChannelsPanel, opsChannelsPanelActions, opsChannelsPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = channelMesh.summary || {};",
    "  const selected = detail?.channel || channelMesh.selected || null;",
    "  const registry = detail?.registry || null;",
    "  const selectedId = normalizeText(selected?.id || operationalMeshSelection.channels);",
    "  const selectedLabel = normalizeText(selected?.label || selected?.id || '');",
    "  const selectedSummary = normalizeText(selected?.operatorSummary || selected?.summary || selected?.actionHint);",
    "  const selectedTransport = normalizeText(selected?.transport || registry?.transport || 'unknown');",
    "  const selectedInstallPlan = Array.isArray(installReport?.channels)",
    "    - installReport.channels.find((entry) => normalizeText(entry?.channelId) === selectedId) || null",
    "    : null;",
    "  const assistantSelected = channelAssistant?.selected || null;",
    "  const assistantStatus = normalizeText(channelAssistant?.status || '');",
    "  const assistantReply = normalizeText(channelAssistant?.naturalReply || '');",
    "  const assistantQuestion = Array.isArray(channelAssistant?.nextQuestions)",
    "    - normalizeText(channelAssistant.nextQuestions[0] || '')",
    "    : '';",
    "  const assistantAction = Array.isArray(channelAssistant?.nextActions)",
    "    - channelAssistant.nextActions[0] || null",
    "    : null;",
    "  const doctorItems = Array.isArray(channelDoctor?.items) ? channelDoctor.items : [];",
    "  const selectedDoctor = doctorItems.find((entry) => normalizeText(entry?.channelId) === selectedId) || null;",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'channels',",
    "    Array.isArray(channelMesh.entries) ? channelMesh.entries : [],",
    "    selectedId,",
    "    (entry) => entry?.id,",
    "    (entry) => entry?.label || entry?.id,",
    "  );",
    "  const promotionHint = buildChannelPromotionHint(selected, selectedInstallPlan);",
    "  operationalMeshSelection.channels = selectedId;",
    "",
    "  setText(",
    "    opsChannelsState,",
    "    summary.total",
    "      - String(summary.ready || 0) + '/' + String(summary.total || 0) + ' ready'",
    "      : 'without channels',",
    "  );",
    "  setText(",
    "    opsChannelsSummary,",
    "    selectedLabel",
    "      - selectedLabel + ': ' + (selectedSummary || 'without observoperational action now.')",
    "      : summary.total",
    "        - String(summary.configured || 0) + ' configured(s), ' + String(summary.partial || 0) + ' parcial(is) and ' + String(summary.planned || 0) + ' planejado(s).'",
    "        : 'No channel registered on this host.',",
    "  );",
    "",
    "  const fleetPreview = Array.isArray(channelMesh.entries)",
    "    - channelMesh.entries.slice(0, 5).map((entry) => {",
    "      const label = normalizeText(entry?.label || entry?.id || 'channel');",
    "      const readiness = normalizeText(entry?.readiness || 'unknown');",
    "      const transport = normalizeText(entry?.transport || 'unknown');",
    "      return escapeHtml(label) + ' [' + escapeHtml(readiness) + '; ' + escapeHtml(transport) + ']';",
    "    }).join(' | ')",
    "    : '';",
    "  const selectedActions = Array.isArray(selected?.actions) ? selected.actions : [];",
    "  const selectedFeatures = selected?.features || registry?.features || null;",
    "  const featureSummary = selectedFeatures",
    "    - [",
    "        selectedFeatures.sessionSend ? 'sessions_send' : '',",
    "        selectedFeatures.sessionSpawn ? 'sessions_spawn' : '',",
    "        selectedFeatures.attachments ? 'attachments' : '',",
    "        selectedFeatures.threads ? 'threads' : '',",
    "        selectedFeatures.groupPolicy ? 'group-policy' : '',",
    "      ].filter(Boolean).join(', ')",
    "    : '';",
    "  const latestActionSummary = pickFirstText([",
    "    latestAction?.summary,",
    "    Array.isArray(latestAction?.details) ? latestAction.details[0] : '',",
    "  ]);",
    "  const installSummary = selectedInstallPlan",
    "    - [",
    "        'modo current ' + normalizeText(selectedInstallPlan.currentMode || 'no configured'),",
    "        'recomendado ' + normalizeText(selectedInstallPlan.recommendedMode || 'n/a'),",
    "      ].join(' | ')",
    "    : '';",
    "  const doctorSummary = pickFirstText([",
    "    selectedDoctor?.summary,",
    "    channelDoctor?.summary,",
    "  ]);",
    "  const assistantSummary = pickFirstText([",
    "    assistantReply,",
    "    assistantSelected?.operatorNextStep,",
    "    assistantQuestion,",
    "  ]);",
    "  const modeButtons = selectedInstallPlan && Array.isArray(selectedInstallPlan.modes)",
    "    - selectedInstallPlan.modes.slice(0, 4).map((mode) => {",
    "        const normalizedMode = normalizeText(mode);",
    "        const label = normalizedMode === normalizeText(selectedInstallPlan.currentMode)",
    "          - 'Reapply ' + normalizedMode",
    "          : normalizedMode === normalizeText(selectedInstallPlan.recommendedMode)",
    "            - 'Promote: ' + normalizedMode",
    "            : 'Use ' + normalizedMode;",
    "        return buildOperationalButtonHtml('channels', 'channel-apply-mode', label, selectedId, normalizedMode);",
    "      })",
    "    : [];",
    "  const modeConfigButtons = selectedInstallPlan && Array.isArray(selectedInstallPlan.modes)",
    "    - selectedInstallPlan.modes.slice(0, 4).map((mode) => {",
    "        const normalizedMode = normalizeText(mode);",
    "        const label = normalizedMode === normalizeText(selectedInstallPlan.currentMode)",
    "          - 'Editar ' + normalizedMode",
    "          : 'Configure ' + normalizedMode;",
    "        return buildOperationalButtonHtml('channels', 'channel-configure-mode', label, selectedId, normalizedMode);",
    "      })",
    "    : [];",
    "",
    "  const items = operationalMeshExpanded.channels",
    "    - [",
    "        fleetPreview",
    "          - '<strong>Visible fleet:</strong> ' + fleetPreview",
    "          : '<strong>Visible fleet:</strong> in the channel registered now.',",
    "        selectedLabel",
    "          - '<strong>Focus:</strong> ' + escapeHtml(selectedLabel) + ' [' + escapeHtml(normalizeText(selected?.readiness || 'unknown')) + '; ' + escapeHtml(selectedTransport) + ']'",
    "          : '<strong>Focus:</strong> in the channel selected now.',",
    "        selectedSummary",
    "          - '<strong>Status:</strong> ' + escapeHtml(selectedSummary)",
    "          : '<strong>Status:</strong> without observoperational action now.',",
    "        selected?.actionHint",
    "          - '<strong>Next step:</strong> ' + escapeHtml(normalizeText(selected.actionHint))",
    "          : '<strong>Next step:</strong> without operational hint for this channel.',",
    "        featureSummary",
    "          - '<strong>Surface available:</strong> ' + escapeHtml(featureSummary)",
    "          : '<strong>Surface available:</strong> in the features registered on this focus.',",
    "        selectorRow",
    "          - '<strong>Switch focus:</strong> ' + selectorRow",
    "          : '<strong>Switch focus:</strong> in the channel registered now.',",
    "        latestActionSummary",
    "          - '<strong>Latest action:</strong> ' + escapeHtml(latestActionSummary)",
    "          : '<strong>Latest action:</strong> in the operational action has run in this shell session.',",
    "        installSummary",
    "          - '<strong>Scaffold:</strong> ' + escapeHtml(installSummary)",
    "          : '<strong>Scaffold:</strong> use <code>npm run setup:channels</code> to generate the plan from this channel.',",
    "        assistantSummary",
    "          - '<strong>Assistant:</strong> ' + escapeHtml(assistantSummary)",
    "          : '<strong>Assistant:</strong> open the assistant to receive the next step in natural language.',",
    "        doctorSummary",
    "          - '<strong>Doctor:</strong> ' + escapeHtml(doctorSummary)",
    "          : '<strong>Doctor:</strong> run the channel doctor to validate the current mode on this host.',",
    "        '<strong>Promocao:</strong> ' + escapeHtml(promotionHint),",
    "      ]",
    "    : [",
    "        selectedLabel",
    "          - '<strong>Focus:</strong> ' + escapeHtml(selectedLabel) + ' ? ' + escapeHtml(selectedSummary || promotionHint)",
    "          : '<strong>Configurados:</strong> ' + String(summary.configured || 0) + ' de ' + String(summary.total || 0) + '.',",
    "        '<strong>Guided setup:</strong> use <code>npm run setup:channels</code> to connect or promote channels without editing env manually.',",
    "        assistantSummary",
    "          - '<strong>Assistant:</strong> ' + escapeHtml(assistantSummary)",
    "          : '<strong>Assistant:</strong> open the panel to receive mode, variables, and next step.',",
    "      ];",
    "  renderList(opsChannelsDetails, items);",
    "",
    "  if (operationalMeshExpanded.channels) {",
    "    const panelButtons = [",
    "      buildOperationalCopyButtonHtml('Copy setup guiado', 'npm run setup:channels'),",
    "      buildOperationalCopyButtonHtml(",
    "        'Copy assistente CLI',",
    "        'npm run channels:assistant -- --channel ' + selectedId,",
    "      ),",
    "      buildOperationalButtonHtml('channels', 'channel-assistant', 'Abrir assistente', selectedId),",
    "      buildOperationalButtonHtml(",
    "        'channels',",
    "        'channel-assistant-apply',",
    "        assistantStatus === 'needs_scaffold' ? 'Apply assistant' : 'Reapply safe scaffold',",
    "        selectedId,",
    "        normalizeText(assistantSelected?.setupMode || selectedInstallPlan?.currentMode || selectedInstallPlan?.recommendedMode || ''),",
    "      ),",
    "      buildOperationalButtonHtml('channels', 'channel-assistant-doctor', 'Doctor assistido', selectedId),",
    "      buildOperationalButtonHtml('channels', 'channels-doctor', 'run doctor', selectedId),",
    "      ...selectedActions.slice(0, 4).map((entry) =>",
    "        buildOperationalButtonHtml(",
    "          'channels',",
    "          'channel-action',",
    "          normalizeText(entry?.label || entry?.kind || entry?.id || 'Action'),",
    "          selectedId,",
    "          normalizeText(entry?.id || entry?.kind),",
    "        ),",
    "      ),",
    "      ...modeButtons,",
    "      ...modeConfigButtons,",
    "    ];",
    "    showOperationalPanel(",
    "      opsChannelsPanel,",
    "      opsChannelsPanelTitle,",
    "      opsChannelsPanelSummary,",
    "      opsChannelsPanelActions,",
    "      opsChannelsPanelDetails,",
    "      {",
    "        title: selectedLabel || 'Channel Mesh',",
    "        summary: pickFirstText([",
    "          selectedSummary,",
    "          selected?.actionHint,",
    "          promotionHint,",
    "        ], 'No additional detail for the focused channel.'),",
    "        actionsHtml: [",
    "          selectorRow,",
    "          buildOperationalInlineButtons(panelButtons),",
    "        ].filter(Boolean).join(''),",
    "        details: [",
    "          selected",
    "            - '<strong>Readiness:</strong> ' + escapeHtml(normalizeText(selected?.readiness || 'unknown')) + ' | <strong>Transport:</strong> ' + escapeHtml(selectedTransport)",
    "            : '<strong>Readiness:</strong> in the channel on focus now.',",
    "          '<strong>configured:</strong> ' + escapeHtml(selected?.configured ? 'yes' : 'no') + ' | <strong>implementation:</strong> ' + escapeHtml(normalizeText(selected?.implementationState || 'n/a')),",
    "          selectedInstallPlan",
    "            - '<strong>Modo current:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.currentMode || 'no configured'))",
    "              + ' | <strong>Recomendado:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.recommendedMode || 'n/a'))",
    "            : '<strong>Current mode:</strong> use the scaffold to discover the recommended mode for this channel.',",
    "          selectedInstallPlan?.scaffoldEntries?.length",
    "            - '<strong>Inline editing:</strong> use Configure to review <code>KEY=value</code> fields for the selected mode before applying the scaffold.'",
    "            : '<strong>Inline editing:</strong> this channel exposes the extra scaffold beyond the current mode.',",
    "          channelAssistant",
    "            - '<strong>Assistant:</strong> ' + escapeHtml(assistantStatus || 'without status') + ' ? ' + escapeHtml(assistantReply || 'no natural-language response now.')",
    "            : '<strong>Assistant:</strong> open the assistant to consolidate scaffold, doctor, and next step.',",
    "          assistantQuestion",
    "            - '<strong>question of the assistente:</strong> ' + escapeHtml(assistantQuestion)",
    "            : '<strong>question of the assistente:</strong> without question pending now.',",
    "          assistantSelected?.operatorNextStep",
    "            - '<strong>Next step assistido:</strong> ' + escapeHtml(normalizeText(assistantSelected.operatorNextStep))",
    "            : '<strong>Next step assistido:</strong> without assisted action calculada now.',",
    "          assistantAction?.command",
    "            - '<strong>Action assistida:</strong> ' + escapeHtml(normalizeText(assistantAction.label || assistantAction.id)) + ' ? ' + escapeHtml(normalizeText(assistantAction.command))",
    "            : '<strong>Action assistida:</strong> in the calculated action now.',",
    "          selectedInstallPlan?.missingEnvKeys?.length",
    "            - '<strong>Missing:</strong> ' + escapeHtml(selectedInstallPlan.missingEnvKeys.join(', '))",
    "            : '<strong>Missing:</strong> no required field is pending for the current scaffold.',",
    "          selectedInstallPlan?.localWebhookUrl",
    "            - '<strong>Webhook local:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.localWebhookUrl))",
    "            : '<strong>Webhook local:</strong> does not apply to the current mode for this channel.',",
    "          selectedInstallPlan?.publicWebhookUrl",
    "            - '<strong>Webhook public:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.publicWebhookUrl))",
    "            : '<strong>Public webhook:</strong> publish when you want to operate outside the local host.',",
    "          featureSummary",
    "            - '<strong>Features:</strong> ' + escapeHtml(featureSummary)",
    "            : '<strong>Features:</strong> in the feature registrada in this foco.',",
    "          '<strong>Official promotion:</strong> ' + escapeHtml(promotionHint),",
    "          doctorSummary",
    "            - '<strong>Doctor:</strong> ' + escapeHtml(doctorSummary)",
    "            : '<strong>Doctor:</strong> without report recente from this channel in the shell.',",
    "          selectedDoctor?.recommendedAction",
    "            - '<strong>Action sugerida:</strong> ' + escapeHtml(normalizeText(selectedDoctor.recommendedAction))",
    "            : '<strong>Action sugerida:</strong> without additional doctor action now.',",
    "          selected?.actionHint",
    "            - '<strong>Hint of the mesh:</strong> ' + escapeHtml(normalizeText(selected.actionHint))",
    "            : '<strong>Mesh hint:</strong> no operational hint for this channel.',",
    "          registry",
    "            - '<strong>Registry canonical:</strong> ' + escapeHtml(normalizeText(registry?.label || selectedLabel || selectedId || 'channel')) + ' with transport ' + escapeHtml(normalizeText(registry?.transport || selectedTransport))",
    "            : '<strong>Registry canonical:</strong> without additional detail in this runtime.',",
    "          latestActionSummary",
    "            - '<strong>Latest action:</strong> ' + escapeHtml(latestActionSummary)",
    "            : '<strong>Latest action:</strong> in the operational action has run in this shell session.',",
    "          selectedInstallPlan?.commands?.apply",
    "            - '<strong>CLI canonica:</strong> ' + escapeHtml(normalizeText(selectedInstallPlan.commands.apply))",
    "            : '<strong>CLI canonica:</strong> use npm run setup:channels for the guided path.',",
    "          ...((Array.isArray(selected?.notes) ? selected.notes : []).slice(0, 4).map((note) =>",
    "            '<strong>Nota:</strong> ' + escapeHtml(normalizeText(note)),",
    "          )),",
    "          ...((Array.isArray(selectedInstallPlan?.notes) ? selectedInstallPlan.notes : []).slice(0, 3).map((note) =>",
    "            '<strong>Setup:</strong> ' + escapeHtml(normalizeText(note)),",
    "          )),",
    "          ...((Array.isArray(latestAction?.details) ? latestAction.details : []).slice(0, 3).map((detailLine) =>",
    "            '<strong>Action:</strong> ' + escapeHtml(normalizeText(detailLine)),",
    "          )),",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsChannelsPanel, opsChannelsPanelActions, opsChannelsPanelDetails);",
    "  }",
    "",
    "  setOperationalActionStatus(",
    "    opsChannelsStatus,",
    "    operationalMeshExpanded.channels",
    "      - 'Channel Mesh Panel aberto with foco, policy, hints de promotion and inline actions of the selected channel.'",
    "      : 'Open the Channel Mesh to review policy, pairing and promotion of the channels in the same style as the ZavorthControl.',",
    "  );",
    "  showOperationalAction(",
    "    opsChannelsAction,",
    "    operationalMeshExpanded.channels ? 'Back to summary' : 'Open channels panel',",
    "    operationalMeshExpanded.channels ? 'collapse' : 'channels-open',",
    "    selectedId,",
    "  );",
    "}",
    "",
    "function renderTransportsOperationalCard() {",
    "  const transports = operationalMeshData.transports?.transports || null;",
    "  const history = Array.isArray(operationalMeshData.transportHistory?.history?.entries)",
    "    - operationalMeshData.transportHistory.history.entries",
    "    : [];",
    "  const doctor = operationalMeshData.transportDoctor?.report || operationalMeshData.transportHistory?.doctor || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.transports?.error",
    "    || operationalMeshData.transportHistory?.error",
    "    || operationalMeshData.transportDoctor?.error,",
    "  );",
    "",
    "  if (!transports) {",
    "    setText(opsTransportsState, 'Unavailable');",
    "    setText(opsTransportsSummary, errorMessage || 'Protected remote plan unavailable in this runtime.');",
    "    renderList(opsTransportsDetails, [errorMessage || 'Validate the token to review health, attention, and recovery for the remote plan.']);",
    "    hideOperationalAction(opsTransportsAction);",
    "    hideOperationalPanel(opsTransportsPanel, opsTransportsPanelActions, opsTransportsPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = transports.summary || {};",
    "  const focus = transports.selected",
    "    || (Array.isArray(transports.entries)",
    "      - transports.entries.find((entry) => entry?.readiness !== 'ready' || Number(entry?.telemetry?.pendingWork || 0) > 0 || normalizeText(entry?.telemetry?.lastError))",
    "        || transports.entries[0]",
    "      : null);",
    "  const focusLabel = normalizeText(focus?.label || focus?.id || '');",
    "  const focusSummary = normalizeText(focus?.operatorSummary || focus?.telemetry?.statusLine || focus?.actionHint);",
    "  const focusId = normalizeText(focus?.id || operationalMeshSelection.transports);",
    "  operationalMeshSelection.transports = focusId;",
    "  const suggestedAction = Array.isArray(transports?.suggestedActions) && transports.suggestedActions.length > 0",
    "    - transports.suggestedActions[0]",
    "    : null;",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'transports',",
    "    Array.isArray(transports.entries) ? transports.entries : [],",
    "    focusId,",
    "    (entry) => entry?.id,",
    "    (entry) => entry?.label || entry?.id,",
    "  );",
    "  const historyItems = history.slice(0, 2).map((entry) => {",
    "    const action = normalizeText(entry?.action || 'action');",
    "    const status = normalizeText(entry?.status || 'unknown');",
    "    const summaryText = normalizeText(entry?.summary || entry?.resultSummary || entry?.command || 'No detail.');",
    "    return '<strong>' + escapeHtml(action) + ' [' + escapeHtml(status) + ']:</strong> ' + escapeHtml(summaryText);",
    "  });",
    "  const needsRecover = Boolean(",
    "    focusId",
    "    && (",
    "      normalizeText(focus?.telemetry?.lastError)",
    "      || Number(focus?.telemetry?.pendingWork || 0) > 0",
    "      || normalizeText(focus?.readiness) !== 'ready'",
    "    ),",
    "  );",
    "  const transportActionButtons = focusId",
    "    - '<div class=\"inline-action-row\">'",
    "      + buildOperationalInlineButton('transports', 'transport-doctor', focusId, 'run doctor of the foco')",
    "      + (needsRecover ? buildOperationalInlineButton('transports', 'transport-recover', focusId, 'Apply recover') : '')",
    "      + '</div>'",
    "    : '';",
    "  const fleetPreview = Array.isArray(transports.entries)",
    "    - transports.entries.slice(0, 4).map((entry) => {",
    "        const label = normalizeText(entry?.label || entry?.id || 'transporte');",
    "        const readiness = normalizeText(entry?.readiness || 'unknown');",
    "        const pending = Number(entry?.telemetry?.pendingWork || 0);",
    "        return escapeHtml(label) + ' [' + escapeHtml(readiness) + (pending ? '; ' + String(pending) + ' pend.' : '') + ']';",
    "      }).join(' | ')",
    "    : '';",
    "  const focusActions = Array.isArray(focus?.actions) ? focus.actions : [];",
    "  setText(",
    "    opsTransportsState,",
    "    summary.total",
    "      - String(summary.ready || 0) + '/' + String(summary.total || 0) + ' ready'",
    "      : 'without transportes',",
    "  );",
    "  setText(",
    "    opsTransportsSummary,",
    "    focusLabel",
    "      - focusLabel + ': ' + (focusSummary || 'without observoperational action now.')",
    "      : summary.total",
    "        - String(summary.attentionRequired || 0) + ' need attention; ' + String(summary.pendingWork || 0) + ' item(s) pending.'",
    "      : 'No remote transport registered on this host.',",
    "  );",
    "",
    "  const items = operationalMeshExpanded.transports",
    "    - [",
    "        fleetPreview",
    "          - '<strong>Visible fleet:</strong> ' + fleetPreview",
    "          : '<strong>Visible fleet:</strong> in the remote transport registered now.',",
    "        focusLabel",
    "          ? '<strong>Focus:</strong> ' + escapeHtml(focusLabel) + (focus?.readiness ? ' [' + escapeHtml(normalizeText(focus.readiness)) + ']' : '')",
    "          : '<strong>Focus:</strong> in the transport selecionado.',",
    "        focusSummary",
    "          - '<strong>Status:</strong> ' + escapeHtml(focusSummary)",
    "          : '<strong>Status:</strong> without observoperational action now.',",
    "        doctor?.summary",
    "          - '<strong>Doctor:</strong> ' + escapeHtml(normalizeText(doctor.summary))",
    "          : '<strong>Doctor:</strong> no dedicated report for the current focus.',",
    "        historyItems.length > 0",
    "          - '<strong>Recent history:</strong><br>' + historyItems.join('<br>')",
    "          : '<strong>Recent history:</strong> there are no recorded cycles for the current focus yet.',",
    "        selectorRow",
    "          - '<strong>Switch focus:</strong> ' + selectorRow",
    "          : '<strong>Switch focus:</strong> in the remote transport registered now.',",
    "        focusActions.length > 0",
    "          - '<strong>Actions inline:</strong> ' + escapeHtml(focusActions.slice(0, 3).map((entry) => normalizeText(entry?.label || entry?.id || 'action')).filter(Boolean).join(', '))",
    "          : '<strong>Actions inline:</strong> in the action exposed on this focus now.',",
    "        transportActionButtons || '<strong>Actions:</strong> select um transport to run doctor or recover.',",
    "        ...((transports?.suggestedActions || []).slice(0, 2).map((entry) =>",
    "          '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action sugerida')) + ':</strong> '",
    "          + escapeHtml(normalizeText(entry?.reason || entry?.command || 'No detail.'))",
    "        )),",
    "      ]",
    "    : [",
    "        focusLabel",
    "          ? '<strong>Focus:</strong> ' + escapeHtml(focusLabel) + (focus?.readiness ? ' [' + escapeHtml(normalizeText(focus.readiness)) + ']' : '') + (focusSummary ? ' ? ' + escapeHtml(focusSummary) : '.')",
    "          : '<strong>Parciais:</strong> ' + String(summary.partial || 0) + ' | <strong>planned:</strong> ' + String(summary.planned || 0) + '.',",
    "        suggestedAction",
    "          - '<strong>Next action:</strong> ' + escapeHtml(normalizeText(suggestedAction?.label || suggestedAction?.id || 'Action sugerida')) + ' ? ' + escapeHtml(normalizeText(suggestedAction?.reason || suggestedAction?.command || 'No detail.'))",
    "          : '<strong>Ao vivo:</strong> ' + String(summary.live || 0) + ' | <strong>reachable:</strong> ' + String(summary.reachable || 0) + '.',",
    "      ];",
    "  renderList(opsTransportsDetails, items);",
    "  if (operationalMeshExpanded.transports) {",
    "    const panelButtons = [",
    "      buildOperationalButtonHtml('transports', 'doctor', 'run doctor of the foco', focusId),",
    "      ...((Array.isArray(focus?.actions) ? focus.actions : []).slice(0, 2).map((entry) =>",
    "        buildOperationalButtonHtml(",
    "          'transports',",
    "          'remote-action',",
    "          normalizeText(entry?.label || entry?.id || 'Remote action'),",
    "          focusId,",
    "          normalizeText(entry?.id),",
    "        ),",
    "      )),",
    "    ];",
    "    if (needsRecover) {",
    "      panelButtons.push(buildOperationalButtonHtml('transports', 'recover', 'Apply recover', focusId));",
    "    }",
    "    showOperationalPanel(",
    "      opsTransportsPanel,",
    "      opsTransportsPanelTitle,",
    "      opsTransportsPanelSummary,",
    "      opsTransportsPanelActions,",
    "      opsTransportsPanelDetails,",
    "      {",
    "        title: focusLabel || 'Remote plan',",
    "        summary: pickFirstText([",
    "          focusSummary,",
    "          doctor?.summary,",
    "          transports?.narrative?.operatorSummary,",
    "        ], 'No additional detail for the focused transport.'),",
    "        actionsHtml: [",
    "          selectorRow,",
    "          buildOperationalInlineButtons(panelButtons),",
    "        ].filter(Boolean).join(''),",
    "        details: [",
    "          focus",
    "            - '<strong>Readiness:</strong> ' + escapeHtml(normalizeText(focus?.readiness || 'unknown')) + ' | <strong>Transport:</strong> ' + escapeHtml(normalizeText(focus?.transport || 'n/a'))",
    "            : '<strong>Readiness:</strong> in the transport in focus now.',",
    "          focus?.endpoint",
    "            - '<strong>Endpoint:</strong> ' + escapeHtml(normalizeText(focus.endpoint))",
    "            : '<strong>Endpoint:</strong> without endpoint public in this foco.',",
    "          focus?.telemetry",
    "            - '<strong>Telemetry:</strong> ' + escapeHtml(normalizeText(focus.telemetry.statusLine || 'No status line.')) + ' | pending items: ' + String(focus.telemetry.pendingWork || 0)",
    "            : '<strong>Telemetry:</strong> no recent telemetry for the current focus.',",
    "          normalizeText(focus?.telemetry?.lastError)",
    "            - '<strong>Latest error:</strong> ' + escapeHtml(normalizeText(focus.telemetry.lastError))",
    "            : '<strong>Latest error:</strong> no recent error exposed for this focus.',",
    "          focusActions.length > 0",
    "            - '<strong>Actions operational:</strong> ' + escapeHtml(focusActions.slice(0, 4).map((entry) => normalizeText(entry?.label || entry?.id || 'action')).filter(Boolean).join(', '))",
    "            : '<strong>Actions operational:</strong> in the remote action exposed now.',",
    "          Array.isArray(transports?.suggestedActions) && transports.suggestedActions.length > 0",
    "            - '<strong>next suggested action:</strong> ' + escapeHtml(normalizeText(transports.suggestedActions[0]?.label || transports.suggestedActions[0]?.id || 'action')) + ' ? '",
    "              + escapeHtml(normalizeText(transports.suggestedActions[0]?.reason || transports.suggestedActions[0]?.command || 'No detail.'))",
    "            : '<strong>next suggested action:</strong> in the additional recommendation for the remote plan.',",
    "          ...((Array.isArray(focus?.details) ? focus.details : []).slice(0, 2).map((detail) =>",
    "            '<strong>Detail:</strong> ' + escapeHtml(normalizeText(detail)),",
    "          )),",
    "          ...historyItems,",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsTransportsPanel, opsTransportsPanelActions, opsTransportsPanelDetails);",
    "  }",
    "  setOperationalActionStatus(",
    "    opsTransportsStatus,",
    "    operationalMeshExpanded.transports",
    "      - 'Remote panel opened with focus, doctor, history, and recovery for the selected transport.'",
    "      : 'Open the remote panel to review focus, history, and recovery without leaving the shell.',",
    "  );",
    "  showOperationalAction(",
    "    opsTransportsAction,",
    "    operationalMeshExpanded.transports ? 'Back to summary' : 'Open transports panel',",
    "    operationalMeshExpanded.transports ? 'collapse' : 'transports-open',",
    "    focusId,",
    "  );",
    "}",
    "",
    "function renderExtensionsOperationalCard() {",
    "  const extensions = operationalMeshData.extensions?.workspaceExtensions || null;",
    "  const plugins = operationalMeshData.plugins?.plugins || null;",
    "  const hooks = operationalMeshData.hooks?.hooks || null;",
    "  const latestHookRun = operationalMeshData.hooks?.run || null;",
    "  const latestHookPipeline = operationalMeshData.hooks?.pipeline || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.extensions?.error",
    "    || operationalMeshData.plugins?.error",
    "    || operationalMeshData.hooks?.error,",
    "  );",
    "",
    "  if (!extensions) {",
    "    setText(opsExtensionsState, 'Unavailable');",
    "    setText(opsExtensionsSummary, errorMessage || 'Catalog protegido de integrations unavailable in this runtime.');",
    "    renderList(opsExtensionsDetails, [errorMessage || 'Validate the token to review loaded workspaces, plugins, commands, and hooks.']);",
    "    hideOperationalAction(opsExtensionsAction);",
    "    hideOperationalPanel(opsExtensionsPanel, opsExtensionsPanelActions, opsExtensionsPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = extensions.summary || {};",
    "  const selected = extensions.selected",
    "    || (Array.isArray(extensions.entries) ? extensions.entries[0] : null);",
    "  const selectedId = normalizeText(selected?.slug || operationalMeshSelection.extensions);",
    "  operationalMeshSelection.extensions = selectedId;",
    "  const selectedLabel = normalizeText(selected?.workspaceName || selected?.slug || '');",
    "  const selectedLead = normalizeText(",
    "    selected?.instructionSummary",
    "      || selected?.instructionFile",
    "      || selected?.commands?.[0]?.template",
    "      || selected?.hooks?.[0]?.command,",
    "  );",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'extensions',",
    "    Array.isArray(extensions.entries) ? extensions.entries : [],",
    "    selectedId,",
    "    (entry) => entry?.slug,",
    "    (entry) => entry?.workspaceName || entry?.slug,",
    "  );",
    "  const commandItems = Array.isArray(selected?.commands)",
    "    - selected.commands.slice(0, 2).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.name || 'Command')) + ':</strong> ' + escapeHtml(normalizeText(entry?.template || 'without template.')),",
    "    )",
    "    : [];",
    "  const hookItems = Array.isArray(selected?.hooks)",
    "    - selected.hooks.slice(0, 2).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.event || 'Hook')) + ':</strong> ' + escapeHtml(normalizeText(entry?.command || 'without command.')),",
    "    )",
    "    : [];",
    "  const workspacePreview = Array.isArray(extensions.entries)",
    "    - extensions.entries.slice(0, 4).map((entry) => {",
    "        const label = normalizeText(entry?.workspaceName || entry?.slug || 'workspace');",
    "        const counts = String(entry?.commandCount || 0) + ' cmd / ' + String(entry?.hookCount || 0) + ' hook';",
    "        return escapeHtml(label) + ' [' + escapeHtml(counts) + ']';",
    "      }).join(' | ')",
    "    : '';",
    "  const pluginFocus = resolvePluginFocusEntry(plugins);",
    "  const extensionActionRow = buildExtensionActionRow(selected, plugins);",
    "  setText(",
    "    opsExtensionsState,",
    "    summary.workspaces",
    "      - String(summary.workspaces) + ' workspace(s)'",
    "      : 'without extensions',",
    "  );",
    "  setText(",
    "    opsExtensionsSummary,",
    "    selectedLabel",
    "      - selectedLabel + ': ' + (selectedLead || (String(selected?.commandCount || 0) + ' command(s) and ' + String(selected?.hookCount || 0) + ' hook(s).'))",
    "      : summary.workspaces",
    "        - String(summary.commands || 0) + ' command(s), ' + String(summary.hooks || 0) + ' hook(s) and ' + String(summary.withInstructions || 0) + ' with instructions.'",
    "      : 'No integration de workspace registrada on this host.',",
    "  );",
    "",
    "  const items = operationalMeshExpanded.extensions",
    "    - [",
    "        workspacePreview",
    "          - '<strong>Visible workspaces:</strong> ' + workspacePreview",
    "          : '<strong>Visible workspaces:</strong> in the workspace registered now.',",
    "        selectedLabel",
    "          - '<strong>Workspace:</strong> ' + escapeHtml(selectedLabel)",
    "            + ' - ' + String(selected?.commandCount || 0) + ' command(s), ' + String(selected?.hookCount || 0) + ' hook(s).'",
    "          : '<strong>Workspace:</strong> in the workspace selected now.',",
    "        selectedLead",
    "          - '<strong>Instrucao principal:</strong> ' + escapeHtml(selectedLead)",
].join('\n');
