export const runtimeShellScriptPart5Seg1: string = [
    "    ),",
    "  );",
    "",
    "  if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "    systemOverlordRefreshAction.hidden = false;",
    "    systemOverlordRefreshAction.disabled = false;",
    "  }",
    "  if (systemOverlordKillSwitchEnable instanceof HTMLButtonElement) {",
    "    systemOverlordKillSwitchEnable.hidden = false;",
    "    systemOverlordKillSwitchEnable.disabled = killSwitch?.active === true;",
    "  }",
    "  if (systemOverlordKillSwitchRelease instanceof HTMLButtonElement) {",
    "    systemOverlordKillSwitchRelease.hidden = false;",
    "    systemOverlordKillSwitchRelease.disabled = killSwitch?.active !== true;",
    "  }",
    "  if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "    systemOverlordRunAction.hidden = false;",
    "    systemOverlordRunAction.disabled = false;",
    "  }",
    "}",
    "",
    "async function refreshSystemOverlordPanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Validate the token before updating the System Overlord.');",
    "    return;",
    "  }",
    "",
    "  if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "    systemOverlordRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(systemOverlordStatus, 'Updating supervised System Overlord...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/system-overlord...limit=20', token);",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      normalizeText(payload?.snapshot?.narrative?.operatorSummary) || 'System Overlord updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(systemOverlordStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "      systemOverlordRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshEvalControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(evalControlPlaneStatus, 'Validate the token before updating operational evals.');",
    "    return;",
    "  }",
    "  if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    evalControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(evalControlPlaneStatus, 'Updating operational evals...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/evals', token);",
    "    renderEvalControlPlanePanel(payload);",
    "    setText(",
    "      evalControlPlaneStatus,",
    "      normalizeText(payload?.evals?.narrative?.operatorSummary) || 'Operational evals updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(evalControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      evalControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshHubControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(hubControlPlaneStatus, 'Validate the token before refreshing Hub + MCP.');",
    "    return;",
    "  }",
    "  if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(hubControlPlaneStatus, 'Updating Hub + MCP...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/hub', token);",
    "    renderHubControlPlanePanel(payload);",
    "    setText(",
    "      hubControlPlaneStatus,",
    "      normalizeText(payload?.hub?.narrative?.nextAction) || 'Hub + MCP updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(hubControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runHubControlPlaneAction(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(hubControlPlaneStatus, 'Validate the token before agir no Hub + MCP.');",
    "    return;",
    "  }",
    "  const button = mode === 'platform-sync' ? hubControlPlaneSyncAction : hubControlPlaneMcpDoctorAction;",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(",
    "      hubControlPlaneStatus,",
    "      mode === 'platform-sync'",
    "        - 'Syncing remote registry via Hub...'",
    "        : 'Running MCP doctor via Hub...',",
    "    );",
    "    const payload = await postProtectedJson('/api/web/hub/actions', token, {",
    "      actionId: mode,",
    "    });",
    "    renderHubControlPlanePanel(payload);",
    "    setText(",
    "      hubControlPlaneStatus,",
    "      pickFirstText([",
    "        payload?.action?.summary,",
    "        payload?.hub?.narrative?.nextAction,",
    "      ], 'Hub updated.'),",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(hubControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshQaControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(qaControlPlaneStatus, 'Validate the token before refreshing the QA control plane.');",
    "    return;",
    "  }",
    "  if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    qaControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(qaControlPlaneStatus, 'Updating QA control plane...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/qa', token);",
    "    renderQaControlPlanePanel(payload);",
    "    setText(",
    "      qaControlPlaneStatus,",
    "      normalizeText(payload?.qa?.narrative?.nextAction) || 'QA control plane updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(qaControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      qaControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshGovernanceControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(governanceControlPlaneStatus, 'Validate the token before updating Governance control plane.');",
    "    return;",
    "  }",
    "  if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    governanceControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(governanceControlPlaneStatus, 'Updating Governance control plane...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/governance', token);",
    "    renderGovernanceControlPlanePanel(payload);",
    "    setText(",
    "      governanceControlPlaneStatus,",
    "      normalizeText(payload?.governance?.narrative?.nextAction) || 'Governance control plane updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(governanceControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      governanceControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshReplayLearningControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(replayLearningControlPlaneStatus, 'Validate the token before refreshing the replay/learning control plane.');",
    "    return;",
    "  }",
    "  if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    replayLearningControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(replayLearningControlPlaneStatus, 'Updating replay, artifacts and learning loop...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/replay-learning', token);",
    "    renderReplayLearningControlPlanePanel(payload);",
    "    setText(",
    "      replayLearningControlPlaneStatus,",
    "      normalizeText(payload?.replayLearning?.narrative?.nextAction) || 'Replay/learning control plane updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(replayLearningControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      replayLearningControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshEcosystemControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(ecosystemControlPlaneStatus, 'Validate the token before refreshing the Ecosystem.');",
    "    return;",
    "  }",
    "  if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    ecosystemControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(ecosystemControlPlaneStatus, 'Updating SDKs, guides, publish and public catalog...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/ecosystem', token);",
    "    renderEcosystemControlPlanePanel(payload);",
    "    setText(",
    "      ecosystemControlPlaneStatus,",
    "      normalizeText(payload?.ecosystem?.narrative?.nextAction) || 'Ecosystem updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(ecosystemControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      ecosystemControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshDistributedRuntimeControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(distributedRuntimeControlPlaneStatus, 'Validate the token before refreshing the Distributed runtime.');",
    "    return;",
    "  }",
    "  if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    distributedRuntimeControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(distributedRuntimeControlPlaneStatus, 'Updating channels, fleet, transports and distributed runtime surfaces...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/distributed-runtime', token);",
    "    renderDistributedRuntimeControlPlanePanel(payload);",
    "    setText(",
    "      distributedRuntimeControlPlaneStatus,",
    "      normalizeText(payload?.distributedRuntime?.narrative?.nextAction) || 'Distributed runtime updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(distributedRuntimeControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      distributedRuntimeControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshRuntimeStabilityControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(runtimeStabilityControlPlaneStatus, 'Validate the token before refreshing supervised stability.');",
    "    return;",
    "  }",
    "  if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    runtimeStabilityControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(runtimeStabilityControlPlaneStatus, 'Updating fleet, transports, keepalive and recovery...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/runtime-stability', token);",
    "    renderRuntimeStabilityControlPlanePanel(payload);",
    "    setText(",
    "      runtimeStabilityControlPlaneStatus,",
    "      normalizeText(payload?.runtimeStability?.narrative?.nextAction) || 'Supervised stability updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(runtimeStabilityControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      runtimeStabilityControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshAutomationControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(automationControlPlaneStatus, 'Validate the token before refreshing automations.');",
    "    return;",
    "  }",
    "",
    "  if (automationControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/automations...limit=8', token);",
    "    renderAutomationControlPlanePanel(payload);",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      normalizeText(payload?.automations?.narrative?.nextAction) || 'Scheduled runs updated.',",
    "    );",
    "  } finally {",
    "    if (automationControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      automationControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runAutomationControlPlaneAction(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(automationControlPlaneStatus, 'Validate the token before agir nas automations.');",
    "    return;",
    "  }",
    "",
    "  const payload = {",
    "    actionId: mode,",
    "    intentText: normalizeText(automationControlPlaneIntent?.value),",
    "    taskId: normalizeText(automationControlPlaneIntent?.value),",
    "  };",
    "  const buttons = [",
    "    automationControlPlaneCreateAction,",
    "    automationControlPlaneRefreshAction,",
    "    automationControlPlaneMaintenanceOnAction,",
    "    automationControlPlaneMaintenanceOffAction,",
    "    automationControlPlaneMaintenanceRunAction,",
    "  ].filter((entry) => entry instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    const response = await postProtectedJson('/api/web/automations/actions', token, payload);",
    "    renderAutomationControlPlanePanel(response);",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      normalizeText(response?.action?.summary) || 'Scheduled runs updated.',",
    "    );",
    "    if (mode === 'create' && automationControlPlaneIntent instanceof HTMLInputElement && response?.action?.ok) {",
    "      automationControlPlaneIntent.value = '';",
    "    }",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      error instanceof Error ? err.message : 'Failed to execute the Scheduled runs action.',",
    "    );",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshRolloutReadinessControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(rolloutReadinessControlPlaneStatus, 'Validate the token before refreshing the persistent rollout.');",
    "    return;",
    "  }",
    "  if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    rolloutReadinessControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(rolloutReadinessControlPlaneStatus, 'Updating QA, maintenance, publish and persistent rollout...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/rollout-readiness', token);",
    "    renderRolloutReadinessControlPlanePanel(payload);",
    "    setText(",
    "      rolloutReadinessControlPlaneStatus,",
    "      normalizeText(payload?.rolloutReadiness?.narrative?.nextAction) || 'Persistent rollout updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(rolloutReadinessControlPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      rolloutReadinessControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshTrustPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(trustPlaneStatus, 'Validate the token before updating Trust Plane.');",
    "    return;",
    "  }",
    "",
    "  if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    trustPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(trustPlaneStatus, 'Updating Trust Plane...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/trust-plane', token);",
    "    renderTrustPlanePanel(payload);",
    "    setText(",
    "      trustPlaneStatus,",
    "      normalizeText(payload?.trustPlane?.narrative?.operatorSummary) || 'Trust Plane updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(trustPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      trustPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runTrustPlaneAction(actionId, body = {}) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(trustPlaneStatus, 'Validate the token before agir no Trust Plane.');",
    "    return;",
    "  }",
    "",
    "  const buttons = [",
    "    trustPlanePromoteTrustedAction,",
    "    trustPlaneHardenSafeAction,",
    "    trustPlaneSkillsDenyAction,",
    "  ].filter((entry) => entry instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(trustPlaneStatus, 'Applying Trust Plane policy...');",
    "    const payload = await postProtectedJson('/api/web/trust-plane/actions', token, {",
    "      actionId,",
    "      ...body,",
    "    });",
    "    renderTrustPlanePanel(payload);",
    "    setText(",
    "      trustPlaneStatus,",
    "      normalizeText(payload?.action?.summary)",
    "        || normalizeText(payload?.trustPlane?.narrative?.operatorSummary)",
    "        || 'Trust Plane updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(trustPlaneStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshWatchModePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Validate the token before refreshing Watch Mode.');",
    "    return;",
    "  }",
    "",
    "  if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "    watchModeRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(watchModeStatus, 'Updating Supervised Watch Mode...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/watch-mode...limit=8', token);",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      normalizeText(payload?.snapshot?.activeRun?.nextOperatorStep) || 'Watch Mode updated.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(watchModeStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "      watchModeRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModeStart() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Validate the token before starting Watch Mode.');",
    "    return;",
    "  }",
    "  const targetWindow = normalizeText(watchModeTargetWindow?.value);",
    "  const objective = normalizeText(watchModeObjective?.value);",
    "  if (!targetWindow || !objective) {",
    "    setText(watchModeStatus, 'Provide targetWindow and objective before starting Watch Mode.');",
    "    return;",
    "  }",
    "  if (watchModeStartAction instanceof HTMLButtonElement) {",
    "    watchModeStartAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(watchModeStatus, 'Starting Supervised Watch Mode...');",
    "    const payload = await postProtectedJson('/api/web/watch-mode/runs', token, {",
    "      targetWindow,",
    "      objective,",
    "      siteUrl: normalizeText(watchModeSiteUrl?.value) || null,",
    "      strictApproval: !(watchModeStrictApproval instanceof HTMLInputElement) || watchModeStrictApproval.checked,",
    "      requestedBy: 'web-watch-mode',",
    "    });",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      normalizeText(payload?.run?.nextOperatorStep) || 'Watch Mode started.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(watchModeStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (watchModeStartAction instanceof HTMLButtonElement) {",
    "      watchModeStartAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModePolicyAction(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Validate the token before ajustar a policy do Watch Mode.');",
    "    return;",
    "  }",
    "",
    "  const activeRun = watchModeData?.run || watchModeData?.snapshot?.activeRun || null;",
    "  const currentApp = normalizeText(watchModeTargetWindow?.value) || normalizeText(activeRun?.targetWindow);",
    "  const currentSite = normalizeText(watchModeSiteUrl?.value) || normalizeText(activeRun?.siteUrl);",
    "  const button = mode === 'allow-app'",
    "    - watchModeAllowAppAction",
    "    : mode === 'allow-site'",
    "      - watchModeAllowSiteAction",
    "      : mode === 'strict-on'",
    "        - watchModeStrictOnAction",
    "        : watchModeStrictOffAction;",
    "",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    let body = null;",
    "    if (mode === 'allow-app') {",
    "      if (!currentApp) {",
    "        setText(watchModeStatus, 'Provide a target window before promoting the app to allowlist.');",
    "        return;",
    "      }",
    "      body = {",
    "        actionId: 'allow-app',",
    "        app: currentApp,",
    "      };",
    "      setText(watchModeStatus, 'Promoting current window to Watch Mode allowlist...');",
    "    } else if (mode === 'allow-site') {",
    "      if (!currentSite) {",
    "        setText(watchModeStatus, 'Provide a site before promoting host to allowlist.');",
    "        return;",
    "      }",
    "      body = {",
    "        actionId: 'allow-site',",
    "        site: currentSite,",
    "      };",
    "      setText(watchModeStatus, 'Promoting current site to Watch Mode allowlist...');",
    "    } else {",
    "      body = {",
    "        actionId: 'set-strict-default',",
    "        strictApproval: mode === 'strict-on',",
    "      };",
    "      setText(",
    "        watchModeStatus,",
    "        mode === 'strict-on'",
    "          - 'Enforcing strict approval by default in Watch Mode...'",
    "          : 'Reducing Watch Mode friction for allowlist-first...',",
    "      );",
    "    }",
    "",
    "    const payload = await postProtectedJson('/api/web/watch-mode/policy', token, body);",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      mode === 'allow-app'",
    "        - 'Window added to Watch Mode allowlist.'",
    "        : mode === 'allow-site'",
    "          - 'Site added to Watch Mode allowlist.'",
    "          : mode === 'strict-on'",
    "            - 'Strict approval enabled by default.'",
    "            : 'Strict approval disabled by default.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setText(watchModeStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModeMutation(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Validate the token before mutar o Watch Mode.');",
    "    return;",
    "  }",
].join('\n');
