export const runtimeShellScriptPart5Seg2: string = [
    "  const runId = normalizeText(watchModeData?.run?.runId || watchModeData?.snapshot?.activeRun?.runId);",
    "  if (!runId) {",
    "    setText(watchModeStatus, 'There is in the active visual run for this action.');",
    "    return;",
    "  }",
    "",
    "  const button = mode === 'pause'",
    "    - watchModePauseAction",
    "    : mode === 'resume'",
    "      - watchModeResumeAction",
    "      : watchModeStopAction;",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    const payload = await postProtectedJson('/api/web/watch-mode/runs/' + encodeURIComponent(runId) + '/' + mode, token, {",
    "      requestedBy: 'web-watch-mode',",
    "    });",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      mode === 'pause'",
    "        - 'Watch Mode paused.'",
    "        : mode === 'resume'",
    "          - 'Watch Mode resumed.'",
    "          : 'Watch Mode stopped.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(watchModeStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModeApprovalDecision(approvalId, decision) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Validate the token before deciding a visual approval.');",
    "    return;",
    "  }",
    "  const runId = normalizeText(watchModeData?.run?.runId || watchModeData?.snapshot?.activeRun?.runId);",
    "  if (!runId || !approvalId) {",
    "    setText(watchModeStatus, 'Visual approval unavailable at this time.');",
    "    return;",
    "  }",
    "  try {",
    "    const payload = await postProtectedJson(",
    "      '/api/web/watch-mode/runs/' + encodeURIComponent(runId) + '/approvals/' + encodeURIComponent(approvalId),",
    "      token,",
    "      {",
    "        decision,",
    "        requestedBy: 'web-watch-mode',",
    "      },",
    "    );",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      decision === 'approve'",
    "        - 'Visual approval granted.'",
    "        : 'Visual approval denied; the agent will observe again before acting.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(watchModeStatus, error instanceof Error ? err.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSystemOverlordSupervisedAction() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Validate the token before executing a supervised action.');",
    "    return;",
    "  }",
    "  const command = normalizeText(systemOverlordCommand?.value);",
    "  if (!command) {",
    "    setText(systemOverlordStatus, 'Provide a short command or payload before executing.');",
    "    return;",
    "  }",
    "",
    "  if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "    systemOverlordRunAction.disabled = true;",
    "  }",
    "  try {",
    "    const dryRun = !(systemOverlordDryRun instanceof HTMLInputElement) || systemOverlordDryRun.checked;",
    "    setText(systemOverlordStatus, dryRun ? 'Simulating supervised action...' : 'Executing supervised action...');",
    "    const payload = await postProtectedJson('/api/web/system-overlord/actions', token, {",
    "      capability: normalizeText(systemOverlordCapability?.value) || 'host.shell',",
    "      profile: normalizeText(systemOverlordProfile?.value) || 'safe',",
    "      autonomyLevel: Number(systemOverlordAutonomy?.value || 1) || 1,",
    "      command,",
    "      dryRun,",
    "      approved: systemOverlordApproved instanceof HTMLInputElement ? systemOverlordApproved.checked : false,",
    "      requestedBy: 'web-operator',",
    "      metadata: {",
    "        source: 'web-system-overlord-panel',",
    "      },",
    "    });",
    "    renderSystemOverlordPanel(payload);",
    "    const action = payload?.action || null;",
    "    setText(",
    "      systemOverlordStatus,",
    "      action",
    "        - 'Action ' + normalizeText(action.actionId || 'supervised') + ' became ' + normalizeText(action.status || 'n/d') + '.'",
    "        : 'Supervised action sent.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(systemOverlordStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "      systemOverlordRunAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runSystemOverlordApprovalDecision(actionId, mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Validate the token before deciding approvals.');",
    "    return;",
    "  }",
    "  const normalizedActionId = normalizeText(actionId);",
    "  const normalizedMode = normalizeText(mode);",
    "  if (!normalizedActionId || !normalizedMode) {",
    "    setText(systemOverlordStatus, 'Invalid approval for decision.');",
    "    return;",
    "  }",
    "",
    "  const decision = normalizedMode === 'reject' ? 'reject' : 'approve';",
    "  const dryRun = normalizedMode === 'approve-dry-run';",
    "  try {",
    "    setText(",
    "      systemOverlordStatus,",
    "      decision === 'reject'",
    "        - 'Rejecting supervised approval...'",
    "        : dryRun",
    "          - 'Approving dry-run approval...'",
    "          : 'Approving and executing supervised action...',",
    "    );",
    "    const payload = await postProtectedJson(",
    "      '/api/web/system-overlord/approvals/' + encodeURIComponent(normalizedActionId),",
    "      token,",
    "      {",
    "        decision,",
    "        dryRun,",
    "        requestedBy: 'web-operator',",
    "        reason: decision === 'reject'",
    "          - 'Rejected by the operator in ZavorthControl web.'",
    "          : dryRun",
    "            - 'Approved as dry-run by the operator in ZavorthControl web.'",
    "            : 'Approved for execution by the operator in ZavorthControl web.',",
    "      },",
    "    );",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      payload?.approval",
    "        - 'Approval ' + normalizedActionId + ' became ' + normalizeText(payload.approval.status || 'n/d') + '.'",
    "        : 'Approval decided.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(systemOverlordStatus, error instanceof Error ? err.message : String(error));",
    "  }",
    "}",
    "",
    "async function runSystemOverlordKillSwitch(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Validate the token before operating the supervised kill switch.');",
    "    return;",
    "  }",
    "  const activate = normalizeText(mode) !== 'release';",
    "  const button = activate ? systemOverlordKillSwitchEnable : systemOverlordKillSwitchRelease;",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(",
    "      systemOverlordStatus,",
    "      activate",
    "        - 'Enabling supervised kill switch...'",
    "        : 'Releasing supervised kill switch...',",
    "    );",
    "    const payload = await postProtectedJson('/api/web/system-overlord/kill-switch', token, {",
    "      active: activate,",
    "      cancelActive: activate,",
    "      requestedBy: 'web-operator',",
    "      reason: activate",
    "        - 'Kill switch activated by the operator in ZavorthControl web.'",
    "        : 'Kill switch released by the operator in ZavorthControl web.',",
    "    });",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      payload?.killSwitch?.active",
    "        - 'Kill switch active. ' + String((payload?.affectedActions || []).length || 0) + ' action(s) cancelled on activation.'",
    "        : 'Kill switch released. New supervised actions can resume.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(systemOverlordStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runSystemOverlordActionMutation(actionId, mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Validate the token before canceling or reverting supervised actions.');",
    "    return;",
    "  }",
    "  const normalizedActionId = normalizeText(actionId);",
    "  const normalizedMode = normalizeText(mode);",
    "  if (!normalizedActionId || !normalizedMode) {",
    "    setText(systemOverlordStatus, 'Action supervised invalid for mutation.');",
    "    return;",
    "  }",
    "  const endpoint = normalizedMode === 'rollback'",
    "    - '/api/web/system-overlord/actions/' + encodeURIComponent(normalizedActionId) + '/rollback'",
    "    : '/api/web/system-overlord/actions/' + encodeURIComponent(normalizedActionId) + '/cancel';",
    "  try {",
    "    setText(",
    "      systemOverlordStatus,",
    "      normalizedMode === 'rollback'",
    "        - 'Running supervised rollback...'",
    "        : 'Cancelling supervised action...',",
    "    );",
    "    const payload = await postProtectedJson(endpoint, token, {",
    "      requestedBy: 'web-operator',",
    "      reason: normalizedMode === 'rollback'",
    "        - 'Rollback requested by the operator in ZavorthControl web.'",
    "        : 'Cancellation requested by the operator in ZavorthControl web.',",
    "    });",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      payload?.action",
    "        - 'Action ' + normalizedActionId + ' now shows as ' + normalizeText(payload.action.status || 'n/d') + '.'",
    "        : 'Supervised mutation completed.',",
    "    );",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(systemOverlordStatus, error instanceof Error ? err.message : String(error));",
    "  }",
    "}",
    "",
    "function scrollToCockpitTarget(targetId) {",
    "  const target = document.getElementById(targetId);",
    "  if (!(target instanceof HTMLElement)) {",
    "    return;",
    "  }",
    "  target.scrollIntoView({ behavior: 'smooth', block: 'start' });",
    "  setText(operatorCockpitStatus, 'Jumping to the selected operational block.');",
    "  setCardEmphasis(target, 'focus');",
    "  window.setTimeout(() => {",
    "    target.classList.remove('card-focus', 'card-subtle');",
    "  }, 1800);",
    "}",
    "",
    "async function runOperatorCockpitRefresh(button) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(operatorCockpitStatus, 'Validate the token before updating the protected cockpit.');",
    "    return;",
    "  }",
    "",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(operatorCockpitStatus, 'Updating cockpit, sessions and operational mesh...');",
    "    await refreshProtectedShellState(token);",
    "    setText(operatorCockpitStatus, 'Cockpit updated with the latest protected state.');",
    "  } catch (error: unknown) { const err = asErrorLike(error); const and = err;",
    "    setText(operatorCockpitStatus, error instanceof Error ? err.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function installOperatorCockpitActions() {",
    "  if (!(operatorActionRail instanceof HTMLElement)) {",
    "    return;",
    "  }",
    "",
    "  operatorActionRail.addEventListener('click', (event) => {",
    "    if (!(event.target instanceof Element)) {",
    "      return;",
    "    }",
    "    const button = event.target.closest('[data-cockpit-action],[data-cockpit-target]');",
    "    if (!(button instanceof HTMLButtonElement)) {",
    "      return;",
    "    }",
    "    event.preventDefault();",
    "    const action = normalizeText(button.dataset.cockpitAction);",
    "    const targetId = normalizeText(button.dataset.cockpitTarget);",
    "    if (action === 'refresh') {",
    "      void runOperatorCockpitRefresh(button);",
    "      return;",
    "    }",
    "    if (targetId) {",
    "      scrollToCockpitTarget(targetId);",
    "    }",
    "  });",
    "}",
    "",
    "function hideOperationalAction(target) {",
    "  if (!(target instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  target.hidden = true;",
    "  target.disabled = false;",
    "  target.dataset.mode = '';",
    "  target.dataset.targetId = '';",
    "}",
    "",
    "function showOperationalAction(target, label, mode = 'collapse', targetId = '') {",
    "  if (!(target instanceof HTMLButtonElement)) {",
    "    return;",
    "  }",
    "  target.hidden = false;",
    "  target.textContent = label;",
    "  target.dataset.mode = mode;",
    "  target.dataset.targetId = targetId || '';",
    "}",
    "",
    "function setOperationalActionStatus(target, value) {",
    "  setText(target, value);",
    "}",
    "",
    "function hideOperationalPanel(panel, actionsTarget, detailsTarget) {",
    "  if (panel) {",
    "    panel.hidden = true;",
    "  }",
    "  if (actionsTarget) {",
    "    actionsTarget.innerHTML = '';",
    "  }",
    "  renderList(detailsTarget, ['Open the panel to review the operational focus of this host.']);",
    "}",
    "",
    "function showOperationalPanel(panel, titleTarget, summaryTarget, actionsTarget, detailsTarget, config) {",
    "  if (panel) {",
    "    panel.hidden = false;",
    "  }",
    "  setText(titleTarget, normalizeText(config?.title) || 'Operational panel');",
    "  setText(",
    "    summaryTarget,",
    "    normalizeText(config?.summary) || 'No additional detail for the current operational focus.',",
    "  );",
    "  if (actionsTarget) {",
    "    actionsTarget.innerHTML = normalizeText(config?.actionsHtml) ? sanitizePanelHtml(config.actionsHtml) : '';",
    "  }",
    "  renderList(",
    "    detailsTarget,",
    "    Array.isArray(config?.details) && config.details.length > 0",
    "      - config.details",
    "      : ['No additional detail for the current operational focus.'],",
    "  );",
    "}",
    "",
    "function renderNodesOperationalCard() {",
    "  const nodeMesh = operationalMeshData.nodes?.nodeMesh || null;",
    "  const doctor = operationalMeshData.nodeDoctor?.doctor || null;",
    "  const activity = operationalMeshData.nodeActivity?.activity || null;",
    "  const capabilities = operationalMeshData.nodeCapabilities?.capabilities || null;",
    "  const bootstrapDraft = operationalMeshData.nodeBootstrap?.draft || null;",
    "  const errorMessage = normalizeText(",
    "    operationalMeshData.nodes?.error",
    "    || operationalMeshData.nodeDoctor?.error",
    "    || operationalMeshData.nodeActivity?.error",
    "    || operationalMeshData.nodeCapabilities?.error,",
    "  );",
    "",
    "  if (!nodeMesh) {",
    "    setText(opsNodesState, 'Unavailable');",
    "    setText(opsNodesSummary, errorMessage || 'Protected Node Mesh unavailable in this runtime.');",
    "    renderList(opsNodesDetails, [errorMessage || 'Validate the token to review nodes, queue and pairing of the current host.']);",
    "    hideOperationalAction(opsNodesAction);",
    "    hideOperationalPanel(opsNodesPanel, opsNodesPanelActions, opsNodesPanelDetails);",
    "    return;",
    "  }",
    "",
    "  const summary = nodeMesh.summary || {};",
    "  const selected = nodeMesh.selected || null;",
    "  const selectedActivity = nodeMesh.selectedActivity || null;",
    "  const firstIssue = Array.isArray(doctor?.issues) && doctor.issues.length > 0 ? doctor.issues[0] : null;",
    "  const selectedLabel = normalizeText(selected?.label || selected?.id || '');",
    "  const selectedAction = normalizeText(selected?.nextAction || selected?.operatorSummary);",
    "  const selectedId = normalizeText(selected?.id || operationalMeshSelection.nodes);",
    "  const allowlistAudit = selected?.allowlistAudit || null;",
    "  const hostHints = selected?.hostHints || {};",
    "  operationalMeshSelection.nodes = selectedId;",
    "  const selectorRow = buildOperationalSelectorRow(",
    "    'nodes',",
    "    Array.isArray(nodeMesh.entries) ? nodeMesh.entries : [],",
    "    selectedId,",
    "    (entry) => entry?.id,",
    "    (entry) => entry?.label || entry?.id,",
    "  );",
    "  setText(",
    "    opsNodesState,",
    "    summary.total",
    "      - String(summary.online || 0) + '/' + String(summary.total || 0) + ' online'",
    "      : 'No nodes',",
    "  );",
    "  setText(",
    "    opsNodesSummary,",
    "    doctor?.status === 'attention'",
    "      - ((selectedLabel",
    "        - selectedLabel + ': '",
    "        : '')",
    "        + (normalizeText(firstIssue?.summary || firstIssue?.actionHint) || String((doctor.issues || []).length) + ' pending item(s) in the Node Mesh doctor.'))",
    "      : selectedLabel",
    "        - selectedLabel + ': ' + (selectedAction || 'no next operational action now.')",
    "      : (summary.total",
    "        - String(summary.paired || 0) + ' paired, ' + String(summary.queued || 0) + ' item(s) in queue.'",
    "        : 'No node registered on this host.'),",
    "  );",
    "",
    "  const items = operationalMeshExpanded.nodes",
    "    - [",
    "        Array.isArray(nodeMesh.entries) && nodeMesh.entries.length > 0",
    "          - '<strong>Visible fleet:</strong> ' + nodeMesh.entries",
    "            .slice(0, 4)",
    "            .map((entry) => {",
    "              const trust = normalizeText(entry?.trustLabel || entry?.pairingStatus || 'no trust');",
    "              const label = normalizeText(entry?.label || entry?.id || 'node');",
    "              const status = normalizeText(entry?.status || 'unknown');",
    "              return escapeHtml(label) + ' [' + escapeHtml(status) + '; ' + escapeHtml(trust) + ']';",
    "            })",
    "            .join(' | ')",
    "          : '<strong>Visible fleet:</strong> in the node registered now.',",
    "        selectedLabel",
    "          - '<strong>Selected:</strong> ' + escapeHtml(selectedLabel) + ' [' + escapeHtml(normalizeText(selected?.status || 'unknown')) + ']'",
    "          : '<strong>Selected:</strong> No node on focus now.',",
    "        selected",
    "          - '<strong>Trust:</strong> ' + escapeHtml(normalizeText(selected?.trustLabel || 'no policy visible')) + ' | <strong>Pairing:</strong> ' + escapeHtml(normalizeText(selected?.pairingStatus || 'unknown'))",
    "          : '<strong>Pairing:</strong> No node selected.',",
    "        selectedActivity?.narrative?.operatorSummary",
    "          - '<strong>Activity:</strong> ' + escapeHtml(normalizeText(selectedActivity.narrative.operatorSummary))",
    "          : '<strong>Activity:</strong> in the live queue for the focused node.',",
    "        capabilities?.summary",
    "          - '<strong>Capabilities:</strong> ' + String(capabilities.summary.total || 0) + ' totais, ' + String(capabilities.summary.risky || 0) + ' arriscadas and categorias ' + escapeHtml((capabilities.summary.categories || []).join(', ') || 'n/a') + '.'",
    "          : '<strong>Capabilities:</strong> select um node to review allowlist and catalog.',",
    "        selectorRow",
    "          - '<strong>Switch focus:</strong> ' + selectorRow",
    "          : '<strong>Switch focus:</strong> in the node registered now.',",
    "        normalizeText(doctor?.summary)",
    "          - '<strong>Doctor:</strong> ' + escapeHtml(normalizeText(doctor.summary))",
    "          : '<strong>Doctor:</strong> without issues abertas now.',",
    "        bootstrapDraft?.bootstrap?.command",
    "          - '<strong>Bootstrap:</strong> draft pending ready for copiar in the host selecionado.'",
    "          : '<strong>Bootstrap:</strong> without bootstrap pending for the focused node.',",
    "        ...((doctor?.issues || []).slice(0, 2).map((issue) =>",
    "          '<strong>' + escapeHtml(normalizeText(issue?.label || issue?.nodeId || 'Node')) + ':</strong> '",
    "          + escapeHtml(normalizeText(issue?.summary || issue?.actionHint || 'No observation.'))",
    "        )),",
    "        '<div class=\"inline-action-row\">' + buildOperationalInlineButton('nodes', 'nodes-doctor', selectedId, 'run doctor of the mesh') + '</div>',",
    "      ]",
    "    : [",
    "        selectedLabel",
    "          ? '<strong>Foco:</strong> ' + escapeHtml(selectedLabel) + (selectedAction ? ' ? ' + escapeHtml(selectedAction) : '.')",
    "          : '<strong>Pareados:</strong> ' + String(summary.paired || 0) + ' de ' + String(summary.total || 0) + '.',",
    "        firstIssue",
    "          - '<strong>Next action:</strong> ' + escapeHtml(normalizeText(firstIssue?.actionHint || firstIssue?.recoverKind || doctor?.summary || 'review doctor of the mesh.'))",
    "          : '<strong>Doctor:</strong> ' + escapeHtml(normalizeText(doctor?.summary || ('Old queue: ' + String(summary.staleQueued || 0) + ' item(s) and ' + String(summary.expiredDrafts || 0) + ' draft(s) expired.'))),",
    "      ];",
    "  renderList(opsNodesDetails, items);",
    "    if (operationalMeshExpanded.nodes) {",
    "      const approvedCount = Array.isArray(selected?.approvedCapabilityIds) ? selected.approvedCapabilityIds.length : 0;",
    "      const declaredCount = Array.isArray(selected?.capabilityIds) ? selected.capabilityIds.length : 0;",
    "      const maintenance = activity?.maintenance || selectedActivity?.maintenance || selected?.maintenance || null;",
    "      const recoverKind = normalizeText(maintenance?.recoverKind || firstIssue?.recoverKind || '');",
    "      const nodePolicyActionRow = buildNodePolicyActionRow(selected, capabilities);",
    "      const panelButtons = [",
    "        buildOperationalButtonHtml('nodes', 'doctor', 'run doctor of the mesh', selectedId),",
    "      ];",
    "      if (selectedId && normalizeText(selected?.pairingStatus) === 'pending') {",
    "        panelButtons.push(buildOperationalButtonHtml('nodes', 'bootstrap', 'Copiar bootstrap', selectedId));",
    "      }",
    "      if (selectedId && recoverKind) {",
    "        panelButtons.push(buildOperationalButtonHtml('nodes', 'recover', 'Apply recover', selectedId, recoverKind));",
    "    }",
    "    showOperationalPanel(",
    "      opsNodesPanel,",
    "      opsNodesPanelTitle,",
    "      opsNodesPanelSummary,",
    "      opsNodesPanelActions,",
    "      opsNodesPanelDetails,",
    "      {",
    "        title: selectedLabel || 'Node Mesh',",
    "          summary: pickFirstText([",
    "            activity?.narrative?.operatorSummary,",
    "            selectedActivity?.narrative?.operatorSummary,",
    "            capabilities?.narrative?.operatorSummary,",
    "            selectedAction,",
    "          doctor?.summary,",
    "        ], 'No additional detail for the focused node.'),",
    "          actionsHtml: [",
    "            selectorRow,",
    "            buildOperationalInlineButtons(panelButtons),",
    "            nodePolicyActionRow,",
    "          ].filter(Boolean).join(''),",
    "          details: [",
    "            selected",
    "              - '<strong>Status:</strong> ' + escapeHtml(normalizeText(selected?.status || 'unknown')) + ' | <strong>Trust:</strong> ' + escapeHtml(normalizeText(selected?.trustLabel || 'no policy visible'))",
    "              : '<strong>Status:</strong> in the node on focus now.',",
    "            normalizeText(hostHints?.hostname || hostHints?.deviceModel || hostHints?.locationLabel)",
    "              - '<strong>Host:</strong> ' + escapeHtml(",
    "                [",
    "                  normalizeText(hostHints?.hostname || hostHints?.deviceModel || hostHints?.locationLabel),",
    "                  normalizeText(hostHints?.nodeVersion) ? 'node ' + normalizeText(hostHints.nodeVersion) : '',",
    "                  normalizeText(hostHints?.appVersion) ? 'app ' + normalizeText(hostHints.appVersion) : '',",
    "                ].filter(Boolean).join(' | '),",
    "              )",
    "              : '<strong>Host:</strong> without identidade detalhada in the snapshot current.',",
    "            declaredCount",
    "              - '<strong>Allowlist:</strong> ' + String(approvedCount) + '/' + String(declaredCount) + ' approved capability(s)(s) on this host.'",
    "              : '<strong>Allowlist:</strong> in the capability catalog declared now.',",
    "            approvedCount > 0",
    "              - '<strong>Approved now:</strong> ' + escapeHtml((selected?.approvedCapabilityIds || []).map((entry) => normalizeText(entry)).filter(Boolean).slice(0, 6).join(', ') || 'n/a')",
    "              : '<strong>Approved now:</strong> in the capability approved on this host.',",
    "            allowlistAudit",
    "              - '<strong>Latest policy:</strong> ' + escapeHtml([",
    "                normalizeText(allowlistAudit?.approvedBy) || 'operador in the provided',",
    "                normalizeText(allowlistAudit?.mode) || 'modo in the provided',",
    "                normalizeText(allowlistAudit?.approvedAt) || '',",
    "              ].filter(Boolean).join(' | '))",
    "              : '<strong>Latest policy:</strong> in the recent allowlist audit.',",
    "            normalizeText(allowlistAudit?.reason)",
    "              - '<strong>Motivo of the policy:</strong> ' + escapeHtml(normalizeText(allowlistAudit.reason))",
    "              : '<strong>Motivo of the policy:</strong> in the justification recorded for this allowlist.',",
    "            (activity?.summary || selectedActivity?.summary)",
    "              - '<strong>Fila:</strong> ' + String((activity?.summary?.pending ?? selectedActivity?.summary?.pending) || 0) + ' pending(s), '",
    "                + String((activity?.summary?.claimed ?? selectedActivity?.summary?.claimed) || 0) + ' claimed and '",
    "                + String((activity?.summary?.completedRecently ?? selectedActivity?.summary?.completedRecently) || 0) + ' completed(s) recentemente.'",
    "              : '<strong>Queue:</strong> without activity recente for the focused node.',",
    "          maintenance?.supported",
    "            - '<strong>Maintenance:</strong> ' + escapeHtml(",
    "              pickFirstText([",
    "                maintenance?.latestResultSummary,",
    "                maintenance?.latestAction ? maintenance.latestAction + ' at ' + normalizeText(maintenance.latestStatus || 'unknown state') : '',",
    "                maintenance?.recoverKind,",
    "              ], 'The node.maintenance capability is available for local repair.'),",
    "            )",
    "            : '<strong>Maintenance:</strong> node.maintenance is enabled on this host.',",
    "          bootstrapDraft?.bootstrap?.command",
    "            - '<strong>Pending bootstrap:</strong> ' + escapeHtml(",
    "              bootstrapDraft.bootstrap.packageScript",
    "                - bootstrapDraft.bootstrap.packageScript + ' | ' + normalizeText(bootstrapDraft.bootstrap.workspaceHint || '')",
    "                : normalizeText(bootstrapDraft.bootstrap.command),",
    "            )",
    "            : '<strong>Pending bootstrap:</strong> in the pending draft to copy on this host.',",
    "          ...((Array.isArray(capabilities?.capabilities) ? capabilities.capabilities : []).slice(0, 4).map((entry) =>",
    "            '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Capability')) + ':</strong> '",
    "            + escapeHtml(normalizeText(entry?.description || entry?.category || 'No additional detail.')),",
    "          )),",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsNodesPanel, opsNodesPanelActions, opsNodesPanelDetails);",
    "  }",
    "  setOperationalActionStatus(",
    "    opsNodesStatus,",
    "    operationalMeshExpanded.nodes",
    "      - 'Node Mesh Panel aberto with foco, activity, capabilities and doctor of the mesh current.'",
    "      : 'Open the Node Mesh panel to review foco, allowlist and hints operational without cair in the legado.',",
    "  );",
    "  showOperationalAction(",
    "    opsNodesAction,",
    "    operationalMeshExpanded.nodes ? 'Back to summary' : 'Open nodes panel',",
    "    operationalMeshExpanded.nodes ? 'collapse' : 'nodes-open',",
    "    selectedId,",
    "  );",
    "}",
    "",
    "function buildChannelPromotionHint(selected, installPlan = null) {",
    "  const channelId = normalizeText(selected?.id);",
    "  const currentMode = normalizeText(installPlan?.currentMode || '');",
    "  const recommendedMode = normalizeText(installPlan?.recommendedMode || '');",
    "  if (channelId && currentMode && recommendedMode && currentMode !== recommendedMode) {",
    "    return 'Official promotion: this host is in ' + currentMode + ' and the recommended mode is ' + recommendedMode + '. Use the panel to promote without leaving the shell.';",
    "  }",
    "  if (channelId === 'slack') {",
    "    return normalizeText(selected?.transport) === 'native'",
    "      - 'Slack is already in official mode. Use prepare/policy to review the rollout before expanding channels or DMs.'",
    "      : 'Official promotion: run npm run setup:channels to promote local mode to Slack native (socket/http) with tokens and webhook reais.';",
    "  }",
    "  if (channelId === 'whatsapp') {",
    "    return normalizeText(selected?.transport) === 'webhook'",
    "      - 'WhatsApp is already in official mode. Review allowed chats and callback before expanding the rollout.'",
    "      : 'Official promotion: run npm run setup:channels to migrate WhatsApp to Cloud API or close the supervised bootstrap of the chosen provider.';",
    "  }",
    "  if (channelId === 'telegram') {",
    "    return 'Telegram is usually the fastest channel to connect. Use the wizard to align token and allowed users.';",
    "  }",
].join('\n');
