import { asErrorLike } from '../../../../../utils/errorLike';
export const runtimeShellScriptPart6Seg2: string = [
    "          : '<strong>Instrucao principal:</strong> sem instrucao destacada para o foco atual.',",
    "        selectorRow",
    "          ? '<strong>Alternar foco:</strong> ' + selectorRow",
    "          : '<strong>Alternar foco:</strong> nenhum workspace registrado agora.',",
    "        commandItems.length > 0",
    "          ? '<strong>Comandos:</strong><br>' + commandItems.join('<br>')",
    "          : '<strong>Comandos:</strong> nenhum comando registrado neste workspace.',",
    "        hookItems.length > 0",
    "          ? '<strong>Hooks:</strong><br>' + hookItems.join('<br>')",
    "          : '<strong>Hooks:</strong> nenhum hook registrado neste workspace.',",
    "        pluginFocus",
    "          ? '<strong>Plugin foco:</strong> ' + escapeHtml(normalizeText(pluginFocus?.label || pluginFocus?.id || 'plugin')) + ' - '",
    "            + escapeHtml(normalizeText(pluginFocus?.summary || pluginFocus?.actionHint || 'Use as acoes inline para operar o plugin.'))",
    "          : '<strong>Plugin foco:</strong> nenhum plugin com action exposto agora.',",
    "        latestHookRun?.summary",
    "          ? '<strong>Ultimo dry-run:</strong> ' + escapeHtml(normalizeText(latestHookRun.summary))",
    "          : '<strong>Ultimo dry-run:</strong> ainda nao houve execucao operacional de hook nesta sessao do shell.',",
    "        normalizeText(extensions?.narrative?.operatorSummary)",
    "          ? '<strong>Catalogo:</strong> ' + escapeHtml(normalizeText(extensions.narrative.operatorSummary))",
    "          : '<strong>Catalogo:</strong> sem narrativa operacional agora.',",
    "      ]",
    "    : [",
    "        selectedLabel",
    "          ? '<strong>Selecionado:</strong> ' + escapeHtml(selectedLabel) + '.'",
    "          : '<strong>Instrucao visivel:</strong> ' + String(summary.withInstructions || 0) + ' workspace(s).',",
    "        selectedLead",
    "          ? '<strong>Entrada principal:</strong> ' + escapeHtml(selectedLead)",
    "          : '<strong>Catalogo:</strong> ' + escapeHtml(normalizeText(extensions?.narrative?.operatorSummary || 'Nenhuma instrucao principal visivel agora.')),",
    "      ];",
    "  renderList(opsExtensionsDetails, items);",
    "    if (operationalMeshExpanded.extensions) {",
    "      showOperationalPanel(",
    "        opsExtensionsPanel,",
    "        opsExtensionsPanelTitle,",
    "        opsExtensionsPanelSummary,",
    "        opsExtensionsPanelActions,",
    "      opsExtensionsPanelDetails,",
    "      {",
    "        title: selectedLabel || 'Catalogo de integrations',",
    "          summary: pickFirstText([",
    "            selectedLead,",
    "            extensions?.narrative?.operatorSummary,",
    "            plugins?.narrative?.operatorSummary,",
    "            hooks?.narrative?.operatorSummary,",
    "          ], 'Sem detalhe adicional para o workspace foco.'),",
    "          actionsHtml: [",
    "            selectorRow,",
    "            extensionActionRow,",
    "          ].filter(Boolean).join(''),",
    "          details: [",
    "            selected",
    "              ? '<strong>Workspace:</strong> ' + escapeHtml(selectedLabel)",
    "              : '<strong>Workspace:</strong> nenhum workspace em foco agora.',",
    "          '<strong>Extensoes:</strong> ' + String(selected?.commandCount || 0) + ' comando(s), ' + String(selected?.hookCount || 0) + ' hook(s).',",
    "          selected?.instructionFile",
    "            ? '<strong>Instrucao:</strong> ' + escapeHtml(normalizeText(selected.instructionFile))",
    "            : '<strong>Instrucao:</strong> nenhum ZAVORTH.md visivel neste foco.',",
    "            plugins?.summary",
    "              ? '<strong>Plugin plane:</strong> ' + String(plugins.summary.total || 0) + ' total, ' + String(plugins.summary.installed || 0) + ' instalado(s) e ' + String(plugins.summary.trusted || 0) + ' trusted.'",
    "              : '<strong>Plugin plane:</strong> indisponivel neste runtime.',",
    "            pluginFocus",
    "              ? '<strong>Plugin foco:</strong> ' + escapeHtml(normalizeText(pluginFocus?.label || pluginFocus?.id || 'plugin')) + ' - '",
    "                + escapeHtml(normalizeText(pluginFocus?.summary || pluginFocus?.actionHint || 'Acione as acoes inline para operar o plugin.'))",
    "              : '<strong>Plugin foco:</strong> nenhum plugin com acoes visiveis agora.',",
    "            pluginFocus && Array.isArray(pluginFocus?.actions) && pluginFocus.actions.length > 0",
    "              ? '<strong>Acoes do plugin:</strong> ' + escapeHtml(pluginFocus.actions.slice(0, 4).map((entry) => normalizeText(entry?.label || entry?.kind || entry?.id || 'acao')).filter(Boolean).join(', '))",
    "              : '<strong>Acoes do plugin:</strong> nenhum action exposto para o plugin foco.',",
    "            hooks?.summary",
    "              ? '<strong>Hook plane:</strong> ' + String(hooks.summary.registeredHooks || 0) + ' hook(s) registrados em ' + String(hooks.summary.workspaces || 0) + ' workspace(s).'",
    "              : '<strong>Hook plane:</strong> indisponivel neste runtime.',",
    "            latestHookRun?.summary",
    "              ? '<strong>Ultimo dry-run:</strong> ' + escapeHtml(normalizeText(latestHookRun.summary))",
    "              : '<strong>Ultimo dry-run:</strong> nenhum hook rodado operacionalmente nesta sessao.',",
    "            latestHookPipeline?.narrative?.operatorSummary",
    "              ? '<strong>Pipeline de hook:</strong> ' + escapeHtml(normalizeText(latestHookPipeline.narrative.operatorSummary))",
    "              : '<strong>Pipeline de hook:</strong> sem pipeline operacional capturado nesta sessao.',",
    "          ...commandItems,",
    "          ...hookItems,",
    "        ],",
    "      },",
    "    );",
    "  } else {",
    "    hideOperationalPanel(opsExtensionsPanel, opsExtensionsPanelActions, opsExtensionsPanelDetails);",
    "  }",
    "  setOperationalActionStatus(",
    "    opsExtensionsStatus,",
    "    operationalMeshExpanded.extensions",
    "      ? 'Catalogo expandido com foco, comandos e hooks do workspace selecionado.'",
    "      : 'Atualize o catalogo quando ZAVORTH.md, plugins, comandos ou hooks mudarem neste host.',",
    "  );",
    "  showOperationalAction(",
    "    opsExtensionsAction,",
    "    operationalMeshExpanded.extensions ? 'Voltar ao resumo' : 'Abrir painel das integrations',",
    "    operationalMeshExpanded.extensions ? 'collapse' : 'extensions-open',",
    "  );",
    "}",
    "",
    "function renderOperationalMeshSummary(channelMeshPayload, channelInstallPayload, channelDoctorPayload, channelAssistantPayload, nodeMeshPayload, nodeDoctorPayload, transportPayload, extensionPayload, pluginPayload, hookPayload) {",
    "  operationalMeshData = {",
    "    nodes: nodeMeshPayload || null,",
    "    nodeDoctor: nodeDoctorPayload || null,",
    "    nodeActivity: null,",
    "    nodeCapabilities: null,",
    "    nodeBootstrap: null,",
    "    channels: channelMeshPayload || null,",
    "    channelDetail: null,",
    "    channelAction: null,",
    "    channelInstall: channelInstallPayload || null,",
    "    channelDoctor: channelDoctorPayload || null,",
    "    channelAssistant: channelAssistantPayload || null,",
    "    transports: transportPayload || null,",
    "    transportHistory: null,",
    "    transportDoctor: null,",
    "    extensions: extensionPayload || null,",
    "    plugins: pluginPayload || null,",
    "    hooks: hookPayload || null,",
    "  };",
    "  renderNodesOperationalCard();",
    "  renderChannelsOperationalCard();",
    "  renderTransportsOperationalCard();",
    "  renderExtensionsOperationalCard();",
    "  renderOperatorCockpit();",
    "}",
    "",
    "function renderProtectedCardHierarchy(manifest, report) {",
    "  const plan = manifest?.recommendedPlan;",
    "  const action = normalizeText(plan?.primaryAction);",
    "",
    "  setCardEmphasis(manifestCard, 'subtle');",
    "  setCardEmphasis(journeyCard, 'subtle');",
    "  setCardEmphasis(remoteCard, 'subtle');",
    "",
    "  setText(",
    "    journeyCardNote,",
    "    action === 'go' || action === 'trust'",
    "      ? 'Este e o aprofundamento principal agora: feche setup, trust e prontidao local antes de seguir.'",
    "      : 'Use este caminho quando o runtime local ainda nao estiver pronto ou quando este host ainda precisar trust.',",
    "  );",
    "  setText(",
    "    remoteCardNote,",
    "    action === 'remote'",
    "      ? 'Este e o aprofundamento principal agora: feche o rollout remoto oficial antes de operar fora da maquina.'",
    "      : 'Use este caminho quando voce quiser operar fora desta maquina ou publicar o shell remoto oficial.',",
    "  );",
    "",
    "  if (action === 'go' || action === 'trust') {",
    "    setCardEmphasis(journeyCard, 'focus');",
    "    return;",
    "  }",
    "",
    "  if (action === 'remote') {",
    "    setCardEmphasis(remoteCard, 'focus');",
    "    return;",
    "  }",
    "}",
    "",
    "function hideJourneyActionButtons() {",
    "  if (journeyTrustActionButton instanceof HTMLButtonElement) {",
    "    journeyTrustActionButton.hidden = true;",
    "    journeyTrustActionButton.dataset.mode = '';",
    "    journeyTrustActionButton.dataset.action = '';",
    "  }",
    "  if (journeyRefreshActionButton instanceof HTMLButtonElement) {",
    "    journeyRefreshActionButton.hidden = true;",
    "  }",
    "}",
    "",
    "function detectJourneyActionFromCommand(command) {",
    "  const normalized = normalizeText(command).toLowerCase();",
    "  if (!normalized) {",
    "    return '';",
    "  }",
    "  if (normalized.includes('ops:go')) {",
    "    return 'go';",
    "  }",
    "  if (normalized.includes('ops:install') || normalized.includes('ops:bootstrap')) {",
    "    return 'install';",
    "  }",
    "  if (normalized.includes('ops:start') || normalized.includes('ops:up')) {",
    "    return 'start';",
    "  }",
    "  if (normalized.includes('ops:ready')) {",
    "    return 'ready';",
    "  }",
    "  return '';",
    "}",
    "",
    "function buildJourneyPrimaryAction(manifest, journeyReport) {",
    "  if (!manifest) {",
    "    return null;",
    "  }",
    "",
    "  const hostAuthorized = manifest?.auth?.authorizedHost;",
    "  const localReady = manifest?.local?.ready === true;",
    "  if (hostAuthorized === false) {",
    "    return {",
    "      mode: 'trust',",
    "      action: '',",
    "      label: 'Autorizar este host',",
    "      status: 'Este host ainda precisa trust antes de acoes mutaveis.',",
    "    };",
    "  }",
    "",
    "  const phases = Array.isArray(journeyReport?.phases) ? journeyReport.phases : [];",
    "  const nextStepPhase = phases.find((phase) => normalizeText(phase?.id) === 'next-step' && String(phase?.status || '').trim().toLowerCase() !== 'ready');",
    "  const actionablePhase = phases.find((phase) => {",
    "    const status = String(phase?.status || '').trim().toLowerCase();",
    "    return status === 'action' || status === 'failed';",
    "  });",
    "  const phase = nextStepPhase || actionablePhase || null;",
    "  const detectedAction = detectJourneyActionFromCommand(phase?.command);",
    "  const fallbackAction = localReady ? 'ready' : 'go';",
    "  const action = detectedAction || fallbackAction;",
    "",
    "  if (action === 'install') {",
    "    return {",
    "      mode: 'journey',",
    "      action,",
    "      label: 'Corrigir bootstrap local',",
    "      status: normalizeText(phase?.summary) || 'Use este passo para corrigir o bootstrap seguro deste host.',",
    "    };",
    "  }",
    "",
    "  if (action === 'start') {",
    "    return {",
    "      mode: 'journey',",
    "      action,",
    "      label: 'Subir runtime local',",
    "      status: normalizeText(phase?.summary) || 'Use este passo para subir o runtime supervisionado e validar o shell local.',",
    "    };",
    "  }",
    "",
    "  if (action === 'ready') {",
    "    return {",
    "      mode: 'journey',",
    "      action,",
    "      label: localReady ? 'Revalidar prontidao oficial' : 'Revisar prontidao oficial',",
    "      status: normalizeText(phase?.summary) || (localReady",
    "        ? 'Host local pronto. Rode a checagem oficial para revisar readiness e trust.'",
    "        : 'Use este passo para revisar a prontidao local e o estado do host oficial.'),",
    "    };",
    "  }",
    "",
    "  return {",
    "    mode: 'journey',",
    "    action: 'go',",
    "    label: 'Executar atalho oficial',",
    "    status: normalizeText(phase?.summary) || 'Use este atalho para fechar setup, subida do runtime e shell oficial deste host.',",
    "  };",
    "}",
    "",
    "function renderJourneyActionControls(manifest, journeyReport) {",
    "  hideJourneyActionButtons();",
    "  if (!manifest) {",
    "    setJourneyActionStatus('Valide o token para usar as acoes do host oficial.');",
    "    return;",
    "  }",
    "",
    "  const primaryAction = buildJourneyPrimaryAction(manifest, journeyReport);",
    "  const localReady = manifest?.local?.ready === true;",
    "",
    "  if (journeyTrustActionButton instanceof HTMLButtonElement && primaryAction) {",
    "    journeyTrustActionButton.hidden = false;",
    "    journeyTrustActionButton.textContent = primaryAction.label;",
    "    journeyTrustActionButton.dataset.mode = primaryAction.mode;",
    "    journeyTrustActionButton.dataset.action = primaryAction.action || '';",
    "  }",
    "",
    "  if (journeyRefreshActionButton instanceof HTMLButtonElement) {",
    "    journeyRefreshActionButton.hidden = false;",
    "    journeyRefreshActionButton.textContent = localReady ? 'Revalidar host' : 'Atualizar host';",
    "  }",
    "",
    "  setJourneyActionStatus(primaryAction?.status || (localReady",
    "    ? 'Host local pronto. Use este card so para revisar readiness e trust.'",
    "    : 'Use este card para revisar a prontidao local e atualizar o estado do host.'));",
    "}",
    "",
    "function hideRemoteActionButtons() {",
    "  if (remoteRecommendedActionButton instanceof HTMLButtonElement) {",
    "    remoteRecommendedActionButton.hidden = true;",
    "    remoteRecommendedActionButton.dataset.action = '';",
    "    remoteRecommendedActionButton.dataset.provider = '';",
    "  }",
    "  if (remoteVerifyActionButton instanceof HTMLButtonElement) {",
    "    remoteVerifyActionButton.hidden = true;",
    "    remoteVerifyActionButton.dataset.action = '';",
    "  }",
    "}",
    "",
    "function renderRemoteActionControls(report) {",
    "  hideRemoteActionButtons();",
    "  if (!report?.actions) {",
    "    setRemoteActionStatus('Valide o token para usar a acao guiada do remoto oficial.');",
    "    return;",
    "  }",
    "",
    "  const recommendedAction = normalizeText(report.actions.recommendedAction);",
    "  const recommendedProvider = normalizeText(report.actions.recommendedProvider);",
    "  const recommendedConfig = recommendedAction ? report.actions[recommendedAction] : null;",
    "",
    "  if (remoteRecommendedActionButton instanceof HTMLButtonElement && recommendedAction && recommendedConfig) {",
    "    remoteRecommendedActionButton.hidden = false;",
    "    remoteRecommendedActionButton.textContent = normalizeText(recommendedConfig.label) || 'Executar proximo passo remoto';",
    "    remoteRecommendedActionButton.dataset.action = recommendedAction;",
    "    remoteRecommendedActionButton.dataset.provider = recommendedProvider;",
    "  }",
    "",
    "  if (remoteVerifyActionButton instanceof HTMLButtonElement && report.actions.canVerify) {",
    "    remoteVerifyActionButton.hidden = false;",
    "    remoteVerifyActionButton.textContent = normalizeText(report.actions.verify?.label) || 'Verificar remoto';",
    "    remoteVerifyActionButton.dataset.action = 'verify';",
    "    remoteVerifyActionButton.dataset.provider = recommendedProvider;",
    "  }",
    "}",
    "",
    "async function runOfficialRemoteAction(action, provider) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setRemoteActionStatus('Valide o token antes de acionar o remoto oficial.');",
    "    return;",
    "  }",
    "",
    "  const buttons = [remoteRecommendedActionButton, remoteVerifyActionButton].filter((target) => target instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    setRemoteActionStatus('Executando acao remota oficial...');",
    "    const response = await fetch('/api/web/host/official-remote-access/actions', {",
    "      method: 'POST',",
    "      headers: {",
    "        Accept: 'application/json',",
    "        'Content-Type': 'application/json',",
    "        'X-Zavorth-Token': token,",
    "      },",
    "      body: JSON.stringify({",
    "        action,",
    "        provider: provider || undefined,",
    "      }),",
    "    });",
    "    const payload = await response.json().catch(() => null);",
    "    if (!response.ok || !payload?.ok) {",
    "      throw new Error(payload?.error || 'Falha ao executar a acao remota oficial.');",
    "    }",
    "",
    "    await refreshProtectedShellState(token, {",
    "      manifest: payload.manifest,",
    "      officialRemoteAccess: payload.report,",
    "    });",
    "    setRemoteActionStatus(normalizeText(payload?.report?.summary) || 'Acao remota concluida.');",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setRemoteActionStatus(error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function fetchSessionWorkspacePayload(token, requestedSessionId = '') {",
    "  const query = normalizeText(requestedSessionId)",
    "    ? '?sessionId=' + encodeURIComponent(normalizeText(requestedSessionId))",
    "    : '';",
    "  const sessionPayload = await fetchProtectedJsonOptional('/api/web/session' + query, token, { timeoutMs: 8000 });",
    "  const sessionId = normalizeText(sessionPayload?.sessionId) || normalizeText(requestedSessionId);",
    "  if (!sessionId) {",
    "    return {",
    "      session: sessionPayload,",
    "      state: null,",
    "      history: null,",
    "      toolRuns: null,",
    "    };",
    "  }",
    "",
    "  const sessionQuery = '?sessionId=' + encodeURIComponent(sessionId);",
    "  const [statePayload, historyPayload, toolRunsPayload] = await Promise.all([",
    "    fetchProtectedJsonOptional('/api/web/gateway/sessions' + sessionQuery, token),",
    "    fetchProtectedJsonOptional('/api/web/gateway/sessions/history' + sessionQuery, token),",
    "    fetchProtectedJsonOptional('/api/web/tool-runs' + sessionQuery, token),",
    "  ]);",
    "",
    "  return {",
    "    session: sessionPayload,",
    "    state: statePayload,",
    "    history: historyPayload,",
    "    toolRuns: toolRunsPayload,",
    "  };",
    "}",
    "",
    "async function refreshProtectedShellState(token, seed = {}) {",
    "  const manifestPayloadPromise = seed.manifest",
    "    ? Promise.resolve({ manifest: seed.manifest })",
    "    : fetchProtectedJsonOptional('/api/web/host/access-manifest', token, { timeoutMs: 7000 });",
    "  const journeyPayloadPromise = seed.installJourney",
    "    ? Promise.resolve({ report: seed.installJourney })",
    "    : fetchProtectedJsonOptional('/api/web/host/install-journey', token, { timeoutMs: 7000 });",
    "  const remotePayloadPromise = seed.officialRemoteAccess",
    "    ? Promise.resolve({ report: seed.officialRemoteAccess })",
    "    : fetchProtectedJsonOptional('/api/web/host/official-remote-access', token, { timeoutMs: 7000 });",
    "  const channelMeshPayloadPromise = fetchProtectedJsonOptional('/api/web/channels', token);",
    "  const channelInstallPayloadPromise = fetchProtectedJsonOptional('/api/web/channels/install', token);",
    "  const channelDoctorPayloadPromise = fetchProtectedJsonOptional('/api/web/channels/doctor', token, { method: 'POST' });",
    "  const channelAssistantPayloadPromise = fetchProtectedJsonOptional('/api/web/channels/setup-assistant', token);",
    "  const nodeMeshPayloadPromise = fetchProtectedJsonOptional('/api/web/nodes', token);",
    "  const nodeDoctorPayloadPromise = fetchProtectedJsonOptional('/api/web/nodes/doctor', token);",
    "  const transportPayloadPromise = fetchProtectedJsonOptional('/api/web/transports', token);",
    "  const extensionPayloadPromise = fetchProtectedJsonOptional('/api/web/workspace/extensions', token);",
    "  const pluginPayloadPromise = fetchProtectedJsonOptional('/api/web/plugins', token);",
    "  const hookPayloadPromise = fetchProtectedJsonOptional('/api/web/hooks', token);",
    "  const sessionWorkspacePayloadPromise = fetchSessionWorkspacePayload(token, readSessionWorkspaceSessionId());",
    "  const learningPayloadPromise = fetchProtectedJsonOptional('/api/web/learning', token);",
    "  const memoryProceduresPayloadPromise = fetchProtectedJsonOptional('/api/web/memory/procedures', token);",
    "  const evalControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/evals', token);",
    "  const qaControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/qa', token);",
    "  const governanceControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/governance', token);",
    "  const replayLearningControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/replay-learning', token);",
    "  const ecosystemControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/ecosystem', token);",
    "  const distributedRuntimeControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/distributed-runtime', token);",
    "  const runtimeStabilityControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/runtime-stability', token);",
    "  const rolloutReadinessControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/rollout-readiness', token);",
    "  const automationControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/operations/automations?limit=8', token);",
    "  const hubControlPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/hub', token);",
    "  const trustPlanePayloadPromise = fetchProtectedJsonOptional('/api/web/trust-plane', token);",
    "  const watchModePayloadPromise = fetchProtectedJsonOptional('/api/web/watch-mode?limit=8', token);",
    "  const systemOverlordPayloadPromise = fetchProtectedJsonOptional('/api/web/system-overlord?limit=20', token);",
    "",
    "  const [",
    "    manifestPayload,",
    "    journeyPayload,",
    "    remotePayload,",
    "    channelMeshPayload,",
    "    channelInstallPayload,",
    "    channelDoctorPayload,",
    "    channelAssistantPayload,",
    "    nodeMeshPayload,",
    "    nodeDoctorPayload,",
    "    transportPayload,",
    "    extensionPayload,",
    "    pluginPayload,",
    "    hookPayload,",
    "    sessionWorkspacePayload,",
    "    learningPayload,",
    "    memoryProceduresPayload,",
    "    evalControlPlanePayload,",
    "    qaControlPlanePayload,",
    "    governanceControlPlanePayload,",
    "    replayLearningControlPlanePayload,",
    "    ecosystemControlPlanePayload,",
    "    distributedRuntimeControlPlanePayload,",
    "    runtimeStabilityControlPlanePayload,",
    "    rolloutReadinessControlPlanePayload,",
    "    automationControlPlanePayload,",
    "    hubControlPlanePayload,",
    "    trustPlanePayload,",
    "    watchModePayload,",
    "    systemOverlordPayload,",
    "  ] = await Promise.all([",
    "    manifestPayloadPromise,",
    "    journeyPayloadPromise,",
    "    remotePayloadPromise,",
    "    channelMeshPayloadPromise,",
    "    channelInstallPayloadPromise,",
    "    channelDoctorPayloadPromise,",
    "    channelAssistantPayloadPromise,",
    "    nodeMeshPayloadPromise,",
    "    nodeDoctorPayloadPromise,",
    "    transportPayloadPromise,",
    "    extensionPayloadPromise,",
    "    pluginPayloadPromise,",
    "    hookPayloadPromise,",
    "    sessionWorkspacePayloadPromise,",
    "    learningPayloadPromise,",
    "    memoryProceduresPayloadPromise,",
    "    evalControlPlanePayloadPromise,",
    "    qaControlPlanePayloadPromise,",
    "    governanceControlPlanePayloadPromise,",
    "    replayLearningControlPlanePayloadPromise,",
    "    ecosystemControlPlanePayloadPromise,",
    "    distributedRuntimeControlPlanePayloadPromise,",
    "    runtimeStabilityControlPlanePayloadPromise,",
    "    rolloutReadinessControlPlanePayloadPromise,",
    "    automationControlPlanePayloadPromise,",
    "    hubControlPlanePayloadPromise,",
    "    trustPlanePayloadPromise,",
    "    watchModePayloadPromise,",
    "    systemOverlordPayloadPromise,",
    "  ]);",
    "",
    "  renderPriorityState(manifestPayload, journeyPayload, remotePayload);",
    "  renderManifest(manifestPayload);",
    "  renderJourney(journeyPayload);",
    "  renderRemoteAccess(remotePayload);",
    "  renderJourneyActionControls(manifestPayload?.manifest, journeyPayload?.report);",
    "  renderRemoteActionControls(remotePayload?.report);",
    "  renderOperationalMeshSummary(",
    "    channelMeshPayload,",
    "    channelInstallPayload,",
    "    channelDoctorPayload,",
    "    channelAssistantPayload,",
    "    nodeMeshPayload,",
    "    nodeDoctorPayload,",
    "    transportPayload,",
    "    extensionPayload,",
    "    pluginPayload,",
    "    hookPayload,",
    "  );",
    "  renderSessionWorkspace(sessionWorkspacePayload);",
    "  renderLearningMemory(sessionWorkspacePayload?.state, learningPayload, memoryProceduresPayload);",
    "  protectedShellUnlocked = true;",
    "  renderEvalControlPlanePanel(evalControlPlanePayload);",
    "  renderQaControlPlanePanel(qaControlPlanePayload);",
    "  renderGovernanceControlPlanePanel(governanceControlPlanePayload);",
    "  renderReplayLearningControlPlanePanel(replayLearningControlPlanePayload);",
    "  renderEcosystemControlPlanePanel(ecosystemControlPlanePayload);",
    "  renderDistributedRuntimeControlPlanePanel(distributedRuntimeControlPlanePayload);",
    "  renderRuntimeStabilityControlPlanePanel(runtimeStabilityControlPlanePayload);",
    "  renderRolloutReadinessControlPlanePanel(rolloutReadinessControlPlanePayload);",
    "  renderAutomationControlPlanePanel(automationControlPlanePayload);",
    "  renderHubControlPlanePanel(hubControlPlanePayload);",
    "  renderTrustPlanePanel(trustPlanePayload);",
    "  renderWatchModePanel(watchModePayload);",
    "  renderSystemOverlordPanel(systemOverlordPayload);",
    "  renderOperatorCockpit();",
    "  ensureGatewayControlSocket(token, readSessionWorkspaceSessionId());",
    "}",
    "",
    "async function runJourneyTrustAction() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setJourneyActionStatus('Valide o token antes de acionar o host oficial.');",
    "    return;",
    "  }",
    "",
    "  const buttons = [journeyTrustActionButton, journeyRefreshActionButton].filter((target) => target instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    const mode = normalizeText(journeyTrustActionButton?.dataset.mode) || 'trust';",
    "    if (mode === 'journey') {",
    "      const action = normalizeText(journeyTrustActionButton?.dataset.action) || 'ready';",
    "      setJourneyActionStatus('Executando jornada local do host...');",
    "      const response = await fetch('/api/web/host/install-journey/actions', {",
    "        method: 'POST',",
    "        headers: {",
    "          Accept: 'application/json',",
    "          'Content-Type': 'application/json',",
    "          'X-Zavorth-Token': token,",
    "        },",
    "        body: JSON.stringify({ action }),",
    "      });",
    "      const payload = await response.json().catch(() => null);",
    "      if (!response.ok || !payload?.ok) {",
    "        throw new Error(payload?.error || 'Falha ao executar a jornada local do host.');",
    "      }",
    "",
    "      await refreshProtectedShellState(token, {",
    "        manifest: payload.manifest,",
    "        installJourney: payload.installJourney,",
    "        officialRemoteAccess: payload.officialRemoteAccess,",
    "      });",
    "      setJourneyActionStatus(normalizeText(payload?.report?.summary) || 'Jornada local atualizada.');",
    "      return;",
    "    }",
    "",
    "    setJourneyActionStatus('Autorizando host e atualizando readiness...');",
    "    const response = await fetch('/api/web/host/trust', {",
    "      method: 'POST',",
    "      headers: {",
    "        Accept: 'application/json',",
    "        'X-Zavorth-Token': token,",
    "      },",
    "    });",
    "    const payload = await response.json().catch(() => null);",
    "    if (!response.ok || !payload?.ok) {",
    "      throw new Error(payload?.error || 'Falha ao autorizar este host.');",
    "    }",
    "",
    "    await refreshProtectedShellState(token, {",
    "      manifest: payload.manifest,",
    "      installJourney: payload.installJourney,",
    "      officialRemoteAccess: payload.officialRemoteAccess,",
    "    });",
    "    setJourneyActionStatus('Host autorizado e estado local atualizado.');",
    "  } catch (error: unknown) { const err = asErrorLike(error); const e = err;",
    "    setJourneyActionStatus(error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshJourneyState() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setJourneyActionStatus('Valide o token antes de atualizar o host.');",
].join('\n');
