export const runtimeShellScriptPart3Seg1: string = [
    "  );",
    "  setText(",
    "    sessionWorkspaceSelfmodSummary,",
    "    Array.isArray(selfmodPlane?.recentPlans) && selfmodPlane.recentPlans.length > 0",
    "      - 'Recent self-modification preview, apply, and rollback are visible in this session.'",
    "      : 'No selfmod preview or rollback associated with this session right now.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceResourcesState,",
    "    resourcePlane?.host",
    "      - escapeHtml(normalizeText(resourcePlane.host.pressure || 'unknown'))",
    "      : 'No reading',",
    "  );",
    "  setText(",
    "    sessionWorkspaceResourcesSummary,",
    "    resourcePlane?.host",
    "      - formatSessionWorkspaceMb(resourcePlane.host.usedPhysicalMemoryMb) + '/' + formatSessionWorkspaceMb(resourcePlane.host.totalVisibleMemoryMb)",
    "        + ' MB | top consumers and safe actions appear below.'",
    "      : 'Desktop Resource Plane unavailable on this host now.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceCompanionsState,",
    "    Array.isArray(companionPlane?.companions) && companionPlane.companions.length > 0",
    "      - String(companionPlane.companions.filter((entry) => normalizeText(entry?.status) === 'running').length) + ' active(s)'",
    "      : 'No reading',",
    "  );",
    "  setText(",
    "    sessionWorkspaceCompanionsSummary,",
    "    Array.isArray(companionPlane?.companions) && companionPlane.companions.length > 0",
    "      - String(companionPlane.companions.length) + ' companion(s) observados with status and supervised actions.'",
    "      : 'Companion Control Plane unavailable on this host now.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceHealthState,",
    "    runtimeWarnings.length > 0 ? String(runtimeWarnings.length) + ' warning(s)' : 'Stable',",
    "  );",
    "  setText(",
    "    sessionWorkspaceHealthSummary,",
    "    runtimeWarnings.length > 0",
    "      - 'Canonical warnings and prioritized next actions appear below.'",
    "      : actionRecommendations.length > 0",
    "        - 'No strong warnings; safe actions are still recommended for this host.'",
    "        : 'Runtime without warnings relevantes in this session now.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceStatus,",
    "    continuityReason",
    "      || handoffHeadline",
    "      || 'Refresh this workspace to review the active session, approvals, and replay without opening the legacy panel.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceSummary,",
    "    'chat ' + chatId + ' | ' + counts.taskCount + ' task(s) | ' + counts.toolRuns + ' tool run(s) | ' + counts.pendingPermissions + ' approval(s) at aberto | ' + runtimeWarnings.length + ' warning(s) | ' + counts.linkedSurfaces + ' surface(s) ligada(s).',",
    "  );",
    "",
    "  const items = [",
    "      '<strong>Session:</strong> ' + sessionId + ' | ' + chatId + '.',",
    "    formatWorkspaceCount('Tarefas', counts.taskCount),",
    "    formatWorkspaceCount('Approvals', counts.pendingPermissions),",
    "    formatWorkspaceCount('Workflows', counts.workflowRuns),",
    "    formatWorkspaceCount('Tool runs', counts.toolRuns),",
    "    formatWorkspaceCount('Files tocados', counts.filesTouched),",
    "    formatWorkspaceCount('Visible sessions', counts.sessionsTotal),",
    "    formatWorkspaceCount('surfaces ligadas', counts.linkedSurfaces),",
    "  ];",
    "",
    "  if (focusTask) {",
    "    items.push('<strong>Foco current:</strong> ' + escapeHtml(focusTask?.summary || focusTask?.shortId || focusTask?.taskId || 'Task dominante.'));",
    "  }",
    "  if (continuityReason) {",
    "    items.push('<strong>Continuidade:</strong> ' + escapeHtml(continuityReason));",
    "  }",
    "  if (sessionOptions.length > 1) {",
    "    items.push('<strong>Recent sessions:</strong> choose a session to rehydrate without reloading the page.');",
    "    items.push(buildOperationalSelectorHtml('session-workspace', sessionOptions, sessionId));",
    "  }",
    "  items.push(",
    "    tools.length > 0",
    "      - '<strong>Session tools:</strong> ' + escapeHtml(formatSessionToolList(tools)) + '.'",
    "      : '<strong>Session tools:</strong> the gateway resolves sessions, history, send, and spawn through this plane.',",
    "  );",
    "  if (historyPayload?.sessionPlane?.narrative?.operatorSummary) {",
    "    items.push('<strong>Resumo of the operador:</strong> ' + escapeHtml(historyPayload.sessionPlane.narrative.operatorSummary));",
    "  }",
    "",
    "  renderList(sessionWorkspaceDetails, items);",
    "  renderList(",
    "    sessionWorkspaceApprovals,",
    "    approvalItems.items.length > 0 ? approvalItems.items : ['No permission or task gate pending in this session.'],",
    "  );",
    "  const replayItems = buildSessionWorkspaceReplayItems(replay, handoff, continuity);",
    "  renderList(",
    "    sessionWorkspaceReplay,",
    "    replayItems.length > 0 ? replayItems : ['No relevant replay or handoff to show now.'],",
    "  );",
    "  renderList(",
    "    sessionWorkspaceTools,",
    "    buildSessionWorkspaceToolItems(toolRuns),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceDiffs,",
    "    buildSessionWorkspaceDiffItems(toolRuns),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceCapabilities,",
    "    buildSessionWorkspaceCapabilityItems(capabilityPlane),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceSelfmod,",
    "    buildSessionWorkspaceSelfmodItems(selfmodPlane),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceResources,",
    "    buildSessionWorkspaceResourceItems(resourcePlane, actionRecommendations),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceCompanions,",
    "    buildSessionWorkspaceCompanionItems(companionPlane),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceHealth,",
    "    buildSessionWorkspaceHealthItems(runtimeWarnings, actionRecommendations),",
    "  );",
    "  if (sessionWorkspaceAction instanceof HTMLButtonElement) {",
    "    sessionWorkspaceAction.hidden = false;",
    "    sessionWorkspaceAction.textContent = 'Atualizar workspace';",
    "  }",
    "}",
    "",
    "function renderOperatorCockpit() {",
    "  const runtimeLabel = normalizeText(runtimeStatus?.textContent || publicShellSnapshot.gatewayLabel || 'Checking');",
    "  const keepaliveLabel = normalizeText(opsKeepaliveState?.textContent || '');",
    "  const channelSummary = operationalMeshData.channels?.channels?.summary || null;",
    "  const nodeSummary = operationalMeshData.nodes?.nodeMesh?.summary || null;",
    "  const transportSummary = operationalMeshData.transports?.transports?.summary || null;",
    "  const extensionSummary = operationalMeshData.extensions?.workspaceExtensions?.summary || null;",
    "  const pluginSummary = operationalMeshData.plugins?.plugins?.summary || null;",
    "  const hookSummary = operationalMeshData.hooks?.hooks?.summary || null;",
    "  const sessionId = readSessionWorkspaceSessionId();",
    "  const sessionPlaneSummary = sessionWorkspaceData.state?.sessionPlane?.summary",
    "    || sessionWorkspaceData.history?.sessionPlane?.summary",
    "    || null;",
    "  const resourcePlane = sessionWorkspaceData.state?.resourcePlane || sessionWorkspaceData.history?.resourcePlane || null;",
    "  const companionPlane = sessionWorkspaceData.state?.companionPlane || sessionWorkspaceData.history?.companionPlane || null;",
    "  const runtimeWarnings = Array.isArray(sessionWorkspaceData.state?.runtimeWarnings)",
    "    - sessionWorkspaceData.state.runtimeWarnings",
    "    : Array.isArray(sessionWorkspaceData.history?.runtimeWarnings)",
    "      - sessionWorkspaceData.history.runtimeWarnings",
    "      : [];",
    "  const actionRecommendations = Array.isArray(sessionWorkspaceData.state?.actionRecommendations)",
    "    - sessionWorkspaceData.state.actionRecommendations",
    "    : Array.isArray(sessionWorkspaceData.history?.actionRecommendations)",
    "      - sessionWorkspaceData.history.actionRecommendations",
    "      : [];",
    "  const sessionCounts = readSessionWorkspaceCounts(sessionWorkspaceData.state, sessionWorkspaceData.history);",
    "  const approvalItems = buildSessionWorkspaceApprovalItems(",
    "    Array.isArray(sessionWorkspaceData.history?.session?.permissions) ? sessionWorkspaceData.history.session.permissions : [],",
    "    Array.isArray(sessionWorkspaceData.history?.session?.tasks) ? sessionWorkspaceData.history.session.tasks : [],",
    "  );",
    "  const historyItems = Number(sessionPlaneSummary?.historyItems || 0) || 0;",
    "  const sessionsSendReady = Boolean(sessionPlaneSummary?.sendReady);",
    "  const sessionsSpawnReady = Boolean(sessionPlaneSummary?.spawnReady);",
    "  const workspaceCount = Number(extensionSummary?.workspaces || 0) || 0;",
    "  const pluginCount = Number(pluginSummary?.total || 0) || 0;",
    "  const hookCount = Number(hookSummary?.registeredHooks || 0) || 0;",
    "",
    "  setText(",
    "    cockpitRuntimeState,",
    "    keepaliveLabel === 'Atencao' || keepaliveLabel === 'Stale'",
    "      - keepaliveLabel",
    "      : runtimeLabel,",
    "  );",
    "  setText(",
    "    cockpitRuntimeSummary,",
    "    channelSummary",
    "      - 'Gateway ' + publicShellSnapshot.gatewayLabel",
    "        + ' | dominios ' + publicShellSnapshot.initializedDomains",
    "        + ' | channels ' + String(channelSummary.ready || 0) + '/' + String(channelSummary.total || 0)",
    "        + ' | keepalive ' + (keepaliveLabel || 'n/d')",
    "      : 'Gateway ' + publicShellSnapshot.gatewayLabel",
    "        + ' | dominios ' + publicShellSnapshot.initializedDomains",
    "        + ' | nodes ' + publicShellSnapshot.nodeCount",
    "        + ' | transports ' + publicShellSnapshot.transportCount,",
    "  );",
    "",
    "  if (!protectedShellUnlocked || !sessionId) {",
    "    setText(cockpitSessionsState, protectedShellUnlocked ? 'without active session' : 'Validate the token');",
    "    setText(",
    "      cockpitSessionsSummary,",
    "      protectedShellUnlocked",
    "        - 'O host is liberado, but not yet existe umthe active session resolvida para mostrar aqui.'",
    "        : 'The active session, history, and cross-send appear here when the protected shell is unlocked.',",
    "    );",
    "    setText(cockpitApprovalsState, protectedShellUnlocked ? 'without active session' : 'Validate the token');",
    "    setText(",
    "      cockpitApprovalsSummary,",
    "      protectedShellUnlocked",
    "        - 'A queue de approvals depende de umthe active session resolvida on this host.'",
    "        : 'The approval queue for this session appears here when the protected shell is released.',",
    "    );",
    "    setText(cockpitResourcesState, protectedShellUnlocked ? 'No reading' : 'Validate the token');",
    "    setText(",
    "      cockpitResourcesSummary,",
    "      protectedShellUnlocked",
    "        - 'O Desktop Resource Plane not yet respondeu para this host.'",
    "        : 'Memory, host pressure, and top consumers appear here when the protected shell is released.',",
    "    );",
    "    setText(cockpitCompanionsState, protectedShellUnlocked ? 'No reading' : 'Validate the token');",
    "    setText(",
    "      cockpitCompanionsSummary,",
    "      protectedShellUnlocked",
    "        - 'O Companion Control Plane not yet respondeu para this host.'",
    "        : 'WSL, Docker Desktop, ZavorthBridge, and Codex appear here when the protected shell is released.',",
    "    );",
    "    setText(cockpitHealthState, protectedShellUnlocked ? 'No reading' : 'Validate the token');",
    "    setText(",
    "      cockpitHealthSummary,",
    "      protectedShellUnlocked",
    "        - 'Warnings and recommendations appear here when the active session is resolved.'",
    "        : 'Runtime warnings and next actions appear here when the protected shell is released.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitSessionsState,",
    "      sessionCounts.sessionsTotal > 1",
    "        - String(sessionCounts.sessionsTotal) + ' visible'",
    "        : '1 ativa',",
    "    );",
    "    setText(",
    "      cockpitSessionsSummary,",
    "      String(sessionCounts.taskCount) + ' task(s) | history ' + String(historyItems)",
    "      + ' | enviar ' + (sessionsSendReady ? 'ready' : 'parcial')",
    "      + ' | spawn ' + (sessionsSpawnReady ? 'ready' : 'parcial'),",
    "    );",
    "    setText(",
    "      cockpitApprovalsState,",
    "      approvalItems.total > 0 ? String(approvalItems.total) + ' pending(s)' : 'without pending items',",
    "    );",
    "    setText(",
    "      cockpitApprovalsSummary,",
    "      approvalItems.total > 0",
    "        - String(approvalItems.permissions) + ' permission(s) and ' + String(approvalItems.tasks) + ' open task gate(s).'",
    "        : 'No permission or task gate pending in the active session right now.',",
    "    );",
    "    setText(",
    "      cockpitResourcesState,",
    "      resourcePlane?.host ? String(resourcePlane.host.pressure || 'unknown') : 'No reading',",
    "    );",
    "    setText(",
    "      cockpitResourcesSummary,",
    "      resourcePlane?.host",
    "        - formatSessionWorkspaceMb(resourcePlane.host.usedPhysicalMemoryMb) + '/' + formatSessionWorkspaceMb(resourcePlane.host.totalVisibleMemoryMb)",
    "          + ' MB | ' + String((Array.isArray(resourcePlane.topConsumers) ? resourcePlane.topConsumers.length : 0)) + ' top consumer(s).'",
    "        : 'Desktop Resource Plane unavailable on this host now.',",
    "    );",
    "    setText(",
    "      cockpitCompanionsState,",
    "      Array.isArray(companionPlane?.companions)",
    "        - String(companionPlane.companions.filter((entry) => normalizeText(entry?.status) === 'running').length) + ' active(s)'",
    "        : 'No reading',",
    "    );",
    "    setText(",
    "      cockpitCompanionsSummary,",
    "      Array.isArray(companionPlane?.companions) && companionPlane.companions.length > 0",
    "        - String(companionPlane.companions.length) + ' companion(s) | '",
    "          + String(companionPlane.companions.filter((entry) => entry?.pressure === 'high' || entry?.pressure === 'critical').length)",
    "          + ' sob pressure.'",
    "        : 'No relevant companion appeared on this host now.',",
    "    );",
    "    setText(",
    "      cockpitHealthState,",
    "      runtimeWarnings.length > 0 ? String(runtimeWarnings.length) + ' warning(s)' : 'Stable',",
    "    );",
    "    setText(",
    "      cockpitHealthSummary,",
    "      runtimeWarnings.length > 0",
    "        - runtimeWarnings.slice(0, 2).join(' | ')",
    "        : actionRecommendations.length > 0",
    "          - actionRecommendations.slice(0, 2).map((entry) => normalizeText(entry?.label || entry?.summary)).filter(Boolean).join(' | ')",
    "          : 'no relevant warnings; cockpit ready to operate.',",
    "    );",
    "  }",
    "",
    "  if (!protectedShellUnlocked || !nodeSummary) {",
    "    setText(cockpitNodesState, protectedShellUnlocked ? 'No nodes' : 'Validate the token');",
    "    setText(",
    "      cockpitNodesSummary,",
    "      protectedShellUnlocked",
    "        - 'No protected Node Mesh is available to summarize on this host now.'",
    "        : 'The Node Mesh fleet, pairing, and queue summary appears here when the protected shell is released.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitNodesState,",
    "      nodeSummary.total ? String(nodeSummary.online || 0) + '/' + String(nodeSummary.total || 0) + ' online' : 'No nodes',",
    "    );",
    "    setText(",
    "      cockpitNodesSummary,",
    "      String(nodeSummary.paired || 0) + ' paired(s) | queue ' + String(nodeSummary.queued || 0)",
    "      + ' | antigos ' + String(nodeSummary.staleQueued || 0),",
    "    );",
    "  }",
    "",
    "  if (!protectedShellUnlocked || !transportSummary) {",
    "    setText(cockpitTransportsState, protectedShellUnlocked ? 'without transportes' : 'Validate the token');",
    "    setText(",
    "      cockpitTransportsSummary,",
    "      protectedShellUnlocked",
    "        - 'No protected remote plan is available to summarize on this host now.'",
    "        : 'The remote plan summary appears here when the protected shell is released.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitTransportsState,",
    "      transportSummary.total ? String(transportSummary.ready || 0) + '/' + String(transportSummary.total || 0) + ' ready' : 'without transportes',",
    "    );",
    "    setText(",
    "      cockpitTransportsSummary,",
    "      String(transportSummary.attentionRequired || 0) + ' with attention | pending items '",
    "      + String(transportSummary.pendingWork || 0) + ' | reachable ' + String(transportSummary.reachable || 0),",
    "    );",
    "  }",
    "",
    "  if (!protectedShellUnlocked || (!workspaceCount && !pluginCount && !hookCount && !extensionSummary)) {",
    "    setText(cockpitIntegrationsState, protectedShellUnlocked ? 'without integrations' : 'Validate the token');",
    "    setText(",
    "      cockpitIntegrationsSummary,",
    "      protectedShellUnlocked",
    "        - 'No workspace, plugin, or hook is loaded to summarize on this host now.'",
    "        : 'Loaded plugins, hooks, and workspaces appear here when the protected shell is released.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitIntegrationsState,",
    "      workspaceCount ? String(workspaceCount) + ' workspace(s)' : String(pluginCount) + ' plugin(s)',",
    "    );",
    "    setText(",
    "      cockpitIntegrationsSummary,",
    "      String(pluginCount) + ' plugin(s) | ' + String(hookCount) + ' hook(s) | '",
    "      + String(Number(extensionSummary?.commands || 0) || 0) + ' command(s)',",
    "    );",
    "  }",
    "",
    "  setText(",
    "    operatorCockpitStatus,",
    "    protectedShellUnlocked",
    "      - 'Use the action rail to refresh the cockpit, copy status/doctor output, or jump to sessions, resources, companions, and health without leaving ZavorthControl.'",
    "      : 'Validate the token to turn this summary into the full operational cockpit.',",
    "  );",
    "}",
    "",
    "function buildSystemOverlordActionControls(action) {",
    "  const actionId = normalizeText(action?.actionId);",
    "  if (!actionId) {",
    "    return '';",
    "  }",
    "  const status = normalizeText(action?.status);",
    "  const controls = [];",
    "  if (status === 'running' || status === 'pending_approval' || status === 'dry_run') {",
    "    controls.push(",
    "      '<button type=\"button\" class=\"action-button secondary compact-action\" data-overlord-action-mode=\"cancel\" data-overlord-action-id=\"' + escapeHtml(actionId) + '\">Cancel</button>',",
    "    );",
    "  }",
    "  if (status === 'completed' && action?.rollbackAvailable === true) {",
    "    controls.push(",
    "      '<button type=\"button\" class=\"action-button compact-action\" data-overlord-action-mode=\"rollback\" data-overlord-action-id=\"' + escapeHtml(actionId) + '\">Rollback</button>',",
    "    );",
    "  }",
    "  if (!controls.length) {",
    "    return '';",
    "  }",
    "  return '<div class=\"inline-action-row\">' + controls.join('') + '</div>';",
    "}",
    "",
    "function renderEvalControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    evalControlPlaneData = payload;",
    "  }",
    "  const snapshot = evalControlPlaneData?.evals || evalControlPlaneData?.snapshot || evalControlPlaneData || null;",
    "  const errorMessage = normalizeText(evalControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(evalControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(evalControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      evalControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'The eval panel has not responded in this runtime yet.'",
    "        : 'Operational eval reading appears here when the protected shell is released.',",
    "    );",
    "    setText(evalControlPlaneScorecardsState, 'No reading');",
    "    setText(evalControlPlaneScorecardsSummary, 'Routes with better baseline and higher friction appear here.');",
    "    setText(evalControlPlaneDatasetsState, 'No reading');",
    "    setText(evalControlPlaneDatasetsSummary, 'Operational datasets and comparisons appear here when reads exist.');",
    "    setText(evalControlPlaneCoverageState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(evalControlPlaneCoverageSummary, 'Tasks, approvals, workflows, and artifacts feeding this panel appear here.');",
    "    setText(evalControlPlaneStatus, errorMessage || 'Validate the token to review scorecards, regressions and datasets from this host.');",
    "    renderList(evalControlPlaneScorecards, [errorMessage || 'Validate the token to see runtime scorecards and baselines.']);",
    "    renderList(evalControlPlaneRegressions, [errorMessage || 'Validate the token to see regressions and bottlenecks for this window.']);",
    "    renderList(evalControlPlaneDatasets, [errorMessage || 'Validate the token to review datasets operational, coverage and comparisons.']);",
    "    if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      evalControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      evalControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const scorecards = Array.isArray(snapshot.scorecards) ? snapshot.scorecards : [];",
    "  const regressions = Array.isArray(snapshot.regressions) ? snapshot.regressions : [];",
    "  const datasets = Array.isArray(snapshot.datasets) ? snapshot.datasets : [];",
    "  const coverage = snapshot.coverage || {};",
    "  const comparisons = snapshot.comparisons || {};",
    "  const telemetry = snapshot.telemetry || {};",
    "  const history = snapshot.history || {};",
    "  const operatorSummary = normalizeText(snapshot?.narrative?.operatorSummary);",
    "",
    "  setCardEmphasis(evalControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(evalControlPlaneState, posture);",
    "  setText(",
    "    evalControlPlaneSummary,",
    "    operatorSummary",
    "      || 'Operational eval panel updated.',",
    "  );",
    "  setText(",
    "    evalControlPlaneScorecardsState,",
    "    String(summary.scorecards || scorecards.length || 0) + ' scorecard(s)',",
    "  );",
    "  setText(",
    "    evalControlPlaneScorecardsSummary,",
    "    String(summary.healthyScorecards || 0)",
    "      + ' healthy | '",
    "      + String(summary.attentionScorecards || 0)",
    "      + ' attention | '",
    "      + String(summary.criticalScorecards || 0)",
    "      + ' critical',",
    "  );",
    "  setText(",
    "    evalControlPlaneDatasetsState,",
    "    String(summary.datasets || datasets.length || 0) + ' dataset(s)',",
    "  );",
    "  setText(",
    "    evalControlPlaneDatasetsSummary,",
    "    [",
    "      regressions.length > 0",
    "        - 'Largest regression: ' + normalizeText(regressions[0]?.label || 'without label')",
    "        : 'without strong regressions in the current slice.',",
    "      Number(history.entries || 0) > 0",
    "        - 'Historico: ' + String(history.entries || 0) + ' window(s)'",
    "        : 'Historico still at formaction.',",
    "    ].filter(Boolean).join(' | '),",
    "  );",
    "  setText(",
    "    evalControlPlaneCoverageState,",
    "    String(summary.telemetrySignals || 0)",
    "      + ' sinal(is) | traces '",
    "      + String(telemetry.traceCount || 0)",
    "      + ' | cost '",
    "      + String(summary.operatorCostState || 'low'),",
    "  );",
    "  setText(",
    "    evalControlPlaneCoverageSummary,",
    "    [",
    "      normalizeText(coverage.taskSignal),",
    "      normalizeText(coverage.workflowSignal),",
    "      normalizeText(telemetry.lastEventAt)",
    "        - 'ultima trace at ' + normalizeText(telemetry.lastEventAt)",
    "        : 'without trace recente',",
    "    ].filter(Boolean).join(' | '),",
    "  );",
    "  setText(",
    "    evalControlPlaneStatus,",
    "    normalizeText(history.recommendation)",
    "      || normalizeText(telemetry.recommendation)",
    "      || operatorSummary",
    "      || 'Operational evals updated.',",
    "  );",
    "  renderList(",
    "    evalControlPlaneScorecards,",
    "    scorecards.slice(0, 6).map((entry) => {",
    "      const successRate = Math.round(Number(entry?.successRate || 0) * 100);",
    "      const frictionRate = Math.round(Number(entry?.frictionRate || 0) * 100);",
    "      return '<strong>'",
    "        + escapeHtml(normalizeText(entry?.label || 'Flow'))",
    "        + '</strong>: '",
    "        + escapeHtml(normalizeText(entry?.status || 'unknown'))",
    "        + ' | success '",
    "        + String(successRate)",
    "        + '% | friction '",
    "        + String(frictionRate)",
    "        + '%';",
    "    }).concat(",
    "      scorecards.length === 0 ? ['without enough scorecards in this slice.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    evalControlPlaneRegressions,",
    "    regressions.slice(0, 6).map((entry) => {",
    "      return '<strong>'",
    "        + escapeHtml(normalizeText(entry?.label || 'Regression'))",
    "        + '</strong>: '",
    "        + escapeHtml(normalizeText(entry?.severity || 'medium'))",
    "        + ' | '",
    "        + escapeHtml(normalizeText(entry?.evidence || 'without evidence resumida.'));",
    "    }).concat(",
    "      regressions.length === 0 ? ['without regressions destacadas in this read.'] : [],",
    "    ),",
    "  );",
    "  const comparisonItems = []",
    "    .concat(",
    "      Array.isArray(comparisons.executors)",
    "        - comparisons.executors.slice(0, 2).map((entry) => {",
    "            return '<strong>Executor:</strong> '",
    "              + escapeHtml(normalizeText(entry?.label || 'executor'))",
    "              + ' | '",
    "              + escapeHtml(normalizeText(entry?.note || 'without nota.'));",
    "          })",
    "        : [],",
    "    )",
    "    .concat(",
    "      Array.isArray(comparisons.surfaces)",
    "        - comparisons.surfaces.slice(0, 2).map((entry) => {",
    "            return '<strong>Surface:</strong> '",
    "              + escapeHtml(normalizeText(entry?.label || 'surface'))",
    "              + ' | '",
    "              + escapeHtml(normalizeText(entry?.note || 'without nota.'));",
    "          })",
    "        : [],",
    "    );",
    "  const telemetryItems = []",
    "    .concat(",
    "      Array.isArray(telemetry.traces)",
    "        - telemetry.traces.slice(0, 2).map((entry) => {",
    "            return '<strong>Trace:</strong> '",
    "              + escapeHtml(normalizeText(entry?.source || 'runtime'))",
    "              + ' | '",
    "              + escapeHtml(normalizeText(entry?.status || 'unknown'))",
    "              + ' | '",
    "              + String(entry?.eventCount || 0)",
    "              + ' event(s)';",
    "          })",
    "        : [],",
    "    )",
    "    .concat(",
    "      Array.isArray(telemetry.topEventTypes)",
    "        - telemetry.topEventTypes.slice(0, 2).map((entry) => {",
    "            return '<strong>Evento:</strong> '",
    "              + escapeHtml(normalizeText(entry?.label || 'telemetry'))",
    "              + ' | '",
    "              + String(entry?.count || 0)",
    "              + ' vez(es)';",
    "          })",
    "        : [],",
    "    )",
    "    .concat(",
    "      Array.isArray(history.trend)",
    "        - history.trend.slice(-2).reverse().map((entry) => {",
    "            return '<strong>Baseline:</strong> '",
    "              + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "              + ' | regressions '",
    "              + String(entry?.regressions || 0)",
    "              + ' | traces '",
    "              + String(entry?.traceCount || 0);",
    "          })",
    "        : [],",
    "    );",
    "  renderList(",
    "    evalControlPlaneDatasets,",
    "    datasets.slice(0, 4).map((entry) => {",
    "      return '<strong>'",
    "        + escapeHtml(normalizeText(entry?.label || 'Dataset'))",
    "        + '</strong>: '",
    "        + String(entry?.sampleCount || 0)",
    "        + ' item(s) | '",
    "        + escapeHtml(normalizeText(entry?.description || 'without descricao.'));",
    "    }).concat(",
    "      Array.isArray(coverage.notes)",
    "        - coverage.notes.slice(0, 2).map((entry) => '<strong>Coverage:</strong> ' + escapeHtml(normalizeText(entry)))",
    "        : [],",
    "    ).concat(",
    "      telemetryItems,",
    "    ).concat(",
    "      comparisonItems.length ? comparisonItems : ['without enough comparisons in this slice.'],",
    "    ),",
    "  );",
    "  if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    evalControlPlaneRefreshAction.hidden = false;",
    "    evalControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderHubControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    hubControlPlaneData = payload;",
    "  }",
    "  const snapshot = hubControlPlaneData?.hub || hubControlPlaneData?.snapshot || hubControlPlaneData || null;",
    "  const errorMessage = normalizeText(hubControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
].join('\n');
