export const runtimeShellScriptPart4Seg1: string = [
    "      + ' | warnings ' + escapeHtml(String(entry?.validationWarnings || 0))",
    "      + (normalizeText(entry?.file) ? ' | ' + escapeHtml(normalizeText(entry.file)) : ''),",
    "    ).concat(",
    "      publishArtifacts.length === 0 ? ['No recent bundle saved yet on this host.'] : [],",
    "    ),",
    "  );",
    "  if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    ecosystemControlPlaneRefreshAction.hidden = false;",
    "    ecosystemControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderDistributedRuntimeControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    distributedRuntimeControlPlaneData = payload;",
    "  }",
    "  const snapshot = distributedRuntimeControlPlaneData?.distributedRuntime",
    "    || distributedRuntimeControlPlaneData?.snapshot",
    "    || distributedRuntimeControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(distributedRuntimeControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(distributedRuntimeControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(distributedRuntimeControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      distributedRuntimeControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado of the runtime distributed not yet respondeu on this host.'",
    "        : 'Channel Mesh, fleet, transports and surfaces oficiais aparecem here when the protected shell is released.',",
    "    );",
    "    setText(distributedRuntimeChannelsState, 'No reading');",
    "    setText(distributedRuntimeChannelsSummary, 'Slack, WhatsApp, Signal, iMessage, Teams and Email aparecem in this recorte.');",
    "    setText(distributedRuntimeFleetState, 'No reading');",
    "    setText(distributedRuntimeFleetSummary, 'Online, queue, stale, and advanced capability coverage appear here.');",
    "    setText(distributedRuntimeTransportsState, 'No reading');",
    "    setText(distributedRuntimeTransportsSummary, 'Remote bridges, sidecars, and node-hosts appear here.');",
    "    setText(distributedRuntimeSurfacesState, 'No reading');",
    "    setText(distributedRuntimeSurfacesSummary, 'Web shell, CLI, Telegram, Discord, and the official remote appear here.');",
    "    setText(",
    "      distributedRuntimeControlPlaneStatus,",
    "      errorMessage || 'Validate the token to review channels, fleet, transports and surfaces of the Distributed runtime.',",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneActions,",
    "      [errorMessage || 'Validate the token to review o next passo of the runtime distributed.'],",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneChannels,",
    "      [errorMessage || 'Validate the token to see advanced channels under the same canonical contract.'],",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneFleet,",
    "      [errorMessage || 'Validate the token to see advanced fleet capability coverage.'],",
    "    );",
    "    renderList(",
    "      distributedRuntimeControlPlaneSurfaces,",
    "      [errorMessage || 'Validate the token to review shell web, CLI, Telegram, Discord and remote oficial.'],",
    "    );",
    "    if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      distributedRuntimeControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      distributedRuntimeControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const advancedChannels = Array.isArray(snapshot.advancedChannels) ? snapshot.advancedChannels : [];",
    "  const fleetCapabilities = Array.isArray(snapshot.fleetCapabilities) ? snapshot.fleetCapabilities : [];",
    "  const surfaces = Array.isArray(snapshot.surfaces) ? snapshot.surfaces : [];",
    "",
    "  setCardEmphasis(distributedRuntimeControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(distributedRuntimeControlPlaneState, posture);",
    "  setText(",
    "    distributedRuntimeControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Runtime distributed currentizado.',",
    "  );",
    "  setText(",
    "    distributedRuntimeChannelsState,",
    "    String(summary.readyAdvancedChannels || 0) + '/' + String(summary.advancedChannels || 0) + ' advanced',",
    "  );",
    "  setText(",
    "    distributedRuntimeChannelsSummary,",
    "    String(summary.readyChannels || 0) + '/' + String(summary.totalChannels || 0)",
    "      + ' in the general contract | attachments ' + String(summary.channelsWithAttachments || 0)",
    "      + ' | threads ' + String(summary.channelsWithThreads || 0),",
    "  );",
    "  setText(",
    "    distributedRuntimeFleetState,",
    "    String(summary.onlineNodes || 0) + '/' + String(summary.totalNodes || 0) + ' online',",
    "  );",
    "  setText(",
    "    distributedRuntimeFleetSummary,",
    "    'queue ' + String(summary.queuedInvocations || 0)",
    "      + ' | stale ' + String(summary.staleQueued || 0)",
    "      + ' | caps ' + String(summary.advancedCapabilityCoverage || 0) + '/8',",
    "  );",
    "  setText(",
    "    distributedRuntimeTransportsState,",
    "    String(summary.readyTransports || 0) + '/' + String(summary.totalTransports || 0) + ' ready',",
    "  );",
    "  setText(",
    "    distributedRuntimeTransportsSummary,",
    "    'live ' + String(summary.liveTransports || 0)",
    "      + ' | attention ' + String(summary.transportAttention || 0),",
    "  );",
    "  setText(",
    "    distributedRuntimeSurfacesState,",
    "    String(summary.readySurfaces || 0) + '/' + String(summary.totalSurfaces || 0) + ' ready',",
    "  );",
    "  setText(",
    "    distributedRuntimeSurfacesSummary,",
    "    'primaria ' + (summary.primarySurfaceReady ? 'ok' : 'pending')",
    "      + ' | remote ' + (summary.remoteReady ? 'ok' : 'pending'),",
    "  );",
    "  setText(",
    "    distributedRuntimeControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Distributed runtime updated.',",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['without suggested actions; mantenha a malha distribuida sob review periodica.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneChannels,",
    "    advancedChannels.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Channel')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.readiness || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || entry?.operatorSummary || 'No summary.'))",
    "      + (normalizeText(entry?.operatorNextStep || entry?.actionHint)",
    "        - ' | ' + escapeHtml(normalizeText(entry?.operatorNextStep || entry?.actionHint))",
    "        : ''),",
    "    ).concat(",
    "      advancedChannels.length === 0 ? ['No advanced channel visible in this slice.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneFleet,",
    "    fleetCapabilities.map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Capability')) + '</strong>: '",
    "      + escapeHtml(String(entry?.supportedNodes || 0) + ' node(s)')",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.category || 'misc'))",
    "      + (entry?.risky ? ' | sensitive' : ' | liberada')",
    "      + (normalizeText(entry?.actionHint) ? ' | ' + escapeHtml(normalizeText(entry.actionHint)) : ''),",
    "    ).concat(",
    "      fleetCapabilities.length === 0 ? ['No capability avancada mapeada in this recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    distributedRuntimeControlPlaneSurfaces,",
    "    surfaces.map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Surface')) + '</strong>: '",
    "      + escapeHtml(entry?.ready ? 'ready' : 'pending')",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.description || 'No summary.'))",
    "      + (normalizeText(entry?.entry) ? ' | ' + escapeHtml(normalizeText(entry.entry)) : '')",
    "      + (normalizeText(entry?.remoteEntry) ? ' | remote ' + escapeHtml(normalizeText(entry.remoteEntry)) : ''),",
    "    ).concat(",
    "      surfaces.length === 0 ? ['No surface oficial mapeada in this recorte.'] : [],",
    "    ),",
    "  );",
    "  if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    distributedRuntimeControlPlaneRefreshAction.hidden = false;",
    "    distributedRuntimeControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderRuntimeStabilityControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    runtimeStabilityControlPlaneData = payload;",
    "  }",
    "  const snapshot = runtimeStabilityControlPlaneData?.runtimeStability",
    "    || runtimeStabilityControlPlaneData?.snapshot",
    "    || runtimeStabilityControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(runtimeStabilityControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(runtimeStabilityControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(runtimeStabilityControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      runtimeStabilityControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado de estabilidade not yet respondeu on this host.'",
    "        : 'Fleet, transports, keepalive and recovery aparecem here when the protected shell is released.',",
    "    );",
    "    setText(runtimeStabilityFleetState, 'No reading');",
    "    setText(runtimeStabilityFleetSummary, 'Online, paired, queue, and stale states of the Node Mesh appear here.');",
    "    setText(runtimeStabilityTransportsState, 'No reading');",
    "    setText(runtimeStabilityTransportsSummary, 'Transport readiness, attention, and doctor appear here.');",
    "    setText(runtimeStabilityKeepaliveState, 'No reading');",
    "    setText(runtimeStabilityKeepaliveSummary, 'Supervised processes, restarts, and staleness appear here.');",
    "    setText(runtimeStabilityRecoverState, 'No reading');",
    "    setText(runtimeStabilityRecoverSummary, 'Recoverable issues and canonical repair appear here.');",
    "    setText(",
    "      runtimeStabilityControlPlaneStatus,",
    "      errorMessage || 'Validate the token to review keepalive, doctor and recovery supervised.',",
    "    );",
    "    renderList(",
    "      runtimeStabilityControlPlaneActions,",
    "      [errorMessage || 'Validate the token to review the next step for supervised stability.'],",
    "    );",
    "    renderList(",
    "      runtimeStabilityControlPlaneCards,",
    "      [errorMessage || 'Validate the token to see fleet, transports, keepalive, and recovery in one frame.'],",
    "    );",
    "    renderList(",
    "      runtimeStabilityControlPlaneProcesses,",
    "      [errorMessage || 'Validate the token to review proxy, gateway, and supervised node-hosts.'],",
    "    );",
    "    if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      runtimeStabilityControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      runtimeStabilityControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const cards = Array.isArray(snapshot.cards) ? snapshot.cards : [];",
    "  const processes = Array.isArray(snapshot.keepalive?.processes) ? snapshot.keepalive.processes : [];",
    "",
    "  setCardEmphasis(runtimeStabilityControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(runtimeStabilityControlPlaneState, posture);",
    "  setText(",
    "    runtimeStabilityControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Supervised stability updated.',",
    "  );",
    "  setText(",
    "    runtimeStabilityFleetState,",
    "    String(summary.onlineNodes || 0) + '/' + String(summary.totalNodes || 0) + ' online',",
    "  );",
    "  setText(",
    "    runtimeStabilityFleetSummary,",
    "    'paired ' + String(summary.pairedNodes || 0)",
    "      + ' | queue ' + String(summary.queuedInvocations || 0)",
    "      + ' | stale ' + String(summary.staleQueued || 0),",
    "  );",
    "  setText(",
    "    runtimeStabilityTransportsState,",
    "    String(summary.readyTransports || 0) + '/' + String(summary.totalTransports || 0) + ' ready',",
    "  );",
    "  setText(",
    "    runtimeStabilityTransportsSummary,",
    "    'attention ' + String(summary.transportAttention || 0)",
    "      + ' | recoverable ' + String(summary.recoverableIssues || 0),",
    "  );",
    "  setText(",
    "    runtimeStabilityKeepaliveState,",
    "    summary.keepaliveActive ? (summary.keepaliveStale ? 'stale' : 'active') : 'absent',",
    "  );",
    "  setText(",
    "    runtimeStabilityKeepaliveSummary,",
    "    String(summary.keepaliveReadyProcesses || 0) + '/' + String(summary.keepaliveTotalProcesses || 0)",
    "      + ' process(s) ready',",
    "  );",
    "  setText(",
    "    runtimeStabilityRecoverState,",
    "    String(summary.recoverableIssues || 0) + ' issue(s)',",
    "  );",
    "  setText(",
    "    runtimeStabilityRecoverSummary,",
    "    (summary.recoverableIssues || 0) > 0",
    "      - 'There is pending recovery to clean the supervised mesh.'",
    "      : 'No urgent repair; keep doctor and keepalive current.',",
    "  );",
    "  setText(",
    "    runtimeStabilityControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Supervised stability updated.',",
    "  );",
    "  renderList(",
    "    runtimeStabilityControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['without suggested actions; mantenha keepalive and doctor recorrentes.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    runtimeStabilityControlPlaneCards,",
    "    cards.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Card')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      cards.length === 0 ? ['No operational card generated in this slice.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    runtimeStabilityControlPlaneProcesses,",
    "    processes.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.name || 'Processo')) + '</strong>: '",
    "      + escapeHtml(entry?.ready ? 'ready' : 'unhealthy')",
    "      + ' | restart ' + escapeHtml(String(entry?.restarts || 0))",
    "      + (normalizeText(entry?.lastError) ? ' | ' + escapeHtml(normalizeText(entry.lastError)) : ''),",
    "    ).concat(",
    "      processes.length === 0 ? ['No process keepalive listado on this host.'] : [],",
    "    ),",
    "  );",
    "  if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    runtimeStabilityControlPlaneRefreshAction.hidden = false;",
    "    runtimeStabilityControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderAutomationControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    automationControlPlaneData = payload;",
    "  }",
    "  const snapshot = automationControlPlaneData?.automations",
    "    || automationControlPlaneData?.snapshot",
    "    || automationControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(automationControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(automationControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(automationControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      automationControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado de automations not yet respondeu on this host.'",
    "        : 'Automations naturais, maintenance and deliveries aparecem here when the protected shell is released.',",
    "    );",
    "    setText(automationControlPlaneTasksState, 'No reading');",
    "    setText(automationControlPlaneTasksSummary, 'Active scheduled runs, paused runs, and recent failures appear here.');",
    "    setText(automationControlPlaneMaintenanceState, 'No reading');",
    "    setText(automationControlPlaneMaintenanceSummary, 'Recurring maintenance and the next trigger appear here.');",
    "    setText(automationControlPlaneDeliveriesState, 'No reading');",
    "    setText(automationControlPlaneDeliveriesSummary, 'Recent app, email, and webhook deliveries appear here.');",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      errorMessage || 'Validate the token to create automations and review o state recorrente of the host.',",
    "    );",
    "    renderList(",
    "      automationControlPlaneActions,",
    "      [errorMessage || 'Validate the token to review the next automation step.'],",
    "    );",
    "    renderList(",
    "      automationControlPlaneTasks,",
    "      [errorMessage || 'Validate the token to view schedules for this host.'],",
    "    );",
    "    renderList(",
    "      automationControlPlaneDeliveries,",
    "      [errorMessage || 'Validate the token to review entregas por app, email or webhook.'],",
    "    );",
    "    if (automationControlPlaneCreateAction instanceof HTMLButtonElement) {",
    "      automationControlPlaneCreateAction.hidden = !protectedShellUnlocked;",
    "      automationControlPlaneCreateAction.disabled = false;",
    "    }",
    "    for (const button of [",
    "      automationControlPlaneRefreshAction,",
    "      automationControlPlaneMaintenanceOnAction,",
    "      automationControlPlaneMaintenanceOffAction,",
    "      automationControlPlaneMaintenanceRunAction,",
    "    ]) {",
    "      if (button instanceof HTMLButtonElement) {",
    "        button.hidden = !protectedShellUnlocked;",
    "        button.disabled = false;",
    "      }",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const tasks = Array.isArray(snapshot.tasks) ? snapshot.tasks : [];",
    "  const deliveries = Array.isArray(snapshot.deliveries) ? snapshot.deliveries : [];",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "",
    "  setCardEmphasis(automationControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(automationControlPlaneState, posture);",
    "  setText(",
    "    automationControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Automations currentizadas.',",
    "  );",
    "  setText(",
    "    automationControlPlaneTasksState,",
    "    String(summary.activeTasks || 0) + ' active(s)',",
    "  );",
    "  setText(",
    "    automationControlPlaneTasksSummary,",
    "    'pausadas ' + String(summary.pausedTasks || 0)",
    "      + ' | failures ' + String(summary.failedTasks || 0),",
    "  );",
    "  setText(",
    "    automationControlPlaneMaintenanceState,",
    "    snapshot?.maintenance?.enabled ? 'active' : 'off',",
    "  );",
    "  setText(",
    "    automationControlPlaneMaintenanceSummary,",
    "    normalizeText(snapshot?.maintenance?.nextPlannedAt)",
    "      - 'next ' + escapeHtml(formatRelativeTime(snapshot.maintenance.nextPlannedAt))",
    "      : 'without next window registrada',",
    "  );",
    "  setText(",
    "    automationControlPlaneDeliveriesState,",
    "    String(summary.deliveries || deliveries.length || 0) + ' recente(s)',",
    "  );",
    "  setText(",
    "    automationControlPlaneDeliveriesSummary,",
    "    deliveries.length > 0",
    "      - 'latest channel: ' + normalizeText(deliveries[0]?.delivery || 'app')",
    "      : 'no entrega recente registrada.',",
    "  );",
    "  setText(",
    "    automationControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Scheduled runs updated.',",
    "  );",
    "  renderList(",
    "    automationControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(actions.length === 0 ? ['No suggested actions; the recurring plan is stable.'] : []),",
    "  );",
    "  renderList(",
    "    automationControlPlaneTasks,",
    "    tasks.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.shortId || entry?.id || 'task')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.schedule || 'without agenda'))",
    "      + ' | ' + escapeHtml(normalizeText(entry?.prompt || 'without prompt'))",
    "      + ' | ' + escapeHtml(normalizeText(entry?.delivery || 'telegram'))",
    "      + ' | ' + escapeHtml(normalizeText(entry?.status || 'idle'))",
    "      + (normalizeText(entry?.lastError) ? ' | ' + escapeHtml(normalizeText(entry.lastError)) : '')",
    "      + ' <button type=\"button\" class=\"inline-chip-button\" data-automation-action=\"pause\" data-automation-task-id=\"' + escapeHtml(normalizeText(entry?.shortId || '')) + '\">Pausar</button>'",
    "      + ' <button type=\"button\" class=\"inline-chip-button\" data-automation-action=\"resume\" data-automation-task-id=\"' + escapeHtml(normalizeText(entry?.shortId || '')) + '\">resume</button>'",
    "      + ' <button type=\"button\" class=\"inline-chip-button\" data-automation-action=\"remove\" data-automation-task-id=\"' + escapeHtml(normalizeText(entry?.shortId || '')) + '\">Remove</button>',",
    "    ).concat(tasks.length === 0 ? ['No automation registered on this host.'] : []),",
    "  );",
    "  renderList(",
    "    automationControlPlaneDeliveries,",
    "    deliveries.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.delivery || 'app')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (normalizeText(entry?.target) ? ' | ' + escapeHtml(normalizeText(entry.target)) : ''),",
    "    ).concat(deliveries.length === 0 ? ['No entrega recente registrada.'] : []),",
    "  );",
    "  if (automationControlPlaneCreateAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneCreateAction.hidden = false;",
    "    automationControlPlaneCreateAction.disabled = false;",
    "  }",
    "  for (const button of [",
    "    automationControlPlaneRefreshAction,",
    "    automationControlPlaneMaintenanceOnAction,",
    "    automationControlPlaneMaintenanceOffAction,",
    "    automationControlPlaneMaintenanceRunAction,",
    "  ]) {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.hidden = false;",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "function renderRolloutReadinessControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    rolloutReadinessControlPlaneData = payload;",
    "  }",
    "  const snapshot = rolloutReadinessControlPlaneData?.rolloutReadiness",
    "    || rolloutReadinessControlPlaneData?.snapshot",
    "    || rolloutReadinessControlPlaneData",
    "    || null;",
    "  const errorMessage = normalizeText(rolloutReadinessControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(rolloutReadinessControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(rolloutReadinessControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      rolloutReadinessControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado de rollout readiness not yet respondeu on this host.'",
    "        : 'QA, maintenance and rollout persistente aparecem here when the protected shell is released.',",
    "    );",
    "    setText(rolloutReadinessQaState, 'No reading');",
    "    setText(rolloutReadinessQaSummary, 'Alpha/beta gates, regressions, and readiness appear here.');",
    "    setText(rolloutReadinessDistributedState, 'No reading');",
    "    setText(rolloutReadinessDistributedSummary, 'A postura of the runtime distributed entra como requisito of the rollout.');",
    "    setText(rolloutReadinessMaintenanceState, 'No reading');",
    "    setText(rolloutReadinessMaintenanceSummary, 'Recurring maintenance and persistent keepalive appear here.');",
    "    setText(rolloutReadinessPublishState, 'No reading');",
    "    setText(rolloutReadinessPublishSummary, 'Publish history and baseline comparisons appear here.');",
    "    setText(",
    "      rolloutReadinessControlPlaneStatus,",
    "      errorMessage || 'Validate the token to review gates, maintenance, and publish for persistent rollout.',",
    "    );",
    "    renderList(",
    "      rolloutReadinessControlPlaneActions,",
    "      [errorMessage || 'Validate the token to review the next step for persistent rollout.'],",
    "    );",
    "    renderList(",
    "      rolloutReadinessControlPlaneCards,",
    "      [errorMessage || 'Validate the token to see QA, runtime, maintenance, and publish in one panel.'],",
    "    );",
    "    renderList(",
    "      rolloutReadinessControlPlanePublish,",
    "      [errorMessage || 'Validate the token to review o history de publish of the host.'],",
    "    );",
    "    if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      rolloutReadinessControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      rolloutReadinessControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const cards = Array.isArray(snapshot.cards) ? snapshot.cards : [];",
    "  const publishEntries = Array.isArray(snapshot.sourceSnapshots?.publishHistory)",
    "    - snapshot.sourceSnapshots.publishHistory",
    "    : [];",
    "",
    "  setCardEmphasis(rolloutReadinessControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(rolloutReadinessControlPlaneState, posture);",
    "  setText(",
    "    rolloutReadinessControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Persistent rollout updated.',",
    "  );",
    "  setText(",
    "    rolloutReadinessQaState,",
    "    normalizeText(summary.qaPosture || 'unknown'),",
    "  );",
    "  setText(",
    "    rolloutReadinessQaSummary,",
    "    snapshot?.summary?.releaseReady ? 'Release ready for promotion.' : 'There are still gates pending before of the release.',",
    "  );",
    "  setText(",
    "    rolloutReadinessDistributedState,",
    "    normalizeText(summary.distributedPosture || 'unknown'),",
    "  );",
    "  setText(",
    "    rolloutReadinessDistributedSummary,",
    "    'keepalive ' + (summary.keepaliveActive ? 'ok' : 'pending')",
    "      + ' | runtime ' + normalizeText(summary.distributedPosture || 'unknown'),",
    "  );",
    "  setText(",
    "    rolloutReadinessMaintenanceState,",
    "    summary.maintenanceFresh ? 'fresh' : 'pending',",
    "  );",
    "  setText(",
    "    rolloutReadinessMaintenanceSummary,",
    "    summary.maintenanceFresh",
    "      - 'Recent recurring maintenance supports long-running rollout.'",
    "      : 'The recurring cycle must be renewed before rollout.',",
    "  );",
    "  setText(",
    "    rolloutReadinessPublishState,",
    "    String(summary.publishEntries || 0) + ' release(s)',",
    "  );",
    "  setText(",
    "    rolloutReadinessPublishSummary,",
    "    String(summary.publishComparisons || 0) + ' comparison(s) against the previous baseline',",
    "  );",
    "  setText(",
    "    rolloutReadinessControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Persistent rollout updated.',",
    "  );",
    "  renderList(",
    "    rolloutReadinessControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['without suggested actions; mantenha QA, maintenance and publish sob review periodica.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    rolloutReadinessControlPlaneCards,",
    "    cards.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || entry?.id || 'Card')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      cards.length === 0 ? ['No operational card generated in this slice.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    rolloutReadinessControlPlanePublish,",
    "    publishEntries.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.releaseId || entry?.packageId || 'Release')) + '</strong>: '",
].join('\n');
