export const runtimeShellScriptPart4Seg2: string = [
    "      + escapeHtml(normalizeText(entry?.uploadStatus || 'history'))",
    "      + (normalizeText(entry?.outputFile || entry?.bundlePath)",
    "        - ' | ' + escapeHtml(normalizeText(entry?.outputFile || entry?.bundlePath))",
    "        : ''),",
    "    ).concat(",
    "      publishEntries.length === 0 ? ['No publish salvo still on this host.'] : [],",
    "    ),",
    "  );",
    "  if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    rolloutReadinessControlPlaneRefreshAction.hidden = false;",
    "    rolloutReadinessControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderTrustPlanePanel(payload = null) {",
    "  const snapshot = payload?.trustPlane || payload?.snapshot || payload || null;",
    "  const errorMessage = normalizeText(payload?.error);",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(trustPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(trustPlaneHostState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      trustPlaneHostSummary,",
    "      protectedShellUnlocked",
    "        - 'O Trust Plane not yet respondeu in this runtime.'",
    "        : 'Approvals, kill switch and capabilities sensitive aparecem here when o shell protegido estiver liberado.',",
    "    );",
    "    setText(trustPlaneMcpState, 'Perfil safe');",
    "    setText(trustPlaneMcpSummary, 'O profile MCP and a allowlist explicit aparecem here when o runtime protegido estiver autenticado.');",
    "    setText(trustPlaneSkillsState, 'Policy deny');",
    "    setText(trustPlaneSkillsSummary, 'Skill policy and trusted plugin plane appear together here to avoid scattered trust.');",
    "    setText(trustPlaneRuntimeState, protectedShellUnlocked ? 'Unavailable' : 'Baseline');",
    "    setText(trustPlaneRuntimeSummary, 'The Runtime & Security Mesh trust boundary appears here in a short form for the operator.');",
    "    setText(trustPlaneStatus, errorMessage || 'Validate the token to review this host official Trust Plane.');",
    "    renderList(trustPlaneHighlights, [errorMessage || 'Validate the token to see the main risks and blockers.']);",
    "    renderList(trustPlaneActions, [errorMessage || 'Validate the token to review the next Trust Plane steps.']);",
    "    renderList(trustPlaneSurfaces, [errorMessage || 'Validate the token to see host, MCP, skills, plugins, and runtime in one read.']);",
    "    if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      trustPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      trustPlaneRefreshAction.disabled = false;",
    "    }",
    "    if (trustPlanePromoteTrustedAction instanceof HTMLButtonElement) {",
    "      trustPlanePromoteTrustedAction.hidden = !protectedShellUnlocked;",
    "      trustPlanePromoteTrustedAction.disabled = false;",
    "    }",
    "    if (trustPlaneHardenSafeAction instanceof HTMLButtonElement) {",
    "      trustPlaneHardenSafeAction.hidden = !protectedShellUnlocked;",
    "      trustPlaneHardenSafeAction.disabled = false;",
    "    }",
    "    if (trustPlaneSkillsDenyAction instanceof HTMLButtonElement) {",
    "      trustPlaneSkillsDenyAction.hidden = !protectedShellUnlocked;",
    "      trustPlaneSkillsDenyAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const surfaces = snapshot.surfaces || {};",
    "  const highlights = Array.isArray(snapshot.riskHighlights) ? snapshot.riskHighlights : [];",
    "  const actions = Array.isArray(snapshot.suggestedActions) ? snapshot.suggestedActions : [];",
    "  const host = surfaces.systemOverlord || {};",
    "  const mcp = surfaces.mcp || {};",
    "  const skills = surfaces.skills || {};",
    "  const plugins = surfaces.plugins || {};",
    "  const nodes = surfaces.nodes || {};",
    "  const runtime = surfaces.runtime || {};",
    "  const attention = Number(summary.pendingApprovals || 0)",
    "    + Number(summary.highRiskCapabilities || 0)",
    "    + (summary.killSwitchActive ? 2 : 0)",
    "    + highlights.filter((entry) => normalizeText(entry?.severity) === 'critical').length;",
    "",
    "  setCardEmphasis(trustPlaneCard, attention > 0 ? 'focus' : 'subtle');",
    "  setText(",
    "    trustPlaneHostState,",
    "    summary.killSwitchActive",
    "      - 'Kill switch'",
    "      : Number(summary.pendingApprovals || 0) > 0",
    "        - 'Approvals'",
    "        : 'Protegido',",
    "  );",
    "  setText(",
    "    trustPlaneHostSummary,",
    "    normalizeText(host.operatorSummary)",
    "      || String(summary.pendingApprovals || 0) + ' approval(s) and '",
    "      + String(summary.highRiskCapabilities || 0) + ' capability(s) sensitive.',",
    "  );",
    "  setText(",
    "    trustPlaneMcpState,",
    "    String(mcp.profile || summary.mcpProfile || 'safe') + ' | ' + String(summary.mcpAllowedTools || 0) + ' tools',",
    "  );",
    "  setText(",
    "    trustPlaneMcpSummary,",
    "    normalizeText(mcp.operatorSummary)",
    "      || 'MCP without detailed summary in this runtime.',",
    "  );",
    "  setText(",
    "    trustPlaneSkillsState,",
    "    String(skills.defaultPolicy || summary.skillDefaultPolicy || 'deny')",
    "      + ' | ' + String(summary.trustedPlugins || 0) + ' trusted',",
    "  );",
    "  setText(",
    "    trustPlaneSkillsSummary,",
    "    normalizeText(skills.operatorSummary)",
    "      || normalizeText(plugins.operatorSummary)",
    "      || 'Policy de skills and plugin plane without detailed summary.',",
    "  );",
    "  setText(",
    "    trustPlaneRuntimeState,",
    "    String(runtime.posture || summary.posture || 'unknown'),",
    "  );",
    "  setText(",
    "    trustPlaneRuntimeSummary,",
    "    normalizeText(runtime.trustBoundary)",
    "      || normalizeText(runtime.operatorSummary)",
    "      || 'Runtime in the trust boundary detalhado.',",
    "  );",
    "  setText(",
    "    trustPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.operatorSummary)",
    "      || 'Trust Plane updated.',",
    "  );",
    "",
    "  renderList(",
    "    trustPlaneHighlights,",
    "    highlights.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || 'Risk') + '</strong>: '",
    "      + escapeHtml(entry?.summary || 'No summary.')",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(entry?.severity || 'info') + ']</span>'",
    "    ).concat(",
    "      highlights.length === 0",
    "        - ['No highlighted risks in the current summary of the Trust Plane.']",
    "        : highlights.length > 6",
    "          - ['+' + String(highlights.length - 6) + ' risk(s) outside of the short summary.']",
    "          : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    trustPlaneActions,",
    "    actions.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || 'Action') + '</strong>: '",
    "      + escapeHtml(entry?.reason || 'No detailed reason.')",
    "      + (entry?.command",
    "        - ' <span class=\"muted-inline\">[' + escapeHtml(entry.command) + ']</span>'",
    "        : '')",
    "    ).concat(",
    "      actions.length === 0",
    "        - ['without suggested actions in the current summary of the Trust Plane.']",
    "        : actions.length > 6",
    "          - ['+' + String(actions.length - 6) + ' action(oes) outside of the short summary.']",
    "          : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    trustPlaneSurfaces,",
    "    [",
    "      '<strong>Host:</strong> ' + escapeHtml(normalizeText(host.operatorSummary || 'No host summary.')),",
    "      '<strong>MCP:</strong> ' + escapeHtml(",
    "        String(mcp.profile || 'safe') + ' | '",
    "        + String((mcp.allowedTools || []).length || summary.mcpAllowedTools || 0)",
    "        + ' tools | '",
    "        + String((mcp.allowlist || []).length || 0)",
    "        + ' allowlist',",
    "      ),",
    "      '<strong>Skills:</strong> ' + escapeHtml(",
    "        String(skills.defaultPolicy || 'deny') + ' | '",
    "        + String((skills.allowedSourceIds || []).length || summary.skillAllowedSources || 0)",
    "        + ' fontes | '",
    "        + String((skills.explicitRules || []).length || summary.explicitSkillRules || 0)",
    "        + ' regras explicit',",
    "      ),",
    "      '<strong>Plugins:</strong> ' + escapeHtml(",
    "        String(plugins.trusted || summary.trustedPlugins || 0)",
    "        + ' trusted / '",
    "        + String(plugins.installed || summary.installedPlugins || 0)",
    "        + ' installed',",
    "      ),",
    "      '<strong>Nodes:</strong> ' + escapeHtml(",
    "        String(nodes.paired || summary.pairedNodes || 0)",
    "        + ' paired(s) | '",
    "        + String(nodes.restricted || summary.restrictedNodes || 0)",
    "        + ' restrito(s)',",
    "      ),",
    "      '<strong>Runtime:</strong> ' + escapeHtml(normalizeText(runtime.trustBoundary || runtime.operatorSummary || 'No summary of the runtime.')),",
    "    ],",
    "  );",
    "",
    "  if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    trustPlaneRefreshAction.hidden = false;",
    "    trustPlaneRefreshAction.disabled = false;",
    "  }",
    "  if (trustPlanePromoteTrustedAction instanceof HTMLButtonElement) {",
    "    trustPlanePromoteTrustedAction.hidden = false;",
    "    trustPlanePromoteTrustedAction.disabled = normalizeText(mcp.profile || summary.mcpProfile || 'safe') === 'trusted';",
    "  }",
    "  if (trustPlaneHardenSafeAction instanceof HTMLButtonElement) {",
    "    trustPlaneHardenSafeAction.hidden = false;",
    "    trustPlaneHardenSafeAction.disabled = normalizeText(mcp.profile || summary.mcpProfile || 'safe') === 'safe';",
    "  }",
    "  if (trustPlaneSkillsDenyAction instanceof HTMLButtonElement) {",
    "    trustPlaneSkillsDenyAction.hidden = false;",
    "    trustPlaneSkillsDenyAction.disabled = normalizeText(skills.defaultPolicy || summary.skillDefaultPolicy || 'deny') === 'deny';",
    "  }",
    "}",
    "",
    "function buildWatchModeApprovalItems(run) {",
    "  const approvals = Array.isArray(run?.approvals)",
    "    - run.approvals.filter((entry) => normalizeText(entry?.status) === 'pending').slice(0, 5)",
    "    : [];",
    "  if (!approvals.length) {",
    "    return ['No approval pending in the Watch Mode.'];",
    "  }",
    "  return approvals.map((approval) => {",
    "    const approvalId = normalizeText(approval?.approvalId);",
    "    const action = normalizeText(approval?.action?.action) || 'action';",
    "    const target = normalizeText(approval?.action?.targetText || approval?.action?.payload || approval?.action?.windowTitle) || 'no textual target';",
    "    return '<strong>' + escapeHtml(action) + ':</strong> ' + escapeHtml(target)",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(approval?.riskLevel) || 'risk') + ']</span>'",
    "      + '<div class=\"inline-action-row\">'",
    "      + '<button type=\"button\" class=\"action-button compact-action\" data-watch-mode-approval=\"approve\" data-watch-mode-approval-id=\"' + escapeHtml(approvalId) + '\">Approve</button>'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-watch-mode-approval=\"reject\" data-watch-mode-approval-id=\"' + escapeHtml(approvalId) + '\">Deny</button>'",
    "      + '</div>';",
    "  });",
    "}",
    "",
    "function buildWatchModeTimelineItems(run) {",
    "  const timeline = Array.isArray(run?.timeline) ? run.timeline.slice(0, 6) : [];",
    "  if (!timeline.length) {",
    "    return ['No registered visual action ainda.'];",
    "  }",
    "  return timeline.map((entry) => {",
    "    const summary = normalizeText(entry?.summary) || 'Evento visual';",
    "    const createdAt = normalizeText(entry?.createdAt);",
    "    const type = normalizeText(entry?.type) || 'evento';",
    "    const result = normalizeText(entry?.result);",
    "    const parts = ['<strong>' + escapeHtml(type) + ':</strong> ' + escapeHtml(summary)];",
    "    if (createdAt) {",
    "      parts.push('<span class=\"muted-inline\">[' + escapeHtml(new Date(createdAt).toLocaleTimeString('en-US')) + ']</span>');",
    "    }",
    "    if (result) {",
    "      parts.push('<div class=\"muted-copy\">' + escapeHtml(result) + '</div>');",
    "    }",
    "    return parts.join(' ');",
    "  });",
    "}",
    "",
    "function renderWatchModePanel(payload = null) {",
    "  if (payload !== null) {",
    "    watchModeData = payload;",
    "  }",
    "  const snapshot = watchModeData?.snapshot || watchModeData?.watchMode?.watchMode || watchModeData?.watchMode || null;",
    "  const run = watchModeData?.run || snapshot?.activeRun || watchModeData?.activeRun || watchModeData?.watchMode?.watchMode?.activeRun || null;",
    "  const errorMessage = normalizeText(watchModeData?.error);",
    "",
    "  if (!snapshot) {",
    "    setCardEmphasis(watchModeCard, 'subtle');",
    "    setText(watchModeState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      watchModeSummary,",
    "      errorMessage || (",
    "        protectedShellUnlocked",
    "          - 'Supervised Watch Mode unavailable in this runtime.'",
    "          : 'O run visual supervised aparece here assim que o shell protegido for liberado.'",
    "      ),",
    "    );",
    "    setText(watchModePolicyState, 'strict approval');",
    "    setText(watchModePolicySummary, 'Allowlisted apps and sites appear here with approval policy.');",
    "    setText(watchModeApprovalState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(watchModeApprovalSummary, 'every mutable action of the UI pede handoff before run.');",
    "    setText(watchModeReplayState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(watchModeReplaySummary, 'Screenshot current and timeline curta aparecem here when o Watch Mode estiver active.');",
    "    setText(watchModeStatus, errorMessage || 'Validate the token to operate supervised Watch Mode on this host.');",
    "    setText(watchModeNextStep, 'No run active ainda.');",
    "    renderList(watchModeApprovals, [errorMessage || 'Validate the token to review pending visual approvals.']);",
    "    renderList(watchModeTimeline, ['Validate the token to review Watch Mode screenshots, actions, and handoffs.']);",
    "    if (watchModePreview instanceof HTMLImageElement) {",
    "      watchModePreview.hidden = true;",
    "      watchModePreview.removeAttribute('src');",
    "    }",
    "    if (watchModePreviewEmpty instanceof HTMLElement) {",
    "      watchModePreviewEmpty.hidden = false;",
    "    }",
    "    if (watchModeStartAction instanceof HTMLButtonElement) {",
    "      watchModeStartAction.hidden = !protectedShellUnlocked;",
    "      watchModeStartAction.disabled = false;",
    "    }",
    "    if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "      watchModeRefreshAction.hidden = !protectedShellUnlocked;",
    "      watchModeRefreshAction.disabled = false;",
    "    }",
    "    if (watchModeAllowAppAction instanceof HTMLButtonElement) {",
    "      watchModeAllowAppAction.hidden = !protectedShellUnlocked;",
    "      watchModeAllowAppAction.disabled = true;",
    "    }",
    "    if (watchModeAllowSiteAction instanceof HTMLButtonElement) {",
    "      watchModeAllowSiteAction.hidden = !protectedShellUnlocked;",
    "      watchModeAllowSiteAction.disabled = true;",
    "    }",
    "    if (watchModeStrictOnAction instanceof HTMLButtonElement) {",
    "      watchModeStrictOnAction.hidden = !protectedShellUnlocked;",
    "      watchModeStrictOnAction.disabled = false;",
    "    }",
    "    if (watchModeStrictOffAction instanceof HTMLButtonElement) {",
    "      watchModeStrictOffAction.hidden = !protectedShellUnlocked;",
    "      watchModeStrictOffAction.disabled = false;",
    "    }",
    "    if (watchModeCopyCommand instanceof HTMLButtonElement) {",
    "      watchModeCopyCommand.hidden = !protectedShellUnlocked;",
    "      watchModeCopyCommand.disabled = false;",
    "    }",
    "    if (watchModePauseAction instanceof HTMLButtonElement) {",
    "      watchModePauseAction.hidden = true;",
    "    }",
    "    if (watchModeResumeAction instanceof HTMLButtonElement) {",
    "      watchModeResumeAction.hidden = true;",
    "    }",
    "    if (watchModeStopAction instanceof HTMLButtonElement) {",
    "      watchModeStopAction.hidden = true;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const policy = snapshot.policy || {};",
    "  const pendingApprovals = Number(run?.pendingApprovalCount ?? summary.pendingApprovals ?? 0) || 0;",
    "  const activeStatus = normalizeText(run?.status) || normalizeText(summary.lastStatus) || 'idle';",
    "  const allowlistMode = normalizeText(run?.allowlist?.mode) || 'guarded';",
    "  setCardEmphasis(",
    "    watchModeCard,",
    "    pendingApprovals > 0 || activeStatus === 'waiting_approval' || activeStatus === 'running'",
    "      - 'focus'",
    "      : 'subtle',",
    "  );",
    "  setText(watchModeState, activeStatus);",
    "  setText(",
    "    watchModeSummary,",
    "    run",
    "      - ((normalizeText(run?.targetWindow) || 'window') + ' | ' + (normalizeText(run?.objective) || 'objetivo blank'))",
    "      : 'No run visual active in the momento.',",
    "  );",
    "  setText(",
    "    watchModePolicyState,",
    "    policy.strictApprovalDefault === false ? 'allowlist first' : 'strict approval',",
    "  );",
    "  setText(",
    "    watchModePolicySummary,",
    "    'Apps allowlisted: ' + String((policy.allowedApps || []).length || 0)",
    "      + ' | sites allowlisted: ' + String((policy.allowedSites || []).length || 0)",
    "      + ' | modo current: ' + allowlistMode,",
    "  );",
    "  setText(watchModeApprovalState, pendingApprovals > 0 ? String(pendingApprovals) + ' pending(s)' : 'Queue clear');",
    "  setText(",
    "    watchModeApprovalSummary,",
    "    pendingApprovals > 0",
    "      - 'Revise o screenshot current and decida os handoffs before of the next action.'",
    "      : 'No approval pending in this momento.',",
    "  );",
    "  setText(watchModeReplayState, run?.latestScreenshotPath ? 'screenshot ready' : 'without screenshot');",
    "  setText(",
    "    watchModeReplaySummary,",
    "    run?.timeline?.length",
    "      - 'Timeline recente: ' + String(run.timeline.length) + ' evento(s) auditaveis.'",
    "      : 'No replay visual registrado ainda.',",
    "  );",
    "  setText(",
    "    watchModeStatus,",
    "    normalizeText(run?.lastError) || normalizeText(run?.nextOperatorStep) || 'Supervised Watch Mode ready.',",
    "  );",
    "  setText(watchModeNextStep, normalizeText(run?.nextOperatorStep) || 'No run active ainda.');",
    "  renderList(watchModeApprovals, buildWatchModeApprovalItems(run));",
    "  renderList(watchModeTimeline, buildWatchModeTimelineItems(run));",
    "",
    "  if (watchModePreview instanceof HTMLImageElement) {",
    "    const runId = normalizeText(run?.runId);",
    "    if (runId && run?.latestScreenshotPath) {",
    "      watchModePreview.src = '/api/web/watch-mode/runs/' + encodeURIComponent(runId) + '/screenshot...ts=' + Date.now();",
    "      watchModePreview.hidden = false;",
    "      if (watchModePreviewEmpty instanceof HTMLElement) {",
    "        watchModePreviewEmpty.hidden = true;",
    "      }",
    "    } else {",
    "      watchModePreview.hidden = true;",
    "      watchModePreview.removeAttribute('src');",
    "      if (watchModePreviewEmpty instanceof HTMLElement) {",
    "        watchModePreviewEmpty.hidden = false;",
    "      }",
    "    }",
    "  }",
    "",
    "  if (watchModeStartAction instanceof HTMLButtonElement) {",
    "    watchModeStartAction.hidden = !protectedShellUnlocked;",
    "    watchModeStartAction.disabled = activeStatus === 'running' || activeStatus === 'paused' || activeStatus === 'waiting_approval';",
    "  }",
    "  if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "    watchModeRefreshAction.hidden = !protectedShellUnlocked;",
    "    watchModeRefreshAction.disabled = false;",
    "  }",
    "  if (watchModeAllowAppAction instanceof HTMLButtonElement) {",
    "    watchModeAllowAppAction.hidden = !protectedShellUnlocked;",
    "    watchModeAllowAppAction.disabled = !normalizeText(run?.targetWindow) && !normalizeText(watchModeTargetWindow?.value);",
    "  }",
    "  if (watchModeAllowSiteAction instanceof HTMLButtonElement) {",
    "    watchModeAllowSiteAction.hidden = !protectedShellUnlocked;",
    "    watchModeAllowSiteAction.disabled = !normalizeText(run?.siteUrl) && !normalizeText(watchModeSiteUrl?.value);",
    "  }",
    "  if (watchModeStrictOnAction instanceof HTMLButtonElement) {",
    "    watchModeStrictOnAction.hidden = !protectedShellUnlocked;",
    "    watchModeStrictOnAction.disabled = policy.strictApprovalDefault !== false;",
    "  }",
    "  if (watchModeStrictOffAction instanceof HTMLButtonElement) {",
    "    watchModeStrictOffAction.hidden = !protectedShellUnlocked;",
    "    watchModeStrictOffAction.disabled = policy.strictApprovalDefault === false;",
    "  }",
    "  if (watchModeCopyCommand instanceof HTMLButtonElement) {",
    "    watchModeCopyCommand.hidden = !protectedShellUnlocked;",
    "    watchModeCopyCommand.disabled = false;",
    "  }",
    "  if (watchModePauseAction instanceof HTMLButtonElement) {",
    "    watchModePauseAction.hidden = !protectedShellUnlocked || !run;",
    "    watchModePauseAction.disabled = activeStatus !== 'running';",
    "  }",
    "  if (watchModeResumeAction instanceof HTMLButtonElement) {",
    "    watchModeResumeAction.hidden = !protectedShellUnlocked || !run;",
    "    watchModeResumeAction.disabled = activeStatus !== 'paused';",
    "  }",
    "  if (watchModeStopAction instanceof HTMLButtonElement) {",
    "    watchModeStopAction.hidden = !protectedShellUnlocked || !run;",
    "    watchModeStopAction.disabled = !(activeStatus === 'running' || activeStatus === 'paused' || activeStatus === 'waiting_approval');",
    "  }",
    "}",
    "",
    "function renderSystemOverlordPanel(payload = null) {",
    "  if (payload !== null) {",
    "    systemOverlordData = payload;",
    "  }",
    "  const snapshot = systemOverlordData?.snapshot || null;",
    "  const errorMessage = normalizeText(systemOverlordData?.error);",
    "",
    "  if (!snapshot) {",
    "    setText(systemOverlordState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      systemOverlordSummary,",
    "      errorMessage || (",
    "        protectedShellUnlocked",
    "          - 'System Overlord control plane unavailable in this runtime.'",
    "          : 'O control plane supervised aparece here assim que o shell protegido for liberado.'",
    "      ),",
    "    );",
    "    setText(systemOverlordAutonomyState, 'Niveis 1-6');",
    "    setText(systemOverlordAutonomySummary, 'diagnostic, patch, build/test/install, host, desktop/browser and owner supervised.');",
    "    setText(systemOverlordAdaptersState, protectedShellUnlocked ? 'Unavailable' : 'Waiting');",
    "    setText(systemOverlordAdaptersSummary, 'Browser, desktop and computer-use aparecem when it isem registrados in the gateway.');",
    "    setText(systemOverlordKillSwitchState, protectedShellUnlocked ? 'Unavailable' : 'Protegido');",
    "    setText(systemOverlordKillSwitchSummary, 'Blocks new actions and helps cancel whatever is still active.');",
    "    setText(systemOverlordStatus, errorMessage || 'Validate the token to review o System Overlord supervised from this host.');",
    "    renderList(systemOverlordApprovals, [errorMessage || 'Validate the token to see pending approvals.']);",
    "    renderList(systemOverlordCapabilities, [errorMessage || 'Validate the token to see capabilities and risk.']);",
    "    renderList(systemOverlordActions, ['Validate the token to see the recent action ledger.']);",
    "    if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "      systemOverlordRefreshAction.hidden = !protectedShellUnlocked;",
    "    }",
    "    if (systemOverlordKillSwitchEnable instanceof HTMLButtonElement) {",
    "      systemOverlordKillSwitchEnable.hidden = !protectedShellUnlocked;",
    "    }",
    "    if (systemOverlordKillSwitchRelease instanceof HTMLButtonElement) {",
    "      systemOverlordKillSwitchRelease.hidden = !protectedShellUnlocked;",
    "    }",
    "    if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "      systemOverlordRunAction.hidden = !protectedShellUnlocked;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const profiles = Array.isArray(snapshot.profiles) ? snapshot.profiles : [];",
    "  const levels = Array.isArray(snapshot.autonomyLevels) ? snapshot.autonomyLevels : [];",
    "  const capabilities = Array.isArray(snapshot.capabilities) ? snapshot.capabilities : [];",
    "  const adapters = Array.isArray(snapshot.adapters) ? snapshot.adapters : [];",
    "  const killSwitch = snapshot.killSwitch || null;",
    "  const approvalQueue = Array.isArray(snapshot.approvalQueue) ? snapshot.approvalQueue : [];",
    "  const actions = Array.isArray(snapshot.recentActions) ? snapshot.recentActions : [];",
    "  const running = Number(summary.runningActions || 0) || actions.filter((action) => normalizeText(action?.status) === 'running').length;",
    "  const pending = Number(summary.pendingApprovals || 0) || 0;",
    "  const blocked = Number(summary.blockedActions || 0) || 0;",
    "  const failed = Number(summary.failedActions || 0) || 0;",
    "  const timedOut = Number(summary.timedOutActions || 0) || actions.filter((action) => normalizeText(action?.status) === 'timed_out').length;",
    "  const completed = Number(summary.completedActions || 0) || 0;",
    "  const attention = pending + blocked + failed + timedOut;",
    "  const highRiskCount = capabilities.filter((entry) =>",
    "    normalizeText(entry?.riskLevel) === 'critical' || normalizeText(entry?.riskLevel) === 'high'",
    "  ).length;",
    "",
    "  setCardEmphasis(systemOverlordCard, attention > 0 ? 'focus' : 'subtle');",
    "  setText(",
    "    systemOverlordState,",
    "    killSwitch?.active",
    "      - 'Kill switch'",
    "      : attention > 0",
    "        - 'Atencao'",
    "        : running > 0",
    "          - 'Executando'",
    "          : 'Ready',",
    "  );",
    "  setText(",
    "    systemOverlordSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary)",
    "      || String(summary.capabilities || capabilities.length) + ' capability(s), '",
    "      + String(summary.adapters || adapters.length) + ' adapter(s) and '",
    "      + String(summary.recentActions || actions.length) + ' action(oes) recentes.',",
    "  );",
    "  setText(",
    "    systemOverlordAutonomyState,",
    "    String(levels.length || 6) + ' niveis | ' + String(profiles.length || 4) + ' profiles',",
    "  );",
    "  setText(",
    "    systemOverlordAutonomySummary,",
    "    profiles.map((entry) => normalizeText(entry?.profile)).filter(Boolean).join(', ')",
    "      || 'safe, trusted, dangerous and owner with limites de autonomia 1-6.',",
    "  );",
    "  setText(",
    "    systemOverlordAdaptersState,",
    "    adapters.length ? String(adapters.length) + ' registered' : 'No adapters',",
    "  );",
    "  setText(",
    "    systemOverlordAdaptersSummary,",
    "    adapters.map((entry) => normalizeText(entry?.label || entry?.id)).filter(Boolean).slice(0, 4).join(', ')",
    "      || 'No adapter supervised registrado in the gateway current.',",
    "  );",
    "  setText(systemOverlordKillSwitchState, killSwitch?.active ? 'Active' : 'Released');",
    "  setText(",
    "    systemOverlordKillSwitchSummary,",
    "    killSwitch?.active",
    "      - (normalizeText(killSwitch?.reason) || 'new actions are blocked ate liberaction manual.')",
    "      : running > 0",
    "        - String(running) + ' supervised action(s) are still running.'",
    "        : 'Bloqueia new actions and pode cancelar o que still estiver active.',",
    "  );",
    "  setText(",
    "    systemOverlordStatus,",
    "    killSwitch?.active",
    "      - 'Kill switch supervised active. new actions ficam blocked ate liberaction manual.'",
    "      : attention > 0",
    "      - String(pending) + ' approval(s), ' + String(blocked) + ' block(s), ' + String(failed) + ' failure(s) and ' + String(timedOut) + ' timeout(s) recentes.'",
    "      : running > 0",
    "        - String(running) + ' action(oes) supervised(s) still are rodando.'",
    "        : 'Control plane supervised ready. ' + String(completed) + ' action(oes) concluidas in the ledger recente.'",
    "  );",
    "",
    "  renderList(",
    "    systemOverlordApprovals,",
    "    approvalQueue.slice(0, 5).map((item) =>",
    "      '<strong>' + escapeHtml(item?.capability || 'approval') + '</strong>: '",
    "      + escapeHtml(item?.reason || 'Aprovpending action.')",
    "      + ' <span class=\"muted-inline\">['",
    "      + escapeHtml(item?.riskLevel || 'risk n/a')",
    "      + ' | profile ' + escapeHtml(item?.requiredProfile || 'n/a')",
    "      + ' | level ' + escapeHtml(item?.requiredAutonomyLevel || 'n/a')",
    "      + ']</span>'",
    "      + '<div class=\"inline-action-row\">'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-overlord-approval=\"approve-dry-run\" data-overlord-action-id=\"' + escapeHtml(item?.actionId || '') + '\">Approve dry-run</button>'",
    "      + '<button type=\"button\" class=\"action-button compact-action\" data-overlord-approval=\"approve-run\" data-overlord-action-id=\"' + escapeHtml(item?.actionId || '') + '\">Approve run</button>'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-overlord-approval=\"reject\" data-overlord-action-id=\"' + escapeHtml(item?.actionId || '') + '\">Reject</button>'",
    "      + '</div>'",
    "    ).concat(",
    "      approvalQueue.length === 0",
    "        - ['No pending approvals in the System Overlord.']",
    "        : approvalQueue.length > 5",
    "          - ['+' + String(approvalQueue.length - 5) + ' approval(s) outside the short summary.']",
    "          : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    systemOverlordCapabilities,",
    "    capabilities.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || entry?.capability || 'Capability') + '</strong>: '",
    "      + escapeHtml(entry?.riskLevel || 'risk n/d')",
    "      + ' | profile ' + escapeHtml(entry?.requiredProfile || 'n/d')",
    "      + ' | autonomia ' + escapeHtml(entry?.requiredAutonomyLevel || 'n/d')",
    "      + ' | runtime ' + escapeHtml(entry?.runtimeTarget || 'n/d')",
    "    ).concat(",
    "      capabilities.length > 8",
    "        - ['+' + String(capabilities.length - 8) + ' capability(s) outside of the short summary.']",
    "        : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    systemOverlordActions,",
    "    actions.slice(0, 6).map((action) =>",
    "      '<strong>' + escapeHtml(action?.status || 'action') + '</strong>: '",
    "      + escapeHtml(action?.request?.capability || 'capability n/d')",
    "      + ' | ' + escapeHtml(action?.command || action?.errorMessage || action?.decision?.reason || 'without command')",
    "      + buildSystemOverlordActionControls(action)",
    "    ).concat(",
    "      actions.length === 0",
    "        - ['without recent actions in the ledger supervised.']",
    "        : highRiskCount > 0",
    "          - [String(highRiskCount) + ' high/critical-risk capability(s) are available only with policy and approval.']",
    "          : []",
].join('\n');
