export const runtimeShellScriptPart3Seg1: string = [
    "  );",
    "  setText(",
    "    sessionWorkspaceSelfmodSummary,",
    "    Array.isArray(selfmodPlane?.recentPlans) && selfmodPlane.recentPlans.length > 0",
    "      ? 'Preview, apply e rollback recentes do selfmod visiveis nesta sessao.'",
    "      : 'Nenhum preview ou rollback de selfmod associado a esta sessao agora.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceResourcesState,",
    "    resourcePlane?.host",
    "      ? escapeHtml(normalizeText(resourcePlane.host.pressure || 'unknown'))",
    "      : 'Sem leitura',",
    "  );",
    "  setText(",
    "    sessionWorkspaceResourcesSummary,",
    "    resourcePlane?.host",
    "      ? formatSessionWorkspaceMb(resourcePlane.host.usedPhysicalMemoryMb) + '/' + formatSessionWorkspaceMb(resourcePlane.host.totalVisibleMemoryMb)",
    "        + ' MB | top consumers e acoes seguras aparecem abaixo.'",
    "      : 'Desktop Resource Plane indisponivel neste host agora.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceCompanionsState,",
    "    Array.isArray(companionPlane?.companions) && companionPlane.companions.length > 0",
    "      ? String(companionPlane.companions.filter((entry) => normalizeText(entry?.status) === 'running').length) + ' ativo(s)'",
    "      : 'Sem leitura',",
    "  );",
    "  setText(",
    "    sessionWorkspaceCompanionsSummary,",
    "    Array.isArray(companionPlane?.companions) && companionPlane.companions.length > 0",
    "      ? String(companionPlane.companions.length) + ' companion(s) observados com status e acoes supervisionadas.'",
    "      : 'Companion Control Plane indisponivel neste host agora.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceHealthState,",
    "    runtimeWarnings.length > 0 ? String(runtimeWarnings.length) + ' warning(s)' : 'Estavel',",
    "  );",
    "  setText(",
    "    sessionWorkspaceHealthSummary,",
    "    runtimeWarnings.length > 0",
    "      ? 'Warnings canonicos e proximas acoes priorizadas aparecem abaixo.'",
    "      : actionRecommendations.length > 0",
    "        ? 'Sem warnings fortes; ainda assim ha acoes seguras recomendadas para este host.'",
    "        : 'Runtime sem warnings relevantes nesta sessao agora.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceStatus,",
    "    continuityReason",
    "      || handoffHeadline",
    "      || 'Atualize este workspace para rever sessao ativa, approvals e replay sem abrir o painel legado.',",
    "  );",
    "  setText(",
    "    sessionWorkspaceSummary,",
    "    'chat ' + chatId + ' | ' + counts.taskCount + ' tarefa(s) | ' + counts.toolRuns + ' tool run(s) | ' + counts.pendingPermissions + ' approval(s) em aberto | ' + runtimeWarnings.length + ' warning(s) | ' + counts.linkedSurfaces + ' superficie(s) ligada(s).',",
    "  );",
    "",
    "  const items = [",
    "      '<strong>Sessao:</strong> ' + sessionId + ' | ' + chatId + '.',",
    "    formatWorkspaceCount('Tarefas', counts.taskCount),",
    "    formatWorkspaceCount('Approvals', counts.pendingPermissions),",
    "    formatWorkspaceCount('Workflows', counts.workflowRuns),",
    "    formatWorkspaceCount('Tool runs', counts.toolRuns),",
    "    formatWorkspaceCount('Arquivos tocados', counts.filesTouched),",
    "    formatWorkspaceCount('Sessoes visiveis', counts.sessionsTotal),",
    "    formatWorkspaceCount('Superficies ligadas', counts.linkedSurfaces),",
    "  ];",
    "",
    "  if (focusTask) {",
    "    items.push('<strong>Foco atual:</strong> ' + escapeHtml(focusTask?.summary || focusTask?.shortId || focusTask?.taskId || 'Task dominante.'));",
    "  }",
    "  if (continuityReason) {",
    "    items.push('<strong>Continuidade:</strong> ' + escapeHtml(continuityReason));",
    "  }",
    "  if (sessionOptions.length > 1) {",
    "    items.push('<strong>Sessoes recentes:</strong> escolha uma sessao para reidratar sem recarregar a pagina.');",
    "    items.push(buildOperationalSelectorHtml('session-workspace', sessionOptions, sessionId));",
    "  }",
    "  items.push(",
    "    tools.length > 0",
    "      ? '<strong>Session tools:</strong> ' + escapeHtml(formatSessionToolList(tools)) + '.'",
    "      : '<strong>Session tools:</strong> o gateway resolve sessions, history, send e spawn por este plano.',",
    "  );",
    "  if (historyPayload?.sessionPlane?.narrative?.operatorSummary) {",
    "    items.push('<strong>Resumo do operador:</strong> ' + escapeHtml(historyPayload.sessionPlane.narrative.operatorSummary));",
    "  }",
    "",
    "  renderList(sessionWorkspaceDetails, items);",
    "  renderList(",
    "    sessionWorkspaceApprovals,",
    "    approvalItems.items.length > 0 ? approvalItems.items : ['Nenhuma permissao ou task gate pendente nesta sessao.'],",
    "  );",
    "  const replayItems = buildSessionWorkspaceReplayItems(replay, handoff, continuity);",
    "  renderList(",
    "    sessionWorkspaceReplay,",
    "    replayItems.length > 0 ? replayItems : ['Sem replay ou handoff relevantes para mostrar agora.'],",
    "  );",
    "  renderList(",
    "    sessionWorkspaceTools,",
    "    buildSessionWorkspaceToolItems(toolRuns),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceDiffs,",
    "    buildSessionWorkspaceDiffItems(toolRuns),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceCapabilities,",
    "    buildSessionWorkspaceCapabilityItems(capabilityPlane),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceSelfmod,",
    "    buildSessionWorkspaceSelfmodItems(selfmodPlane),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceResources,",
    "    buildSessionWorkspaceResourceItems(resourcePlane, actionRecommendations),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceCompanions,",
    "    buildSessionWorkspaceCompanionItems(companionPlane),",
    "  );",
    "  renderList(",
    "    sessionWorkspaceHealth,",
    "    buildSessionWorkspaceHealthItems(runtimeWarnings, actionRecommendations),",
    "  );",
    "  if (sessionWorkspaceAction instanceof HTMLButtonElement) {",
    "    sessionWorkspaceAction.hidden = false;",
    "    sessionWorkspaceAction.textContent = 'Atualizar workspace';",
    "  }",
    "}",
    "",
    "function renderOperatorCockpit() {",
    "  const runtimeLabel = normalizeText(runtimeStatus?.textContent || publicShellSnapshot.gatewayLabel || 'Verificando');",
    "  const keepaliveLabel = normalizeText(opsKeepaliveState?.textContent || '');",
    "  const channelSummary = operationalMeshData.channels?.channels?.summary || null;",
    "  const nodeSummary = operationalMeshData.nodes?.nodeMesh?.summary || null;",
    "  const transportSummary = operationalMeshData.transports?.transports?.summary || null;",
    "  const extensionSummary = operationalMeshData.extensions?.workspaceExtensions?.summary || null;",
    "  const pluginSummary = operationalMeshData.plugins?.plugins?.summary || null;",
    "  const hookSummary = operationalMeshData.hooks?.hooks?.summary || null;",
    "  const sessionId = readSessionWorkspaceSessionId();",
    "  const sessionPlaneSummary = sessionWorkspaceData.state?.sessionPlane?.summary",
    "    || sessionWorkspaceData.history?.sessionPlane?.summary",
    "    || null;",
    "  const resourcePlane = sessionWorkspaceData.state?.resourcePlane || sessionWorkspaceData.history?.resourcePlane || null;",
    "  const companionPlane = sessionWorkspaceData.state?.companionPlane || sessionWorkspaceData.history?.companionPlane || null;",
    "  const runtimeWarnings = Array.isArray(sessionWorkspaceData.state?.runtimeWarnings)",
    "    ? sessionWorkspaceData.state.runtimeWarnings",
    "    : Array.isArray(sessionWorkspaceData.history?.runtimeWarnings)",
    "      ? sessionWorkspaceData.history.runtimeWarnings",
    "      : [];",
    "  const actionRecommendations = Array.isArray(sessionWorkspaceData.state?.actionRecommendations)",
    "    ? sessionWorkspaceData.state.actionRecommendations",
    "    : Array.isArray(sessionWorkspaceData.history?.actionRecommendations)",
    "      ? sessionWorkspaceData.history.actionRecommendations",
    "      : [];",
    "  const sessionCounts = readSessionWorkspaceCounts(sessionWorkspaceData.state, sessionWorkspaceData.history);",
    "  const approvalItems = buildSessionWorkspaceApprovalItems(",
    "    Array.isArray(sessionWorkspaceData.history?.session?.permissions) ? sessionWorkspaceData.history.session.permissions : [],",
    "    Array.isArray(sessionWorkspaceData.history?.session?.tasks) ? sessionWorkspaceData.history.session.tasks : [],",
    "  );",
    "  const historyItems = Number(sessionPlaneSummary?.historyItems || 0) || 0;",
    "  const sessionsSendReady = Boolean(sessionPlaneSummary?.sendReady);",
    "  const sessionsSpawnReady = Boolean(sessionPlaneSummary?.spawnReady);",
    "  const workspaceCount = Number(extensionSummary?.workspaces || 0) || 0;",
    "  const pluginCount = Number(pluginSummary?.total || 0) || 0;",
    "  const hookCount = Number(hookSummary?.registeredHooks || 0) || 0;",
    "",
    "  setText(",
    "    cockpitRuntimeState,",
    "    keepaliveLabel === 'Atencao' || keepaliveLabel === 'Stale'",
    "      ? keepaliveLabel",
    "      : runtimeLabel,",
    "  );",
    "  setText(",
    "    cockpitRuntimeSummary,",
    "    channelSummary",
    "      ? 'Gateway ' + publicShellSnapshot.gatewayLabel",
    "        + ' | dominios ' + publicShellSnapshot.initializedDomains",
    "        + ' | channels ' + String(channelSummary.ready || 0) + '/' + String(channelSummary.total || 0)",
    "        + ' | keepalive ' + (keepaliveLabel || 'n/d')",
    "      : 'Gateway ' + publicShellSnapshot.gatewayLabel",
    "        + ' | dominios ' + publicShellSnapshot.initializedDomains",
    "        + ' | nodes ' + publicShellSnapshot.nodeCount",
    "        + ' | transports ' + publicShellSnapshot.transportCount,",
    "  );",
    "",
    "  if (!protectedShellUnlocked || !sessionId) {",
    "    setText(cockpitSessionsState, protectedShellUnlocked ? 'Sem sessao ativa' : 'Valide o token');",
    "    setText(",
    "      cockpitSessionsSummary,",
    "      protectedShellUnlocked",
    "        ? 'O host esta liberado, mas ainda nao existe uma sessao ativa resolvida para mostrar aqui.'",
    "        : 'A sessao ativa, o historico e o envio cruzado aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(cockpitApprovalsState, protectedShellUnlocked ? 'Sem sessao ativa' : 'Valide o token');",
    "    setText(",
    "      cockpitApprovalsSummary,",
    "      protectedShellUnlocked",
    "        ? 'A fila de approvals depende de uma sessao ativa resolvida neste host.'",
    "        : 'A fila de aprovacoes desta sessao aparece aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(cockpitResourcesState, protectedShellUnlocked ? 'Sem leitura' : 'Valide o token');",
    "    setText(",
    "      cockpitResourcesSummary,",
    "      protectedShellUnlocked",
    "        ? 'O Desktop Resource Plane ainda nao respondeu para este host.'",
    "        : 'Memoria, pressao do host e top consumers aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(cockpitCompanionsState, protectedShellUnlocked ? 'Sem leitura' : 'Valide o token');",
    "    setText(",
    "      cockpitCompanionsSummary,",
    "      protectedShellUnlocked",
    "        ? 'O Companion Control Plane ainda nao respondeu para este host.'",
    "        : 'WSL, Docker Desktop, ZavorthBridge e Codex aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(cockpitHealthState, protectedShellUnlocked ? 'Sem leitura' : 'Valide o token');",
    "    setText(",
    "      cockpitHealthSummary,",
    "      protectedShellUnlocked",
    "        ? 'Warnings e recomendacoes aparecem aqui quando a sessao ativa estiver resolvida.'",
    "        : 'Warnings de runtime e proximas acoes aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitSessionsState,",
    "      sessionCounts.sessionsTotal > 1",
    "        ? String(sessionCounts.sessionsTotal) + ' visiveis'",
    "        : '1 ativa',",
    "    );",
    "    setText(",
    "      cockpitSessionsSummary,",
    "      String(sessionCounts.taskCount) + ' tarefa(s) | historico ' + String(historyItems)",
    "      + ' | enviar ' + (sessionsSendReady ? 'pronto' : 'parcial')",
    "      + ' | spawn ' + (sessionsSpawnReady ? 'pronto' : 'parcial'),",
    "    );",
    "    setText(",
    "      cockpitApprovalsState,",
    "      approvalItems.total > 0 ? String(approvalItems.total) + ' pendente(s)' : 'Sem pendencias',",
    "    );",
    "    setText(",
    "      cockpitApprovalsSummary,",
    "      approvalItems.total > 0",
    "        ? String(approvalItems.permissions) + ' permissao(oes) e ' + String(approvalItems.tasks) + ' task gate(s) em aberto.'",
    "        : 'Nenhuma permissao ou task gate pendente na sessao ativa agora.',",
    "    );",
    "    setText(",
    "      cockpitResourcesState,",
    "      resourcePlane?.host ? String(resourcePlane.host.pressure || 'unknown') : 'Sem leitura',",
    "    );",
    "    setText(",
    "      cockpitResourcesSummary,",
    "      resourcePlane?.host",
    "        ? formatSessionWorkspaceMb(resourcePlane.host.usedPhysicalMemoryMb) + '/' + formatSessionWorkspaceMb(resourcePlane.host.totalVisibleMemoryMb)",
    "          + ' MB | ' + String((Array.isArray(resourcePlane.topConsumers) ? resourcePlane.topConsumers.length : 0)) + ' top consumer(s).'",
    "        : 'Desktop Resource Plane indisponivel neste host agora.',",
    "    );",
    "    setText(",
    "      cockpitCompanionsState,",
    "      Array.isArray(companionPlane?.companions)",
    "        ? String(companionPlane.companions.filter((entry) => normalizeText(entry?.status) === 'running').length) + ' ativo(s)'",
    "        : 'Sem leitura',",
    "    );",
    "    setText(",
    "      cockpitCompanionsSummary,",
    "      Array.isArray(companionPlane?.companions) && companionPlane.companions.length > 0",
    "        ? String(companionPlane.companions.length) + ' companion(s) | '",
    "          + String(companionPlane.companions.filter((entry) => entry?.pressure === 'high' || entry?.pressure === 'critical').length)",
    "          + ' sob pressao.'",
    "        : 'Nenhum companion relevante apareceu neste host agora.',",
    "    );",
    "    setText(",
    "      cockpitHealthState,",
    "      runtimeWarnings.length > 0 ? String(runtimeWarnings.length) + ' warning(s)' : 'Estavel',",
    "    );",
    "    setText(",
    "      cockpitHealthSummary,",
    "      runtimeWarnings.length > 0",
    "        ? runtimeWarnings.slice(0, 2).join(' | ')",
    "        : actionRecommendations.length > 0",
    "          ? actionRecommendations.slice(0, 2).map((entry) => normalizeText(entry?.label || entry?.summary)).filter(Boolean).join(' | ')",
    "          : 'Sem warnings relevantes; cockpit pronto para operar.',",
    "    );",
    "  }",
    "",
    "  if (!protectedShellUnlocked || !nodeSummary) {",
    "    setText(cockpitNodesState, protectedShellUnlocked ? 'Sem nodes' : 'Valide o token');",
    "    setText(",
    "      cockpitNodesSummary,",
    "      protectedShellUnlocked",
    "        ? 'Nenhum Node Mesh protegido disponivel para resumir neste host agora.'",
    "        : 'O resumo da frota, do pairing e da fila do Node Mesh aparece aqui quando o shell protegido for liberado.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitNodesState,",
    "      nodeSummary.total ? String(nodeSummary.online || 0) + '/' + String(nodeSummary.total || 0) + ' online' : 'Sem nodes',",
    "    );",
    "    setText(",
    "      cockpitNodesSummary,",
    "      String(nodeSummary.paired || 0) + ' pareado(s) | fila ' + String(nodeSummary.queued || 0)",
    "      + ' | antigos ' + String(nodeSummary.staleQueued || 0),",
    "    );",
    "  }",
    "",
    "  if (!protectedShellUnlocked || !transportSummary) {",
    "    setText(cockpitTransportsState, protectedShellUnlocked ? 'Sem transportes' : 'Valide o token');",
    "    setText(",
    "      cockpitTransportsSummary,",
    "      protectedShellUnlocked",
    "        ? 'Nenhum plano remoto protegido disponivel para resumir neste host agora.'",
    "        : 'O resumo do plano remoto aparece aqui quando o shell protegido for liberado.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitTransportsState,",
    "      transportSummary.total ? String(transportSummary.ready || 0) + '/' + String(transportSummary.total || 0) + ' prontos' : 'Sem transportes',",
    "    );",
    "    setText(",
    "      cockpitTransportsSummary,",
    "      String(transportSummary.attentionRequired || 0) + ' com atencao | pendencias '",
    "      + String(transportSummary.pendingWork || 0) + ' | reachable ' + String(transportSummary.reachable || 0),",
    "    );",
    "  }",
    "",
    "  if (!protectedShellUnlocked || (!workspaceCount && !pluginCount && !hookCount && !extensionSummary)) {",
    "    setText(cockpitIntegrationsState, protectedShellUnlocked ? 'Sem integrations' : 'Valide o token');",
    "    setText(",
    "      cockpitIntegrationsSummary,",
    "      protectedShellUnlocked",
    "        ? 'Nenhum workspace, plugin ou hook carregado para resumir neste host agora.'",
    "        : 'Plugins, hooks e workspaces carregados aparecem aqui quando o shell protegido for liberado.',",
    "    );",
    "  } else {",
    "    setText(",
    "      cockpitIntegrationsState,",
    "      workspaceCount ? String(workspaceCount) + ' workspace(s)' : String(pluginCount) + ' plugin(s)',",
    "    );",
    "    setText(",
    "      cockpitIntegrationsSummary,",
    "      String(pluginCount) + ' plugin(s) | ' + String(hookCount) + ' hook(s) | '",
    "      + String(Number(extensionSummary?.commands || 0) || 0) + ' comando(s)',",
    "    );",
    "  }",
    "",
    "  setText(",
    "    operatorCockpitStatus,",
    "    protectedShellUnlocked",
    "      ? 'Use o action rail para atualizar o cockpit, copiar status/doctor ou saltar para sessions, resources, companions e health sem sair da ZavorthControl.'",
    "      : 'Valide o token para transformar este resumo em cockpit operacional completo.',",
    "  );",
    "}",
    "",
    "function buildSystemOverlordActionControls(action) {",
    "  const actionId = normalizeText(action?.actionId);",
    "  if (!actionId) {",
    "    return '';",
    "  }",
    "  const status = normalizeText(action?.status);",
    "  const controls = [];",
    "  if (status === 'running' || status === 'pending_approval' || status === 'dry_run') {",
    "    controls.push(",
    "      '<button type=\"button\" class=\"action-button secondary compact-action\" data-overlord-action-mode=\"cancel\" data-overlord-action-id=\"' + escapeHtml(actionId) + '\">Cancelar</button>',",
    "    );",
    "  }",
    "  if (status === 'completed' && action?.rollbackAvailable === true) {",
    "    controls.push(",
    "      '<button type=\"button\" class=\"action-button compact-action\" data-overlord-action-mode=\"rollback\" data-overlord-action-id=\"' + escapeHtml(actionId) + '\">Rollback</button>',",
    "    );",
    "  }",
    "  if (!controls.length) {",
    "    return '';",
    "  }",
    "  return '<div class=\"inline-action-row\">' + controls.join('') + '</div>';",
    "}",
    "",
    "function renderEvalControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    evalControlPlaneData = payload;",
    "  }",
    "  const snapshot = evalControlPlaneData?.evals || evalControlPlaneData?.snapshot || evalControlPlaneData || null;",
    "  const errorMessage = normalizeText(evalControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(evalControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(evalControlPlaneState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      evalControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        ? 'O painel de evals ainda nao respondeu neste runtime.'",
    "        : 'A leitura de evals operacionais aparece aqui quando o shell protegido for liberado.',",
    "    );",
    "    setText(evalControlPlaneScorecardsState, 'Sem leitura');",
    "    setText(evalControlPlaneScorecardsSummary, 'Rotas com melhor baseline e maior friccao aparecem aqui.');",
    "    setText(evalControlPlaneDatasetsState, 'Sem leitura');",
    "    setText(evalControlPlaneDatasetsSummary, 'Datasets operacionais e comparacoes aparecem aqui quando houver leitura.');",
    "    setText(evalControlPlaneCoverageState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(evalControlPlaneCoverageSummary, 'Tasks, approvals, workflows e artifacts que alimentam este painel aparecem aqui.');",
    "    setText(evalControlPlaneStatus, errorMessage || 'Valide o token para revisar scorecards, regressions e datasets deste host.');",
    "    renderList(evalControlPlaneScorecards, [errorMessage || 'Valide o token para ver scorecards e baselines do runtime.']);",
    "    renderList(evalControlPlaneRegressions, [errorMessage || 'Valide o token para ver regressions e gargalos desta janela.']);",
    "    renderList(evalControlPlaneDatasets, [errorMessage || 'Valide o token para revisar datasets operacionais, coverage e comparacoes.']);",
    "    if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      evalControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      evalControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const scorecards = Array.isArray(snapshot.scorecards) ? snapshot.scorecards : [];",
    "  const regressions = Array.isArray(snapshot.regressions) ? snapshot.regressions : [];",
    "  const datasets = Array.isArray(snapshot.datasets) ? snapshot.datasets : [];",
    "  const coverage = snapshot.coverage || {};",
    "  const comparisons = snapshot.comparisons || {};",
    "  const telemetry = snapshot.telemetry || {};",
    "  const history = snapshot.history || {};",
    "  const operatorSummary = normalizeText(snapshot?.narrative?.operatorSummary);",
    "",
    "  setCardEmphasis(evalControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(evalControlPlaneState, posture);",
    "  setText(",
    "    evalControlPlaneSummary,",
    "    operatorSummary",
    "      || 'Painel de evals operacionais atualizado.',",
    "  );",
    "  setText(",
    "    evalControlPlaneScorecardsState,",
    "    String(summary.scorecards || scorecards.length || 0) + ' scorecard(s)',",
    "  );",
    "  setText(",
    "    evalControlPlaneScorecardsSummary,",
    "    String(summary.healthyScorecards || 0)",
    "      + ' healthy | '",
    "      + String(summary.attentionScorecards || 0)",
    "      + ' attention | '",
    "      + String(summary.criticalScorecards || 0)",
    "      + ' critical',",
    "  );",
    "  setText(",
    "    evalControlPlaneDatasetsState,",
    "    String(summary.datasets || datasets.length || 0) + ' dataset(s)',",
    "  );",
    "  setText(",
    "    evalControlPlaneDatasetsSummary,",
    "    [",
    "      regressions.length > 0",
    "        ? 'Maior regressao: ' + normalizeText(regressions[0]?.label || 'sem rotulo')",
    "        : 'Sem regressions fortes no recorte atual.',",
    "      Number(history.entries || 0) > 0",
    "        ? 'Historico: ' + String(history.entries || 0) + ' janela(s)'",
    "        : 'Historico ainda em formacao.',",
    "    ].filter(Boolean).join(' | '),",
    "  );",
    "  setText(",
    "    evalControlPlaneCoverageState,",
    "    String(summary.telemetrySignals || 0)",
    "      + ' sinal(is) | traces '",
    "      + String(telemetry.traceCount || 0)",
    "      + ' | cost '",
    "      + String(summary.operatorCostState || 'low'),",
    "  );",
    "  setText(",
    "    evalControlPlaneCoverageSummary,",
    "    [",
    "      normalizeText(coverage.taskSignal),",
    "      normalizeText(coverage.workflowSignal),",
    "      normalizeText(telemetry.lastEventAt)",
    "        ? 'ultima trace em ' + normalizeText(telemetry.lastEventAt)",
    "        : 'sem trace recente',",
    "    ].filter(Boolean).join(' | '),",
    "  );",
    "  setText(",
    "    evalControlPlaneStatus,",
    "    normalizeText(history.recommendation)",
    "      || normalizeText(telemetry.recommendation)",
    "      || operatorSummary",
    "      || 'Evals operacionais atualizadas.',",
    "  );",
    "  renderList(",
    "    evalControlPlaneScorecards,",
    "    scorecards.slice(0, 6).map((entry) => {",
    "      const successRate = Math.round(Number(entry?.successRate || 0) * 100);",
    "      const frictionRate = Math.round(Number(entry?.frictionRate || 0) * 100);",
    "      return '<strong>'",
    "        + escapeHtml(normalizeText(entry?.label || 'Fluxo'))",
    "        + '</strong>: '",
    "        + escapeHtml(normalizeText(entry?.status || 'unknown'))",
    "        + ' | success '",
    "        + String(successRate)",
    "        + '% | friction '",
    "        + String(frictionRate)",
    "        + '%';",
    "    }).concat(",
    "      scorecards.length === 0 ? ['Sem scorecards suficientes neste recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    evalControlPlaneRegressions,",
    "    regressions.slice(0, 6).map((entry) => {",
    "      return '<strong>'",
    "        + escapeHtml(normalizeText(entry?.label || 'Regressao'))",
    "        + '</strong>: '",
    "        + escapeHtml(normalizeText(entry?.severity || 'medium'))",
    "        + ' | '",
    "        + escapeHtml(normalizeText(entry?.evidence || 'Sem evidencia resumida.'));",
    "    }).concat(",
    "      regressions.length === 0 ? ['Sem regressions destacadas nesta leitura.'] : [],",
    "    ),",
    "  );",
    "  const comparisonItems = []",
    "    .concat(",
    "      Array.isArray(comparisons.executors)",
    "        ? comparisons.executors.slice(0, 2).map((entry) => {",
    "            return '<strong>Executor:</strong> '",
    "              + escapeHtml(normalizeText(entry?.label || 'executor'))",
    "              + ' | '",
    "              + escapeHtml(normalizeText(entry?.note || 'Sem nota.'));",
    "          })",
    "        : [],",
    "    )",
    "    .concat(",
    "      Array.isArray(comparisons.surfaces)",
    "        ? comparisons.surfaces.slice(0, 2).map((entry) => {",
    "            return '<strong>Surface:</strong> '",
    "              + escapeHtml(normalizeText(entry?.label || 'surface'))",
    "              + ' | '",
    "              + escapeHtml(normalizeText(entry?.note || 'Sem nota.'));",
    "          })",
    "        : [],",
    "    );",
    "  const telemetryItems = []",
    "    .concat(",
    "      Array.isArray(telemetry.traces)",
    "        ? telemetry.traces.slice(0, 2).map((entry) => {",
    "            return '<strong>Trace:</strong> '",
    "              + escapeHtml(normalizeText(entry?.source || 'runtime'))",
    "              + ' | '",
    "              + escapeHtml(normalizeText(entry?.status || 'unknown'))",
    "              + ' | '",
    "              + String(entry?.eventCount || 0)",
    "              + ' evento(s)';",
    "          })",
    "        : [],",
    "    )",
    "    .concat(",
    "      Array.isArray(telemetry.topEventTypes)",
    "        ? telemetry.topEventTypes.slice(0, 2).map((entry) => {",
    "            return '<strong>Evento:</strong> '",
    "              + escapeHtml(normalizeText(entry?.label || 'telemetry'))",
    "              + ' | '",
    "              + String(entry?.count || 0)",
    "              + ' vez(es)';",
    "          })",
    "        : [],",
    "    )",
    "    .concat(",
    "      Array.isArray(history.trend)",
    "        ? history.trend.slice(-2).reverse().map((entry) => {",
    "            return '<strong>Baseline:</strong> '",
    "              + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "              + ' | regressions '",
    "              + String(entry?.regressions || 0)",
    "              + ' | traces '",
    "              + String(entry?.traceCount || 0);",
    "          })",
    "        : [],",
    "    );",
    "  renderList(",
    "    evalControlPlaneDatasets,",
    "    datasets.slice(0, 4).map((entry) => {",
    "      return '<strong>'",
    "        + escapeHtml(normalizeText(entry?.label || 'Dataset'))",
    "        + '</strong>: '",
    "        + String(entry?.sampleCount || 0)",
    "        + ' item(ns) | '",
    "        + escapeHtml(normalizeText(entry?.description || 'Sem descricao.'));",
    "    }).concat(",
    "      Array.isArray(coverage.notes)",
    "        ? coverage.notes.slice(0, 2).map((entry) => '<strong>Coverage:</strong> ' + escapeHtml(normalizeText(entry)))",
    "        : [],",
    "    ).concat(",
    "      telemetryItems,",
    "    ).concat(",
    "      comparisonItems.length ? comparisonItems : ['Sem comparacoes suficientes neste recorte.'],",
    "    ),",
    "  );",
    "  if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    evalControlPlaneRefreshAction.hidden = false;",
    "    evalControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderHubControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    hubControlPlaneData = payload;",
    "  }",
    "  const snapshot = hubControlPlaneData?.hub || hubControlPlaneData?.snapshot || hubControlPlaneData || null;",
    "  const errorMessage = normalizeText(hubControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
].join('\n');
