import { asErrorLike } from '../../../../../utils/errorLike';
export const runtimeShellScriptPart8Seg1: string = [
  '          return;',
  '        }',
  "        void copyTextWithFallback(value, 'Copy the command below:');",
  '        return;',
  '      }',
  '',
  '      const target = event.target instanceof HTMLElement',
  "        - event.target.closest('[data-operational-kind][data-operational-mode][data-target-id],[data-operational-kind][data-operational-action][data-operational-target]')",
  '        : null;',
  '      if (!(target instanceof HTMLButtonElement)) {',
  '        return;',
  '      }',
  '      event.preventDefault();',
  '      const kind = normalizeText(target.dataset.operationalKind);',
  '      const mode = normalizeText(target.dataset.operationalMode || target.dataset.operationalAction);',
  '      const targetId = normalizeText(target.dataset.targetId || target.dataset.operationalTarget);',
  '      const extra = normalizeText(target.dataset.operationalExtra);',
  '      if (!kind || !mode) {',
  '        return;',
  '      }',
  '      void runOperationalMeshInlineAction(kind, mode, targetId, extra);',
  '    });',
  '  }',
  '}',
  '',
  'async function runSessionWorkspaceAction() {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(sessionWorkspaceStatus, 'Validate the token before updating the session workspace.');",
  '    return;',
  '  }',
  '',
  '  if (!(sessionWorkspaceAction instanceof HTMLButtonElement)) {',
  '    return;',
  '  }',
  '',
  '  sessionWorkspaceAction.disabled = true;',
  '  try {',
  "    setText(sessionWorkspaceStatus, 'Atualizando active session, approvals e replay...');",
  "    const payload = await refreshSessionWorkspaceViaGateway(token, '', {",
  "      replayMode: 'full',",
  '    });',
  '    renderSessionWorkspace(payload);',
  '    setText(',
  '      sessionWorkspaceStatus,',
  '      pickFirstText([',
  '        payload?.state?.sessionPlane?.narrative?.operatorSummary,',
  '        payload?.history?.sessionPlane?.narrative?.operatorSummary,',
  '        payload?.history?.session?.handoff?.operatorSummary,',
  '        payload?.history?.session?.replay?.operatorSummary,',
  "      ], 'Workspace of the session atualizado.'),",
  '    );',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(sessionWorkspaceStatus, error instanceof Error ? err.message : String(error));',
  '  } finally {',
  '    sessionWorkspaceAction.disabled = false;',
  '  }',
  '}',
  '',
  'async function runSessionWorkspaceApprovalAction(kind, decision, identifier) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(sessionWorkspaceStatus, 'Validate the token before deciding session approvals.');",
  '    return;',
  '  }',
  '  if (!identifier) {',
  "    setText(sessionWorkspaceStatus, 'Approval without valid identifier.');",
  '    return;',
  '  }',
  '',
  '  try {',
  "    if (kind !== 'permission' && kind !== 'task') {",
  "      setText(sessionWorkspaceStatus, 'Approval type not supported in the shell.');",
  '      return;',
  '    }',
  '    const body = {',
  '      approvalId: identifier,',
  '      decision,',
  '      sessionId: readSessionWorkspaceSessionId() || undefined,',
  "      scope: 'once',",
  '    };',
  "    if (decision === 'approve') {",
  "      const approvalCode = window.prompt('Se is approval exigir PIN, informe agora. Pode deixar in branco.', '') || '';",
  '      if (approvalCode) {',
  '        body.approvalCode = approvalCode;',
  '      }',
  '    }',
  "    setText(sessionWorkspaceStatus, (decision === 'approve' ? 'Aprovando' : 'Rejeitando') + ' approval pending...');",
  '    if (gatewayControlSocket instanceof WebSocket && gatewayControlSocket.readyState === WebSocket.OPEN) {',
  "      await requestGatewayControlSocket('approval.resolve', body);",
  "    } else if (kind === 'permission') {",
  '      await postProtectedJson(',
  "        '/api/web/permissions/' + (decision === 'approve' ? 'approve' : 'reject'),",
  '        token,',
  '        {',
  '          permissionId: identifier,',
  '          sessionId: readSessionWorkspaceSessionId() || undefined,',
  '        },',
  '      );',
  '    } else {',
  '      await postProtectedJson(',
  "        '/api/web/tasks/' + (decision === 'approve' ? 'approve' : 'reject'),",
  '        token,',
  '        {',
  '          taskId: identifier,',
  '          sessionId: readSessionWorkspaceSessionId() || undefined,',
  '          approvalCode: body.approvalCode,',
  '        },',
  '      );',
  '    }',
  '',
  '    const payload = await refreshSessionWorkspaceViaGateway(token, readSessionWorkspaceSessionId(), {',
  "      replayMode: 'full',",
  '    });',
  '    renderSessionWorkspace(payload);',
  '    setText(',
  '      sessionWorkspaceStatus,',
  "      decision === 'approve'",
  "        - 'Approval registrada e workspace atualizado.'",
  "        : 'Rejeicao registrada e workspace atualizado.',",
  '    );',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(sessionWorkspaceStatus, error instanceof Error ? err.message : String(error));',
  '  }',
  '}',
  '',
  'async function runSessionWorkspaceToolDiffAction(runId) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(sessionWorkspaceStatus, 'Validate the token before reviewing the tool-run diff.');",
  '    return;',
  '  }',
  '  const sessionId = readSessionWorkspaceSessionId();',
  '  if (!sessionId) {',
  "    setText(sessionWorkspaceStatus, 'Session active unavailable for review diff.');",
  '    return;',
  '  }',
  '  const normalizedRunId = normalizeText(runId);',
  '  if (!normalizedRunId) {',
  "    setText(sessionWorkspaceStatus, 'Tool run without valid identifier.');",
  '    return;',
  '  }',
  '',
  '  try {',
  "    setText(sessionWorkspaceStatus, 'Carregando diff do tool run...');",
  '    const payload = gatewayControlSocket instanceof WebSocket && gatewayControlSocket.readyState === WebSocket.OPEN',
  "      - await requestGatewayControlSocket('artifact.diff', {",
  '          sessionId,',
  '          toolRunId: normalizedRunId,',
  '        })',
  '      : await fetchProtectedJsonOptional(',
  "          '/api/web/tool-runs/' + encodeURIComponent(normalizedRunId) + '/diff?sessionId=' + encodeURIComponent(sessionId),",
  '          token,',
  '        );',
  '    if (!payload?.ok) {',
  "      throw new Error(payload?.error || 'Could not load the diff for this tool run.');",
  '    }',
  '    const currentToolRuns = readSessionWorkspaceToolRuns(sessionWorkspaceData.state, sessionWorkspaceData.toolRuns);',
  '    renderList(sessionWorkspaceDiffs, [',
  "      '<strong>Diff de ' + escapeHtml(normalizedRunId) + '</strong>',",
  '      ...buildSessionToolDiffPreview(payload),',
  '      ...buildSessionWorkspaceDiffItems(currentToolRuns).slice(0, 3),',
  '    ]);',
  "    setText(sessionWorkspaceDiffsState, 'Diff loaded');",
  '    setText(',
  '      sessionWorkspaceDiffsSummary,',
  "      'Showing patch consolidado deste tool run. Refresh o workspace for return to the full summary.',",
  '    );',
  "    setText(sessionWorkspaceStatus, 'Diff do tool run loaded.');",
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(sessionWorkspaceStatus, error instanceof Error ? err.message : String(error));',
  '  }',
  '}',
  '',
  'async function runSessionWorkspaceCompanionAction(companionId, actionId, requiresApproval = false) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(sessionWorkspaceStatus, 'Validate the token before operating companions on this host.');",
  '    return;',
  '  }',
  '  const normalizedCompanionId = normalizeText(companionId);',
  '  const normalizedActionId = normalizeText(actionId);',
  '  if (!normalizedCompanionId || !normalizedActionId) {',
  "    setText(sessionWorkspaceStatus, 'Companion action invalid for este workspace.');",
  '    return;',
  '  }',
  '',
  '  try {',
  '    setText(',
  '      sessionWorkspaceStatus,',
  "      'Executando supervised action in ' + normalizedCompanionId + '...',",
  '    );',
  '    const payload = await postProtectedJson(',
  "      '/api/web/runtime/companions/' + encodeURIComponent(normalizedCompanionId) + '/actions',",
  '      token,',
  '      {',
  '        actionId: normalizedActionId,',
  "        requestedBy: 'web-operator',",
  '        dryRun: false,',
  '        force: requiresApproval === true ? false : undefined,',
  '      },',
  '    );',
  '    const result = payload?.result || payload;',
  '    const refreshed = await refreshSessionWorkspaceViaGateway(token, readSessionWorkspaceSessionId(), {',
  "      replayMode: 'full',",
  '    });',
  '    renderSessionWorkspace(refreshed);',
  '    setText(',
  '      sessionWorkspaceStatus,',
  '      normalizeText(result?.summary || result?.reason || payload?.error)',
  "        || ('Action ' + normalizedActionId + ' enviada for ' + normalizedCompanionId + '.'),",
  '    );',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(sessionWorkspaceStatus, error instanceof Error ? err.message : String(error));',
  '  }',
  '}',
  '',
  'async function runSessionWorkspaceSwitchAction(nextSessionId) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  const normalizedSessionId = normalizeText(nextSessionId);',
  '  if (!token || !normalizedSessionId) {',
  "    setText(sessionWorkspaceStatus, 'Session target invalid for reidrataction.');",
  '    return;',
  '  }',
  '',
  '  try {',
  "    setText(sessionWorkspaceStatus, 'Rehydrating the session selected by Gateway...');",
  '    const payload = await refreshSessionWorkspaceViaGateway(token, normalizedSessionId, {',
  '      activate: true,',
  "      replayMode: 'full',",
  '    });',
  '    renderSessionWorkspace(payload);',
  '    gatewayControlSocketSessionId = normalizedSessionId;',
  "    setText(sessionWorkspaceStatus, 'Session rehydrated without reloading the page.');",
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(sessionWorkspaceStatus, error instanceof Error ? err.message : String(error));',
  '  }',
  '}',
  '',
  'function buildReplayComparePrompt(replay) {',
  '  const timeline = Array.isArray(replay?.timeline) ? replay.timeline : [];',
  '  if (timeline.length === 0) {',
  "    return 'Compare the context of recent executions and point out what needs to be resumed now.';",
  '  }',
  '  const labels = timeline',
  '    .slice(0, 4)',
  '    .map((step) => normalizeText(step?.label || step?.id || step?.summary))',
  '    .filter(Boolean)',
  "    .join(' | ');",
  "  return 'Compare estes runs recentes: ' + labels + '. Foque in diferencas, entrega principal e next passo.';",
  '}',
  '',
  'async function runSessionWorkspaceReplayAction(action, promptValue, summaryValue) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(sessionWorkspaceStatus, 'Validate the token before operating replay and artifacts.');",
  '    return;',
  '  }',
  '  const sessionId = readSessionWorkspaceSessionId();',
  '  if (!sessionId) {',
  "    setText(sessionWorkspaceStatus, 'Session active unavailable for replay.');",
  '    return;',
  '  }',
  '',
  '  const replay = sessionWorkspaceData?.history?.session?.replay || null;',
  "  let seedMessage = '';",
  "  if (action === 'compare-runs') {",
  '    seedMessage = normalizeText(promptValue) || buildReplayComparePrompt(replay);',
  "  } else if (action === 'resume-artifact') {",
  "    const label = normalizeText(promptValue || 'recent artifact');",
  '    const summary = normalizeText(summaryValue);',
  "    seedMessage = ('Resume from artifact ' + label + '. ' + (summary ? ('Context: ' + summary + '.') : '')).trim();",
  "  } else if (action === 'resume-recommended') {",
  '    seedMessage = normalizeText(promptValue)',
  '      || normalizeText(replay?.recommendedEntry?.prompt)',
  '      || normalizeText(sessionWorkspaceData?.history?.session?.handoff?.handoffPrompt)',
  "      || 'Resume the main context and deliver the suggested next step.';",
  '  } else {',
  "    setText(sessionWorkspaceStatus, 'Action de replay no reconhecida.');",
  '    return;',
  '  }',
  '',
  "  const edited = window.prompt('Edit the resume prompt if needed:', seedMessage);",
  '  if (edited === null) {',
  '    return;',
  '  }',
  "  const finalMessage = String(edited || '').trim();",
  '  if (!finalMessage) {',
  "    setText(sessionWorkspaceStatus, 'Prompt vazio; nada foi enviado.');",
  '    return;',
  '  }',
  '',
  '  try {',
  "    setText(sessionWorkspaceStatus, 'Abrindo new session a partir do replay...');",
  "    const payload = await postProtectedJson('/api/web/gateway/sessions/spawn', token, {",
  '      sessionId,',
  '      message: finalMessage,',
  "      platform: 'web',",
  '    });',
  '    const newSessionId = normalizeText(payload?.spawn?.sessionId || payload?.sessionId);',
  '    setText(',
  '      sessionWorkspaceStatus,',
  '      newSessionId',
  "        - ('Session new session opened: ' + newSessionId + '.')",
  "        : 'Session new session opened from replay.',",
  '    );',
  '    const refreshed = await fetchSessionWorkspacePayload(token);',
  '    renderSessionWorkspace(refreshed);',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(sessionWorkspaceStatus, error instanceof Error ? err.message : String(error));',
  '  }',
  '}',
  '',
  'async function runLearningAction(actionId, candidateId) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(learningStatus, 'Validate the token before deciding learning-plane candidates.');",
  '    return;',
  '  }',
  '  if (!candidateId || !actionId) {',
  "    setText(learningStatus, 'Candidate ou action invalid for o learning plane.');",
  '    return;',
  '  }',
  '',
  "  setText(learningStatus, 'Aplicando ' + actionId + ' in ' + candidateId + '...');",
  '  try {',
  "    const payload = await postProtectedJson('/api/web/learning/actions', token, {",
  '      candidateId,',
  '      actionId,',
  '    });',
  '    await refreshProtectedShellState(token);',
  '    setText(',
  '      learningStatus,',
  '      pickFirstText([',
  '        payload?.execution?.summary,',
  "        'Learning updated successfully.',",
  "      ], 'Learning updated successfully.'),",
  '    );',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(learningStatus, error instanceof Error ? err.message : String(error));',
  '  }',
  '}',
  '',
  'async function runLayeredMemorySearch(options = {}) {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(memoryLayeredStatus, 'Validate the token before searching layered memory.');",
  '    return;',
  '  }',
  '  const query = normalizeText(options.query || memoryLayeredQuery?.value);',
  '  learningMemoryData.lastQuery = query;',
  '  if (!query) {',
  '    renderLayeredMemorySearchResults(null);',
  "    setText(memoryLayeredStatus, 'Enter a short query to consult episodes, facts, and procedures.');",
  '    return;',
  '  }',
  '',
  '  if (memoryLayeredSearchAction instanceof HTMLButtonElement) {',
  '    memoryLayeredSearchAction.disabled = true;',
  '  }',
  '  try {',
  "    setText(memoryLayeredStatus, 'Buscando recall in episodic, semantic e procedural memory...');",
  '    const payload = await fetchProtectedJsonOptional(',
  "      '/api/web/memory/search?q=' + encodeURIComponent(query),",
  '      token,',
  '    );',
  '    renderLayeredMemorySearchResults(payload?.search || null);',
  '    setText(',
  '      memoryLayeredStatus,',
  "      'Search completed for \"' + query + '\" com ' + String(Number(payload?.search?.total || 0)) + ' result(s).',",
  '    );',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    setText(memoryLayeredStatus, error instanceof Error ? err.message : String(error));',
  '  } finally {',
  '    if (memoryLayeredSearchAction instanceof HTMLButtonElement) {',
  '      memoryLayeredSearchAction.disabled = false;',
  '    }',
  '  }',
  '}',
  '',
  'async function refreshLearningMemoryPanels() {',
  '  const token = normalizeText(readStoredToken() || authInput?.value);',
  '  if (!token) {',
  "    setText(learningStatus, 'Validate the token before updating learning and memory.');",
  "    setText(memoryLayeredStatus, 'Validate the token before updating learning and memory.');",
  '    return;',
  '  }',
  '',
  '  if (learningRefreshAction instanceof HTMLButtonElement) {',
  '    learningRefreshAction.disabled = true;',
  '  }',
  '  if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {',
  '    memoryLayeredRefreshAction.disabled = true;',
  '  }',
  '  try {',
  "    setText(learningStatus, 'Atualizando learning, budgets e procedimentos...');",
  "    setText(memoryLayeredStatus, 'Atualizando learning, budgets e procedimentos...');",
  '    await refreshProtectedShellState(token);',
  '    if (normalizeText(memoryLayeredQuery?.value || learningMemoryData.lastQuery)) {',
  '      await runLayeredMemorySearch({',
  '        query: normalizeText(memoryLayeredQuery?.value || learningMemoryData.lastQuery),',
  '      });',
  '    }',
  '  } catch (error: unknown) { const err = asErrorLike(error); const e = err;',
  '    const message = error instanceof Error ? err.message : String(error);',
  '    setText(learningStatus, message);',
  '    setText(memoryLayeredStatus, message);',
  '  } finally {',
  '    if (learningRefreshAction instanceof HTMLButtonElement) {',
  '      learningRefreshAction.disabled = false;',
  '    }',
  '    if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {',
  '      memoryLayeredRefreshAction.disabled = false;',
  '    }',
  '  }',
  '}',
  '',
  'function installSessionWorkspaceInteractions() {',
  '  if (sessionWorkspaceAction instanceof HTMLButtonElement) {',
  "    sessionWorkspaceAction.addEventListener('click', () => {",
  '      void runSessionWorkspaceAction();',
  '    });',
  '  }',
  '',
  '  if (sessionWorkspaceCard instanceof HTMLElement) {',
  "    sessionWorkspaceCard.addEventListener('click', (event) => {",
  '      if (!(event.target instanceof Element)) {',
  '        return;',
  '      }',
  "      const copyButton = event.target.closest('[data-operational-copy]');",
  '      if (copyButton instanceof HTMLButtonElement) {',
  '        event.preventDefault();',
  '        const value = normalizeText(copyButton.dataset.operationalCopy);',
  '        if (value) {',
  "          void copyTextWithFallback(value, 'Copy the command below:');",
  '        }',
  '        return;',
  '      }',
  '      const selectorButton = event.target.closest(\'[data-operational-kind="session-workspace"][data-operational-action="select"]\');',
  '      if (selectorButton instanceof HTMLButtonElement) {',
  '        event.preventDefault();',
  '        void runSessionWorkspaceSwitchAction(',
  '          normalizeText(selectorButton.dataset.operationalTarget),',
  '        );',
  '        return;',
  '      }',
  "      const toolDiffButton = event.target.closest('[data-session-tool-diff]');",
  '      if (toolDiffButton instanceof HTMLButtonElement) {',
  '        event.preventDefault();',
  '        void runSessionWorkspaceToolDiffAction(',
  '          normalizeText(toolDiffButton.dataset.sessionToolDiff),',
  '        );',
  '        return;',
  '      }',
  "      const companionActionButton = event.target.closest('[data-session-companion-id][data-session-companion-action]');",
  '      if (companionActionButton instanceof HTMLButtonElement) {',
  '        event.preventDefault();',
  '        void runSessionWorkspaceCompanionAction(',
  '          normalizeText(companionActionButton.dataset.sessionCompanionId),',
  '          normalizeText(companionActionButton.dataset.sessionCompanionAction),',
  "          normalizeText(companionActionButton.dataset.sessionCompanionApproval) === 'true',",
  '        );',
  '        return;',
  '      }',
  "      const replayButton = event.target.closest('[data-session-replay-action]');",
  '      if (replayButton instanceof HTMLButtonElement) {',
  '        event.preventDefault();',
  '        void runSessionWorkspaceReplayAction(',
  '          normalizeText(replayButton.dataset.sessionReplayAction),',
  '          normalizeText(replayButton.dataset.sessionReplayPrompt),',
  '          normalizeText(replayButton.dataset.sessionReplaySummary),',
  '        );',
  '        return;',
  '      }',
  "      const button = event.target.closest('[data-session-approval-kind]');",
  '      if (!(button instanceof HTMLButtonElement)) {',
  '        return;',
  '      }',
  '      event.preventDefault();',
  '      void runSessionWorkspaceApprovalAction(',
  '        normalizeText(button.dataset.sessionApprovalKind),',
  '        normalizeText(button.dataset.sessionApprovalDecision),',
  '        normalizeText(button.dataset.sessionApprovalId),',
  '      );',
  '    });',
  '  }',
  '}',
  '',
  'function installLearningMemoryInteractions() {',
  '  if (learningRefreshAction instanceof HTMLButtonElement) {',
  "    learningRefreshAction.addEventListener('click', () => {",
  '      void refreshLearningMemoryPanels();',
  '    });',
  '  }',
  '',
  '  if (memoryLayeredRefreshAction instanceof HTMLButtonElement) {',
  "    memoryLayeredRefreshAction.addEventListener('click', () => {",
  '      void refreshLearningMemoryPanels();',
  '    });',
  '  }',
  '',
  '  if (memoryLayeredSearchAction instanceof HTMLButtonElement) {',
  "    memoryLayeredSearchAction.addEventListener('click', () => {",
  '      void runLayeredMemorySearch();',
  '    });',
  '  }',
  '',
  '  if (memoryLayeredQuery instanceof HTMLInputElement) {',
].join('\n');
