export const runtimeShellScriptPart4Seg2: string = [
    "      + escapeHtml(normalizeText(entry?.uploadStatus || 'historico'))",
    "      + (normalizeText(entry?.outputFile || entry?.bundlePath)",
    "        ? ' | ' + escapeHtml(normalizeText(entry?.outputFile || entry?.bundlePath))",
    "        : ''),",
    "    ).concat(",
    "      publishEntries.length === 0 ? ['Nenhum publish salvo ainda neste host.'] : [],",
    "    ),",
    "  );",
    "  if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    rolloutReadinessControlPlaneRefreshAction.hidden = false;",
    "    rolloutReadinessControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderTrustPlanePanel(payload = null) {",
    "  const snapshot = payload?.trustPlane || payload?.snapshot || payload || null;",
    "  const errorMessage = normalizeText(payload?.error);",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(trustPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(trustPlaneHostState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      trustPlaneHostSummary,",
    "      protectedShellUnlocked",
    "        ? 'O Trust Plane ainda nao respondeu neste runtime.'",
    "        : 'Approvals, kill switch e capabilities sensiveis aparecem aqui quando o shell protegido estiver liberado.',",
    "    );",
    "    setText(trustPlaneMcpState, 'Perfil safe');",
    "    setText(trustPlaneMcpSummary, 'O perfil MCP e a allowlist explicita aparecem aqui quando o runtime protegido estiver autenticado.');",
    "    setText(trustPlaneSkillsState, 'Policy deny');",
    "    setText(trustPlaneSkillsSummary, 'A policy de skills e o plugin plane trusted aparecem juntos aqui para evitar trust espalhado.');",
    "    setText(trustPlaneRuntimeState, protectedShellUnlocked ? 'Indisponivel' : 'Baseline');",
    "    setText(trustPlaneRuntimeSummary, 'O trust boundary do Runtime & Security Mesh aparece aqui de forma resumida para o operador.');",
    "    setText(trustPlaneStatus, errorMessage || 'Valide o token para revisar o Trust Plane oficial deste host.');",
    "    renderList(trustPlaneHighlights, [errorMessage || 'Valide o token para ver os principais riscos e bloqueios.']);",
    "    renderList(trustPlaneActions, [errorMessage || 'Valide o token para revisar os proximos passos do Trust Plane.']);",
    "    renderList(trustPlaneSurfaces, [errorMessage || 'Valide o token para ver host, MCP, skills, plugins e runtime numa leitura unica.']);",
    "    if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      trustPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      trustPlaneRefreshAction.disabled = false;",
    "    }",
    "    if (trustPlanePromoteTrustedAction instanceof HTMLButtonElement) {",
    "      trustPlanePromoteTrustedAction.hidden = !protectedShellUnlocked;",
    "      trustPlanePromoteTrustedAction.disabled = false;",
    "    }",
    "    if (trustPlaneHardenSafeAction instanceof HTMLButtonElement) {",
    "      trustPlaneHardenSafeAction.hidden = !protectedShellUnlocked;",
    "      trustPlaneHardenSafeAction.disabled = false;",
    "    }",
    "    if (trustPlaneSkillsDenyAction instanceof HTMLButtonElement) {",
    "      trustPlaneSkillsDenyAction.hidden = !protectedShellUnlocked;",
    "      trustPlaneSkillsDenyAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const surfaces = snapshot.surfaces || {};",
    "  const highlights = Array.isArray(snapshot.riskHighlights) ? snapshot.riskHighlights : [];",
    "  const actions = Array.isArray(snapshot.suggestedActions) ? snapshot.suggestedActions : [];",
    "  const host = surfaces.systemOverlord || {};",
    "  const mcp = surfaces.mcp || {};",
    "  const skills = surfaces.skills || {};",
    "  const plugins = surfaces.plugins || {};",
    "  const nodes = surfaces.nodes || {};",
    "  const runtime = surfaces.runtime || {};",
    "  const attention = Number(summary.pendingApprovals || 0)",
    "    + Number(summary.highRiskCapabilities || 0)",
    "    + (summary.killSwitchActive ? 2 : 0)",
    "    + highlights.filter((entry) => normalizeText(entry?.severity) === 'critical').length;",
    "",
    "  setCardEmphasis(trustPlaneCard, attention > 0 ? 'focus' : 'subtle');",
    "  setText(",
    "    trustPlaneHostState,",
    "    summary.killSwitchActive",
    "      ? 'Kill switch'",
    "      : Number(summary.pendingApprovals || 0) > 0",
    "        ? 'Approvals'",
    "        : 'Protegido',",
    "  );",
    "  setText(",
    "    trustPlaneHostSummary,",
    "    normalizeText(host.operatorSummary)",
    "      || String(summary.pendingApprovals || 0) + ' approval(s) e '",
    "      + String(summary.highRiskCapabilities || 0) + ' capability(s) sensiveis.',",
    "  );",
    "  setText(",
    "    trustPlaneMcpState,",
    "    String(mcp.profile || summary.mcpProfile || 'safe') + ' | ' + String(summary.mcpAllowedTools || 0) + ' tools',",
    "  );",
    "  setText(",
    "    trustPlaneMcpSummary,",
    "    normalizeText(mcp.operatorSummary)",
    "      || 'MCP sem resumo detalhado neste runtime.',",
    "  );",
    "  setText(",
    "    trustPlaneSkillsState,",
    "    String(skills.defaultPolicy || summary.skillDefaultPolicy || 'deny')",
    "      + ' | ' + String(summary.trustedPlugins || 0) + ' trusted',",
    "  );",
    "  setText(",
    "    trustPlaneSkillsSummary,",
    "    normalizeText(skills.operatorSummary)",
    "      || normalizeText(plugins.operatorSummary)",
    "      || 'Policy de skills e plugin plane sem resumo detalhado.',",
    "  );",
    "  setText(",
    "    trustPlaneRuntimeState,",
    "    String(runtime.posture || summary.posture || 'unknown'),",
    "  );",
    "  setText(",
    "    trustPlaneRuntimeSummary,",
    "    normalizeText(runtime.trustBoundary)",
    "      || normalizeText(runtime.operatorSummary)",
    "      || 'Runtime sem trust boundary detalhado.',",
    "  );",
    "  setText(",
    "    trustPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.operatorSummary)",
    "      || 'Trust Plane atualizado.',",
    "  );",
    "",
    "  renderList(",
    "    trustPlaneHighlights,",
    "    highlights.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || 'Risco') + '</strong>: '",
    "      + escapeHtml(entry?.summary || 'Sem resumo.')",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(entry?.severity || 'info') + ']</span>'",
    "    ).concat(",
    "      highlights.length === 0",
    "        ? ['Sem riscos destacados no resumo atual do Trust Plane.']",
    "        : highlights.length > 6",
    "          ? ['+' + String(highlights.length - 6) + ' risco(s) fora do resumo curto.']",
    "          : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    trustPlaneActions,",
    "    actions.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || 'Acao') + '</strong>: '",
    "      + escapeHtml(entry?.reason || 'Sem motivo detalhado.')",
    "      + (entry?.command",
    "        ? ' <span class=\"muted-inline\">[' + escapeHtml(entry.command) + ']</span>'",
    "        : '')",
    "    ).concat(",
    "      actions.length === 0",
    "        ? ['Sem acoes sugeridas no resumo atual do Trust Plane.']",
    "        : actions.length > 6",
    "          ? ['+' + String(actions.length - 6) + ' acao(oes) fora do resumo curto.']",
    "          : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    trustPlaneSurfaces,",
    "    [",
    "      '<strong>Host:</strong> ' + escapeHtml(normalizeText(host.operatorSummary || 'Sem resumo do host.')),",
    "      '<strong>MCP:</strong> ' + escapeHtml(",
    "        String(mcp.profile || 'safe') + ' | '",
    "        + String((mcp.allowedTools || []).length || summary.mcpAllowedTools || 0)",
    "        + ' tools | '",
    "        + String((mcp.allowlist || []).length || 0)",
    "        + ' allowlist',",
    "      ),",
    "      '<strong>Skills:</strong> ' + escapeHtml(",
    "        String(skills.defaultPolicy || 'deny') + ' | '",
    "        + String((skills.allowedSourceIds || []).length || summary.skillAllowedSources || 0)",
    "        + ' fontes | '",
    "        + String((skills.explicitRules || []).length || summary.explicitSkillRules || 0)",
    "        + ' regras explicitas',",
    "      ),",
    "      '<strong>Plugins:</strong> ' + escapeHtml(",
    "        String(plugins.trusted || summary.trustedPlugins || 0)",
    "        + ' trusted / '",
    "        + String(plugins.installed || summary.installedPlugins || 0)",
    "        + ' instalado(s)',",
    "      ),",
    "      '<strong>Nodes:</strong> ' + escapeHtml(",
    "        String(nodes.paired || summary.pairedNodes || 0)",
    "        + ' pareado(s) | '",
    "        + String(nodes.restricted || summary.restrictedNodes || 0)",
    "        + ' restrito(s)',",
    "      ),",
    "      '<strong>Runtime:</strong> ' + escapeHtml(normalizeText(runtime.trustBoundary || runtime.operatorSummary || 'Sem resumo do runtime.')),",
    "    ],",
    "  );",
    "",
    "  if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    trustPlaneRefreshAction.hidden = false;",
    "    trustPlaneRefreshAction.disabled = false;",
    "  }",
    "  if (trustPlanePromoteTrustedAction instanceof HTMLButtonElement) {",
    "    trustPlanePromoteTrustedAction.hidden = false;",
    "    trustPlanePromoteTrustedAction.disabled = normalizeText(mcp.profile || summary.mcpProfile || 'safe') === 'trusted';",
    "  }",
    "  if (trustPlaneHardenSafeAction instanceof HTMLButtonElement) {",
    "    trustPlaneHardenSafeAction.hidden = false;",
    "    trustPlaneHardenSafeAction.disabled = normalizeText(mcp.profile || summary.mcpProfile || 'safe') === 'safe';",
    "  }",
    "  if (trustPlaneSkillsDenyAction instanceof HTMLButtonElement) {",
    "    trustPlaneSkillsDenyAction.hidden = false;",
    "    trustPlaneSkillsDenyAction.disabled = normalizeText(skills.defaultPolicy || summary.skillDefaultPolicy || 'deny') === 'deny';",
    "  }",
    "}",
    "",
    "function buildWatchModeApprovalItems(run) {",
    "  const approvals = Array.isArray(run?.approvals)",
    "    ? run.approvals.filter((entry) => normalizeText(entry?.status) === 'pending').slice(0, 5)",
    "    : [];",
    "  if (!approvals.length) {",
    "    return ['Nenhum approval pendente no Watch Mode.'];",
    "  }",
    "  return approvals.map((approval) => {",
    "    const approvalId = normalizeText(approval?.approvalId);",
    "    const action = normalizeText(approval?.action?.action) || 'acao';",
    "    const target = normalizeText(approval?.action?.targetText || approval?.action?.payload || approval?.action?.windowTitle) || 'sem alvo textual';",
    "    return '<strong>' + escapeHtml(action) + ':</strong> ' + escapeHtml(target)",
    "      + ' <span class=\"muted-inline\">[' + escapeHtml(normalizeText(approval?.riskLevel) || 'risk') + ']</span>'",
    "      + '<div class=\"inline-action-row\">'",
    "      + '<button type=\"button\" class=\"action-button compact-action\" data-watch-mode-approval=\"approve\" data-watch-mode-approval-id=\"' + escapeHtml(approvalId) + '\">Aprovar</button>'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-watch-mode-approval=\"reject\" data-watch-mode-approval-id=\"' + escapeHtml(approvalId) + '\">Negar</button>'",
    "      + '</div>';",
    "  });",
    "}",
    "",
    "function buildWatchModeTimelineItems(run) {",
    "  const timeline = Array.isArray(run?.timeline) ? run.timeline.slice(0, 6) : [];",
    "  if (!timeline.length) {",
    "    return ['Nenhuma acao visual registrada ainda.'];",
    "  }",
    "  return timeline.map((entry) => {",
    "    const summary = normalizeText(entry?.summary) || 'Evento visual';",
    "    const createdAt = normalizeText(entry?.createdAt);",
    "    const type = normalizeText(entry?.type) || 'evento';",
    "    const result = normalizeText(entry?.result);",
    "    const parts = ['<strong>' + escapeHtml(type) + ':</strong> ' + escapeHtml(summary)];",
    "    if (createdAt) {",
    "      parts.push('<span class=\"muted-inline\">[' + escapeHtml(new Date(createdAt).toLocaleTimeString('en-US')) + ']</span>');",
    "    }",
    "    if (result) {",
    "      parts.push('<div class=\"muted-copy\">' + escapeHtml(result) + '</div>');",
    "    }",
    "    return parts.join(' ');",
    "  });",
    "}",
    "",
    "function renderWatchModePanel(payload = null) {",
    "  if (payload !== null) {",
    "    watchModeData = payload;",
    "  }",
    "  const snapshot = watchModeData?.snapshot || watchModeData?.watchMode?.watchMode || watchModeData?.watchMode || null;",
    "  const run = watchModeData?.run || snapshot?.activeRun || watchModeData?.activeRun || watchModeData?.watchMode?.watchMode?.activeRun || null;",
    "  const errorMessage = normalizeText(watchModeData?.error);",
    "",
    "  if (!snapshot) {",
    "    setCardEmphasis(watchModeCard, 'subtle');",
    "    setText(watchModeState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      watchModeSummary,",
    "      errorMessage || (",
    "        protectedShellUnlocked",
    "          ? 'Watch Mode supervisionado indisponivel neste runtime.'",
    "          : 'O run visual supervisionado aparece aqui assim que o shell protegido for liberado.'",
    "      ),",
    "    );",
    "    setText(watchModePolicyState, 'strict approval');",
    "    setText(watchModePolicySummary, 'Apps e sites em allowlist aparecem aqui junto com a policy de approvals.');",
    "    setText(watchModeApprovalState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(watchModeApprovalSummary, 'Toda acao mutavel da UI pede handoff antes de executar.');",
    "    setText(watchModeReplayState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(watchModeReplaySummary, 'Screenshot atual e timeline curta aparecem aqui quando o Watch Mode estiver ativo.');",
    "    setText(watchModeStatus, errorMessage || 'Valide o token para operar o Watch Mode supervisionado deste host.');",
    "    setText(watchModeNextStep, 'Nenhum run ativo ainda.');",
    "    renderList(watchModeApprovals, [errorMessage || 'Valide o token para revisar approvals visuais pendentes.']);",
    "    renderList(watchModeTimeline, ['Valide o token para revisar screenshots, acoes e handoffs do Watch Mode.']);",
    "    if (watchModePreview instanceof HTMLImageElement) {",
    "      watchModePreview.hidden = true;",
    "      watchModePreview.removeAttribute('src');",
    "    }",
    "    if (watchModePreviewEmpty instanceof HTMLElement) {",
    "      watchModePreviewEmpty.hidden = false;",
    "    }",
    "    if (watchModeStartAction instanceof HTMLButtonElement) {",
    "      watchModeStartAction.hidden = !protectedShellUnlocked;",
    "      watchModeStartAction.disabled = false;",
    "    }",
    "    if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "      watchModeRefreshAction.hidden = !protectedShellUnlocked;",
    "      watchModeRefreshAction.disabled = false;",
    "    }",
    "    if (watchModeAllowAppAction instanceof HTMLButtonElement) {",
    "      watchModeAllowAppAction.hidden = !protectedShellUnlocked;",
    "      watchModeAllowAppAction.disabled = true;",
    "    }",
    "    if (watchModeAllowSiteAction instanceof HTMLButtonElement) {",
    "      watchModeAllowSiteAction.hidden = !protectedShellUnlocked;",
    "      watchModeAllowSiteAction.disabled = true;",
    "    }",
    "    if (watchModeStrictOnAction instanceof HTMLButtonElement) {",
    "      watchModeStrictOnAction.hidden = !protectedShellUnlocked;",
    "      watchModeStrictOnAction.disabled = false;",
    "    }",
    "    if (watchModeStrictOffAction instanceof HTMLButtonElement) {",
    "      watchModeStrictOffAction.hidden = !protectedShellUnlocked;",
    "      watchModeStrictOffAction.disabled = false;",
    "    }",
    "    if (watchModeCopyCommand instanceof HTMLButtonElement) {",
    "      watchModeCopyCommand.hidden = !protectedShellUnlocked;",
    "      watchModeCopyCommand.disabled = false;",
    "    }",
    "    if (watchModePauseAction instanceof HTMLButtonElement) {",
    "      watchModePauseAction.hidden = true;",
    "    }",
    "    if (watchModeResumeAction instanceof HTMLButtonElement) {",
    "      watchModeResumeAction.hidden = true;",
    "    }",
    "    if (watchModeStopAction instanceof HTMLButtonElement) {",
    "      watchModeStopAction.hidden = true;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const policy = snapshot.policy || {};",
    "  const pendingApprovals = Number(run?.pendingApprovalCount ?? summary.pendingApprovals ?? 0) || 0;",
    "  const activeStatus = normalizeText(run?.status) || normalizeText(summary.lastStatus) || 'idle';",
    "  const allowlistMode = normalizeText(run?.allowlist?.mode) || 'guarded';",
    "  setCardEmphasis(",
    "    watchModeCard,",
    "    pendingApprovals > 0 || activeStatus === 'waiting_approval' || activeStatus === 'running'",
    "      ? 'focus'",
    "      : 'subtle',",
    "  );",
    "  setText(watchModeState, activeStatus);",
    "  setText(",
    "    watchModeSummary,",
    "    run",
    "      ? ((normalizeText(run?.targetWindow) || 'janela') + ' | ' + (normalizeText(run?.objective) || 'objetivo em branco'))",
    "      : 'Nenhum run visual ativo no momento.',",
    "  );",
    "  setText(",
    "    watchModePolicyState,",
    "    policy.strictApprovalDefault === false ? 'allowlist first' : 'strict approval',",
    "  );",
    "  setText(",
    "    watchModePolicySummary,",
    "    'Apps allowlisted: ' + String((policy.allowedApps || []).length || 0)",
    "      + ' | sites allowlisted: ' + String((policy.allowedSites || []).length || 0)",
    "      + ' | modo atual: ' + allowlistMode,",
    "  );",
    "  setText(watchModeApprovalState, pendingApprovals > 0 ? String(pendingApprovals) + ' pendente(s)' : 'Fila limpa');",
    "  setText(",
    "    watchModeApprovalSummary,",
    "    pendingApprovals > 0",
    "      ? 'Revise o screenshot atual e decida os handoffs antes da proxima acao.'",
    "      : 'Nenhum approval pendente neste momento.',",
    "  );",
    "  setText(watchModeReplayState, run?.latestScreenshotPath ? 'screenshot pronto' : 'sem screenshot');",
    "  setText(",
    "    watchModeReplaySummary,",
    "    run?.timeline?.length",
    "      ? 'Timeline recente: ' + String(run.timeline.length) + ' evento(s) auditaveis.'",
    "      : 'Nenhum replay visual registrado ainda.',",
    "  );",
    "  setText(",
    "    watchModeStatus,",
    "    normalizeText(run?.lastError) || normalizeText(run?.nextOperatorStep) || 'Watch Mode supervisionado pronto.',",
    "  );",
    "  setText(watchModeNextStep, normalizeText(run?.nextOperatorStep) || 'Nenhum run ativo ainda.');",
    "  renderList(watchModeApprovals, buildWatchModeApprovalItems(run));",
    "  renderList(watchModeTimeline, buildWatchModeTimelineItems(run));",
    "",
    "  if (watchModePreview instanceof HTMLImageElement) {",
    "    const runId = normalizeText(run?.runId);",
    "    if (runId && run?.latestScreenshotPath) {",
    "      watchModePreview.src = '/api/web/watch-mode/runs/' + encodeURIComponent(runId) + '/screenshot?ts=' + Date.now();",
    "      watchModePreview.hidden = false;",
    "      if (watchModePreviewEmpty instanceof HTMLElement) {",
    "        watchModePreviewEmpty.hidden = true;",
    "      }",
    "    } else {",
    "      watchModePreview.hidden = true;",
    "      watchModePreview.removeAttribute('src');",
    "      if (watchModePreviewEmpty instanceof HTMLElement) {",
    "        watchModePreviewEmpty.hidden = false;",
    "      }",
    "    }",
    "  }",
    "",
    "  if (watchModeStartAction instanceof HTMLButtonElement) {",
    "    watchModeStartAction.hidden = !protectedShellUnlocked;",
    "    watchModeStartAction.disabled = activeStatus === 'running' || activeStatus === 'paused' || activeStatus === 'waiting_approval';",
    "  }",
    "  if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "    watchModeRefreshAction.hidden = !protectedShellUnlocked;",
    "    watchModeRefreshAction.disabled = false;",
    "  }",
    "  if (watchModeAllowAppAction instanceof HTMLButtonElement) {",
    "    watchModeAllowAppAction.hidden = !protectedShellUnlocked;",
    "    watchModeAllowAppAction.disabled = !normalizeText(run?.targetWindow) && !normalizeText(watchModeTargetWindow?.value);",
    "  }",
    "  if (watchModeAllowSiteAction instanceof HTMLButtonElement) {",
    "    watchModeAllowSiteAction.hidden = !protectedShellUnlocked;",
    "    watchModeAllowSiteAction.disabled = !normalizeText(run?.siteUrl) && !normalizeText(watchModeSiteUrl?.value);",
    "  }",
    "  if (watchModeStrictOnAction instanceof HTMLButtonElement) {",
    "    watchModeStrictOnAction.hidden = !protectedShellUnlocked;",
    "    watchModeStrictOnAction.disabled = policy.strictApprovalDefault !== false;",
    "  }",
    "  if (watchModeStrictOffAction instanceof HTMLButtonElement) {",
    "    watchModeStrictOffAction.hidden = !protectedShellUnlocked;",
    "    watchModeStrictOffAction.disabled = policy.strictApprovalDefault === false;",
    "  }",
    "  if (watchModeCopyCommand instanceof HTMLButtonElement) {",
    "    watchModeCopyCommand.hidden = !protectedShellUnlocked;",
    "    watchModeCopyCommand.disabled = false;",
    "  }",
    "  if (watchModePauseAction instanceof HTMLButtonElement) {",
    "    watchModePauseAction.hidden = !protectedShellUnlocked || !run;",
    "    watchModePauseAction.disabled = activeStatus !== 'running';",
    "  }",
    "  if (watchModeResumeAction instanceof HTMLButtonElement) {",
    "    watchModeResumeAction.hidden = !protectedShellUnlocked || !run;",
    "    watchModeResumeAction.disabled = activeStatus !== 'paused';",
    "  }",
    "  if (watchModeStopAction instanceof HTMLButtonElement) {",
    "    watchModeStopAction.hidden = !protectedShellUnlocked || !run;",
    "    watchModeStopAction.disabled = !(activeStatus === 'running' || activeStatus === 'paused' || activeStatus === 'waiting_approval');",
    "  }",
    "}",
    "",
    "function renderSystemOverlordPanel(payload = null) {",
    "  if (payload !== null) {",
    "    systemOverlordData = payload;",
    "  }",
    "  const snapshot = systemOverlordData?.snapshot || null;",
    "  const errorMessage = normalizeText(systemOverlordData?.error);",
    "",
    "  if (!snapshot) {",
    "    setText(systemOverlordState, protectedShellUnlocked ? 'Indisponivel' : 'Valide o token');",
    "    setText(",
    "      systemOverlordSummary,",
    "      errorMessage || (",
    "        protectedShellUnlocked",
    "          ? 'System Overlord control plane indisponivel neste runtime.'",
    "          : 'O control plane supervisionado aparece aqui assim que o shell protegido for liberado.'",
    "      ),",
    "    );",
    "    setText(systemOverlordAutonomyState, 'Niveis 1-6');",
    "    setText(systemOverlordAutonomySummary, 'Diagnostico, patch, build/test/install, host, desktop/browser e owner supervisionado.');",
    "    setText(systemOverlordAdaptersState, protectedShellUnlocked ? 'Indisponivel' : 'Aguardando');",
    "    setText(systemOverlordAdaptersSummary, 'Browser, desktop e computer-use aparecem quando estiverem registrados no gateway.');",
    "    setText(systemOverlordKillSwitchState, protectedShellUnlocked ? 'Indisponivel' : 'Protegido');",
    "    setText(systemOverlordKillSwitchSummary, 'Bloqueia novas acoes e ajuda a cancelar o que ainda estiver ativo.');",
    "    setText(systemOverlordStatus, errorMessage || 'Valide o token para revisar o System Overlord supervisionado deste host.');",
    "    renderList(systemOverlordApprovals, [errorMessage || 'Valide o token para ver aprovacoes pendentes.']);",
    "    renderList(systemOverlordCapabilities, [errorMessage || 'Valide o token para ver capabilities e risco.']);",
    "    renderList(systemOverlordActions, ['Valide o token para ver ledger de acoes recentes.']);",
    "    if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "      systemOverlordRefreshAction.hidden = !protectedShellUnlocked;",
    "    }",
    "    if (systemOverlordKillSwitchEnable instanceof HTMLButtonElement) {",
    "      systemOverlordKillSwitchEnable.hidden = !protectedShellUnlocked;",
    "    }",
    "    if (systemOverlordKillSwitchRelease instanceof HTMLButtonElement) {",
    "      systemOverlordKillSwitchRelease.hidden = !protectedShellUnlocked;",
    "    }",
    "    if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "      systemOverlordRunAction.hidden = !protectedShellUnlocked;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const profiles = Array.isArray(snapshot.profiles) ? snapshot.profiles : [];",
    "  const levels = Array.isArray(snapshot.autonomyLevels) ? snapshot.autonomyLevels : [];",
    "  const capabilities = Array.isArray(snapshot.capabilities) ? snapshot.capabilities : [];",
    "  const adapters = Array.isArray(snapshot.adapters) ? snapshot.adapters : [];",
    "  const killSwitch = snapshot.killSwitch || null;",
    "  const approvalQueue = Array.isArray(snapshot.approvalQueue) ? snapshot.approvalQueue : [];",
    "  const actions = Array.isArray(snapshot.recentActions) ? snapshot.recentActions : [];",
    "  const running = Number(summary.runningActions || 0) || actions.filter((action) => normalizeText(action?.status) === 'running').length;",
    "  const pending = Number(summary.pendingApprovals || 0) || 0;",
    "  const blocked = Number(summary.blockedActions || 0) || 0;",
    "  const failed = Number(summary.failedActions || 0) || 0;",
    "  const timedOut = Number(summary.timedOutActions || 0) || actions.filter((action) => normalizeText(action?.status) === 'timed_out').length;",
    "  const completed = Number(summary.completedActions || 0) || 0;",
    "  const attention = pending + blocked + failed + timedOut;",
    "  const highRiskCount = capabilities.filter((entry) =>",
    "    normalizeText(entry?.riskLevel) === 'critical' || normalizeText(entry?.riskLevel) === 'high'",
    "  ).length;",
    "",
    "  setCardEmphasis(systemOverlordCard, attention > 0 ? 'focus' : 'subtle');",
    "  setText(",
    "    systemOverlordState,",
    "    killSwitch?.active",
    "      ? 'Kill switch'",
    "      : attention > 0",
    "        ? 'Atencao'",
    "        : running > 0",
    "          ? 'Executando'",
    "          : 'Pronto',",
    "  );",
    "  setText(",
    "    systemOverlordSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary)",
    "      || String(summary.capabilities || capabilities.length) + ' capability(s), '",
    "      + String(summary.adapters || adapters.length) + ' adapter(s) e '",
    "      + String(summary.recentActions || actions.length) + ' acao(oes) recentes.',",
    "  );",
    "  setText(",
    "    systemOverlordAutonomyState,",
    "    String(levels.length || 6) + ' niveis | ' + String(profiles.length || 4) + ' perfis',",
    "  );",
    "  setText(",
    "    systemOverlordAutonomySummary,",
    "    profiles.map((entry) => normalizeText(entry?.profile)).filter(Boolean).join(', ')",
    "      || 'safe, trusted, dangerous e owner com limites de autonomia 1-6.',",
    "  );",
    "  setText(",
    "    systemOverlordAdaptersState,",
    "    adapters.length ? String(adapters.length) + ' registrado(s)' : 'Sem adapters',",
    "  );",
    "  setText(",
    "    systemOverlordAdaptersSummary,",
    "    adapters.map((entry) => normalizeText(entry?.label || entry?.id)).filter(Boolean).slice(0, 4).join(', ')",
    "      || 'Nenhum adapter supervisionado registrado no gateway atual.',",
    "  );",
    "  setText(systemOverlordKillSwitchState, killSwitch?.active ? 'Ativo' : 'Liberado');",
    "  setText(",
    "    systemOverlordKillSwitchSummary,",
    "    killSwitch?.active",
    "      ? (normalizeText(killSwitch?.reason) || 'Novas acoes estao bloqueadas ate liberacao manual.')",
    "      : running > 0",
    "        ? String(running) + ' acao(oes) supervisionada(s) ainda estao em execucao.'",
    "        : 'Bloqueia novas acoes e pode cancelar o que ainda estiver ativo.',",
    "  );",
    "  setText(",
    "    systemOverlordStatus,",
    "    killSwitch?.active",
    "      ? 'Kill switch supervisionado ativo. Novas acoes ficam bloqueadas ate liberacao manual.'",
    "      : attention > 0",
    "      ? String(pending) + ' approval(s), ' + String(blocked) + ' bloqueio(s), ' + String(failed) + ' falha(s) e ' + String(timedOut) + ' timeout(s) recentes.'",
    "      : running > 0",
    "        ? String(running) + ' acao(oes) supervisionada(s) ainda estao rodando.'",
    "        : 'Control plane supervisionado pronto. ' + String(completed) + ' acao(oes) concluidas no ledger recente.'",
    "  );",
    "",
    "  renderList(",
    "    systemOverlordApprovals,",
    "    approvalQueue.slice(0, 5).map((item) =>",
    "      '<strong>' + escapeHtml(item?.capability || 'approval') + '</strong>: '",
    "      + escapeHtml(item?.reason || 'Aprovacao pendente.')",
    "      + ' <span class=\"muted-inline\">['",
    "      + escapeHtml(item?.riskLevel || 'risco n/d')",
    "      + ' | perfil ' + escapeHtml(item?.requiredProfile || 'n/d')",
    "      + ' | nivel ' + escapeHtml(item?.requiredAutonomyLevel || 'n/d')",
    "      + ']</span>'",
    "      + '<div class=\"inline-action-row\">'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-overlord-approval=\"approve-dry-run\" data-overlord-action-id=\"' + escapeHtml(item?.actionId || '') + '\">Aprovar dry-run</button>'",
    "      + '<button type=\"button\" class=\"action-button compact-action\" data-overlord-approval=\"approve-run\" data-overlord-action-id=\"' + escapeHtml(item?.actionId || '') + '\">Aprovar executar</button>'",
    "      + '<button type=\"button\" class=\"action-button secondary compact-action\" data-overlord-approval=\"reject\" data-overlord-action-id=\"' + escapeHtml(item?.actionId || '') + '\">Rejeitar</button>'",
    "      + '</div>'",
    "    ).concat(",
    "      approvalQueue.length === 0",
    "        ? ['Sem approvals pendentes no System Overlord.']",
    "        : approvalQueue.length > 5",
    "          ? ['+' + String(approvalQueue.length - 5) + ' approval(s) fora do resumo curto.']",
    "          : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    systemOverlordCapabilities,",
    "    capabilities.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(entry?.label || entry?.capability || 'Capability') + '</strong>: '",
    "      + escapeHtml(entry?.riskLevel || 'risco n/d')",
    "      + ' | perfil ' + escapeHtml(entry?.requiredProfile || 'n/d')",
    "      + ' | autonomia ' + escapeHtml(entry?.requiredAutonomyLevel || 'n/d')",
    "      + ' | runtime ' + escapeHtml(entry?.runtimeTarget || 'n/d')",
    "    ).concat(",
    "      capabilities.length > 8",
    "        ? ['+' + String(capabilities.length - 8) + ' capability(s) fora do resumo curto.']",
    "        : []",
    "    ),",
    "  );",
    "",
    "  renderList(",
    "    systemOverlordActions,",
    "    actions.slice(0, 6).map((action) =>",
    "      '<strong>' + escapeHtml(action?.status || 'acao') + '</strong>: '",
    "      + escapeHtml(action?.request?.capability || 'capability n/d')",
    "      + ' | ' + escapeHtml(action?.command || action?.errorMessage || action?.decision?.reason || 'sem comando')",
    "      + buildSystemOverlordActionControls(action)",
    "    ).concat(",
    "      actions.length === 0",
    "        ? ['Sem acoes recentes no ledger supervisionado.']",
    "        : highRiskCount > 0",
    "          ? [String(highRiskCount) + ' capability(s) de risco alto/critico estao disponiveis apenas com policy e approval.']",
    "          : []",
].join('\n');
