export const runtimeShellScriptPart3Seg2: string = [
    "    setCardEmphasis(hubControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(hubControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      hubControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado of the Hub + MCP not yet respondeu in this runtime.'",
    "        : 'O consolidado of the Hub + MCP aparece here assim que o shell protegido for liberado.',",
    "    );",
    "    setText(hubControlPlaneIntegrationsState, 'No reading');",
    "    setText(hubControlPlaneIntegrationsSummary, 'Conectores, plugins trusted and itens configuraveis aparecem aqui.');",
    "    setText(hubControlPlanePlatformState, 'No reading');",
    "    setText(hubControlPlanePlatformSummary, 'Registry remote, colecoes, recipes and skills ready aparecem aqui.');",
    "    setText(hubControlPlaneMcpState, 'No reading');",
    "    setText(hubControlPlaneMcpSummary, 'servers MCP, tools, resources and doctor ficam consolidados aqui.');",
    "    setText(hubControlPlaneStatus, errorMessage || 'Validate the token to review surfaces, actions, and highlighted Hub + MCP items.');",
    "    renderList(hubControlPlaneSurfaces, [errorMessage || 'Validate the token to see the consolidated surface plan.']);",
    "    renderList(hubControlPlaneActions, [errorMessage || 'Validate the token to review sync, doctor, and next ecosystem steps.']);",
    "    renderList(hubControlPlaneFeatured, [errorMessage || 'Validate the token to review highlighted connectors, plugins, skills, and MCPs.']);",
    "    if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      hubControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    if (hubControlPlaneSyncAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneSyncAction.hidden = !protectedShellUnlocked;",
    "      hubControlPlaneSyncAction.disabled = false;",
    "    }",
    "    if (hubControlPlaneMcpDoctorAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneMcpDoctorAction.hidden = !protectedShellUnlocked;",
    "      hubControlPlaneMcpDoctorAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const surfaces = Array.isArray(snapshot.surfaces) ? snapshot.surfaces : [];",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const featured = Array.isArray(snapshot.featured) ? snapshot.featured : [];",
    "  const highlights = Array.isArray(snapshot.highlights) ? snapshot.highlights : [];",
    "  const sync = snapshot.sync || {};",
    "",
    "  setCardEmphasis(hubControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(hubControlPlaneState, posture);",
    "  setText(hubControlPlaneSummary, normalizeText(snapshot?.narrative?.operatorSummary) || 'Hub consolidado currentizado.');",
    "  setText(",
    "    hubControlPlaneIntegrationsState,",
    "    String(summary.integrations || 0) + ' conectore(s) | ' + String(summary.plugins || 0) + ' plugin(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneIntegrationsSummary,",
    "    String(summary.providersReady || 0) + ' provider(s) ready | ' + String(summary.pluginsTrusted || 0) + ' plugin(s) trusted',",
    "  );",
    "  setText(",
    "    hubControlPlanePlatformState,",
    "    String(summary.platformEntries || 0) + ' entry(s) | sync ' + normalizeText(sync.status || 'disabled'),",
    "  );",
    "  setText(",
    "    hubControlPlanePlatformSummary,",
    "    String(summary.skillsVisible || 0) + ' skill(s) | ' + String(summary.skillRecipesReady || 0) + ' recipe(s) ready',",
    "  );",
    "  setText(",
    "    hubControlPlaneMcpState,",
    "    String(summary.mcpConnected || 0) + '/' + String(summary.mcpServers || 0) + ' server(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneMcpSummary,",
    "    String(summary.mcpTools || 0) + ' tool(s) | ' + String(summary.mcpResources || 0) + ' resource(s)',",
    "  );",
    "  setText(",
    "    hubControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction)",
    "      || normalizeText(sync.summary)",
    "      || 'Hub consolidado currentizado.',",
    "  );",
    "  renderList(",
    "    hubControlPlaneSurfaces,",
    "    surfaces.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Surface')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'healthy'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.primary || 'No summary.'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.secondary || 'No detail.')),",
    "    ).concat(highlights.slice(0, 2).map((entry) => '<strong>Highlight:</strong> ' + escapeHtml(normalizeText(entry))))",
    "      .concat(surfaces.length === 0 ? ['without surfaces consolidadas in this runtime.'] : []),",
    "  );",
    "  renderList(",
    "    hubControlPlaneActions,",
    "    actions.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.rationale || 'without racional.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(actions.length === 0 ? ['without suggested actions in this recorte.'] : []),",
    "  );",
    "  renderList(",
    "    hubControlPlaneFeatured,",
    "    featured.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Item')) + '</strong> [' + escapeHtml(normalizeText(entry?.surface || 'surface')) + ']: '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(featured.length === 0 ? ['without destaques suficientes in this recorte.'] : []),",
    "  );",
    "  if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneRefreshAction.hidden = false;",
    "    hubControlPlaneRefreshAction.disabled = false;",
    "  }",
    "  if (hubControlPlaneSyncAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneSyncAction.hidden = false;",
    "    hubControlPlaneSyncAction.disabled = false;",
    "  }",
    "  if (hubControlPlaneMcpDoctorAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneMcpDoctorAction.hidden = false;",
    "    hubControlPlaneMcpDoctorAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderQaControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    qaControlPlaneData = payload;",
    "  }",
    "  const snapshot = qaControlPlaneData?.qa || qaControlPlaneData?.snapshot || qaControlPlaneData || null;",
    "  const errorMessage = normalizeText(qaControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(qaControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(qaControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      qaControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado de QA not yet respondeu in this runtime.'",
    "        : 'O consolidado de budgets and release gates aparece here assim que o shell protegido for liberado.',",
    "    );",
    "    setText(qaControlPlaneBenchmarksState, 'No reading');",
    "    setText(qaControlPlaneBenchmarksSummary, 'Boot, runtime flow and sidecars aparecem here with budget and idade of the report.');",
    "    setText(qaControlPlaneRegressionsState, 'No reading');",
    "    setText(qaControlPlaneRegressionsSummary, 'Smokes and regressions appear here with failures, absence, and stale status.');",
    "    setText(qaControlPlaneReleaseState, 'No reading');",
    "    setText(qaControlPlaneReleaseSummary, 'Alpha and beta aparecem here with gate ready or pending.');",
    "    setText(qaControlPlaneStatus, errorMessage || 'Validate the token to review this host budgets, reports, and release gates.');",
    "    renderList(qaControlPlaneBenchmarks, [errorMessage || 'Validate the token to review benchmarks and budgets versionados.']);",
    "    renderList(qaControlPlaneSmokes, [errorMessage || 'Validate the token to review smoke suite and regressions criticas.']);",
    "    renderList(qaControlPlaneReleaseGates, [errorMessage || 'Validate the token to review alpha and beta without ler logs manualmente.']);",
    "    if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      qaControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      qaControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const benchmarks = Array.isArray(snapshot.benchmarks) ? snapshot.benchmarks : [];",
    "  const regressions = Array.isArray(snapshot.regressions) ? snapshot.regressions : [];",
    "  const smokes = Array.isArray(snapshot.smokes) ? snapshot.smokes : [];",
    "  const releaseGates = Array.isArray(snapshot.releaseGates) ? snapshot.releaseGates : [];",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "",
    "  setCardEmphasis(qaControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(qaControlPlaneState, posture);",
    "  setText(",
    "    qaControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'QA control plane updated.',",
    "  );",
    "  setText(",
    "    qaControlPlaneBenchmarksState,",
    "    String(benchmarks.length) + ' benchmark(s)',",
    "  );",
    "  setText(",
    "    qaControlPlaneBenchmarksSummary,",
    "    String(benchmarks.filter((entry) => normalizeText(entry?.status) === 'healthy').length)",
    "      + ' healthy | '",
    "      + String(benchmarks.filter((entry) => normalizeText(entry?.status) === 'attention').length)",
    "      + ' attention | '",
    "      + String(benchmarks.filter((entry) => ['critical', 'missing'].includes(normalizeText(entry?.status))).length)",
    "      + ' outside of the gate',",
    "  );",
    "  setText(",
    "    qaControlPlaneRegressionsState,",
    "    String(smokes.length) + ' smoke(s) | ' + String(regressions.length) + ' regression(s)',",
    "  );",
    "  setText(",
    "    qaControlPlaneRegressionsSummary,",
    "    String(summary.stale || 0) + ' stale | '",
    "      + String(summary.missing || 0) + ' missing | '",
    "      + String(summary.critical || 0) + ' critical',",
    "  );",
    "  const releasePrimary = releaseGates.find((entry) => normalizeText(entry?.profile) === normalizeText(snapshot.profile)) || releaseGates[0] || null;",
    "  setText(",
    "    qaControlPlaneReleaseState,",
    "    releasePrimary",
    "      - normalizeText(releasePrimary.profile || 'alpha')",
    "      : 'No reading',",
    "  );",
    "  setText(",
    "    qaControlPlaneReleaseSummary,",
    "    releasePrimary",
    "      - normalizeText(releasePrimary.summary)",
    "      : 'without gate principal in this recorte.',",
    "  );",
    "  setText(",
    "    qaControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction)",
    "      || 'QA control plane updated.',",
    "  );",
    "  renderList(",
    "    qaControlPlaneBenchmarks,",
    "    benchmarks.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Benchmark')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.status || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.actual || 'No reading.'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.budget || 'without budget.')),",
    "    ).concat(",
    "      benchmarks.length === 0 ? ['without benchmarks suficientes in this recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    qaControlPlaneSmokes,",
    "    smokes.slice(0, 4).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Smoke')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.')),",
    "    ).concat(",
    "      regressions.slice(0, 4).map((entry) =>",
    "        '<strong>' + escapeHtml(normalizeText(entry?.label || 'Regression')) + '</strong>: '",
    "        + escapeHtml(normalizeText(entry?.summary || 'No summary.')),",
    "      ),",
    "    ).concat(",
    "      actions.slice(0, 2).map((entry) =>",
    "        '<strong>Action:</strong> '",
    "        + escapeHtml(normalizeText(entry?.label || 'Action'))",
    "        + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "      ),",
    "    ).concat(",
    "      smokes.length === 0 && regressions.length === 0 ? ['without smokes or regressions suficientes in this recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    qaControlPlaneReleaseGates,",
    "    releaseGates.slice(0, 4).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.profile || 'release')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      releaseGates.length === 0 ? ['without release profiles suficientes in this recorte.'] : [],",
    "    ),",
    "  );",
    "  if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    qaControlPlaneRefreshAction.hidden = false;",
    "    qaControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderGovernanceControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    governanceControlPlaneData = payload;",
    "  }",
    "  const snapshot = governanceControlPlaneData?.governance || governanceControlPlaneData?.snapshot || governanceControlPlaneData || null;",
    "  const errorMessage = normalizeText(governanceControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(governanceControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(governanceControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      governanceControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado de governance not yet respondeu in this runtime.'",
    "        : 'A postura consolidada of the Governance aparece here assim que o shell protegido for liberado.',",
    "    );",
    "    setText(governanceControlPlaneTenantsState, 'No reading');",
    "    setText(governanceControlPlaneTenantsSummary, 'Tenants compartilhados, pessoais, onboarding and public servers aparecem aqui.');",
    "    setText(governanceControlPlaneTrustState, 'No reading');",
    "    setText(governanceControlPlaneTrustSummary, 'Approvals, MCP, plugins trusted and capabilities sensitive aparecem in this summary.');",
    "    setText(governanceControlPlanePolicyState, 'No reading');",
    "    setText(governanceControlPlanePolicySummary, 'Channels, nodes, platform, transports and teams ficam conectados ao mesmo contrato.');",
    "    setText(governanceControlPlaneStatus, errorMessage || 'Validate the token to review decisions, allowlists, and policy by surface.');",
    "    renderList(governanceControlPlaneDecisions, [errorMessage || 'Validate the token to see allow/ask/deny/defer/audit decisions.']);",
    "    renderList(governanceControlPlaneSurfaces, [errorMessage || 'Validate the token to see tenants, trust, channels, nodes, plugins, platform, transports, and teams.']);",
    "    renderList(governanceControlPlaneActions, [errorMessage || 'Validate the token to review next governance steps.']);",
    "    if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      governanceControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      governanceControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const surfaces = Array.isArray(snapshot.surfaces) ? snapshot.surfaces : [];",
    "  const decisions = Array.isArray(snapshot.decisions) ? snapshot.decisions : [];",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "",
    "  setCardEmphasis(governanceControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(governanceControlPlaneState, posture);",
    "  setText(",
    "    governanceControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Governance control plane updated.',",
    "  );",
    "  setText(",
    "    governanceControlPlaneTenantsState,",
    "    String(summary.sharedTenants || 0) + ' shared | ' + String(summary.personalTenants || 0) + ' personal',",
    "  );",
    "  setText(",
    "    governanceControlPlaneTenantsSummary,",
    "    String(summary.pendingOnboarding || 0) + ' onboarding pending | '",
    "      + String(summary.restrictedShared || 0) + ' restrito(s) | '",
    "      + String(summary.publicServers || 0) + ' public server(s)',",
    "  );",
    "  setText(",
    "    governanceControlPlaneTrustState,",
    "    'MCP ' + normalizeText(summary.mcpProfile || 'safe'),",
    "  );",
    "  setText(",
    "    governanceControlPlaneTrustSummary,",
    "    String(summary.pendingApprovals || 0) + ' approval(s) | '",
    "      + String(summary.highRiskCapabilities || 0) + ' high-risk | '",
    "      + String(summary.trustedPlugins || 0) + '/' + String(summary.installedPlugins || 0) + ' plugin(s) trusted',",
    "  );",
    "  setText(",
    "    governanceControlPlanePolicyState,",
    "    String(summary.readyChannels || 0) + '/' + String(summary.totalChannels || 0) + ' channels | '",
    "      + String(summary.pairedNodes || 0) + ' nodes',",
    "  );",
    "  setText(",
    "    governanceControlPlanePolicySummary,",
    "    String(summary.remoteAttention || 0) + ' transport(s) with attention real | '",
    "      + String(summary.decisions || 0) + ' decision(s)',",
    "  );",
    "  setText(",
    "    governanceControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Governance control plane updated.',",
    "  );",
    "  renderList(",
    "    governanceControlPlaneDecisions,",
    "    decisions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Decision')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.decision || 'audit'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.severity || 'info'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.rationale || 'without racional.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      decisions.length === 0 ? ['without trust decisions destacadas in the recorte current.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    governanceControlPlaneSurfaces,",
    "    surfaces.slice(0, 9).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Surface')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.posture || 'healthy'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.allowlistState || 'without allowlist state.'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.nextAction || 'without next passo.')),",
    "    ).concat(",
    "      surfaces.length === 0 ? ['without surfaces de policy suficientes in this recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    governanceControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['without suggested actions; mantenha review periodica de tenants and allowlists.'] : [],",
    "    ),",
    "  );",
    "  if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    governanceControlPlaneRefreshAction.hidden = false;",
    "    governanceControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderReplayLearningControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    replayLearningControlPlaneData = payload;",
    "  }",
    "  const snapshot = replayLearningControlPlaneData?.replayLearning || replayLearningControlPlaneData?.snapshot || replayLearningControlPlaneData || null;",
    "  const errorMessage = normalizeText(replayLearningControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(replayLearningControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(replayLearningControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      replayLearningControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado de replay/learning not yet respondeu in this runtime.'",
    "        : 'Timeline, compare runs and restore context aparecem here assim que o shell protegido for liberado.',",
    "    );",
    "    setText(replayLearningControlPlaneArtifactsState, 'No reading');",
    "    setText(replayLearningControlPlaneArtifactsSummary, 'Reusable artifacts and resume prompts are visible in this slice.');",
    "    setText(replayLearningControlPlaneLearningState, 'No reading');",
    "    setText(replayLearningControlPlaneLearningSummary, 'Pending, promoted, and high-trust candidates appear with a clear next step.');",
    "    setText(replayLearningControlPlaneMemoryState, 'No reading');",
    "    setText(replayLearningControlPlaneMemorySummary, 'Memory pressure, procedures, and restore points stay connected to the same plan.');",
    "    setText(replayLearningControlPlaneStatus, errorMessage || 'Validate the token to review timeline, reusable artifacts, learning promotions, and memory pressure.');",
    "    renderList(replayLearningControlPlaneActions, [errorMessage || 'Validate the token to review compare, resume, and learning promotions.']);",
    "    renderList(replayLearningControlPlaneArtifacts, [errorMessage || 'Validate the token to see artifacts with resume prompts.']);",
    "    renderList(replayLearningControlPlaneTimeline, [errorMessage || 'Validate the token para compare recent replay, workflows, and artifacts.']);",
    "    if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      replayLearningControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      replayLearningControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const artifacts = Array.isArray(snapshot.artifacts) ? snapshot.artifacts : [];",
    "  const timeline = Array.isArray(snapshot.timeline) ? snapshot.timeline : [];",
    "",
    "  setCardEmphasis(replayLearningControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(replayLearningControlPlaneState, posture);",
    "  setText(",
    "    replayLearningControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Replay/learning control plane updated.',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneArtifactsState,",
    "    String(summary.reusableArtifacts || 0) + '/' + String(summary.recentArtifacts || 0) + ' reutilizavel(is)',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneArtifactsSummary,",
    "    String(summary.resumeReady ? 'Resume ready' : 'without resume forte')",
    "      + ' | restore '",
    "      + String(summary.restoreReady ? 'ready' : 'pending'),",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneLearningState,",
    "    String(summary.pendingLearning || 0) + ' pending(s)',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneLearningSummary,",
    "    String(summary.learningCandidates || 0) + ' candidate(s) | '",
    "      + String(summary.promotedLearning || 0) + ' promovido(s) | '",
    "      + String(summary.highConfidenceLearning || 0) + ' high-confidence',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneMemoryState,",
    "    normalizeText(summary.memoryPressure || 'ok'),",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneMemorySummary,",
    "    String(summary.memoryEntries || 0) + ' entry(s) | '",
    "      + String(summary.proceduralEntries || 0) + ' procedure(s)',",
    "  );",
    "  setText(",
    "    replayLearningControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Replay/learning control plane updated.',",
    "  );",
    "  renderList(",
    "    replayLearningControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : '')",
    "      + (normalizeText(entry?.prompt) ? ' | ' + escapeHtml(normalizeText(entry.prompt)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['without suggested actions; mantenha review periodica de replay, artifacts and learning.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    replayLearningControlPlaneArtifacts,",
    "    artifacts.slice(0, 6).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Artifact')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.kind || 'file'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (entry?.reusable ? ' | reutilizavel' : ' | registrado'),",
    "    ).concat(",
    "      artifacts.length === 0 ? ['without artifacts reutilizaveis suficientes in this recorte.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    replayLearningControlPlaneTimeline,",
    "    timeline.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Evento')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.kind || 'timeline'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.status || 'without status'))",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.')),",
    "    ).concat(",
    "      timeline.length === 0 ? ['Not enough timeline data to compare runs in this window.'] : [],",
    "    ),",
    "  );",
    "  if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    replayLearningControlPlaneRefreshAction.hidden = false;",
    "    replayLearningControlPlaneRefreshAction.disabled = false;",
    "  }",
    "}",
    "",
    "function renderEcosystemControlPlanePanel(payload = null) {",
    "  if (payload !== null) {",
    "    ecosystemControlPlaneData = payload;",
    "  }",
    "  const snapshot = ecosystemControlPlaneData?.ecosystem || ecosystemControlPlaneData?.snapshot || ecosystemControlPlaneData || null;",
    "  const errorMessage = normalizeText(ecosystemControlPlaneData?.error);",
    "",
    "  if (!snapshot || typeof snapshot !== 'object') {",
    "    setCardEmphasis(ecosystemControlPlaneCard, protectedShellUnlocked ? 'focus' : 'subtle');",
    "    setText(ecosystemControlPlaneState, protectedShellUnlocked ? 'Unavailable' : 'Validate the token');",
    "    setText(",
    "      ecosystemControlPlaneSummary,",
    "      protectedShellUnlocked",
    "        - 'O consolidado of the ecossistema not yet respondeu in this runtime.'",
    "        : 'SDKs, guides and publish aparecem here assim que o shell protegido for liberado.',",
    "    );",
    "    setText(ecosystemControlPlaneSdkState, 'No reading');",
    "    setText(ecosystemControlPlaneSdkSummary, 'O state of the SDKs TypeScript and Python fica visible aqui.');",
    "    setText(ecosystemControlPlaneRegistryState, 'No reading');",
    "    setText(ecosystemControlPlaneRegistrySummary, 'Registry remote, colecoes, recipes and itens under review ficam consolidados aqui.');",
    "    setText(ecosystemControlPlanePublishState, 'No reading');",
    "    setText(ecosystemControlPlanePublishSummary, 'Bundles prepared, publicdos and warnings de provenance aparecem aqui.');",
    "    setText(ecosystemControlPlaneStatus, errorMessage || 'Validate the token to review ecosystem SDKs, guides, recipes, and publish artifacts.');",
    "    renderList(ecosystemControlPlaneActions, [errorMessage || 'Validate the token to review ecosystem SDKs, guides, and next steps.']);",
    "    renderList(ecosystemControlPlaneGuides, [errorMessage || 'Validate the token to see client, node, plugin, and recipe in one plan.']);",
    "    renderList(ecosystemControlPlanePublish, [errorMessage || 'Validate the token to review publish bundles, signatures, and readiness.']);",
    "    if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      ecosystemControlPlaneRefreshAction.hidden = !protectedShellUnlocked;",
    "      ecosystemControlPlaneRefreshAction.disabled = false;",
    "    }",
    "    return;",
    "  }",
    "",
    "  const summary = snapshot.summary || {};",
    "  const posture = normalizeText(summary.posture || 'healthy');",
    "  const actions = Array.isArray(snapshot.actions) ? snapshot.actions : [];",
    "  const guides = Array.isArray(snapshot.guides) ? snapshot.guides : [];",
    "  const publishArtifacts = Array.isArray(snapshot.publishArtifacts) ? snapshot.publishArtifacts : [];",
    "",
    "  setCardEmphasis(ecosystemControlPlaneCard, posture === 'healthy' ? 'subtle' : 'focus');",
    "  setText(ecosystemControlPlaneState, posture);",
    "  setText(",
    "    ecosystemControlPlaneSummary,",
    "    normalizeText(snapshot?.narrative?.operatorSummary) || 'Ecossistema currentizado.',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneSdkState,",
    "    String(summary.sdkFilesReady || 0) + '/' + String(summary.sdkFilesExpected || 0) + ' file(s)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneSdkSummary,",
    "    'TypeScript ' + (summary.sdkTypescriptReady ? 'ready' : 'pending')",
    "      + ' | Python ' + (summary.sdkPythonReady ? 'ready' : 'pending'),",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneRegistryState,",
    "    String(summary.registryEntries || 0) + ' item(s) | ' + String(summary.collections || 0) + ' collection(s)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneRegistrySummary,",
    "    String(summary.recipes || 0) + ' recipe(s) | review ' + String(summary.reviewPending || 0),",
    "  );",
    "  setText(",
    "    ecosystemControlPlanePublishState,",
    "    String(summary.publishArtifacts || 0) + ' artifact(s)',",
    "  );",
    "  setText(",
    "    ecosystemControlPlanePublishSummary,",
    "    String(summary.publishedArtifacts || 0) + ' publicdo(s) | ' + String(summary.preparedArtifacts || 0) + ' prepared',",
    "  );",
    "  setText(",
    "    ecosystemControlPlaneStatus,",
    "    normalizeText(snapshot?.narrative?.nextAction) || 'Ecossistema currentizado.',",
    "  );",
    "  renderList(",
    "    ecosystemControlPlaneActions,",
    "    actions.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Action')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.reason || 'No reason.'))",
    "      + (normalizeText(entry?.command) ? ' | ' + escapeHtml(normalizeText(entry.command)) : ''),",
    "    ).concat(",
    "      actions.length === 0 ? ['without suggested actions; mantenha SDKs, guides and publish sob review periodica.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    ecosystemControlPlaneGuides,",
    "    guides.map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.label || 'Guia')) + '</strong>: '",
    "      + escapeHtml(entry?.exists ? 'publicado' : 'pending')",
    "      + ' | '",
    "      + escapeHtml(normalizeText(entry?.summary || 'No summary.'))",
    "      + (normalizeText(entry?.path) ? ' | ' + escapeHtml(normalizeText(entry.path)) : ''),",
    "    ).concat(",
    "      guides.length === 0 ? ['No guia mapeado in this runtime.'] : [],",
    "    ),",
    "  );",
    "  renderList(",
    "    ecosystemControlPlanePublish,",
    "    publishArtifacts.slice(0, 8).map((entry) =>",
    "      '<strong>' + escapeHtml(normalizeText(entry?.releaseId || 'Bundle')) + '</strong>: '",
    "      + escapeHtml(normalizeText(entry?.uploadStatus || 'unknown'))",
    "      + ' | '",
    "      + escapeHtml(String(entry?.fileCount || 0) + ' file(s)')",
].join('\n');
