export const runtimeShellScriptPart5Seg1: string = [
    "    ),",
    "  );",
    "",
    "  if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "    systemOverlordRefreshAction.hidden = false;",
    "    systemOverlordRefreshAction.disabled = false;",
    "  }",
    "  if (systemOverlordKillSwitchEnable instanceof HTMLButtonElement) {",
    "    systemOverlordKillSwitchEnable.hidden = false;",
    "    systemOverlordKillSwitchEnable.disabled = killSwitch?.active === true;",
    "  }",
    "  if (systemOverlordKillSwitchRelease instanceof HTMLButtonElement) {",
    "    systemOverlordKillSwitchRelease.hidden = false;",
    "    systemOverlordKillSwitchRelease.disabled = killSwitch?.active !== true;",
    "  }",
    "  if (systemOverlordRunAction instanceof HTMLButtonElement) {",
    "    systemOverlordRunAction.hidden = false;",
    "    systemOverlordRunAction.disabled = false;",
    "  }",
    "}",
    "",
    "async function refreshSystemOverlordPanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(systemOverlordStatus, 'Valide o token antes de atualizar o System Overlord.');",
    "    return;",
    "  }",
    "",
    "  if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "    systemOverlordRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(systemOverlordStatus, 'Atualizando System Overlord supervisionado...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/system-overlord?limit=20', token);",
    "    renderSystemOverlordPanel(payload);",
    "    setText(",
    "      systemOverlordStatus,",
    "      normalizeText(payload?.snapshot?.narrative?.operatorSummary) || 'System Overlord atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(systemOverlordStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (systemOverlordRefreshAction instanceof HTMLButtonElement) {",
    "      systemOverlordRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshEvalControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(evalControlPlaneStatus, 'Valide o token antes de atualizar as evals operacionais.');",
    "    return;",
    "  }",
    "  if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    evalControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(evalControlPlaneStatus, 'Atualizando evals operacionais...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/evals', token);",
    "    renderEvalControlPlanePanel(payload);",
    "    setText(",
    "      evalControlPlaneStatus,",
    "      normalizeText(payload?.evals?.narrative?.operatorSummary) || 'Evals operacionais atualizadas.',",
    "    );",
    "  } catch (error) {",
    "    setText(evalControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (evalControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      evalControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshHubControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(hubControlPlaneStatus, 'Valide o token antes de atualizar o Hub + MCP.');",
    "    return;",
    "  }",
    "  if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    hubControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(hubControlPlaneStatus, 'Atualizando Hub + MCP...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/hub', token);",
    "    renderHubControlPlanePanel(payload);",
    "    setText(",
    "      hubControlPlaneStatus,",
    "      normalizeText(payload?.hub?.narrative?.nextAction) || 'Hub + MCP atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(hubControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (hubControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      hubControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runHubControlPlaneAction(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(hubControlPlaneStatus, 'Valide o token antes de agir no Hub + MCP.');",
    "    return;",
    "  }",
    "  const button = mode === 'platform-sync' ? hubControlPlaneSyncAction : hubControlPlaneMcpDoctorAction;",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(",
    "      hubControlPlaneStatus,",
    "      mode === 'platform-sync'",
    "        ? 'Sincronizando registry remoto pelo Hub...'",
    "        : 'Rodando doctor MCP pelo Hub...',",
    "    );",
    "    const payload = await postProtectedJson('/api/web/hub/actions', token, {",
    "      actionId: mode,",
    "    });",
    "    renderHubControlPlanePanel(payload);",
    "    setText(",
    "      hubControlPlaneStatus,",
    "      pickFirstText([",
    "        payload?.action?.summary,",
    "        payload?.hub?.narrative?.nextAction,",
    "      ], 'Hub atualizado.'),",
    "    );",
    "  } catch (error) {",
    "    setText(hubControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshQaControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(qaControlPlaneStatus, 'Valide o token antes de atualizar o QA control plane.');",
    "    return;",
    "  }",
    "  if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    qaControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(qaControlPlaneStatus, 'Atualizando QA control plane...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/qa', token);",
    "    renderQaControlPlanePanel(payload);",
    "    setText(",
    "      qaControlPlaneStatus,",
    "      normalizeText(payload?.qa?.narrative?.nextAction) || 'QA control plane atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(qaControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (qaControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      qaControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshGovernanceControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(governanceControlPlaneStatus, 'Valide o token antes de atualizar o Governance control plane.');",
    "    return;",
    "  }",
    "  if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    governanceControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(governanceControlPlaneStatus, 'Atualizando Governance control plane...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/governance', token);",
    "    renderGovernanceControlPlanePanel(payload);",
    "    setText(",
    "      governanceControlPlaneStatus,",
    "      normalizeText(payload?.governance?.narrative?.nextAction) || 'Governance control plane atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(governanceControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (governanceControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      governanceControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshReplayLearningControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(replayLearningControlPlaneStatus, 'Valide o token antes de atualizar o replay/learning control plane.');",
    "    return;",
    "  }",
    "  if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    replayLearningControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(replayLearningControlPlaneStatus, 'Atualizando replay, artifacts e learning loop...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/replay-learning', token);",
    "    renderReplayLearningControlPlanePanel(payload);",
    "    setText(",
    "      replayLearningControlPlaneStatus,",
    "      normalizeText(payload?.replayLearning?.narrative?.nextAction) || 'Replay/learning control plane atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(replayLearningControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (replayLearningControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      replayLearningControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshEcosystemControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(ecosystemControlPlaneStatus, 'Valide o token antes de atualizar a Wave 9.');",
    "    return;",
    "  }",
    "  if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    ecosystemControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(ecosystemControlPlaneStatus, 'Atualizando SDKs, guides, publish e catalogo publico...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/ecosystem', token);",
    "    renderEcosystemControlPlanePanel(payload);",
    "    setText(",
    "      ecosystemControlPlaneStatus,",
    "      normalizeText(payload?.ecosystem?.narrative?.nextAction) || 'Wave 9 atualizada.',",
    "    );",
    "  } catch (error) {",
    "    setText(ecosystemControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (ecosystemControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      ecosystemControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshDistributedRuntimeControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(distributedRuntimeControlPlaneStatus, 'Valide o token antes de atualizar a Wave 10.');",
    "    return;",
    "  }",
    "  if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    distributedRuntimeControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(distributedRuntimeControlPlaneStatus, 'Atualizando channels, fleet, transports e surfaces do runtime distribuido...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/distributed-runtime', token);",
    "    renderDistributedRuntimeControlPlanePanel(payload);",
    "    setText(",
    "      distributedRuntimeControlPlaneStatus,",
    "      normalizeText(payload?.distributedRuntime?.narrative?.nextAction) || 'Wave 10 atualizada.',",
    "    );",
    "  } catch (error) {",
    "    setText(distributedRuntimeControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (distributedRuntimeControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      distributedRuntimeControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshRuntimeStabilityControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(runtimeStabilityControlPlaneStatus, 'Valide o token antes de atualizar a estabilidade supervisionada.');",
    "    return;",
    "  }",
    "  if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    runtimeStabilityControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(runtimeStabilityControlPlaneStatus, 'Atualizando fleet, transports, keepalive e recovery...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/runtime-stability', token);",
    "    renderRuntimeStabilityControlPlanePanel(payload);",
    "    setText(",
    "      runtimeStabilityControlPlaneStatus,",
    "      normalizeText(payload?.runtimeStability?.narrative?.nextAction) || 'Estabilidade supervisionada atualizada.',",
    "    );",
    "  } catch (error) {",
    "    setText(runtimeStabilityControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (runtimeStabilityControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      runtimeStabilityControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshAutomationControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(automationControlPlaneStatus, 'Valide o token antes de atualizar as automacoes.');",
    "    return;",
    "  }",
    "",
    "  if (automationControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    automationControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/automations?limit=8', token);",
    "    renderAutomationControlPlanePanel(payload);",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      normalizeText(payload?.automations?.narrative?.nextAction) || 'Wave F atualizada.',",
    "    );",
    "  } finally {",
    "    if (automationControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      automationControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runAutomationControlPlaneAction(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(automationControlPlaneStatus, 'Valide o token antes de agir nas automacoes.');",
    "    return;",
    "  }",
    "",
    "  const payload = {",
    "    actionId: mode,",
    "    intentText: normalizeText(automationControlPlaneIntent?.value),",
    "    taskId: normalizeText(automationControlPlaneIntent?.value),",
    "  };",
    "  const buttons = [",
    "    automationControlPlaneCreateAction,",
    "    automationControlPlaneRefreshAction,",
    "    automationControlPlaneMaintenanceOnAction,",
    "    automationControlPlaneMaintenanceOffAction,",
    "    automationControlPlaneMaintenanceRunAction,",
    "  ].filter((entry) => entry instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    const response = await postProtectedJson('/api/web/automations/actions', token, payload);",
    "    renderAutomationControlPlanePanel(response);",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      normalizeText(response?.action?.summary) || 'Wave F atualizada.',",
    "    );",
    "    if (mode === 'create' && automationControlPlaneIntent instanceof HTMLInputElement && response?.action?.ok) {",
    "      automationControlPlaneIntent.value = '';",
    "    }",
    "  } catch (error) {",
    "    setText(",
    "      automationControlPlaneStatus,",
    "      error instanceof Error ? error.message : 'Falha ao executar a acao da Wave F.',",
    "    );",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshRolloutReadinessControlPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(rolloutReadinessControlPlaneStatus, 'Valide o token antes de atualizar o rollout persistente.');",
    "    return;",
    "  }",
    "  if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    rolloutReadinessControlPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(rolloutReadinessControlPlaneStatus, 'Atualizando QA, maintenance, publish e rollout persistente...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/operations/rollout-readiness', token);",
    "    renderRolloutReadinessControlPlanePanel(payload);",
    "    setText(",
    "      rolloutReadinessControlPlaneStatus,",
    "      normalizeText(payload?.rolloutReadiness?.narrative?.nextAction) || 'Rollout persistente atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(rolloutReadinessControlPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (rolloutReadinessControlPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      rolloutReadinessControlPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshTrustPlanePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(trustPlaneStatus, 'Valide o token antes de atualizar o Trust Plane.');",
    "    return;",
    "  }",
    "",
    "  if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "    trustPlaneRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(trustPlaneStatus, 'Atualizando Trust Plane...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/trust-plane', token);",
    "    renderTrustPlanePanel(payload);",
    "    setText(",
    "      trustPlaneStatus,",
    "      normalizeText(payload?.trustPlane?.narrative?.operatorSummary) || 'Trust Plane atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(trustPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (trustPlaneRefreshAction instanceof HTMLButtonElement) {",
    "      trustPlaneRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runTrustPlaneAction(actionId, body = {}) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(trustPlaneStatus, 'Valide o token antes de agir no Trust Plane.');",
    "    return;",
    "  }",
    "",
    "  const buttons = [",
    "    trustPlanePromoteTrustedAction,",
    "    trustPlaneHardenSafeAction,",
    "    trustPlaneSkillsDenyAction,",
    "  ].filter((entry) => entry instanceof HTMLButtonElement);",
    "  for (const button of buttons) {",
    "    button.disabled = true;",
    "  }",
    "  try {",
    "    setText(trustPlaneStatus, 'Aplicando politica do Trust Plane...');",
    "    const payload = await postProtectedJson('/api/web/trust-plane/actions', token, {",
    "      actionId,",
    "      ...body,",
    "    });",
    "    renderTrustPlanePanel(payload);",
    "    setText(",
    "      trustPlaneStatus,",
    "      normalizeText(payload?.action?.summary)",
    "        || normalizeText(payload?.trustPlane?.narrative?.operatorSummary)",
    "        || 'Trust Plane atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(trustPlaneStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    for (const button of buttons) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function refreshWatchModePanel() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Valide o token antes de atualizar o Watch Mode.');",
    "    return;",
    "  }",
    "",
    "  if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "    watchModeRefreshAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(watchModeStatus, 'Atualizando Watch Mode supervisionado...');",
    "    const payload = await fetchProtectedJsonOptional('/api/web/watch-mode?limit=8', token);",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      normalizeText(payload?.snapshot?.activeRun?.nextOperatorStep) || 'Watch Mode atualizado.',",
    "    );",
    "  } catch (error) {",
    "    setText(watchModeStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (watchModeRefreshAction instanceof HTMLButtonElement) {",
    "      watchModeRefreshAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModeStart() {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Valide o token antes de iniciar o Watch Mode.');",
    "    return;",
    "  }",
    "  const targetWindow = normalizeText(watchModeTargetWindow?.value);",
    "  const objective = normalizeText(watchModeObjective?.value);",
    "  if (!targetWindow || !objective) {",
    "    setText(watchModeStatus, 'Informe targetWindow e objective antes de iniciar o Watch Mode.');",
    "    return;",
    "  }",
    "  if (watchModeStartAction instanceof HTMLButtonElement) {",
    "    watchModeStartAction.disabled = true;",
    "  }",
    "  try {",
    "    setText(watchModeStatus, 'Iniciando Watch Mode supervisionado...');",
    "    const payload = await postProtectedJson('/api/web/watch-mode/runs', token, {",
    "      targetWindow,",
    "      objective,",
    "      siteUrl: normalizeText(watchModeSiteUrl?.value) || null,",
    "      strictApproval: !(watchModeStrictApproval instanceof HTMLInputElement) || watchModeStrictApproval.checked,",
    "      requestedBy: 'web-watch-mode',",
    "    });",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      normalizeText(payload?.run?.nextOperatorStep) || 'Watch Mode iniciado.',",
    "    );",
    "  } catch (error) {",
    "    setText(watchModeStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (watchModeStartAction instanceof HTMLButtonElement) {",
    "      watchModeStartAction.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModePolicyAction(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Valide o token antes de ajustar a policy do Watch Mode.');",
    "    return;",
    "  }",
    "",
    "  const activeRun = watchModeData?.run || watchModeData?.snapshot?.activeRun || null;",
    "  const currentApp = normalizeText(watchModeTargetWindow?.value) || normalizeText(activeRun?.targetWindow);",
    "  const currentSite = normalizeText(watchModeSiteUrl?.value) || normalizeText(activeRun?.siteUrl);",
    "  const button = mode === 'allow-app'",
    "    ? watchModeAllowAppAction",
    "    : mode === 'allow-site'",
    "      ? watchModeAllowSiteAction",
    "      : mode === 'strict-on'",
    "        ? watchModeStrictOnAction",
    "        : watchModeStrictOffAction;",
    "",
    "  if (button instanceof HTMLButtonElement) {",
    "    button.disabled = true;",
    "  }",
    "",
    "  try {",
    "    let body = null;",
    "    if (mode === 'allow-app') {",
    "      if (!currentApp) {",
    "        setText(watchModeStatus, 'Informe uma janela alvo antes de promover o app para allowlist.');",
    "        return;",
    "      }",
    "      body = {",
    "        actionId: 'allow-app',",
    "        app: currentApp,",
    "      };",
    "      setText(watchModeStatus, 'Promovendo a janela atual para a allowlist do Watch Mode...');",
    "    } else if (mode === 'allow-site') {",
    "      if (!currentSite) {",
    "        setText(watchModeStatus, 'Informe um site antes de promover o host para allowlist.');",
    "        return;",
    "      }",
    "      body = {",
    "        actionId: 'allow-site',",
    "        site: currentSite,",
    "      };",
    "      setText(watchModeStatus, 'Promovendo o site atual para a allowlist do Watch Mode...');",
    "    } else {",
    "      body = {",
    "        actionId: 'set-strict-default',",
    "        strictApproval: mode === 'strict-on',",
    "      };",
    "      setText(",
    "        watchModeStatus,",
    "        mode === 'strict-on'",
    "          ? 'Reforcando strict approval por default no Watch Mode...'",
    "          : 'Reduzindo a friccao do Watch Mode para allowlist-first...',",
    "      );",
    "    }",
    "",
    "    const payload = await postProtectedJson('/api/web/watch-mode/policy', token, body);",
    "    renderWatchModePanel(payload);",
    "    setText(",
    "      watchModeStatus,",
    "      mode === 'allow-app'",
    "        ? 'Janela adicionada a allowlist do Watch Mode.'",
    "        : mode === 'allow-site'",
    "          ? 'Site adicionado a allowlist do Watch Mode.'",
    "          : mode === 'strict-on'",
    "            ? 'Strict approval habilitado por default.'",
    "            : 'Strict approval desabilitado por default.',",
    "    );",
    "  } catch (error) {",
    "    setText(watchModeStatus, error instanceof Error ? error.message : String(error));",
    "  } finally {",
    "    if (button instanceof HTMLButtonElement) {",
    "      button.disabled = false;",
    "    }",
    "  }",
    "}",
    "",
    "async function runWatchModeMutation(mode) {",
    "  const token = normalizeText(readStoredToken() || authInput?.value);",
    "  if (!token) {",
    "    setText(watchModeStatus, 'Valide o token antes de mutar o Watch Mode.');",
    "    return;",
    "  }",
].join('\n');
