/* eslint-disable */
// AUTO-GENERATED by scripts/sync-gateway-i18n-catalogs.mjs - do not edit by hand.
import type { GatewayCatalogSection, SupportedLocale } from '../../localeContracts.js';
import { gateway_ar } from './ar.js';
import { gateway_bg } from './bg.js';
import { gateway_cs } from './cs.js';
import { gateway_da } from './da.js';
import { gateway_de } from './de.js';
import { gateway_en } from './en.js';
import { gateway_es } from './es.js';
import { gateway_fi } from './fi.js';
import { gateway_fr } from './fr.js';
import { gateway_he } from './he.js';
import { gateway_hi } from './hi.js';
import { gateway_hu } from './hu.js';
import { gateway_id } from './id.js';
import { gateway_it } from './it.js';
import { gateway_ja } from './ja.js';
import { gateway_ko } from './ko.js';
import { gateway_ms } from './ms.js';
import { gateway_nl } from './nl.js';
import { gateway_no } from './no.js';
import { gateway_phi } from './phi.js';
import { gateway_pl } from './pl.js';
import { gateway_pt_br } from './pt-br.js';
import { gateway_pt } from './pt.js';
import { gateway_ro } from './ro.js';
import { gateway_ru } from './ru.js';
import { gateway_sk } from './sk.js';
import { gateway_sv } from './sv.js';
import { gateway_th } from './th.js';
import { gateway_tr } from './tr.js';
import { gateway_uk_ua } from './uk-ua.js';
import { gateway_vi } from './vi.js';
import { gateway_zh_cn } from './zh-cn.js';

export interface GatewayCatalogExtension {
  gateway?: GatewayCatalogSection;
}

/** Every synced gateway seed keyed by its normalized locale tag. */
export const GATEWAY_SEED_CATALOGS: Record<string, GatewayCatalogSection> = {
  'ar': gateway_ar,
  'bg': gateway_bg,
  'cs': gateway_cs,
  'da': gateway_da,
  'de': gateway_de,
  'en': gateway_en,
  'es': gateway_es,
  'fi': gateway_fi,
  'fr': gateway_fr,
  'he': gateway_he,
  'hi': gateway_hi,
  'hu': gateway_hu,
  'id': gateway_id,
  'it': gateway_it,
  'ja': gateway_ja,
  'ko': gateway_ko,
  'ms': gateway_ms,
  'nl': gateway_nl,
  'no': gateway_no,
  'phi': gateway_phi,
  'pl': gateway_pl,
  'pt-br': gateway_pt_br,
  'pt': gateway_pt,
  'ro': gateway_ro,
  'ru': gateway_ru,
  'sk': gateway_sk,
  'sv': gateway_sv,
  'th': gateway_th,
  'tr': gateway_tr,
  'uk-ua': gateway_uk_ua,
  'vi': gateway_vi,
  'zh-cn': gateway_zh_cn,
};

/** Gateway sections layered onto builtin locale catalogs (base-language match). */
export const GATEWAY_CATALOG_EXTENSIONS: Partial<Record<SupportedLocale, GatewayCatalogExtension>> = {
  'ar': { gateway: gateway_ar },
  'de': { gateway: gateway_de },
  'en': { gateway: gateway_en },
  'es': { gateway: gateway_es },
  'fr': { gateway: gateway_fr },
  'hu': { gateway: gateway_hu },
  'it': { gateway: gateway_it },
  'ja': { gateway: gateway_ja },
  'ko': { gateway: gateway_ko },
  'pt': { gateway: gateway_pt },
  'ru': { gateway: gateway_ru },
  'tr': { gateway: gateway_tr },
  'uk': { gateway: gateway_uk_ua },
  'zh': { gateway: gateway_zh_cn },
};

/**
 * Locale tags carried solely by gateway seeds or by regional variants that
 * must not shadow their base builtin catalog; resolved under exact tags.
 */
export const GATEWAY_DYNAMIC_CATALOG_TAGS: readonly string[] = [
  'bg',
  'cs',
  'da',
  'fi',
  'he',
  'hi',
  'id',
  'ms',
  'nl',
  'no',
  'phi',
  'pl',
  'pt-br',
  'ro',
  'sk',
  'sv',
  'th',
  'vi',
];
