export const CHECKPOINT_TEMPLATE = `# Session checkpoint
_Generated by checkpoint writer; structure preserved across updates. Edit only content under italic instructions._

## §1 Active intent
_User's most recent explicit request, verbatim block-quoted from the conversation. The verbatim quote is the ground truth for what to do — do not paraphrase._

(none yet)

## §2 Next concrete action
_The single next concrete step, derived from §1 and current state. Include verbatim quote when the user gave one._

(none yet)

## §3 Directives (this session)
_This session's specific working style. Project-level rules are in projects/<pid>/MEMORY.md — do not duplicate them here. Only put items that are session-specific._

(none)

## §4 Task tree
_Hierarchical view of tasks with current focus marked. Pulled from task tool's DB; one bullet per top-level task with status + summary. Append \` (progress: tasks/<id>/progress.md)\` so the next agent can Read the per-task journal directly. Indent sub-tasks two spaces under their parent._

(none yet)

## §5 Current work
_Description of what was being done immediately before this checkpoint. Mention specific file paths and code locations._

(none yet)

## §6 Files and code sections
_Files actively being read or modified. List with one-line purpose._

(none yet)

## §7 Discovered knowledge (cross-task)
_Facts learned during this session that may apply to future tasks. Items here are candidates for promotion to projects/<pid>/MEMORY.md if they prove durable._

(none yet)

## §8 Errors and fixes
_Errors encountered this session and how they were resolved. Newest first._

(none)

## §9 Live resources
_Runtime state: branch, uncommitted files, running processes, temp artifacts. Most volatile — don't dwell on details that change every minute._

(none yet)

## §10 Design decisions and discussion outcomes
_Decisions reached through discussion that produced no immediate code/file artifact. Captures user intent or trade-off rationale future agents need to understand "why we did it this way". Promote to MEMORY.md ## Architecture decisions when proven cross-session-durable._

(none yet)

## §11 Open notes
_Writer-curated catch-all for items that don't fit §1-§10. Quotes from conversation, unresolved questions, micro-observations, miscellaneous. Cleaner than letting orphan content pollute §3 or §7. May be empty for many checkpoints._

(none yet)
`

export const MEMORY_TEMPLATE = `# Project memory
_Durable project-level knowledge. Persists across all sessions in this project. Edit only content under italic instructions._

## Project context
_What is this project? What's its goal? High-level identity._

(none yet)

## Rules
_Hard constraints from user that every session must respect._

(none yet)

## Architecture decisions
_Major design choices with rationale. The "why" matters more than the "what" for future sessions._

(none yet)

## Discovered durable knowledge
_Cross-task facts that survive across sessions. Promoted from session checkpoints' §7 when proven durable._

(none yet)
`

/**
 * Section budgets for checkpoint.md (token estimates per section).
 * Total ~11K, well under the 40K tail max.
 */
export const CHECKPOINT_SECTION_BUDGETS: Record<string, number> = {
  "§1 Active intent": 500,
  "§2 Next concrete action": 1000,
  "§3 Directives (this session)": 800,
  "§4 Task tree": 1000,
  "§5 Current work": 2000,
  "§6 Files and code sections": 1500,
  "§7 Discovered knowledge (cross-task)": 2000,
  "§8 Errors and fixes": 1500,
  "§9 Live resources": 1000,
  "§10 Design decisions and discussion outcomes": 3000,
  "§11 Open notes": 800,
}

/**
 * Section budgets for MEMORY.md (project-level). Total ~10K.
 */
export const MEMORY_SECTION_BUDGETS: Record<string, number> = {
  "Project context": 1000,
  "Rules": 2000,
  "Architecture decisions": 3000,
  "Discovered durable knowledge": 4000,
}

export const NOTES_TEMPLATE = `# Session notes
_Free-form scratchpad for the main agent. Append entries as you go; the checkpoint writer reconciles them at checkpoint events. Format each entry as \`## [turn N · YYYY-MM-DDTHH:MM:SSZ]\` (minute precision UTC, seconds optional) followed by free-form body. Before appending: scan existing entries — if you've already noted substantially similar content, add a short \`(see entry above)\` reference instead of duplicating._
`
