import type { LocalizationCatalog } from '../localeContracts.js';

export const af: LocalizationCatalog = {
  common: {
    save: 'Stoor',
    saving: 'Stoor tans...',
    cancel: 'Kanselleer',
    close: 'Maak toe',
    confirm: 'Bevestig',
    delete: 'Skrap',
    refresh: 'Herlaai',
    retry: 'Probeer weer',
    search: 'Soek...',
    loading: 'Laai tans...',
    create: 'Skep',
    creating: 'Skep tans...',
    clear: 'Vee uit',
    enabled: 'Geaktiveer',
    disabled: 'Gedeaktiveer',
    active: 'Aktief',
    inactive: 'Onaktief',
    status: 'Status',
    actions: 'Aksies',
    details: 'Besonderhede',
    error: 'Fout',
    success: 'Sukses',
    none: 'Geen',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Outonome KI-ontwikkelingsomgewing',
    chat: 'Klets',
    files: 'Lêers',
    approvals: 'Goedkeurings',
    memory: 'Mnemos Geheue',
    plugins: 'Inproppe',
    channels: 'Kanale',
    settings: 'Instellings',
    workboard: 'Kanban Matriks',
    automations: 'Outomatisering',
    analytics: 'Analise',
  },
  chat: {
    placeholder: 'Vra Zavorth enigiets of ken ’n koderingstaak toe...',
    send: 'Stuur',
    stop: 'Stop',
    clearHistory: 'Vee Geskiedenis Uit',
    emptyState: 'Nog geen boodskappe nie. Stuur ’n opdrag om te begin.',
    tokens: 'tokens',
    thinking: 'Dink tans...',
    errorOccurred: '’n Fout het voorgekom tydens die generering van die antwoord.',
  },
  channels: {
    title: 'Veelkanaal-Poort',
    description: 'Stel eksterne boodskapplatform-brûe op en monitor dit.',
    primaryChannel: 'Primêre Kanaal',
    telegram: 'Telegram-Poort',
    discord: 'Discord-Poort',
    slack: 'Slack-Poort',
    whatsapp: 'WhatsApp-Poort',
    web: 'Web-Konsole',
    notConfigured: 'Nie Opgestel Nie',
    connected: 'Gekoppel',
    disconnected: 'Ontkoppel',
  },
  providers: {
    title: 'LLM-Modelroeteerder',
    description: 'Stel primêre KI-verskaffers, API-sleutels en terugvalroetes op.',
    primaryProvider: 'Primêre Verskaffer',
    primaryModel: 'Primêre Model',
    fallbackModel: 'Terugvalmodel',
    apiKey: 'API-Sleutel',
    saveRoute: 'Stoor Roete',
    savedSuccessfully: 'KI-roete suksesvol gestoor.',
    saveFailed: 'Kon nie KI-roetekonfigurasie stoor nie.',
  },
  mnemos: {
    title: 'Mnemos Permanente Geheue',
    description: 'Konteksfeite, semantiese vektorherroeping en kruissessie-kennisberging.',
    searchFacts: 'Soek onthoude feite...',
    recall: 'Herroep Kennis',
    forget: 'Vergeet Feit',
    totalFacts: 'Totale Feite',
    noFactsRecorded: 'Nog geen geheuefeite aangeteken nie.',
  },
  kanban: {
    title: 'Swarm Kanban Matriks',
    description: 'Intydse taak-DAG-vordering, werkerstoekennings en herstelstatus.',
    backlog: 'Agterstand',
    inProgress: 'Besig',
    review: 'Hersiening',
    autoRepairLane: 'Outo-Herstel',
    done: 'Klaar',
    createTask: 'Nuwe Taak',
    taskTitle: 'Taaktitel',
    priority: 'Prioriteit',
  },
  autoRepair: {
    title: 'Geslote-Lus Outo-Herstel',
    description: 'Outonome diagnose, pleistergenerering, toetsvalidering en terugrol.',
    resolvingFailure: 'Besig om kodefout op te los...',
    patchApplied: 'Chirurgiese pleister toegepas.',
    testsPassing: 'Verifikasietoetse slaag.',
    rollbackRecovered: 'Veilige terugrol herstel.',
    incidentHistory: 'Voorvalgeskiedenis',
  },
  codeGraph: {
    title: 'AST-Kodebasisgrafiek',
    description: 'Simbooldefinisies, kruislêerroepafhanklikhede en impakanalise.',
    symbolsIndexed: 'Geïndekseerde Simbole',
    callGraph: 'Roepgrafiek',
    impactAnalysis: 'Impakanalise',
    callerDependencies: 'Roepafhanklikhede',
  },
  diffReview: {
    title: 'Spekulatiewe Diff-Hersiening',
    description: 'Voor-vaslegging risikotelling, kontrakbeskerming en sekuriteitsoudit.',
    riskRating: 'Risikogradering',
    securityAudit: 'Sekuriteitsoudit',
    secretCheck: 'Geheimlekkasiekontrole',
    breakingChanges: 'Kontrakbreukkontrole',
    approved: 'Goedgekeur',
    rejected: 'Afgewys',
  },
  approvals: {
    title: 'Uitvoeringsekuriteitshek',
    description: 'Hersien en keur sensitiewe gereedskapoproepe, lêerwysigings en toetskripte goed.',
    pendingApprovals: 'Hangende Goedkeurings',
    approve: 'Keur Goed',
    reject: 'Wys Af',
    riskLevel: 'Risikovlak',
    commandPreview: 'Opdragvoorskou',
    noPendingApprovals: 'Geen hangende goedkeurings nodig nie.',
  },
  settings: {
    title: 'Stelselinstellings',
    language: 'Taal',
    theme: 'Tema',
    logLevel: 'Boekstawingsvlak',
    resetDefaults: 'Herstel na Verstekwaardes',
  },
  connections: {
    title: 'Universele Verbindingstelsel',
    connectedSuccess: 'Suksesvol aan **{target}** verbind!',
    disconnectedSuccess: 'Ontkoppel van **{target}**. Plaaslike geloofsbriewe geskoonmaak.',
    alreadyConnected: 'Die teiken **{target}** is reeds verbind (status: `connected`).',
    notConnected: "Geen aktiewe verbinding met '{target}'.",
    unrecognizedTarget: "Die teiken '{target}' word nie erken nie.",
    rateLimitExceeded: 'Koerslimiet oorskry: jy kan hoogstens 10 verbindingsopdragte per minuut uitvoer. Wag asseblief.',
    apiKeyPrompt: 'Om **{target}** te verbind, verskaf jou {label}:\n`/connect {id} <jou_sleutel>`',
    localPathPrompt: 'Om **{target}** te verbind, spesifiseer die plaaslike gidspad:\n`/connect {id} /pad/na/{kind}`',
    oauthDeviceCodePrompt: 'Om toestelmagtiging vir **{target}** te voltooi:\n1. Maak oop: {url}\n2. Voer die paringskode in: `{code}`',
    catalogTitle: 'Beskikbare Verbinding Katalogus',
    noActiveConnections: 'Geen aktiewe verbindings gevind nie.\n\n• Koppel n integrasie: `/connect <teiken>`\n• Besigtig beskikbare katalogus: `/connections catalog`',
    usageConnect: '**Connect-opdraggebruik:**\n`/connect <teiken> [geloofsbriewe]`\n\n**Voorbeelde:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /pad/na/vault`\n\nGebruik `/connections catalog` om alle beskikbare teikens te sien.',
    usageDisconnect: 'Gebruik: `/disconnect <teiken>`\nVoorbeeld: `/disconnect stripe`',
    handshakeInProgress: "Daar is reeds 'n verbindingshanddruk aan die gang vir hierdie teiken.",
    pathVerificationFailed: '❌ Padverifikasie het misluk vir **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Sleutelverifikasie het misluk vir **{target}**: {details}',
    oauthClickLink: '🔗 **Verbind {target}:**\nKlik op die skakel hieronder om Zavorth te magtig:\n[Magtig {target}]({url})',
    oauthEnded: '⚠️ OAuth-magtiging het geëindig vir **{target}**: {details}',
    activeConnectionsHeader: '**Jou Aktiewe Verbindings ({count}):**',
    catalogEmpty: 'Daar is tans geen teikens in die verbindingskatalogus beskikbaar nie.',
    statusHeader: '**Verbinding Gesondheidstatus:**',
    statusEmpty: 'Geen aktiewe verbindings om status aan te meld nie.',
    guidanceLabel: '💡 **Leiding:**',
    reconnectHint: '• Herverbinding of geloofsbriewe opdateer: `/connect {target} <nuwe_geloofsbriewe>`',
    disconnectHint: '• Ontkoppel: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Plaaslike gids geverifieer by: `{path}`',
    credentialsVaultSuffix: 'Geloofsbriewe geënkripteer en veilig in die kluis gestoor.',
    secretStoreFailed: '❌ Stoor van geënkripteerde geloofsbriewe het misluk vir **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Verbind {target} (Toestelkode-vloei):**\n1. Maak die magtigingskakel oop: {url}\n2. Bevestig magtiging in jou blaaier.\n3. Zavorth sal die handdruk outomaties voltooi.',
    missingDeviceVerificationUrl: 'Toestelverifikasie-URL ontbreek',
    oauthConnectedSuccess: '✅ Suksesvol verbind met **{target}** via OAuth2!',
    oauthExchangeFailed: '❌ OAuth-tokenuitruil het misluk vir **{target}**: {details}',
    oauthListenerFailed: '⚠️ Kon nie OAuth-terugroep-luisteraar begin nie: {details}',
    oauthConfigActive: 'Die OAuth-konfigurasie vir **{target}** is aktief.',
    catalogConnectHint: 'Om enige teiken te verbind, tik: `/connect <teiken>`',
    statusLabel: 'Status',
    healthLabel: 'Gesondheid',
    authLabel: 'Verif',
    connectedAtLabel: 'Verbind om',
    disconnectServiceHint: '• Ontkoppel n diens: `/disconnect <teiken>`',
  },
};
