import type { LocalizationCatalog } from '../localeContracts.js';

export const af: LocalizationCatalog = {
  common: {
    save: 'Stoor',
    saving: 'Stoor tans...',
    cancel: 'Kanselleer',
    close: 'Maak toe',
    confirm: 'Bevestig',
    delete: 'Skrap',
    refresh: 'Herlaai',
    retry: 'Probeer weer',
    search: 'Soek...',
    loading: 'Laai tans...',
    create: 'Skep',
    creating: 'Skep tans...',
    clear: 'Vee uit',
    enabled: 'Geaktiveer',
    disabled: 'Gedeaktiveer',
    active: 'Aktief',
    inactive: 'Onaktief',
    status: 'Status',
    actions: 'Aksies',
    details: 'Besonderhede',
    error: 'Fout',
    success: 'Sukses',
    none: 'Geen',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Outonome KI-ontwikkelingsomgewing',
    chat: 'Klets',
    files: 'Lêers',
    approvals: 'Goedkeurings',
    memory: 'Mnemos Geheue',
    plugins: 'Inproppe',
    channels: 'Kanale',
    settings: 'Instellings',
    workboard: 'Kanban Matriks',
    automations: 'Outomatisering',
    analytics: 'Analise',
  },
  chat: {
    placeholder: 'Vra Zavorth enigiets of ken ’n koderingstaak toe...',
    send: 'Stuur',
    stop: 'Stop',
    clearHistory: 'Vee Geskiedenis Uit',
    emptyState: 'Nog geen boodskappe nie. Stuur ’n opdrag om te begin.',
    tokens: 'tokens',
    thinking: 'Dink tans...',
    errorOccurred: '’n Fout het voorgekom tydens die generering van die antwoord.',
  },
  channels: {
    title: 'Veelkanaal-Poort',
    description: 'Stel eksterne boodskapplatform-brûe op en monitor dit.',
    primaryChannel: 'Primêre Kanaal',
    telegram: 'Telegram-Poort',
    discord: 'Discord-Poort',
    slack: 'Slack-Poort',
    whatsapp: 'WhatsApp-Poort',
    web: 'Web-Konsole',
    notConfigured: 'Nie Opgestel Nie',
    connected: 'Gekoppel',
    disconnected: 'Ontkoppel',
  },
  providers: {
    title: 'LLM-Modelroeteerder',
    description: 'Stel primêre KI-verskaffers, API-sleutels en terugvalroetes op.',
    primaryProvider: 'Primêre Verskaffer',
    primaryModel: 'Primêre Model',
    fallbackModel: 'Terugvalmodel',
    apiKey: 'API-Sleutel',
    saveRoute: 'Stoor Roete',
    savedSuccessfully: 'KI-roete suksesvol gestoor.',
    saveFailed: 'Kon nie KI-roetekonfigurasie stoor nie.',
  },
  mnemos: {
    title: 'Mnemos Permanente Geheue',
    description: 'Konteksfeite, semantiese vektorherroeping en kruissessie-kennisberging.',
    searchFacts: 'Soek onthoude feite...',
    recall: 'Herroep Kennis',
    forget: 'Vergeet Feit',
    totalFacts: 'Totale Feite',
    noFactsRecorded: 'Nog geen geheuefeite aangeteken nie.',
  },
  kanban: {
    title: 'Swarm Kanban Matriks',
    description: 'Intydse taak-DAG-vordering, werkerstoekennings en herstelstatus.',
    backlog: 'Agterstand',
    inProgress: 'Besig',
    review: 'Hersiening',
    autoRepairLane: 'Outo-Herstel',
    done: 'Klaar',
    createTask: 'Nuwe Taak',
    taskTitle: 'Taaktitel',
    priority: 'Prioriteit',
  },
  autoRepair: {
    title: 'Geslote-Lus Outo-Herstel',
    description: 'Outonome diagnose, pleistergenerering, toetsvalidering en terugrol.',
    resolvingFailure: 'Besig om kodefout op te los...',
    patchApplied: 'Chirurgiese pleister toegepas.',
    testsPassing: 'Verifikasietoetse slaag.',
    rollbackRecovered: 'Veilige terugrol herstel.',
    incidentHistory: 'Voorvalgeskiedenis',
  },
  codeGraph: {
    title: 'AST-Kodebasisgrafiek',
    description: 'Simbooldefinisies, kruislêerroepafhanklikhede en impakanalise.',
    symbolsIndexed: 'Geïndekseerde Simbole',
    callGraph: 'Roepgrafiek',
    impactAnalysis: 'Impakanalise',
    callerDependencies: 'Roepafhanklikhede',
  },
  diffReview: {
    title: 'Spekulatiewe Diff-Hersiening',
    description: 'Voor-vaslegging risikotelling, kontrakbeskerming en sekuriteitsoudit.',
    riskRating: 'Risikogradering',
    securityAudit: 'Sekuriteitsoudit',
    secretCheck: 'Geheimlekkasiekontrole',
    breakingChanges: 'Kontrakbreukkontrole',
    approved: 'Goedgekeur',
    rejected: 'Afgewys',
  },
  approvals: {
    title: 'Uitvoeringsekuriteitshek',
    description: 'Hersien en keur sensitiewe gereedskapoproepe, lêerwysigings en toetskripte goed.',
    pendingApprovals: 'Hangende Goedkeurings',
    approve: 'Keur Goed',
    reject: 'Wys Af',
    riskLevel: 'Risikovlak',
    commandPreview: 'Opdragvoorskou',
    noPendingApprovals: 'Geen hangende goedkeurings nodig nie.',
  },
  settings: {
    title: 'Stelselinstellings',
    language: 'Taal',
    theme: 'Tema',
    logLevel: 'Boekstawingsvlak',
    resetDefaults: 'Herstel na Verstekwaardes',
  },
};
