import type { LocalizationCatalog } from '../localeContracts.js';

export const ar: LocalizationCatalog = {
  common: {
    save: 'حفظ',
    saving: 'جاري الحفظ...',
    cancel: 'إلغاء',
    close: 'إغلاق',
    confirm: 'تأكيد',
    delete: 'حذف',
    refresh: 'تحديث',
    retry: 'إعادة المحاولة',
    search: 'بحث...',
    loading: 'جاري التحميل...',
    create: 'إنشاء',
    creating: 'جاري الإنشاء...',
    clear: 'مسح',
    enabled: 'مفعل',
    disabled: 'معطل',
    active: 'نشط',
    inactive: 'غير نشط',
    status: 'الحالة',
    actions: 'الإجراءات',
    details: 'التفاصيل',
    error: 'خطأ',
    success: 'نجاح',
    none: 'لا يوجد',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'بيئة هندسة الذكاء الاصطناعي المستقلة',
    chat: 'محادثة',
    files: 'ملفات',
    approvals: 'موافقات',
    memory: 'ذاكرة Mnemos',
    plugins: 'إضافات',
    channels: 'قنوات',
    settings: 'إعدادات',
    workboard: 'مصفوفة كانبان',
    automations: 'أتمتة',
    analytics: 'تحليلات',
  },
  chat: {
    placeholder: 'اسأل Zavorth أو عيّن مهمة برمجية...',
    send: 'إرسال',
    stop: 'إيقاف',
    clearHistory: 'مسح السجل',
    emptyState: 'لا توجد رسائل بعد. أرسل أمراً للبدء.',
    tokens: 'رموز',
    thinking: 'جاري التفكير...',
    errorOccurred: 'حدث خطأ أثناء إنشاء الرد.',
  },
  channels: {
    title: 'بوابة القنوات المتعددة',
    description: 'تكوين ومراقبة جسور منصات المراسلة الخارجية.',
    primaryChannel: 'القناة الأساسية',
    telegram: 'بوابة Telegram',
    discord: 'بوابة Discord',
    slack: 'بوابة Slack',
    whatsapp: 'بوابة WhatsApp',
    web: 'لوحة التحكم',
    notConfigured: 'غير مهيأ',
    connected: 'متصل',
    disconnected: 'غير متصل',
  },
  providers: {
    title: 'موجّه نماذج الذكاء الاصطناعي',
    description: 'تكوين موفري الذكاء الاصطناعي الرئيسيين وبيانات الاعتماد ومسارات الطوارئ.',
    primaryProvider: 'الموفر الأساسي',
    primaryModel: 'النموذج الأساسي',
    fallbackModel: 'نموذج الطوارئ',
    apiKey: 'مفتاح API',
    saveRoute: 'حفظ المسار',
    savedSuccessfully: 'تم حفظ مسار الذكاء الاصطناعي بنجاح.',
    saveFailed: 'فشل حفظ تكوين المسار.',
  },
  mnemos: {
    title: 'ذاكرة Mnemos الدائمة',
    description: 'حقائق السياق، والاسترجاع الدلالي، والاحتفاظ بالمعرفة عبر الجلسات.',
    searchFacts: 'البحث في الحقائق المحفوظة...',
    recall: 'استرجاع المعرفة',
    forget: 'نسيان الحقيقة',
    totalFacts: 'إجمالي الحقائق',
    noFactsRecorded: 'لم يتم تسجيل أي حقائق بعد.',
  },
  kanban: {
    title: 'مصفوفة كانبان Swarm',
    description: 'تتبع مخطط المهام في الوقت الفعلي وتعيينات العمال والإصلاح.',
    backlog: 'قائمة الانتظار',
    inProgress: 'قيد التنفيذ',
    review: 'مراجعة',
    autoRepairLane: 'إصلاح تلقائي',
    done: 'مكتمل',
    createTask: 'مهمة جديدة',
    taskTitle: 'عنوان المهمة',
    priority: 'الأولوية',
  },
  autoRepair: {
    title: 'الإصلاح التلقائي المغلق',
    description: 'التشخيص المستقل وتوليد التعديلات والتحقق من الاختبارات والاستعادة.',
    resolvingFailure: 'جاري حل عطل الشيفرة البرمجية...',
    patchApplied: 'تم تطبيق التعديل بنجاح.',
    testsPassing: 'تم اجتياز اختبارات التحقق.',
    rollbackRecovered: 'تمت استعادة التراجع الآمن بنجاح.',
    incidentHistory: 'سجل الحوادث',
  },
  codeGraph: {
    title: 'مخطط كود AST',
    description: 'تعريفات الرموز وتبعيات الاستدعاء وتحليل التأثير.',
    symbolsIndexed: 'الرموز المفهرسة',
    callGraph: 'مخطط الاستدعاءات',
    impactAnalysis: 'تحليل التأثير',
    callerDependencies: 'تبعيات المستدعي',
  },
  diffReview: {
    title: 'المراجعة التخمينية للفروق',
    description: 'تقييم المخاطر قبل الاعتماد، وحماية العقود العامة، وفحص الأمان.',
    riskRating: 'تقييم المخاطر',
    securityAudit: 'تدقيق الأمان',
    secretCheck: 'فحص تسريب المفاتيح',
    breakingChanges: 'فحص العقود العامة',
    approved: 'مقبول',
    rejected: 'مرفوض',
  },
  approvals: {
    title: 'بوابة أمان التنفيذ',
    description: 'مراجعة واعتماد استدعاءات الأدوات الحساسة والكتابة على القرص وأوامر الصدفة.',
    pendingApprovals: 'الموافقات المعلقة',
    approve: 'موافقة',
    reject: 'رفض',
    riskLevel: 'مستوى الخطورة',
    commandPreview: 'معاينة الأمر',
    noPendingApprovals: 'لا توجد موافقات معلقة مطلوبة.',
  },
  settings: {
    title: 'إعدادات النظام',
    language: 'اللغة',
    theme: 'المظهر',
    logLevel: 'مستوى السجل',
    resetDefaults: 'استعادة الافتراضيات',
  },
};
