import type { LocalizationCatalog } from '../localeContracts.js';

export const ar: LocalizationCatalog = {
  common: {
    save: 'حفظ',
    saving: 'جاري الحفظ...',
    cancel: 'إلغاء',
    close: 'إغلاق',
    confirm: 'تأكيد',
    delete: 'حذف',
    refresh: 'تحديث',
    retry: 'إعادة المحاولة',
    search: 'بحث...',
    loading: 'جاري التحميل...',
    create: 'إنشاء',
    creating: 'جاري الإنشاء...',
    clear: 'مسح',
    enabled: 'مفعل',
    disabled: 'معطل',
    active: 'نشط',
    inactive: 'غير نشط',
    status: 'الحالة',
    actions: 'الإجراءات',
    details: 'التفاصيل',
    error: 'خطأ',
    success: 'نجاح',
    none: 'لا يوجد',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'بيئة هندسة الذكاء الاصطناعي المستقلة',
    chat: 'محادثة',
    files: 'ملفات',
    approvals: 'موافقات',
    memory: 'ذاكرة Mnemos',
    plugins: 'إضافات',
    channels: 'قنوات',
    settings: 'إعدادات',
    workboard: 'مصفوفة كانبان',
    automations: 'أتمتة',
    analytics: 'تحليلات',
  },
  chat: {
    placeholder: 'اسأل Zavorth أو عيّن مهمة برمجية...',
    send: 'إرسال',
    stop: 'إيقاف',
    clearHistory: 'مسح السجل',
    emptyState: 'لا توجد رسائل بعد. أرسل أمراً للبدء.',
    tokens: 'رموز',
    thinking: 'جاري التفكير...',
    errorOccurred: 'حدث خطأ أثناء إنشاء الرد.',
  },
  channels: {
    title: 'بوابة القنوات المتعددة',
    description: 'تكوين ومراقبة جسور منصات المراسلة الخارجية.',
    primaryChannel: 'القناة الأساسية',
    telegram: 'بوابة Telegram',
    discord: 'بوابة Discord',
    slack: 'بوابة Slack',
    whatsapp: 'بوابة WhatsApp',
    web: 'لوحة التحكم',
    notConfigured: 'غير مهيأ',
    connected: 'متصل',
    disconnected: 'غير متصل',
  },
  providers: {
    title: 'موجّه نماذج الذكاء الاصطناعي',
    description: 'تكوين موفري الذكاء الاصطناعي الرئيسيين وبيانات الاعتماد ومسارات الطوارئ.',
    primaryProvider: 'الموفر الأساسي',
    primaryModel: 'النموذج الأساسي',
    fallbackModel: 'نموذج الطوارئ',
    apiKey: 'مفتاح API',
    saveRoute: 'حفظ المسار',
    savedSuccessfully: 'تم حفظ مسار الذكاء الاصطناعي بنجاح.',
    saveFailed: 'فشل حفظ تكوين المسار.',
  },
  mnemos: {
    title: 'ذاكرة Mnemos الدائمة',
    description: 'حقائق السياق، والاسترجاع الدلالي، والاحتفاظ بالمعرفة عبر الجلسات.',
    searchFacts: 'البحث في الحقائق المحفوظة...',
    recall: 'استرجاع المعرفة',
    forget: 'نسيان الحقيقة',
    totalFacts: 'إجمالي الحقائق',
    noFactsRecorded: 'لم يتم تسجيل أي حقائق بعد.',
  },
  kanban: {
    title: 'مصفوفة كانبان Swarm',
    description: 'تتبع مخطط المهام في الوقت الفعلي وتعيينات العمال والإصلاح.',
    backlog: 'قائمة الانتظار',
    inProgress: 'قيد التنفيذ',
    review: 'مراجعة',
    autoRepairLane: 'إصلاح تلقائي',
    done: 'مكتمل',
    createTask: 'مهمة جديدة',
    taskTitle: 'عنوان المهمة',
    priority: 'الأولوية',
  },
  autoRepair: {
    title: 'الإصلاح التلقائي المغلق',
    description: 'التشخيص المستقل وتوليد التعديلات والتحقق من الاختبارات والاستعادة.',
    resolvingFailure: 'جاري حل عطل الشيفرة البرمجية...',
    patchApplied: 'تم تطبيق التعديل بنجاح.',
    testsPassing: 'تم اجتياز اختبارات التحقق.',
    rollbackRecovered: 'تمت استعادة التراجع الآمن بنجاح.',
    incidentHistory: 'سجل الحوادث',
  },
  codeGraph: {
    title: 'مخطط كود AST',
    description: 'تعريفات الرموز وتبعيات الاستدعاء وتحليل التأثير.',
    symbolsIndexed: 'الرموز المفهرسة',
    callGraph: 'مخطط الاستدعاءات',
    impactAnalysis: 'تحليل التأثير',
    callerDependencies: 'تبعيات المستدعي',
  },
  diffReview: {
    title: 'المراجعة التخمينية للفروق',
    description: 'تقييم المخاطر قبل الاعتماد، وحماية العقود العامة، وفحص الأمان.',
    riskRating: 'تقييم المخاطر',
    securityAudit: 'تدقيق الأمان',
    secretCheck: 'فحص تسريب المفاتيح',
    breakingChanges: 'فحص العقود العامة',
    approved: 'مقبول',
    rejected: 'مرفوض',
  },
  approvals: {
    title: 'بوابة أمان التنفيذ',
    description: 'مراجعة واعتماد استدعاءات الأدوات الحساسة والكتابة على القرص وأوامر الصدفة.',
    pendingApprovals: 'الموافقات المعلقة',
    approve: 'موافقة',
    reject: 'رفض',
    riskLevel: 'مستوى الخطورة',
    commandPreview: 'معاينة الأمر',
    noPendingApprovals: 'لا توجد موافقات معلقة مطلوبة.',
  },
  settings: {
    title: 'إعدادات النظام',
    language: 'اللغة',
    theme: 'المظهر',
    logLevel: 'مستوى السجل',
    resetDefaults: 'استعادة الافتراضيات',
  },
  connections: {
    title: 'نظام الاتصالات الشامل',
    connectedSuccess: 'تم الاتصال بـ **{target}** بنجاح!',
    disconnectedSuccess: 'تم قطع الاتصال بـ **{target}**. تمت إزالة بيانات الاعتماد المحلية.',
    alreadyConnected: 'الهدف **{target}** متصل بالفعل (الحالة: `connected`).',
    notConnected: "لا يوجد اتصال نشط بـ '{target}'.",
    unrecognizedTarget: "الهدف '{target}' غير معروف.",
    rateLimitExceeded: 'تم تجاوز حد المعدل: يمكنك تنفيذ 10 أوامر اتصال كحد أقصى في الدقيقة. يرجى الانتظار.',
    apiKeyPrompt: 'للاتصال بـ **{target}**، قدّم {label} الخاص بك:\n`/connect {id} <مفتاحك>`',
    localPathPrompt: 'للاتصال بـ **{target}**، حدد مسار الدليل المحلي:\n`/connect {id} /path/to/{kind}`',
    oauthDeviceCodePrompt: 'لإكمال تفويض الجهاز لـ **{target}**:\n1. افتح: {url}\n2. أدخل رمز الاقتران: `{code}`',
    catalogTitle: 'كتالوج الاتصالات المتاحة',
    noActiveConnections: 'لم يتم العثور على اتصالات نشطة.\n\n• الاتصال بتكامل: `/connect <هدف>`\n• عرض الكتالوج المتاح: `/connections catalog`',
    usageConnect: '**استخدام أمر Connect:**\n`/connect <هدف> [بيانات_الاعتماد]`\n\n**أمثلة:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /path/to/vault`\n\nاستخدم `/connections catalog` لعرض جميع الأهداف المتاحة.',
    usageDisconnect: 'الاستخدام: `/disconnect <هدف>`\nمثال: `/disconnect stripe`',
    handshakeInProgress: 'توجد بالفعل محاولة اتصال قيد التنفيذ لهذا الهدف.',
    pathVerificationFailed: '❌ فشل التحقق من المسار لـ **{target}**: {details}',
    apiKeyVerificationFailed: '❌ فشل التحقق من المفتاح لـ **{target}**: {details}',
    oauthClickLink: '🔗 **الاتصال بـ {target}:**\nانقر على الرابط أدناه لتفويض Zavorth:\n[تفويض {target}]({url})',
    oauthEnded: '⚠️ انتهى تفويض OAuth لـ **{target}**: {details}',
    activeConnectionsHeader: '**اتصالاتك النشطة ({count}):**',
    catalogEmpty: 'لا توجد أهداف متاحة في كتالوج الاتصالات حاليًا.',
    statusHeader: '**حالة سلامة الاتصالات:**',
    statusEmpty: 'لا توجد اتصالات نشطة لعرض حالتها.',
    guidanceLabel: '💡 **إرشاد:**',
    reconnectHint: '• إعادة الاتصال أو تحديث بيانات الاعتماد: `/connect {target} <بيانات_جديدة>`',
    disconnectHint: '• قطع الاتصال: `/disconnect {target}`',
    localPathVerifiedSuffix: 'تم التحقق من الدليل المحلي: `{path}`',
    credentialsVaultSuffix: 'تم تشفير بيانات الاعتماد وتخزينها بأمان في الخزنة.',
    secretStoreFailed: '❌ فشل تخزين بيانات الاعتماد المشفرة لـ **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **الاتصال بـ {target} (تدفق رمز الجهاز):**\n1. افتح رابط التفويض: {url}\n2. أكّد التفويض في متصفحك.\n3. سيُكمل Zavorth المصافحة تلقائيًا.',
    missingDeviceVerificationUrl: 'رابط التحقق من الجهاز مفقود',
    oauthConnectedSuccess: '✅ تم الاتصال بنجاح بـ **{target}** عبر OAuth2!',
    oauthExchangeFailed: '❌ فشل تبادل رموز OAuth لـ **{target}**: {details}',
    oauthListenerFailed: '⚠️ فشل بدء مستمع استدعاءات OAuth: {details}',
    oauthConfigActive: 'تكوين OAuth لـ **{target}** نشط.',
    catalogConnectHint: 'للاتصال بأي هدف، اكتب: `/connect <هدف>`',
    statusLabel: 'الحالة',
    healthLabel: 'السلامة',
    authLabel: 'المصادقة',
    connectedAtLabel: 'وقت الاتصال',
    disconnectServiceHint: '• قطع اتصال خدمة: `/disconnect <هدف>`',
  },
};
