import type { LocalizationCatalog } from '../localeContracts.js';

export const de: LocalizationCatalog = {
  common: {
    save: 'Speichern',
    saving: 'Speichern...',
    cancel: 'Abbrechen',
    close: 'Schließen',
    confirm: 'Bestätigen',
    delete: 'Löschen',
    refresh: 'Aktualisieren',
    retry: 'Wiederholen',
    search: 'Suchen...',
    loading: 'Laden...',
    create: 'Erstellen',
    creating: 'Erstellen...',
    clear: 'Leeren',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    status: 'Status',
    actions: 'Aktionen',
    details: 'Details',
    error: 'Fehler',
    success: 'Erfolg',
    none: 'Keine',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Autonome KI-Entwicklungsumgebung',
    chat: 'Chat',
    files: 'Dateien',
    approvals: 'Genehmigungen',
    memory: 'Mnemos Speicher',
    plugins: 'Plugins',
    channels: 'Kanäle',
    settings: 'Einstellungen',
    workboard: 'Kanban-Matrix',
    automations: 'Automatisierungen',
    analytics: 'Analysen',
  },
  chat: {
    placeholder: 'Fragen Sie Zavorth oder weisen Sie eine Entwicklungsaufgabe zu...',
    send: 'Senden',
    stop: 'Stoppen',
    clearHistory: 'Verlauf löschen',
    emptyState: 'Noch keine Nachrichten. Senden Sie eine Eingabe, um zu beginnen.',
    tokens: 'Tokens',
    thinking: 'Denken...',
    errorOccurred: 'Beim Generieren der Antwort ist ein Fehler aufgetreten.',
  },
  channels: {
    title: 'Multi-Kanal-Gateway',
    description: 'Konfigurieren und überwachen Sie externe Messaging-Plattformen.',
    primaryChannel: 'Hauptkanal',
    telegram: 'Telegram-Gateway',
    discord: 'Discord-Gateway',
    slack: 'Slack-Gateway',
    whatsapp: 'WhatsApp-Gateway',
    web: 'Web-Konsole',
    notConfigured: 'Nicht konfiguriert',
    connected: 'Verbunden',
    disconnected: 'Getrennt',
  },
  providers: {
    title: 'LLM-Modell-Router',
    description: 'Konfigurieren Sie primäre KI-Anbieter, API-Schlüssel und Fallback-Routen.',
    primaryProvider: 'Primärer Anbieter',
    primaryModel: 'Primäres Modell',
    fallbackModel: 'Fallback-Modell',
    apiKey: 'API-Schlüssel',
    saveRoute: 'Route speichern',
    savedSuccessfully: 'KI-Route erfolgreich gespeichert.',
    saveFailed: 'Fehler beim Speichern der KI-Routenkonfiguration.',
  },
  mnemos: {
    title: 'Mnemos Persistenter Speicher',
    description: 'Kontextfakten, semantische Vektorsuche und sitzungsübergreifende Wissensspeicherung.',
    searchFacts: 'Gespeicherte Fakten suchen...',
    recall: 'Wissen abrufen',
    forget: 'Fakt vergessen',
    totalFacts: 'Gesamtfakten',
    noFactsRecorded: 'Noch keine Speicherfakten aufgezeichnet.',
  },
  kanban: {
    title: 'Swarm Kanban-Matrix',
    description: 'Echtzeit-Aufgaben-DAG, Worker-Zuweisungen und Reparaturstatus.',
    backlog: 'Backlog',
    inProgress: 'In Bearbeitung',
    review: 'Überprüfung',
    autoRepairLane: 'Automatische Reparatur',
    done: 'Erledigt',
    createTask: 'Neue Aufgabe',
    taskTitle: 'Aufgabentitel',
    priority: 'Priorität',
  },
  autoRepair: {
    title: 'Closed-Loop Automatische Reparatur',
    description: 'Autonome Diagnose, Patch-Generierung, Testvalidierung und Rollback-Wiederherstellung.',
    resolvingFailure: 'Fehler wird behoben...',
    patchApplied: 'Patch angewendet.',
    testsPassing: 'Verifikationstests bestanden.',
    rollbackRecovered: 'Sicheres Rollback wiederhergestellt.',
    incidentHistory: 'Vorfallverlauf',
  },
  codeGraph: {
    title: 'AST-Codebasis-Graph',
    description: 'Symboldefinitionen, dateiübergreifende Abhängigkeiten und Auswirkungsanalyse.',
    symbolsIndexed: 'Indexierte Symbole',
    callGraph: 'Aufrufgraph',
    impactAnalysis: 'Auswirkungsanalyse',
    callerDependencies: 'Aufrufer-Abhängigkeiten',
  },
  diffReview: {
    title: 'Spekulative Diff-Überprüfung',
    description: 'Risikobewertung vor dem Commit, Vertragsschutz und Sicherheitsaudit.',
    riskRating: 'Risikobewertung',
    securityAudit: 'Sicherheitsaudit',
    secretCheck: 'Prüfung auf Geheimnislecks',
    breakingChanges: 'Prüfung auf Vertragsänderungen',
    approved: 'Genehmigt',
    rejected: 'Abgelehnt',
  },
  approvals: {
    title: 'Ausführungssicherheitsgate',
    description: 'Überprüfen und genehmigen Sie sensible Werkzeugaufrufe, Dateiänderungen und Shell-Befehle.',
    pendingApprovals: 'Ausstehende Genehmigungen',
    approve: 'Genehmigen',
    reject: 'Ablehnen',
    riskLevel: 'Risikostufe',
    commandPreview: 'Befehlsvorschau',
    noPendingApprovals: 'Keine ausstehenden Genehmigungen erforderlich.',
  },
  settings: {
    title: 'Systemeinstellungen',
    language: 'Sprache',
    theme: 'Design',
    logLevel: 'Protokollebene',
    resetDefaults: 'Auf Standard zurücksetzen',
  },
  connections: {
    title: 'Universelles Verbindungssubsystem',
    connectedSuccess: 'Erfolgreich mit **{target}** verbunden!',
    disconnectedSuccess: 'Von **{target}** getrennt. Lokale Zugangsdaten entfernt.',
    alreadyConnected: 'Das Ziel **{target}** ist bereits verbunden (Status: `connected`).',
    notConnected: "Keine aktive Verbindung mit '{target}'.",
    unrecognizedTarget: "Das Ziel '{target}' wurde nicht erkannt.",
    rateLimitExceeded: 'Ratenlimit überschritten: Du kannst maximal 10 Verbindungsbefehle pro Minute ausführen. Bitte warte kurz.',
    apiKeyPrompt: 'Um **{target}** zu verbinden, gib deinen {label} an:\n`/connect {id} <dein_schluessel>`',
    localPathPrompt: 'Um **{target}** zu verbinden, gib den lokalen Verzeichnispfad an:\n`/connect {id} /pfad/zum/{kind}`',
    oauthDeviceCodePrompt: 'Um die Geräteautorisierung für **{target}** abzuschließen:\n1. Öffne: {url}\n2. Gib den Kopplungscode ein: `{code}`',
    catalogTitle: 'Verfügbare Verbindungskatalog',
    noActiveConnections: 'Keine aktiven Verbindungen gefunden.\n\n• Integration verbinden: `/connect <ziel>`\n• Verfügbaren Katalog ansehen: `/connections catalog`',
    usageConnect: '**Connect-Befehlsverwendung:**\n`/connect <ziel> [zugangsdaten]`\n\n**Beispiele:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /pfad/zum/vault`\n\nVerwende `/connections catalog`, um alle verfügbaren Ziele zu sehen.',
    usageDisconnect: 'Verwendung: `/disconnect <ziel>`\nBeispiel: `/disconnect stripe`',
    handshakeInProgress: 'Für dieses Ziel läuft bereits ein Verbindungs-Handshake.',
    pathVerificationFailed: '❌ Pfadverifizierung für **{target}** fehlgeschlagen: {details}',
    apiKeyVerificationFailed: '❌ Schlüsselverifizierung für **{target}** fehlgeschlagen: {details}',
    oauthClickLink: '🔗 **{target} verbinden:**\nKlicke auf den untenstehenden Link, um Zavorth zu autorisieren:\n[{target} autorisieren]({url})',
    oauthEnded: '⚠️ Die OAuth-Autorisierung für **{target}** wurde beendet: {details}',
    activeConnectionsHeader: '**Deine Aktiven Verbindungen ({count}):**',
    catalogEmpty: 'Derzeit sind keine Ziele im Verbindungskatalog verfügbar.',
    statusHeader: '**Verbindungs-Integritätsstatus:**',
    statusEmpty: 'Keine aktiven Verbindungen für eine Statusanzeige.',
    guidanceLabel: '💡 **Hinweis:**',
    reconnectHint: '• Neu verbinden oder Zugangsdaten aktualisieren: `/connect {target} <neue_zugangsdaten>`',
    disconnectHint: '• Trennen: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Lokales Verzeichnis verifiziert unter: `{path}`',
    credentialsVaultSuffix: 'Zugangsdaten verschlüsselt und sicher im Tresor gespeichert.',
    secretStoreFailed: '❌ Speichern der verschlüsselten Zugangsdaten für **{target}** fehlgeschlagen: {details}',
    deviceCodeFlowInstructions: '🔑 **{target} verbinden (Device-Code-Flow):**\n1. Öffne den Autorisierungslink: {url}\n2. Bestätige die Autorisierung in deinem Browser.\n3. Zavorth schließt den Handshake automatisch ab.',
    missingDeviceVerificationUrl: 'Geräte-Verifizierungs-URL fehlt',
    oauthConnectedSuccess: '✅ Erfolgreich mit **{target}** über OAuth2 verbunden!',
    oauthExchangeFailed: '❌ OAuth-Token-Austausch für **{target}** fehlgeschlagen: {details}',
    oauthListenerFailed: '⚠️ Start des OAuth-Callback-Listeners fehlgeschlagen: {details}',
    oauthConfigActive: 'Die OAuth-Konfiguration für **{target}** ist aktiv.',
    catalogConnectHint: 'Um ein beliebiges Ziel zu verbinden, tippe: `/connect <ziel>`',
    statusLabel: 'Status',
    healthLabel: 'Integrität',
    authLabel: 'Auth',
    connectedAtLabel: 'Verbunden am',
    disconnectServiceHint: '• Dienst trennen: `/disconnect <ziel>`',
  },
};
