import type { LocalizationCatalog } from '../localeContracts.js';

export const de: LocalizationCatalog = {
  common: {
    save: 'Speichern',
    saving: 'Speichern...',
    cancel: 'Abbrechen',
    close: 'Schließen',
    confirm: 'Bestätigen',
    delete: 'Löschen',
    refresh: 'Aktualisieren',
    retry: 'Wiederholen',
    search: 'Suchen...',
    loading: 'Laden...',
    create: 'Erstellen',
    creating: 'Erstellen...',
    clear: 'Leeren',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    status: 'Status',
    actions: 'Aktionen',
    details: 'Details',
    error: 'Fehler',
    success: 'Erfolg',
    none: 'Keine',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Autonome KI-Entwicklungsumgebung',
    chat: 'Chat',
    files: 'Dateien',
    approvals: 'Genehmigungen',
    memory: 'Mnemos Speicher',
    plugins: 'Plugins',
    channels: 'Kanäle',
    settings: 'Einstellungen',
    workboard: 'Kanban-Matrix',
    automations: 'Automatisierungen',
    analytics: 'Analysen',
  },
  chat: {
    placeholder: 'Fragen Sie Zavorth oder weisen Sie eine Entwicklungsaufgabe zu...',
    send: 'Senden',
    stop: 'Stoppen',
    clearHistory: 'Verlauf löschen',
    emptyState: 'Noch keine Nachrichten. Senden Sie eine Eingabe, um zu beginnen.',
    tokens: 'Tokens',
    thinking: 'Denken...',
    errorOccurred: 'Beim Generieren der Antwort ist ein Fehler aufgetreten.',
  },
  channels: {
    title: 'Multi-Kanal-Gateway',
    description: 'Konfigurieren und überwachen Sie externe Messaging-Plattformen.',
    primaryChannel: 'Hauptkanal',
    telegram: 'Telegram-Gateway',
    discord: 'Discord-Gateway',
    slack: 'Slack-Gateway',
    whatsapp: 'WhatsApp-Gateway',
    web: 'Web-Konsole',
    notConfigured: 'Nicht konfiguriert',
    connected: 'Verbunden',
    disconnected: 'Getrennt',
  },
  providers: {
    title: 'LLM-Modell-Router',
    description: 'Konfigurieren Sie primäre KI-Anbieter, API-Schlüssel und Fallback-Routen.',
    primaryProvider: 'Primärer Anbieter',
    primaryModel: 'Primäres Modell',
    fallbackModel: 'Fallback-Modell',
    apiKey: 'API-Schlüssel',
    saveRoute: 'Route speichern',
    savedSuccessfully: 'KI-Route erfolgreich gespeichert.',
    saveFailed: 'Fehler beim Speichern der KI-Routenkonfiguration.',
  },
  mnemos: {
    title: 'Mnemos Persistenter Speicher',
    description: 'Kontextfakten, semantische Vektorsuche und sitzungsübergreifende Wissensspeicherung.',
    searchFacts: 'Gespeicherte Fakten suchen...',
    recall: 'Wissen abrufen',
    forget: 'Fakt vergessen',
    totalFacts: 'Gesamtfakten',
    noFactsRecorded: 'Noch keine Speicherfakten aufgezeichnet.',
  },
  kanban: {
    title: 'Swarm Kanban-Matrix',
    description: 'Echtzeit-Aufgaben-DAG, Worker-Zuweisungen und Reparaturstatus.',
    backlog: 'Backlog',
    inProgress: 'In Bearbeitung',
    review: 'Überprüfung',
    autoRepairLane: 'Automatische Reparatur',
    done: 'Erledigt',
    createTask: 'Neue Aufgabe',
    taskTitle: 'Aufgabentitel',
    priority: 'Priorität',
  },
  autoRepair: {
    title: 'Closed-Loop Automatische Reparatur',
    description: 'Autonome Diagnose, Patch-Generierung, Testvalidierung und Rollback-Wiederherstellung.',
    resolvingFailure: 'Fehler wird behoben...',
    patchApplied: 'Patch angewendet.',
    testsPassing: 'Verifikationstests bestanden.',
    rollbackRecovered: 'Sicheres Rollback wiederhergestellt.',
    incidentHistory: 'Vorfallverlauf',
  },
  codeGraph: {
    title: 'AST-Codebasis-Graph',
    description: 'Symboldefinitionen, dateiübergreifende Abhängigkeiten und Auswirkungsanalyse.',
    symbolsIndexed: 'Indexierte Symbole',
    callGraph: 'Aufrufgraph',
    impactAnalysis: 'Auswirkungsanalyse',
    callerDependencies: 'Aufrufer-Abhängigkeiten',
  },
  diffReview: {
    title: 'Spekulative Diff-Überprüfung',
    description: 'Risikobewertung vor dem Commit, Vertragsschutz und Sicherheitsaudit.',
    riskRating: 'Risikobewertung',
    securityAudit: 'Sicherheitsaudit',
    secretCheck: 'Prüfung auf Geheimnislecks',
    breakingChanges: 'Prüfung auf Vertragsänderungen',
    approved: 'Genehmigt',
    rejected: 'Abgelehnt',
  },
  approvals: {
    title: 'Ausführungssicherheitsgate',
    description: 'Überprüfen und genehmigen Sie sensible Werkzeugaufrufe, Dateiänderungen und Shell-Befehle.',
    pendingApprovals: 'Ausstehende Genehmigungen',
    approve: 'Genehmigen',
    reject: 'Ablehnen',
    riskLevel: 'Risikostufe',
    commandPreview: 'Befehlsvorschau',
    noPendingApprovals: 'Keine ausstehenden Genehmigungen erforderlich.',
  },
  settings: {
    title: 'Systemeinstellungen',
    language: 'Sprache',
    theme: 'Design',
    logLevel: 'Protokollebene',
    resetDefaults: 'Auf Standard zurücksetzen',
  },
};
