import type { LocalizationCatalog } from '../localeContracts.js';

export const en: LocalizationCatalog = {
  common: {
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    delete: 'Delete',
    refresh: 'Refresh',
    retry: 'Retry',
    search: 'Search...',
    loading: 'Loading...',
    create: 'Create',
    creating: 'Creating...',
    clear: 'Clear',
    enabled: 'Enabled',
    disabled: 'Disabled',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status',
    actions: 'Actions',
    details: 'Details',
    error: 'Error',
    success: 'Success',
    none: 'None',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Autonomous AI Development Suite',
    chat: 'Chat',
    files: 'Files',
    approvals: 'Approvals',
    memory: 'Mnemos Memory',
    plugins: 'Plugins',
    channels: 'Channels',
    settings: 'Settings',
    workboard: 'Kanban Matrix',
    automations: 'Automations',
    analytics: 'Analytics',
  },
  chat: {
    placeholder: 'Ask Zavorth anything or assign a coding mission...',
    send: 'Send',
    stop: 'Stop',
    clearHistory: 'Clear History',
    emptyState: 'No messages yet. Send a prompt to begin.',
    tokens: 'tokens',
    thinking: 'Thinking...',
    errorOccurred: 'An error occurred while generating the response.',
  },
  channels: {
    title: 'Multi-Channel Gateway',
    description: 'Configure and monitor external messaging platform bridges.',
    primaryChannel: 'Primary Channel',
    telegram: 'Telegram Gateway',
    discord: 'Discord Gateway',
    slack: 'Slack Gateway',
    whatsapp: 'WhatsApp Gateway',
    web: 'Web Console',
    notConfigured: 'Not Configured',
    connected: 'Connected',
    disconnected: 'Disconnected',
  },
  providers: {
    title: 'LLM Model Router',
    description: 'Configure primary AI providers, API credentials, and fallback routing.',
    primaryProvider: 'Primary Provider',
    primaryModel: 'Primary Model',
    fallbackModel: 'Fallback Model',
    apiKey: 'API Key',
    saveRoute: 'Save Route',
    savedSuccessfully: 'AI route saved successfully.',
    saveFailed: 'Failed to save AI route configuration.',
  },
  mnemos: {
    title: 'Mnemos Persistent Memory',
    description: 'Context facts, semantic vector recall, and cross-session knowledge storage.',
    searchFacts: 'Search remembered facts...',
    recall: 'Recall Knowledge',
    forget: 'Forget Fact',
    totalFacts: 'Total Facts',
    noFactsRecorded: 'No memory facts recorded yet.',
  },
  kanban: {
    title: 'Swarm Kanban Matrix',
    description: 'Real-time task DAG progression, worker assignments, and repair states.',
    backlog: 'Backlog',
    inProgress: 'In Progress',
    review: 'Review',
    autoRepairLane: 'Auto-Repair',
    done: 'Done',
    createTask: 'New Task',
    taskTitle: 'Task Title',
    priority: 'Priority',
  },
  autoRepair: {
    title: 'Closed-Loop Auto-Repair',
    description: 'Autonomous diagnosis, patch generation, test validation, and rollback recovery.',
    resolvingFailure: 'Resolving incident failure...',
    patchApplied: 'Surgical patch applied.',
    testsPassing: 'Verification tests passing.',
    rollbackRecovered: 'Surgical rollback safely restored.',
    incidentHistory: 'Incident History',
  },
  codeGraph: {
    title: 'AST Codebase Graph',
    description: 'Symbol definitions, cross-file caller dependencies, and impact analysis.',
    symbolsIndexed: 'Symbols Indexed',
    callGraph: 'Call Graph',
    impactAnalysis: 'Impact Analysis',
    callerDependencies: 'Caller Dependencies',
  },
  diffReview: {
    title: 'Speculative Diff Review',
    description: 'Pre-commit risk scoring, contract protection, and security audit.',
    riskRating: 'Risk Rating',
    securityAudit: 'Security Audit',
    secretCheck: 'Secret Leak Check',
    breakingChanges: 'Breaking Contract Check',
    approved: 'Approved',
    rejected: 'Rejected',
  },
  approvals: {
    title: 'Execution Safety Gate',
    description: 'Review and approve sensitive tool calls, file writes, and shell execution.',
    pendingApprovals: 'Pending Approvals',
    approve: 'Approve',
    reject: 'Reject',
    riskLevel: 'Risk Level',
    commandPreview: 'Command Preview',
    noPendingApprovals: 'No pending approvals required.',
  },
  settings: {
    title: 'System Settings',
    language: 'Language',
    theme: 'Theme',
    logLevel: 'Log Level',
    resetDefaults: 'Reset to Defaults',
  },
  approval: {
    prompt: {
      entry: '{ordinal}[{risk}] {label} — ref {ref}',
      hint:
        'Reply 1 (or the ref) to allow once, approve / approve session / approve always, reject (or deny) to refuse, or reply other to type your answer.',
    },
    receipt: {
      approved: 'Approved {ref} ({choice}).',
      denied: 'Denied approval {ref}.',
      notFound: 'No pending approval found for {ref}.',
      resolvedApprovedElsewhere:
        'Resolved elsewhere: approval {ref} was approved on another surface. No action is needed here.',
      resolvedDeniedElsewhere:
        'Resolved elsewhere: approval {ref} was denied on another surface. No action is needed here.',
    },
    bulk: {
      approvedAll: 'Approved all {count} approval(s) ({choice}).',
      deniedAll: 'Denied {count} approval(s).',
      approvedPartial: 'Approved {resolved} of {total} approval(s) ({choice}).',
      deniedPartial: 'Denied {resolved} of {total} approval(s).',
      notFound: 'No pending approval found for all.',
    },
    other: {
      armed:
        'Describe your answer for {count} pending approval(s); your next message is captured as the decision context.',
      deniedWithReason: 'Denied {count} approval(s). Your answer was relayed to the agent.',
      referencedNotFound: 'No pending approval found for the referenced approvals.',
    },
  },
  connections: {
    title: 'Universal Connection Subsystem',
    connectedSuccess: 'Connected to **{target}** successfully!',
    disconnectedSuccess: 'Disconnected from **{target}**. Local secrets purged.',
    alreadyConnected: 'Target **{target}** is already connected (status: `connected`).',
    notConnected: "Not connected to '{target}'.",
    unrecognizedTarget: "Target '{target}' is not recognized.",
    rateLimitExceeded: 'Rate limit exceeded: You can execute at most 10 connection commands per minute. Please wait.',
    apiKeyPrompt: 'To connect **{target}**, provide your {label}:\n`/connect {id} <your_key>`',
    localPathPrompt: 'To connect **{target}**, specify the local directory path:\n`/connect {id} /path/to/{kind}`',
    oauthDeviceCodePrompt: 'To complete device authorization for **{target}**:\n1. Open: {url}\n2. Enter pairing code: `{code}`',
    catalogTitle: 'Available Connection Catalog',
    noActiveConnections: 'No active connections found.\n\n• Connect an integration: `/connect <target>`\n• View available catalog: `/connections catalog`',
    usageConnect: '**Connect Command Usage:**\n`/connect <target> [credential]`\n\n**Examples:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /path/to/vault`\n\nUse `/connections catalog` to view all available targets.',
    usageDisconnect: 'Usage: `/disconnect <target>`\nExample: `/disconnect stripe`',
    handshakeInProgress: 'A connection handshake is already in progress for this target.',
    pathVerificationFailed: '❌ Path verification failed for **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Verification ping failed for **{target}**: {details}',
    oauthClickLink: '🔗 **Connect {target}:**\nClick the link below to authorize Zavorth:\n[Authorize {target}]({url})',
    oauthEnded: '⚠️ OAuth authorization ended for **{target}**: {details}',
    activeConnectionsHeader: '**Your Active Connections ({count}):**',
    catalogEmpty: 'No targets are currently available in the connection catalog.',
    statusHeader: '**Connection Health Status:**',
    statusEmpty: 'No active connections to report status.',
    guidanceLabel: '💡 **Guidance:**',
    reconnectHint: '• To reconnect or upgrade credentials: `/connect {target} <new_credentials>`',
    disconnectHint: '• To disconnect: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Local directory verified at: `{path}`',
    credentialsVaultSuffix: 'Credentials encrypted and stored securely in vault.',
    secretStoreFailed: '❌ Failed to store encrypted credentials for **{target}**: {details}',
    deviceCodeFlowInstructions:
      '🔑 **Connect {target} (Device Code Flow):**\n1. Open the authorization link: {url}\n2. Confirm authorization in your browser.\n3. Zavorth will complete the handshake automatically.',
    missingDeviceVerificationUrl: 'Missing device verification URL',
    oauthConnectedSuccess: '✅ Successfully connected to **{target}** via OAuth2!',
    oauthExchangeFailed: '❌ OAuth token exchange failed for **{target}**: {details}',
    oauthListenerFailed: '⚠️ Failed to start OAuth callback listener: {details}',
    oauthConfigActive: 'OAuth configuration for **{target}** is active.',
    catalogConnectHint: 'To connect any target, type: `/connect <target>`',
    statusLabel: 'Status',
    healthLabel: 'Health',
    authLabel: 'Auth',
    connectedAtLabel: 'Connected At',
    disconnectServiceHint: '• Disconnect a service: `/disconnect <target>`',
  },
};
