import type { LocalizationCatalog } from '../localeContracts.js';

export const en: LocalizationCatalog = {
  common: {
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    delete: 'Delete',
    refresh: 'Refresh',
    retry: 'Retry',
    search: 'Search...',
    loading: 'Loading...',
    create: 'Create',
    creating: 'Creating...',
    clear: 'Clear',
    enabled: 'Enabled',
    disabled: 'Disabled',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status',
    actions: 'Actions',
    details: 'Details',
    error: 'Error',
    success: 'Success',
    none: 'None',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Autonomous AI Development Suite',
    chat: 'Chat',
    files: 'Files',
    approvals: 'Approvals',
    memory: 'Mnemos Memory',
    plugins: 'Plugins',
    channels: 'Channels',
    settings: 'Settings',
    workboard: 'Kanban Matrix',
    automations: 'Automations',
    analytics: 'Analytics',
  },
  chat: {
    placeholder: 'Ask Zavorth anything or assign a coding mission...',
    send: 'Send',
    stop: 'Stop',
    clearHistory: 'Clear History',
    emptyState: 'No messages yet. Send a prompt to begin.',
    tokens: 'tokens',
    thinking: 'Thinking...',
    errorOccurred: 'An error occurred while generating the response.',
  },
  channels: {
    title: 'Multi-Channel Gateway',
    description: 'Configure and monitor external messaging platform bridges.',
    primaryChannel: 'Primary Channel',
    telegram: 'Telegram Gateway',
    discord: 'Discord Gateway',
    slack: 'Slack Gateway',
    whatsapp: 'WhatsApp Gateway',
    web: 'Web Console',
    notConfigured: 'Not Configured',
    connected: 'Connected',
    disconnected: 'Disconnected',
  },
  providers: {
    title: 'LLM Model Router',
    description: 'Configure primary AI providers, API credentials, and fallback routing.',
    primaryProvider: 'Primary Provider',
    primaryModel: 'Primary Model',
    fallbackModel: 'Fallback Model',
    apiKey: 'API Key',
    saveRoute: 'Save Route',
    savedSuccessfully: 'AI route saved successfully.',
    saveFailed: 'Failed to save AI route configuration.',
  },
  mnemos: {
    title: 'Mnemos Persistent Memory',
    description: 'Context facts, semantic vector recall, and cross-session knowledge storage.',
    searchFacts: 'Search remembered facts...',
    recall: 'Recall Knowledge',
    forget: 'Forget Fact',
    totalFacts: 'Total Facts',
    noFactsRecorded: 'No memory facts recorded yet.',
  },
  kanban: {
    title: 'Swarm Kanban Matrix',
    description: 'Real-time task DAG progression, worker assignments, and repair states.',
    backlog: 'Backlog',
    inProgress: 'In Progress',
    review: 'Review',
    autoRepairLane: 'Auto-Repair',
    done: 'Done',
    createTask: 'New Task',
    taskTitle: 'Task Title',
    priority: 'Priority',
  },
  autoRepair: {
    title: 'Closed-Loop Auto-Repair',
    description: 'Autonomous diagnosis, patch generation, test validation, and rollback recovery.',
    resolvingFailure: 'Resolving incident failure...',
    patchApplied: 'Surgical patch applied.',
    testsPassing: 'Verification tests passing.',
    rollbackRecovered: 'Surgical rollback safely restored.',
    incidentHistory: 'Incident History',
  },
  codeGraph: {
    title: 'AST Codebase Graph',
    description: 'Symbol definitions, cross-file caller dependencies, and impact analysis.',
    symbolsIndexed: 'Symbols Indexed',
    callGraph: 'Call Graph',
    impactAnalysis: 'Impact Analysis',
    callerDependencies: 'Caller Dependencies',
  },
  diffReview: {
    title: 'Speculative Diff Review',
    description: 'Pre-commit risk scoring, contract protection, and security audit.',
    riskRating: 'Risk Rating',
    securityAudit: 'Security Audit',
    secretCheck: 'Secret Leak Check',
    breakingChanges: 'Breaking Contract Check',
    approved: 'Approved',
    rejected: 'Rejected',
  },
  approvals: {
    title: 'Execution Safety Gate',
    description: 'Review and approve sensitive tool calls, file writes, and shell execution.',
    pendingApprovals: 'Pending Approvals',
    approve: 'Approve',
    reject: 'Reject',
    riskLevel: 'Risk Level',
    commandPreview: 'Command Preview',
    noPendingApprovals: 'No pending approvals required.',
  },
  settings: {
    title: 'System Settings',
    language: 'Language',
    theme: 'Theme',
    logLevel: 'Log Level',
    resetDefaults: 'Reset to Defaults',
  },
  approval: {
    prompt: {
      entry: '{ordinal}[{risk}] {label} — ref {ref}',
      hint:
        'Reply 1 (or the ref) to allow once, approve / approve session / approve always, reject (or deny) to refuse, or reply other to type your answer.',
    },
    receipt: {
      approved: 'Approved {ref} ({choice}).',
      denied: 'Denied approval {ref}.',
      notFound: 'No pending approval found for {ref}.',
      resolvedApprovedElsewhere:
        'Resolved elsewhere: approval {ref} was approved on another surface. No action is needed here.',
      resolvedDeniedElsewhere:
        'Resolved elsewhere: approval {ref} was denied on another surface. No action is needed here.',
    },
    bulk: {
      approvedAll: 'Approved all {count} approval(s) ({choice}).',
      deniedAll: 'Denied {count} approval(s).',
      approvedPartial: 'Approved {resolved} of {total} approval(s) ({choice}).',
      deniedPartial: 'Denied {resolved} of {total} approval(s).',
      notFound: 'No pending approval found for all.',
    },
    other: {
      armed:
        'Describe your answer for {count} pending approval(s); your next message is captured as the decision context.',
      deniedWithReason: 'Denied {count} approval(s). Your answer was relayed to the agent.',
      referencedNotFound: 'No pending approval found for the referenced approvals.',
    },
  },
};
