import type { LocalizationCatalog } from '../localeContracts.js';

export const es: LocalizationCatalog = {
  common: {
    save: 'Guardar',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    close: 'Cerrar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    refresh: 'Actualizar',
    retry: 'Reintentar',
    search: 'Buscar...',
    loading: 'Cargando...',
    create: 'Crear',
    creating: 'Creando...',
    clear: 'Limpiar',
    enabled: 'Habilitado',
    disabled: 'Deshabilitado',
    active: 'Activo',
    inactive: 'Inactivo',
    status: 'Estado',
    actions: 'Acciones',
    details: 'Detalles',
    error: 'Error',
    success: 'Éxito',
    none: 'Ninguno',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Suite Autónoma de Ingeniería de IA',
    chat: 'Chat',
    files: 'Archivos',
    approvals: 'Aprobaciones',
    memory: 'Memoria Mnemos',
    plugins: 'Plugins',
    channels: 'Canales',
    settings: 'Configuración',
    workboard: 'Matriz Kanban',
    automations: 'Automatizaciones',
    analytics: 'Métricas',
  },
  chat: {
    placeholder: 'Pregunta a Zavorth o asigna una misión de desarrollo...',
    send: 'Enviar',
    stop: 'Detener',
    clearHistory: 'Borrar Historial',
    emptyState: 'No hay mensajes aún. Envía una instrucción para comenzar.',
    tokens: 'tokens',
    thinking: 'Pensando...',
    errorOccurred: 'Ocurrió un error al generar la respuesta.',
  },
  channels: {
    title: 'Gateway Multicanal',
    description: 'Configura y supervisa puentes de plataformas de mensajería externas.',
    primaryChannel: 'Canal Principal',
    telegram: 'Gateway Telegram',
    discord: 'Gateway Discord',
    slack: 'Gateway Slack',
    whatsapp: 'Gateway WhatsApp',
    web: 'Consola Web',
    notConfigured: 'No Configurado',
    connected: 'Conectado',
    disconnected: 'Desconectado',
  },
  providers: {
    title: 'Enrutador de Modelos LLM',
    description: 'Configura proveedores de IA principales, credenciales y rutas de respaldo.',
    primaryProvider: 'Proveedor Principal',
    primaryModel: 'Modelo Principal',
    fallbackModel: 'Modelo de Respaldo',
    apiKey: 'Clave de API',
    saveRoute: 'Guardar Ruta',
    savedSuccessfully: 'Ruta de IA guardada con éxito.',
    saveFailed: 'Error al guardar la configuración de la ruta de IA.',
  },
  mnemos: {
    title: 'Memoria Persistente Mnemos',
    description: 'Hechos de contexto, recuperación vectorial semántica y conocimiento persistente.',
    searchFacts: 'Buscar hechos memorizados...',
    recall: 'Recordar Conocimiento',
    forget: 'Olvidar Hecho',
    totalFacts: 'Total de Hechos',
    noFactsRecorded: 'No hay hechos memorizados aún.',
  },
  kanban: {
    title: 'Matriz Kanban Swarm',
    description: 'Seguimiento en tiempo real del DAG de tareas, asignaciones y auto-reparación.',
    backlog: 'Pendiente',
    inProgress: 'En Progreso',
    review: 'Revisión',
    autoRepairLane: 'Auto-Reparación',
    done: 'Completado',
    createTask: 'Nueva Tarea',
    taskTitle: 'Título de la Tarea',
    priority: 'Prioridad',
  },
  autoRepair: {
    title: 'Auto-Reparación en Bucle Cerrado',
    description: 'Diagnóstico autónomo, generación de parches quirúrgicos, validación y rollback.',
    resolvingFailure: 'Resolviendo incidente y fallo de código...',
    patchApplied: 'Parche quirúrgico aplicado.',
    testsPassing: 'Pruebas de verificación aprobadas.',
    rollbackRecovered: 'Rollback quirúrgico restaurado con seguridad.',
    incidentHistory: 'Historial de Incidentes',
  },
  codeGraph: {
    title: 'Grafo de Código AST',
    description: 'Definiciones de símbolos, dependencias de llamadas y análisis de impacto.',
    symbolsIndexed: 'Símbolos Indexados',
    callGraph: 'Grafo de Llamadas',
    impactAnalysis: 'Análisis de Impacto',
    callerDependencies: 'Dependencias de Consumidores',
  },
  diffReview: {
    title: 'Revisión Especulativa de Diff',
    description: 'Evaluación de riesgo pre-commit, protección de contratos y auditoría de seguridad.',
    riskRating: 'Clasificación de Riesgo',
    securityAudit: 'Auditoría de Seguridad',
    secretCheck: 'Comprobación de Secretos',
    breakingChanges: 'Comprobación de Contratos Públicos',
    approved: 'Aprobado',
    rejected: 'Rechazado',
  },
  approvals: {
    title: 'Puerta de Seguridad de Ejecución',
    description: 'Revisa y aprueba llamadas a herramientas sensibles, escritura en disco y shell.',
    pendingApprovals: 'Aprobaciones Pendientes',
    approve: 'Aprobar',
    reject: 'Rechazar',
    riskLevel: 'Nivel de Riesgo',
    commandPreview: 'Vista Previa del Comando',
    noPendingApprovals: 'No se requieren aprobaciones pendientes.',
  },
  settings: {
    title: 'Configuración del Sistema',
    language: 'Idioma',
    theme: 'Tema',
    logLevel: 'Nivel de Registro',
    resetDefaults: 'Restablecer Valores Predeterminados',
  },
  connections: {
    title: 'Subsistema de Conexión Universal',
    connectedSuccess: '¡Conectado a **{target}** con éxito!',
    disconnectedSuccess: 'Desconectado de **{target}**. Credenciales locales purgadas.',
    alreadyConnected: 'El destino **{target}** ya está conectado (estado: `connected`).',
    notConnected: "No hay conexión activa con '{target}'.",
    unrecognizedTarget: "No se reconoce el destino '{target}'.",
    rateLimitExceeded: 'Límite de tasa excedido: puedes ejecutar como máximo 10 comandos de conexión por minuto. Espera un momento.',
    apiKeyPrompt: 'Para conectar **{target}**, proporciona tu {label}:\n`/connect {id} <tu_clave>`',
    localPathPrompt: 'Para conectar **{target}**, indica la ruta del directorio local:\n`/connect {id} /ruta/del/{kind}`',
    oauthDeviceCodePrompt: 'Para completar la autorización del dispositivo para **{target}**:\n1. Abre: {url}\n2. Introduce el código de emparejamiento: `{code}`',
    catalogTitle: 'Catálogo de Conexiones Disponibles',
    noActiveConnections: 'No se encontraron conexiones activas.\n\n• Conectar una integración: `/connect <destino>`\n• Ver catálogo disponible: `/connections catalog`',
    usageConnect: '**Uso del Comando Connect:**\n`/connect <destino> [credencial]`\n\n**Ejemplos:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /ruta/del/vault`\n\nUsa `/connections catalog` para ver todos los destinos disponibles.',
    usageDisconnect: 'Uso: `/disconnect <destino>`\nEjemplo: `/disconnect stripe`',
    handshakeInProgress: 'Ya existe un intento de conexión en curso para este destino.',
    pathVerificationFailed: '❌ Error al verificar la ruta para **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Error en la verificación de la clave para **{target}**: {details}',
    oauthClickLink: '🔗 **Conectar {target}:**\nHaz clic en el enlace de abajo para autorizar a Zavorth:\n[Autorizar {target}]({url})',
    oauthEnded: '⚠️ La autorización OAuth finalizó para **{target}**: {details}',
    activeConnectionsHeader: '**Tus Conexiones Activas ({count}):**',
    catalogEmpty: 'No hay destinos disponibles en el catálogo en este momento.',
    statusHeader: '**Estado de Integridad de las Conexiones:**',
    statusEmpty: 'No hay conexiones activas para mostrar estado.',
    guidanceLabel: '💡 **Orientación:**',
    reconnectHint: '• Para reconectar o actualizar credenciales: `/connect {target} <nuevas_credenciales>`',
    disconnectHint: '• Para desconectar: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Directorio local verificado en: `{path}`',
    credentialsVaultSuffix: 'Credenciales cifradas y almacenadas de forma segura en la bóveda.',
    secretStoreFailed: '❌ Error al almacenar las credenciales cifradas de **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Conectar {target} (Flujo Device Code):**\n1. Abre el enlace de autorización: {url}\n2. Confirma la autorización en tu navegador.\n3. Zavorth completará el handshake automáticamente.',
    missingDeviceVerificationUrl: 'Falta la URL de verificación del dispositivo',
    oauthConnectedSuccess: '✅ ¡Conectado con éxito a **{target}** vía OAuth2!',
    oauthExchangeFailed: '❌ Error en el intercambio de tokens OAuth para **{target}**: {details}',
    oauthListenerFailed: '⚠️ Error al iniciar el listener de callback OAuth: {details}',
    oauthConfigActive: 'La configuración OAuth de **{target}** está activa.',
    catalogConnectHint: 'Para conectar cualquier destino, escribe: `/connect <destino>`',
    statusLabel: 'Estado',
    healthLabel: 'Integridad',
    authLabel: 'Auth',
    connectedAtLabel: 'Conectado el',
    disconnectServiceHint: '• Desconectar un servicio: `/disconnect <destino>`',
  },
};
