import type { LocalizationCatalog } from '../localeContracts.js';

export const es: LocalizationCatalog = {
  common: {
    save: 'Guardar',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    close: 'Cerrar',
    confirm: 'Confirmar',
    delete: 'Eliminar',
    refresh: 'Actualizar',
    retry: 'Reintentar',
    search: 'Buscar...',
    loading: 'Cargando...',
    create: 'Crear',
    creating: 'Creando...',
    clear: 'Limpiar',
    enabled: 'Habilitado',
    disabled: 'Deshabilitado',
    active: 'Activo',
    inactive: 'Inactivo',
    status: 'Estado',
    actions: 'Acciones',
    details: 'Detalles',
    error: 'Error',
    success: 'Éxito',
    none: 'Ninguno',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Suite Autónoma de Ingeniería de IA',
    chat: 'Chat',
    files: 'Archivos',
    approvals: 'Aprobaciones',
    memory: 'Memoria Mnemos',
    plugins: 'Plugins',
    channels: 'Canales',
    settings: 'Configuración',
    workboard: 'Matriz Kanban',
    automations: 'Automatizaciones',
    analytics: 'Métricas',
  },
  chat: {
    placeholder: 'Pregunta a Zavorth o asigna una misión de desarrollo...',
    send: 'Enviar',
    stop: 'Detener',
    clearHistory: 'Borrar Historial',
    emptyState: 'No hay mensajes aún. Envía una instrucción para comenzar.',
    tokens: 'tokens',
    thinking: 'Pensando...',
    errorOccurred: 'Ocurrió un error al generar la respuesta.',
  },
  channels: {
    title: 'Gateway Multicanal',
    description: 'Configura y supervisa puentes de plataformas de mensajería externas.',
    primaryChannel: 'Canal Principal',
    telegram: 'Gateway Telegram',
    discord: 'Gateway Discord',
    slack: 'Gateway Slack',
    whatsapp: 'Gateway WhatsApp',
    web: 'Consola Web',
    notConfigured: 'No Configurado',
    connected: 'Conectado',
    disconnected: 'Desconectado',
  },
  providers: {
    title: 'Enrutador de Modelos LLM',
    description: 'Configura proveedores de IA principales, credenciales y rutas de respaldo.',
    primaryProvider: 'Proveedor Principal',
    primaryModel: 'Modelo Principal',
    fallbackModel: 'Modelo de Respaldo',
    apiKey: 'Clave de API',
    saveRoute: 'Guardar Ruta',
    savedSuccessfully: 'Ruta de IA guardada con éxito.',
    saveFailed: 'Error al guardar la configuración de la ruta de IA.',
  },
  mnemos: {
    title: 'Memoria Persistente Mnemos',
    description: 'Hechos de contexto, recuperación vectorial semántica y conocimiento persistente.',
    searchFacts: 'Buscar hechos memorizados...',
    recall: 'Recordar Conocimiento',
    forget: 'Olvidar Hecho',
    totalFacts: 'Total de Hechos',
    noFactsRecorded: 'No hay hechos memorizados aún.',
  },
  kanban: {
    title: 'Matriz Kanban Swarm',
    description: 'Seguimiento en tiempo real del DAG de tareas, asignaciones y auto-reparación.',
    backlog: 'Pendiente',
    inProgress: 'En Progreso',
    review: 'Revisión',
    autoRepairLane: 'Auto-Reparación',
    done: 'Completado',
    createTask: 'Nueva Tarea',
    taskTitle: 'Título de la Tarea',
    priority: 'Prioridad',
  },
  autoRepair: {
    title: 'Auto-Reparación en Bucle Cerrado',
    description: 'Diagnóstico autónomo, generación de parches quirúrgicos, validación y rollback.',
    resolvingFailure: 'Resolviendo incidente y fallo de código...',
    patchApplied: 'Parche quirúrgico aplicado.',
    testsPassing: 'Pruebas de verificación aprobadas.',
    rollbackRecovered: 'Rollback quirúrgico restaurado con seguridad.',
    incidentHistory: 'Historial de Incidentes',
  },
  codeGraph: {
    title: 'Grafo de Código AST',
    description: 'Definiciones de símbolos, dependencias de llamadas y análisis de impacto.',
    symbolsIndexed: 'Símbolos Indexados',
    callGraph: 'Grafo de Llamadas',
    impactAnalysis: 'Análisis de Impacto',
    callerDependencies: 'Dependencias de Consumidores',
  },
  diffReview: {
    title: 'Revisión Especulativa de Diff',
    description: 'Evaluación de riesgo pre-commit, protección de contratos y auditoría de seguridad.',
    riskRating: 'Clasificación de Riesgo',
    securityAudit: 'Auditoría de Seguridad',
    secretCheck: 'Comprobación de Secretos',
    breakingChanges: 'Comprobación de Contratos Públicos',
    approved: 'Aprobado',
    rejected: 'Rechazado',
  },
  approvals: {
    title: 'Puerta de Seguridad de Ejecución',
    description: 'Revisa y aprueba llamadas a herramientas sensibles, escritura en disco y shell.',
    pendingApprovals: 'Aprobaciones Pendientes',
    approve: 'Aprobar',
    reject: 'Rechazar',
    riskLevel: 'Nivel de Riesgo',
    commandPreview: 'Vista Previa del Comando',
    noPendingApprovals: 'No se requieren aprobaciones pendientes.',
  },
  settings: {
    title: 'Configuración del Sistema',
    language: 'Idioma',
    theme: 'Tema',
    logLevel: 'Nivel de Registro',
    resetDefaults: 'Restablecer Valores Predeterminados',
  },
};
