import type { LocalizationCatalog } from '../localeContracts.js';

export const fr: LocalizationCatalog = {
  common: {
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    cancel: 'Annuler',
    close: 'Fermer',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    refresh: 'Actualiser',
    retry: 'Réessayer',
    search: 'Rechercher...',
    loading: 'Chargement...',
    create: 'Créer',
    creating: 'Création...',
    clear: 'Effacer',
    enabled: 'Activé',
    disabled: 'Désactivé',
    active: 'Actif',
    inactive: 'Inactif',
    status: 'Statut',
    actions: 'Actions',
    details: 'Détails',
    error: 'Erreur',
    success: 'Succès',
    none: 'Aucun',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Suite Autonome d’Ingénierie IA',
    chat: 'Discussion',
    files: 'Fichiers',
    approvals: 'Approbations',
    memory: 'Mémoire Mnemos',
    plugins: 'Extensions',
    channels: 'Canaux',
    settings: 'Paramètres',
    workboard: 'Matrice Kanban',
    automations: 'Automatisations',
    analytics: 'Analytique',
  },
  chat: {
    placeholder: 'Posez une question à Zavorth ou assignez une mission...',
    send: 'Envoyer',
    stop: 'Arrêter',
    clearHistory: 'Effacer l’historique',
    emptyState: 'Aucun message. Envoyez une commande pour commencer.',
    tokens: 'jetons',
    thinking: 'Réflexion...',
    errorOccurred: 'Une erreur s’est produite lors de la génération de la réponse.',
  },
  channels: {
    title: 'Passerelle Multicanal',
    description: 'Configurez et surveillez les ponts de messagerie externes.',
    primaryChannel: 'Canal Principal',
    telegram: 'Passerelle Telegram',
    discord: 'Passerelle Discord',
    slack: 'Passerelle Slack',
    whatsapp: 'Passerelle WhatsApp',
    web: 'Console Web',
    notConfigured: 'Non Configuré',
    connected: 'Connecté',
    disconnected: 'Déconnecté',
  },
  providers: {
    title: 'Routeur de Modèles LLM',
    description: 'Configurez les fournisseurs IA principaux, les clés API et les routes de secours.',
    primaryProvider: 'Fournisseur Principal',
    primaryModel: 'Modèle Principal',
    fallbackModel: 'Modèle de Secours',
    apiKey: 'Clé API',
    saveRoute: 'Enregistrer la Route',
    savedSuccessfully: 'Route IA enregistrée avec succès.',
    saveFailed: 'Échec de l’enregistrement de la route IA.',
  },
  mnemos: {
    title: 'Mémoire Persistante Mnemos',
    description: 'Faits contextuels, recherche vectorielle sémantique et rétention de connaissances.',
    searchFacts: 'Rechercher des faits mémorisés...',
    recall: 'Rappeler les connaissances',
    forget: 'Oublier le fait',
    totalFacts: 'Total des Faits',
    noFactsRecorded: 'Aucun fait mémorisé pour le moment.',
  },
  kanban: {
    title: 'Matrice Kanban Swarm',
    description: 'Suivi du DAG des tâches en temps réel, affectations et réparations.',
    backlog: 'À faire',
    inProgress: 'En cours',
    review: 'Revue',
    autoRepairLane: 'Auto-Réparation',
    done: 'Terminé',
    createTask: 'Nouvelle Tâche',
    taskTitle: 'Titre de la Tâche',
    priority: 'Priorité',
  },
  autoRepair: {
    title: 'Auto-Réparation en Boucle Fermée',
    description: 'Diagnostic autonome, génération de correctifs, validation et restauration.',
    resolvingFailure: 'Résolution de l’incident de code...',
    patchApplied: 'Correctif chirurgical appliqué.',
    testsPassing: 'Tests de vérification réussis.',
    rollbackRecovered: 'Restauration sécurisée effectuée.',
    incidentHistory: 'Historique des Incidents',
  },
  codeGraph: {
    title: 'Graphe de Code AST',
    description: 'Définitions de symboles, dépendances d’appels et analyse d’impact.',
    symbolsIndexed: 'Symboles Indexés',
    callGraph: 'Graphe d’Appels',
    impactAnalysis: 'Analyse d’Impact',
    callerDependencies: 'Dépendances des Appelants',
  },
  diffReview: {
    title: 'Revue Spéculative de Diff',
    description: 'Évaluation des risques pré-commit, protection des contrats et audit de sécurité.',
    riskRating: 'Évaluation du Risque',
    securityAudit: 'Audit de Sécurité',
    secretCheck: 'Vérification des Secrets',
    breakingChanges: 'Vérification des Contrats Publics',
    approved: 'Approuvé',
    rejected: 'Rejeté',
  },
  approvals: {
    title: 'Barrière de Sécurité d’Exécution',
    description: 'Examinez et approuvez les appels d’outils sensibles, l’écriture disque et le shell.',
    pendingApprovals: 'Approbations en Attente',
    approve: 'Approuver',
    reject: 'Rejeter',
    riskLevel: 'Niveau de Risque',
    commandPreview: 'Aperçu de la Commande',
    noPendingApprovals: 'Aucune approbation en attente requise.',
  },
  settings: {
    title: 'Paramètres Système',
    language: 'Langue',
    theme: 'Thème',
    logLevel: 'Niveau de Journalisation',
    resetDefaults: 'Rétablir les Valeurs par Défaut',
  },
};
