import type { LocalizationCatalog } from '../localeContracts.js';

export const fr: LocalizationCatalog = {
  common: {
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    cancel: 'Annuler',
    close: 'Fermer',
    confirm: 'Confirmer',
    delete: 'Supprimer',
    refresh: 'Actualiser',
    retry: 'Réessayer',
    search: 'Rechercher...',
    loading: 'Chargement...',
    create: 'Créer',
    creating: 'Création...',
    clear: 'Effacer',
    enabled: 'Activé',
    disabled: 'Désactivé',
    active: 'Actif',
    inactive: 'Inactif',
    status: 'Statut',
    actions: 'Actions',
    details: 'Détails',
    error: 'Erreur',
    success: 'Succès',
    none: 'Aucun',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Suite Autonome d’Ingénierie IA',
    chat: 'Discussion',
    files: 'Fichiers',
    approvals: 'Approbations',
    memory: 'Mémoire Mnemos',
    plugins: 'Extensions',
    channels: 'Canaux',
    settings: 'Paramètres',
    workboard: 'Matrice Kanban',
    automations: 'Automatisations',
    analytics: 'Analytique',
  },
  chat: {
    placeholder: 'Posez une question à Zavorth ou assignez une mission...',
    send: 'Envoyer',
    stop: 'Arrêter',
    clearHistory: 'Effacer l’historique',
    emptyState: 'Aucun message. Envoyez une commande pour commencer.',
    tokens: 'jetons',
    thinking: 'Réflexion...',
    errorOccurred: 'Une erreur s’est produite lors de la génération de la réponse.',
  },
  channels: {
    title: 'Passerelle Multicanal',
    description: 'Configurez et surveillez les ponts de messagerie externes.',
    primaryChannel: 'Canal Principal',
    telegram: 'Passerelle Telegram',
    discord: 'Passerelle Discord',
    slack: 'Passerelle Slack',
    whatsapp: 'Passerelle WhatsApp',
    web: 'Console Web',
    notConfigured: 'Non Configuré',
    connected: 'Connecté',
    disconnected: 'Déconnecté',
  },
  providers: {
    title: 'Routeur de Modèles LLM',
    description: 'Configurez les fournisseurs IA principaux, les clés API et les routes de secours.',
    primaryProvider: 'Fournisseur Principal',
    primaryModel: 'Modèle Principal',
    fallbackModel: 'Modèle de Secours',
    apiKey: 'Clé API',
    saveRoute: 'Enregistrer la Route',
    savedSuccessfully: 'Route IA enregistrée avec succès.',
    saveFailed: 'Échec de l’enregistrement de la route IA.',
  },
  mnemos: {
    title: 'Mémoire Persistante Mnemos',
    description: 'Faits contextuels, recherche vectorielle sémantique et rétention de connaissances.',
    searchFacts: 'Rechercher des faits mémorisés...',
    recall: 'Rappeler les connaissances',
    forget: 'Oublier le fait',
    totalFacts: 'Total des Faits',
    noFactsRecorded: 'Aucun fait mémorisé pour le moment.',
  },
  kanban: {
    title: 'Matrice Kanban Swarm',
    description: 'Suivi du DAG des tâches en temps réel, affectations et réparations.',
    backlog: 'À faire',
    inProgress: 'En cours',
    review: 'Revue',
    autoRepairLane: 'Auto-Réparation',
    done: 'Terminé',
    createTask: 'Nouvelle Tâche',
    taskTitle: 'Titre de la Tâche',
    priority: 'Priorité',
  },
  autoRepair: {
    title: 'Auto-Réparation en Boucle Fermée',
    description: 'Diagnostic autonome, génération de correctifs, validation et restauration.',
    resolvingFailure: 'Résolution de l’incident de code...',
    patchApplied: 'Correctif chirurgical appliqué.',
    testsPassing: 'Tests de vérification réussis.',
    rollbackRecovered: 'Restauration sécurisée effectuée.',
    incidentHistory: 'Historique des Incidents',
  },
  codeGraph: {
    title: 'Graphe de Code AST',
    description: 'Définitions de symboles, dépendances d’appels et analyse d’impact.',
    symbolsIndexed: 'Symboles Indexés',
    callGraph: 'Graphe d’Appels',
    impactAnalysis: 'Analyse d’Impact',
    callerDependencies: 'Dépendances des Appelants',
  },
  diffReview: {
    title: 'Revue Spéculative de Diff',
    description: 'Évaluation des risques pré-commit, protection des contrats et audit de sécurité.',
    riskRating: 'Évaluation du Risque',
    securityAudit: 'Audit de Sécurité',
    secretCheck: 'Vérification des Secrets',
    breakingChanges: 'Vérification des Contrats Publics',
    approved: 'Approuvé',
    rejected: 'Rejeté',
  },
  approvals: {
    title: 'Barrière de Sécurité d’Exécution',
    description: 'Examinez et approuvez les appels d’outils sensibles, l’écriture disque et le shell.',
    pendingApprovals: 'Approbations en Attente',
    approve: 'Approuver',
    reject: 'Rejeter',
    riskLevel: 'Niveau de Risque',
    commandPreview: 'Aperçu de la Commande',
    noPendingApprovals: 'Aucune approbation en attente requise.',
  },
  settings: {
    title: 'Paramètres Système',
    language: 'Langue',
    theme: 'Thème',
    logLevel: 'Niveau de Journalisation',
    resetDefaults: 'Rétablir les Valeurs par Défaut',
  },
  connections: {
    title: 'Sous-système de Connexion Universel',
    connectedSuccess: 'Connecté à **{target}** avec succès !',
    disconnectedSuccess: 'Déconnecté de **{target}**. Identifiants locaux purgés.',
    alreadyConnected: "La cible **{target}** est déjà connectée (statut : `connected`).",
    notConnected: "Aucune connexion active avec '{target}'.",
    unrecognizedTarget: "La cible '{target}' n'est pas reconnue.",
    rateLimitExceeded: 'Limite de débit dépassée : vous pouvez exécuter au maximum 10 commandes de connexion par minute. Veuillez patienter.',
    apiKeyPrompt: 'Pour connecter **{target}**, fournissez votre {label} :\n`/connect {id} <votre_cle>`',
    localPathPrompt: 'Pour connecter **{target}**, indiquez le chemin du répertoire local :\n`/connect {id} /chemin/du/{kind}`',
    oauthDeviceCodePrompt: "Pour terminer l'autorisation de l'appareil pour **{target}** :\n1. Ouvrez : {url}\n2. Saisissez le code d'appairage : `{code}`",
    catalogTitle: 'Catalogue des Connexions Disponibles',
    noActiveConnections: 'Aucune connexion active trouvée.\n\n• Connecter une intégration : `/connect <cible>`\n• Voir le catalogue disponible : `/connections catalog`',
    usageConnect: '**Utilisation de la Commande Connect :**\n`/connect <cible> [identifiants]`\n\n**Exemples :**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /chemin/du/vault`\n\nUtilisez `/connections catalog` pour voir toutes les cibles disponibles.',
    usageDisconnect: 'Utilisation : `/disconnect <cible>`\nExemple : `/disconnect stripe`',
    handshakeInProgress: 'Une tentative de connexion est déjà en cours pour cette cible.',
    pathVerificationFailed: '❌ Échec de la vérification du chemin pour **{target}** : {details}',
    apiKeyVerificationFailed: '❌ Échec de la vérification de la clé pour **{target}** : {details}',
    oauthClickLink: '🔗 **Connecter {target} :**\nCliquez sur le lien ci-dessous pour autoriser Zavorth :\n[Autoriser {target}]({url})',
    oauthEnded: "⚠️ L'autorisation OAuth est terminée pour **{target}** : {details}",
    activeConnectionsHeader: '**Vos Connexions Actives ({count}) :**',
    catalogEmpty: 'Aucune cible disponible dans le catalogue pour le moment.',
    statusHeader: "**État de Santé des Connexions :**",
    statusEmpty: 'Aucune connexion active pour afficher un statut.',
    guidanceLabel: '💡 **Conseil :**',
    reconnectHint: '• Reconnecter ou mettre à jour les identifiants : `/connect {target} <nouveaux_identifiants>`',
    disconnectHint: '• Déconnecter : `/disconnect {target}`',
    localPathVerifiedSuffix: 'Répertoire local vérifié à : `{path}`',
    credentialsVaultSuffix: 'Identifiants chiffrés et stockés en toute sécurité dans le coffre.',
    secretStoreFailed: "❌ Échec du stockage des identifiants chiffrés pour **{target}** : {details}",
    deviceCodeFlowInstructions: '🔑 **Connecter {target} (Flux Device Code) :**\n1. Ouvrez le lien d\'autorisation : {url}\n2. Confirmez l\'autorisation dans votre navigateur.\n3. Zavorth terminera le handshake automatiquement.',
    missingDeviceVerificationUrl: 'URL de vérification de l\'appareil manquante',
    oauthConnectedSuccess: '✅ Connecté avec succès à **{target}** via OAuth2 !',
    oauthExchangeFailed: '❌ Échec de l\'échange de tokens OAuth pour **{target}** : {details}',
    oauthListenerFailed: '⚠️ Échec du démarrage du listener de callback OAuth : {details}',
    oauthConfigActive: 'La configuration OAuth de **{target}** est active.',
    catalogConnectHint: 'Pour connecter n\'importe quelle cible, tapez : `/connect <cible>`',
    statusLabel: 'Statut',
    healthLabel: 'Santé',
    authLabel: 'Auth',
    connectedAtLabel: 'Connecté le',
    disconnectServiceHint: '• Déconnecter un service : `/disconnect <cible>`',
  },
};
