import type { LocalizationCatalog } from '../localeContracts.js';

export const ga: LocalizationCatalog = {
  common: {
    save: 'Sábháil',
    saving: 'Ag sábháil...',
    cancel: 'Cealaigh',
    close: 'Dún',
    confirm: 'Deimhnigh',
    delete: 'Scrios',
    refresh: 'Athnuaigh',
    retry: 'Bain triail eile as',
    search: 'Cuardaigh...',
    loading: 'Ag lódáil...',
    create: 'Cruthaigh',
    creating: 'Ag cruthú...',
    clear: 'Glan',
    enabled: 'Cumasaithe',
    disabled: 'Díchumasaithe',
    active: 'Gníomhach',
    inactive: 'Neamhghníomhach',
    status: 'Stádas',
    actions: 'Gníomhartha',
    details: 'Sonraí',
    error: 'Earráid',
    success: 'D’éirigh leis',
    none: 'Dada',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Sraith Forbartha Saorga Neamhspleách',
    chat: 'Comhrá',
    files: 'Comhaid',
    approvals: 'Ceaduithe',
    memory: 'Cuimhne Mnemos',
    plugins: 'Breiseáin',
    channels: 'Cainéil',
    settings: 'Socruithe',
    workboard: 'Maitrís Kanban',
    automations: 'Uathoibrithe',
    analytics: 'Anailísíocht',
  },
  chat: {
    placeholder: 'Cuir ceist ar Zavorth nó tabhair tasc forbartha...',
    send: 'Seol',
    stop: 'Stop',
    clearHistory: 'Glan Stair',
    emptyState: 'Níl aon teachtaireachtaí fós. Seol ordú chun tosú.',
    tokens: 'comharthaí',
    thinking: 'Ag smaoineamh...',
    errorOccurred: 'Tharla earráid agus an freagra á ghiniúint.',
  },
  channels: {
    title: 'Geata Iolchainéil',
    description: 'Cumraigh agus déan monatóireacht ar dhroichead ardáin teachtaireachtaí.',
    primaryChannel: 'Príomhchainéal',
    telegram: 'Geata Telegram',
    discord: 'Geata Discord',
    slack: 'Geata Slack',
    whatsapp: 'Geata WhatsApp',
    web: 'Consól Gréasáin',
    notConfigured: 'Gan Chumrú',
    connected: 'Ceangailte',
    disconnected: 'Dícheangailte',
  },
  providers: {
    title: 'Ródaire Samhlacha LLM',
    description: 'Cumraigh príomhsholáthraithe AI, eochracha API agus bealaí cúltaca.',
    primaryProvider: 'Príomhsholáthraí',
    primaryModel: 'Príomhshamhail',
    fallbackModel: 'Samhail Chúltaca',
    apiKey: 'Eochair API',
    saveRoute: 'Sábháil Bealach',
    savedSuccessfully: 'Bealach AI sábháilte go rathúil.',
    saveFailed: 'Theip ar shábháil chumraíocht an bhealaigh AI.',
  },
  mnemos: {
    title: 'Banchuimhne Bhuan Mnemos',
    description: 'Fíricí comhthéacs, cuardach veicteoireach agus coinneáil eolais.',
    searchFacts: 'Cuardaigh fíricí a mheabhraítear...',
    recall: 'Aisghabháil Eolais',
    forget: 'Dearmad a dhéanamh ar fhíric',
    totalFacts: 'Fíricí Iomlána',
    noFactsRecorded: 'Níl aon fhíricí cuimhne taifeadta fós.',
  },
  kanban: {
    title: 'Maitrís Kanban Swarm',
    description: 'Dul chun cinn tascanna i bhfíor-am, sannacháin oibrithe agus deisiú.',
    backlog: 'Cúlriaráiste',
    inProgress: 'Ar Siúl',
    review: 'Athbhreithniú',
    autoRepairLane: 'Uathdheisiú',
    done: 'Déanta',
    createTask: 'Tasc Nua',
    taskTitle: 'Teideal an Taisc',
    priority: 'Tosaíocht',
  },
  autoRepair: {
    title: 'Uathdheisiú Lúb Dúnta',
    description: 'Diagnóis neamhspleách, giniúint paistí, bailíochtú tástálacha agus rolladh siar.',
    resolvingFailure: 'Teip cóid á réiteach...',
    patchApplied: 'Paiste máinliachta curtha i bhfeidhm.',
    testsPassing: 'Tástálacha fíoraithe rite go rathúil.',
    rollbackRecovered: 'Rolladh siar sábháilte aisghafa.',
    incidentHistory: 'Stair na dTeagmhas',
  },
  codeGraph: {
    title: 'Graf Chódchruinne AST',
    description: 'Sainmhínithe siombailí, spleáchais ghlaonna agus anailís tionchair.',
    symbolsIndexed: 'Siombailí Innéacsaithe',
    callGraph: 'Graf Glaonna',
    impactAnalysis: 'Anailís Tionchair',
    callerDependencies: 'Spleáchais Ghlaoiteora',
  },
  diffReview: {
    title: 'Athbhreithniú Tuairimíochta Diff',
    description: 'Scóráil riosca réamh-ghealltanais, cosaint conarthaí agus iniúchadh slándála.',
    riskRating: 'Rátáil Riosca',
    securityAudit: 'Iniúchadh Slándála',
    secretCheck: 'Seiceáil Sceite Rúin',
    breakingChanges: 'Seiceáil Briste Conarthaí Poiblí',
    approved: 'Ceadaithe',
    rejected: 'Diúltaithe',
  },
  approvals: {
    title: 'Geata Slándála Forghníomhaithe',
    description: 'Déan athbhreithniú ar ghlaonna uirlisí íogaire, scríobh comhad agus orduithe bhlaosc.',
    pendingApprovals: 'Ceaduithe ar Feitheamh',
    approve: 'Ceadaigh',
    reject: 'Diúltaigh',
    riskLevel: 'Leibhéal Riosca',
    commandPreview: 'Réamhamharc ar an Ordú',
    noPendingApprovals: 'Níl aon cheaduithe ar feitheamh ag teastáil.',
  },
  settings: {
    title: 'Socruithe Córais',
    language: 'Teanga',
    theme: 'Téama',
    logLevel: 'Leibhéal Loga',
    resetDefaults: 'Athshocraigh go Réamhshocruithe',
  },
};
