import type { LocalizationCatalog } from '../localeContracts.js';

export const ga: LocalizationCatalog = {
  common: {
    save: 'Sábháil',
    saving: 'Ag sábháil...',
    cancel: 'Cealaigh',
    close: 'Dún',
    confirm: 'Deimhnigh',
    delete: 'Scrios',
    refresh: 'Athnuaigh',
    retry: 'Bain triail eile as',
    search: 'Cuardaigh...',
    loading: 'Ag lódáil...',
    create: 'Cruthaigh',
    creating: 'Ag cruthú...',
    clear: 'Glan',
    enabled: 'Cumasaithe',
    disabled: 'Díchumasaithe',
    active: 'Gníomhach',
    inactive: 'Neamhghníomhach',
    status: 'Stádas',
    actions: 'Gníomhartha',
    details: 'Sonraí',
    error: 'Earráid',
    success: 'D’éirigh leis',
    none: 'Dada',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Sraith Forbartha Saorga Neamhspleách',
    chat: 'Comhrá',
    files: 'Comhaid',
    approvals: 'Ceaduithe',
    memory: 'Cuimhne Mnemos',
    plugins: 'Breiseáin',
    channels: 'Cainéil',
    settings: 'Socruithe',
    workboard: 'Maitrís Kanban',
    automations: 'Uathoibrithe',
    analytics: 'Anailísíocht',
  },
  chat: {
    placeholder: 'Cuir ceist ar Zavorth nó tabhair tasc forbartha...',
    send: 'Seol',
    stop: 'Stop',
    clearHistory: 'Glan Stair',
    emptyState: 'Níl aon teachtaireachtaí fós. Seol ordú chun tosú.',
    tokens: 'comharthaí',
    thinking: 'Ag smaoineamh...',
    errorOccurred: 'Tharla earráid agus an freagra á ghiniúint.',
  },
  channels: {
    title: 'Geata Iolchainéil',
    description: 'Cumraigh agus déan monatóireacht ar dhroichead ardáin teachtaireachtaí.',
    primaryChannel: 'Príomhchainéal',
    telegram: 'Geata Telegram',
    discord: 'Geata Discord',
    slack: 'Geata Slack',
    whatsapp: 'Geata WhatsApp',
    web: 'Consól Gréasáin',
    notConfigured: 'Gan Chumrú',
    connected: 'Ceangailte',
    disconnected: 'Dícheangailte',
  },
  providers: {
    title: 'Ródaire Samhlacha LLM',
    description: 'Cumraigh príomhsholáthraithe AI, eochracha API agus bealaí cúltaca.',
    primaryProvider: 'Príomhsholáthraí',
    primaryModel: 'Príomhshamhail',
    fallbackModel: 'Samhail Chúltaca',
    apiKey: 'Eochair API',
    saveRoute: 'Sábháil Bealach',
    savedSuccessfully: 'Bealach AI sábháilte go rathúil.',
    saveFailed: 'Theip ar shábháil chumraíocht an bhealaigh AI.',
  },
  mnemos: {
    title: 'Banchuimhne Bhuan Mnemos',
    description: 'Fíricí comhthéacs, cuardach veicteoireach agus coinneáil eolais.',
    searchFacts: 'Cuardaigh fíricí a mheabhraítear...',
    recall: 'Aisghabháil Eolais',
    forget: 'Dearmad a dhéanamh ar fhíric',
    totalFacts: 'Fíricí Iomlána',
    noFactsRecorded: 'Níl aon fhíricí cuimhne taifeadta fós.',
  },
  kanban: {
    title: 'Maitrís Kanban Swarm',
    description: 'Dul chun cinn tascanna i bhfíor-am, sannacháin oibrithe agus deisiú.',
    backlog: 'Cúlriaráiste',
    inProgress: 'Ar Siúl',
    review: 'Athbhreithniú',
    autoRepairLane: 'Uathdheisiú',
    done: 'Déanta',
    createTask: 'Tasc Nua',
    taskTitle: 'Teideal an Taisc',
    priority: 'Tosaíocht',
  },
  autoRepair: {
    title: 'Uathdheisiú Lúb Dúnta',
    description: 'Diagnóis neamhspleách, giniúint paistí, bailíochtú tástálacha agus rolladh siar.',
    resolvingFailure: 'Teip cóid á réiteach...',
    patchApplied: 'Paiste máinliachta curtha i bhfeidhm.',
    testsPassing: 'Tástálacha fíoraithe rite go rathúil.',
    rollbackRecovered: 'Rolladh siar sábháilte aisghafa.',
    incidentHistory: 'Stair na dTeagmhas',
  },
  codeGraph: {
    title: 'Graf Chódchruinne AST',
    description: 'Sainmhínithe siombailí, spleáchais ghlaonna agus anailís tionchair.',
    symbolsIndexed: 'Siombailí Innéacsaithe',
    callGraph: 'Graf Glaonna',
    impactAnalysis: 'Anailís Tionchair',
    callerDependencies: 'Spleáchais Ghlaoiteora',
  },
  diffReview: {
    title: 'Athbhreithniú Tuairimíochta Diff',
    description: 'Scóráil riosca réamh-ghealltanais, cosaint conarthaí agus iniúchadh slándála.',
    riskRating: 'Rátáil Riosca',
    securityAudit: 'Iniúchadh Slándála',
    secretCheck: 'Seiceáil Sceite Rúin',
    breakingChanges: 'Seiceáil Briste Conarthaí Poiblí',
    approved: 'Ceadaithe',
    rejected: 'Diúltaithe',
  },
  approvals: {
    title: 'Geata Slándála Forghníomhaithe',
    description: 'Déan athbhreithniú ar ghlaonna uirlisí íogaire, scríobh comhad agus orduithe bhlaosc.',
    pendingApprovals: 'Ceaduithe ar Feitheamh',
    approve: 'Ceadaigh',
    reject: 'Diúltaigh',
    riskLevel: 'Leibhéal Riosca',
    commandPreview: 'Réamhamharc ar an Ordú',
    noPendingApprovals: 'Níl aon cheaduithe ar feitheamh ag teastáil.',
  },
  settings: {
    title: 'Socruithe Córais',
    language: 'Teanga',
    theme: 'Téama',
    logLevel: 'Leibhéal Loga',
    resetDefaults: 'Athshocraigh go Réamhshocruithe',
  },
  connections: {
    title: 'Fóchóras Uilíoch Nasc',
    connectedSuccess: 'D\'eistear go rathúil le **{target}**!',
    disconnectedSuccess: 'Díceangadh ó **{target}**. Baintear creidmheasanna áitiúla.',
    alreadyConnected: 'Tá an sprioc **{target}** ceangailte cheana féin (stádas: `connected`).',
    notConnected: "Níl aon nasc gníomhach le '{target}'.",
    unrecognizedTarget: "Ní aithnítear an sprioc '{target}'.",
    rateLimitExceeded: 'Sáraíodh an teorainn ráta: is féidir 10 n-ordú nasc ar a mhéad a rith in aghaidh na nóiméide. Fan go fóill, le do thoil.',
    apiKeyPrompt: 'Chun **{target}** a nascadh, cuir do {label} ar fáil:\n`/connect {id} <d_eochair>`',
    localPathPrompt: 'Chun **{target}** a nascadh, sonraigh conair an fhillteáin áitiúil:\n`/connect {id} /conair/na/{kind}`',
    oauthDeviceCodePrompt: 'Chun údarú an fheiste a chur i gcrích le haghaidh **{target}**:\n1. Oscail: {url}\n2. Cuir isteach an cód péireála: `{code}`',
    catalogTitle: 'Catalóg na Nascanna atá ar Fáil',
    noActiveConnections: 'Níor aimsíodh aon naisc ghníomhacha.\n\n• Ceangail comhtháthú: `/connect <sprioc>`\n• Féach ar an gcatalóg: `/connections catalog`',
    usageConnect: '**Úsáid an Ordaithe Connect:**\n`/connect <sprioc> [creidmheas]`\n\n**Samplaí:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /conair/vault`\n\nBain úsáid as `/connections catalog` chun gach sprioc a fheiceáil.',
    usageDisconnect: 'Úsáid: `/disconnect <sprioc>`\nSampla: `/disconnect stripe`',
    handshakeInProgress: 'Tá iarracht nasc ar siúl cheana féin don sprioc seo.',
    pathVerificationFailed: '❌ Theip ar fhíorú conaire le haghaidh **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Theip ar fhíorú eochrach le haghaidh **{target}**: {details}',
    oauthClickLink: '🔗 **Nasc {target}:**\nCliceáil ar an nasc thíos chun Zavorth a údarú:\n[Údaraigh {target}]({url})',
    oauthEnded: '⚠️ Tháinig deireadh le húdarú OAuth le haghaidh **{target}**: {details}',
    activeConnectionsHeader: '**Do Naisc Ghníomhacha ({count}):**',
    catalogEmpty: 'Níl aon spriocanna ar fáil sa chatalóg nasc faoi láthair.',
    statusHeader: '**Stádas Sláinte na Nascanna:**',
    statusEmpty: 'Níl aon naisc ghníomhacha le stádas a thuairisciú.',
    guidanceLabel: '💡 **Treoireacht:**',
    reconnectHint: '• Athnasc nó creidmheasanna a nuashonrú: `/connect {target} <creidmheasanna_nua>`',
    disconnectHint: '• Díceangail: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Fillteán áitiúil deimhnithe: `{path}`',
    credentialsVaultSuffix: 'Tá creidmheasanna criptithe agus stóráilte go slán sa taisce.',
    secretStoreFailed: '❌ Theip ar stóráil creidmheasanna criptithe le haghaidh **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Nasc {target} (Sreabhadh Cód Feiste):**\n1. Oscail an nasc údraithe: {url}\n2. Deimhnigh an t-údarú i do bhrabhsálaí.\n3. Críochnóidh Zavorth an lámhchaidreamh go huathoibríoch.',
    missingDeviceVerificationUrl: 'URL fíoraithe feiste ar iarraidh',
    oauthConnectedSuccess: '✅ D\'eistear go rathúil le **{target}** trí OAuth2!',
    oauthExchangeFailed: '❌ Theip ar mhalartán comharthaí OAuth le haghaidh **{target}**: {details}',
    oauthListenerFailed: '⚠️ Theip ar thosú éisteoir athghlao OAuth: {details}',
    oauthConfigActive: 'Tá cumraíocht OAuth le haghaidh **{target}** gníomhach.',
    catalogConnectHint: 'Chun aon sprioc a nascadh, clóscríobh: `/connect <sprioc>`',
    statusLabel: 'Stádas',
    healthLabel: 'Sláinte',
    authLabel: 'Fíorú',
    connectedAtLabel: 'Ceangailte ag',
    disconnectServiceHint: '• Díceangail seirbhís: `/disconnect <sprioc>`',
  },
};
