import type { LocalizationCatalog } from '../localeContracts.js';

export const hu: LocalizationCatalog = {
  common: {
    save: 'Mentés',
    saving: 'Mentés...',
    cancel: 'Mégse',
    close: 'Bezárás',
    confirm: 'Megerősítés',
    delete: 'Törlés',
    refresh: 'Frissítés',
    retry: 'Újrapróbálkozás',
    search: 'Keresés...',
    loading: 'Betöltés...',
    create: 'Létrehozás',
    creating: 'Létrehozás...',
    clear: 'Törlés',
    enabled: 'Engedélyezve',
    disabled: 'Letiltva',
    active: 'Aktív',
    inactive: 'Inaktív',
    status: 'Állapot',
    actions: 'Műveletek',
    details: 'Részletek',
    error: 'Hiba',
    success: 'Sikeres',
    none: 'Nincs',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Autonóm MI Fejlesztői Környezet',
    chat: 'Csevegés',
    files: 'Fájlok',
    approvals: 'Jóváhagyások',
    memory: 'Mnemos Memória',
    plugins: 'Bővítmények',
    channels: 'Csatornák',
    settings: 'Beállítások',
    workboard: 'Kanban Mátrix',
    automations: 'Automatizálások',
    analytics: 'Elemzések',
  },
  chat: {
    placeholder: 'Kérdezzen a Zavorth-tól vagy rendeljen hozzá fejlesztési feladatot...',
    send: 'Küldés',
    stop: 'Leállítás',
    clearHistory: 'Előzmények törlése',
    emptyState: 'Még nincsenek üzenetek. Küldjön parancsot a kezdéshez.',
    tokens: 'token',
    thinking: 'Gondolkodás...',
    errorOccurred: 'Hiba történt a válasz generálása közben.',
  },
  channels: {
    title: 'Többcsatornás Átjáró',
    description: 'Külső üzenetküldő platformok hídjainak konfigurálása és felügyelete.',
    primaryChannel: 'Elsődleges Csatorna',
    telegram: 'Telegram Átjáró',
    discord: 'Discord Átjáró',
    slack: 'Slack Átjáró',
    whatsapp: 'WhatsApp Átjáró',
    web: 'Webkonzol',
    notConfigured: 'Nincs Beállítva',
    connected: 'Csatlakozva',
    disconnected: 'Leválasztva',
  },
  providers: {
    title: 'LLM Modell Útválasztó',
    description: 'Elsődleges MI-szolgáltatók, API-kulcsok és tartalék útvonalak beállítása.',
    primaryProvider: 'Elsődleges Szolgáltató',
    primaryModel: 'Elsődleges Modell',
    fallbackModel: 'Tartalék Modell',
    apiKey: 'API Kulcs',
    saveRoute: 'Útvonal Mentése',
    savedSuccessfully: 'MI útvonal sikeresen mentve.',
    saveFailed: 'Nem sikerült menteni az MI útvonal beállításait.',
  },
  mnemos: {
    title: 'Mnemos Állandó Memória',
    description: 'Kontextus tények, szemantikus vektorkeresés és munkamenet-közi tudásmegőrzés.',
    searchFacts: 'Mentett tények keresése...',
    recall: 'Tudás Felidézése',
    forget: 'Tény Elfelejtése',
    totalFacts: 'Összes Tény',
    noFactsRecorded: 'Még nincsenek rögzített memóriatények.',
  },
  kanban: {
    title: 'Swarm Kanban Mátrix',
    description: 'Valós idejű feladat-DAG haladás, munkatárs-hozzárendelések és javítási állapot.',
    backlog: 'Hátralék',
    inProgress: 'Folyamatban',
    review: 'Felülvizsgálat',
    autoRepairLane: 'Automatikus Javítás',
    done: 'Kész',
    createTask: 'Új Feladat',
    taskTitle: 'Feladat Címe',
    priority: 'Prioritás',
  },
  autoRepair: {
    title: 'Zárt Láncú Automatikus Javítás',
    description: 'Autonóm diagnosztika, javítófolt-generálás, tesztvalidáció és visszagörgetés.',
    resolvingFailure: 'Kódhiba elhárítása folyamatban...',
    patchApplied: 'Sebészeti javítás alkalmazva.',
    testsPassing: 'Ellenőrző tesztek sikeresek.',
    rollbackRecovered: 'Biztonságos visszagörgetés helyreállítva.',
    incidentHistory: 'Eseménytörténet',
  },
  codeGraph: {
    title: 'AST Kódbázis Gráf',
    description: 'Szimbólumdefiníciók, fájlok közötti hívásfüggőségek és hatáselemzés.',
    symbolsIndexed: 'Indexelt Szimbólumok',
    callGraph: 'Hívási Gráf',
    impactAnalysis: 'Hatáselemzés',
    callerDependencies: 'Hívó Függőségei',
  },
  diffReview: {
    title: 'Spekulatív Diff Felülvizsgálat',
    description: 'Commit előtti kockázatértékelés, szerződésvédelem és biztonsági audit.',
    riskRating: 'Kockázati Besorolás',
    securityAudit: 'Biztonsági Audit',
    secretCheck: 'Titokszivárgás Ellenőrzése',
    breakingChanges: 'Publikus Szerződés Törés Ellenőrzése',
    approved: 'Jóváhagyva',
    rejected: 'Elutasítva',
  },
  approvals: {
    title: 'Végrehajtási Biztonsági Kapu',
    description: 'Érzékeny eszközhívások, fájlírások és shell parancsok áttekintése és jóváhagyása.',
    pendingApprovals: 'Függőben Lévő Jóváhagyások',
    approve: 'Jóváhagyás',
    reject: 'Elutasítás',
    riskLevel: 'Kockázati Szint',
    commandPreview: 'Parancs Előnézete',
    noPendingApprovals: 'Nincs szükség függőben lévő jóváhagyásra.',
  },
  settings: {
    title: 'Rendszerbeállítások',
    language: 'Nyelv',
    theme: 'Téma',
    logLevel: 'Naplózási Szint',
    resetDefaults: 'Alapértelmezések Visszaállítása',
  },
  connections: {
    title: 'Univerzális Kapcsolat-Alrendszer',
    connectedSuccess: 'Sikeresen kapcsolódva a következőhöz: **{target}**!',
    disconnectedSuccess: 'Kapcsolat bontva: **{target}**. Helyi hitelesítési adatok törölve.',
    alreadyConnected: 'A **{target}** cél már csatlakoztatva van (állapot: `connected`).',
    notConnected: "Nincs aktív kapcsolat a következővel: '{target}'.",
    unrecognizedTarget: "A '{target}' cél nem ismerhető fel.",
    rateLimitExceeded: 'Sebességkorlát túllépve: percenként legfeljebb 10 kapcsolódási parancs hajtható végre. Kérjük, várjon.',
    apiKeyPrompt: 'A **{target}** kapcsolódásához adja meg a {label} kulcsot:\n`/connect {id} <sajat_kulcs>`',
    localPathPrompt: 'A **{target}** kapcsolódásához adja meg a helyi könyvtár elérési útját:\n`/connect {id} /utvonal/{kind}`',
    oauthDeviceCodePrompt: '**{target}** eszköz-hitelesítésének befejezéséhez:\n1. Nyissa meg: {url}\n2. Adja meg a párosítási kódot: `{code}`',
    catalogTitle: 'Elérhető kapcsolatkatalógus',
    noActiveConnections: 'Nem található aktív kapcsolat.\n\n• Integráció csatlakoztatása: `/connect <cél>`\n• Elérhető katalógus megtekintése: `/connections catalog`',
    usageConnect: '**Connect parancs használata:**\n`/connect <cél> [hitelesites]`\n\n**Példák:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /utvonal/vault`\n\nA `/connections catalog` parancssal megtekintheti az összes elérhető célt.',
    usageDisconnect: 'Használat: `/disconnect <cél>`\nPélda: `/disconnect stripe`',
    handshakeInProgress: 'Ehhez a célhoz már folyamatban van egy kapcsolódási kézfogás.',
    pathVerificationFailed: '❌ Az útvonal ellenőrzése sikertelen itt: **{target}**: {details}',
    apiKeyVerificationFailed: '❌ A kulcs ellenőrzése sikertelen itt: **{target}**: {details}',
    oauthClickLink: '🔗 **Kapcsolódás: {target}:**\nKattintson az alábbi linkre a Zavorth hitelesítéséhez:\n[{target} hitelesítése]({url})',
    oauthEnded: '⚠️ A(z) **{target}** OAuth-hitelesítése befejeződött: {details}',
    activeConnectionsHeader: '**Aktív kapcsolatai ({count}):**',
    catalogEmpty: 'Jelenleg nincs elérhető cél a kapcsolatkatalógusban.',
    statusHeader: '**Kapcsolatok állapot-egészsége:**',
    statusEmpty: 'Nincs aktív kapcsolat az állapot megjelenítéséhez.',
    guidanceLabel: '💡 **Útmutató:**',
    reconnectHint: '• Újracsatlakozás vagy hitelesítési adatok frissítése: `/connect {target} <uj_adatok>`',
    disconnectHint: '• Kapcsolat bontása: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Helyi könyvtár ellenőrizve: `{path}`',
    credentialsVaultSuffix: 'A hitelesítési adatok titkosítva, biztonságosan a széfben tárolva.',
    secretStoreFailed: '❌ A titkosított hitelesítési adatok tárolása sikertelen: **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Kapcsolódás: {target} (Eszközkód-folyamat):**\n1. Nyissa meg a hitelesítési linket: {url}\n2. Erősítse meg a hitelesítést a böngészőjében.\n3. A Zavorth automatikusan befejezi a kézfogást.',
    missingDeviceVerificationUrl: 'Hiányzó eszköz-ellenőrzési URL',
    oauthConnectedSuccess: '✅ Sikeresen kapcsolódva a következőhöz OAuth2-n keresztül: **{target}**!',
    oauthExchangeFailed: '❌ OAuth tokencsere sikertelen itt: **{target}**: {details}',
    oauthListenerFailed: '⚠️ OAuth visszahívási figyelő indítása sikertelen: {details}',
    oauthConfigActive: 'A(z) **{target}** OAuth-konfigurációja aktív.',
    catalogConnectHint: 'Bármely cél kapcsolódásához írja be: `/connect <cél>`',
    statusLabel: 'Állapot',
    healthLabel: 'Egészség',
    authLabel: 'Hitelesítés',
    connectedAtLabel: 'Kapcsolódás ideje',
    disconnectServiceHint: '• Szolgáltatás lekapcsolása: `/disconnect <cél>`',
  },
};
