import type { LocalizationCatalog } from '../localeContracts.js';

export const hu: LocalizationCatalog = {
  common: {
    save: 'Mentés',
    saving: 'Mentés...',
    cancel: 'Mégse',
    close: 'Bezárás',
    confirm: 'Megerősítés',
    delete: 'Törlés',
    refresh: 'Frissítés',
    retry: 'Újrapróbálkozás',
    search: 'Keresés...',
    loading: 'Betöltés...',
    create: 'Létrehozás',
    creating: 'Létrehozás...',
    clear: 'Törlés',
    enabled: 'Engedélyezve',
    disabled: 'Letiltva',
    active: 'Aktív',
    inactive: 'Inaktív',
    status: 'Állapot',
    actions: 'Műveletek',
    details: 'Részletek',
    error: 'Hiba',
    success: 'Sikeres',
    none: 'Nincs',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Autonóm MI Fejlesztői Környezet',
    chat: 'Csevegés',
    files: 'Fájlok',
    approvals: 'Jóváhagyások',
    memory: 'Mnemos Memória',
    plugins: 'Bővítmények',
    channels: 'Csatornák',
    settings: 'Beállítások',
    workboard: 'Kanban Mátrix',
    automations: 'Automatizálások',
    analytics: 'Elemzések',
  },
  chat: {
    placeholder: 'Kérdezzen a Zavorth-tól vagy rendeljen hozzá fejlesztési feladatot...',
    send: 'Küldés',
    stop: 'Leállítás',
    clearHistory: 'Előzmények törlése',
    emptyState: 'Még nincsenek üzenetek. Küldjön parancsot a kezdéshez.',
    tokens: 'token',
    thinking: 'Gondolkodás...',
    errorOccurred: 'Hiba történt a válasz generálása közben.',
  },
  channels: {
    title: 'Többcsatornás Átjáró',
    description: 'Külső üzenetküldő platformok hídjainak konfigurálása és felügyelete.',
    primaryChannel: 'Elsődleges Csatorna',
    telegram: 'Telegram Átjáró',
    discord: 'Discord Átjáró',
    slack: 'Slack Átjáró',
    whatsapp: 'WhatsApp Átjáró',
    web: 'Webkonzol',
    notConfigured: 'Nincs Beállítva',
    connected: 'Csatlakozva',
    disconnected: 'Leválasztva',
  },
  providers: {
    title: 'LLM Modell Útválasztó',
    description: 'Elsődleges MI-szolgáltatók, API-kulcsok és tartalék útvonalak beállítása.',
    primaryProvider: 'Elsődleges Szolgáltató',
    primaryModel: 'Elsődleges Modell',
    fallbackModel: 'Tartalék Modell',
    apiKey: 'API Kulcs',
    saveRoute: 'Útvonal Mentése',
    savedSuccessfully: 'MI útvonal sikeresen mentve.',
    saveFailed: 'Nem sikerült menteni az MI útvonal beállításait.',
  },
  mnemos: {
    title: 'Mnemos Állandó Memória',
    description: 'Kontextus tények, szemantikus vektorkeresés és munkamenet-közi tudásmegőrzés.',
    searchFacts: 'Mentett tények keresése...',
    recall: 'Tudás Felidézése',
    forget: 'Tény Elfelejtése',
    totalFacts: 'Összes Tény',
    noFactsRecorded: 'Még nincsenek rögzített memóriatények.',
  },
  kanban: {
    title: 'Swarm Kanban Mátrix',
    description: 'Valós idejű feladat-DAG haladás, munkatárs-hozzárendelések és javítási állapot.',
    backlog: 'Hátralék',
    inProgress: 'Folyamatban',
    review: 'Felülvizsgálat',
    autoRepairLane: 'Automatikus Javítás',
    done: 'Kész',
    createTask: 'Új Feladat',
    taskTitle: 'Feladat Címe',
    priority: 'Prioritás',
  },
  autoRepair: {
    title: 'Zárt Láncú Automatikus Javítás',
    description: 'Autonóm diagnosztika, javítófolt-generálás, tesztvalidáció és visszagörgetés.',
    resolvingFailure: 'Kódhiba elhárítása folyamatban...',
    patchApplied: 'Sebészeti javítás alkalmazva.',
    testsPassing: 'Ellenőrző tesztek sikeresek.',
    rollbackRecovered: 'Biztonságos visszagörgetés helyreállítva.',
    incidentHistory: 'Eseménytörténet',
  },
  codeGraph: {
    title: 'AST Kódbázis Gráf',
    description: 'Szimbólumdefiníciók, fájlok közötti hívásfüggőségek és hatáselemzés.',
    symbolsIndexed: 'Indexelt Szimbólumok',
    callGraph: 'Hívási Gráf',
    impactAnalysis: 'Hatáselemzés',
    callerDependencies: 'Hívó Függőségei',
  },
  diffReview: {
    title: 'Spekulatív Diff Felülvizsgálat',
    description: 'Commit előtti kockázatértékelés, szerződésvédelem és biztonsági audit.',
    riskRating: 'Kockázati Besorolás',
    securityAudit: 'Biztonsági Audit',
    secretCheck: 'Titokszivárgás Ellenőrzése',
    breakingChanges: 'Publikus Szerződés Törés Ellenőrzése',
    approved: 'Jóváhagyva',
    rejected: 'Elutasítva',
  },
  approvals: {
    title: 'Végrehajtási Biztonsági Kapu',
    description: 'Érzékeny eszközhívások, fájlírások és shell parancsok áttekintése és jóváhagyása.',
    pendingApprovals: 'Függőben Lévő Jóváhagyások',
    approve: 'Jóváhagyás',
    reject: 'Elutasítás',
    riskLevel: 'Kockázati Szint',
    commandPreview: 'Parancs Előnézete',
    noPendingApprovals: 'Nincs szükség függőben lévő jóváhagyásra.',
  },
  settings: {
    title: 'Rendszerbeállítások',
    language: 'Nyelv',
    theme: 'Téma',
    logLevel: 'Naplózási Szint',
    resetDefaults: 'Alapértelmezések Visszaállítása',
  },
};
