import type { LocalizationCatalog } from '../localeContracts.js';

export const it: LocalizationCatalog = {
  common: {
    save: 'Salva',
    saving: 'Salvataggio...',
    cancel: 'Annulla',
    close: 'Chiudi',
    confirm: 'Conferma',
    delete: 'Elimina',
    refresh: 'Aggiorna',
    retry: 'Riprova',
    search: 'Cerca...',
    loading: 'Caricamento...',
    create: 'Crea',
    creating: 'Creazione...',
    clear: 'Cancella',
    enabled: 'Abilitato',
    disabled: 'Disabilitato',
    active: 'Attivo',
    inactive: 'Inattivo',
    status: 'Stato',
    actions: 'Azioni',
    details: 'Dettagli',
    error: 'Errore',
    success: 'Successo',
    none: 'Nessuno',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Suite Autonoma di Ingegneria IA',
    chat: 'Chat',
    files: 'File',
    approvals: 'Approvazioni',
    memory: 'Memoria Mnemos',
    plugins: 'Plugin',
    channels: 'Canali',
    settings: 'Impostazioni',
    workboard: 'Matrice Kanban',
    automations: 'Automazioni',
    analytics: 'Analitica',
  },
  chat: {
    placeholder: 'Chiedi a Zavorth o assegna una missione di sviluppo...',
    send: 'Invia',
    stop: 'Ferma',
    clearHistory: 'Cancella Cronologia',
    emptyState: 'Nessun messaggio ancora. Invia un comando per iniziare.',
    tokens: 'token',
    thinking: 'Elaborazione...',
    errorOccurred: 'Si è verificato un errore durante la generazione della risposta.',
  },
  channels: {
    title: 'Gateway Multicanale',
    description: 'Configura e monitora i bridge delle piattaforme di messaggistica esterne.',
    primaryChannel: 'Canale Principale',
    telegram: 'Gateway Telegram',
    discord: 'Gateway Discord',
    slack: 'Gateway Slack',
    whatsapp: 'Gateway WhatsApp',
    web: 'Console Web',
    notConfigured: 'Non Configurato',
    connected: 'Connesso',
    disconnected: 'Disconnesso',
  },
  providers: {
    title: 'Router di Modelli LLM',
    description: 'Configura provider IA principali, credenziali API e route di fallback.',
    primaryProvider: 'Provider Principale',
    primaryModel: 'Modello Principale',
    fallbackModel: 'Modello di Fallback',
    apiKey: 'Chiave API',
    saveRoute: 'Salva Route',
    savedSuccessfully: 'Route IA salvata con successo.',
    saveFailed: 'Impossibile salvare la configurazione della route IA.',
  },
  mnemos: {
    title: 'Memoria Persistente Mnemos',
    description: 'Fatti di contesto, recupero vettoriale semantico e conservazione della conoscenza.',
    searchFacts: 'Cerca fatti memorizzati...',
    recall: 'Richiama Conoscenza',
    forget: 'Dimentica Fatto',
    totalFacts: 'Totale Fatti',
    noFactsRecorded: 'Nessun fatto memorizzato al momento.',
  },
  kanban: {
    title: 'Matrice Kanban Swarm',
    description: 'Monitoraggio del DAG delle attività in tempo reale, assegnazioni e riparazioni.',
    backlog: 'Da fare',
    inProgress: 'In Corso',
    review: 'Revisione',
    autoRepairLane: 'Auto-Riparazione',
    done: 'Completato',
    createTask: 'Nuova Attività',
    taskTitle: 'Titolo dell’Attività',
    priority: 'Priorità',
  },
  autoRepair: {
    title: 'Auto-Riparazione a Ciclo Chiuso',
    description: 'Diagnosi autonoma, generazione di patch chirurgiche, convalida e ripristino.',
    resolvingFailure: 'Risoluzione dell’incidente di codice...',
    patchApplied: 'Patch chirurgica applicata.',
    testsPassing: 'Test di verifica superati.',
    rollbackRecovered: 'Rollback sicuro ripristinato.',
    incidentHistory: 'Cronologia Incidenti',
  },
  codeGraph: {
    title: 'Grafo del Codice AST',
    description: 'Definizioni dei simboli, dipendenze delle chiamate e analisi di impatto.',
    symbolsIndexed: 'Simboli Indicizzati',
    callGraph: 'Grafo delle Chiamate',
    impactAnalysis: 'Analisi di Impatto',
    callerDependencies: 'Dipendenze Chiamanti',
  },
  diffReview: {
    title: 'Revisione Speculativa del Diff',
    description: 'Valutazione del rischio pre-commit, protezione dei contratti e audit di sicurezza.',
    riskRating: 'Valutazione del Rischio',
    securityAudit: 'Audit di Sicurezza',
    secretCheck: 'Controllo Fuga di Segreti',
    breakingChanges: 'Controllo Contratti Pubblici',
    approved: 'Approvato',
    rejected: 'Rifiutato',
  },
  approvals: {
    title: 'Gate di Sicurezza dell’Esecuzione',
    description: 'Esamina e approva chiamate a strumenti sensibili, scrittura su disco e comandi shell.',
    pendingApprovals: 'Approvazioni in Sospeso',
    approve: 'Approva',
    reject: 'Rifiuta',
    riskLevel: 'Livello di Rischio',
    commandPreview: 'Anteprima Comando',
    noPendingApprovals: 'Nessuna approvazione in sospeso richiesta.',
  },
  settings: {
    title: 'Impostazioni di Sistema',
    language: 'Lingua',
    theme: 'Tema',
    logLevel: 'Livello di Log',
    resetDefaults: 'Ripristina Predefiniti',
  },
};
