import type { LocalizationCatalog } from '../localeContracts.js';

export const it: LocalizationCatalog = {
  common: {
    save: 'Salva',
    saving: 'Salvataggio...',
    cancel: 'Annulla',
    close: 'Chiudi',
    confirm: 'Conferma',
    delete: 'Elimina',
    refresh: 'Aggiorna',
    retry: 'Riprova',
    search: 'Cerca...',
    loading: 'Caricamento...',
    create: 'Crea',
    creating: 'Creazione...',
    clear: 'Cancella',
    enabled: 'Abilitato',
    disabled: 'Disabilitato',
    active: 'Attivo',
    inactive: 'Inattivo',
    status: 'Stato',
    actions: 'Azioni',
    details: 'Dettagli',
    error: 'Errore',
    success: 'Successo',
    none: 'Nessuno',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Suite Autonoma di Ingegneria IA',
    chat: 'Chat',
    files: 'File',
    approvals: 'Approvazioni',
    memory: 'Memoria Mnemos',
    plugins: 'Plugin',
    channels: 'Canali',
    settings: 'Impostazioni',
    workboard: 'Matrice Kanban',
    automations: 'Automazioni',
    analytics: 'Analitica',
  },
  chat: {
    placeholder: 'Chiedi a Zavorth o assegna una missione di sviluppo...',
    send: 'Invia',
    stop: 'Ferma',
    clearHistory: 'Cancella Cronologia',
    emptyState: 'Nessun messaggio ancora. Invia un comando per iniziare.',
    tokens: 'token',
    thinking: 'Elaborazione...',
    errorOccurred: 'Si è verificato un errore durante la generazione della risposta.',
  },
  channels: {
    title: 'Gateway Multicanale',
    description: 'Configura e monitora i bridge delle piattaforme di messaggistica esterne.',
    primaryChannel: 'Canale Principale',
    telegram: 'Gateway Telegram',
    discord: 'Gateway Discord',
    slack: 'Gateway Slack',
    whatsapp: 'Gateway WhatsApp',
    web: 'Console Web',
    notConfigured: 'Non Configurato',
    connected: 'Connesso',
    disconnected: 'Disconnesso',
  },
  providers: {
    title: 'Router di Modelli LLM',
    description: 'Configura provider IA principali, credenziali API e route di fallback.',
    primaryProvider: 'Provider Principale',
    primaryModel: 'Modello Principale',
    fallbackModel: 'Modello di Fallback',
    apiKey: 'Chiave API',
    saveRoute: 'Salva Route',
    savedSuccessfully: 'Route IA salvata con successo.',
    saveFailed: 'Impossibile salvare la configurazione della route IA.',
  },
  mnemos: {
    title: 'Memoria Persistente Mnemos',
    description: 'Fatti di contesto, recupero vettoriale semantico e conservazione della conoscenza.',
    searchFacts: 'Cerca fatti memorizzati...',
    recall: 'Richiama Conoscenza',
    forget: 'Dimentica Fatto',
    totalFacts: 'Totale Fatti',
    noFactsRecorded: 'Nessun fatto memorizzato al momento.',
  },
  kanban: {
    title: 'Matrice Kanban Swarm',
    description: 'Monitoraggio del DAG delle attività in tempo reale, assegnazioni e riparazioni.',
    backlog: 'Da fare',
    inProgress: 'In Corso',
    review: 'Revisione',
    autoRepairLane: 'Auto-Riparazione',
    done: 'Completato',
    createTask: 'Nuova Attività',
    taskTitle: 'Titolo dell’Attività',
    priority: 'Priorità',
  },
  autoRepair: {
    title: 'Auto-Riparazione a Ciclo Chiuso',
    description: 'Diagnosi autonoma, generazione di patch chirurgiche, convalida e ripristino.',
    resolvingFailure: 'Risoluzione dell’incidente di codice...',
    patchApplied: 'Patch chirurgica applicata.',
    testsPassing: 'Test di verifica superati.',
    rollbackRecovered: 'Rollback sicuro ripristinato.',
    incidentHistory: 'Cronologia Incidenti',
  },
  codeGraph: {
    title: 'Grafo del Codice AST',
    description: 'Definizioni dei simboli, dipendenze delle chiamate e analisi di impatto.',
    symbolsIndexed: 'Simboli Indicizzati',
    callGraph: 'Grafo delle Chiamate',
    impactAnalysis: 'Analisi di Impatto',
    callerDependencies: 'Dipendenze Chiamanti',
  },
  diffReview: {
    title: 'Revisione Speculativa del Diff',
    description: 'Valutazione del rischio pre-commit, protezione dei contratti e audit di sicurezza.',
    riskRating: 'Valutazione del Rischio',
    securityAudit: 'Audit di Sicurezza',
    secretCheck: 'Controllo Fuga di Segreti',
    breakingChanges: 'Controllo Contratti Pubblici',
    approved: 'Approvato',
    rejected: 'Rifiutato',
  },
  approvals: {
    title: 'Gate di Sicurezza dell’Esecuzione',
    description: 'Esamina e approva chiamate a strumenti sensibili, scrittura su disco e comandi shell.',
    pendingApprovals: 'Approvazioni in Sospeso',
    approve: 'Approva',
    reject: 'Rifiuta',
    riskLevel: 'Livello di Rischio',
    commandPreview: 'Anteprima Comando',
    noPendingApprovals: 'Nessuna approvazione in sospeso richiesta.',
  },
  settings: {
    title: 'Impostazioni di Sistema',
    language: 'Lingua',
    theme: 'Tema',
    logLevel: 'Livello di Log',
    resetDefaults: 'Ripristina Predefiniti',
  },
  connections: {
    title: 'Sottosistema di Connessione Universale',
    connectedSuccess: 'Connesso a **{target}** con successo!',
    disconnectedSuccess: 'Disconnesso da **{target}**. Credenziali locali eliminate.',
    alreadyConnected: "La destinazione **{target}** è già connessa (stato: `connected`).",
    notConnected: "Nessuna connessione attiva con '{target}'.",
    unrecognizedTarget: "La destinazione '{target}' non è riconosciuta.",
    rateLimitExceeded: 'Limite di frequenza superato: puoi eseguire al massimo 10 comandi di connessione al minuto. Attendi un momento.',
    apiKeyPrompt: 'Per connettere **{target}**, fornisci la tua {label}:\n`/connect {id} <tua_chiave>`',
    localPathPrompt: 'Per connettere **{target}**, indica il percorso della directory locale:\n`/connect {id} /percorso/del/{kind}`',
    oauthDeviceCodePrompt: 'Per completare l\'autorizzazione del dispositivo per **{target}**:\n1. Apri: {url}\n2. Inserisci il codice di abbinamento: `{code}`',
    catalogTitle: 'Catalogo delle Connessioni Disponibili',
    noActiveConnections: 'Nessuna connessione attiva trovata.\n\n• Connetti un\'integrazione: `/connect <destinazione>`\n• Vedi il catalogo disponibile: `/connections catalog`',
    usageConnect: '**Uso del Comando Connect:**\n`/connect <destinazione> [credenziali]`\n\n**Esempi:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /percorso/del/vault`\n\nUsa `/connections catalog` per vedere tutte le destinazioni disponibili.',
    usageDisconnect: 'Uso: `/disconnect <destinazione>`\nEsempio: `/disconnect stripe`',
    handshakeInProgress: 'Un tentativo di connessione è già in corso per questa destinazione.',
    pathVerificationFailed: '❌ Verifica del percorso non riuscita per **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Verifica della chiave non riuscita per **{target}**: {details}',
    oauthClickLink: '🔗 **Connetti {target}:**\nFai clic sul link qui sotto per autorizzare Zavorth:\n[Autorizza {target}]({url})',
    oauthEnded: '⚠️ Autorizzazione OAuth terminata per **{target}**: {details}',
    activeConnectionsHeader: '**Le Tue Connessioni Attive ({count}):**',
    catalogEmpty: 'Nessuna destinazione disponibile nel catalogo al momento.',
    statusHeader: '**Stato di Integrità delle Connessioni:**',
    statusEmpty: 'Nessuna connessione attiva di cui mostrare lo stato.',
    guidanceLabel: '💡 **Guida:**',
    reconnectHint: '• Riconnetti o aggiorna le credenziali: `/connect {target} <nuove_credenziali>`',
    disconnectHint: '• Disconnetti: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Directory locale verificata in: `{path}`',
    credentialsVaultSuffix: 'Credenziali crittografate e archiviate in modo sicuro nella vault.',
    secretStoreFailed: '❌ Archiviazione delle credenziali crittografate non riuscita per **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Connetti {target} (Flusso Device Code):**\n1. Apri il link di autorizzazione: {url}\n2. Conferma l\'autorizzazione nel tuo browser.\n3. Zavorth completerà l\'handshake automaticamente.',
    missingDeviceVerificationUrl: 'URL di verifica del dispositivo mancante',
    oauthConnectedSuccess: '✅ Connesso con successo a **{target}** tramite OAuth2!',
    oauthExchangeFailed: '❌ Scambio di token OAuth non riuscito per **{target}**: {details}',
    oauthListenerFailed: '⚠️ Avvio del listener di callback OAuth non riuscito: {details}',
    oauthConfigActive: 'La configurazione OAuth di **{target}** è attiva.',
    catalogConnectHint: 'Per connettere qualsiasi destinazione, digita: `/connect <destinazione>`',
    statusLabel: 'Stato',
    healthLabel: 'Integrità',
    authLabel: 'Auth',
    connectedAtLabel: 'Connesso il',
    disconnectServiceHint: '• Disconnetti un servizio: `/disconnect <destinazione>`',
  },
};
