import type { LocalizationCatalog } from '../localeContracts.js';

export const ja: LocalizationCatalog = {
  common: {
    save: '保存',
    saving: '保存中...',
    cancel: 'キャンセル',
    close: '閉じる',
    confirm: '確認',
    delete: '削除',
    refresh: '更新',
    retry: '再試行',
    search: '検索...',
    loading: '読み込み中...',
    create: '作成',
    creating: '作成中...',
    clear: 'クリア',
    enabled: '有効',
    disabled: '無効',
    active: 'アクティブ',
    inactive: '非アクティブ',
    status: 'ステータス',
    actions: '操作',
    details: '詳細',
    error: 'エラー',
    success: '成功',
    none: 'なし',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '自律型AIエンジニアリング環境',
    chat: 'チャット',
    files: 'ファイル',
    approvals: '承認',
    memory: 'Mnemos メモリ',
    plugins: 'プラグイン',
    channels: 'チャンネル',
    settings: '設定',
    workboard: 'カンバン行列',
    automations: '自動化',
    analytics: '分析',
  },
  chat: {
    placeholder: 'Zavorthに質問するか、開発タスクを割り当ててください...',
    send: '送信',
    stop: '停止',
    clearHistory: '履歴をクリア',
    emptyState: 'メッセージはまだありません。プロンプトを送信して開始してください。',
    tokens: 'トークン',
    thinking: '思考中...',
    errorOccurred: '応答の生成中にエラーが発生しました。',
  },
  channels: {
    title: 'マルチチャネルゲートウェイ',
    description: '外部メッセージングプラットフォームブリッジを設定および監視します。',
    primaryChannel: 'プライマリチャンネル',
    telegram: 'Telegram ゲートウェイ',
    discord: 'Discord ゲートウェイ',
    slack: 'Slack ゲートウェイ',
    whatsapp: 'WhatsApp ゲートウェイ',
    web: 'Web コンソール',
    notConfigured: '未設定',
    connected: '接続済み',
    disconnected: '切断済み',
  },
  providers: {
    title: 'LLMモデルルーター',
    description: '主要なAIプロバイダー、API認証情報、およびフォールバックルートを設定します。',
    primaryProvider: '主要プロバイダー',
    primaryModel: '主要モデル',
    fallbackModel: 'フォールバックモデル',
    apiKey: 'APIキー',
    saveRoute: 'ルートを保存',
    savedSuccessfully: 'AIルートが正常に保存されました。',
    saveFailed: 'AIルート設定の保存に失敗しました。',
  },
  mnemos: {
    title: 'Mnemos 永続メモリ',
    description: 'コンテキスト事実、セマンティックベクトル検索、およびセッション間の知識保持。',
    searchFacts: '記憶された事実を検索...',
    recall: '知識を呼び出す',
    forget: '事実を忘れる',
    totalFacts: '合計事実数',
    noFactsRecorded: '記憶された事実はまだありません。',
  },
  kanban: {
    title: 'Swarm カンバン行列',
    description: 'リアルタイムのタスクDAG進行、ワーカー割り当て、および修復状態。',
    backlog: 'バックログ',
    inProgress: '進行中',
    review: 'レビュー',
    autoRepairLane: '自動修復',
    done: '完了',
    createTask: '新規タスク',
    taskTitle: 'タスク名',
    priority: '優先度',
  },
  autoRepair: {
    title: '閉ループ自動修復',
    description: '自律診断、修正パッチ生成、テスト検証、およびロールバック復元。',
    resolvingFailure: '障害を修復中...',
    patchApplied: '修正パッチが適用されました。',
    testsPassing: '検証テストに合格しました。',
    rollbackRecovered: '安全なロールバックが復元されました。',
    incidentHistory: 'インシデント履歴',
  },
  codeGraph: {
    title: 'ASTコードベースグラフ',
    description: 'シンボル定義、クロスファイル呼び出し依存関係、および影響分析。',
    symbolsIndexed: 'インデックス済みシンボル',
    callGraph: 'コールグラフ',
    impactAnalysis: '影響分析',
    callerDependencies: '呼び出し元の依存関係',
  },
  diffReview: {
    title: '投機的Diffレビュー',
    description: 'コミット前リスクスコアリング、契約保護、およびセキュリティ監査。',
    riskRating: 'リスク評価',
    securityAudit: 'セキュリティ監査',
    secretCheck: 'シークレット漏洩チェック',
    breakingChanges: '公開契約の破壊チェック',
    approved: '承認済み',
    rejected: '拒否済み',
  },
  approvals: {
    title: '実行セキュリティゲート',
    description: 'センシティブなツール呼び出し、ファイル書き込み、Shell実行を確認および承認します。',
    pendingApprovals: '保留中の承認',
    approve: '承認',
    reject: '拒否',
    riskLevel: 'リスクレベル',
    commandPreview: 'コマンドプレビュー',
    noPendingApprovals: '保留中の承認はありません。',
  },
  settings: {
    title: 'システム設定',
    language: '言語',
    theme: 'テーマ',
    logLevel: 'ログレベル',
    resetDefaults: 'デフォルトに戻す',
  },
};
