import type { LocalizationCatalog } from '../localeContracts.js';

export const ja: LocalizationCatalog = {
  common: {
    save: '保存',
    saving: '保存中...',
    cancel: 'キャンセル',
    close: '閉じる',
    confirm: '確認',
    delete: '削除',
    refresh: '更新',
    retry: '再試行',
    search: '検索...',
    loading: '読み込み中...',
    create: '作成',
    creating: '作成中...',
    clear: 'クリア',
    enabled: '有効',
    disabled: '無効',
    active: 'アクティブ',
    inactive: '非アクティブ',
    status: 'ステータス',
    actions: '操作',
    details: '詳細',
    error: 'エラー',
    success: '成功',
    none: 'なし',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '自律型AIエンジニアリング環境',
    chat: 'チャット',
    files: 'ファイル',
    approvals: '承認',
    memory: 'Mnemos メモリ',
    plugins: 'プラグイン',
    channels: 'チャンネル',
    settings: '設定',
    workboard: 'カンバン行列',
    automations: '自動化',
    analytics: '分析',
  },
  chat: {
    placeholder: 'Zavorthに質問するか、開発タスクを割り当ててください...',
    send: '送信',
    stop: '停止',
    clearHistory: '履歴をクリア',
    emptyState: 'メッセージはまだありません。プロンプトを送信して開始してください。',
    tokens: 'トークン',
    thinking: '思考中...',
    errorOccurred: '応答の生成中にエラーが発生しました。',
  },
  channels: {
    title: 'マルチチャネルゲートウェイ',
    description: '外部メッセージングプラットフォームブリッジを設定および監視します。',
    primaryChannel: 'プライマリチャンネル',
    telegram: 'Telegram ゲートウェイ',
    discord: 'Discord ゲートウェイ',
    slack: 'Slack ゲートウェイ',
    whatsapp: 'WhatsApp ゲートウェイ',
    web: 'Web コンソール',
    notConfigured: '未設定',
    connected: '接続済み',
    disconnected: '切断済み',
  },
  providers: {
    title: 'LLMモデルルーター',
    description: '主要なAIプロバイダー、API認証情報、およびフォールバックルートを設定します。',
    primaryProvider: '主要プロバイダー',
    primaryModel: '主要モデル',
    fallbackModel: 'フォールバックモデル',
    apiKey: 'APIキー',
    saveRoute: 'ルートを保存',
    savedSuccessfully: 'AIルートが正常に保存されました。',
    saveFailed: 'AIルート設定の保存に失敗しました。',
  },
  mnemos: {
    title: 'Mnemos 永続メモリ',
    description: 'コンテキスト事実、セマンティックベクトル検索、およびセッション間の知識保持。',
    searchFacts: '記憶された事実を検索...',
    recall: '知識を呼び出す',
    forget: '事実を忘れる',
    totalFacts: '合計事実数',
    noFactsRecorded: '記憶された事実はまだありません。',
  },
  kanban: {
    title: 'Swarm カンバン行列',
    description: 'リアルタイムのタスクDAG進行、ワーカー割り当て、および修復状態。',
    backlog: 'バックログ',
    inProgress: '進行中',
    review: 'レビュー',
    autoRepairLane: '自動修復',
    done: '完了',
    createTask: '新規タスク',
    taskTitle: 'タスク名',
    priority: '優先度',
  },
  autoRepair: {
    title: '閉ループ自動修復',
    description: '自律診断、修正パッチ生成、テスト検証、およびロールバック復元。',
    resolvingFailure: '障害を修復中...',
    patchApplied: '修正パッチが適用されました。',
    testsPassing: '検証テストに合格しました。',
    rollbackRecovered: '安全なロールバックが復元されました。',
    incidentHistory: 'インシデント履歴',
  },
  codeGraph: {
    title: 'ASTコードベースグラフ',
    description: 'シンボル定義、クロスファイル呼び出し依存関係、および影響分析。',
    symbolsIndexed: 'インデックス済みシンボル',
    callGraph: 'コールグラフ',
    impactAnalysis: '影響分析',
    callerDependencies: '呼び出し元の依存関係',
  },
  diffReview: {
    title: '投機的Diffレビュー',
    description: 'コミット前リスクスコアリング、契約保護、およびセキュリティ監査。',
    riskRating: 'リスク評価',
    securityAudit: 'セキュリティ監査',
    secretCheck: 'シークレット漏洩チェック',
    breakingChanges: '公開契約の破壊チェック',
    approved: '承認済み',
    rejected: '拒否済み',
  },
  approvals: {
    title: '実行セキュリティゲート',
    description: 'センシティブなツール呼び出し、ファイル書き込み、Shell実行を確認および承認します。',
    pendingApprovals: '保留中の承認',
    approve: '承認',
    reject: '拒否',
    riskLevel: 'リスクレベル',
    commandPreview: 'コマンドプレビュー',
    noPendingApprovals: '保留中の承認はありません。',
  },
  settings: {
    title: 'システム設定',
    language: '言語',
    theme: 'テーマ',
    logLevel: 'ログレベル',
    resetDefaults: 'デフォルトに戻す',
  },
  connections: {
    title: 'ユニバーサル接続サブシステム',
    connectedSuccess: '**{target}** に正常に接続しました！',
    disconnectedSuccess: '**{target}** から切断しました。ローカルの認証情報を削除しました。',
    alreadyConnected: 'ターゲット **{target}** はすでに接続されています（状態： `connected`）。',
    notConnected: "'{target}' には接続していません。",
    unrecognizedTarget: "ターゲット '{target}' を認識できません。",
    rateLimitExceeded: 'レート制限を超えました。接続コマンドは1分あたり最大10回までです。しばらくお待ちください。',
    apiKeyPrompt: '**{target}** に接続するには、{label} を入力してください：\n`/connect {id} <あなたのキー>`',
    localPathPrompt: '**{target}** に接続するには、ローカルディレクトリのパスを指定してください：\n`/connect {id} /path/to/{kind}`',
    oauthDeviceCodePrompt: '**{target}** のデバイス認証を完了するには：\n1. 開く： {url}\n2. ペアリングコードを入力： `{code}`',
    catalogTitle: '利用可能な接続カタログ',
    noActiveConnections: 'アクティブな接続は見つかりませんでした。\n\n• 統合を接続： `/connect <ターゲット>`\n• 利用可能なカタログを表示： `/connections catalog`',
    usageConnect: '**Connect コマンドの使用法：**\n`/connect <ターゲット> [認証情報]`\n\n**例：**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /path/to/vault`\n\n`/connections catalog` ですべての利用可能なターゲットを表示できます。',
    usageDisconnect: '使用法： `/disconnect <ターゲット>`\n例： `/disconnect stripe`',
    handshakeInProgress: 'このターゲットの接続ハンドシェイクはすでに進行中です。',
    pathVerificationFailed: '❌ **{target}** のパス検証に失敗しました： {details}',
    apiKeyVerificationFailed: '❌ **{target}** のキー検証に失敗しました： {details}',
    oauthClickLink: '🔗 **{target} を接続：**\n下のリンクをクリックして Zavorth を認証してください：\n[{target} を認証]({url})',
    oauthEnded: '⚠️ **{target}** の OAuth 認証が終了しました： {details}',
    activeConnectionsHeader: '**アクティブな接続（{count}）：**',
    catalogEmpty: '現在、接続カタログに利用可能なターゲットはありません。',
    statusHeader: '**接続の整合性ステータス：**',
    statusEmpty: 'ステータスを表示するアクティブな接続はありません。',
    guidanceLabel: '💡 **ガイダンス：**',
    reconnectHint: '• 再接続または認証情報の更新： `/connect {target} <新しい認証情報>`',
    disconnectHint: '• 切断： `/disconnect {target}`',
    localPathVerifiedSuffix: 'ローカルディレクトリを検証済み： `{path}`',
    credentialsVaultSuffix: '認証情報を暗号化してボールトに安全に保存しました。',
    secretStoreFailed: '❌ **{target}** の暗号化された認証情報の保存に失敗しました： {details}',
    deviceCodeFlowInstructions: '🔑 **{target} を接続（デバイスコードフロー）：**\n1. 認証リンクを開く： {url}\n2. ブラウザで認証を確認します。\n3. Zavorth がハンドシェイクを自動的に完了します。',
    missingDeviceVerificationUrl: 'デバイス検証URLが見つかりません',
    oauthConnectedSuccess: '✅ OAuth2 で **{target}** に正常に接続しました！',
    oauthExchangeFailed: '❌ **{target}** の OAuth トークン交換に失敗しました： {details}',
    oauthListenerFailed: '⚠️ OAuth コールバックリスナーの起動に失敗しました： {details}',
    oauthConfigActive: '**{target}** の OAuth 設定はアクティブです。',
    catalogConnectHint: '任意のターゲットに接続するには、次を入力してください： `/connect <ターゲット>`',
    statusLabel: '状態',
    healthLabel: '整合性',
    authLabel: '認証',
    connectedAtLabel: '接続日時',
    disconnectServiceHint: '• サービスを切断： `/disconnect <ターゲット>`',
  },
};
