import type { LocalizationCatalog } from '../localeContracts.js';

export const ko: LocalizationCatalog = {
  common: {
    save: '저장',
    saving: '저장 중...',
    cancel: '취소',
    close: '닫기',
    confirm: '확인',
    delete: '삭제',
    refresh: '새로고침',
    retry: '다시 시도',
    search: '검색...',
    loading: '로딩 중...',
    create: '생성',
    creating: '생성 중...',
    clear: '지우기',
    enabled: '활성화됨',
    disabled: '비활성화됨',
    active: '활성',
    inactive: '비활성',
    status: '상태',
    actions: '작업',
    details: '세부정보',
    error: '오류',
    success: '성공',
    none: '없음',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '자율 AI 엔지니어링 스위트',
    chat: '대화',
    files: '파일',
    approvals: '승인',
    memory: 'Mnemos 메모리',
    plugins: '플러그인',
    channels: '채널',
    settings: '설정',
    workboard: '칸반 매트릭스',
    automations: '자동화',
    analytics: '통계',
  },
  chat: {
    placeholder: 'Zavorth에게 질문하거나 개발 작업을 할당하세요...',
    send: '전송',
    stop: '중지',
    clearHistory: '기록 지우기',
    emptyState: '아직 메시지가 없습니다. 명령을 보내 시작하세요.',
    tokens: '토큰',
    thinking: '생각 중...',
    errorOccurred: '응답 생성 중 오류가 발생했습니다.',
  },
  channels: {
    title: '멀티 채널 게이트웨이',
    description: '외부 메시징 플랫폼 브리지를 구성하고 모니터링합니다.',
    primaryChannel: '기본 채널',
    telegram: 'Telegram 게이트웨이',
    discord: 'Discord 게이트웨이',
    slack: 'Slack 게이트웨이',
    whatsapp: 'WhatsApp 게이트웨이',
    web: '웹 콘솔',
    notConfigured: '구성되지 않음',
    connected: '연결됨',
    disconnected: '연결 끊김',
  },
  providers: {
    title: 'LLM 모델 라우터',
    description: '기본 AI 제공자, API 자격 증명 및 대체 라우팅을 구성합니다.',
    primaryProvider: '기본 제공자',
    primaryModel: '기본 모델',
    fallbackModel: '대체 모델',
    apiKey: 'API 키',
    saveRoute: '경로 저장',
    savedSuccessfully: 'AI 경로가 성공적으로 저장되었습니다.',
    saveFailed: 'AI 경로 구성을 저장하지 못했습니다.',
  },
  mnemos: {
    title: 'Mnemos 영구 메모리',
    description: '컨텍스트 사실, 의미론적 벡터 검색 및 세션 간 지식 저장.',
    searchFacts: '기억된 사실 검색...',
    recall: '지식 회상',
    forget: '사실 잊기',
    totalFacts: '총 사실 수',
    noFactsRecorded: '기록된 메모리 사실이 아직 없습니다.',
  },
  kanban: {
    title: 'Swarm 칸반 매트릭스',
    description: '실시간 작업 DAG 진행 상황, 작업자 할당 및 복구 상태.',
    backlog: '대기열',
    inProgress: '진행 중',
    review: '검토',
    autoRepairLane: '자동 복구',
    done: '완료',
    createTask: '새 작업',
    taskTitle: '작업 제목',
    priority: '우선순위',
  },
  autoRepair: {
    title: '폐쇄 루프 자동 복구',
    description: '자율 진단, 코드 패치 생성, 테스트 검증 및 롤백 복구.',
    resolvingFailure: '코드 장애 해결 중...',
    patchApplied: '정밀 패치가 적용되었습니다.',
    testsPassing: '검증 테스트를 통과했습니다.',
    rollbackRecovered: '안전한 롤백이 복원되었습니다.',
    incidentHistory: '장애 이력',
  },
  codeGraph: {
    title: 'AST 코드베이스 그래프',
    description: '심볼 정의, 파일 간 호출 종속성 및 영향 분석.',
    symbolsIndexed: '인덱싱된 심볼',
    callGraph: '호출 그래프',
    impactAnalysis: '영향 분석',
    callerDependencies: '호출자 종속성',
  },
  diffReview: {
    title: '추측적 Diff 검토',
    description: '커밋 전 위험 평가, 계약 보호 및 보안 감사.',
    riskRating: '위험 등급',
    securityAudit: '보안 감사',
    secretCheck: '비밀 유출 검사',
    breakingChanges: '공개 계약 위반 검사',
    approved: '승인됨',
    rejected: '거부됨',
  },
  approvals: {
    title: '실행 보안 게이트',
    description: '민감한 도구 호출, 파일 쓰기 및 셸 실행을 검토하고 승인합니다.',
    pendingApprovals: '대기 중인 승인',
    approve: '승인',
    reject: '거부',
    riskLevel: '위험 수준',
    commandPreview: '명령 미리보기',
    noPendingApprovals: '대기 중인 승인이 필요하지 않습니다.',
  },
  settings: {
    title: '시스템 설정',
    language: '언어',
    theme: '테마',
    logLevel: '로그 레벨',
    resetDefaults: '기본값으로 재설정',
  },
};
