import type { LocalizationCatalog } from '../localeContracts.js';

export const pt: LocalizationCatalog = {
  common: {
    save: 'Salvar',
    saving: 'Salvando...',
    cancel: 'Cancelar',
    close: 'Fechar',
    confirm: 'Confirmar',
    delete: 'Excluir',
    refresh: 'Atualizar',
    retry: 'Tentar novamente',
    search: 'Buscar...',
    loading: 'Carregando...',
    create: 'Criar',
    creating: 'Criando...',
    clear: 'Limpar',
    enabled: 'Ativado',
    disabled: 'Desativado',
    active: 'Ativo',
    inactive: 'Inativo',
    status: 'Status',
    actions: 'Ações',
    details: 'Detalhes',
    error: 'Erro',
    success: 'Sucesso',
    none: 'Nenhum',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Ambiente Autônomo de Engenharia de IA',
    chat: 'Conversa',
    files: 'Arquivos',
    approvals: 'Aprovações',
    memory: 'Memória Mnemos',
    plugins: 'Plugins',
    channels: 'Canais',
    settings: 'Configurações',
    workboard: 'Matriz Kanban',
    automations: 'Automações',
    analytics: 'Métricas',
  },
  chat: {
    placeholder: 'Pergunte ao Zavorth ou atribua uma missão de desenvolvimento...',
    send: 'Enviar',
    stop: 'Parar',
    clearHistory: 'Limpar Histórico',
    emptyState: 'Nenhuma mensagem ainda. Envie um comando para iniciar.',
    tokens: 'tokens',
    thinking: 'Pensando...',
    errorOccurred: 'Ocorreu um erro ao gerar a resposta.',
  },
  channels: {
    title: 'Gateway Multicanal',
    description: 'Configure e monitore conexões com plataformas de mensagens externas.',
    primaryChannel: 'Canal Principal',
    telegram: 'Gateway Telegram',
    discord: 'Gateway Discord',
    slack: 'Gateway Slack',
    whatsapp: 'Gateway WhatsApp',
    web: 'Console Web',
    notConfigured: 'Não Configurado',
    connected: 'Conectado',
    disconnected: 'Desconectado',
  },
  providers: {
    title: 'Roteador de Modelos LLM',
    description: 'Configure provedores de IA primários, credenciais de API e rotas de contingência.',
    primaryProvider: 'Provedor Principal',
    primaryModel: 'Modelo Principal',
    fallbackModel: 'Modelo de Contingência',
    apiKey: 'Chave de API',
    saveRoute: 'Salvar Rota',
    savedSuccessfully: 'Rota de IA salva com sucesso.',
    saveFailed: 'Falha ao salvar configuração da rota de IA.',
  },
  mnemos: {
    title: 'Memória Persistente Mnemos',
    description: 'Fatos de contexto, busca semântica vetorial e retenção de conhecimento.',
    searchFacts: 'Buscar fatos memorizados...',
    recall: 'Relembrar Conhecimento',
    forget: 'Esquecer Fato',
    totalFacts: 'Total de Fatos',
    noFactsRecorded: 'Nenhum fato memorizado ainda.',
  },
  kanban: {
    title: 'Matriz Kanban Swarm',
    description: 'Acompanhamento do DAG de tarefas em tempo real, atribuições e auto-reparo.',
    backlog: 'Pendente',
    inProgress: 'Em Progresso',
    review: 'Revisão',
    autoRepairLane: 'Auto-Reparo',
    done: 'Concluído',
    createTask: 'Nova Tarefa',
    taskTitle: 'Título da Tarefa',
    priority: 'Prioridade',
  },
  autoRepair: {
    title: 'Auto-Reparo em Loop Fechado',
    description: 'Diagnóstico autônomo, geração de patches cirúrgicos, validação e rollback.',
    resolvingFailure: 'Resolvendo incidente e falha de código...',
    patchApplied: 'Patch cirúrgico aplicado.',
    testsPassing: 'Testes de verificação aprovados.',
    rollbackRecovered: 'Rollback cirúrgico restaurado com segurança.',
    incidentHistory: 'Histórico de Incidentes',
  },
  codeGraph: {
    title: 'Grafo de Código AST',
    description: 'Definição de símbolos, dependências de chamadas e análise de impacto.',
    symbolsIndexed: 'Símbolos Indexados',
    callGraph: 'Grafo de Chamadas',
    impactAnalysis: 'Análise de Impacto',
    callerDependencies: 'Dependências de Consumidores',
  },
  diffReview: {
    title: 'Revisão Especulativa de Diff',
    description: 'Avaliação de risco pré-commit, proteção de contratos e auditoria de segurança.',
    riskRating: 'Classificação de Risco',
    securityAudit: 'Auditoria de Segurança',
    secretCheck: 'Verificação de Segredos',
    breakingChanges: 'Verificação de Contratos Públicos',
    approved: 'Aprovado',
    rejected: 'Rejeitado',
  },
  approvals: {
    title: 'Barreira de Segurança de Execução',
    description: 'Revise e aprove chamadas sensíveis de ferramentas, escrita em disco e shell.',
    pendingApprovals: 'Aprovações Pendentes',
    approve: 'Aprovar',
    reject: 'Rejeitar',
    riskLevel: 'Nível de Risco',
    commandPreview: 'Pré-visualização do Comando',
    noPendingApprovals: 'Nenhuma aprovação pendente necessária.',
  },
  settings: {
    title: 'Configurações do Sistema',
    language: 'Idioma',
    theme: 'Tema',
    logLevel: 'Nível de Log',
    resetDefaults: 'Restaurar Padrões',
  },
  approval: {
    prompt: {
      entry: '{ordinal}[{risk}] {label} — ref {ref}',
      hint:
        'Responda 1 (ou a referência) para permitir uma vez; use /approve <referência> com once/session/always, /reject <referência> (ou /deny) para negar, ou responda other para digitar sua resposta.',
    },
    receipt: {
      approved: 'Aprovado {ref} ({choice}).',
      denied: 'Aprovação {ref} negada.',
      notFound: 'Nenhuma aprovação pendente encontrada para {ref}.',
      resolvedApprovedElsewhere:
        'Resolvida em outra superfície: a aprovação {ref} foi aprovada em outra superfície. Nenhuma ação é necessária aqui.',
      resolvedDeniedElsewhere:
        'Resolvida em outra superfície: a aprovação {ref} foi negada em outra superfície. Nenhuma ação é necessária aqui.',
    },
    bulk: {
      approvedAll: 'Todas as {count} aprovações foram aprovadas ({choice}).',
      deniedAll: '{count} aprovações foram negadas.',
      approvedPartial: '{resolved} de {total} aprovações aprovadas ({choice}).',
      deniedPartial: '{resolved} de {total} aprovações negadas.',
      notFound: 'Nenhuma aprovação pendente encontrada para all.',
    },
    other: {
      armed:
        'Descreva sua resposta para {count} aprovação(ões) pendente(s); sua próxima mensagem será capturada como o contexto da decisão.',
      deniedWithReason: '{count} aprovações negadas. Sua resposta foi repassada ao agente.',
      referencedNotFound: 'Nenhuma aprovação pendente encontrada para as referências informadas.',
    },
  },
  connections: {
    title: 'Subsistema de Conexão Universal',
    connectedSuccess: 'Conectado a **{target}** com sucesso!',
    disconnectedSuccess: 'Desconectado de **{target}**. Credenciais locais expurgadas.',
    alreadyConnected: 'O alvo **{target}** já está conectado (status: `connected`).',
    notConnected: "Não conectado a '{target}'.",
    unrecognizedTarget: "O alvo '{target}' não foi reconhecido.",
    rateLimitExceeded: 'Limite de taxa excedido: Você pode executar no máximo 10 comandos de conexão por minuto. Por favor, aguarde.',
    apiKeyPrompt: 'Para conectar o **{target}**, forneça sua {label}:\n`/connect {id} <sua_chave>`',
    localPathPrompt: 'Para conectar o **{target}**, informe o caminho do diretório local:\n`/connect {id} /caminho/do/{kind}`',
    oauthDeviceCodePrompt: 'Para concluir a autorização do dispositivo para **{target}**:\n1. Acesse: {url}\n2. Digite o código de emparelhamento: `{code}`',
    catalogTitle: 'Catálogo de Conexões Disponíveis',
    noActiveConnections: 'Nenhuma conexão ativa encontrada.\n\n• Conectar uma integração: `/connect <alvo>`\n• Ver catálogo disponível: `/connections catalog`',
    usageConnect: '**Uso do Comando Connect:**\n`/connect <alvo> [credencial]`\n\n**Exemplos:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /caminho/do/vault`\n\nUse `/connections catalog` para ver todos os alvos disponíveis.',
    usageDisconnect: 'Uso: `/disconnect <alvo>`\nExemplo: `/disconnect stripe`',
    handshakeInProgress: 'Já existe uma tentativa de conexão em andamento para este alvo.',
    pathVerificationFailed: '❌ Falha ao verificar o caminho para **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Falha na verificação da chave para **{target}**: {details}',
    oauthClickLink: '🔗 **Conectar {target}:**\nClique no link abaixo para autorizar o Zavorth:\n[Autorizar {target}]({url})',
    oauthEnded: '⚠️ Autorização OAuth encerrada para **{target}**: {details}',
    activeConnectionsHeader: '**Suas Conexões Ativas ({count}):**',
    catalogEmpty: 'Nenhum alvo disponível no catálogo no momento.',
    statusHeader: '**Status de Integridade das Conexões:**',
    statusEmpty: 'Nenhuma conexão ativa para exibir status.',
  },
};
