import type { LocalizationCatalog } from '../localeContracts.js';

export const ru: LocalizationCatalog = {
  common: {
    save: 'Сохранить',
    saving: 'Сохранение...',
    cancel: 'Отмена',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    delete: 'Удалить',
    refresh: 'Обновить',
    retry: 'Повторить',
    search: 'Поиск...',
    loading: 'Загрузка...',
    create: 'Создать',
    creating: 'Создание...',
    clear: 'Очистить',
    enabled: 'Включено',
    disabled: 'Отключено',
    active: 'Активно',
    inactive: 'Неактивно',
    status: 'Статус',
    actions: 'Действия',
    details: 'Детали',
    error: 'Ошибка',
    success: 'Успешно',
    none: 'Нет',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Автономная среда разработки ИИ',
    chat: 'Чат',
    files: 'Файлы',
    approvals: 'Одобрения',
    memory: 'Память Mnemos',
    plugins: 'Плагины',
    channels: 'Каналы',
    settings: 'Настройки',
    workboard: 'Матрица Канбан',
    automations: 'Автоматизация',
    analytics: 'Аналитика',
  },
  chat: {
    placeholder: 'Задайте вопрос Zavorth или назначьте задачу разработки...',
    send: 'Отправить',
    stop: 'Остановить',
    clearHistory: 'Очистить историю',
    emptyState: 'Сообщений пока нет. Отправьте запрос для начала.',
    tokens: 'токенов',
    thinking: 'Размышление...',
    errorOccurred: 'Произошла ошибка при генерации ответа.',
  },
  channels: {
    title: 'Многоканальный шлюз',
    description: 'Настройка и мониторинг мостов внешних платформ обмена сообщениями.',
    primaryChannel: 'Основной канал',
    telegram: 'Шлюз Telegram',
    discord: 'Шлюз Discord',
    slack: 'Шлюз Slack',
    whatsapp: 'Шлюз WhatsApp',
    web: 'Веб-консоль',
    notConfigured: 'Не настроено',
    connected: 'Подключено',
    disconnected: 'Отключено',
  },
  providers: {
    title: 'Маршрутизатор моделей LLM',
    description: 'Настройка основных провайдеров ИИ, ключей API и резервных маршрутов.',
    primaryProvider: 'Основной провайдер',
    primaryModel: 'Основная модель',
    fallbackModel: 'Резервная модель',
    apiKey: 'Ключ API',
    saveRoute: 'Сохранить маршрут',
    savedSuccessfully: 'Маршрут ИИ успешно сохранен.',
    saveFailed: 'Не удалось сохранить настройки маршрута ИИ.',
  },
  mnemos: {
    title: 'Постоянная память Mnemos',
    description: 'Контекстные факты, семантический векторный поиск и сохранение знаний.',
    searchFacts: 'Поиск сохраненных фактов...',
    recall: 'Вспомнить знания',
    forget: 'Забыть факт',
    totalFacts: 'Всего фактов',
    noFactsRecorded: 'Факты памяти пока не записаны.',
  },
  kanban: {
    title: 'Матрица Канбан Swarm',
    description: 'Отслеживание DAG задач в реальном времени, назначение исполнителей и статус восстановления.',
    backlog: 'Бэклог',
    inProgress: 'В работе',
    review: 'Проверка',
    autoRepairLane: 'Авто-восстановление',
    done: 'Готово',
    createTask: 'Новая задача',
    taskTitle: 'Название задачи',
    priority: 'Приоритет',
  },
  autoRepair: {
    title: 'Авто-восстановление в замкнутом цикле',
    description: 'Автономная диагностика, генерация патчей, проверка тестов и откат изменений.',
    resolvingFailure: 'Устранение инцидента с кодом...',
    patchApplied: 'Точечный патч применен.',
    testsPassing: 'Проверочные тесты пройдены.',
    rollbackRecovered: 'Безопасный откат успешно восстановлен.',
    incidentHistory: 'История инцидентов',
  },
  codeGraph: {
    title: 'AST Граф кодовой базы',
    description: 'Определения символов, зависимости вызовов и анализ влияния изменений.',
    symbolsIndexed: 'Проиндексировано символов',
    callGraph: 'Граф вызовов',
    impactAnalysis: 'Анализ влияния',
    callerDependencies: 'Зависимости вызывающих объектов',
  },
  diffReview: {
    title: 'Спекулятивный обзор Diff',
    description: 'Оценка рисков до коммита, защита контрактов и аудит безопасности.',
    riskRating: 'Оценка риска',
    securityAudit: 'Аудит безопасности',
    secretCheck: 'Проверка утечки секретов',
    breakingChanges: 'Проверка нарушения контрактов',
    approved: 'Одобрено',
    rejected: 'Отклонено',
  },
  approvals: {
    title: 'Шлюз безопасности выполнения',
    description: 'Проверка и подтверждение вызовов инструментов, записи на диск и команд shell.',
    pendingApprovals: 'Ожидающие одобрения',
    approve: 'Одобрить',
    reject: 'Отклонить',
    riskLevel: 'Уровень риска',
    commandPreview: 'Предпросмотр команды',
    noPendingApprovals: 'Нет ожидающих одобрений.',
  },
  settings: {
    title: 'Настройки системы',
    language: 'Язык',
    theme: 'Тема',
    logLevel: 'Уровень логирования',
    resetDefaults: 'Сбросить по умолчанию',
  },
};
