import type { LocalizationCatalog } from '../localeContracts.js';

export const ru: LocalizationCatalog = {
  common: {
    save: 'Сохранить',
    saving: 'Сохранение...',
    cancel: 'Отмена',
    close: 'Закрыть',
    confirm: 'Подтвердить',
    delete: 'Удалить',
    refresh: 'Обновить',
    retry: 'Повторить',
    search: 'Поиск...',
    loading: 'Загрузка...',
    create: 'Создать',
    creating: 'Создание...',
    clear: 'Очистить',
    enabled: 'Включено',
    disabled: 'Отключено',
    active: 'Активно',
    inactive: 'Неактивно',
    status: 'Статус',
    actions: 'Действия',
    details: 'Детали',
    error: 'Ошибка',
    success: 'Успешно',
    none: 'Нет',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Автономная среда разработки ИИ',
    chat: 'Чат',
    files: 'Файлы',
    approvals: 'Одобрения',
    memory: 'Память Mnemos',
    plugins: 'Плагины',
    channels: 'Каналы',
    settings: 'Настройки',
    workboard: 'Матрица Канбан',
    automations: 'Автоматизация',
    analytics: 'Аналитика',
  },
  chat: {
    placeholder: 'Задайте вопрос Zavorth или назначьте задачу разработки...',
    send: 'Отправить',
    stop: 'Остановить',
    clearHistory: 'Очистить историю',
    emptyState: 'Сообщений пока нет. Отправьте запрос для начала.',
    tokens: 'токенов',
    thinking: 'Размышление...',
    errorOccurred: 'Произошла ошибка при генерации ответа.',
  },
  channels: {
    title: 'Многоканальный шлюз',
    description: 'Настройка и мониторинг мостов внешних платформ обмена сообщениями.',
    primaryChannel: 'Основной канал',
    telegram: 'Шлюз Telegram',
    discord: 'Шлюз Discord',
    slack: 'Шлюз Slack',
    whatsapp: 'Шлюз WhatsApp',
    web: 'Веб-консоль',
    notConfigured: 'Не настроено',
    connected: 'Подключено',
    disconnected: 'Отключено',
  },
  providers: {
    title: 'Маршрутизатор моделей LLM',
    description: 'Настройка основных провайдеров ИИ, ключей API и резервных маршрутов.',
    primaryProvider: 'Основной провайдер',
    primaryModel: 'Основная модель',
    fallbackModel: 'Резервная модель',
    apiKey: 'Ключ API',
    saveRoute: 'Сохранить маршрут',
    savedSuccessfully: 'Маршрут ИИ успешно сохранен.',
    saveFailed: 'Не удалось сохранить настройки маршрута ИИ.',
  },
  mnemos: {
    title: 'Постоянная память Mnemos',
    description: 'Контекстные факты, семантический векторный поиск и сохранение знаний.',
    searchFacts: 'Поиск сохраненных фактов...',
    recall: 'Вспомнить знания',
    forget: 'Забыть факт',
    totalFacts: 'Всего фактов',
    noFactsRecorded: 'Факты памяти пока не записаны.',
  },
  kanban: {
    title: 'Матрица Канбан Swarm',
    description: 'Отслеживание DAG задач в реальном времени, назначение исполнителей и статус восстановления.',
    backlog: 'Бэклог',
    inProgress: 'В работе',
    review: 'Проверка',
    autoRepairLane: 'Авто-восстановление',
    done: 'Готово',
    createTask: 'Новая задача',
    taskTitle: 'Название задачи',
    priority: 'Приоритет',
  },
  autoRepair: {
    title: 'Авто-восстановление в замкнутом цикле',
    description: 'Автономная диагностика, генерация патчей, проверка тестов и откат изменений.',
    resolvingFailure: 'Устранение инцидента с кодом...',
    patchApplied: 'Точечный патч применен.',
    testsPassing: 'Проверочные тесты пройдены.',
    rollbackRecovered: 'Безопасный откат успешно восстановлен.',
    incidentHistory: 'История инцидентов',
  },
  codeGraph: {
    title: 'AST Граф кодовой базы',
    description: 'Определения символов, зависимости вызовов и анализ влияния изменений.',
    symbolsIndexed: 'Проиндексировано символов',
    callGraph: 'Граф вызовов',
    impactAnalysis: 'Анализ влияния',
    callerDependencies: 'Зависимости вызывающих объектов',
  },
  diffReview: {
    title: 'Спекулятивный обзор Diff',
    description: 'Оценка рисков до коммита, защита контрактов и аудит безопасности.',
    riskRating: 'Оценка риска',
    securityAudit: 'Аудит безопасности',
    secretCheck: 'Проверка утечки секретов',
    breakingChanges: 'Проверка нарушения контрактов',
    approved: 'Одобрено',
    rejected: 'Отклонено',
  },
  approvals: {
    title: 'Шлюз безопасности выполнения',
    description: 'Проверка и подтверждение вызовов инструментов, записи на диск и команд shell.',
    pendingApprovals: 'Ожидающие одобрения',
    approve: 'Одобрить',
    reject: 'Отклонить',
    riskLevel: 'Уровень риска',
    commandPreview: 'Предпросмотр команды',
    noPendingApprovals: 'Нет ожидающих одобрений.',
  },
  settings: {
    title: 'Настройки системы',
    language: 'Язык',
    theme: 'Тема',
    logLevel: 'Уровень логирования',
    resetDefaults: 'Сбросить по умолчанию',
  },
  connections: {
    title: 'Универсальная подсистема подключений',
    connectedSuccess: 'Успешно подключено к **{target}**!',
    disconnectedSuccess: 'Отключено от **{target}**. Локальные учётные данные удалены.',
    alreadyConnected: 'Цель **{target}** уже подключена (статус: `connected`).',
    notConnected: "Нет активного подключения к '{target}'.",
    unrecognizedTarget: "Цель '{target}' не распознана.",
    rateLimitExceeded: 'Превышен лимит частоты: можно выполнять не более 10 команд подключения в минуту. Пожалуйста, подождите.',
    apiKeyPrompt: 'Чтобы подключить **{target}**, укажите ваш {label}:\n`/connect {id} <ваш_ключ>`',
    localPathPrompt: 'Чтобы подключить **{target}**, укажите путь к локальному каталогу:\n`/connect {id} /путь/к/{kind}`',
    oauthDeviceCodePrompt: 'Чтобы завершить авторизацию устройства для **{target}**:\n1. Откройте: {url}\n2. Введите код сопряжения: `{code}`',
    catalogTitle: 'Каталог доступных подключений',
    noActiveConnections: 'Активные подключения не найдены.\n\n• Подключить интеграцию: `/connect <цель>`\n• Просмотреть каталог: `/connections catalog`',
    usageConnect: '**Использование команды Connect:**\n`/connect <цель> [учётные_данные]`\n\n**Примеры:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /путь/к/vault`\n\nИспользуйте `/connections catalog`, чтобы увидеть все доступные цели.',
    usageDisconnect: 'Использование: `/disconnect <цель>`\nПример: `/disconnect stripe`',
    handshakeInProgress: 'Для этой цели уже выполняется попытка подключения.',
    pathVerificationFailed: '❌ Не удалось проверить путь для **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Не удалось проверить ключ для **{target}**: {details}',
    oauthClickLink: '🔗 **Подключить {target}:**\nНажмите на ссылку ниже, чтобы авторизовать Zavorth:\n[Авторизовать {target}]({url})',
    oauthEnded: '⚠️ OAuth-авторизация для **{target}** завершена: {details}',
    activeConnectionsHeader: '**Ваши активные подключения ({count}):**',
    catalogEmpty: 'В каталоге подключений сейчас нет доступных целей.',
    statusHeader: '**Состояние работоспособности подключений:**',
    statusEmpty: 'Нет активных подключений для отображения состояния.',
    guidanceLabel: '💡 **Рекомендация:**',
    reconnectHint: '• Переподключить или обновить учётные данные: `/connect {target} <новые_данные>`',
    disconnectHint: '• Отключить: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Локальный каталог проверен: `{path}`',
    credentialsVaultSuffix: 'Учётные данные зашифрованы и безопасно сохранены в хранилище.',
    secretStoreFailed: '❌ Не удалось сохранить зашифрованные учётные данные для **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Подключить {target} (Device Code Flow):**\n1. Откройте ссылку авторизации: {url}\n2. Подтвердите авторизацию в браузере.\n3. Zavorth автоматически завершит handshake.',
    missingDeviceVerificationUrl: 'Отсутствует URL проверки устройства',
    oauthConnectedSuccess: '✅ Успешно подключено к **{target}** через OAuth2!',
    oauthExchangeFailed: '❌ Ошибка обмена токенами OAuth для **{target}**: {details}',
    oauthListenerFailed: '⚠️ Не удалось запустить слушатель OAuth-колбэков: {details}',
    oauthConfigActive: 'Конфигурация OAuth для **{target}** активна.',
    catalogConnectHint: 'Чтобы подключить любую цель, введите: `/connect <цель>`',
    statusLabel: 'Статус',
    healthLabel: 'Работоспособность',
    authLabel: 'Аутентификация',
    connectedAtLabel: 'Подключено',
    disconnectServiceHint: '• Отключить сервис: `/disconnect <цель>`',
  },
};
