import type { LocalizationCatalog } from '../localeContracts.js';

export const tr: LocalizationCatalog = {
  common: {
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    cancel: 'İptal',
    close: 'Kapat',
    confirm: 'Onayla',
    delete: 'Sil',
    refresh: 'Yenile',
    retry: 'Tekrar Dene',
    search: 'Ara...',
    loading: 'Yükleniyor...',
    create: 'Oluştur',
    creating: 'Oluşturuluyor...',
    clear: 'Temizle',
    enabled: 'Etkin',
    disabled: 'Devre Dışı',
    active: 'Aktif',
    inactive: 'Pasif',
    status: 'Durum',
    actions: 'Eylemler',
    details: 'Ayrıntılar',
    error: 'Hata',
    success: 'Başarılı',
    none: 'Yok',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Otonom Yapay Zeka Geliştirme Ortamı',
    chat: 'Sohbet',
    files: 'Dosyalar',
    approvals: 'Onaylar',
    memory: 'Mnemos Belleği',
    plugins: 'Eklentiler',
    channels: 'Kanallar',
    settings: 'Ayarlar',
    workboard: 'Kanban Matrisi',
    automations: 'Otomasyonlar',
    analytics: 'Analitik',
  },
  chat: {
    placeholder: 'Zavorth’a bir soru sorun veya bir geliştirme görevi atayın...',
    send: 'Gönder',
    stop: 'Durdur',
    clearHistory: 'Geçmişi Temizle',
    emptyState: 'Henüz mesaj yok. Başlamak için bir komut gönderin.',
    tokens: 'jeton',
    thinking: 'Düşünüyor...',
    errorOccurred: 'Yanıt oluşturulurken bir hata oluştu.',
  },
  channels: {
    title: 'Çok Kanallı Ağ Geçidi',
    description: 'Harici mesajlaşma platformu köprülerini yapılandırın ve izleyin.',
    primaryChannel: 'Birincil Kanal',
    telegram: 'Telegram Ağ Geçidi',
    discord: 'Discord Ağ Geçidi',
    slack: 'Slack Ağ Geçidi',
    whatsapp: 'WhatsApp Ağ Geçidi',
    web: 'Web Konsolu',
    notConfigured: 'Yapılandırılmadı',
    connected: 'Bağlandı',
    disconnected: 'Bağlantı Kesildi',
  },
  providers: {
    title: 'LLM Model Yönlendiricisi',
    description: 'Birincil yapay zeka sağlayıcılarını, API anahtarlarını ve yedek rotaları yapılandırın.',
    primaryProvider: 'Birincil Sağlayıcı',
    primaryModel: 'Birincil Model',
    fallbackModel: 'Yedek Model',
    apiKey: 'API Anahtarı',
    saveRoute: 'Rotayı Kaydet',
    savedSuccessfully: 'Yapay zeka rotası başarıyla kaydedildi.',
    saveFailed: 'Yapay zeka rota yapılandırması kaydedilemedi.',
  },
  mnemos: {
    title: 'Mnemos Kalıcı Bellek',
    description: 'Bağlam gerçekleri, anlamsal vektör araması ve oturumlar arası bilgi saklama.',
    searchFacts: 'Hatırlanan gerçekleri ara...',
    recall: 'Bilgiyi Hatırla',
    forget: 'Gerçeği Unut',
    totalFacts: 'Toplam Gerçek',
    noFactsRecorded: 'Henüz kayıtlı bellek gerçeği yok.',
  },
  kanban: {
    title: 'Swarm Kanban Matrisi',
    description: 'Gerçek zamanlı görev DAG ilerlemesi, çalışan atamaları ve onarım durumları.',
    backlog: 'Bekleme Listesi',
    inProgress: 'Devam Ediyor',
    review: 'İnceleme',
    autoRepairLane: 'Otomatik Onarım',
    done: 'Tamamlandı',
    createTask: 'Yeni Görev',
    taskTitle: 'Görev Başlığı',
    priority: 'Öncelik',
  },
  autoRepair: {
    title: 'Kapalı Döngü Otomatik Onarım',
    description: 'Otonom teşhis, yama oluşturma, test doğrulama ve geri alma.',
    resolvingFailure: 'Kod hatası çözülüyor...',
    patchApplied: 'Cerrahi yama uygulandı.',
    testsPassing: 'Doğrulama testleri geçti.',
    rollbackRecovered: 'Güvenli geri alma başarıyla sağlandı.',
    incidentHistory: 'Olay Geçmişi',
  },
  codeGraph: {
    title: 'AST Kod Tabanı Grafiği',
    description: 'Sembol tanımları, dosyalar arası çağrı bağımlılıkları ve etki analizi.',
    symbolsIndexed: 'Dizinlenen Semboller',
    callGraph: 'Çağrı Grafiği',
    impactAnalysis: 'Etki Analizi',
    callerDependencies: 'Arayan Bağımlılıkları',
  },
  diffReview: {
    title: 'Spekülatif Fark İncelemesi',
    description: 'Commit öncesi risk puanlaması, sözleşme koruması ve güvenlik denetimi.',
    riskRating: 'Risk Değerlendirmesi',
    securityAudit: 'Güvenlik Denetimi',
    secretCheck: 'Gizli Bilgi Sızıntısı Kontrolü',
    breakingChanges: 'Açık Sözleşme Bozulma Kontrolü',
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
  },
  approvals: {
    title: 'Yürütme Güvenlik Kapısı',
    description: 'Hassas araç çağrılarını, disk yazma işlemlerini ve kabuk komutlarını inceleyin ve onaylayın.',
    pendingApprovals: 'Bekleyen Onaylar',
    approve: 'Onayla',
    reject: 'Reddet',
    riskLevel: 'Risk Düzeyi',
    commandPreview: 'Komut Önizlemesi',
    noPendingApprovals: 'Bekleyen onay gerekmiyor.',
  },
  settings: {
    title: 'Sistem Ayarları',
    language: 'Dil',
    theme: 'Tema',
    logLevel: 'Günlük Düzeyi',
    resetDefaults: 'Varsayılanlara Sıfırla',
  },
  connections: {
    title: 'Evrensel Bağlantı Alt Sistemi',
    connectedSuccess: '**{target}** ile başarıyla bağlanıldı!',
    disconnectedSuccess: '**{target}** bağlantısı kesildi. Yerel kimlik bilgileri temizlendi.',
    alreadyConnected: '**{target}** hedefi zaten bağlı (durum: `connected`).',
    notConnected: "'{target}' ile aktif bir bağlantı yok.",
    unrecognizedTarget: "'{target}' hedefi tanınmadı.",
    rateLimitExceeded: 'Hız sınırı aşıldı: dakikada en fazla 10 bağlantı komutu yürütebilirsiniz. Lütfen bekleyin.',
    apiKeyPrompt: '**{target}** bağlantısı için {label} bilgilerinizi girin:\n`/connect {id} <anahtariniz>`',
    localPathPrompt: '**{target}** bağlantısı için yerel dizin yolunu belirtin:\n`/connect {id} /dizin/yolu/{kind}`',
    oauthDeviceCodePrompt: '**{target}** için cihaz yetkilendirmesini tamamlamak için:\n1. Açın: {url}\n2. Eşleştirme kodunu girin: `{code}`',
    catalogTitle: 'Kullanılabilir Bağlantı Kataloğu',
    noActiveConnections: 'Aktif bağlantı bulunamadı.\n\n• Entegrasyon bağlayın: `/connect <hedef>`\n• Kullanılabilir kataloğu görüntüleyin: `/connections catalog`',
    usageConnect: '**Connect Komutu Kullanımı:**\n`/connect <hedef> [kimlik_bilgisi]`\n\n**Örnekler:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /dizin/yolu/vault`\n\nTüm kullanılabilir hedefleri görmek için `/connections catalog` kullanın.',
    usageDisconnect: 'Kullanım: `/disconnect <hedef>`\nÖrnek: `/disconnect stripe`',
    handshakeInProgress: 'Bu hedef için zaten bir bağlantı el sıkışması sürüyor.',
    pathVerificationFailed: '❌ **{target}** için yol doğrulaması başarısız: {details}',
    apiKeyVerificationFailed: '❌ **{target}** için anahtar doğrulaması başarısız: {details}',
    oauthClickLink: '🔗 **{target} bağla:**\nZavorth’ı yetkilendirmek için aşağıdaki bağlantıya tıklayın:\n[{target} yetkilendir]({url})',
    oauthEnded: '⚠️ **{target}** için OAuth yetkilendirmesi sona erdi: {details}',
    activeConnectionsHeader: '**Aktif Bağlantılarınız ({count}):**',
    catalogEmpty: 'Bağlantı kataloğunda şu anda kullanılabilir hedef yok.',
    statusHeader: '**Bağlantı Sağlık Durumu:**',
    statusEmpty: 'Durum bildirecek aktif bağlantı yok.',
    guidanceLabel: '💡 **Rehberlik:**',
    reconnectHint: '• Yeniden bağlan veya kimlik bilgilerini güncelle: `/connect {target} <yeni_bilgiler>`',
    disconnectHint: '• Bağlantıyı kes: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Yerel dizin doğrulandı: `{path}`',
    credentialsVaultSuffix: 'Kimlik bilgileri şifrelendi ve kasaya güvenle kaydedildi.',
    secretStoreFailed: '❌ **{target}** için şifreli kimlik bilgileri kaydedilemedi: {details}',
    deviceCodeFlowInstructions: '🔑 **{target} bağla (Cihaz Kodu Akışı):**\n1. Yetkilendirme bağlantısını açın: {url}\n2. Tarayıcınızda yetkilendirmeyi onaylayın.\n3. Zavorth el sıkışmayı otomatik tamamlayacak.',
    missingDeviceVerificationUrl: 'Cihaz doğrulama URL’si eksik',
    oauthConnectedSuccess: '✅ OAuth2 ile **{target}** bağlantısı başarıyla kuruldu!',
    oauthExchangeFailed: '❌ **{target}** için OAuth token değişimi başarısız: {details}',
    oauthListenerFailed: '⚠️ OAuth geri çağrı dinleyicisi başlatılamadı: {details}',
    oauthConfigActive: '**{target}** için OAuth yapılandırması etkin.',
    catalogConnectHint: 'Herhangi bir hedefi bağlamak için şunu yazın: `/connect <hedef>`',
    statusLabel: 'Durum',
    healthLabel: 'Sağlık',
    authLabel: 'Kimlik',
    connectedAtLabel: 'Bağlanma zamanı',
    disconnectServiceHint: '• Hizmetin bağlantısını kes: `/disconnect <hedef>`',
  },
};
