import type { LocalizationCatalog } from '../localeContracts.js';

export const tr: LocalizationCatalog = {
  common: {
    save: 'Kaydet',
    saving: 'Kaydediliyor...',
    cancel: 'İptal',
    close: 'Kapat',
    confirm: 'Onayla',
    delete: 'Sil',
    refresh: 'Yenile',
    retry: 'Tekrar Dene',
    search: 'Ara...',
    loading: 'Yükleniyor...',
    create: 'Oluştur',
    creating: 'Oluşturuluyor...',
    clear: 'Temizle',
    enabled: 'Etkin',
    disabled: 'Devre Dışı',
    active: 'Aktif',
    inactive: 'Pasif',
    status: 'Durum',
    actions: 'Eylemler',
    details: 'Ayrıntılar',
    error: 'Hata',
    success: 'Başarılı',
    none: 'Yok',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Otonom Yapay Zeka Geliştirme Ortamı',
    chat: 'Sohbet',
    files: 'Dosyalar',
    approvals: 'Onaylar',
    memory: 'Mnemos Belleği',
    plugins: 'Eklentiler',
    channels: 'Kanallar',
    settings: 'Ayarlar',
    workboard: 'Kanban Matrisi',
    automations: 'Otomasyonlar',
    analytics: 'Analitik',
  },
  chat: {
    placeholder: 'Zavorth’a bir soru sorun veya bir geliştirme görevi atayın...',
    send: 'Gönder',
    stop: 'Durdur',
    clearHistory: 'Geçmişi Temizle',
    emptyState: 'Henüz mesaj yok. Başlamak için bir komut gönderin.',
    tokens: 'jeton',
    thinking: 'Düşünüyor...',
    errorOccurred: 'Yanıt oluşturulurken bir hata oluştu.',
  },
  channels: {
    title: 'Çok Kanallı Ağ Geçidi',
    description: 'Harici mesajlaşma platformu köprülerini yapılandırın ve izleyin.',
    primaryChannel: 'Birincil Kanal',
    telegram: 'Telegram Ağ Geçidi',
    discord: 'Discord Ağ Geçidi',
    slack: 'Slack Ağ Geçidi',
    whatsapp: 'WhatsApp Ağ Geçidi',
    web: 'Web Konsolu',
    notConfigured: 'Yapılandırılmadı',
    connected: 'Bağlandı',
    disconnected: 'Bağlantı Kesildi',
  },
  providers: {
    title: 'LLM Model Yönlendiricisi',
    description: 'Birincil yapay zeka sağlayıcılarını, API anahtarlarını ve yedek rotaları yapılandırın.',
    primaryProvider: 'Birincil Sağlayıcı',
    primaryModel: 'Birincil Model',
    fallbackModel: 'Yedek Model',
    apiKey: 'API Anahtarı',
    saveRoute: 'Rotayı Kaydet',
    savedSuccessfully: 'Yapay zeka rotası başarıyla kaydedildi.',
    saveFailed: 'Yapay zeka rota yapılandırması kaydedilemedi.',
  },
  mnemos: {
    title: 'Mnemos Kalıcı Bellek',
    description: 'Bağlam gerçekleri, anlamsal vektör araması ve oturumlar arası bilgi saklama.',
    searchFacts: 'Hatırlanan gerçekleri ara...',
    recall: 'Bilgiyi Hatırla',
    forget: 'Gerçeği Unut',
    totalFacts: 'Toplam Gerçek',
    noFactsRecorded: 'Henüz kayıtlı bellek gerçeği yok.',
  },
  kanban: {
    title: 'Swarm Kanban Matrisi',
    description: 'Gerçek zamanlı görev DAG ilerlemesi, çalışan atamaları ve onarım durumları.',
    backlog: 'Bekleme Listesi',
    inProgress: 'Devam Ediyor',
    review: 'İnceleme',
    autoRepairLane: 'Otomatik Onarım',
    done: 'Tamamlandı',
    createTask: 'Yeni Görev',
    taskTitle: 'Görev Başlığı',
    priority: 'Öncelik',
  },
  autoRepair: {
    title: 'Kapalı Döngü Otomatik Onarım',
    description: 'Otonom teşhis, yama oluşturma, test doğrulama ve geri alma.',
    resolvingFailure: 'Kod hatası çözülüyor...',
    patchApplied: 'Cerrahi yama uygulandı.',
    testsPassing: 'Doğrulama testleri geçti.',
    rollbackRecovered: 'Güvenli geri alma başarıyla sağlandı.',
    incidentHistory: 'Olay Geçmişi',
  },
  codeGraph: {
    title: 'AST Kod Tabanı Grafiği',
    description: 'Sembol tanımları, dosyalar arası çağrı bağımlılıkları ve etki analizi.',
    symbolsIndexed: 'Dizinlenen Semboller',
    callGraph: 'Çağrı Grafiği',
    impactAnalysis: 'Etki Analizi',
    callerDependencies: 'Arayan Bağımlılıkları',
  },
  diffReview: {
    title: 'Spekülatif Fark İncelemesi',
    description: 'Commit öncesi risk puanlaması, sözleşme koruması ve güvenlik denetimi.',
    riskRating: 'Risk Değerlendirmesi',
    securityAudit: 'Güvenlik Denetimi',
    secretCheck: 'Gizli Bilgi Sızıntısı Kontrolü',
    breakingChanges: 'Açık Sözleşme Bozulma Kontrolü',
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
  },
  approvals: {
    title: 'Yürütme Güvenlik Kapısı',
    description: 'Hassas araç çağrılarını, disk yazma işlemlerini ve kabuk komutlarını inceleyin ve onaylayın.',
    pendingApprovals: 'Bekleyen Onaylar',
    approve: 'Onayla',
    reject: 'Reddet',
    riskLevel: 'Risk Düzeyi',
    commandPreview: 'Komut Önizlemesi',
    noPendingApprovals: 'Bekleyen onay gerekmiyor.',
  },
  settings: {
    title: 'Sistem Ayarları',
    language: 'Dil',
    theme: 'Tema',
    logLevel: 'Günlük Düzeyi',
    resetDefaults: 'Varsayılanlara Sıfırla',
  },
};
