import type { LocalizationCatalog } from '../localeContracts.js';

export const uk: LocalizationCatalog = {
  common: {
    save: 'Зберегти',
    saving: 'Збереження...',
    cancel: 'Скасувати',
    close: 'Закрити',
    confirm: 'Підтвердити',
    delete: 'Видалити',
    refresh: 'Оновити',
    retry: 'Повторити',
    search: 'Пошук...',
    loading: 'Завантаження...',
    create: 'Створити',
    creating: 'Створення...',
    clear: 'Очистити',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено',
    active: 'Активно',
    inactive: 'Неактивно',
    status: 'Статус',
    actions: 'Дії',
    details: 'Деталі',
    error: 'Помилка',
    success: 'Успіх',
    none: 'Немає',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Автономне середовище розробки ШІ',
    chat: 'Чат',
    files: 'Файли',
    approvals: 'Схвалення',
    memory: 'Пам’ять Mnemos',
    plugins: 'Плагіни',
    channels: 'Канали',
    settings: 'Налаштування',
    workboard: 'Матриця Канбан',
    automations: 'Автоматизація',
    analytics: 'Аналітика',
  },
  chat: {
    placeholder: 'Задайте питання Zavorth або призначте завдання розробки...',
    send: 'Надіслати',
    stop: 'Зупинити',
    clearHistory: 'Очистити історію',
    emptyState: 'Повідомлень ще немає. Надішліть команду для початку.',
    tokens: 'токенів',
    thinking: 'Розмірковування...',
    errorOccurred: 'Під час генерації відповіді сталася помилка.',
  },
  channels: {
    title: 'Багатоканальний шлюз',
    description: 'Налаштування та моніторинг мостів зовнішніх платформ обміну повідомленнями.',
    primaryChannel: 'Основний канал',
    telegram: 'Шлюз Telegram',
    discord: 'Шлюз Discord',
    slack: 'Шлюз Slack',
    whatsapp: 'Шлюз WhatsApp',
    web: 'Веб-консоль',
    notConfigured: 'Не налаштовано',
    connected: 'Підключено',
    disconnected: 'Відключено',
  },
  providers: {
    title: 'Маршрутизатор моделей LLM',
    description: 'Налаштування основних провайдерів ШІ, ключів API та резервних маршрутів.',
    primaryProvider: 'Основний провайдер',
    primaryModel: 'Основна модель',
    fallbackModel: 'Резервна модель',
    apiKey: 'Ключ API',
    saveRoute: 'Зберегти маршрут',
    savedSuccessfully: 'Маршрут ШІ успішно збережено.',
    saveFailed: 'Не вдалося зберегти налаштування маршруту ШІ.',
  },
  mnemos: {
    title: 'Постійна пам’ять Mnemos',
    description: 'Контекстні факти, семантичний векторний пошук та збереження знань.',
    searchFacts: 'Пошук збережених фактів...',
    recall: 'Згадати знання',
    forget: 'Забути факт',
    totalFacts: 'Всього фактів',
    noFactsRecorded: 'Фактів пам’яті ще не записано.',
  },
  kanban: {
    title: 'Матриця Канбан Swarm',
    description: 'Відстеження DAG завдань у реальному часі, призначення виконавців та статус відновлення.',
    backlog: 'Беклог',
    inProgress: 'У роботі',
    review: 'Перевірка',
    autoRepairLane: 'Авто-відновлення',
    done: 'Готово',
    createTask: 'Нове завдання',
    taskTitle: 'Назва завдання',
    priority: 'Пріоритет',
  },
  autoRepair: {
    title: 'Авто-відновлення в замкненому циклі',
    description: 'Автономна діагностика, генерація виправлень, перевірка тестів та відкат.',
    resolvingFailure: 'Усунення збою коду...',
    patchApplied: 'Точкове виправлення застосовано.',
    testsPassing: 'Перевірочні тести пройдено.',
    rollbackRecovered: 'Безпечний відкат успішно відновлено.',
    incidentHistory: 'Історія інцидентів',
  },
  codeGraph: {
    title: 'AST Граф кодової бази',
    description: 'Визначення символів, залежності викликів та аналіз впливу.',
    symbolsIndexed: 'Індексовано символів',
    callGraph: 'Граф викликів',
    impactAnalysis: 'Аналіз впливу',
    callerDependencies: 'Залежності викликаючих об’єктів',
  },
  diffReview: {
    title: 'Спекулятивний огляд Diff',
    description: 'Оцінка ризиків перед комітом, захист контрактів та аудит безпеки.',
    riskRating: 'Оцінка ризику',
    securityAudit: 'Аудит безпеки',
    secretCheck: 'Перевірка витоку секретів',
    breakingChanges: 'Перевірка порушення контрактів',
    approved: 'Схвалено',
    rejected: 'Відхилено',
  },
  approvals: {
    title: 'Шлюз безпеки виконання',
    description: 'Перевірка та схвалення викликів чутливих інструментів, запису на диск та команд shell.',
    pendingApprovals: 'Очікують схвалення',
    approve: 'Схвалити',
    reject: 'Відхилити',
    riskLevel: 'Рівень ризику',
    commandPreview: 'Попередній перегляд команди',
    noPendingApprovals: 'Немає запитів на схвалення.',
  },
  settings: {
    title: 'Налаштування системи',
    language: 'Мова',
    theme: 'Тема',
    logLevel: 'Рівень журналу',
    resetDefaults: 'Скинути до типових',
  },
  connections: {
    title: 'Універсальна підсистема підключень',
    connectedSuccess: 'Успішно підключено до **{target}**!',
    disconnectedSuccess: 'Відключено від **{target}**. Локальні облікові дані видалено.',
    alreadyConnected: 'Ціль **{target}** уже підключена (статус: `connected`).',
    notConnected: "Немає активного підключення до '{target}'.",
    unrecognizedTarget: "Ціль '{target}' не розпізнано.",
    rateLimitExceeded: 'Перевищено ліміт частоти: можна виконувати не більше 10 команд підключення за хвилину. Будь ласка, зачекайте.',
    apiKeyPrompt: 'Щоб підключити **{target}**, вкажіть ваш {label}:\n`/connect {id} <ваш_ключ>`',
    localPathPrompt: 'Щоб підключити **{target}**, вкажіть шлях до локального каталогу:\n`/connect {id} /шлях/до/{kind}`',
    oauthDeviceCodePrompt: 'Щоб завершити авторизацію пристрою для **{target}**:\n1. Відкрийте: {url}\n2. Введіть код сполучення: `{code}`',
    catalogTitle: 'Каталог доступних підключень',
    noActiveConnections: 'Активних підключень не знайдено.\n\n• Підключити інтеграцію: `/connect <ціль>`\n• Переглянути каталог: `/connections catalog`',
    usageConnect: '**Використання команди Connect:**\n`/connect <ціль> [облікові_дані]`\n\n**Приклади:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /шлях/до/vault`\n\nВикористовуйте `/connections catalog`, щоб побачити всі доступні цілі.',
    usageDisconnect: 'Використання: `/disconnect <ціль>`\nПриклад: `/disconnect stripe`',
    handshakeInProgress: 'Для цієї цілі вже триває спроба підключення.',
    pathVerificationFailed: '❌ Не вдалося перевірити шлях для **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Не вдалося перевірити ключ для **{target}**: {details}',
    oauthClickLink: '🔗 **Підключити {target}:**\nНатисніть на посилання нижче, щоб авторизувати Zavorth:\n[Авторизувати {target}]({url})',
    oauthEnded: '⚠️ OAuth-авторизацію для **{target}** завершено: {details}',
    activeConnectionsHeader: '**Ваші активні підключення ({count}):**',
    catalogEmpty: 'У каталозі підключень зараз немає доступних цілей.',
    statusHeader: '**Стан працездатності підключень:**',
    statusEmpty: 'Немає активних підключень для відображення стану.',
    guidanceLabel: '💡 **Порада:**',
    reconnectHint: '• Перепідключити або оновити облікові дані: `/connect {target} <нові_дані>`',
    disconnectHint: '• Відключити: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Локальний каталог перевірено: `{path}`',
    credentialsVaultSuffix: 'Облікові дані зашифровано та безпечно збережено у сховищі.',
    secretStoreFailed: '❌ Не вдалося зберегти зашифровані облікові дані для **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Підключити {target} (Device Code Flow):**\n1. Відкрийте посилання авторизації: {url}\n2. Підтвердьте авторизацію у браузері.\n3. Zavorth автоматично завершить handshake.',
    missingDeviceVerificationUrl: 'Відсутній URL перевірки пристрою',
    oauthConnectedSuccess: '✅ Успішно підключено до **{target}** через OAuth2!',
    oauthExchangeFailed: '❌ Помилка обміну токенами OAuth для **{target}**: {details}',
    oauthListenerFailed: '⚠️ Не вдалося запустити слухач OAuth-колбеків: {details}',
    oauthConfigActive: 'Конфігурація OAuth для **{target}** активна.',
    catalogConnectHint: 'Щоб підключити будь-яку ціль, введіть: `/connect <ціль>`',
    statusLabel: 'Статус',
    healthLabel: 'Працездатність',
    authLabel: 'Автентифікація',
    connectedAtLabel: 'Підключено',
    disconnectServiceHint: '• Відключити сервіс: `/disconnect <ціль>`',
  },
};
