import type { LocalizationCatalog } from '../localeContracts.js';

export const uk: LocalizationCatalog = {
  common: {
    save: 'Зберегти',
    saving: 'Збереження...',
    cancel: 'Скасувати',
    close: 'Закрити',
    confirm: 'Підтвердити',
    delete: 'Видалити',
    refresh: 'Оновити',
    retry: 'Повторити',
    search: 'Пошук...',
    loading: 'Завантаження...',
    create: 'Створити',
    creating: 'Створення...',
    clear: 'Очистити',
    enabled: 'Увімкнено',
    disabled: 'Вимкнено',
    active: 'Активно',
    inactive: 'Неактивно',
    status: 'Статус',
    actions: 'Дії',
    details: 'Деталі',
    error: 'Помилка',
    success: 'Успіх',
    none: 'Немає',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: 'Автономне середовище розробки ШІ',
    chat: 'Чат',
    files: 'Файли',
    approvals: 'Схвалення',
    memory: 'Пам’ять Mnemos',
    plugins: 'Плагіни',
    channels: 'Канали',
    settings: 'Налаштування',
    workboard: 'Матриця Канбан',
    automations: 'Автоматизація',
    analytics: 'Аналітика',
  },
  chat: {
    placeholder: 'Задайте питання Zavorth або призначте завдання розробки...',
    send: 'Надіслати',
    stop: 'Зупинити',
    clearHistory: 'Очистити історію',
    emptyState: 'Повідомлень ще немає. Надішліть команду для початку.',
    tokens: 'токенів',
    thinking: 'Розмірковування...',
    errorOccurred: 'Під час генерації відповіді сталася помилка.',
  },
  channels: {
    title: 'Багатоканальний шлюз',
    description: 'Налаштування та моніторинг мостів зовнішніх платформ обміну повідомленнями.',
    primaryChannel: 'Основний канал',
    telegram: 'Шлюз Telegram',
    discord: 'Шлюз Discord',
    slack: 'Шлюз Slack',
    whatsapp: 'Шлюз WhatsApp',
    web: 'Веб-консоль',
    notConfigured: 'Не налаштовано',
    connected: 'Підключено',
    disconnected: 'Відключено',
  },
  providers: {
    title: 'Маршрутизатор моделей LLM',
    description: 'Налаштування основних провайдерів ШІ, ключів API та резервних маршрутів.',
    primaryProvider: 'Основний провайдер',
    primaryModel: 'Основна модель',
    fallbackModel: 'Резервна модель',
    apiKey: 'Ключ API',
    saveRoute: 'Зберегти маршрут',
    savedSuccessfully: 'Маршрут ШІ успішно збережено.',
    saveFailed: 'Не вдалося зберегти налаштування маршруту ШІ.',
  },
  mnemos: {
    title: 'Постійна пам’ять Mnemos',
    description: 'Контекстні факти, семантичний векторний пошук та збереження знань.',
    searchFacts: 'Пошук збережених фактів...',
    recall: 'Згадати знання',
    forget: 'Забути факт',
    totalFacts: 'Всього фактів',
    noFactsRecorded: 'Фактів пам’яті ще не записано.',
  },
  kanban: {
    title: 'Матриця Канбан Swarm',
    description: 'Відстеження DAG завдань у реальному часі, призначення виконавців та статус відновлення.',
    backlog: 'Беклог',
    inProgress: 'У роботі',
    review: 'Перевірка',
    autoRepairLane: 'Авто-відновлення',
    done: 'Готово',
    createTask: 'Нове завдання',
    taskTitle: 'Назва завдання',
    priority: 'Пріоритет',
  },
  autoRepair: {
    title: 'Авто-відновлення в замкненому циклі',
    description: 'Автономна діагностика, генерація виправлень, перевірка тестів та відкат.',
    resolvingFailure: 'Усунення збою коду...',
    patchApplied: 'Точкове виправлення застосовано.',
    testsPassing: 'Перевірочні тести пройдено.',
    rollbackRecovered: 'Безпечний відкат успішно відновлено.',
    incidentHistory: 'Історія інцидентів',
  },
  codeGraph: {
    title: 'AST Граф кодової бази',
    description: 'Визначення символів, залежності викликів та аналіз впливу.',
    symbolsIndexed: 'Індексовано символів',
    callGraph: 'Граф викликів',
    impactAnalysis: 'Аналіз впливу',
    callerDependencies: 'Залежності викликаючих об’єктів',
  },
  diffReview: {
    title: 'Спекулятивний огляд Diff',
    description: 'Оцінка ризиків перед комітом, захист контрактів та аудит безпеки.',
    riskRating: 'Оцінка ризику',
    securityAudit: 'Аудит безпеки',
    secretCheck: 'Перевірка витоку секретів',
    breakingChanges: 'Перевірка порушення контрактів',
    approved: 'Схвалено',
    rejected: 'Відхилено',
  },
  approvals: {
    title: 'Шлюз безпеки виконання',
    description: 'Перевірка та схвалення викликів чутливих інструментів, запису на диск та команд shell.',
    pendingApprovals: 'Очікують схвалення',
    approve: 'Схвалити',
    reject: 'Відхилити',
    riskLevel: 'Рівень ризику',
    commandPreview: 'Попередній перегляд команди',
    noPendingApprovals: 'Немає запитів на схвалення.',
  },
  settings: {
    title: 'Налаштування системи',
    language: 'Мова',
    theme: 'Тема',
    logLevel: 'Рівень журналу',
    resetDefaults: 'Скинути до типових',
  },
};
