import type { LocalizationCatalog } from '../localeContracts.js';

export const zhHant: LocalizationCatalog = {
  common: {
    save: '儲存',
    saving: '儲存中...',
    cancel: '取消',
    close: '關閉',
    confirm: '確認',
    delete: '刪除',
    refresh: '重新整理',
    retry: '重試',
    search: '搜尋...',
    loading: '載入中...',
    create: '建立',
    creating: '建立中...',
    clear: '清除',
    enabled: '已啟用',
    disabled: '已停用',
    active: '活躍',
    inactive: '未啟用',
    status: '狀態',
    actions: '操作',
    details: '詳細資訊',
    error: '錯誤',
    success: '成功',
    none: '無',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '自主 AI 開發套件',
    chat: '對話',
    files: '檔案',
    approvals: '審批',
    memory: 'Mnemos 記憶',
    plugins: '外掛模組',
    channels: '通道',
    settings: '設定',
    workboard: '看板矩陣',
    automations: '自動化',
    analytics: '分析',
  },
  chat: {
    placeholder: '向 Zavorth 提問或指派開發任務...',
    send: '發送',
    stop: '停止',
    clearHistory: '清除歷史',
    emptyState: '尚無訊息。發送指令即可開始。',
    tokens: '代幣',
    thinking: '思考中...',
    errorOccurred: '產生回應時發生錯誤。',
  },
  channels: {
    title: '多通道閘道',
    description: '設定和監控外部訊息平台橋接。',
    primaryChannel: '主通道',
    telegram: 'Telegram 閘道',
    discord: 'Discord 閘道',
    slack: 'Slack 閘道',
    whatsapp: 'WhatsApp 閘道',
    web: 'Web 主控台',
    notConfigured: '未設定',
    connected: '已連線',
    disconnected: '已中斷連線',
  },
  providers: {
    title: 'LLM 模型路由器',
    description: '設定主要 AI 提供商、API 憑證和備援路由。',
    primaryProvider: '主要提供商',
    primaryModel: '主要模型',
    fallbackModel: '備援模型',
    apiKey: 'API 金鑰',
    saveRoute: '儲存路由',
    savedSuccessfully: 'AI 路由儲存成功。',
    saveFailed: '儲存 AI 路由設定失敗。',
  },
  mnemos: {
    title: 'Mnemos 持久化記憶',
    description: '上下文事實、語意向量檢索和跨工作階段知識儲存。',
    searchFacts: '搜尋記憶事實...',
    recall: '召回知識',
    forget: '遺忘事實',
    totalFacts: '事實總數',
    noFactsRecorded: '尚無記錄的記憶事實。',
  },
  kanban: {
    title: 'Swarm 看板矩陣',
    description: '即時任務 DAG 進度、執行者指派和修復狀態。',
    backlog: '待辦',
    inProgress: '進行中',
    review: '審查',
    autoRepairLane: '自動修復',
    done: '已完成',
    createTask: '新增任務',
    taskTitle: '任務標題',
    priority: '優先順序',
  },
  autoRepair: {
    title: '閉環自動修復',
    description: '自主診斷、程式碼修補產生、測試驗證和復原恢復。',
    resolvingFailure: '正在解決程式碼故障...',
    patchApplied: '已套用精確修補。',
    testsPassing: '驗證測試已通過。',
    rollbackRecovered: '安全復原已恢復。',
    incidentHistory: '事件歷程記錄',
  },
  codeGraph: {
    title: 'AST 程式碼庫圖譜',
    description: '符號定義、跨檔案呼叫相依性與影響分析。',
    symbolsIndexed: '已索引符號',
    callGraph: '呼叫圖譜',
    impactAnalysis: '影響分析',
    callerDependencies: '呼叫相依項目',
  },
  diffReview: {
    title: '推測性 Diff 審查',
    description: '認可前風險評分、合約保護與安全稽核。',
    riskRating: '風險評級',
    securityAudit: '安全稽核',
    secretCheck: '密鑰洩漏檢查',
    breakingChanges: '公開合約檢查',
    approved: '已批准',
    rejected: '已拒絕',
  },
  approvals: {
    title: '執行安全閘道',
    description: '審查並批准敏感工具呼叫、磁碟寫入與 Shell 執行。',
    pendingApprovals: '待審批項目',
    approve: '批准',
    reject: '拒絕',
    riskLevel: '風險等級',
    commandPreview: '命令預覽',
    noPendingApprovals: '無須待審批項目。',
  },
  settings: {
    title: '系統設定',
    language: '語言',
    theme: '佈景主題',
    logLevel: '記錄層級',
    resetDefaults: '重設為預設值',
  },
  connections: {
    title: '通用連線子系統',
    connectedSuccess: '已成功連線到 **{target}**！',
    disconnectedSuccess: '已從 **{target}** 中斷連線。本機憑證已清除。',
    alreadyConnected: '目標 **{target}** 已處於連線狀態（狀態：`connected`）。',
    notConnected: "目前未連線到 '{target}'。",
    unrecognizedTarget: "無法識別目標 '{target}'。",
    rateLimitExceeded: '已超出頻率限制：每分鐘最多執行 10 條連線指令。請稍候。',
    apiKeyPrompt: '要連線 **{target}**，請提供你的 {label}：\n`/connect {id} <你的金鑰>`',
    localPathPrompt: '要連線 **{target}**，請指定本機目錄路徑：\n`/connect {id} /path/to/{kind}`',
    oauthDeviceCodePrompt: '要完成 **{target}** 的裝置授權：\n1. 開啟：{url}\n2. 輸入配對碼：`{code}`',
    catalogTitle: '可用連線目錄',
    noActiveConnections: '找不到使用中的連線。\n\n• 連線整合：`/connect <目標>`\n• 檢視可用目錄：`/connections catalog`',
    usageConnect: '**Connect 指令用法：**\n`/connect <目標> [憑證]`\n\n**範例：**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /path/to/vault`\n\n使用 `/connections catalog` 檢視所有可用目標。',
    usageDisconnect: '用法：`/disconnect <目標>`\n範例：`/disconnect stripe`',
    handshakeInProgress: '此目標已有連線交握正在進行中。',
    pathVerificationFailed: '❌ **{target}** 的路徑驗證失敗：{details}',
    apiKeyVerificationFailed: '❌ **{target}** 的金鑰驗證失敗：{details}',
    oauthClickLink: '🔗 **連線 {target}：**\n點擊下方連結以授權 Zavorth：\n[授權 {target}]({url})',
    oauthEnded: '⚠️ **{target}** 的 OAuth 授權已結束：{details}',
    activeConnectionsHeader: '**你的使用中連線（{count}）：**',
    catalogEmpty: '目前連線目錄中沒有可用目標。',
    statusHeader: '**連線健康狀態：**',
    statusEmpty: '沒有可回報狀態的使用中連線。',
    guidanceLabel: '💡 **指引：**',
    reconnectHint: '• 重新連線或更新憑證：`/connect {target} <新憑證>`',
    disconnectHint: '• 中斷連線：`/disconnect {target}`',
    localPathVerifiedSuffix: '本機目錄已驗證：`{path}`',
    credentialsVaultSuffix: '憑證已加密並安全儲存在保管庫中。',
    secretStoreFailed: '❌ **{target}** 的加密憑證儲存失敗：{details}',
    deviceCodeFlowInstructions: '🔑 **連線 {target}（裝置碼流程）：**\n1. 開啟授權連結：{url}\n2. 在瀏覽器中確認授權。\n3. Zavorth 將自動完成交握。',
    missingDeviceVerificationUrl: '缺少裝置驗證 URL',
    oauthConnectedSuccess: '✅ 已透過 OAuth2 成功連線到 **{target}**！',
    oauthExchangeFailed: '❌ **{target}** 的 OAuth 權杖交換失敗：{details}',
    oauthListenerFailed: '⚠️ OAuth 回呼監聽器啟動失敗：{details}',
    oauthConfigActive: '**{target}** 的 OAuth 設定已生效。',
    catalogConnectHint: '要連線任意目標，請輸入：`/connect <目標>`',
    statusLabel: '狀態',
    healthLabel: '健康度',
    authLabel: '認證',
    connectedAtLabel: '連線時間',
    disconnectServiceHint: '• 中斷服務：`/disconnect <目標>`',
  },
};
