import type { LocalizationCatalog } from '../localeContracts.js';

export const zhHant: LocalizationCatalog = {
  common: {
    save: '儲存',
    saving: '儲存中...',
    cancel: '取消',
    close: '關閉',
    confirm: '確認',
    delete: '刪除',
    refresh: '重新整理',
    retry: '重試',
    search: '搜尋...',
    loading: '載入中...',
    create: '建立',
    creating: '建立中...',
    clear: '清除',
    enabled: '已啟用',
    disabled: '已停用',
    active: '活躍',
    inactive: '未啟用',
    status: '狀態',
    actions: '操作',
    details: '詳細資訊',
    error: '錯誤',
    success: '成功',
    none: '無',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '自主 AI 開發套件',
    chat: '對話',
    files: '檔案',
    approvals: '審批',
    memory: 'Mnemos 記憶',
    plugins: '外掛模組',
    channels: '通道',
    settings: '設定',
    workboard: '看板矩陣',
    automations: '自動化',
    analytics: '分析',
  },
  chat: {
    placeholder: '向 Zavorth 提問或指派開發任務...',
    send: '發送',
    stop: '停止',
    clearHistory: '清除歷史',
    emptyState: '尚無訊息。發送指令即可開始。',
    tokens: '代幣',
    thinking: '思考中...',
    errorOccurred: '產生回應時發生錯誤。',
  },
  channels: {
    title: '多通道閘道',
    description: '設定和監控外部訊息平台橋接。',
    primaryChannel: '主通道',
    telegram: 'Telegram 閘道',
    discord: 'Discord 閘道',
    slack: 'Slack 閘道',
    whatsapp: 'WhatsApp 閘道',
    web: 'Web 主控台',
    notConfigured: '未設定',
    connected: '已連線',
    disconnected: '已中斷連線',
  },
  providers: {
    title: 'LLM 模型路由器',
    description: '設定主要 AI 提供商、API 憑證和備援路由。',
    primaryProvider: '主要提供商',
    primaryModel: '主要模型',
    fallbackModel: '備援模型',
    apiKey: 'API 金鑰',
    saveRoute: '儲存路由',
    savedSuccessfully: 'AI 路由儲存成功。',
    saveFailed: '儲存 AI 路由設定失敗。',
  },
  mnemos: {
    title: 'Mnemos 持久化記憶',
    description: '上下文事實、語意向量檢索和跨工作階段知識儲存。',
    searchFacts: '搜尋記憶事實...',
    recall: '召回知識',
    forget: '遺忘事實',
    totalFacts: '事實總數',
    noFactsRecorded: '尚無記錄的記憶事實。',
  },
  kanban: {
    title: 'Swarm 看板矩陣',
    description: '即時任務 DAG 進度、執行者指派和修復狀態。',
    backlog: '待辦',
    inProgress: '進行中',
    review: '審查',
    autoRepairLane: '自動修復',
    done: '已完成',
    createTask: '新增任務',
    taskTitle: '任務標題',
    priority: '優先順序',
  },
  autoRepair: {
    title: '閉環自動修復',
    description: '自主診斷、程式碼修補產生、測試驗證和復原恢復。',
    resolvingFailure: '正在解決程式碼故障...',
    patchApplied: '已套用精確修補。',
    testsPassing: '驗證測試已通過。',
    rollbackRecovered: '安全復原已恢復。',
    incidentHistory: '事件歷程記錄',
  },
  codeGraph: {
    title: 'AST 程式碼庫圖譜',
    description: '符號定義、跨檔案呼叫相依性與影響分析。',
    symbolsIndexed: '已索引符號',
    callGraph: '呼叫圖譜',
    impactAnalysis: '影響分析',
    callerDependencies: '呼叫相依項目',
  },
  diffReview: {
    title: '推測性 Diff 審查',
    description: '認可前風險評分、合約保護與安全稽核。',
    riskRating: '風險評級',
    securityAudit: '安全稽核',
    secretCheck: '密鑰洩漏檢查',
    breakingChanges: '公開合約檢查',
    approved: '已批准',
    rejected: '已拒絕',
  },
  approvals: {
    title: '執行安全閘道',
    description: '審查並批准敏感工具呼叫、磁碟寫入與 Shell 執行。',
    pendingApprovals: '待審批項目',
    approve: '批准',
    reject: '拒絕',
    riskLevel: '風險等級',
    commandPreview: '命令預覽',
    noPendingApprovals: '無須待審批項目。',
  },
  settings: {
    title: '系統設定',
    language: '語言',
    theme: '佈景主題',
    logLevel: '記錄層級',
    resetDefaults: '重設為預設值',
  },
};
