import type { LocalizationCatalog } from '../localeContracts.js';

export const zh: LocalizationCatalog = {
  common: {
    save: '保存',
    saving: '保存中...',
    cancel: '取消',
    close: '关闭',
    confirm: '确认',
    delete: '删除',
    refresh: '刷新',
    retry: '重试',
    search: '搜索...',
    loading: '加载中...',
    create: '创建',
    creating: '创建中...',
    clear: '清除',
    enabled: '已启用',
    disabled: '已禁用',
    active: '活跃',
    inactive: '未激活',
    status: '状态',
    actions: '操作',
    details: '详情',
    error: '错误',
    success: '成功',
    none: '无',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '自主 AI 开发套件',
    chat: '对话',
    files: '文件',
    approvals: '审批',
    memory: 'Mnemos 记忆',
    plugins: '插件',
    channels: '通道',
    settings: '设置',
    workboard: '看板矩阵',
    automations: '自动化',
    analytics: '分析',
  },
  chat: {
    placeholder: '向 Zavorth 提问或分配开发任务...',
    send: '发送',
    stop: '停止',
    clearHistory: '清除历史',
    emptyState: '暂无消息。发送指令即可开始。',
    tokens: '代币',
    thinking: '思考中...',
    errorOccurred: '生成响应时发生错误。',
  },
  channels: {
    title: '多通道网关',
    description: '配置和监控外部消息平台网桥。',
    primaryChannel: '主通道',
    telegram: 'Telegram 网关',
    discord: 'Discord 网关',
    slack: 'Slack 网关',
    whatsapp: 'WhatsApp 网关',
    web: 'Web 控制台',
    notConfigured: '未配置',
    connected: '已连接',
    disconnected: '已断开',
  },
  providers: {
    title: 'LLM 模型路由器',
    description: '配置主要 AI 提供商、API 凭据和后备路由。',
    primaryProvider: '主要提供商',
    primaryModel: '主要模型',
    fallbackModel: '后备模型',
    apiKey: 'API 密钥',
    saveRoute: '保存路由',
    savedSuccessfully: 'AI 路由保存成功。',
    saveFailed: '保存 AI 路由配置失败。',
  },
  mnemos: {
    title: 'Mnemos 持久化记忆',
    description: '上下文事实、语义向量检索和跨会话知识存储。',
    searchFacts: '搜索记忆事实...',
    recall: '召回知识',
    forget: '遗忘事实',
    totalFacts: '事实总数',
    noFactsRecorded: '暂无记录的记忆事实。',
  },
  kanban: {
    title: 'Swarm 看板矩阵',
    description: '实时任务 DAG 进度、执行者分配和修复状态。',
    backlog: '待办',
    inProgress: '进行中',
    review: '评审',
    autoRepairLane: '自动修复',
    done: '已完成',
    createTask: '新建任务',
    taskTitle: '任务标题',
    priority: '优先级',
  },
  autoRepair: {
    title: '闭环自动修复',
    description: '自主诊断、代码补丁生成、测试验证和回滚恢复。',
    resolvingFailure: '正在解决代码故障...',
    patchApplied: '已应用精准补丁。',
    testsPassing: '验证测试已通过。',
    rollbackRecovered: '安全回滚已恢复。',
    incidentHistory: '故障历史',
  },
  codeGraph: {
    title: 'AST 代码库图谱',
    description: '符号定义、跨文件调用依赖关系和影响分析。',
    symbolsIndexed: '已索引符号',
    callGraph: '调用图谱',
    impactAnalysis: '影响分析',
    callerDependencies: '调用依赖项',
  },
  diffReview: {
    title: '推测性 Diff 审查',
    description: '提交前风险评分、契约保护和安全审计。',
    riskRating: '风险评级',
    securityAudit: '安全审计',
    secretCheck: '密钥泄露检查',
    breakingChanges: '公开契约检查',
    approved: '已批准',
    rejected: '已拒绝',
  },
  approvals: {
    title: '执行安全网关',
    description: '审查并批准敏感工具调用、磁盘写入和 Shell 执行。',
    pendingApprovals: '待审批项',
    approve: '批准',
    reject: '拒绝',
    riskLevel: '风险等级',
    commandPreview: '命令预览',
    noPendingApprovals: '无需待审批项。',
  },
  settings: {
    title: '系统设置',
    language: '语言',
    theme: '主题',
    logLevel: '日志级别',
    resetDefaults: '恢复默认设置',
  },
};
