import type { LocalizationCatalog } from '../localeContracts.js';

export const zh: LocalizationCatalog = {
  common: {
    save: '保存',
    saving: '保存中...',
    cancel: '取消',
    close: '关闭',
    confirm: '确认',
    delete: '删除',
    refresh: '刷新',
    retry: '重试',
    search: '搜索...',
    loading: '加载中...',
    create: '创建',
    creating: '创建中...',
    clear: '清除',
    enabled: '已启用',
    disabled: '已禁用',
    active: '活跃',
    inactive: '未激活',
    status: '状态',
    actions: '操作',
    details: '详情',
    error: '错误',
    success: '成功',
    none: '无',
  },
  app: {
    title: 'Zavorth Desktop',
    tagline: '自主 AI 开发套件',
    chat: '对话',
    files: '文件',
    approvals: '审批',
    memory: 'Mnemos 记忆',
    plugins: '插件',
    channels: '通道',
    settings: '设置',
    workboard: '看板矩阵',
    automations: '自动化',
    analytics: '分析',
  },
  chat: {
    placeholder: '向 Zavorth 提问或分配开发任务...',
    send: '发送',
    stop: '停止',
    clearHistory: '清除历史',
    emptyState: '暂无消息。发送指令即可开始。',
    tokens: '代币',
    thinking: '思考中...',
    errorOccurred: '生成响应时发生错误。',
  },
  channels: {
    title: '多通道网关',
    description: '配置和监控外部消息平台网桥。',
    primaryChannel: '主通道',
    telegram: 'Telegram 网关',
    discord: 'Discord 网关',
    slack: 'Slack 网关',
    whatsapp: 'WhatsApp 网关',
    web: 'Web 控制台',
    notConfigured: '未配置',
    connected: '已连接',
    disconnected: '已断开',
  },
  providers: {
    title: 'LLM 模型路由器',
    description: '配置主要 AI 提供商、API 凭据和后备路由。',
    primaryProvider: '主要提供商',
    primaryModel: '主要模型',
    fallbackModel: '后备模型',
    apiKey: 'API 密钥',
    saveRoute: '保存路由',
    savedSuccessfully: 'AI 路由保存成功。',
    saveFailed: '保存 AI 路由配置失败。',
  },
  mnemos: {
    title: 'Mnemos 持久化记忆',
    description: '上下文事实、语义向量检索和跨会话知识存储。',
    searchFacts: '搜索记忆事实...',
    recall: '召回知识',
    forget: '遗忘事实',
    totalFacts: '事实总数',
    noFactsRecorded: '暂无记录的记忆事实。',
  },
  kanban: {
    title: 'Swarm 看板矩阵',
    description: '实时任务 DAG 进度、执行者分配和修复状态。',
    backlog: '待办',
    inProgress: '进行中',
    review: '评审',
    autoRepairLane: '自动修复',
    done: '已完成',
    createTask: '新建任务',
    taskTitle: '任务标题',
    priority: '优先级',
  },
  autoRepair: {
    title: '闭环自动修复',
    description: '自主诊断、代码补丁生成、测试验证和回滚恢复。',
    resolvingFailure: '正在解决代码故障...',
    patchApplied: '已应用精准补丁。',
    testsPassing: '验证测试已通过。',
    rollbackRecovered: '安全回滚已恢复。',
    incidentHistory: '故障历史',
  },
  codeGraph: {
    title: 'AST 代码库图谱',
    description: '符号定义、跨文件调用依赖关系和影响分析。',
    symbolsIndexed: '已索引符号',
    callGraph: '调用图谱',
    impactAnalysis: '影响分析',
    callerDependencies: '调用依赖项',
  },
  diffReview: {
    title: '推测性 Diff 审查',
    description: '提交前风险评分、契约保护和安全审计。',
    riskRating: '风险评级',
    securityAudit: '安全审计',
    secretCheck: '密钥泄露检查',
    breakingChanges: '公开契约检查',
    approved: '已批准',
    rejected: '已拒绝',
  },
  approvals: {
    title: '执行安全网关',
    description: '审查并批准敏感工具调用、磁盘写入和 Shell 执行。',
    pendingApprovals: '待审批项',
    approve: '批准',
    reject: '拒绝',
    riskLevel: '风险等级',
    commandPreview: '命令预览',
    noPendingApprovals: '无需待审批项。',
  },
  settings: {
    title: '系统设置',
    language: '语言',
    theme: '主题',
    logLevel: '日志级别',
    resetDefaults: '恢复默认设置',
  },
  connections: {
    title: '通用连接子系统',
    connectedSuccess: '已成功连接到 **{target}**！',
    disconnectedSuccess: '已从 **{target}** 断开连接。本地凭据已清除。',
    alreadyConnected: '目标 **{target}** 已处于连接状态（状态：`connected`）。',
    notConnected: "当前未连接到 '{target}'。",
    unrecognizedTarget: "无法识别目标 '{target}'。",
    rateLimitExceeded: '已超出频率限制：每分钟最多执行 10 条连接命令。请稍候。',
    apiKeyPrompt: '要连接 **{target}**，请提供你的 {label}：\n`/connect {id} <你的密钥>`',
    localPathPrompt: '要连接 **{target}**，请指定本地目录路径：\n`/connect {id} /path/to/{kind}`',
    oauthDeviceCodePrompt: '要完成 **{target}** 的设备授权：\n1. 打开：{url}\n2. 输入配对码：`{code}`',
    catalogTitle: '可用连接目录',
    noActiveConnections: '未找到活动连接。\n\n• 连接集成：`/connect <目标>`\n• 查看可用目录：`/connections catalog`',
    usageConnect: '**Connect 命令用法：**\n`/connect <目标> [凭据]`\n\n**示例：**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /path/to/vault`\n\n使用 `/connections catalog` 查看所有可用目标。',
    usageDisconnect: '用法：`/disconnect <目标>`\n示例：`/disconnect stripe`',
    handshakeInProgress: '此目标已有连接握手正在进行中。',
    pathVerificationFailed: '❌ **{target}** 的路径验证失败：{details}',
    apiKeyVerificationFailed: '❌ **{target}** 的密钥验证失败：{details}',
    oauthClickLink: '🔗 **连接 {target}：**\n点击下方链接授权 Zavorth：\n[授权 {target}]({url})',
    oauthEnded: '⚠️ **{target}** 的 OAuth 授权已结束：{details}',
    activeConnectionsHeader: '**你的活动连接（{count}）：**',
    catalogEmpty: '当前连接目录中没有可用目标。',
    statusHeader: '**连接健康状态：**',
    statusEmpty: '没有可报告状态的活动连接。',
    guidanceLabel: '💡 **指引：**',
    reconnectHint: '• 重新连接或更新凭据：`/connect {target} <新凭据>`',
    disconnectHint: '• 断开连接：`/disconnect {target}`',
    localPathVerifiedSuffix: '本地目录已验证：`{path}`',
    credentialsVaultSuffix: '凭据已加密并安全存储在保管库中。',
    secretStoreFailed: '❌ **{target}** 的加密凭据存储失败：{details}',
    deviceCodeFlowInstructions: '🔑 **连接 {target}（设备码流程）：**\n1. 打开授权链接：{url}\n2. 在浏览器中确认授权。\n3. Zavorth 将自动完成握手。',
    missingDeviceVerificationUrl: '缺少设备验证 URL',
    oauthConnectedSuccess: '✅ 已通过 OAuth2 成功连接到 **{target}**！',
    oauthExchangeFailed: '❌ **{target}** 的 OAuth 令牌交换失败：{details}',
    oauthListenerFailed: '⚠️ OAuth 回调监听器启动失败：{details}',
    oauthConfigActive: '**{target}** 的 OAuth 配置已生效。',
    catalogConnectHint: '要连接任意目标，请输入：`/connect <目标>`',
    statusLabel: '状态',
    healthLabel: '健康度',
    authLabel: '认证',
    connectedAtLabel: '连接时间',
    disconnectServiceHint: '• 断开服务：`/disconnect <目标>`',
  },
};
