import { CapabilityDefinition } from '../contracts/CapabilityContract.js';

export const BUILTIN_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'executor-codex',
    label: 'Codex CLI',
    type: 'executor',
    description: 'Executa tarefas locais de codigo pelo Codex.',
    intent: 'code_execution',
    executor_preference: 'codex',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Codex.',
    routing_confidence: 1,
    command: {
      command: 'codex',
      description: 'Executa tarefa local de codigo.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'codex',
    },
  },
  {
    id: 'executor.external',
    label: 'External Code Executor',
    type: 'executor',
    description: 'Executa tarefas de codigo e revisao via executor externo governado.',
    intent: 'code_execution',
    executor_preference: 'external_executor',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para executor externo governado.',
    routing_confidence: 1,
    command: {
      command: 'external',
      aliases: ['ext'],
      description: 'Delega tarefa ao executor externo governado.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'external_executor',
    },
  },
  {
    id: 'executor-zavorthBridge',
    label: 'ZavorthBridge',
    type: 'executor',
    description: 'Executa tarefas via ZavorthBridge.',
    intent: 'plan_execution',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Comando explicito do ZavorthBridge.',
    routing_confidence: 1,
    command: {
      command: 'ag',
      aliases: ['aga'],
      description: 'Executa tarefa via ZavorthBridge.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'zavorthBridge',
    },
  },
  {
    id: 'executor-zavorthBridge',
    label: 'Zavorth Bridge',
    type: 'executor',
    description: 'Alias explicito para o fluxo do ZavorthBridge.',
    intent: 'plan_execution',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Comando explicito do ZavorthBridge/bridge.',
    routing_confidence: 1,
    command: {
      command: 'bridge',
      description: 'Alias de compatibilidade para ZavorthBridge.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: 'zavorthBridge',
    },
  },
  {
    id: 'executor-gemini-cli',
    label: 'Gemini CLI',
    type: 'executor',
    description: 'Executa tarefas via Gemini CLI.',
    intent: 'code_execution',
    executor_preference: 'gemini_cli',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Gemini CLI.',
    routing_confidence: 1,
    command: {
      command: 'gemini',
      aliases: ['gcli', 'geminicli', 'codeassist', 'gca'],
      description: 'Executa tarefa via Gemini CLI.',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'gemini_cli',
    },
  },
  {
    id: 'executor-aistudio',
    label: 'Google AI Studio',
    type: 'executor',
    description: 'Executa tarefas via Google AI Studio.',
    intent: 'research_and_generation',
    executor_preference: 'aistudio',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Google AI Studio.',
    routing_confidence: 1,
    command: {
      command: 'aistudio',
      aliases: ['gaistudio', 'gstudio', 'ais'],
      description: 'Executa tarefa via Google AI Studio com modelo e tools configuraveis.',
      usage: 'model=<modelo> [tools=search,code] <tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'aistudio',
    },
  },
  {
    id: 'executor-jules',
    label: 'Jules',
    type: 'executor',
    description: 'Executa tarefas via Jules.',
    intent: 'code_execution',
    executor_preference: 'jules',
    dispatch_mode: 'execution',
    requires_planning: true,
    routing_reason: 'Comando explicito do Jules.',
    routing_confidence: 1,
    command: {
      command: 'jules',
      description: 'Delega tarefa ao Jules (Google AI Agent).',
      usage: '<tarefa>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'jules',
    },
  },
  {
    id: 'executor-stitch',
    label: 'Google Stitch',
    type: 'executor',
    description: 'Gera UI/app via Google Stitch.',
    intent: 'design_generation',
    executor_preference: 'stitch',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito do Google Stitch.',
    routing_confidence: 1,
    command: {
      command: 'stitch',
      aliases: ['stich'],
      description: 'Gera app/UI no Google Stitch e entrega screenshot + HTML.',
      usage: '<briefing do app>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: 'stitch',
    },
  },
  {
    id: 'command-research',
    label: 'Pesquisa',
    type: 'research',
    description: 'Enfileira uma pesquisa web estruturada com notificacao ao terminar.',
    intent: 'research',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito de pesquisa web.',
    routing_confidence: 1,
    command: {
      command: 'research',
      description: 'Pesquisa um tema na web.',
      usage: '<tema>',
      section: 'search',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'research_queue',
      handler_config: {
        mode: 'research',
      },
    },
  },
  {
    id: 'command-deepresearch',
    label: 'Deep Research',
    type: 'research',
    description: 'Enfileira uma pesquisa profunda multi-etapa.',
    intent: 'deep_research',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito de pesquisa profunda.',
    routing_confidence: 1,
    command: {
      command: 'deepresearch',
      description: 'Pesquisa profunda multi-etapa.',
      usage: '<tema>',
      section: 'search',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'research_queue',
      handler_config: {
        mode: 'deepresearch',
      },
    },
  },
  {
    id: 'command.external-review',
    label: 'External Review',
    type: 'workflow',
    description: 'Roda o pipeline maker+reviewer por executor externo governado.',
    intent: 'workflow_execution',
    executor_preference: 'workflow:review',
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para o workflow review.',
    routing_confidence: 1,
    command: {
      command: 'external_review',
      aliases: ['external-review'],
      description: 'Pipeline maker+reviewer por executor externo governado.',
      usage: '<objetivo>',
      section: 'execution',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: 'workflow:review',
      handler_action: 'workflow_named',
      handler_config: {
        workflow: 'review',
      },
    },
  },
  {
    id: 'command-workflow',
    label: 'Workflow',
    type: 'workflow',
    description: 'Executa workflows compostos entre executores.',
    intent: 'workflow_execution',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para um workflow composto.',
    routing_confidence: 1,
    command: {
      command: 'workflow',
      description: 'Workflow composto entre executores.',
      usage: '<review|ship|research|sdd> <objetivo|feature-id>',
      section: 'execution',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'workflow_dynamic',
    },
  },
  {
    id: 'command-file-delivery',
    label: 'Entrega de arquivo',
    type: 'integration',
    description: 'Procura e envia um arquivo local.',
    intent: 'file_delivery',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para localizar e enviar arquivo.',
    routing_confidence: 1,
    command: {
      command: 'arquivo',
      aliases: ['file', 'sendfile'],
      description: 'Procura e envia um arquivo local.',
      usage: '<pedido|caminho>',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'file_delivery',
    },
  },
  {
    id: 'command-task-files',
    label: 'Arquivos da tarefa',
    type: 'integration',
    description: 'Mostra arquivos de uma tarefa ou faz inspecao natural de arquivos.',
    intent: 'file_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito de inspecao de arquivos.',
    routing_confidence: 1,
    command: {
      command: 'files',
      description: 'Mostra arquivos de uma tarefa.',
      usage: '[task_id|pedido natural]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_files',
    },
  },
  {
    id: 'command-task-diff',
    label: 'Diff da tarefa',
    type: 'integration',
    description: 'Mostra o diff de uma tarefa.',
    intent: 'file_diff',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para ver diff da tarefa.',
    routing_confidence: 1,
    command: {
      command: 'diff',
      description: 'Mostra diff de uma tarefa.',
      usage: '[task_id]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_diff',
    },
  },
  {
    id: 'command-tasks',
    label: 'Tasks',
    type: 'integration',
    description: 'Mostra a central de tarefas recentes.',
    intent: 'task_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito de inspecao de tarefas.',
    routing_confidence: 1,
    command: {
      command: 'tasks',
      description: 'Lista tarefas recentes.',
      usage: '[active|approval|failed|completed|N]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_tasks',
    },
  },
  {
    id: 'command-logs',
    label: 'Logs',
    type: 'integration',
    description: 'Mostra logs recentes do runtime.',
    intent: 'log_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito de inspecao de logs.',
    routing_confidence: 1,
    command: {
      command: 'logs',
      description: 'Mostra logs recentes.',
      usage: '[quantidade]',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'inspection_logs',
    },
  },
  {
    id: 'command-capabilities',
    label: 'Capabilities',
    type: 'integration',
    description: 'Lista capabilities e plugins carregados.',
    intent: 'capability_inspection',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para ver capabilities carregadas.',
    routing_confidence: 1,
    command: {
      command: 'capabilities',
      description: 'Lista capabilities e plugins carregados.',
      section: 'monitoring',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'ops_capabilities',
    },
  },
  {
    id: 'command-dashboard',
    label: 'Dashboard',
    type: 'integration',
    description: 'Abre o painel web do Zavorth.',
    intent: 'dashboard_access',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para abrir o dashboard.',
    routing_confidence: 1,
    command: {
      command: 'dashboard',
      aliases: ['app', 'miniapp'],
      description: 'Abre o painel web do Zavorth.',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'ops_dashboard',
    },
  },
  {
    id: 'route-sandbox-lifecycle-auto',
    label: 'Sandbox Lifecycle',
    type: 'automation',
    description: 'Routes natural requests to start, use, inspect, or clean up Docker, gVisor, and Firecracker through the governed sandbox lifecycle manager.',
    intent: 'sandbox_lifecycle',
    executor_preference: 'sandbox_lifecycle',
    dispatch_mode: 'planning',
    workspace_hint: 'sandbox',
    requires_planning: true,
    routing_reason: 'The request mentions Docker, gVisor, Firecracker, sandbox lifecycle, or cleanup of isolated runtime resources.',
    routing_confidence: 0.92,
    priority: 94,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'sandbox',
      aliases: ['docker', 'gvisor', 'firecracker'],
      description: 'Plan governed sandbox lifecycle actions from natural language.',
      usage: '<request>',
      section: 'execution',
      privateMenu: false,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'sandbox_lifecycle_plan',
    },
    matchers: [
      {
        patterns: [
          '\\b(docker|gvisor|runsc|firecracker|microvm|sandbox)\\b',
          '\\b(ligue|liga|suba|start|inicie|derrube|desligue|mate|cleanup|use|usar)\\b.*\\b(docker|gvisor|firecracker|sandbox)\\b',
        ],
      },
    ],
    policy: {
      executor: 'ZavorthSandboxLifecycleManager',
      requiresApproval: true,
      dangerLevel: 'medium',
      networkScope: 'none',
      lifecycle: 'session',
      artifactKinds: ['sandbox-lifecycle-plan', 'sandbox-receipt'],
    },
  },
  {
    id: 'route-web-research',
    label: 'Pesquisa web estruturada',
    type: 'research',
    description: 'Usa a rota web estruturada do Zavorth para pesquisas basicas.',
    intent: 'web_research',
    executor_preference: 'web_research',
    dispatch_mode: 'execution',
    workspace_hint: 'web',
    requires_planning: false,
    routing_reason: 'Pedido tem perfil claro de pesquisa web basica e deve usar a rota web estruturada do Zavorth.',
    routing_confidence: 0.93,
    priority: 93,
    allowed_command_types: ['/task', '/auto'],
    matchers: [
      {
        patterns: [
          '\\b(pesquise|pesquisa|pesquisar|busque|buscar|procure|procurar|resuma)\\b.*\\b(web|internet|online|google|na web)\\b',
          '\\b(noticias|noticia|news)\\b.*\\b(hoje|do dia|na web|online|internet)\\b',
          '\\b(na web|na internet|online)\\b',
        ],
      },
    ],
  },
  {
    id: 'route-stitch-auto',
    label: 'Geracao de interface',
    type: 'executor',
    description: 'Auto-roteia pedidos de UI/layout para Google Stitch.',
    intent: 'design_generation',
    executor_preference: 'stitch',
    dispatch_mode: 'execution',
    workspace_hint: 'AUTO',
    requires_planning: false,
    routing_reason: 'Pedido tem cara de geracao de interface ou layout.',
    routing_confidence: 0.88,
    priority: 88,
    allowed_command_types: ['/task', '/auto'],
    matchers: [
      {
        patterns: [
          '\\b(crie|criar|gere|gerar|monte|montar|projete|desenhe|redesenhe)\\b.*\\b(landing|landing page|dashboard|ui|ux|interface|tela|layout|wireframe|mockup|pagina|pagina web|site|hero|cta|app mobile|mobile app)\\b',
          '\\b(landing page|wireframe|mockup|hero section|design system)\\b',
        ],
      },
    ],
  },
  {
    id: 'route-zavorth-bridge-auto',
    label: 'Automacao de interface',
    type: 'automation',
    description: 'Auto-roteia automacao de janelas/apps para ZavorthBridge.',
    intent: 'autonomous_interface_task',
    executor_preference: 'zavorthBridge',
    dispatch_mode: 'execution',
    workspace_hint: 'AUTO',
    requires_planning: false,
    routing_reason: 'Pedido menciona navegacao ou manipulacao de interface/app.',
    routing_confidence: 0.86,
    priority: 86,
    allowed_command_types: ['/auto'],
    matchers: [
      {
        patterns: [
          '\\b(abra|abrir|navegue|navegar|clique|clicar|janela|ide|app|aplicativo|navegador|tela|interface grafica|agent manager)\\b',
          '\\b(zavorthBridge|vscode|visual studio code)\\b',
        ],
        require_all_keywords: false,
      },
    ],
  },
  {
    id: 'route-external-code-review',
    label: 'Investigacao de codigo',
    type: 'executor',
    description: 'Auto-roteia investigacao ampla de codigo para executor externo governado.',
    intent: 'code_execution',
    executor_preference: 'external_executor',
    dispatch_mode: 'execution',
    workspace_hint: 'AUTO',
    requires_planning: false,
    routing_reason: 'Pedido parece investigacao ou revisao ampla de codigo.',
    routing_confidence: 0.82,
    priority: 82,
    allowed_command_types: ['/task', '/auto'],
    matchers: [
      {
        patterns: [
          '\\b(review|revise|revisar|audite|auditar|investigue|investigar|diagnostique|diagnosticar|vasculhe|inspecione|analise o codigo|analise o projeto)\\b',
          '\\b(encontre|encontrar|descubra|descobrir)\\b.*\\b(bug|erro|falha|problema)\\b',
        ],
        keywords: [
          'codigo',
          'codebase',
          'repo',
          'repositorio',
          'projeto',
          'workspace',
          'arquivo',
          'typescript',
          'javascript',
          'html',
          'css',
          'json',
          'api',
        ],
      },
    ],
  },
  {
    id: 'route-codex-auto',
    label: 'Edicao direcionada de codigo',
    type: 'executor',
    description: 'Auto-roteia alteracoes direcionadas de codigo para Codex.',
    intent: 'code_execution',
    executor_preference: 'codex',
    dispatch_mode: 'execution',
    workspace_hint: 'AUTO',
    requires_planning: false,
    routing_reason: 'Pedido parece alteracao direcionada de codigo ou arquivo.',
    routing_confidence: 0.78,
    priority: 78,
    allowed_command_types: ['/task', '/auto'],
    matchers: [
      {
        patterns: [
          '\\b(corrija|corrigir|corrige|fix|implemente|implementar|adicione|adicionar|refatore|refatorar|edite|editar|altere|alterar|ajuste|ajustar|mude|mudar)\\b',
          '\\b[a-z0-9_./\\\\-]+\\.(ts|tsx|js|jsx|mjs|cjs|html|css|json|md|py|java|kt|go|rs|sql|yml|yaml)\\b',
        ],
        keywords: [
          'codigo',
          'repo',
          'repositorio',
          'projeto',
          'workspace',
          'arquivo',
          'funcao',
          'bug',
          'teste',
          'typescript',
          'javascript',
          'html',
          'css',
          'json',
          'markdown',
          'sql',
          'api',
        ],
      },
    ],
  },
  {
    id: 'command-mcp',
    label: 'MCP Servers',
    type: 'integration',
    description: 'Gerencia servidores MCP: instalar, remover, listar e verificar status.',
    intent: 'mcp_management',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Comando explicito para gerenciamento de servidores MCP.',
    routing_confidence: 1,
    command: {
      command: 'mcp',
      description: 'Gerencia servidores MCP (install, remove, status, enable, disable).',
      usage: '<install|remove|status|enable|disable> [id] [command] [args...]',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'mcp_management',
    },
  },

  // =========================================================================
  // Zavorth-Native Capabilities (Track 1+)
  // Ref: docs/product-direction.md
  // =========================================================================

  {
    id: 'media.generate',
    label: 'Geração de Mídia',
    type: 'integration',
    description: 'Gera imagens, vídeos ou áudio a partir de prompt textual. Saída é sempre um ZavorthArtifact.',
    intent: 'media_generation',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve geração de mídia visual ou sonora.',
    routing_confidence: 0.90,
    priority: 90,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'imagine',
      aliases: ['img', 'gerar_imagem', 'generate_image'],
      description: 'Gera imagens a partir de um prompt textual.',
      usage: '<prompt descritivo>',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'media_generate',
    },
    matchers: [
      {
        patterns: [
          '\\b(gere|gerar|crie|criar|faca|fazer|produza|produzir|desenhe|desenhar)\\b.*\\b(imagem|imagens|foto|fotos|ilustracao|ilustracoes|arte|artwork|picture|image|icon|icone|banner|thumbnail|wallpaper)\\b',
          '\\b(imagem|foto|ilustracao|arte|picture|image)\\b.*\\b(de|do|da|com|sobre|mostrando|showing)\\b',
          '\\b(imagine|visualize|render|renderize)\\b',
        ],
        keywords: [
          'imagem',
          'foto',
          'ilustracao',
          'arte',
          'picture',
          'image',
          'gerar',
          'generate',
          'criar',
          'imagine',
        ],
      },
    ],
    policy: {
      executor: 'media.generate',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['image', 'video', 'audio'],
    },
  },

  {
    id: 'search.query',
    label: 'Busca Web Unificada',
    type: 'research',
    description: 'Busca web unificada com modos rápido, profundo e grounded. Retorna resultados com quality gate e ranking de evidência.',
    intent: 'web_search',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve pesquisa, busca ou consulta na web.',
    routing_confidence: 0.92,
    priority: 92,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'search',
      aliases: ['busca', 'pesquisa', 'web_search'],
      description: 'Busca web unificada com ranking de evidência.',
      usage: '<consulta> [mode=quick|deep|grounded]',
      section: 'search',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'search_query',
    },
    matchers: [
      {
        patterns: [
          '\\b(pesquise|pesquisa|pesquisar|busque|buscar|procure|procurar|search|find)\\b.*\\b(web|internet|online|google|na web)\\b',
          '\\b(noticias|noticia|news)\\b.*\\b(hoje|do dia|na web|online|internet|recentes|ultimas)\\b',
          '\\b(na web|na internet|online)\\b',
          '\\b(cotacao|preco|valor|dolar|euro|bitcoin)\\b.*\\b(hoje|atual|agora)\\b',
        ],
        keywords: [
          'pesquisar',
          'buscar',
          'procurar',
          'search',
          'web',
          'internet',
          'noticias',
          'news',
          'cotacao',
        ],
      },
    ],
    policy: {
      executor: 'search.query',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['search-result'],
    },
  },

  {
    id: 'media.understand',
    label: 'Análise de Mídia',
    type: 'integration',
    description: 'Analisa imagens, áudio e vídeo: descreve, extrai texto (OCR), classifica e responde perguntas sobre o conteúdo.',
    intent: 'media_understanding',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve análise, descrição ou compreensão de mídia recebida.',
    routing_confidence: 0.88,
    priority: 88,
    allowed_command_types: ['/task', '/auto'],
    command: {
      command: 'analyze',
      aliases: ['analisar', 'analise', 'descrever', 'ocr', 'analyze_media'],
      description: 'Analisa mídia (imagem, áudio, vídeo) com IA.',
      usage: '<caminho do arquivo> [type=describe|extract|classify|qa] [prompt]',
      section: 'execution',
      privateMenu: true,
      groupMenu: true,
      explicit_executor: null,
      handler_action: 'media_understand',
    },
    matchers: [
      {
        patterns: [
          '\\b(analise|analisar|descreva|descrever|identifique|identificar|leia|ler)\\b.*\\b(imagem|foto|imagens|fotos|screenshot|print|captura|tela|audio|video|midia)\\b',
          '\\b(o que|que|quem|qual|como)\\b.*\\b(tem|esta|aparece|mostra|diz|fala)\\b.*\\b(imagem|foto|audio|video|arquivo|midia)\\b',
          '\\b(ocr|transcrever|transcreva|extrair texto|extraia texto)\\b',
          '\\b(essa|esta|nessa|nesta)\\b.*\\b(imagem|foto|figura|screenshot|print)\\b',
        ],
        keywords: [
          'analisar',
          'descrever',
          'ocr',
          'transcrever',
          'identificar',
          'imagem',
          'foto',
          'screenshot',
          'audio',
          'video',
          'midia',
        ],
      },
    ],
    policy: {
      executor: 'media.understand',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'external-policy',
      lifecycle: 'stateless',
      artifactKinds: ['analysis-result'],
    },
  },

  {
    id: 'satellite.connect',
    label: 'Zavorth Satellite',
    type: 'integration',
    description: 'Gerencia conexões do Zavorth Satellite PWA via Node Mesh WebSocket.',
    intent: 'satellite_management',
    executor_preference: null,
    dispatch_mode: 'execution',
    requires_planning: false,
    routing_reason: 'Pedido envolve gerenciamento do Satellite ou acesso remoto via PWA.',
    routing_confidence: 0.85,
    priority: 80,
    command: {
      command: 'satellite',
      aliases: ['sat', 'pwa'],
      description: 'Gerencia o Zavorth Satellite PWA (status, sessões ativas, URL).',
      usage: '[status|sessions|url]',
      section: 'monitoring',
      privateMenu: true,
      groupMenu: false,
      explicit_executor: null,
      handler_action: 'satellite_connect',
    },
    policy: {
      executor: 'satellite.connect',
      requiresApproval: false,
      dangerLevel: null,
      networkScope: 'local',
      lifecycle: 'session',
      artifactKinds: [],
    },
  },
];
