export { BUILTIN_CAPABILITIES } from './definitions/index.js';
export { EXECUTOR_CAPABILITIES, RESEARCH_CAPABILITIES, WORKFLOW_CAPABILITIES, INTEGRATION_CAPABILITIES, AUTOMATION_CAPABILITIES } from './definitions/index.js';
