import { buildZavorthControlZavorthControlViewModel } from '../../../src/ai-gateway/app/(zavorthControl)/control/zavorth-control/adapters/zavorthControlZavorthControlAdapter.js';

describe('ZavorthControl Run Observatory Run Observatory', () => {
  it('keeps Run Observatory receipts, timeline, replay and health in the zavorthControl contract', () => {
    const viewModel = buildZavorthControlZavorthControlViewModel({
      runtime: {
        status: 'ready',
      },
      wsStatus: 'connected',
      runObservatory: {
        contractVersion: '2026-05-03.run-observatory',
        generatedAt: '2026-05-03T19:20:00.000Z',
        query: {
          status: 'failed',
          limit: 50,
        },
        totalRuns: 2,
        matchedRuns: 1,
        summary: {
          totalRuns: 2,
          matchedRuns: 1,
          eventCount: 4,
          artifactCount: 1,
          approvalCount: 1,
          pendingApprovalCount: 1,
          memorySignalCount: 1,
          receiptCount: 6,
          replayableRunCount: 2,
          failedRunCount: 1,
          waitingApprovalRunCount: 1,
          runningRunCount: 0,
        },
        health: {
          status: 'degraded',
          issues: ['1 run falhou.'],
          nextSafeAction: 'Abrir /zavorthControl?status=failed.',
          receiptsAvailable: true,
          replayAvailable: true,
          staleRunCount: 0,
        },
        indexes: {
          runIds: ['run-failed'],
          traceIds: ['trace-failed'],
          sessionIds: ['session-failed'],
          statuses: [{ status: 'failed', count: 1 }],
        },
        runSummaries: [
          {
            id: 'run-failed',
            traceId: 'trace-failed',
            requestId: 'request-failed',
            sessionId: 'session-failed',
            title: 'Run falha',
            status: 'failed',
            channel: 'cli',
            providerLabel: 'OpenAI',
            modelLabel: 'gpt-5.2',
            eventCount: 2,
            artifactCount: 0,
            approvalCount: 0,
            pendingApprovalCount: 0,
            memorySignalCount: 0,
            receiptCount: 2,
            replayable: true,
            hasError: true,
            firstEventAt: '2026-05-03T19:19:00.000Z',
            lastEventAt: '2026-05-03T19:20:00.000Z',
          },
        ],
        runs: [
          {
            run: {
              id: 'run-failed',
              traceId: 'trace-failed',
              requestId: 'request-failed',
              sessionId: 'session-failed',
              title: 'Run falha',
              status: 'failed',
              summary: 'Falhou de forma observavel.',
              updatedAt: '2026-05-03T19:20:00.000Z',
              modelProfile: {
                providerLabel: 'OpenAI',
                modelLabel: 'gpt-5.2',
              },
              events: [{ id: 'event-failed' }],
              artifacts: [],
              approvals: [],
            },
            matchedBy: ['status'],
          },
        ],
        receipts: [
          {
            id: 'receipt:event-failed',
            runId: 'run-failed',
            traceId: 'trace-failed',
            sessionId: 'session-failed',
            kind: 'error',
            source: 'agent.error',
            title: 'Executor falhou',
            detail: 'Falha controlada.',
            status: 'failed',
            createdAt: '2026-05-03T19:20:00.000Z',
          },
        ],
        diffPreviews: [
          {
            id: 'diff-preview:receipt:event-diff',
            runId: 'run-failed',
            traceId: 'trace-failed',
            sessionId: 'session-failed',
            receiptId: 'receipt:event-diff',
            planId: 'plan-zavorthControl-diff',
            title: 'Previa de alteracao',
            status: 'pending',
            approvalRequired: true,
            applied: false,
            summary: '1 arquivo, 1 hunk, Risk 3 reversivel.',
            text: 'Previa de alteracao\nResumo: 1 arquivo, 1 hunk.',
            files: [
              {
                path: 'notes/zavorthControl.txt',
                operation: 'patch',
                status: 'passed',
                hunkCount: 1,
              },
            ],
            actions: {
              approveApplyLabel: 'Aprovar/aplicar',
              approveApplyInstruction: 'Peça ao Zavorth: aplicar rascunho plan-zavorthControl-diff.',
              rollbackLabel: 'Rollback sera gerado no apply',
              rollbackInstruction: 'Depois do apply, o receipt vai apontar o artifact de rollback reversivel.',
              rollbackArtifactPath: null,
              zavorthControlPath: '/zavorthControl?runId=run-failed',
            },
          },
        ],
        intelligenceFabricHealth: {
          contractVersion: 'zavorth-intelligence-fabric-post-default-health/v1',
          generatedAt: '2026-05-03T19:20:00.000Z',
          status: 'attention',
          recommendation: 'observe',
          summary: {
            runs: 2,
            fabricRuns: 1,
            observedRuns: 1,
            disabledRuns: 0,
            fallbackCurrentRuntimeRuns: 0,
            errorFallbackRuns: 0,
            orientedRuns: 1,
            fallbackRate: 0,
            errorFallbackRate: 0,
            disabledRate: 0,
            orientationRate: 1,
            averageLatencyMs: 42,
            p95LatencyMs: 42,
          },
          thresholds: {
            minRuns: 3,
            maxFallbackRate: 0.25,
            maxErrorFallbackRate: 0.05,
            maxDisabledRate: 0.4,
            maxAverageLatencyMs: 250,
            maxP95LatencyMs: 600,
          },
          surfaces: [
            {
              surface: 'web',
              runs: 1,
              observed: 1,
              disabled: 0,
              fallbackCurrentRuntime: 0,
              errorFallback: 0,
              oriented: 1,
              averageLatencyMs: 42,
            },
          ],
          findings: [
            {
              id: 'insufficient-sample',
              severity: 'warning',
              message: 'Only 1 Fabric run(s) observed; minimum is 3.',
            },
          ],
          rollback: {
            available: true,
            demoteMode: 'disabled',
            instruction: 'Set intelligenceFabricMode=disabled at runtime or request metadata.',
            destructive: false,
          },
          receipts: ['intelligence-fabric-post-default-health'],
        },
        llmTelemetry: {
          contractVersion: 'llm-runtime-telemetry/v1',
          generatedAt: '2026-05-03T19:20:00.000Z',
          summary: {
            totalAttempts: 3,
            succeeded: 2,
            failed: 1,
            skippedUnavailable: 0,
            fallbackAttempts: 1,
            fallbackRate: 0.3333,
            averageLatencyMs: 120,
            p95LatencyMs: 250,
            providerCount: 2,
            surfaceCount: 1,
          },
          providers: [
            {
              providerName: 'openrouter',
              attempts: 2,
              succeeded: 1,
              failed: 1,
              skippedUnavailable: 0,
              fallbackAttempts: 0,
              averageLatencyMs: 150,
              p95LatencyMs: 250,
              lastStatus: 'failed',
              lastError: 'primary failed',
              lastAttemptAt: '2026-05-03T19:20:00.000Z',
              models: ['model-a'],
            },
            {
              providerName: 'openai',
              attempts: 1,
              succeeded: 1,
              failed: 0,
              skippedUnavailable: 0,
              fallbackAttempts: 1,
              averageLatencyMs: 60,
              p95LatencyMs: 60,
              lastStatus: 'succeeded',
              lastAttemptAt: '2026-05-03T19:20:01.000Z',
              models: ['model-b'],
            },
          ],
          surfaces: [
            {
              surface: 'echo',
              attempts: 3,
              fallbackAttempts: 1,
              fallbackRate: 0.3333,
              averageLatencyMs: 120,
              p95LatencyMs: 250,
            },
          ],
          recentAttempts: [
            {
              id: 'llm-attempt:1',
              recordedAt: '2026-05-03T19:20:01.000Z',
              runId: 'run-failed',
              traceId: 'trace-failed',
              sessionId: 'session-failed',
              surface: 'echo',
              requestedProviderName: 'openrouter',
              primaryProviderName: 'openrouter',
              providerName: 'openai',
              modelName: 'model-b',
              status: 'succeeded',
              fallback: true,
              fallbackAllowed: true,
              durationMs: 60,
            },
          ],
          receipts: ['llm-runtime-telemetry:sanitized:no-prompts'],
        },
        timeline: [
          {
            id: 'timeline:receipt:event-failed',
            runId: 'run-failed',
            traceId: 'trace-failed',
            sessionId: 'session-failed',
            kind: 'error',
            title: 'Executor falhou',
            status: 'failed',
            createdAt: '2026-05-03T19:20:00.000Z',
            relativeOrder: 1,
            receiptId: 'receipt:event-failed',
          },
        ],
        replay: {
          available: true,
          runCount: 1,
          eventCount: 2,
          artifactCount: 0,
          receiptCount: 1,
          anchors: [],
          commandHints: ['zavorth observatory status failed --json'],
          summary: '1 run com receipts prontos para replay.',
        },
        surface: {
          zavorthControlPath: '/zavorthControl?status=failed',
          cliCommand: 'zavorth observatory --json',
          filterHints: ['status'],
        },
      },
    });

    expect(viewModel.runObservatory).toEqual(expect.objectContaining({
      diffPreviews: [
        expect.objectContaining({
          planId: 'plan-zavorthControl-diff',
          actions: expect.objectContaining({
            approveApplyLabel: 'Aprovar/aplicar',
          }),
        }),
      ],
      intelligenceFabricHealth: expect.objectContaining({
        status: 'attention',
        recommendation: 'observe',
        summary: expect.objectContaining({
          fabricRuns: 1,
          p95LatencyMs: 42,
        }),
        findings: [
          expect.objectContaining({
            id: 'insufficient-sample',
            severity: 'warning',
          }),
        ],
      }),
      extensions: expect.objectContaining({
        contractVersion: '2026-05-03.run-observatory',
        summary: expect.objectContaining({
          receiptCount: 6,
        }),
        health: expect.objectContaining({
          status: 'degraded',
          replayAvailable: true,
        }),
        receipts: [
          expect.objectContaining({
            kind: 'error',
            source: 'agent.error',
          }),
        ],
        timeline: [
          expect.objectContaining({
            receiptId: 'receipt:event-failed',
          }),
        ],
        replay: expect.objectContaining({
          available: true,
          commandHints: ['zavorth observatory status failed --json'],
        }),
        llmTelemetry: expect.objectContaining({
          summary: expect.objectContaining({
            totalAttempts: 3,
            fallbackAttempts: 1,
            p95LatencyMs: 250,
          }),
          providers: [
            expect.objectContaining({
              providerName: 'openrouter',
              lastStatus: 'failed',
            }),
            expect.objectContaining({
              providerName: 'openai',
              fallbackAttempts: 1,
            }),
          ],
        }),
        surface: expect.objectContaining({
          zavorthControlPath: '/zavorthControl?status=failed',
        }),
      }),
    }));
  });
});
