[package]
name = "zavorth-setup"
version = "0.1.0"
description = "Zavorth Setup"
authors = ["Zavorth"]
edition = "2021"

[lib]
name = "zavorth_setup_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tokio = { version = "1", features = ["process", "sync", "rt-multi-thread", "macros", "io-util", "time"] }
