/**
 * Environment Schema Validation — FASE-01 Security Hardening
 *
 * Validates critical environment variables at server boot using Zod.
 * Called from instrumentation-node.ts after secrets are auto-generated.
 *
 * @module lib/envSchema
 */

import { z } from "zod";

// ── Helpers ──

const booleanStringSchema = z
  .enum(["true", "false", "1", "0", "yes", "no", ""])
  .optional();

const portSchema = z.coerce
  .number()
  .int()
  .min(1)
  .max(65535)
  .optional();

// ── Main Schema ──

export const envSchema = z.object({
  // ─── Core Server ───
  PORT: portSchema,
  NODE_ENV: z.enum(["development", "production", "test"]).optional(),

  // ─── Authentication Secrets ───
  JWT_SECRET: z
    .string()
    .min(32, "JWT_SECRET must be at least 32 characters for HS256 security")
    .optional(), // auto-generated by ensureSecrets() if missing
  API_KEY_SECRET: z
    .string()
    .min(16, "API_KEY_SECRET must be at least 16 characters")
    .optional(), // auto-generated by ensureSecrets() if missing
  INITIAL_PASSWORD: z
    .string()
    .min(8, "INITIAL_PASSWORD must be at least 8 characters if set")
    .optional(),

  // ─── Auth Behavior ───
  AUTH_COOKIE_SECURE: booleanStringSchema,
  REQUIRE_API_KEY: booleanStringSchema,

  // ─── Security Modules ───
  INPUT_SANITIZER_ENABLED: booleanStringSchema,
  INPUT_SANITIZER_MODE: z
    .enum(["warn", "block", "redact"])
    .optional(),
  PII_REDACTION_ENABLED: booleanStringSchema,
  TOOL_POLICY_MODE: z
    .enum(["allowlist", "denylist", "disabled"])
    .optional(),

  // ─── Logging ───
  APP_LOG_LEVEL: z
    .enum(["debug", "info", "warn", "error", "silent"])
    .optional(),
  APP_LOG_FORMAT: z
    .enum(["text", "json"])
    .optional(),
});

// ── Types ──

export type EnvSchema = z.infer<typeof envSchema>;

export interface EnvValidationResult {
  valid: boolean;
  errors: Array<{ field: string; message: string }>;
}

// ── Core Functions ──

/**
 * Validate process.env against the schema.
 * Returns structured errors without terminating.
 */
export function validateEnvSchema(): EnvValidationResult {
  const result = envSchema.safeParse(process.env);

  if (result.success) {
    return { valid: true, errors: [] };
  }

  const errors = result.error.issues.map((issue) => ({
    field: issue.path.join(".") || "unknown",
    message: issue.message,
  }));

  return { valid: false, errors };
}

/**
 * Validate env and terminate the process on failure (fail-fast).
 * Should be called during server boot, after ensureSecrets().
 */
export function enforceEnvSchema(logger = console): void {
  const result = validateEnvSchema();

  if (result.valid) {
    logger.log("[STARTUP] Environment schema validation passed ✓");
    return;
  }

  logger.error("");
  logger.error("═══════════════════════════════════════════════════════════");
  logger.error("  ❌  SECURITY: Environment validation failed");
  logger.error("═══════════════════════════════════════════════════════════");

  for (const err of result.errors) {
    logger.error(`  • ${err.field}: ${err.message}`);
  }

  logger.error("");
  logger.error("  Fix your .env file or environment variables.");
  logger.error("  See .env.example for reference.");
  logger.error("═══════════════════════════════════════════════════════════");
  logger.error("");

  throw new Error(`Environment validation failed: ${result.errors.map((e) => `${e.field}: ${e.message}`).join(', ')}`);
}
