import { normalizeModelProfile } from './runtime-model-profile';

type RuntimeOperationsPanelsOptions = {
  collectToolExposures: () => any[];
  escapeHtml: (value: unknown) => string;
  eventCountMatching: (pattern: RegExp) => number;
  formatDate: (value: unknown) => string;
  formattedMoney: (value: unknown) => string;
  getCurrentModelLabel: () => string;
  getCurrentModelRouteLabel: () => string;
  getCurrentProviderLabel: () => string;
  getRuns: () => any[];
  getWorkflowJobs: () => any[];
  numberLabel: (value: unknown, fallback?: string) => string;
  pendingApprovalCount: () => number;
  resolveCurrentModelProfile: () => any;
  runArtifactCount: (run: any) => number;
  setLiveStripValue: (selector: string, value: unknown) => void;
  setTableBody: (sectionId: string, html: string) => void;
  setTableHeaders: (sectionId: string, labels: string[]) => void;
  state: any;
  statusBadge: (status: unknown, label: string) => string;
  sumRunNumbers: (paths: string[]) => number;
  text: (value: unknown, fallback?: string) => string;
  totalArtifactCount: () => number;
  updatePlatformAction: (sectionId: string, title: string, detail: string, prompt?: string) => void;
  updatePremiumMetric: (label: string, value: string, sub: string) => void;
  updatePremiumStatus: (label: string, value: string, tone?: string) => void;
  updateSummaryCard: (label: string, value: string, sub: string) => void;
};

export function createRuntimeOperationsPanels(options: RuntimeOperationsPanelsOptions) {
  function groupRunsByModel() {
    const groups = new Map();
    for (const run of options.getRuns()) {
      const profile = normalizeModelProfile(run?.modelProfile) || options.resolveCurrentModelProfile();
      const key = profile.modelLabel || 'current model';
      const current = groups.get(key) || {
        model: key,
        runs: 0,
        events: 0,
        artifacts: 0,
        status: 'Ready',
      };
      current.runs += 1;
      current.events += Array.isArray(run?.events) ? run.events.length : 0;
      current.artifacts += options.runArtifactCount(run);
      current.status = options.text(run?.status, current.status);
      groups.set(key, current);
    }
    return Array.from(groups.values());
  }

  function updateUsage() {
    const runs = options.getRuns();
    const models = groupRunsByModel();
    const tokenTotal = options.sumRunNumbers(['usage.totalTokens', 'usage.tokens', 'tokenUsage.totalTokens', 'tokens.total', 'tokensUsed', 'totalTokens']);
    const costTotal = options.sumRunNumbers(['usage.costUsd', 'costUsd', 'cost.usd', 'billing.costUsd']);
    const toolCalls = options.eventCountMatching(/tool|executor|command|mcp/i);
    const errors = options.eventCountMatching(/failed|error|blocked|rejected|cancelled|canceled/i);

    options.updatePremiumMetric('Tokens', options.numberLabel(tokenTotal), tokenTotal ? 'measured by runtime' : 'no measured usage');
    options.updatePremiumMetric('Cost', options.formattedMoney(costTotal), costTotal ? 'reported by provider' : 'waiting for provider proof');
    options.updatePremiumMetric('Calls', options.numberLabel(toolCalls), toolCalls ? 'tools used' : 'no tools executed');
    options.updatePremiumMetric('Errors', options.numberLabel(errors), errors ? 'review recent events' : 'no visible errors');
    options.updatePremiumStatus('Usage', options.state.zavorthControl?.live ? 'live' : 'local', options.state.zavorthControl?.live ? 'ok' : 'info');
    options.updatePremiumStatus('Costs', costTotal ? 'reported' : 'when reported', costTotal ? 'ok' : 'info');
    options.updatePremiumStatus('Secrets', 'redacted', 'ok');
    options.updatePremiumStatus('Export', options.totalArtifactCount() ? 'available' : 'manual', options.totalArtifactCount() ? 'ok' : 'info');
    options.updatePlatformAction('sector-usage', 'Active model', options.getCurrentModelRouteLabel());
    options.updatePlatformAction('sector-usage', 'Test route', errors ? `${options.numberLabel(errors)} event(s) to review` : 'Ready for a safe check.');
    options.updatePlatformAction('sector-usage', 'Recent usage', `${options.numberLabel(runs.length)} run(s), ${options.numberLabel(tokenTotal)} token(s)`);

    options.updateSummaryCard('Runs', options.numberLabel(runs.length), runs.length ? 'live executions registered' : 'no execution registered');
    options.updateSummaryCard('Current Model', options.getCurrentModelLabel(), options.getCurrentProviderLabel());
    options.updateSummaryCard('Artifacts', options.numberLabel(options.totalArtifactCount()), options.totalArtifactCount() ? 'generated by runtime' : 'no file generated in this session');
    options.updateSummaryCard('Approvals', options.numberLabel(options.pendingApprovalCount()), options.pendingApprovalCount() ? 'waiting for decision' : 'no pending approvals');

    options.setTableHeaders('sector-usage', ['Model', 'Runs', 'Events', 'Artifacts', 'Status']);
    if (models.length === 0) {
      options.setTableBody('sector-usage', `
        <tr>
          <td class="mono">${options.escapeHtml(options.getCurrentModelLabel())}</td>
          <td>0</td>
          <td>0</td>
          <td>0</td>
          <td>${options.statusBadge(options.state.zavorthControl?.authRequired ? 'auth' : 'ready', options.state.zavorthControl?.authRequired ? 'Protected' : 'Waiting run')}</td>
        </tr>
      `);
      return;
    }

    options.setTableBody('sector-usage', models.map((entry) => `
      <tr>
        <td class="mono">${options.escapeHtml(entry.model)}</td>
        <td>${options.numberLabel(entry.runs)}</td>
        <td>${options.numberLabel(entry.events)}</td>
        <td>${options.numberLabel(entry.artifacts)}</td>
        <td>${options.statusBadge(entry.status, options.text(entry.status, 'Ready'))}</td>
      </tr>
    `).join(''));
  }

  function updateCron() {
    const jobs = options.getWorkflowJobs();
    options.setTableHeaders('sector-cron', ['Job', 'Type', 'Attempts', 'Next', 'Updated', 'Status']);
    if (jobs.length === 0) {
      options.setTableBody('sector-cron', `
        <tr>
          <td class="mono">workflow queue</td>
          <td>local durable</td>
          <td>0</td>
          <td>---</td>
          <td>${options.formatDate(options.state.updatedAt)}</td>
          <td>${options.statusBadge(options.state.zavorthControl?.authRequired ? 'auth' : 'ready', options.state.zavorthControl?.authRequired ? 'Protected' : 'No live jobs')}</td>
        </tr>
      `);
      return;
    }

    options.setTableBody('sector-cron', jobs.slice(0, 8).map((job) => `
      <tr>
        <td class="mono">${options.escapeHtml(options.text(job.id || job.jobId || job.runId, 'job'))}</td>
        <td>${options.escapeHtml(options.text(job.type || job.kind, 'workflow'))}</td>
        <td>${options.numberLabel(job.attempts || job.attempt || 0)}</td>
        <td>${job.nextRunAt ? options.formatDate(job.nextRunAt) : '---'}</td>
        <td>${options.formatDate(job.updatedAt || job.createdAt)}</td>
        <td>${options.statusBadge(job.status, options.text(job.status, 'Ready'))}</td>
      </tr>
    `).join(''));
  }

  function extractCompanions() {
    const candidates = [
      options.state.companions?.snapshot?.companions,
      options.state.companions?.companions,
      options.state.gatewayRuntime?.snapshot?.companions,
      options.state.gatewayRuntime?.companions,
    ];
    for (const candidate of candidates) {
      if (Array.isArray(candidate)) return candidate;
    }
    return [];
  }

  function updateNodes() {
    const companions = extractCompanions();
    const tools = options.collectToolExposures();
    const haystack = [
      ...tools.map((tool) => `${tool.id} ${tool.title} ${tool.summary}`),
      ...companions.map((node) => `${node?.id || ''} ${node?.label || ''} ${node?.type || ''} ${node?.kind || ''} ${node?.summary || ''}`),
    ].join(' ').toLowerCase();
    const hasMnemos = /mnemos|memory|vault/.test(haystack);
    const hasSwarm = /swarm|worker|subagent/.test(haystack) || Boolean(options.state.zavorthControl?.snapshot?.swarmV2);
    const hasAcp = /\bacp\b|agent communication protocol/.test(haystack) || Boolean(options.state.zavorthControl?.snapshot?.acp);
    const backendCount = companions.length;
    options.setLiveStripValue('[data-memory-live-files]', hasMnemos ? 'ready' : options.state.zavorthControl?.authRequired ? 'protected' : 'configurable');
    options.setLiveStripValue('[data-memory-live-agents]', companions.length || (hasAcp ? 1 : 0));
    options.setLiveStripValue('[data-memory-live-env]', backendCount ? `${backendCount} visible` : 'approval gated');

    options.updatePremiumStatus('File memory', hasMnemos ? 'ready' : 'configurable', hasMnemos ? 'ok' : 'info');
    options.updatePremiumStatus('Parallel work', hasSwarm ? 'ready' : 'ready', 'ok');
    options.updatePremiumStatus('External links', companions.length || hasAcp ? `${companions.length || 1} profile` : 'consent required', companions.length || hasAcp ? 'ok' : 'info');
    options.updatePremiumStatus('Safe execution', backendCount ? `${backendCount} visible` : 'approval gated', backendCount ? 'ok' : 'warn');
    options.updatePlatformAction('sector-nodes', 'File memory', hasMnemos ? 'Memory tools are visible in the runtime.' : 'Memory scope is configurable.');
    options.updatePlatformAction('sector-nodes', 'Parallel work', hasSwarm ? 'Ready with cost limits and receipts.' : 'Active when a task asks for parallel work.');
    options.updatePlatformAction('sector-nodes', 'Connect agent', companions.length ? `${companions.length} consented profile(s).` : 'Only from a path you provide.');
    options.updatePlatformAction('sector-nodes', 'Execution environments', backendCount ? `${backendCount} visible backend signal(s).` : 'Shell, files, and remote actions require scope.');

    options.setTableHeaders('sector-nodes', ['Node', 'Type', 'Processes', 'Memory', 'Summary', 'Actions', 'Status']);
    if (companions.length === 0) {
      options.setTableBody('sector-nodes', `
        <tr>
          <td class="mono">companions</td>
          <td>Runtime</td>
          <td>0</td>
          <td>---</td>
          <td>${options.state.zavorthControl?.authRequired ? 'Unlock to read live nodes' : 'No live companion/node connected'}</td>
          <td>---</td>
          <td>${options.statusBadge(options.state.zavorthControl?.authRequired ? 'auth' : 'ready', options.state.zavorthControl?.authRequired ? 'Protected' : 'Waiting')}</td>
        </tr>
      `);
      return;
    }

    options.setTableBody('sector-nodes', companions.slice(0, 8).map((node) => {
      const actions = Array.isArray(node?.actions) ? node.actions.length : 0;
      return `
        <tr>
          <td class="mono">${options.escapeHtml(options.text(node.id, node.label))}</td>
          <td>${options.escapeHtml(options.text(node.type || node.kind || node.label, 'Companion'))}</td>
          <td>${options.numberLabel(node.processCount || node.processes || 0)}</td>
          <td>${node.workingSetMb ? `${options.numberLabel(node.workingSetMb)} MB` : '---'}</td>
          <td>${options.escapeHtml(options.text(node.summary || node.details, 'No summary published'))}</td>
          <td>${options.numberLabel(actions)}</td>
          <td>${options.statusBadge(node.status, options.text(node.status, 'Ready'))}</td>
        </tr>
      `;
    }).join(''));
  }

  return {
    updateCron,
    updateNodes,
    updateUsage,
  };
}
