type RuntimeArtifactUtilsOptions = {
  state: any;
  text: (value: unknown, fallback?: string) => string;
  readRunId: () => string;
  readSessionId: () => string;
};

export function basename(value: unknown) {
  return String(value || '').trim().replace(/\\/g, '/').split('/').filter(Boolean).pop() || '';
}

export function extensionOf(value: unknown) {
  const name = basename(value).toLowerCase();
  const dot = name.lastIndexOf('.');
  return dot >= 0 ? name.slice(dot + 1) : '';
}

export function createRuntimeArtifactUtils({
  state,
  text,
  readRunId,
  readSessionId,
}: RuntimeArtifactUtilsOptions) {
  function inferArtifactKind(entry: any) {
    const explicit = String(entry?.kind || entry?.type || '').trim().toLowerCase();
    if (explicit) return explicit;
    const extension = extensionOf(entry?.path || entry?.name || entry?.title);
    if (extension === 'pdf') return 'pdf';
    if (['png', 'jpg', 'jpeg', 'gif', 'webp'].includes(extension)) return 'image';
    if (['diff', 'patch'].includes(extension)) return 'diff';
    if (['md', 'txt', 'log', 'json', 'csv'].includes(extension)) return 'report';
    return 'file';
  }

  function normalizeArtifact(entry: any, defaults: any = {}) {
    const pathValue = String(entry?.path || entry?.filePath || defaults.path || '').trim();
    const name = String(entry?.name || entry?.title || basename(pathValue) || defaults.name || '').trim();
    const id = String(
      entry?.id
      || entry?.key
      || defaults.id
      || `${defaults.source || 'artifact'}:${defaults.toolRunId || defaults.runId || 'runtime'}:${pathValue || name}`,
    ).trim();
    if (!id) return null;
    return {
      id,
      source: String(entry?.source || defaults.source || 'runtime').trim(),
      kind: inferArtifactKind(entry),
      title: name || text(pathValue, id),
      name: name || null,
      path: pathValue || null,
      status: String(entry?.status || defaults.status || 'ready').trim(),
      summary: String(entry?.summary || entry?.description || defaults.summary || '').trim() || null,
      sessionId: String(entry?.sessionId || defaults.sessionId || '').trim() || null,
      runId: String(entry?.runId || defaults.runId || '').trim() || null,
      toolRunId: String(entry?.toolRunId || defaults.toolRunId || '').trim() || null,
      createdAt: entry?.createdAt || entry?.created_at || defaults.createdAt || null,
      content: entry?.content || entry?.output || entry?.body || null,
      diff: entry?.diff || defaults.diff || null,
      raw: entry,
    };
  }

  function extractArtifacts(payload: any) {
    const artifacts = [];
    const directArtifacts = [
      payload?.artifacts,
      payload?.artifactPlane?.artifacts,
      payload?.snapshot?.artifacts,
      payload?.session?.artifacts,
    ];
    for (const candidate of directArtifacts) {
      if (!Array.isArray(candidate)) continue;
      for (const entry of candidate) {
        const artifact = normalizeArtifact(entry, { sessionId: payload?.sessionId, source: entry?.source || 'runtime' });
        if (artifact) artifacts.push(artifact);
      }
    }

    const toolRuns = [
      payload?.toolRuns,
      payload?.snapshot?.toolRuns,
      payload?.session?.toolRuns,
    ];
    for (const candidate of toolRuns) {
      if (!Array.isArray(candidate)) continue;
      for (const run of candidate) {
        const toolRunId = String(run?.runId || run?.id || '').trim();
        const runArtifacts = Array.isArray(run?.artifacts) ? run.artifacts : [];
        for (const entry of runArtifacts) {
          const artifact = normalizeArtifact(entry, {
            source: 'tool-run',
            sessionId: payload?.sessionId,
            toolRunId,
            summary: entry?.summary || run?.summary,
          });
          if (artifact) artifacts.push(artifact);
        }
        const filesTouched = Array.isArray(run?.filesTouched) ? run.filesTouched : [];
        for (const pathValue of filesTouched) {
          const normalizedPath = String(pathValue || '').trim();
          const artifact = normalizeArtifact({
            id: `file:${toolRunId || 'session'}:${normalizedPath}`,
            kind: 'file',
            path: normalizedPath,
            title: basename(normalizedPath) || normalizedPath,
            summary: 'File touched by a live execution.',
          }, {
            source: 'file',
            sessionId: payload?.sessionId,
            toolRunId,
          });
          if (artifact) artifacts.push(artifact);
        }
        if (run?.diff && (Array.isArray(run.diff?.patches) || run.diff?.summary)) {
          const artifact = normalizeArtifact({
            id: `diff:${toolRunId || payload?.sessionId || 'session'}`,
            kind: 'diff',
            title: `Diff ${toolRunId || 'session'}`,
            summary: run.diff.summary || 'Changes generated by Zavorth.',
            diff: run.diff,
          }, {
            source: 'tool-run',
            sessionId: payload?.sessionId,
            toolRunId,
          });
          if (artifact) artifacts.push(artifact);
        }
      }
    }

    const runs = [
      payload?.snapshot?.runs,
      payload?.zavorthControl?.snapshot?.runs,
      state.zavorthControl?.snapshot?.runs,
    ];
    for (const candidate of runs) {
      if (!Array.isArray(candidate)) continue;
      for (const run of candidate) {
        const runArtifacts = Array.isArray(run?.artifacts) ? run.artifacts : [];
        for (const entry of runArtifacts) {
          const artifact = normalizeArtifact(entry, {
            source: 'agent-run',
            sessionId: entry?.sessionId || run?.sessionId,
            runId: run?.id,
            summary: entry?.summary || run?.summary,
          });
          if (artifact) artifacts.push(artifact);
        }
      }
    }

    return Array.from(new Map(artifacts.map((artifact) => [artifact.id, artifact])).values());
  }

  function hasDirectExecutionArtifactContext(payload: any) {
    if (!payload || typeof payload !== 'object') return false;
    if (String(payload.taskId || payload.runId || payload.approvalId || '').trim()) return true;
    if (Array.isArray(payload.artifacts) && payload.artifacts.length > 0) return true;
    if (Array.isArray(payload.artifactIds) && payload.artifactIds.length > 0) return true;
    return Boolean(payload.agentRun || payload.activeRun || payload.run);
  }

  function extractResponseDecision(payload: any) {
    const snapshot = payload?.snapshot || payload?.zavorthControl?.snapshot || state.zavorthControl?.snapshot || null;
    const candidates = [
      payload?.responseDecision,
      payload?.agentRun?.metadata?.responseDecision,
      payload?.activeRun?.metadata?.responseDecision,
      payload?.run?.metadata?.responseDecision,
      snapshot?.activeRun?.metadata?.responseDecision,
      snapshot?.agentRun?.metadata?.responseDecision,
      snapshot?.run?.metadata?.responseDecision,
    ];
    return candidates.find((candidate) => candidate && typeof candidate === 'object') || null;
  }

  function extractArtifactPolicy(payload: any) {
    const responseDecision = extractResponseDecision(payload);
    const snapshot = payload?.snapshot || payload?.zavorthControl?.snapshot || state.zavorthControl?.snapshot || null;
    const candidates = [
      payload?.artifactPolicy,
      responseDecision?.artifactPolicy,
      payload?.agentRun?.metadata?.artifactPolicy,
      payload?.activeRun?.metadata?.artifactPolicy,
      payload?.run?.metadata?.artifactPolicy,
      snapshot?.activeRun?.metadata?.artifactPolicy,
      snapshot?.agentRun?.metadata?.artifactPolicy,
      snapshot?.run?.metadata?.artifactPolicy,
    ];
    return candidates.find((candidate) => candidate && typeof candidate === 'object') || null;
  }

  function artifactPolicyAllowsChatDisplay(payload: any) {
    const policy = extractArtifactPolicy(payload);
    if (!policy) return true;
    return policy.shouldShowArtifactInChat === true;
  }

  function shouldDisplayArtifactsInChat(payload: any, options: any = {}) {
    if (options.display !== true) return false;
    if (!artifactPolicyAllowsChatDisplay(payload)) return false;
    return hasDirectExecutionArtifactContext(payload);
  }

  function normalizeDiffPreview(preview: any) {
    if (!preview || typeof preview !== 'object') return null;
    const planId = String(preview.planId || preview.plan_id || '').trim();
    const id = String(preview.id || planId || '').trim();
    if (!id) return null;
    const actions = preview.actions && typeof preview.actions === 'object' ? preview.actions : {};
    return {
      id,
      planId,
      runId: String(preview.runId || preview.run_id || readRunId() || '').trim(),
      sessionId: String(preview.sessionId || preview.session_id || readSessionId() || '').trim(),
      title: text(preview.title, 'Change preview'),
      summary: text(preview.summary || preview.diffReceiptText, 'Reversible draft prepared by the Intelligence Fabric.'),
      diffReceiptText: String(preview.diffReceiptText || preview.receiptText || preview.summary || '').trim(),
      approvalRequired: preview.approvalRequired === true,
      applied: preview.applied === true || String(preview.status || '').trim().toLowerCase() === 'applied',
      rollbackArtifactPath: String(preview.rollbackArtifactPath || '').trim(),
      actions: {
        approveApplyLabel: text(actions.approveApplyLabel, 'Approve/apply'),
        approveApplyInstruction: text(actions.approveApplyInstruction, 'Applies this draft to the workspace using the approved plan.'),
        rollbackLabel: text(actions.rollbackLabel, 'Rollback'),
        rollbackInstruction: text(actions.rollbackInstruction, 'Rollback is available through the Mutation Plane after apply.'),
      },
    };
  }

  function extractDiffPreviews(payload: any = state.zavorthControl || {}) {
    const candidates = [
      payload?.snapshot?.diffPreviews,
      payload?.snapshot?.runObservatory?.diffPreviews,
      payload?.diffPreviews,
      payload?.zavorthControl?.snapshot?.diffPreviews,
      payload?.zavorthControl?.snapshot?.runObservatory?.diffPreviews,
      state.zavorthControl?.snapshot?.diffPreviews,
      state.zavorthControl?.snapshot?.runObservatory?.diffPreviews,
    ];
    const previews = [];
    for (const candidate of candidates) {
      if (!Array.isArray(candidate)) continue;
      for (const entry of candidate) {
        const preview = normalizeDiffPreview(entry);
        if (preview) previews.push(preview);
      }
    }
    const byPlan = new Map();
    for (const preview of previews) {
      const key = preview.planId || preview.id;
      const current = byPlan.get(key);
      if (!current || preview.applied || (!current.applied && preview.runId === readRunId())) {
        byPlan.set(key, preview);
      }
    }
    return Array.from(byPlan.values());
  }

  function hasExecutionArtifactContext(payload: any) {
    if (!payload || typeof payload !== 'object') return false;
    if (!artifactPolicyAllowsChatDisplay(payload)) return false;
    if (String(payload.taskId || payload.runId || payload.approvalId || '').trim()) return true;
    if (Array.isArray(payload.artifacts) && payload.artifacts.length > 0) return true;
    if (Array.isArray(payload.artifactIds) && payload.artifactIds.length > 0) return true;
    if (payload.agentRun || payload.activeRun || payload.run) return true;
    const snapshot = payload.snapshot || payload.zavorthControl || null;
    if (snapshot && typeof snapshot === 'object') {
      if (snapshot.activeRun || snapshot.agentRun || snapshot.run) return true;
      if (Array.isArray(snapshot.tasks) && snapshot.tasks.length > 0) return true;
      if (Array.isArray(snapshot.workflowRuns) && snapshot.workflowRuns.length > 0) return true;
      if (Array.isArray(snapshot.artifacts) && snapshot.artifacts.length > 0) return true;
    }
    return false;
  }

  return {
    artifactPolicyAllowsChatDisplay,
    extractArtifacts,
    extractDiffPreviews,
    extractArtifactPolicy,
    extractResponseDecision,
    hasDirectExecutionArtifactContext,
    hasExecutionArtifactContext,
    normalizeArtifact,
    shouldDisplayArtifactsInChat,
  };
}
