import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import JSZip from 'jszip';
import { config } from '../config/index.js';
import {
  ZAVORTH_UNIVERSAL_SKILL_IMPORT_CONTRACT_VERSION,
  type ZavorthUniversalSkillImportDecision,
  type ZavorthUniversalSkillImportMaterializedFile,
  type ZavorthUniversalSkillImportReceipt,
  type ZavorthUniversalSkillImportSnapshot,
  type ZavorthUniversalSkillImportTrustPolicy,
} from '../contracts/ZavorthUniversalSkillImportContract.js';
import type {
  ZavorthUniversalSkillCandidate,
  ZavorthUniversalSkillIntakePreview,
  ZavorthUniversalSkillPermissionProfileId,
} from '../contracts/ZavorthUniversalSkillIntakeContract.js';
import type {
  SkillImportAuditReference,
  SkillLicensePolicyDecision,
  SkillRiskAssessment,
} from './SkillCatalogContract.js';
import { LicensePolicyService } from './LicensePolicyService.js';

import { UniversalSkillIntakeService } from './UniversalSkillIntakeService.js';type Runtime = {
  now?: () => Date;
  projectRoot?: string;
  intakeService?: Pick<UniversalSkillIntakeService, 'previewSource'>;
  licensePolicyService?: Pick<LicensePolicyService, 'evaluateClassification'>;
  existsSync?: typeof fs.existsSync;
  mkdirSync?: typeof fs.mkdirSync;
  rmSync?: typeof fs.rmSync;
  statSync?: typeof fs.statSync;
  lstatSync?: typeof fs.lstatSync;
  readFileSync?: typeof fs.readFileSync;
  writeFileSync?: typeof fs.writeFileSync;
};

export type UniversalSkillTrustImportInput = {
  sourcePath: string;
  sourceKind?: 'auto' | 'directory' | 'zip';
  sourceId?: string;
  sourceLabel?: string;
  targetRootPath?: string;
  apply?: boolean;
  overwrite?: boolean;
  allowSource?: boolean;
  allowedSourceIds?: string[];
  allowedSkillIds?: string[];
  allowedSkillNames?: string[];
  allowAllCandidates?: boolean;
};

type SourceFile = {
  relativePath: string;
  text: string;
};

type LicenseClassification = {
  license: string | null;
  confidence: 'high' | 'medium' | 'low';
  evidence: string[];
};

const GENERATED_SKILL_HEADER = [
  'Generated by Zavorth Universal Skill Intake.',
  'This file is a normalized skill prompt, not executable upstream code.',
  'Original source material is preserved for inspection only.',
].join(' ');

export class UniversalSkillTrustImportService {
  private readonly now: () => Date;
  private readonly projectRoot: string;
  private readonly intakeService: Pick<UniversalSkillIntakeService, 'previewSource'>;
  private readonly licensePolicyService: Pick<LicensePolicyService, 'evaluateClassification'>;
  private readonly existsSyncImpl: typeof fs.existsSync;
  private readonly mkdirSyncImpl: typeof fs.mkdirSync;
  private readonly rmSyncImpl: typeof fs.rmSync;
  private readonly statSyncImpl: typeof fs.statSync;
  private readonly lstatSyncImpl: typeof fs.lstatSync;
  private readonly readFileSyncImpl: typeof fs.readFileSync;
  private readonly writeFileSyncImpl: typeof fs.writeFileSync;

  constructor(runtime: Runtime = {}) {
    this.now = runtime.now || (() => new Date());
    this.projectRoot = runtime.projectRoot || config.projectRoot;
    this.intakeService = runtime.intakeService || new UniversalSkillIntakeService();
    this.licensePolicyService = runtime.licensePolicyService || new LicensePolicyService();
    this.existsSyncImpl = runtime.existsSync || fs.existsSync.bind(fs);
    this.mkdirSyncImpl = runtime.mkdirSync || fs.mkdirSync.bind(fs);
    this.rmSyncImpl = runtime.rmSync || fs.rmSync.bind(fs);
    this.statSyncImpl = runtime.statSync || fs.statSync.bind(fs);
    this.lstatSyncImpl = runtime.lstatSync || fs.lstatSync.bind(fs);
    this.readFileSyncImpl = runtime.readFileSync || fs.readFileSync.bind(fs);
    this.writeFileSyncImpl = runtime.writeFileSync || fs.writeFileSync.bind(fs);
  }

  public async buildSnapshot(input: UniversalSkillTrustImportInput): Promise<ZavorthUniversalSkillImportSnapshot> {
    const sourcePath = path.resolve(input.sourcePath || '.');
    const targetRootPath = path.resolve(input.targetRootPath || path.join(this.projectRoot, 'skill-library', 'imported'));
    const preview = await this.intakeService.previewSource({
      sourcePath,
      sourceKind: input.sourceKind || 'auto',
      sourceLabel: input.sourceLabel,
    });
    const sourceId = normalizeSourceId(input.sourceId || buildSourceId(preview));
    const trustPolicy = this.buildTrustPolicy(input, sourceId, preview);
    const apply = input.apply === true;
    const overwrite = input.overwrite === true;
    const decisions: ZavorthUniversalSkillImportDecision[] = [];
    const receipts: ZavorthUniversalSkillImportReceipt[] = [];
    const materializedFiles: ZavorthUniversalSkillImportMaterializedFile[] = [];

    for (const candidate of preview.candidates) {
      const files = await this.readCandidateFiles(preview, candidate);
      const license = this.classifyLicense(candidate, files);
      const licensePolicy = this.licensePolicyService.evaluateClassification(license);
      const risk = this.assessRisk({
        candidate,
        sourceAllowed: isSourceAllowed(trustPolicy, sourceId),
        skillAllowed: isSkillAllowed(trustPolicy, candidate),
        licensePolicy,
        warnings: candidate.issues.filter((issue) => issue.severity === 'warn').length,
      });
      const targetSkillDirPath = this.resolveTargetSkillDir(targetRootPath, candidate);
      const decision = this.buildDecision({
        candidate,
        trustPolicy,
        sourceId,
        targetSkillDirPath,
        risk,
        licensePolicy,
        apply,
        overwrite,
      });

      decisions.push(decision);
      receipts.push(this.buildReceipt({
        candidate,
        decision,
        sourceId,
        sourceLabel: trustPolicy.sourceLabel,
      }));

      if (!apply || !decision.allowed || decision.mode !== 'allow') {
        continue;
      }

      const written = this.materializeCandidate({
        preview,
        candidate,
        files,
        targetRootPath,
        targetSkillDirPath,
        sourceId,
        sourceLabel: trustPolicy.sourceLabel,
        license,
        licensePolicy,
        risk,
        overwrite,
        audit: decision.audit,
      });

      decision.materialized = written.length > 0;
      materializedFiles.push(...written);
    }

    const materialized = decisions.filter((decision) => decision.materialized).length;
    const denied = decisions.filter((decision) => decision.mode === 'deny').length;
    const skippedExisting = decisions.filter((decision) => decision.mode === 'skip-existing').length;
    const allowed = decisions.filter((decision) => decision.allowed).length;
    const status = apply
      ? materialized > 0 && denied === 0
        ? 'passed'
        : materialized > 0
          ? 'partial'
          : 'blocked'
      : 'preview-only';

    return {
      generatedAt: this.now().toISOString(),
      contractVersion: ZAVORTH_UNIVERSAL_SKILL_IMPORT_CONTRACT_VERSION,
      status,
      apply,
      overwrite,
      targetRootPath,
      preview,
      trustPolicy,
      summary: {
        candidates: preview.candidates.length,
        allowed,
        denied,
        skippedExisting,
        materialized,
        receipts: receipts.length,
        filesWritten: materializedFiles.length,
        previewRequired: true,
        importPerformed: materializedFiles.length > 0,
        executionPerformed: false,
        directUpstreamRuntimeUse: false,
      },
      decisions,
      receipts,
      materializedFiles,
      policy: {
        previewRequired: true,
        denyByDefault: true,
        sourceAllowlistRequired: true,
        skillAllowlistRequired: true,
        provenanceRequired: true,
        contentHashRequired: true,
        receiptsRequired: true,
        targetIsImportedLibrary: true,
        noExecutionPerformed: true,
        noDirectUpstreamRuntimeUse: true,
      },
      commands: {
        plan: 'npm run zavorth:universal-skill-import -- --source <path>',
        apply: 'npm run zavorth:universal-skill-import -- --source <path> --allow-source --skills <name> --apply',
        check: 'npm run zavorth:universal-skill-import:check --silent',
        nextAction: 'Approval gate - Skill Bridge Runtime',
      },
    };
  }

  public formatSnapshotText(snapshot: ZavorthUniversalSkillImportSnapshot): string {
    const lines = [
      'Zavorth Universal Skill Import - Preview engine',
      `Status: ${snapshot.status}`,
      `Apply: ${snapshot.apply}`,
      `Source: ${snapshot.trustPolicy.sourceLabel} (${snapshot.trustPolicy.sourceId})`,
      `Target: ${snapshot.targetRootPath}`,
      `Candidates: ${snapshot.summary.candidates}`,
      `Allowed: ${snapshot.summary.allowed}`,
      `Denied: ${snapshot.summary.denied}`,
      `Materialized: ${snapshot.summary.materialized}`,
      '',
      'Decisions:',
    ];

    for (const decision of snapshot.decisions) {
      lines.push(
        `- ${decision.skillName}: ${decision.mode}`,
        `  reason=${decision.reason}`,
        `  risk=${decision.risk.level}(${decision.risk.score}) license=${decision.licensePolicy.label}`,
        `  target=${decision.targetSkillDirPath}`,
      );
    }

    lines.push('', `Next: ${snapshot.commands.nextAction}`);
    return lines.join('\n');
  }

  private buildTrustPolicy(
    input: UniversalSkillTrustImportInput,
    sourceId: string,
    preview: ZavorthUniversalSkillIntakePreview,
  ): ZavorthUniversalSkillImportTrustPolicy {
    const allowedSourceIds = uniqueStrings([
      ...(input.allowedSourceIds || []),
      ...(input.allowSource === true ? [sourceId] : []),
    ]).map(normalizeSourceId);

    return {
      sourceId,
      sourceLabel: input.sourceLabel || preview.source.label,
      allowedSourceIds,
      allowedSkillIds: uniqueStrings(input.allowedSkillIds || []),
      allowedSkillNames: uniqueStrings(input.allowedSkillNames || []),
      allowAllCandidates: input.allowAllCandidates === true,
      denyByDefault: true,
    };
  }

  private buildDecision(input: {
    candidate: ZavorthUniversalSkillCandidate;
    trustPolicy: ZavorthUniversalSkillImportTrustPolicy;
    sourceId: string;
    targetSkillDirPath: string;
    risk: SkillRiskAssessment;
    licensePolicy: SkillLicensePolicyDecision;
    apply: boolean;
    overwrite: boolean;
  }): ZavorthUniversalSkillImportDecision {
    const sourceAllowed = isSourceAllowed(input.trustPolicy, input.sourceId);
    const skillAllowed = isSkillAllowed(input.trustPolicy, input.candidate);
    const candidateBlocked = input.candidate.status === 'blocked';
    const audit: SkillImportAuditReference = {
      lastEventId: `universal-skill-import-${stableReceiptId(input.candidate.id, this.now().toISOString()).slice(0, 12)}`,
      trailFilePath: path.join(path.dirname(input.targetSkillDirPath), '.zavorth-universal-import-audit.json'),
      lastAction: input.apply ? 'import' : 'preview',
      lastRecordedAt: this.now().toISOString(),
    };

    if (!input.apply) {
      return {
        candidateId: input.candidate.id,
        skillName: input.candidate.manifest.name,
        mode: 'preview-only',
        allowed: false,
        materialized: false,
        targetSkillDirPath: input.targetSkillDirPath,
        reason: 'Required preview completed; rerun with --apply and an explicit allowlist to import.',
        sourceAllowed,
        skillAllowed,
        candidateBlocked,
        risk: input.risk,
        licensePolicy: input.licensePolicy,
        audit,
      };
    }

    if (candidateBlocked || input.risk.level === 'blocked') {
      return denied('Candidate blocked by preview, risk, or license.');
    }
    if (!sourceAllowed) {
      return denied('Source is not in the explicit allowlist.');
    }
    if (!skillAllowed) {
      return denied('Skill is not in the explicit allowlist.');
    }
    if (!input.licensePolicy.allowImport) {
      return denied(`License blocks import: ${input.licensePolicy.summary}`);
    }
    if (this.existsSyncImpl(input.targetSkillDirPath) && !input.overwrite) {
      return {
        candidateId: input.candidate.id,
        skillName: input.candidate.manifest.name,
        mode: 'skip-existing',
        allowed: false,
        materialized: false,
        targetSkillDirPath: input.targetSkillDirPath,
        reason: 'Destination already exists; use --overwrite to replace it.',
        sourceAllowed,
        skillAllowed,
        candidateBlocked,
        risk: input.risk,
        licensePolicy: input.licensePolicy,
        audit,
      };
    }

    return {
      candidateId: input.candidate.id,
      skillName: input.candidate.manifest.name,
      mode: 'allow',
      allowed: true,
      materialized: false,
      targetSkillDirPath: input.targetSkillDirPath,
      reason: 'Source and skill authorized; import can be materialized in the imported workspace.',
      sourceAllowed,
      skillAllowed,
      candidateBlocked,
      risk: input.risk,
      licensePolicy: input.licensePolicy,
      audit,
    };

    function denied(reason: string): ZavorthUniversalSkillImportDecision {
      return {
        candidateId: input.candidate.id,
        skillName: input.candidate.manifest.name,
        mode: 'deny',
        allowed: false,
        materialized: false,
        targetSkillDirPath: input.targetSkillDirPath,
        reason,
        sourceAllowed,
        skillAllowed,
        candidateBlocked,
        risk: input.risk,
        licensePolicy: input.licensePolicy,
        audit,
      };
    }
  }

  private buildReceipt(input: {
    candidate: ZavorthUniversalSkillCandidate;
    decision: ZavorthUniversalSkillImportDecision;
    sourceId: string;
    sourceLabel: string;
  }): ZavorthUniversalSkillImportReceipt {
    const kind = input.decision.mode === 'allow'
      ? 'import'
      : input.decision.mode === 'skip-existing'
        ? 'skip'
        : input.decision.mode === 'preview-only'
          ? 'preview'
          : 'deny';
    return {
      id: `universal-skill-${kind}:${stableReceiptId(input.candidate.id, input.decision.audit.lastEventId || '')}`,
      kind,
      candidateId: input.candidate.id,
      skillName: input.candidate.manifest.name,
      status: kind === 'import' || kind === 'preview' ? 'pass' : kind === 'skip' ? 'skip' : 'deny',
      targetSkillDirPath: input.decision.targetSkillDirPath,
      sourceId: input.sourceId,
      sourceLabel: input.sourceLabel,
      contentHash: input.candidate.manifest.contentHash,
      previewRequired: true,
      allowedBySource: input.decision.sourceAllowed,
      allowedBySkill: input.decision.skillAllowed,
      noExecutionPerformed: true,
      noDirectUpstreamRuntimeUse: true,
      reason: input.decision.reason,
    };
  }

  private materializeCandidate(input: {
    preview: ZavorthUniversalSkillIntakePreview;
    candidate: ZavorthUniversalSkillCandidate;
    files: SourceFile[];
    targetRootPath: string;
    targetSkillDirPath: string;
    sourceId: string;
    sourceLabel: string;
    license: LicenseClassification;
    licensePolicy: SkillLicensePolicyDecision;
    risk: SkillRiskAssessment;
    overwrite: boolean;
    audit: SkillImportAuditReference;
  }): ZavorthUniversalSkillImportMaterializedFile[] {
    this.ensureTargetWithinRoot(input.targetRootPath, input.targetSkillDirPath);
    if (this.existsSyncImpl(input.targetSkillDirPath)) {
      if (!input.overwrite) {
        return [];
      }
      this.rmSyncImpl(input.targetSkillDirPath, { recursive: true, force: true });
    }
    this.mkdirSyncImpl(input.targetSkillDirPath, { recursive: true });

    const written: ZavorthUniversalSkillImportMaterializedFile[] = [];
    const mainFile = input.files.find((file) => file.relativePath === input.candidate.manifest.entrypointPath);
    const hasSkillMd = Boolean(mainFile && path.posix.basename(mainFile.relativePath) === 'SKILL.md');

    if (hasSkillMd && mainFile) {
      this.writeMaterializedFile({
        targetRootPath: input.targetSkillDirPath,
        relativePath: 'SKILL.md',
        text: mainFile.text,
        candidateId: input.candidate.id,
        generated: false,
        written,
      });
    } else {
      this.writeMaterializedFile({
        targetRootPath: input.targetSkillDirPath,
        relativePath: 'SKILL.md',
        text: this.buildGeneratedSkillMd(input.candidate),
        candidateId: input.candidate.id,
        generated: true,
        written,
      });
    }

    for (const file of input.files) {
      if (file.relativePath === input.candidate.manifest.entrypointPath && hasSkillMd) {
        continue;
      }
      const relative = this.resolveImportedSupportPath(input.candidate, file.relativePath);
      this.writeMaterializedFile({
        targetRootPath: input.targetSkillDirPath,
        relativePath: relative,
        text: file.text,
        candidateId: input.candidate.id,
        generated: false,
        written,
      });
    }

    const origin = {
      version: 1,
      importedAt: this.now().toISOString(),
      importMode: 'manual',
      skillName: input.candidate.manifest.name,
      source: {
        id: input.sourceId,
        label: input.sourceLabel,
        kind: input.preview.source.kind === 'zip' ? 'vendor' : 'repository',
        trust: 'review',
        registrySource: 'zavorth:universal-skill-intake',
        upstream: input.preview.source.path,
        license: input.license.license,
        ownership: 'universal-intake',
      },
      originalSkillPath: input.candidate.manifest.entrypointPath,
      originalRelativePath: input.candidate.manifest.relativeSkillPath,
      copiedFiles: written.map((file) => file.relativePath).sort((left, right) => left.localeCompare(right, 'en-US')),
      governance: {
        risk: input.risk,
        licensePolicy: input.licensePolicy,
        audit: input.audit,
      },
    };

    this.writeMaterializedFile({
      targetRootPath: input.targetSkillDirPath,
      relativePath: 'ORIGIN.json',
      text: JSON.stringify(origin, null, 2),
      candidateId: input.candidate.id,
      generated: true,
      written,
    });
    this.writeMaterializedFile({
      targetRootPath: input.targetSkillDirPath,
      relativePath: 'ATTRIBUTION.md',
      text: this.buildAttribution(input),
      candidateId: input.candidate.id,
      generated: true,
      written,
    });
    this.appendAuditTrail(path.join(input.targetRootPath, '.zavorth-universal-import-audit.json'), {
      eventId: input.audit.lastEventId,
      importedAt: this.now().toISOString(),
      sourceId: input.sourceId,
      skillName: input.candidate.manifest.name,
      candidateId: input.candidate.id,
      targetSkillDirPath: input.targetSkillDirPath,
      risk: input.risk.level,
      licensePolicy: input.licensePolicy.label,
      contentHash: input.candidate.manifest.contentHash,
    });

    return written;
  }

  private buildGeneratedSkillMd(candidate: ZavorthUniversalSkillCandidate): string {
    return [
      '---',
      `name: ${yamlSafeScalar(candidate.manifest.name)}`,
      `description: ${yamlSafeScalar(candidate.manifest.description)}`,
      '---',
      '',
      `# ${candidate.manifest.name}`,
      '',
      GENERATED_SKILL_HEADER,
      '',
      '## Normalized Capability',
      '',
      `- Source profile: ${candidate.manifest.sourceProfileId}`,
      `- Permission profile: ${candidate.manifest.permissionProfileId}`,
      `- Capability tags: ${candidate.manifest.capabilityTags.join(', ') || 'workflow'}`,
      '',
      '## Description',
      '',
      candidate.manifest.description,
      '',
      '## Safety',
      '',
      'Do not execute upstream scripts or tools directly. Use Zavorth policy, approvals and receipts.',
    ].join('\n');
  }

  private buildAttribution(input: {
    preview: ZavorthUniversalSkillIntakePreview;
    candidate: ZavorthUniversalSkillCandidate;
    sourceId: string;
    sourceLabel: string;
    license: LicenseClassification;
    licensePolicy: SkillLicensePolicyDecision;
    risk: SkillRiskAssessment;
  }): string {
    return [
      '# Attribution',
      '',
      'Imported by Zavorth Universal Skill Intake.',
      '',
      `- Source: ${input.sourceLabel} (${input.sourceId})`,
      `- Source path: ${input.preview.source.path}`,
      `- Source kind: ${input.preview.source.kind}`,
      `- Candidate: ${input.candidate.manifest.name}`,
      `- Candidate path: ${input.candidate.manifest.relativeSkillPath}`,
      `- Content hash: ${input.candidate.manifest.contentHash}`,
      `- License: ${input.license.license || 'unknown'}`,
      `- License policy: ${input.licensePolicy.label} (${input.licensePolicy.summary})`,
      `- Risk: ${input.risk.level} (${input.risk.score})`,
      '',
      'No upstream runtime code was executed during import.',
    ].join('\n');
  }

  private resolveImportedSupportPath(candidate: ZavorthUniversalSkillCandidate, sourceRelativePath: string): string {
    const sourceRoot = candidate.manifest.relativeSkillPath;
    let relative = sourceRelativePath;
    if (sourceRoot !== '.' && !sourceRoot.includes('#') && sourceRelativePath.startsWith(`${sourceRoot}/`)) {
      relative = sourceRelativePath.slice(sourceRoot.length + 1);
    }
    if (relative === 'SKILL.md') {
      return 'references/original-SKILL.md';
    }
    if (relative === candidate.manifest.manifestPath || relative === candidate.manifest.entrypointPath) {
      return `references/source-${path.posix.basename(relative)}`;
    }
    if (!relative.includes('/')) {
      return `references/${relative}`;
    }
    return relative;
  }

  private writeMaterializedFile(input: {
    targetRootPath: string;
    relativePath: string;
    text: string;
    candidateId: string;
    generated: boolean;
    written: ZavorthUniversalSkillImportMaterializedFile[];
  }): void {
    const relativePath = normalizeRelativePath(input.relativePath);
    if (!isSafeRelativePath(relativePath)) {
      throw new Error(`Unsafe target relative path: ${input.relativePath}`);
    }
    const targetPath = path.join(input.targetRootPath, relativePath);
    this.ensureTargetWithinRoot(input.targetRootPath, targetPath);
    this.mkdirSyncImpl(path.dirname(targetPath), { recursive: true });
    this.writeFileSyncImpl(targetPath, input.text, 'utf8');
    input.written.push({
      candidateId: input.candidateId,
      relativePath,
      targetPath,
      sha256: sha256(input.text),
      generated: input.generated,
    });
  }

  private async readCandidateFiles(
    preview: ZavorthUniversalSkillIntakePreview,
    candidate: ZavorthUniversalSkillCandidate,
  ): Promise<SourceFile[]> {
    const paths = uniqueStrings([
      candidate.manifest.entrypointPath || '',
      candidate.manifest.manifestPath || '',
      ...candidate.manifest.supportFiles,
    ]).filter(Boolean);

    if (preview.source.kind === 'zip') {
      const buffer = this.readFileSyncImpl(preview.source.path);
      const zip = await JSZip.loadAsync(buffer);
      const files: SourceFile[] = [];
      for (const relativePath of paths) {
        const normalized = normalizeRelativePath(relativePath);
        const entry = zip.file(normalized);
        if (!entry) {
          continue;
        }
        const content = await entry.async('nodebuffer');
        files.push({
          relativePath: normalized,
          text: content.toString('utf8').replace(/^\uFEFF/, ''),
        });
      }
      return files;
    }

    return paths.map((relativePath) => {
      const normalized = normalizeRelativePath(relativePath);
      const absolute = path.resolve(preview.source.path, normalized);
      this.ensureTargetWithinRoot(preview.source.path, absolute);
      const lstat = this.lstatSyncImpl(absolute);
      if (lstat.isSymbolicLink() || !lstat.isFile()) {
        throw new Error(`Unsafe source file during import: ${normalized}`);
      }
      return {
        relativePath: normalized,
        text: this.readFileSyncImpl(absolute, 'utf8').replace(/^\uFEFF/, ''),
      };
    });
  }

  private classifyLicense(
    candidate: ZavorthUniversalSkillCandidate,
    files: SourceFile[],
  ): LicenseClassification {
    const skillMd = files.find((file) => path.posix.basename(file.relativePath) === 'SKILL.md');
    if (skillMd) {
      const frontmatter = parseFrontmatter(skillMd.text);
      const license = normalizeLicenseValue(frontmatter.license);
      if (license) {
        return {
          license,
          confidence: 'medium',
          evidence: ['SKILL.md:frontmatter.license'],
        };
      }
    }

    const licenseFile = files.find((file) => /^license(?:\.(?:md|txt))?$/i.test(path.posix.basename(file.relativePath)));
    if (licenseFile) {
      const license = detectLicenseFromText(licenseFile.text);
      if (license) {
        return {
          license,
          confidence: 'high',
          evidence: [`license-file:${licenseFile.relativePath}`],
        };
      }
      if (/all rights reserved|proprietary|no redistribution/i.test(licenseFile.text)) {
        return {
          license: 'proprietary',
          confidence: 'high',
          evidence: [`license-file:${licenseFile.relativePath}`],
        };
      }
    }

    const manifestLicense = normalizeLicenseValue(candidate.manifest.notes.find((entry) => /^license:/i.test(entry))?.split(':').slice(1).join(':'));
    if (manifestLicense) {
      return {
        license: manifestLicense,
        confidence: 'low',
        evidence: ['manifest:notes'],
      };
    }

    return {
      license: null,
      confidence: 'low',
      evidence: [],
    };
  }

  private assessRisk(input: {
    candidate: ZavorthUniversalSkillCandidate;
    sourceAllowed: boolean;
    skillAllowed: boolean;
    licensePolicy: SkillLicensePolicyDecision;
    warnings: number;
  }): SkillRiskAssessment {
    const reasons: string[] = [];
    if (input.candidate.status === 'blocked') {
      reasons.push('Candidate blocked by universal preview.');
      return blockedRisk(reasons);
    }
    if (!input.sourceAllowed) {
      reasons.push('Source not allowed by allowlist.');
      return blockedRisk(reasons);
    }
    if (!input.skillAllowed) {
      reasons.push('Skill not allowed by allowlist.');
      return blockedRisk(reasons);
    }
    if (!input.licensePolicy.allowImport) {
      reasons.push(`License blocked: ${input.licensePolicy.summary}`);
      return blockedRisk(reasons);
    }

    let score = 20;
    reasons.push('Universal source requires review by default.');
    score += input.warnings * 10;
    if (input.licensePolicy.reviewRequired) {
      score += 15;
      reasons.push('License requires review before trust.');
    }

    const permission = input.candidate.manifest.permissionProfileId;
    score += riskWeightForPermission(permission);
    reasons.push(`Inferred permission profile: ${permission}.`);

    const normalized = Math.max(0, Math.min(score, 100));
    return {
      score: normalized,
      level: normalized >= 60 ? 'high' : normalized >= 25 ? 'medium' : 'low',
      reviewRequired: true,
      reasons,
    };
  }

  private resolveTargetSkillDir(targetRootPath: string, candidate: ZavorthUniversalSkillCandidate): string {
    const slug = safeId(candidate.manifest.name || candidate.id);
    const target = path.join(targetRootPath, slug);
    this.ensureTargetWithinRoot(targetRootPath, target);
    return target;
  }

  private ensureTargetWithinRoot(rootPath: string, targetPath: string): void {
    const root = path.resolve(rootPath);
    const target = path.resolve(targetPath);
    const relative = path.relative(root, target);
    if (relative.startsWith('..') || path.isAbsolute(relative)) {
      throw new Error(`Path escapes allowed root: ${targetPath}`);
    }
  }

  private appendAuditTrail(filePath: string, event: Record<string, unknown>): void {
    const events = (() => {
      try {
        if (!this.existsSyncImpl(filePath)) {
          return [];
        }
        const parsed = JSON.parse(this.readFileSyncImpl(filePath, 'utf8'));
        return Array.isArray(parsed?.events) ? parsed.events : [];
      } catch (error: unknown) {return [];
      }
    })();
    this.mkdirSyncImpl(path.dirname(filePath), { recursive: true });
    this.writeFileSyncImpl(filePath, JSON.stringify({
      version: 1,
      updatedAt: this.now().toISOString(),
      events: [...events, event],
    }, null, 2), 'utf8');
  }
}

function isSourceAllowed(policy: ZavorthUniversalSkillImportTrustPolicy, sourceId: string): boolean {
  return policy.allowedSourceIds.map(normalizeSourceId).includes(normalizeSourceId(sourceId));
}

function isSkillAllowed(
  policy: ZavorthUniversalSkillImportTrustPolicy,
  candidate: ZavorthUniversalSkillCandidate,
): boolean {
  if (policy.allowAllCandidates) {
    return true;
  }
  const ids = new Set(policy.allowedSkillIds.map((entry) => entry.toLowerCase()));
  const names = new Set(policy.allowedSkillNames.map((entry) => entry.toLowerCase()));
  return ids.has(candidate.id.toLowerCase())
    || ids.has(candidate.manifest.id.toLowerCase())
    || names.has(candidate.manifest.name.toLowerCase());
}

function buildSourceId(preview: ZavorthUniversalSkillIntakePreview): string {
  return `universal-source:${sha256(`${preview.source.kind}:${preview.source.path}:${preview.source.archiveBytes || 0}`).slice(0, 16)}`;
}

function normalizeSourceId(value: string): string {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_:/.-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'universal-source:unknown';
}

function riskWeightForPermission(permission: ZavorthUniversalSkillPermissionProfileId): number {
  switch (permission) {
    case 'connector-live-secretref':
    case 'tool-execution-approval':
      return 35;
    case 'workspace-write-approval':
      return 25;
    case 'network-read-approval':
      return 20;
    case 'workspace-read':
      return 10;
    case 'blocked':
      return 100;
    case 'local-readonly':
    default:
      return 0;
  }
}

function blockedRisk(reasons: string[]): SkillRiskAssessment {
  return {
    score: 100,
    level: 'blocked',
    reviewRequired: true,
    reasons,
  };
}

function parseFrontmatter(text: string): Record<string, unknown> {
  const match = text.match(/^---\s*\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    return {};
  }
  try {
    const parsed = yaml.load(match[1]);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? parsed as Record<string, unknown>
      : {};
  } catch (error: unknown) {return {};
  }
}

function normalizeLicenseValue(value: unknown): string | null {
  const normalized = String(value || '').trim();
  if (!normalized) {
    return null;
  }
  if (/^apache(?:-|\s*)2(?:\.0)?$/i.test(normalized)) {
    return 'Apache-2.0';
  }
  if (/^mit$/i.test(normalized)) {
    return 'MIT';
  }
  if (/^cc[\s-]*by(?:[\s-]*4(?:\.0)?)?$/i.test(normalized)) {
    return 'CC-BY-4.0';
  }
  return normalized;
}

function detectLicenseFromText(text: string): string | null {
  const normalized = text.toLowerCase();
  if (normalized.includes('apache license') && normalized.includes('version 2.0')) return 'Apache-2.0';
  if (normalized.includes('mit license')) return 'MIT';
  if (normalized.includes('creative commons attribution 4.0')) return 'CC-BY-4.0';
  return null;
}

function yamlSafeScalar(value: string): string {
  return JSON.stringify(String(value || ''));
}

function normalizeRelativePath(value: string): string {
  return String(value || '').replace(/\\/g, '/').replace(/^\.\/+/, '');
}

function isSafeRelativePath(value: string): boolean {
  const normalized = normalizeRelativePath(value);
  return Boolean(normalized)
    && !normalized.startsWith('../')
    && normalized !== '..'
    && !path.isAbsolute(normalized)
    && !/^[A-Za-z]:\//.test(normalized)
    && !normalized.split('/').includes('..');
}

function safeId(value: string): string {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_.:-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'skill';
}

function uniqueStrings(values: string[]): string[] {
  return Array.from(new Set(values.map((value) => String(value || '').trim()).filter(Boolean)))
    .sort((left, right) => left.localeCompare(right, 'en-US'));
}

function sha256(text: string | Buffer): string {
  return crypto.createHash('sha256').update(text).digest('hex');
}

function stableReceiptId(...parts: string[]): string {
  return sha256(parts.join(':')).slice(0, 16);
}
