import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

export const AGGREGATOR_PROVIDER_INTEGRATION_MANIFESTS: ProviderIntegrationManifest[] = [
  {
    schemaVersion: 1,
    id: 'openrouter',
    label: 'OpenRouter',
    vendorId: 'openrouter',
    providerId: 'openrouter',
    providerName: 'openrouter',
    source: 'current_constants',
    aliases: ['openrouter', 'or'],
    website: 'https://openrouter.ai',
    routeKind: 'aggregator',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'research', 'streaming', 'tool_use', 'vision', 'long_context'],
    modalities: ['text', 'image', 'tool'],
    families: [
      {
        familyId: 'openrouter',
        label: 'OpenRouter Catalog',
        vendorId: 'openrouter',
        providerIds: ['openrouter'],
        summary: 'Aggregator route that can address many hosted model families.',
        defaultModelName: 'openrouter/auto',
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'research', 'streaming', 'tool_use', 'vision', 'long_context'],
        modalities: ['text', 'image', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'openrouter',
        label: 'OpenRouter',
        vendorId: 'openrouter',
        providerId: 'openrouter',
        providerName: 'openrouter',
        familyIds: ['openrouter'],
        routeKind: 'aggregator',
        mode: 'cloud',
        aliases: ['openrouter', 'or'],
        authKind: 'api_key',
        credentialRefs: ['OPENROUTER_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'research', 'streaming', 'tool_use', 'vision', 'long_context'],
        modalities: ['text', 'image', 'tool'],
        models: [{ modelId: 'openrouter/auto', label: 'OpenRouter Auto', primary: true }],
        passthroughModels: true,
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'qwen',
    label: 'Qwen via Puter',
    vendorId: 'alibaba',
    providerId: 'qwen',
    providerName: 'qwen',
    source: 'current_constants',
    aliases: ['qwen', 'qw', 'puter', 'pu'],
    website: 'https://puter.com',
    routeKind: 'partner',
    authKind: 'bearer_token',
    capabilities: ['chat', 'coding', 'streaming', 'budget', 'vision'],
    modalities: ['text', 'image'],
    families: [
      {
        familyId: 'qwen',
        label: 'Qwen',
        vendorId: 'alibaba',
        providerIds: ['qwen', 'puter'],
        summary: 'Qwen route exposed through Puter and DashScope-compatible surfaces.',
        defaultModelName: 'qwen3-coder-plus',
        secondaryModelNames: ['qwen3.5-plus', 'qwen-vl'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'streaming', 'budget', 'vision'],
        modalities: ['text', 'image'],
      },
    ],
    routes: [
      {
        routeId: 'qwen',
        label: 'Qwen via Puter',
        vendorId: 'alibaba',
        providerId: 'qwen',
        providerName: 'qwen',
        familyIds: ['qwen'],
        routeKind: 'partner',
        mode: 'cloud',
        aliases: ['qwen', 'qw', 'puter', 'pu'],
        authKind: 'bearer_token',
        credentialRefs: ['PUTER_AUTH_TOKEN'],
        capabilities: ['chat', 'coding', 'streaming', 'budget', 'vision'],
        modalities: ['text', 'image'],
        models: [
          { modelId: 'qwen3-coder-plus', label: 'Qwen3 Coder Plus', primary: true },
          { modelId: 'qwen3.5-plus', label: 'Qwen3.5 Plus' },
          { modelId: 'qwen-vl', label: 'Qwen VL' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'kilo-gateway',
    label: 'Kilo Gateway',
    vendorId: 'kilo',
    providerId: 'kilo-gateway',
    providerName: 'kilo-gateway',
    source: 'current_constants',
    aliases: ['kilo-gateway', 'kg'],
    website: 'https://kilo.ai',
    routeKind: 'aggregator',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'kilo-gateway',
        label: 'Kilo Gateway',
        vendorId: 'kilo',
        providerIds: ['kilo-gateway'],
        summary: 'Aggregator route for Kilo hosted models.',
        defaultModelName: null,
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
        modalities: ['text', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'kilo-gateway',
        label: 'Kilo Gateway',
        vendorId: 'kilo',
        providerId: 'kilo-gateway',
        providerName: 'kilo-gateway',
        familyIds: ['kilo-gateway'],
        routeKind: 'aggregator',
        mode: 'cloud',
        aliases: ['kilo-gateway', 'kg'],
        authKind: 'api_key',
        credentialRefs: ['KILO_GATEWAY_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
        modalities: ['text', 'tool'],
        models: [],
        passthroughModels: true,
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'cerebras',
    label: 'Cerebras',
    vendorId: 'cerebras',
    providerId: 'cerebras',
    providerName: 'cerebras',
    source: 'curated',
    aliases: ['cerebras', 'cerebras-cloud'],
    website: 'https://cloud.cerebras.ai',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'budget'],
    modalities: ['text'],
    families: [
      {
        familyId: 'cerebras',
        label: 'Cerebras',
        vendorId: 'cerebras',
        providerIds: ['cerebras'],
        summary: 'Cerebras hosted open models through an OpenAI-compatible inference API.',
        defaultModelName: 'llama-3.3-70b',
        secondaryModelNames: ['gpt-oss-120b', 'qwen-3-235b-a22b-instruct-2507', 'llama3.1-8b'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'budget'],
        modalities: ['text'],
      },
    ],
    routes: [
      {
        routeId: 'cerebras',
        label: 'Cerebras OpenAI-Compatible API',
        vendorId: 'cerebras',
        providerId: 'cerebras',
        providerName: 'cerebras',
        familyIds: ['cerebras'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['cerebras', 'cerebras-cloud'],
        authKind: 'api_key',
        credentialRefs: ['CEREBRAS_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'budget'],
        modalities: ['text'],
        models: [
          { modelId: 'llama-3.3-70b', label: 'Llama 3.3 70B', primary: true },
          { modelId: 'gpt-oss-120b', label: 'GPT OSS 120B' },
          { modelId: 'qwen-3-235b-a22b-instruct-2507', label: 'Qwen 3 235B' },
          { modelId: 'llama3.1-8b', label: 'Llama 3.1 8B' },
        ],
        passthroughModels: true,
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'github-models',
    label: 'GitHub Models',
    vendorId: 'github',
    providerId: 'github-models',
    providerName: 'github-models',
    source: 'curated',
    aliases: ['github-models', 'github-models-api', 'gh-models'],
    website: 'https://docs.github.com/en/rest/models',
    routeKind: 'official',
    authKind: 'bearer_token',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'budget'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'github-models',
        label: 'GitHub Models',
        vendorId: 'github',
        providerIds: ['github-models'],
        summary: 'GitHub Models inference with GitHub token authentication and OpenAI-compatible chat paths.',
        defaultModelName: 'openai/gpt-4.1',
        secondaryModelNames: ['openai/gpt-4o', 'meta/llama-3.3-70b-instruct', 'deepseek/deepseek-v3-0324'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'budget'],
        modalities: ['text', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'github-models',
        label: 'GitHub Models Inference',
        vendorId: 'github',
        providerId: 'github-models',
        providerName: 'github-models',
        familyIds: ['github-models'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['github-models', 'github-models-api', 'gh-models'],
        authKind: 'bearer_token',
        credentialRefs: ['GITHUB_MODELS_TOKEN', 'GITHUB_TOKEN'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'budget'],
        modalities: ['text', 'tool'],
        models: [
          { modelId: 'openai/gpt-4.1', label: 'OpenAI GPT-4.1', primary: true },
          { modelId: 'openai/gpt-4o', label: 'OpenAI GPT-4o' },
          { modelId: 'meta/llama-3.3-70b-instruct', label: 'Llama 3.3 70B Instruct' },
          { modelId: 'deepseek/deepseek-v3-0324', label: 'DeepSeek V3' },
        ],
        passthroughModels: true,
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'cohere',
    label: 'Cohere',
    vendorId: 'cohere',
    providerId: 'cohere',
    providerName: 'cohere',
    source: 'curated',
    aliases: ['cohere', 'command-r', 'command-a'],
    website: 'https://docs.cohere.com/reference/chat',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'reasoning', 'research', 'streaming', 'tool_use', 'long_context'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'cohere-command',
        label: 'Cohere Command',
        vendorId: 'cohere',
        providerIds: ['cohere'],
        summary: 'Cohere Command models through the Cohere API or compatibility route.',
        defaultModelName: 'command-a-plus-05-2026',
        secondaryModelNames: ['command-a-03-2025', 'command-r-plus-08-2024', 'command-r-08-2024'],
        fallbackModelNames: [],
        capabilities: ['chat', 'reasoning', 'research', 'streaming', 'tool_use', 'long_context'],
        modalities: ['text', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'cohere',
        label: 'Cohere Compatibility API',
        vendorId: 'cohere',
        providerId: 'cohere',
        providerName: 'cohere',
        familyIds: ['cohere-command'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['cohere', 'command-r', 'command-a'],
        authKind: 'api_key',
        credentialRefs: ['COHERE_API_KEY', 'CO_API_KEY'],
        capabilities: ['chat', 'reasoning', 'research', 'streaming', 'tool_use', 'long_context'],
        modalities: ['text', 'tool'],
        models: [
          { modelId: 'command-a-plus-05-2026', label: 'Command A Plus 05-2026', primary: true },
          { modelId: 'command-a-03-2025', label: 'Command A 03-2025' },
          { modelId: 'command-r-plus-08-2024', label: 'Command R+ 08-2024' },
          { modelId: 'command-r-08-2024', label: 'Command R 08-2024' },
        ],
        passthroughModels: true,
      },
    ],
    notes: [
      'Cohere native v2/chat is not OpenAI-shaped, so Zavorth routes it through the documented compatibility surface when used by the generic runtime.',
    ],
  },
  {
    schemaVersion: 1,
    id: 'sambanova',
    label: 'SambaNova Cloud',
    vendorId: 'sambanova',
    providerId: 'sambanova',
    providerName: 'sambanova',
    source: 'curated',
    aliases: ['sambanova', 'sambanova-cloud', 'samba'],
    website: 'https://docs.sambanova.ai/docs/en/get-started/quickstart',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'budget'],
    modalities: ['text', 'image'],
    families: [
      {
        familyId: 'sambanova',
        label: 'SambaNova Cloud',
        vendorId: 'sambanova',
        providerIds: ['sambanova'],
        summary: 'SambaNova hosted open models through an OpenAI-compatible API.',
        defaultModelName: 'Meta-Llama-3.3-70B-Instruct',
        secondaryModelNames: ['DeepSeek-V3.2', 'Llama-4-Maverick-17B-128E-Instruct', 'gpt-oss-120b'],
        fallbackModelNames: [],
        capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'budget'],
        modalities: ['text', 'image'],
      },
    ],
    routes: [
      {
        routeId: 'sambanova',
        label: 'SambaNova OpenAI-Compatible API',
        vendorId: 'sambanova',
        providerId: 'sambanova',
        providerName: 'sambanova',
        familyIds: ['sambanova'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['sambanova', 'sambanova-cloud', 'samba'],
        authKind: 'api_key',
        credentialRefs: ['SAMBANOVA_API_KEY'],
        capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'budget'],
        modalities: ['text', 'image'],
        models: [
          { modelId: 'Meta-Llama-3.3-70B-Instruct', label: 'Meta Llama 3.3 70B Instruct', primary: true },
          { modelId: 'DeepSeek-V3.2', label: 'DeepSeek V3.2' },
          { modelId: 'Llama-4-Maverick-17B-128E-Instruct', label: 'Llama 4 Maverick' },
          { modelId: 'gpt-oss-120b', label: 'GPT OSS 120B' },
        ],
        passthroughModels: true,
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'falcon',
    label: 'Falcon via Hugging Face Router',
    vendorId: 'tii',
    providerId: 'falcon',
    providerName: 'falcon',
    source: 'curated',
    aliases: ['falcon', 'tii-falcon', 'falcon-llm'],
    website: 'https://huggingface.co/tiiuae',
    routeKind: 'partner',
    authKind: 'api_key',
    capabilities: ['chat', 'budget'],
    modalities: ['text'],
    families: [
      {
        familyId: 'falcon',
        label: 'Falcon',
        vendorId: 'tii',
        providerIds: ['falcon'],
        summary: 'TII Falcon open-weight models addressed through Hugging Face/OpenAI-compatible routing.',
        defaultModelName: 'tiiuae/falcon-180B-chat',
        secondaryModelNames: ['tiiuae/falcon-40b-instruct', 'tiiuae/falcon-7b-instruct'],
        fallbackModelNames: [],
        capabilities: ['chat', 'budget'],
        modalities: ['text'],
      },
    ],
    routes: [
      {
        routeId: 'falcon',
        label: 'Falcon HF Router',
        vendorId: 'tii',
        providerId: 'falcon',
        providerName: 'falcon',
        familyIds: ['falcon'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['falcon', 'tii-falcon', 'falcon-llm'],
        authKind: 'api_key',
        credentialRefs: ['FALCON_API_KEY', 'HUGGINGFACE_API_KEY', 'HF_TOKEN'],
        capabilities: ['chat', 'budget'],
        modalities: ['text'],
        models: [
          { modelId: 'tiiuae/falcon-180B-chat', label: 'Falcon 180B Chat', primary: true },
          { modelId: 'tiiuae/falcon-40b-instruct', label: 'Falcon 40B Instruct' },
          { modelId: 'tiiuae/falcon-7b-instruct', label: 'Falcon 7B Instruct' },
        ],
      },
    ],
    notes: [
      'Falcon is an open-weight model family. Zavorth exposes it as a dedicated route through Hugging Face-compatible hosting instead of pretending there is one universal TII public chat API.',
    ],
  },
  {
    schemaVersion: 1,
    id: 'jais',
    label: 'Jais via Hugging Face Router',
    vendorId: 'core42',
    providerId: 'jais',
    providerName: 'jais',
    source: 'curated',
    aliases: ['jais', 'core42-jais', 'inception-jais'],
    website: 'https://huggingface.co/core42',
    routeKind: 'partner',
    authKind: 'api_key',
    capabilities: ['chat', 'budget'],
    modalities: ['text'],
    families: [
      {
        familyId: 'jais',
        label: 'Jais',
        vendorId: 'core42',
        providerIds: ['jais'],
        summary: 'Core42/Inception Jais Arabic-English open models through Hugging Face-compatible routing.',
        defaultModelName: 'core42/jais-13b-chat',
        secondaryModelNames: ['core42/jais-30b-chat-v3', 'core42/jais-family-30b-16k-chat'],
        fallbackModelNames: [],
        capabilities: ['chat', 'budget'],
        modalities: ['text'],
      },
    ],
    routes: [
      {
        routeId: 'jais',
        label: 'Jais HF Router',
        vendorId: 'core42',
        providerId: 'jais',
        providerName: 'jais',
        familyIds: ['jais'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['jais', 'core42-jais', 'inception-jais'],
        authKind: 'api_key',
        credentialRefs: ['JAIS_API_KEY', 'CORE42_API_KEY', 'HUGGINGFACE_API_KEY', 'HF_TOKEN'],
        capabilities: ['chat', 'budget'],
        modalities: ['text'],
        models: [
          { modelId: 'core42/jais-13b-chat', label: 'Jais 13B Chat', primary: true },
          { modelId: 'core42/jais-30b-chat-v3', label: 'Jais 30B Chat v3' },
          { modelId: 'core42/jais-family-30b-16k-chat', label: 'Jais Family 30B 16K Chat' },
        ],
      },
    ],
    notes: [
      'Core42 private Compass/Jais endpoints require operator provisioning. The default Zavorth route uses the open model family through Hugging Face-compatible hosting when credentials are present.',
    ],
  },
];
