import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

export const AGGREGATOR_PROVIDER_INTEGRATION_MANIFESTS: ProviderIntegrationManifest[] = [
  {
    schemaVersion: 1,
    id: 'openrouter',
    label: 'OpenRouter',
    vendorId: 'openrouter',
    providerId: 'openrouter',
    providerName: 'openrouter',
    source: 'current_constants',
    aliases: ['openrouter', 'or'],
    website: 'https://openrouter.ai',
    routeKind: 'aggregator',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'research', 'streaming', 'tool_use', 'vision', 'long_context'],
    modalities: ['text', 'image', 'tool'],
    families: [
      {
        familyId: 'openrouter',
        label: 'OpenRouter Catalog',
        vendorId: 'openrouter',
        providerIds: ['openrouter'],
        summary: 'Aggregator route that can address many hosted model families.',
        defaultModelName: 'openrouter/auto',
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'research', 'streaming', 'tool_use', 'vision', 'long_context'],
        modalities: ['text', 'image', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'openrouter',
        label: 'OpenRouter',
        vendorId: 'openrouter',
        providerId: 'openrouter',
        providerName: 'openrouter',
        familyIds: ['openrouter'],
        routeKind: 'aggregator',
        mode: 'cloud',
        aliases: ['openrouter', 'or'],
        authKind: 'api_key',
        credentialRefs: ['OPENROUTER_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'research', 'streaming', 'tool_use', 'vision', 'long_context'],
        modalities: ['text', 'image', 'tool'],
        models: [{ modelId: 'openrouter/auto', label: 'OpenRouter Auto', primary: true }],
        passthroughModels: true,
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'qwen',
    label: 'Qwen via Puter',
    vendorId: 'alibaba',
    providerId: 'qwen',
    providerName: 'qwen',
    source: 'current_constants',
    aliases: ['qwen', 'qw', 'puter', 'pu'],
    website: 'https://puter.com',
    routeKind: 'partner',
    authKind: 'bearer_token',
    capabilities: ['chat', 'coding', 'streaming', 'budget', 'vision'],
    modalities: ['text', 'image'],
    families: [
      {
        familyId: 'qwen',
        label: 'Qwen',
        vendorId: 'alibaba',
        providerIds: ['qwen', 'puter'],
        summary: 'Qwen route exposed through Puter and DashScope-compatible surfaces.',
        defaultModelName: 'qwen3-coder-plus',
        secondaryModelNames: ['qwen3.5-plus', 'qwen-vl'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'streaming', 'budget', 'vision'],
        modalities: ['text', 'image'],
      },
    ],
    routes: [
      {
        routeId: 'qwen',
        label: 'Qwen via Puter',
        vendorId: 'alibaba',
        providerId: 'qwen',
        providerName: 'qwen',
        familyIds: ['qwen'],
        routeKind: 'partner',
        mode: 'cloud',
        aliases: ['qwen', 'qw', 'puter', 'pu'],
        authKind: 'bearer_token',
        credentialRefs: ['PUTER_AUTH_TOKEN'],
        capabilities: ['chat', 'coding', 'streaming', 'budget', 'vision'],
        modalities: ['text', 'image'],
        models: [
          { modelId: 'qwen3-coder-plus', label: 'Qwen3 Coder Plus', primary: true },
          { modelId: 'qwen3.5-plus', label: 'Qwen3.5 Plus' },
          { modelId: 'qwen-vl', label: 'Qwen VL' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'kilo-gateway',
    label: 'Kilo Gateway',
    vendorId: 'kilo',
    providerId: 'kilo-gateway',
    providerName: 'kilo-gateway',
    source: 'current_constants',
    aliases: ['kilo-gateway', 'kg'],
    website: 'https://kilo.ai',
    routeKind: 'aggregator',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'kilo-gateway',
        label: 'Kilo Gateway',
        vendorId: 'kilo',
        providerIds: ['kilo-gateway'],
        summary: 'Aggregator route for Kilo hosted models.',
        defaultModelName: null,
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
        modalities: ['text', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'kilo-gateway',
        label: 'Kilo Gateway',
        vendorId: 'kilo',
        providerId: 'kilo-gateway',
        providerName: 'kilo-gateway',
        familyIds: ['kilo-gateway'],
        routeKind: 'aggregator',
        mode: 'cloud',
        aliases: ['kilo-gateway', 'kg'],
        authKind: 'api_key',
        credentialRefs: ['KILO_GATEWAY_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
        modalities: ['text', 'tool'],
        models: [],
        passthroughModels: true,
      },
    ],
  },
];
