import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

export const CORE_PROVIDER_INTEGRATION_MANIFESTS: ProviderIntegrationManifest[] = [
  {
    schemaVersion: 1,
    id: 'gemini',
    label: 'Gemini',
    vendorId: 'google',
    providerId: 'gemini',
    providerName: 'gemini',
    source: 'current_constants',
    aliases: ['gemini', 'google-ai-studio', 'google'],
    website: 'https://ai.google.dev',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'multimodal', 'long_context', 'agentic'],
    modalities: ['text', 'image', 'tool'],
    families: [
      {
        familyId: 'gemini',
        label: 'Gemini',
        vendorId: 'google',
        providerIds: ['gemini'],
        summary: 'Google AI Studio Gemini models for chat, reasoning and multimodal work.',
        defaultModelName: 'gemini-3.5-flash',
        secondaryModelNames: ['gemini-2.5-flash', 'gemini-2.5-pro'],
        fallbackModelNames: ['gemini-2.5-flash'],
        capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'multimodal', 'long_context', 'agentic'],
        modalities: ['text', 'image', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'gemini',
        label: 'Gemini',
        vendorId: 'google',
        providerId: 'gemini',
        providerName: 'gemini',
        familyIds: ['gemini'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['gemini', 'google-ai-studio', 'google'],
        authKind: 'api_key',
        credentialRefs: ['GEMINI_API_KEY'],
        capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'multimodal', 'long_context', 'agentic'],
        modalities: ['text', 'image', 'tool'],
        models: [
          { modelId: 'gemini-3.5-flash', label: 'Gemini 3.5 Flash', primary: true },
          { modelId: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
          { modelId: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro' },
        ],
      },
      {
        routeId: 'gemini-interactions',
        label: 'Gemini Interactions API',
        vendorId: 'google',
        providerId: 'gemini',
        providerName: 'gemini-interactions',
        familyIds: ['gemini'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['gemini-interactions', 'google-interactions-api', 'interactions-api'],
        authKind: 'api_key',
        credentialRefs: ['GEMINI_INTERACTIONS_API_KEY', 'GEMINI_API_KEY'],
        capabilities: ['chat', 'reasoning', 'streaming', 'vision', 'multimodal', 'long_context', 'tool_use', 'agentic', 'background'],
        modalities: ['text', 'image', 'audio', 'tool'],
        models: [
          { modelId: 'gemini-3.5-flash', label: 'Gemini 3.5 Flash', primary: true },
          { modelId: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
        ],
        fallbackRouteIds: ['gemini'],
        limitations: [
          'Experimental beta route. Disabled by default unless ZAVORTH_GEMINI_INTERACTIONS_ENABLED=true.',
          'For stable production routing, keep using the standard Gemini generateContent provider.',
        ],
      },
      {
        routeId: 'gemini-managed-agent',
        label: 'Gemini Managed Agent',
        vendorId: 'google',
        providerId: 'gemini',
        providerName: 'gemini-managed-agent',
        familyIds: ['gemini'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['gemini-managed-agents', 'google-managed-agent', 'antigravity-managed-agent'],
        authKind: 'api_key',
        credentialRefs: ['GEMINI_INTERACTIONS_API_KEY', 'GEMINI_API_KEY'],
        capabilities: ['coding', 'reasoning', 'research', 'tool_use', 'agentic', 'background'],
        modalities: ['text', 'tool'],
        models: [
          { modelId: 'gemini-3.5-flash', label: 'Gemini 3.5 Flash', primary: true },
        ],
        fallbackRouteIds: ['gemini-interactions', 'gemini'],
        limitations: [
          'Governed execution backend. Never enabled by default.',
          'Requires explicit approval, cost/data limits and ZAVORTH_GEMINI_MANAGED_AGENTS_ENABLED=true.',
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'gemma',
    label: 'Gemma via Gemini API',
    vendorId: 'google',
    providerId: 'gemini',
    providerName: 'gemini',
    source: 'current_constants',
    aliases: ['gemma', 'gemma-via-gemini'],
    website: 'https://ai.google.dev/gemma',
    routeKind: 'alias',
    authKind: 'api_key',
    capabilities: ['chat', 'streaming', 'budget'],
    modalities: ['text'],
    families: [
      {
        familyId: 'gemma',
        label: 'Gemma',
        vendorId: 'google',
        providerIds: ['gemini'],
        summary: 'Gemma hosted through the Gemini API route.',
        defaultModelName: 'gemma-4-31b-it',
        secondaryModelNames: [],
        fallbackModelNames: ['gemini-2.5-flash'],
        capabilities: ['chat', 'streaming', 'budget'],
        modalities: ['text'],
      },
    ],
    routes: [
      {
        routeId: 'gemma',
        label: 'Gemma via Gemini API',
        vendorId: 'google',
        providerId: 'gemini',
        providerName: 'gemini',
        familyIds: ['gemma'],
        routeKind: 'alias',
        mode: 'alias',
        aliases: ['gemma', 'gemma-via-gemini'],
        authKind: 'api_key',
        credentialRefs: ['GEMINI_API_KEY'],
        capabilities: ['chat', 'streaming', 'budget'],
        modalities: ['text'],
        models: [{ modelId: 'gemma-4-31b-it', label: 'Gemma 4 31B IT', primary: true }],
        fallbackRouteIds: ['gemini'],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'openai',
    label: 'OpenAI',
    vendorId: 'openai',
    providerId: 'openai',
    providerName: 'openai',
    source: 'current_constants',
    aliases: ['openai', 'oa'],
    website: 'https://platform.openai.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'vision', 'long_context'],
    modalities: ['text', 'image', 'tool'],
    families: [
      {
        familyId: 'openai',
        label: 'OpenAI',
        vendorId: 'openai',
        providerIds: ['openai'],
        summary: 'OpenAI official API route for general, coding and agentic work.',
        defaultModelName: 'gpt-5.2',
        secondaryModelNames: ['gpt-5.2-mini'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'vision', 'long_context'],
        modalities: ['text', 'image', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'openai',
        label: 'OpenAI',
        vendorId: 'openai',
        providerId: 'openai',
        providerName: 'openai',
        familyIds: ['openai'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['openai', 'oa'],
        authKind: 'api_key',
        credentialRefs: ['OPENAI_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'vision', 'long_context'],
        modalities: ['text', 'image', 'tool'],
        models: [
          { modelId: 'gpt-5.2', label: 'GPT-5.2', primary: true },
          { modelId: 'gpt-5.2-mini', label: 'GPT-5.2 Mini' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'anthropic',
    label: 'Anthropic',
    vendorId: 'anthropic',
    providerId: 'anthropic',
    providerName: 'anthropic',
    source: 'current_constants',
    aliases: ['anthropic', 'claude'],
    website: 'https://console.anthropic.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'long_context'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'claude',
        label: 'Claude',
        vendorId: 'anthropic',
        providerIds: ['anthropic', 'claude'],
        summary: 'Anthropic Claude model family.',
        defaultModelName: 'claude-sonnet-4-5',
        secondaryModelNames: ['claude-opus-4-5'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'long_context'],
        modalities: ['text', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'anthropic',
        label: 'Anthropic API',
        vendorId: 'anthropic',
        providerId: 'anthropic',
        providerName: 'anthropic',
        familyIds: ['claude'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['anthropic', 'claude-api'],
        authKind: 'api_key',
        credentialRefs: ['ANTHROPIC_API_KEY'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'long_context'],
        modalities: ['text', 'tool'],
        models: [
          { modelId: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5', primary: true },
          { modelId: 'claude-opus-4-5', label: 'Claude Opus 4.5' },
        ],
      },
      {
        routeId: 'claude',
        label: 'Claude Code',
        vendorId: 'anthropic',
        providerId: 'claude',
        providerName: 'claude',
        familyIds: ['claude'],
        routeKind: 'partner',
        mode: 'cloud',
        aliases: ['claude', 'cc'],
        authKind: 'oauth',
        credentialRefs: ['CLAUDE_OAUTH_TOKEN'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'long_context'],
        modalities: ['text', 'tool'],
        models: [
          { modelId: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5', primary: true },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'deepseek',
    label: 'DeepSeek',
    vendorId: 'deepseek',
    providerId: 'deepseek',
    providerName: 'deepseek',
    source: 'current_constants',
    aliases: ['deepseek', 'ds'],
    website: 'https://deepseek.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'streaming', 'budget'],
    modalities: ['text'],
    families: [
      {
        familyId: 'deepseek',
        label: 'DeepSeek',
        vendorId: 'deepseek',
        providerIds: ['deepseek'],
        summary: 'DeepSeek OpenAI-compatible route for budget and coding workloads.',
        defaultModelName: 'deepseek-chat',
        secondaryModelNames: ['deepseek-coder'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'streaming', 'budget'],
        modalities: ['text'],
      },
    ],
    routes: [
      {
        routeId: 'deepseek',
        label: 'DeepSeek',
        vendorId: 'deepseek',
        providerId: 'deepseek',
        providerName: 'deepseek',
        familyIds: ['deepseek'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['deepseek', 'ds'],
        authKind: 'api_key',
        credentialRefs: ['DEEPSEEK_API_KEY'],
        capabilities: ['chat', 'coding', 'streaming', 'budget'],
        modalities: ['text'],
        models: [
          { modelId: 'deepseek-chat', label: 'DeepSeek Chat', primary: true },
          { modelId: 'deepseek-coder', label: 'DeepSeek Coder' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'minimax',
    label: 'MiniMax',
    vendorId: 'minimax',
    providerId: 'minimax',
    providerName: 'minimax',
    source: 'current_constants',
    aliases: ['minimax', 'minimax-cn'],
    website: 'https://www.minimaxi.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'streaming'],
    modalities: ['text'],
    families: [
      {
        familyId: 'minimax',
        label: 'MiniMax',
        vendorId: 'minimax',
        providerIds: ['minimax'],
        summary: 'MiniMax coding-oriented OpenAI-compatible route.',
        defaultModelName: 'MiniMax-M2.7',
        secondaryModelNames: ['MiniMax-M2.5'],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'streaming'],
        modalities: ['text'],
      },
    ],
    routes: [
      {
        routeId: 'minimax',
        label: 'MiniMax',
        vendorId: 'minimax',
        providerId: 'minimax',
        providerName: 'minimax',
        familyIds: ['minimax'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['minimax', 'minimax-cn'],
        authKind: 'api_key',
        credentialRefs: ['MINIMAX_API_KEY'],
        capabilities: ['chat', 'coding', 'streaming'],
        modalities: ['text'],
        models: [
          { modelId: 'MiniMax-M2.7', label: 'MiniMax M2.7', primary: true },
          { modelId: 'MiniMax-M2.5', label: 'MiniMax M2.5' },
        ],
      },
    ],
  },
];
