import { AGGREGATOR_PROVIDER_INTEGRATION_MANIFESTS } from './aggregatorProviders.js';
import { CORE_PROVIDER_INTEGRATION_MANIFESTS } from './coreProviders.js';
import { LOCAL_AND_CUSTOM_PROVIDER_INTEGRATION_MANIFESTS } from './localAndCustomProviders.js';
import { LONG_TAIL_PROVIDER_ACTIVATION_MANIFESTS } from './longTailProviderActivationProviders.js';
import { MEDIA_PROVIDER_INTEGRATION_MANIFESTS } from './mediaProviders.js';
import { P0_PROVIDER_ACTIVATION_MANIFESTS } from './p0ProviderActivationProviders.js';
import { ZAVORTH_PROVIDER_CONSISTENCY_PACK_MANIFESTS } from './zavorthProviderCertificationPack.js';
import { ZAVORTH_PROVIDER_CAPABILITY_MANIFESTS } from './zavorthProviderCapabilityProviders.js';

export const DEFAULT_PROVIDER_INTEGRATION_MANIFESTS = [
  ...CORE_PROVIDER_INTEGRATION_MANIFESTS,
  ...AGGREGATOR_PROVIDER_INTEGRATION_MANIFESTS,
  ...LOCAL_AND_CUSTOM_PROVIDER_INTEGRATION_MANIFESTS,
  ...P0_PROVIDER_ACTIVATION_MANIFESTS,
  ...LONG_TAIL_PROVIDER_ACTIVATION_MANIFESTS,
  ...ZAVORTH_PROVIDER_CONSISTENCY_PACK_MANIFESTS,
  ...MEDIA_PROVIDER_INTEGRATION_MANIFESTS,
  ...ZAVORTH_PROVIDER_CAPABILITY_MANIFESTS,
];

export {
  AGGREGATOR_PROVIDER_INTEGRATION_MANIFESTS,
  CORE_PROVIDER_INTEGRATION_MANIFESTS,
  LOCAL_AND_CUSTOM_PROVIDER_INTEGRATION_MANIFESTS,
  LONG_TAIL_PROVIDER_ACTIVATION_MANIFESTS,
  MEDIA_PROVIDER_INTEGRATION_MANIFESTS,
  P0_PROVIDER_ACTIVATION_MANIFESTS,
  ZAVORTH_PROVIDER_CONSISTENCY_PACK_MANIFESTS,
  ZAVORTH_PROVIDER_CAPABILITY_MANIFESTS,
};
