import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

export const LOCAL_AND_CUSTOM_PROVIDER_INTEGRATION_MANIFESTS: ProviderIntegrationManifest[] = [
  {
    schemaVersion: 1,
    id: 'AIGateway',
    label: 'AIGateway',
    vendorId: 'zavorth',
    providerId: 'aigateway',
    providerName: 'AIGateway',
    source: 'current_constants',
    aliases: ['AIGateway', 'ai-gateway', 'zavorth-ai-gateway'],
    website: 'http://127.0.0.1:21128/v1',
    routeKind: 'custom_compatible',
    authKind: 'local_endpoint',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'local'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'AIGateway',
        label: 'AIGateway',
        vendorId: 'zavorth',
        providerIds: ['aigateway'],
        summary: 'Zavorth-owned OpenAI-compatible local/hybrid route.',
        defaultModelName: null,
        secondaryModelNames: [],
        fallbackModelNames: ['openai', 'gemini'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'local'],
        modalities: ['text', 'tool'],
      },
    ],
    routes: [
      {
        routeId: 'AIGateway',
        label: 'AIGateway',
        vendorId: 'zavorth',
        providerId: 'aigateway',
        providerName: 'AIGateway',
        familyIds: ['AIGateway'],
        routeKind: 'custom_compatible',
        mode: 'hybrid',
        aliases: ['AIGateway', 'ai-gateway', 'zavorth-ai-gateway'],
        authKind: 'local_endpoint',
        credentialRefs: ['AIGateway_BASE_URL'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use', 'local'],
        modalities: ['text', 'tool'],
        models: [],
        passthroughModels: true,
        fallbackRouteIds: ['openai', 'gemini'],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'custom-openai-compatible',
    label: 'Custom OpenAI-Compatible',
    vendorId: 'custom',
    providerId: 'custom-openai-compatible',
    providerName: 'custom-openai-compatible',
    source: 'current_constants',
    aliases: ['custom', 'custom_compatible', 'custom-compatible', 'openai-compatible', 'openai-compatible-*'],
    routeKind: 'custom_compatible',
    authKind: 'api_key',
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
    modalities: ['text', 'tool'],
    families: [
      {
        familyId: 'custom-openai-compatible',
        label: 'Custom OpenAI-Compatible',
        vendorId: 'custom',
        providerIds: ['custom-openai-compatible'],
        summary: 'Template manifest for long-tail OpenAI-compatible providers.',
        defaultModelName: null,
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
        modalities: ['text', 'tool'],
        visibility: 'advanced',
      },
    ],
    routes: [
      {
        routeId: 'custom-openai-compatible',
        label: 'Custom OpenAI-Compatible',
        vendorId: 'custom',
        providerId: 'custom-openai-compatible',
        providerName: 'custom-openai-compatible',
        familyIds: ['custom-openai-compatible'],
        routeKind: 'custom_compatible',
        mode: 'cloud',
        aliases: ['custom', 'custom_compatible', 'custom-compatible', 'openai-compatible', 'openai-compatible-*'],
        authKind: 'api_key',
        credentialRefs: ['CUSTOM_OPENAI_COMPATIBLE_API_KEY', 'CUSTOM_OPENAI_COMPATIBLE_BASE_URL'],
        capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
        modalities: ['text', 'tool'],
        models: [],
        passthroughModels: true,
        visibility: 'advanced',
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'ollama',
    label: 'Ollama',
    vendorId: 'ollama',
    providerId: 'ollama',
    providerName: 'ollama',
    source: 'current_constants',
    aliases: ['ollama', 'ollama-local'],
    website: 'https://ollama.com',
    routeKind: 'local_runtime',
    authKind: 'local_endpoint',
    capabilities: ['chat', 'coding', 'streaming', 'local'],
    modalities: ['text'],
    families: [
      {
        familyId: 'ollama',
        label: 'Ollama Local',
        vendorId: 'ollama',
        providerIds: ['ollama'],
        summary: 'Local runtime route for user-managed Ollama models.',
        defaultModelName: null,
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'coding', 'streaming', 'local'],
        modalities: ['text'],
        visibility: 'advanced',
      },
    ],
    routes: [
      {
        routeId: 'ollama',
        label: 'Ollama',
        vendorId: 'ollama',
        providerId: 'ollama',
        providerName: 'ollama',
        familyIds: ['ollama'],
        routeKind: 'local_runtime',
        mode: 'local',
        aliases: ['ollama', 'ollama-local'],
        authKind: 'local_endpoint',
        credentialRefs: ['OLLAMA_BASE_URL'],
        capabilities: ['chat', 'coding', 'streaming', 'local'],
        modalities: ['text'],
        models: [],
        passthroughModels: true,
        visibility: 'advanced',
      },
    ],
  },
];
