// @ts-nocheck
import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

export const MEDIA_PROVIDER_INTEGRATION_MANIFESTS: ProviderIntegrationManifest[] = [
  {
    schemaVersion: 1,
    id: 'deepgram',
    label: 'Deepgram',
    vendorId: 'deepgram',
    providerId: 'deepgram',
    providerName: 'deepgram',
    source: 'current_constants',
    aliases: ['deepgram', 'dg'],
    website: 'https://deepgram.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['audio', 'streaming'],
    modalities: ['audio'],
    families: [
      {
        familyId: 'deepgram',
        label: 'Deepgram Audio',
        vendorId: 'deepgram',
        providerIds: ['deepgram'],
        summary: 'Speech transcription and voice route.',
        defaultModelName: 'nova-2',
        secondaryModelNames: ['nova-2', 'aura-asteria-en'],
        fallbackModelNames: [],
        capabilities: ['audio', 'streaming'],
        modalities: ['audio'],
      },
    ],
    routes: [
      {
        routeId: 'deepgram',
        label: 'Deepgram',
        vendorId: 'deepgram',
        providerId: 'deepgram',
        providerName: 'deepgram',
        familyIds: ['deepgram'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['deepgram', 'dg'],
        authKind: 'api_key',
        credentialRefs: ['DEEPGRAM_API_KEY'],
        capabilities: ['audio', 'streaming'],
        modalities: ['audio'],
        models: [
          { modelId: 'nova-2', label: 'Nova 3', primary: true },
          { modelId: 'nova-2', label: 'Nova 2' },
          { modelId: 'aura-asteria-en', label: 'Aura Asteria EN' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'nanobanana',
    label: 'NanoBanana',
    vendorId: 'nanobanana',
    providerId: 'nanobanana',
    providerName: 'nanobanana',
    source: 'current_constants',
    aliases: ['nanobanana', 'nb'],
    website: 'https://nanobananaapi.ai',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['vision', 'multimodal'],
    modalities: ['image'],
    families: [
      {
        familyId: 'nanobanana',
        label: 'NanoBanana Image',
        vendorId: 'nanobanana',
        providerIds: ['nanobanana'],
        summary: 'Image generation and image editing route.',
        defaultModelName: 'nanobanana-flash',
        secondaryModelNames: ['nanobanana-pro'],
        fallbackModelNames: [],
        capabilities: ['vision', 'multimodal'],
        modalities: ['image'],
      },
    ],
    routes: [
      {
        routeId: 'nanobanana',
        label: 'NanoBanana',
        vendorId: 'nanobanana',
        providerId: 'nanobanana',
        providerName: 'nanobanana',
        familyIds: ['nanobanana'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['nanobanana', 'nb'],
        authKind: 'api_key',
        credentialRefs: ['NANOBANANA_API_KEY'],
        capabilities: ['vision', 'multimodal'],
        modalities: ['image'],
        models: [
          { modelId: 'nanobanana-flash', label: 'NanoBanana Flash', primary: true },
          { modelId: 'nanobanana-pro', label: 'NanoBanana Pro' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'assemblyai',
    label: 'AssemblyAI',
    vendorId: 'assemblyai',
    providerId: 'assemblyai',
    providerName: 'assemblyai',
    source: 'current_constants',
    aliases: ['assemblyai', 'aai'],
    website: 'https://assemblyai.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['audio', 'streaming'],
    modalities: ['audio'],
    families: [
      {
        familyId: 'assemblyai',
        label: 'AssemblyAI Audio',
        vendorId: 'assemblyai',
        providerIds: ['assemblyai'],
        summary: 'Speech transcription route via AssemblyAI.',
        defaultModelName: 'best',
        secondaryModelNames: ['nano', 'universal-streaming'],
        fallbackModelNames: [],
        capabilities: ['audio', 'streaming'],
        modalities: ['audio'],
      },
    ],
    routes: [
      {
        routeId: 'assemblyai',
        label: 'AssemblyAI',
        vendorId: 'assemblyai',
        providerId: 'assemblyai',
        providerName: 'assemblyai',
        familyIds: ['assemblyai'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['assemblyai', 'aai'],
        authKind: 'api_key',
        credentialRefs: ['ASSEMBLYAI_API_KEY'],
        capabilities: ['audio', 'streaming'],
        modalities: ['audio'],
        models: [
          { modelId: 'best', label: 'Best', primary: true },
          { modelId: 'nano', label: 'Nano' },
          { modelId: 'universal-streaming', label: 'Universal Streaming' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'elevenlabs',
    label: 'ElevenLabs',
    vendorId: 'elevenlabs',
    providerId: 'elevenlabs',
    providerName: 'elevenlabs',
    source: 'current_constants',
    aliases: ['elevenlabs', 'el'],
    website: 'https://elevenlabs.io',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['tts', 'audio', 'streaming'],
    modalities: ['audio'],
    families: [
      {
        familyId: 'elevenlabs',
        label: 'ElevenLabs TTS',
        vendorId: 'elevenlabs',
        providerIds: ['elevenlabs'],
        summary: 'Text-to-speech and voice generation route.',
        defaultModelName: 'eleven_multilingual_v2',
        secondaryModelNames: ['eleven_flash_v2_5', 'scribe_v1'],
        fallbackModelNames: [],
        capabilities: ['tts', 'audio', 'streaming'],
        modalities: ['audio'],
      },
    ],
    routes: [
      {
        routeId: 'elevenlabs',
        label: 'ElevenLabs',
        vendorId: 'elevenlabs',
        providerId: 'elevenlabs',
        providerName: 'elevenlabs',
        familyIds: ['elevenlabs'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['elevenlabs', 'el'],
        authKind: 'api_key',
        credentialRefs: ['ELEVENLABS_API_KEY', 'XI_API_KEY'],
        capabilities: ['tts', 'audio', 'streaming'],
        modalities: ['audio'],
        models: [
          { modelId: 'eleven_multilingual_v2', label: 'Multilingual v2', primary: true },
          { modelId: 'eleven_flash_v2_5', label: 'Flash v2.5' },
          { modelId: 'scribe_v1', label: 'Scribe v1 (Transcription)' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'huggingface',
    label: 'HuggingFace',
    vendorId: 'huggingface',
    providerId: 'huggingface',
    providerName: 'huggingface',
    source: 'current_constants',
    aliases: ['huggingface', 'hf'],
    website: 'https://huggingface.co',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['chat', 'embedding', 'audio', 'streaming'],
    modalities: ['text', 'audio', 'embedding'],
    families: [
      {
        familyId: 'huggingface',
        label: 'HuggingFace Inference',
        vendorId: 'huggingface',
        providerIds: ['huggingface'],
        summary: 'HuggingFace Inference API for open models (LLM, Whisper, embeddings).',
        defaultModelName: 'meta-llama/Llama-3.1-8B-Instruct',
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['chat', 'embedding', 'audio', 'streaming'],
        modalities: ['text', 'audio', 'embedding'],
      },
    ],
    routes: [
      {
        routeId: 'huggingface',
        label: 'HuggingFace Inference',
        vendorId: 'huggingface',
        providerId: 'huggingface',
        providerName: 'huggingface',
        familyIds: ['huggingface'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['huggingface', 'hf'],
        authKind: 'api_key',
        credentialRefs: ['HUGGINGFACE_API_KEY', 'HF_TOKEN'],
        capabilities: ['chat', 'embedding', 'audio', 'streaming'],
        modalities: ['text', 'audio', 'embedding'],
        models: [
          { modelId: 'meta-llama/Llama-3.1-8B-Instruct', label: 'Llama 3.1 8B Instruct', primary: true },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'cartesia',
    label: 'Cartesia',
    vendorId: 'cartesia',
    providerId: 'cartesia',
    providerName: 'cartesia',
    source: 'current_constants',
    aliases: ['cartesia'],
    website: 'https://cartesia.ai',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['tts', 'audio', 'streaming'],
    modalities: ['audio'],
    families: [
      {
        familyId: 'cartesia',
        label: 'Cartesia TTS',
        vendorId: 'cartesia',
        providerIds: ['cartesia'],
        summary: 'Real-time text-to-speech with low latency.',
        defaultModelName: 'cartesia-tts',
        secondaryModelNames: [],
        fallbackModelNames: [],
        capabilities: ['tts', 'audio', 'streaming'],
        modalities: ['audio'],
      },
    ],
    routes: [
      {
        routeId: 'cartesia',
        label: 'Cartesia TTS',
        vendorId: 'cartesia',
        providerId: 'cartesia',
        providerName: 'cartesia',
        familyIds: ['cartesia'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['cartesia'],
        authKind: 'api_key',
        credentialRefs: ['CARTESIA_API_KEY'],
        capabilities: ['tts', 'audio', 'streaming'],
        modalities: ['audio'],
        models: [
          { modelId: 'cartesia-tts', label: 'Cartesia TTS', primary: true },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'playht',
    label: 'PlayHT',
    vendorId: 'playht',
    providerId: 'playht',
    providerName: 'playht',
    source: 'current_constants',
    aliases: ['playht'],
    website: 'https://play.ht',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['tts', 'audio', 'streaming'],
    modalities: ['audio'],
    families: [
      {
        familyId: 'playht',
        label: 'PlayHT TTS',
        vendorId: 'playht',
        providerIds: ['playht'],
        summary: 'Text-to-speech with voice cloning.',
        defaultModelName: 'playht-2.0-turbo',
        secondaryModelNames: ['playht-1.0-turbo'],
        fallbackModelNames: [],
        capabilities: ['tts', 'audio', 'streaming'],
        modalities: ['audio'],
      },
    ],
    routes: [
      {
        routeId: 'playht',
        label: 'PlayHT TTS',
        vendorId: 'playht',
        providerId: 'playht',
        providerName: 'playht',
        familyIds: ['playht'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['playht'],
        authKind: 'api_key',
        credentialRefs: ['PLAYHT_API_KEY', 'PLAYHT_USER_ID'],
        capabilities: ['tts', 'audio', 'streaming'],
        modalities: ['audio'],
        models: [
          { modelId: 'playht-2.0-turbo', label: 'PlayHT 2.0 Turbo', primary: true },
        ],
      },
    ],
  },
];
