import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

export const MEDIA_PROVIDER_INTEGRATION_MANIFESTS: ProviderIntegrationManifest[] = [
  {
    schemaVersion: 1,
    id: 'deepgram',
    label: 'Deepgram',
    vendorId: 'deepgram',
    providerId: 'deepgram',
    providerName: 'deepgram',
    source: 'current_constants',
    aliases: ['deepgram', 'dg'],
    website: 'https://deepgram.com',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['audio', 'streaming'],
    modalities: ['audio'],
    families: [
      {
        familyId: 'deepgram',
        label: 'Deepgram Audio',
        vendorId: 'deepgram',
        providerIds: ['deepgram'],
        summary: 'Speech transcription and voice route.',
        defaultModelName: 'nova-2',
        secondaryModelNames: ['nova-2', 'aura-asteria-en'],
        fallbackModelNames: [],
        capabilities: ['audio', 'streaming'],
        modalities: ['audio'],
      },
    ],
    routes: [
      {
        routeId: 'deepgram',
        label: 'Deepgram',
        vendorId: 'deepgram',
        providerId: 'deepgram',
        providerName: 'deepgram',
        familyIds: ['deepgram'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['deepgram', 'dg'],
        authKind: 'api_key',
        credentialRefs: ['DEEPGRAM_API_KEY'],
        capabilities: ['audio', 'streaming'],
        modalities: ['audio'],
        models: [
          { modelId: 'nova-2', label: 'Nova 3', primary: true },
          { modelId: 'nova-2', label: 'Nova 2' },
          { modelId: 'aura-asteria-en', label: 'Aura Asteria EN' },
        ],
      },
    ],
  },
  {
    schemaVersion: 1,
    id: 'nanobanana',
    label: 'NanoBanana',
    vendorId: 'nanobanana',
    providerId: 'nanobanana',
    providerName: 'nanobanana',
    source: 'current_constants',
    aliases: ['nanobanana', 'nb'],
    website: 'https://nanobananaapi.ai',
    routeKind: 'official',
    authKind: 'api_key',
    capabilities: ['vision', 'multimodal'],
    modalities: ['image'],
    families: [
      {
        familyId: 'nanobanana',
        label: 'NanoBanana Image',
        vendorId: 'nanobanana',
        providerIds: ['nanobanana'],
        summary: 'Image generation and image editing route.',
        defaultModelName: 'nanobanana-flash',
        secondaryModelNames: ['nanobanana-pro'],
        fallbackModelNames: [],
        capabilities: ['vision', 'multimodal'],
        modalities: ['image'],
      },
    ],
    routes: [
      {
        routeId: 'nanobanana',
        label: 'NanoBanana',
        vendorId: 'nanobanana',
        providerId: 'nanobanana',
        providerName: 'nanobanana',
        familyIds: ['nanobanana'],
        routeKind: 'official',
        mode: 'cloud',
        aliases: ['nanobanana', 'nb'],
        authKind: 'api_key',
        credentialRefs: ['NANOBANANA_API_KEY'],
        capabilities: ['vision', 'multimodal'],
        modalities: ['image'],
        models: [
          { modelId: 'nanobanana-flash', label: 'NanoBanana Flash', primary: true },
          { modelId: 'nanobanana-pro', label: 'NanoBanana Pro' },
        ],
      },
    ],
  },
];
