// @ts-nocheck
import type { ProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';
import { createMinimalProviderIntegrationManifest } from '../ProviderIntegrationManifest.js';

type ConsistencyRoute = {
  id: string;
  label: string;
  defaultModelName: string;
  website: string;
  aliases?: string[];
  authKind?: 'api_key' | 'oauth' | 'local_endpoint' | 'custom';
  mode?: 'cloud' | 'local' | 'hybrid';
  credentialRefs?: string[];
};

const CONSISTENCY_ROUTES: ConsistencyRoute[] = [
  {
    id: 'alibaba-coding-plan',
    label: 'Alibaba Coding Plan',
    defaultModelName: 'qwen-coder-plus',
    website: 'https://dashscope.aliyun.com',
    aliases: ['dashscope-coding-plan', 'qwen-coding-plan'],
  },
  {
    id: 'azure-foundry',
    label: 'Azure AI Foundry',
    defaultModelName: 'gpt-4o',
    website: 'https://ai.azure.com',
    aliases: ['azure-ai-foundry', 'microsoft-foundry-ai'],
    credentialRefs: ['AZURE_FOUNDRY_API_KEY', 'AZURE_FOUNDRY_BASE_URL', 'AZURE_AI_FOUNDRY_API_KEY', 'AZURE_AI_FOUNDRY_BASE_URL'],
  },
  {
    id: 'bedrock',
    label: 'AWS Bedrock',
    defaultModelName: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    website: 'https://aws.amazon.com/bedrock',
    aliases: ['aws-bedrock', 'amazon-bedrock'],
    credentialRefs: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION', 'BEDROCK_BASE_URL'],
  },
  {
    id: 'copilot',
    label: 'GitHub Copilot',
    defaultModelName: 'gpt-4o',
    website: 'https://github.com/features/copilot',
    aliases: ['github-copilot'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['GITHUB_COPILOT_OAUTH_TOKEN', 'COPILOT_API_KEY', 'COPILOT_BASE_URL'],
  },
  {
    id: 'copilot-acp',
    label: 'GitHub Copilot ACP',
    defaultModelName: 'copilot-acp',
    website: 'https://github.com/features/copilot',
    aliases: ['github-copilot-acp', 'copilot-agent-client-protocol'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['COPILOT_ACP_BASE_URL', 'COPILOT_ACP_COMMAND', 'GITHUB_COPILOT_OAUTH_TOKEN'],
  },
  {
    id: 'codex',
    label: 'Codex App Server',
    defaultModelName: 'gpt-4o-codex',
    website: 'https://openai.com/codex',
    aliases: ['codex-app-server', 'codex-cli-provider', 'openai-codex-app-server'],
    authKind: 'custom',
    mode: 'hybrid',
    credentialRefs: ['CODEX_HOME', 'CODEX_APP_SERVER_URL', 'CODEX_API_KEY', 'OPENAI_API_KEY'],
  },
  {
    id: 'bedrock-mantle',
    label: 'AWS Bedrock Mantle',
    defaultModelName: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    website: 'https://aws.amazon.com/bedrock',
    aliases: ['amazon-bedrock-mantle', 'aws-bedrock-mantle'],
    mode: 'hybrid',
    credentialRefs: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION', 'BEDROCK_MANTLE_BASE_URL'],
  },
  {
    id: 'claude-max-api-proxy',
    label: 'Claude Max API Proxy',
    defaultModelName: 'claude-sonnet-4',
    website: 'https://www.npmjs.com/package/claude-max-api-proxy',
    aliases: ['claude-max-proxy', 'claude-subscription-proxy'],
    authKind: 'local_endpoint',
    mode: 'local',
    credentialRefs: ['CLAUDE_MAX_API_PROXY_BASE_URL', 'CLAUDE_MAX_API_PROXY_API_KEY'],
  },
  {
    id: 'ds4',
    label: 'ds4 Local DeepSeek',
    defaultModelName: 'deepseek-v4-flash',
    website: 'https://github.com/antirez/ds4',
    aliases: ['deepseek-v4-flash-local', 'ds4-server'],
    authKind: 'local_endpoint',
    mode: 'local',
    credentialRefs: ['DS4_BASE_URL', 'DS4_API_KEY', 'DS4_COMMAND'],
  },
  {
    id: 'inferrs',
    label: 'Inferrs Local Runtime',
    defaultModelName: 'google/gemma-4-E2B-it',
    website: 'https://github.com/ericcurtin/inferrs',
    aliases: ['inferrs-local', 'inferrs-server'],
    authKind: 'local_endpoint',
    mode: 'local',
    credentialRefs: ['INFERRS_BASE_URL', 'INFERRS_API_KEY', 'INFERRS_COMMAND'],
  },
  {
    id: 'perplexity-provider',
    label: 'Perplexity Provider',
    defaultModelName: 'sonar-pro',
    website: 'https://www.perplexity.ai',
    aliases: ['perplexity', 'perplexity-ai', 'sonar'],
    credentialRefs: ['PERPLEXITY_API_KEY', 'PERPLEXITY_BASE_URL'],
  },
  {
    id: 'synthetic',
    label: 'Synthetic',
    defaultModelName: 'hf:MiniMaxAI/MiniMax-M2.5',
    website: 'https://synthetic.new',
    aliases: ['synthetic-new', 'synthetic-anthropic'],
    credentialRefs: ['SYNTHETIC_API_KEY', 'SYNTHETIC_BASE_URL'],
  },
  {
    id: 'gmi',
    label: 'GMI Cloud',
    defaultModelName: 'auto',
    website: 'https://www.gmicloud.ai',
    aliases: ['gmi-cloud'],
  },
  {
    id: 'nous',
    label: 'Nous Portal',
    defaultModelName: 'auto',
    website: 'https://portal.nousresearch.com',
    aliases: ['nous-portal'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['NOUS_API_KEY', 'NOUS_OAUTH_TOKEN', 'NOUS_BASE_URL'],
  },
  {
    id: 'ollama-cloud',
    label: 'Ollama Cloud',
    defaultModelName: 'gpt-oss:20b',
    website: 'https://ollama.com',
    aliases: ['ollama-hosted', 'ollama-cloud-compatible'],
    credentialRefs: ['OLLAMA_CLOUD_API_KEY', 'OLLAMA_CLOUD_BASE_URL'],
  },
  {
    id: 'opencode-zen',
    label: 'OpenCode Zen',
    defaultModelName: 'opencode/minimax-m2.5-free',
    website: 'https://opencode.ai',
    aliases: ['opencodezen', 'opencode-zen-gateway'],
    credentialRefs: ['OPENCODE_ZEN_API_KEY', 'OPENCODE_ZEN_BASE_URL'],
  },
  {
    id: 'qwen-oauth',
    label: 'Qwen OAuth',
    defaultModelName: 'qwen3-coder-plus',
    website: 'https://chat.qwen.ai',
    aliases: ['qwen-cli-oauth', 'qwen-auth'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['QWEN_OAUTH_TOKEN', 'QWEN_OAUTH_CREDS_PATH', 'QWEN_BASE_URL'],
  },
  {
    id: 'google-gemini-cli',
    label: 'Google Gemini CLI OAuth',
    defaultModelName: 'gemini-2.5-flash',
    website: 'https://ai.google.dev/gemini-api/docs/cli',
    aliases: ['gemini-cli-oauth', 'google-gemini-oauth'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['GOOGLE_GEMINI_CLI_OAUTH_TOKEN', 'GEMINI_CLI_OAUTH_TOKEN', 'GEMINI_API_KEY'],
  },
  {
    id: 'kimi-coding-cn',
    label: 'Kimi Coding China',
    defaultModelName: 'kimi-k2.5',
    website: 'https://platform.moonshot.cn',
    aliases: ['moonshot-cn', 'kimi-cn'],
    credentialRefs: ['KIMI_CN_API_KEY', 'KIMI_CN_BASE_URL', 'MOONSHOT_CN_API_KEY', 'MOONSHOT_CN_BASE_URL'],
  },
  {
    id: 'minimax-cn',
    label: 'MiniMax China',
    defaultModelName: 'minimax-m2',
    website: 'https://platform.minimaxi.com',
    aliases: ['minimax-china'],
    credentialRefs: ['MINIMAX_CN_API_KEY', 'MINIMAX_CN_BASE_URL'],
  },
  {
    id: 'minimax-oauth',
    label: 'MiniMax OAuth',
    defaultModelName: 'minimax-m2',
    website: 'https://www.minimax.io',
    aliases: ['minimax-auth'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['MINIMAX_OAUTH_TOKEN', 'MINIMAX_API_KEY'],
  },
  {
    id: 'cursor',
    label: 'Cursor IDE',
    defaultModelName: 'auto',
    website: 'https://cursor.sh',
    aliases: ['cursor-ide', 'cursor-agent'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['CURSOR_OAUTH_TOKEN', 'CURSOR_API_KEY'],
  },
  {
    id: 'cline',
    label: 'Cline',
    defaultModelName: 'auto',
    website: 'https://cline.bot',
    aliases: ['cline-agent'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['CLINE_API_KEY', 'CLINE_OAUTH_TOKEN'],
  },
  {
    id: 'deepinfra',
    label: 'DeepInfra',
    defaultModelName: 'deepseek-ai/DeepSeek-V3.2',
    website: 'https://deepinfra.com',
    aliases: ['deep-infra'],
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    defaultModelName: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    website: 'https://fireworks.ai',
    aliases: ['fireworks-ai'],
  },
  {
    id: 'glm',
    label: 'GLM Coding (Zhipu)',
    defaultModelName: 'glm-4-plus',
    website: 'https://open.bigmodel.cn',
    aliases: ['zhipu-glm', 'bigmodel'],
  },
  {
    id: 'kimi',
    label: 'Kimi (Moonshot)',
    defaultModelName: 'moonshot-v1-128k',
    website: 'https://kimi.moonshot.cn',
    aliases: ['moonshot-kimi'],
  },
  {
    id: 'kimi-coding-apikey',
    label: 'Kimi Coding (API Key)',
    defaultModelName: 'kimi-k2-0711-preview',
    website: 'https://kimi.com',
    aliases: ['kimi-coding-key'],
  },
  {
    id: 'alicode',
    label: 'Alibaba Bailian',
    defaultModelName: 'qwen-plus',
    website: 'https://bailian.console.aliyun.com',
    aliases: ['alibaba-bailian', 'bailian'],
  },
  {
    id: 'alicode-intl',
    label: 'Alibaba Bailian Intl',
    defaultModelName: 'qwen-plus',
    website: 'https://modelstudio.console.alibabacloud.com',
    aliases: ['alibaba-intl', 'dashscope-intl'],
  },
  {
    id: 'blackbox',
    label: 'Blackbox AI',
    defaultModelName: 'auto',
    website: 'https://blackbox.ai',
    aliases: ['blackbox-ai'],
  },
  {
    id: 'nebius',
    label: 'Nebius AI',
    defaultModelName: 'auto',
    website: 'https://nebius.com',
    aliases: ['nebius-studio'],
  },
  {
    id: 'siliconflow',
    label: 'SiliconFlow',
    defaultModelName: 'auto',
    website: 'https://cloud.siliconflow.com',
    aliases: ['sf-cloud'],
  },
  {
    id: 'hyperbolic',
    label: 'Hyperbolic',
    defaultModelName: 'auto',
    website: 'https://hyperbolic.xyz',
    aliases: ['hyperbolic-labs'],
  },
  {
    id: 'qoder',
    label: 'Qoder AI',
    defaultModelName: 'auto',
    website: 'https://qoder.ai',
    aliases: ['qoder-ai'],
    credentialRefs: ['QODER_API_KEY'],
  },
  {
    id: 'qwen',
    label: 'Qwen Code',
    defaultModelName: 'qwen3-coder-plus',
    website: 'https://qwen.ai',
    aliases: ['qwen-code', 'qwen-chat'],
    authKind: 'oauth',
    mode: 'hybrid',
    credentialRefs: ['QWEN_OAUTH_TOKEN'],
  },
  {
    id: 'kiro',
    label: 'Kiro AI',
    defaultModelName: 'auto',
    website: 'https://kiro.dev',
    aliases: ['kiro-ai'],
  },
  {
    id: 'longcat',
    label: 'LongCat AI',
    defaultModelName: 'auto',
    website: 'https://longcat.chat',
    aliases: ['longcat-chat'],
  },
  {
    id: 'pollinations',
    label: 'Pollinations AI',
    defaultModelName: 'auto',
    website: 'https://pollinations.ai',
    aliases: ['pollinations-ai'],
  },
  {
    id: 'aimlapi',
    label: 'AI/ML API',
    defaultModelName: 'auto',
    website: 'https://aimlapi.com',
    aliases: ['ai-ml-api'],
    passthroughModels: true,
  },
  {
    id: 'novita',
    label: 'Novita AI',
    defaultModelName: 'auto',
    website: 'https://novita.ai',
    aliases: ['novita-ai'],
    passthroughModels: true,
  },
  {
    id: 'piapi',
    label: 'PiAPI',
    defaultModelName: 'auto',
    website: 'https://piapi.ai',
    aliases: ['pi-api'],
    passthroughModels: true,
  },
  {
    id: 'getgoapi',
    label: 'GoAPI',
    defaultModelName: 'auto',
    website: 'https://api.getgoapi.com',
    aliases: ['go-api'],
    passthroughModels: true,
  },
  {
    id: 'laozhang',
    label: 'LaoZhang AI',
    defaultModelName: 'auto',
    website: 'https://api.laozhang.ai',
    aliases: ['laozhang-ai'],
    passthroughModels: true,
  },
  {
    id: 'puter',
    label: 'Puter AI',
    defaultModelName: 'auto',
    website: 'https://puter.com',
    aliases: ['puter-ai'],
    authKind: 'bearer_token',
    credentialRefs: ['PUTER_AUTH_TOKEN'],
    passthroughModels: true,
  },
  {
    id: 'scaleway',
    label: 'Scaleway AI',
    defaultModelName: 'auto',
    website: 'https://www.scaleway.com',
    aliases: ['scaleway-cloud'],
    credentialRefs: ['SCALEWAY_API_KEY'],
  },
  {
    id: 'cloudflare-ai',
    label: 'Cloudflare Workers AI',
    defaultModelName: 'auto',
    website: 'https://developers.cloudflare.com/workers-ai/',
    aliases: ['cf-workers-ai', 'cloudflare'],
    credentialRefs: ['CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID'],
  },
  {
    id: 'vertex',
    label: 'Google Vertex AI',
    defaultModelName: 'auto',
    website: 'https://cloud.google.com/vertex-ai',
    aliases: ['google-vertex'],
    credentialRefs: ['GOOGLE_APPLICATION_CREDENTIALS', 'VERTEX_AI_ACCESS_TOKEN'],
  },
  {
    id: 'perplexity-search',
    label: 'Perplexity Search',
    defaultModelName: 'sonar-pro',
    website: 'https://docs.perplexity.ai',
    aliases: ['pplx-search'],
    credentialRefs: ['PERPLEXITY_API_KEY'],
  },
  {
    id: 'serper-search',
    label: 'Serper Search',
    defaultModelName: 'auto',
    website: 'https://serper.dev',
    aliases: ['google-serper'],
    credentialRefs: ['SERPER_API_KEY'],
  },
  {
    id: 'brave-search',
    label: 'Brave Search',
    defaultModelName: 'auto',
    website: 'https://brave.com/search/api',
    aliases: ['brave-api'],
    credentialRefs: ['BRAVE_SEARCH_API_KEY'],
  },
  {
    id: 'exa-search',
    label: 'Exa Search',
    defaultModelName: 'auto',
    website: 'https://exa.ai',
    aliases: ['exa-ai'],
    credentialRefs: ['EXA_API_KEY'],
  },
  {
    id: 'tavily-search',
    label: 'Tavily Search',
    defaultModelName: 'auto',
    website: 'https://tavily.com',
    aliases: ['tavily-ai'],
    credentialRefs: ['TAVILY_API_KEY'],
  },
];

export const ZAVORTH_PROVIDER_CONSISTENCY_PACK_MANIFESTS: ProviderIntegrationManifest[] =
  CONSISTENCY_ROUTES.map(toManifest);

function toManifest(route: ConsistencyRoute): ProviderIntegrationManifest {
  const manifest = createMinimalProviderIntegrationManifest({
    id: route.id,
    label: route.label,
    vendorId: route.id,
    providerId: route.id,
    providerName: route.id,
    aliases: [route.id, ...(route.aliases || [])],
    website: route.website,
    routeKind: route.mode === 'local' ? 'local_runtime' : 'custom_compatible',
    mode: route.mode || 'cloud',
    authKind: route.authKind || 'api_key',
    credentialRefs: route.credentialRefs || [`${envPrefix(route.id)}_API_KEY`, `${envPrefix(route.id)}_BASE_URL`],
    capabilities: ['chat', 'coding', 'reasoning', 'streaming', 'tool_use'],
    modalities: ['text', 'tool'],
    defaultModelName: route.defaultModelName,
    source: 'curated',
  });

  return {
    ...manifest,
    notes: [
      'Zavorth provider readiness pack route. Catalog visibility does not imply live execution.',
      'Activation still requires credentials, compatible endpoint or typed adapter, and explicit live proof.',
    ],
    routes: manifest.routes.map((entry) => ({
      ...entry,
      limitations: [
        'Not enabled for default routing until readiness and live proof pass.',
        'OAuth and ACP-flavored routes require owner-configured local credentials or adapter commands.',
      ],
    })),
  };
}

function envPrefix(value: string): string {
  return value.toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}
