import type { IntegrationManifest } from '../../../../contracts/IntegrationHubContract.js';
import { choice, commonCapabilityQuestion, mode, question, req, step } from './IntegrationRegistryCatalogShared.js';

export const INTEGRATION_AGENT_CONNECTOR_MANIFESTS: IntegrationManifest[] = [
  {
    id: 'composio',
    label: 'Composio',
    aliases: ['composio-tools', 'composio-mcp', 'tool-broker'],
    summary: 'Native connector for exposing toolkits and external actions to the agent under Zavorth governance.',
    description: 'Uses Zavorth Connector Mesh to discover toolkits and run external tools only through preview, approval, and receipt flows.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'tools', 'agents', 'oauth'],
    modes: [mode('api', 'Remote API', 'Uses COMPOSIO_API_KEY and the Composio HTTP API.')],
    defaultMode: 'api',
    capabilities: ['agents', 'automation', 'search'],
    binding: {
      kind: 'service',
      key: 'composio',
      status: 'ready',
      summary: 'Native Connector Mesh adapter; external execution is approval-gated.',
    },
    requirements: [
      req('composio_api_key', 'Composio API key', 'Key used to list toolkits and run external tools.', {
        type: 'env',
        secret: true,
        envKey: 'COMPOSIO_API_KEY',
      }),
      req('composio_base_url', 'Composio base URL', 'Optional; defaults to https://backend.composio.dev.', {
        type: 'env',
        envKey: 'COMPOSIO_BASE_URL',
        required: false,
      }),
    ],
    onboardingQuestions: [
      question('composio_api_key', 'What is the Composio API key...', 'secret', 'Paste the workspace or project key Zavorth can use.'),
      question('composio_base_url', 'Use a custom base URL...', 'text', 'Optional; leave empty for the default endpoint.', {
        required: false,
        placeholder: 'https://backend.composio.dev',
      }),
      commonCapabilityQuestion,
    ],
    installSteps: [
      step('scope', 'Define tool scope', 'Choose which apps or toolkits the agent can see first.', 'guided'),
      step('credential', 'Add COMPOSIO_API_KEY', 'Configure the key in a local .env file or secret manager.', 'manual', 'COMPOSIO_API_KEY=...'),
      step('doctor', 'Run connector doctor', 'Validate toolkit catalog readiness without running external actions.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=composio'),
    ],
    safetyNotes: [
      'External tools can mutate third-party systems; real execution goes through Action Harness and approval.',
      'The doctor reports readiness and never serializes secrets.',
    ],
    goodFor: ['External tool calling', 'App OAuth', 'Real actions with approval'],
  },
  {
    id: 'nango',
    label: 'Nango',
    aliases: ['nango-auth', 'oauth-broker', 'connection-broker'],
    summary: 'Native connector for OAuth, connections, and renewable credentials for external APIs.',
    description: 'Uses Connector Mesh to validate Nango connections and let the agent use authorized integrations without handling raw tokens.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'oauth', 'connections', 'proxy'],
    modes: [mode('api', 'Remote API', 'Uses NANGO_SECRET_KEY and the Nango HTTP API.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: {
      kind: 'service',
      key: 'nango',
      status: 'ready',
      summary: 'Native Connector Mesh adapter for OAuth and API connections.',
    },
    requirements: [
      req('nango_secret_key', 'Nango secret key', 'Minimum-scope key for listing connections without exposing credentials.', {
        type: 'env',
        secret: true,
        envKey: 'NANGO_SECRET_KEY',
      }),
      req('nango_base_url', 'Nango base URL', 'Optional; defaults to https://api.nango.dev.', {
        type: 'env',
        envKey: 'NANGO_BASE_URL',
        required: false,
      }),
      req('nango_action_execute_url', 'Nango action execute URL', 'Allowed proxy/action endpoint for governed execution when used.', {
        type: 'env',
        envKey: 'NANGO_ACTION_EXECUTE_URL',
        required: false,
      }),
    ],
    onboardingQuestions: [
      question('nango_secret_key', 'What is the Nango secret key...', 'secret', 'Use a minimum-scope key for the Zavorth environment.'),
      question('nango_base_url', 'Use self-hosted Nango or a custom URL...', 'text', 'Optional; leave empty for Nango Cloud.', {
        required: false,
        placeholder: 'https://api.nango.dev',
      }),
      question('nango_action_execute_url', 'Which Nango action/proxy endpoint can Zavorth execute...', 'text', 'Optional; used only with preview, approval, and receipt.', {
        required: false,
      }),
      commonCapabilityQuestion,
    ],
    installSteps: [
      step('scope', 'Define allowed connections', 'Choose which provider_config_keys the agent can use.', 'guided'),
      step('credential', 'Add NANGO_SECRET_KEY', 'Configure the key in a local .env file or secret manager.', 'manual', 'NANGO_SECRET_KEY=...'),
      step('execute-url', 'Add NANGO_ACTION_EXECUTE_URL', 'Optional; enables a governed action/proxy route.', 'manual', 'NANGO_ACTION_EXECUTE_URL=https://...'),
      step('doctor', 'Run connector doctor', 'Validate Nango connections without exposing credentials.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=nango'),
    ],
    safetyNotes: [
      'OAuth tokens stay in Nango or secure storage; the LLM never receives raw secrets.',
      'Nango proxy/action routes must be allowlisted by policy before execution.',
    ],
    goodFor: ['OAuth', 'User connections', 'External APIs with refresh tokens'],
  },
  {
    id: 'pipedream',
    label: 'Pipedream',
    aliases: ['pipedream-workflows', 'event-workflows'],
    summary: 'Governed connector for workflows and external actions through Pipedream.',
    description: 'Zavorth records readiness and can use a health URL or adapter endpoint to operate workflows with approval.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'workflows', 'automation'],
    modes: [mode('api', 'Configured API/endpoint', 'Uses PIPEDREAM_API_KEY, PIPEDREAM_HEALTH_URL, and PIPEDREAM_EXECUTE_URL when available.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'pipedream', status: 'ready', summary: 'Governed adapter through health URL or configured MCP/endpoint.' },
    requirements: [
      req('pipedream_api_key', 'Pipedream API key', 'Pipedream workspace key.', { type: 'env', secret: true, envKey: 'PIPEDREAM_API_KEY' }),
      req('pipedream_health_url', 'Health URL', 'Safe endpoint for live workspace doctor checks.', { type: 'env', envKey: 'PIPEDREAM_HEALTH_URL', required: false }),
      req('pipedream_execute_url', 'Execute URL', 'Allowed endpoint or workflow for governed execution.', { type: 'env', envKey: 'PIPEDREAM_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('pipedream_api_key', 'What is the Pipedream API key...', 'secret', 'Use a minimum-scope key.'),
      question('pipedream_health_url', 'Which health URL should Zavorth test...', 'text', 'Optional; enables live doctor checks without assuming a proprietary endpoint.', { required: false }),
      question('pipedream_execute_url', 'Which execute URL can Zavorth call...', 'text', 'Optional; used only with preview, approval, and receipt.', { required: false }),
    ],
    installSteps: [
      step('credential', 'Add PIPEDREAM_API_KEY', 'Configure the key in a secure location.', 'manual', 'PIPEDREAM_API_KEY=...'),
      step('execute-url', 'Add PIPEDREAM_EXECUTE_URL', 'Point to the allowed workflow or action.', 'manual', 'PIPEDREAM_EXECUTE_URL=https://...'),
      step('doctor', 'Run doctor', 'Validate the configured health URL or readiness state.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=pipedream'),
    ],
    safetyNotes: ['External workflows require preview, approval, and receipt before execution.'],
    goodFor: ['Events', 'External workflows', 'Webhook automation'],
  },
  {
    id: 'zapier',
    label: 'Zapier',
    aliases: ['zapier-actions', 'zapier-mcp'],
    summary: 'Governed connector for Zapier action catalogs and automations.',
    description: 'Zavorth treats Zapier as a governed external broker, ready for health URL, MCP, or configured action endpoint usage.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'actions', 'automation'],
    modes: [mode('api', 'Configured API/MCP', 'Uses ZAPIER_API_KEY or a configured MCP/action endpoint.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'zapier', status: 'ready', summary: 'Governed adapter through health URL, API key, or configured MCP/action endpoint.' },
    requirements: [
      req('zapier_api_key', 'Zapier API key', 'Key or token for the Zapier endpoint used by the operator.', { type: 'env', secret: true, envKey: 'ZAPIER_API_KEY' }),
      req('zapier_health_url', 'Health URL', 'Safe endpoint for live readiness checks.', { type: 'env', envKey: 'ZAPIER_HEALTH_URL', required: false }),
      req('zapier_execute_url', 'Execute URL', 'Allowed endpoint/action for governed execution.', { type: 'env', envKey: 'ZAPIER_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('zapier_api_key', 'What is the Zapier API key/token...', 'secret', 'Use the token for the allowed flow.'),
      question('zapier_health_url', 'Which health URL should Zavorth test...', 'text', 'Optional; enables live doctor checks without a fixed endpoint.', { required: false }),
      question('zapier_execute_url', 'Which Zapier execute URL can Zavorth call...', 'text', 'Optional; used only with preview, approval, and receipt.', { required: false }),
    ],
    installSteps: [
      step('credential', 'Add ZAPIER_API_KEY', 'Configure the credential or allowed endpoint.', 'manual', 'ZAPIER_API_KEY=...'),
      step('execute-url', 'Add ZAPIER_EXECUTE_URL', 'Point to the allowed action endpoint.', 'manual', 'ZAPIER_EXECUTE_URL=https://...'),
      step('doctor', 'Run doctor', 'Validate configured readiness.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=zapier'),
    ],
    safetyNotes: ['Zapier actions can send messages or mutate apps; real execution is approval-gated.'],
    goodFor: ['No-code automation', 'App actions', 'Personal or business operations'],
  },
  {
    id: 'n8n',
    label: 'n8n',
    aliases: ['n8n-workflows', 'n8n-local'],
    summary: 'Governed connector for local or remote n8n.',
    description: 'Zavorth treats n8n as a workflow broker, ideal for self-hosted automations with local policy.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'workflow', 'self-hosted'],
    modes: [mode('api', 'Remote/local API', 'Uses N8N_BASE_URL, N8N_HEALTH_URL, N8N_API_KEY, and N8N_EXECUTE_URL when available.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'n8n', status: 'ready', summary: 'Governed adapter through N8N_BASE_URL/API key or health URL.' },
    requirements: [
      req('n8n_base_url', 'n8n base URL', 'local or remote n8n URL.', { type: 'env', envKey: 'N8N_BASE_URL' }),
      req('n8n_api_key', 'n8n API key', 'n8n API key.', { type: 'env', secret: true, envKey: 'N8N_API_KEY', required: false }),
      req('n8n_health_url', 'Health URL', 'Safe endpoint for live readiness checks.', { type: 'env', envKey: 'N8N_HEALTH_URL', required: false }),
      req('n8n_execute_url', 'Execute URL', 'Allowed webhook/workflow for governed execution.', { type: 'env', envKey: 'N8N_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('n8n_base_url', 'What is the n8n base URL...', 'text', 'Example: http://127.0.0.1:5678'),
      question('n8n_api_key', 'What is the n8n API key...', 'secret', 'Optional if the selected health endpoint does not require auth.', { required: false }),
      question('n8n_execute_url', 'Which n8n webhook/execute URL can Zavorth call...', 'text', 'Optional; used only with preview, approval, and receipt.', { required: false }),
    ],
    installSteps: [
      step('base-url', 'Add N8N_BASE_URL', 'Point to local or remote n8n.', 'manual', 'N8N_BASE_URL=http://127.0.0.1:5678'),
      step('execute-url', 'Add N8N_EXECUTE_URL', 'Point to the allowed webhook/workflow.', 'manual', 'N8N_EXECUTE_URL=http://127.0.0.1:5678/webhook/...'),
      step('doctor', 'Run doctor', 'Validate configured readiness.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=n8n'),
    ],
    safetyNotes: ['local workflows can still mutate files or external services; use approval.'],
    goodFor: ['Self-hosted automation', 'Personal workflows', 'Private workflows'],
  },
  {
    id: 'workato',
    label: 'Workato',
    aliases: ['workato-recipes', 'enterprise-automation'],
    summary: 'Governed connector for enterprise automations and Workato recipes.',
    description: 'Zavorth records readiness and limits Workato execution to Action Harness flows with approvals and receipts.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'enterprise', 'workflows'],
    modes: [mode('api', 'Enterprise API', 'Uses WORKATO_API_TOKEN and an allowed endpoint.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'workato', status: 'ready', summary: 'Governed adapter through configured token/base URL/health URL.' },
    requirements: [
      req('workato_api_token', 'Workato API token', 'Enterprise token with minimum required scope.', { type: 'env', secret: true, envKey: 'WORKATO_API_TOKEN' }),
      req('workato_base_url', 'Workato base URL', 'Workspace base URL or region.', { type: 'env', envKey: 'WORKATO_BASE_URL', required: false }),
      req('workato_health_url', 'Health URL', 'Safe endpoint for live readiness checks.', { type: 'env', envKey: 'WORKATO_HEALTH_URL', required: false }),
      req('workato_execute_url', 'Execute URL', 'Allowed endpoint/recipe for governed execution.', { type: 'env', envKey: 'WORKATO_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('workato_api_token', 'What is the Workato API token...', 'secret', 'Use the least-privileged token possible.'),
      question('workato_health_url', 'Which health URL should Zavorth test...', 'text', 'Optional; recommended for live doctor checks.', { required: false }),
      question('workato_execute_url', 'Which Workato execute URL can Zavorth call...', 'text', 'Optional; used only with preview, approval, and receipt.', { required: false }),
    ],
    installSteps: [
      step('credential', 'Add WORKATO_API_TOKEN', 'Configure the secure credential.', 'manual', 'WORKATO_API_TOKEN=...'),
      step('execute-url', 'Add WORKATO_EXECUTE_URL', 'Point to the allowed recipe/action.', 'manual', 'WORKATO_EXECUTE_URL=https://...'),
      step('doctor', 'Run doctor', 'Validate configured readiness.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=workato'),
    ],
    safetyNotes: ['Enterprise environments require allowlists, preview, and receipts before external actions.'],
    goodFor: ['Enterprise automation', 'ERP/CRM', 'Governed workflows'],
  },
];
