import type { IntegrationManifest } from '../../../../contracts/IntegrationHubContract.js';
import { choice, commonCapabilityQuestion, mode, question, req, step } from './IntegrationRegistryCatalogShared.js';

export const INTEGRATION_AGENT_CONNECTOR_MANIFESTS: IntegrationManifest[] = [
  {
    id: 'composio',
    label: 'Composio',
    aliases: ['composio-tools', 'composio-mcp', 'tool-broker'],
    summary: 'Conector nativo para expor toolkits e acoes externas ao agente com governanca Zavorth.',
    description: 'Usa o Connector Mesh do Zavorth para descobrir toolkits e executar ferramentas externas somente via preview, approval e receipt.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'tools', 'agents', 'oauth'],
    modes: [mode('api', 'API remota', 'Usa COMPOSIO_API_KEY e a API HTTP do Composio.')],
    defaultMode: 'api',
    capabilities: ['agents', 'automation', 'search'],
    binding: {
      kind: 'service',
      key: 'composio',
      status: 'ready',
      summary: 'Adapter nativo no Connector Mesh; execucao externa e approval-gated.',
    },
    requirements: [
      req('composio_api_key', 'Composio API key', 'Chave para listar toolkits e executar ferramentas externas.', {
        type: 'env',
        secret: true,
        envKey: 'COMPOSIO_API_KEY',
      }),
      req('composio_base_url', 'Composio base URL', 'Opcional; por padrao usa https://backend.composio.dev.', {
        type: 'env',
        envKey: 'COMPOSIO_BASE_URL',
        required: false,
      }),
    ],
    onboardingQuestions: [
      question('composio_api_key', 'Qual e a API key do Composio?', 'secret', 'Cole a chave do workspace/projeto que o Zavorth pode usar.'),
      question('composio_base_url', 'Quer usar uma base URL customizada?', 'text', 'Opcional; deixe vazio para o endpoint padrao.', {
        required: false,
        placeholder: 'https://backend.composio.dev',
      }),
      commonCapabilityQuestion,
    ],
    installSteps: [
      step('scope', 'Definir escopo de ferramentas', 'Escolher quais apps/toolkits o agente pode enxergar primeiro.', 'guided'),
      step('credential', 'Adicionar COMPOSIO_API_KEY', 'Configurar a chave em .env local ou secret manager.', 'manual', 'COMPOSIO_API_KEY=...'),
      step('doctor', 'Rodar doctor do connector', 'Validar catalogo de toolkits sem executar acoes externas.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=composio'),
    ],
    safetyNotes: [
      'Ferramentas externas podem mutar sistemas terceiros; execucao real passa por Action Harness e approval.',
      'O doctor lista readiness e nao serializa segredos.',
    ],
    goodFor: ['Tool calling externo', 'OAuth de apps', 'Acoes reais com approval'],
  },
  {
    id: 'nango',
    label: 'Nango',
    aliases: ['nango-auth', 'oauth-broker', 'connection-broker'],
    summary: 'Conector nativo para OAuth, conexoes e credenciais renovaveis de APIs externas.',
    description: 'Usa o Connector Mesh para validar conexoes Nango e deixar o agente usar integrações autorizadas sem carregar tokens brutos.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'oauth', 'connections', 'proxy'],
    modes: [mode('api', 'API remota', 'Usa NANGO_SECRET_KEY e Nango HTTP API.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: {
      kind: 'service',
      key: 'nango',
      status: 'ready',
      summary: 'Adapter nativo no Connector Mesh para conexoes OAuth/API.',
    },
    requirements: [
      req('nango_secret_key', 'Nango secret key', 'Chave com escopo minimo para listar conexoes sem expor credenciais.', {
        type: 'env',
        secret: true,
        envKey: 'NANGO_SECRET_KEY',
      }),
      req('nango_base_url', 'Nango base URL', 'Opcional; por padrao usa https://api.nango.dev.', {
        type: 'env',
        envKey: 'NANGO_BASE_URL',
        required: false,
      }),
      req('nango_action_execute_url', 'Nango action execute URL', 'Endpoint proxy/action permitido para execucao governada quando usado.', {
        type: 'env',
        envKey: 'NANGO_ACTION_EXECUTE_URL',
        required: false,
      }),
    ],
    onboardingQuestions: [
      question('nango_secret_key', 'Qual e a Nango secret key?', 'secret', 'Use uma key com escopos minimos para o ambiente do Zavorth.'),
      question('nango_base_url', 'Quer usar Nango self-hosted ou URL customizada?', 'text', 'Opcional; deixe vazio para Nango Cloud.', {
        required: false,
        placeholder: 'https://api.nango.dev',
      }),
      question('nango_action_execute_url', 'Qual endpoint Nango action/proxy o Zavorth pode executar?', 'text', 'Opcional; usado somente com preview, approval e receipt.', {
        required: false,
      }),
      commonCapabilityQuestion,
    ],
    installSteps: [
      step('scope', 'Definir conexoes permitidas', 'Escolher quais provider_config_keys podem ser usados pelo agente.', 'guided'),
      step('credential', 'Adicionar NANGO_SECRET_KEY', 'Configurar a chave em .env local ou secret manager.', 'manual', 'NANGO_SECRET_KEY=...'),
      step('execute-url', 'Adicionar NANGO_ACTION_EXECUTE_URL', 'Opcional; permite executar uma rota action/proxy governada.', 'manual', 'NANGO_ACTION_EXECUTE_URL=https://...'),
      step('doctor', 'Rodar doctor do connector', 'Validar conexoes Nango sem expor credenciais.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=nango'),
    ],
    safetyNotes: [
      'Tokens OAuth continuam no Nango ou no secure store; o LLM nunca recebe segredo bruto.',
      'Proxy/action Nango deve ser allowlisted por policy antes de executar.',
    ],
    goodFor: ['OAuth', 'Conexoes por usuario', 'APIs externas com refresh token'],
  },
  {
    id: 'pipedream',
    label: 'Pipedream',
    aliases: ['pipedream-workflows', 'event-workflows'],
    summary: 'Conector governado para workflows e acoes externas via Pipedream.',
    description: 'O Zavorth registra readiness e pode usar uma health URL/adapter MCP para operar workflows com approval.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'workflows', 'automation'],
    modes: [mode('api', 'API/endpoint configurado', 'Usa PIPEDREAM_API_KEY, PIPEDREAM_HEALTH_URL e PIPEDREAM_EXECUTE_URL quando disponiveis.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'pipedream', status: 'ready', summary: 'Adapter governado por health URL ou MCP/endpoint configurado.' },
    requirements: [
      req('pipedream_api_key', 'Pipedream API key', 'Chave do workspace Pipedream.', { type: 'env', secret: true, envKey: 'PIPEDREAM_API_KEY' }),
      req('pipedream_health_url', 'Health URL', 'Endpoint seguro para doctor live do workspace.', { type: 'env', envKey: 'PIPEDREAM_HEALTH_URL', required: false }),
      req('pipedream_execute_url', 'Execute URL', 'Endpoint/workflow permitido para execucao governada.', { type: 'env', envKey: 'PIPEDREAM_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('pipedream_api_key', 'Qual e a Pipedream API key?', 'secret', 'Use uma chave com escopo minimo.'),
      question('pipedream_health_url', 'Qual health URL o Zavorth deve testar?', 'text', 'Opcional; permite doctor live sem supor endpoint proprietario.', { required: false }),
      question('pipedream_execute_url', 'Qual execute URL o Zavorth pode chamar?', 'text', 'Opcional; usado somente com preview, approval e receipt.', { required: false }),
    ],
    installSteps: [
      step('credential', 'Adicionar PIPEDREAM_API_KEY', 'Configurar a chave em local seguro.', 'manual', 'PIPEDREAM_API_KEY=...'),
      step('execute-url', 'Adicionar PIPEDREAM_EXECUTE_URL', 'Apontar para o workflow/action permitido.', 'manual', 'PIPEDREAM_EXECUTE_URL=https://...'),
      step('doctor', 'Rodar doctor', 'Validar health URL ou readiness configurada.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=pipedream'),
    ],
    safetyNotes: ['Workflows externos seguem preview/approval/receipt antes de execucao.'],
    goodFor: ['Eventos', 'Workflows externos', 'Automacao por webhook'],
  },
  {
    id: 'zapier',
    label: 'Zapier',
    aliases: ['zapier-actions', 'zapier-mcp'],
    summary: 'Conector governado para catalogos de acoes e automacoes Zapier.',
    description: 'O Zavorth trata Zapier como broker externo governado, pronto para health URL/MCP/action endpoint configurado.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'actions', 'automation'],
    modes: [mode('api', 'API/MCP configurado', 'Usa ZAPIER_API_KEY ou endpoint MCP/action configurado.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'zapier', status: 'ready', summary: 'Adapter governado por health URL, API key ou MCP/action endpoint configurado.' },
    requirements: [
      req('zapier_api_key', 'Zapier API key', 'Chave ou token do endpoint Zapier usado pelo operador.', { type: 'env', secret: true, envKey: 'ZAPIER_API_KEY' }),
      req('zapier_health_url', 'Health URL', 'Endpoint seguro para readiness live.', { type: 'env', envKey: 'ZAPIER_HEALTH_URL', required: false }),
      req('zapier_execute_url', 'Execute URL', 'Endpoint/action permitido para execucao governada.', { type: 'env', envKey: 'ZAPIER_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('zapier_api_key', 'Qual e a Zapier API key/token?', 'secret', 'Use o token do fluxo permitido.'),
      question('zapier_health_url', 'Qual health URL o Zavorth deve testar?', 'text', 'Opcional; permite doctor live sem endpoint fixo.', { required: false }),
      question('zapier_execute_url', 'Qual execute URL Zapier o Zavorth pode chamar?', 'text', 'Opcional; usado somente com preview, approval e receipt.', { required: false }),
    ],
    installSteps: [
      step('credential', 'Adicionar ZAPIER_API_KEY', 'Configurar credencial ou endpoint permitido.', 'manual', 'ZAPIER_API_KEY=...'),
      step('execute-url', 'Adicionar ZAPIER_EXECUTE_URL', 'Apontar para o action endpoint permitido.', 'manual', 'ZAPIER_EXECUTE_URL=https://...'),
      step('doctor', 'Rodar doctor', 'Validar readiness configurada.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=zapier'),
    ],
    safetyNotes: ['Acoes Zapier podem enviar mensagens ou alterar apps; execucao real e approval-gated.'],
    goodFor: ['Automacoes no-code', 'Acoes de apps', 'Operacao pessoal/empresarial'],
  },
  {
    id: 'n8n',
    label: 'n8n',
    aliases: ['n8n-workflows', 'n8n-local'],
    summary: 'Conector governado para n8n local ou remoto.',
    description: 'O Zavorth trata n8n como broker de workflows, ideal para automacoes self-hosted com policy local.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'workflow', 'self-hosted'],
    modes: [mode('api', 'API remota/local', 'Usa N8N_BASE_URL, N8N_HEALTH_URL, N8N_API_KEY e N8N_EXECUTE_URL quando disponiveis.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'n8n', status: 'ready', summary: 'Adapter governado por N8N_BASE_URL/API key ou health URL.' },
    requirements: [
      req('n8n_base_url', 'n8n base URL', 'URL do n8n local/remoto.', { type: 'env', envKey: 'N8N_BASE_URL' }),
      req('n8n_api_key', 'n8n API key', 'Chave da API n8n.', { type: 'env', secret: true, envKey: 'N8N_API_KEY', required: false }),
      req('n8n_health_url', 'Health URL', 'Endpoint seguro para readiness live.', { type: 'env', envKey: 'N8N_HEALTH_URL', required: false }),
      req('n8n_execute_url', 'Execute URL', 'Webhook/workflow permitido para execucao governada.', { type: 'env', envKey: 'N8N_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('n8n_base_url', 'Qual e a base URL do n8n?', 'text', 'Exemplo: http://127.0.0.1:5678'),
      question('n8n_api_key', 'Qual e a API key do n8n?', 'secret', 'Opcional se o health endpoint escolhido nao exigir auth.', { required: false }),
      question('n8n_execute_url', 'Qual webhook/execute URL do n8n o Zavorth pode chamar?', 'text', 'Opcional; usado somente com preview, approval e receipt.', { required: false }),
    ],
    installSteps: [
      step('base-url', 'Adicionar N8N_BASE_URL', 'Apontar para o n8n local/remoto.', 'manual', 'N8N_BASE_URL=http://127.0.0.1:5678'),
      step('execute-url', 'Adicionar N8N_EXECUTE_URL', 'Apontar para o webhook/workflow permitido.', 'manual', 'N8N_EXECUTE_URL=http://127.0.0.1:5678/webhook/...'),
      step('doctor', 'Rodar doctor', 'Validar readiness configurada.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=n8n'),
    ],
    safetyNotes: ['Workflows locais ainda podem mutar arquivos ou servicos externos; use approval.'],
    goodFor: ['Self-hosted', 'Automacoes pessoais', 'Workflows privados'],
  },
  {
    id: 'workato',
    label: 'Workato',
    aliases: ['workato-recipes', 'enterprise-automation'],
    summary: 'Conector governado para automacoes empresariais e receitas Workato.',
    description: 'O Zavorth registra readiness e limita execucao Workato ao Action Harness com approvals e receipts.',
    supportLevel: 'native',
    category: 'remote',
    tags: ['connector', 'enterprise', 'workflows'],
    modes: [mode('api', 'API corporativa', 'Usa WORKATO_API_TOKEN e endpoint permitido.')],
    defaultMode: 'api',
    capabilities: ['automation', 'agents'],
    binding: { kind: 'service', key: 'workato', status: 'ready', summary: 'Adapter governado por token/base URL/health URL configurados.' },
    requirements: [
      req('workato_api_token', 'Workato API token', 'Token corporativo com escopo minimo.', { type: 'env', secret: true, envKey: 'WORKATO_API_TOKEN' }),
      req('workato_base_url', 'Workato base URL', 'Base URL/region do workspace Workato.', { type: 'env', envKey: 'WORKATO_BASE_URL', required: false }),
      req('workato_health_url', 'Health URL', 'Endpoint seguro para readiness live.', { type: 'env', envKey: 'WORKATO_HEALTH_URL', required: false }),
      req('workato_execute_url', 'Execute URL', 'Endpoint/recipe permitido para execucao governada.', { type: 'env', envKey: 'WORKATO_EXECUTE_URL', required: false }),
    ],
    onboardingQuestions: [
      question('workato_api_token', 'Qual e o Workato API token?', 'secret', 'Use token de menor privilegio possivel.'),
      question('workato_health_url', 'Qual health URL o Zavorth deve testar?', 'text', 'Opcional; recomendado para doctor live.', { required: false }),
      question('workato_execute_url', 'Qual execute URL Workato o Zavorth pode chamar?', 'text', 'Opcional; usado somente com preview, approval e receipt.', { required: false }),
    ],
    installSteps: [
      step('credential', 'Adicionar WORKATO_API_TOKEN', 'Configurar credencial segura.', 'manual', 'WORKATO_API_TOKEN=...'),
      step('execute-url', 'Adicionar WORKATO_EXECUTE_URL', 'Apontar para o recipe/action permitido.', 'manual', 'WORKATO_EXECUTE_URL=https://...'),
      step('doctor', 'Rodar doctor', 'Validar readiness configurada.', 'verification', 'zavorth actions preview integration.connectors.doctor --args connectorId=workato'),
    ],
    safetyNotes: ['Ambiente empresarial exige allowlist, preview e receipt antes de qualquer acao externa.'],
    goodFor: ['Enterprise', 'ERP/CRM', 'Automacoes governadas'],
  },
];
