export const COMMAND_CENTER_TOKEN_NAMES = [
  "--b-void",
  "--b-void-accent",
  "--b-void-elevated",
  "--b-surface",
  "--b-surface-fg",
  "--b-surface-highlight",
  "--b-chrome",
  "--b-chrome-strong",
  "--b-signal",
  "--b-signal-strong",
  "--b-signal-muted",
  "--b-shell",
  "--b-shell-strong",
  "--b-pulse",
  "--b-pulse-hover",
  "--b-pulse-muted",
  "--b-pulse-subtle",
  "--b-pulse-glow",
  "--b-ok",
  "--b-warn",
  "--b-danger",
  "--b-info",
  "--b-radius-md",
  "--b-radius-lg",
  "--b-radius-xl",
  "--b-shadow-glow",
  "--b-shadow-xl",
  "--b-font-body",
  "--b-font-display",
  "--b-mono",
] as const;

export const COMMAND_CENTER_REQUIRED_CLASSES = [
  "bsk-command-center",
  "bcc-shell",
  "bcc-bridge",
  "bcc-bridge__brand",
  "bcc-bridge__center",
  "bcc-bridge__right",
  "bcc-runtime-pulse",
  "bcc-viewport",
  "bcc-panel",
  "bcc-card",
  "bcc-badge",
  "bcc-button",
  "bcc-dock",
  "bcc-dock__node",
  "bcc-dock__glyph",
  "bcc-mascot",
  "bcc-mascot__svg",
  "bcc-hero",
  "bcc-hero__eyebrow",
  "bcc-suggestion-chips",
  "bcc-compose",
  "bcc-compose__input-frame",
  "bcc-message",
  "bcc-message__avatar",
  "bcc-message__events",
  "bcc-event-stream",
  "bcc-agent-trace",
  "bcc-agent-trace__step",
  "bcc-agent-trace__title",
  "bcc-agent-capability",
  "bcc-agent-capability__pill",
  "bcc-agent-capability__reason",
  "bcc-chat-context",
  "bcc-logic-cell",
  "bcc-doctor-summary",
  "bcc-access-card",
  "bcc-onboarding-step",
  "bcc-approval-row",
  "bcc-approval-summary",
  "bcc-approval-row__panel",
  "bcc-approval-capability",
  "bcc-artifact-pane",
  "bcc-command-palette",
  "bcc-command-palette-layer",
  "bcc-mission-brief",
  "bcc-metric-card",
  "bcc-overview-stack",
  "bcc-overview-hero",
  "bcc-state-grid",
  "bcc-state-card",
  "bcc-overview-columns",
  "bcc-run-timeline",
  "bcc-health-row",
  "bcc-tool-chip",
  "bcc-release-strip",
  "bcc-run-card",
  "bcc-active-run-state",
  "bcc-experience-home",
  "bcc-agent-pulse",
  "bcc-daily-brief",
  "bcc-response-profile",
  "bcc-live-action-graph",
  "bcc-reasoning-details",
  "bcc-diff-file",
  "bcc-diff-hunk",
] as const;

export const COMMAND_CENTER_PRODUCT_RULES = [
  "Pouco texto.",
  "Estado sempre visivel.",
  "Proxima acao obvia.",
  "Dados reais ou estado vazio honesto.",
  "Premium operacional, sem teatro hacker.",
] as const;
