#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');
const configPath = path.join(projectRoot, 'config', 'remote-publish.json');
const outputRoot = path.join(projectRoot, 'remote-dist');
const outputSummaryPath = path.join(outputRoot, 'publish-result.json');
const runtimeSummaryPath = path.join(projectRoot, 'data', 'runtime', 'last-publish.json');
const publishHistoryPath = path.join(projectRoot, 'data', 'runtime', 'publish-history.json');
const publishArchiveDir = path.join(projectRoot, 'data', 'publish-archives');
const maxHistoryEntries = 12;

function quoteWindowsArg(value) {
  const normalized = String(value ?? '');
  if (!normalized) {
    return '""';
  }

  if (!/[\s"&()<>^|%!]/.test(normalized)) {
    return normalized;
  }

  const escaped = normalized.replace(/(["^&|<>()%!])/g, '^$1');
  return `"${escaped}"`;
}

function spawn(command, args, cwd, capture = false) {
  const options = {
    cwd,
    stdio: capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    shell: false,
    encoding: capture ? 'utf8' : undefined,
  };

  const result =
    process.platform === 'win32'
      ? spawnSync(
          process.env.ComSpec || 'cmd.exe',
          ['/d', '/s', '/c', [command, ...args].map(quoteWindowsArg).join(' ')],
          options,
        )
      : spawnSync(command, args, options);

  if (result.status !== 0) {
    if (capture) {
      const output = `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
      if (output) {
        process.stdout.write(`${output}\n`);
      }
    }

    if (result.error) {
      throw result.error;
    }

    throw new Error(`${command} ${args.join(' ')} failed with status ${result.status}`);
  }

  return result;
}

function run(command, args, cwd) {
  spawn(command, args, cwd, false);
}

function capture(command, args, cwd) {
  const result = spawn(command, args, cwd, true);
  return `${result.stdout ?? ''}${result.stderr ?? ''}`.trim();
}

function stripAnsi(text) {
  return text.replace(
    // eslint-disable-next-line no-control-regex
    /\u001b(?:\[[0-9;...]*[ -/]*[@-~]|\][^\u0007]*(?:\u0007|\u001b\\))/g,
    '',
  );
}

function readConfig() {
  return JSON.parse(fs.readFileSync(configPath, 'utf8'));
}

function getOptionValue(argv, name) {
  const prefix = `${name}=`;
  const matched = argv.find((entry) => entry.startsWith(prefix));
  return matched ? matched.slice(prefix.length) : null;
}

function ensureGitClean() {
  const status = capture('git', ['status', '--porcelain'], projectRoot);
  if (status) {
    throw new Error('Git working tree is not clean. Commit or stash local changes before remote publish.');
  }
}

function getCurrentBranch() {
  return capture('git', ['rev-parse', '--abbrev-ref', 'HEAD'], projectRoot);
}

function getCurrentCommit() {
  return capture('git', ['rev-parse', 'HEAD'], projectRoot);
}

function ensureLinkedProject(targetDir, project) {
  const vercelDir = path.join(targetDir, '.vercel');
  fs.mkdirSync(vercelDir, { recursive: true });
  fs.writeFileSync(
    path.join(vercelDir, 'project.json'),
    JSON.stringify(
      {
        projectId: project.projectId,
        orgId: project.orgId,
        projectName: project.projectName,
      },
      null,
      0,
    ),
    'utf8',
  );
  fs.writeFileSync(
    path.join(vercelDir, 'README.txt'),
    'Auto-generated by scripts/publish-remote.mjs for non-interactive Vercel deploys.\n',
    'utf8',
  );
}

function deployVercelTarget(project, targetDir) {
  console.log(`[remote] deploying ${project.projectName} from ${targetDir}`);
  const raw = capture('npx', ['vercel', 'deploy', '--prod', '--yes'], targetDir);
  const cleaned = stripAnsi(raw);
  process.stdout.write(`${cleaned}\n`);

  const aliasedMatch = cleaned.match(/Aliased:\s+(https:\/\/[^\s]+)/);
  const productionMatch = cleaned.match(/Production:\s+(https:\/\/[^\s]+)/);
  const deploymentUrlMatch = cleaned.match(/"url":\s*"([^"]+)"/);
  const inspectorUrlMatch = cleaned.match(/"inspectorUrl":\s*"([^"]+)"/);

  return {
    projectName: project.projectName,
    productionUrl: aliasedMatch?.[1] || productionMatch?.[1] || null,
    deploymentUrl: deploymentUrlMatch?.[1] || null,
    inspectorUrl: inspectorUrlMatch?.[1] || null,
  };
}

function writeSummary(summary) {
  fs.mkdirSync(path.dirname(outputSummaryPath), { recursive: true });
  fs.writeFileSync(outputSummaryPath, JSON.stringify(summary, null, 2), 'utf8');
  fs.mkdirSync(path.dirname(runtimeSummaryPath), { recursive: true });
  fs.writeFileSync(runtimeSummaryPath, JSON.stringify(summary, null, 2), 'utf8');
}

function readHistory() {
  try {
    if (!fs.existsSync(publishHistoryPath)) {
      return [];
    }
    const parsed = JSON.parse(fs.readFileSync(publishHistoryPath, 'utf8'));
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function writeHistory(entries) {
  fs.mkdirSync(path.dirname(publishHistoryPath), { recursive: true });
  fs.writeFileSync(publishHistoryPath, JSON.stringify(entries, null, 2), 'utf8');
}

function copyDir(sourceDir, targetDir) {
  fs.mkdirSync(path.dirname(targetDir), { recursive: true });
  fs.cpSync(sourceDir, targetDir, {
    recursive: true,
    force: true,
  });
}

function archivePreparedTargets(summary, docsProject, remoteConsoleProject) {
  const archiveId = `${summary.publishedAt.replace(/[-:TZ.]/g, '').slice(0, 14)}-${summary.commit.slice(0, 8)}`;
  const archiveRoot = path.join(publishArchiveDir, archiveId);
  const docsArchiveDir = path.join(archiveRoot, 'docs');
  const remoteConsoleArchiveDir = path.join(archiveRoot, 'remote-console');

  fs.mkdirSync(archiveRoot, { recursive: true });
  copyDir(path.join(projectRoot, docsProject.relativePath), docsArchiveDir);
  copyDir(path.join(projectRoot, remoteConsoleProject.relativePath), remoteConsoleArchiveDir);

  const archiveMeta = {
    id: archiveId,
    createdAt: summary.publishedAt,
    sourceCommit: summary.commit,
    sourceBranch: summary.branch,
    sourceArchiveId: summary.sourceArchiveId || null,
    targets: {
      docs: path.relative(projectRoot, docsArchiveDir).replace(/\\/g, '/'),
      remoteConsole: path.relative(projectRoot, remoteConsoleArchiveDir).replace(/\\/g, '/'),
    },
  };

  fs.writeFileSync(path.join(archiveRoot, 'summary.json'), JSON.stringify(archiveMeta, null, 2), 'utf8');

  return {
    id: archiveId,
    root: archiveRoot,
    targets: archiveMeta.targets,
  };
}

function pruneHistoryAndArchives(entries) {
  const trimmed = entries.slice(0, maxHistoryEntries);
  const keepIds = new Set(trimmed.map((entry) => entry.archive?.id).filter(Boolean));

  if (fs.existsSync(publishArchiveDir)) {
    for (const entry of fs.readdirSync(publishArchiveDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) {
        continue;
      }
      if (keepIds.has(entry.name)) {
        continue;
      }
      fs.rmSync(path.join(publishArchiveDir, entry.name), { recursive: true, force: true });
    }
  }

  return trimmed;
}

function recordHistory(summary, docsProject, remoteConsoleProject) {
  const archive = archivePreparedTargets(summary, docsProject, remoteConsoleProject);
  const historyEntry = {
    ...summary,
    archive,
  };

  const history = readHistory();
  const nextHistory = pruneHistoryAndArchives([historyEntry, ...history]);
  writeHistory(nextHistory);

  return historyEntry;
}

function main() {
  const argv = process.argv.slice(2);
  const args = new Set(argv);
  const dryRun = args.has('--dry-run');
  const skipSmoke = args.has('--skip-smoke');
  const skipGitPush = args.has('--skip-git-push');
  const reusePrepared = args.has('--reuse-prepared');
  const sourceArchiveId = getOptionValue(argv, '--source-archive');
  const config = readConfig();
  const docsProject = {
    ...config.vercel.projects.docs,
    orgId: config.vercel.orgId,
  };
  const remoteConsoleProject = {
    ...config.vercel.projects.remoteConsole,
    orgId: config.vercel.orgId,
  };

  const branch = getCurrentBranch();
  if (!skipGitPush) {
    ensureGitClean();
  }

  if (dryRun) {
    console.log('[remote] dry-run');
    console.log(`[remote] branch: ${branch}`);
    console.log(`[remote] smoke test: ${skipSmoke ? 'skipped' : 'would run'}`);
    console.log(`[remote] prepared surfaces: ${reusePrepared ? 'reuse current remote-dist' : 'would run remote:prepare'}`);
    console.log('[remote] security preflight: would run before deploy');
    console.log(`[remote] git push: ${skipGitPush ? 'skipped' : `would push origin/${branch}`}`);
    if (sourceArchiveId) {
      console.log(`[remote] source archive: ${sourceArchiveId}`);
    }
    console.log(
      `[remote] docs target: ${path.join(projectRoot, docsProject.relativePath)} -> ${docsProject.projectName}`,
    );
    console.log(
      `[remote] remote console target: ${path.join(
        projectRoot,
        remoteConsoleProject.relativePath,
      )} -> ${remoteConsoleProject.projectName}`,
    );
    return;
  }

  if (!skipSmoke) {
    console.log('[remote] running smoke tests before publish');
    run(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['run', 'test:smoke'], projectRoot);
  }

  if (!reusePrepared) {
    console.log('[remote] preparing static artifacts');
    run(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['run', 'remote:prepare'], projectRoot);
  } else {
    console.log('[remote] reusing current remote-dist artifacts');
  }
  console.log('[remote] running security preflight');
  run(process.platform === 'win32' ? 'node' : process.execPath, [path.join('scripts', 'security-ops.mjs'), 'preflight'], projectRoot);

  ensureLinkedProject(path.join(projectRoot, docsProject.relativePath), docsProject);
  ensureLinkedProject(path.join(projectRoot, remoteConsoleProject.relativePath), remoteConsoleProject);

  if (!skipGitPush) {
    console.log(`[remote] pushing ${branch} to origin/${branch}`);
    run('git', ['push', 'origin', branch], projectRoot);
  }

  const docsResult = deployVercelTarget(docsProject, path.join(projectRoot, docsProject.relativePath));
  const remoteConsoleResult = deployVercelTarget(
    remoteConsoleProject,
    path.join(projectRoot, remoteConsoleProject.relativePath),
  );

  const summary = {
    publishedAt: new Date().toISOString(),
    branch,
    commit: getCurrentCommit(),
    sourceArchiveId: sourceArchiveId || null,
    gitPush: skipGitPush ? 'skipped' : 'completed',
    smokeTest: skipSmoke ? 'skipped' : 'passed',
    targets: {
      docs: docsResult,
      remoteConsole: remoteConsoleResult,
    },
  };

  const historyEntry = recordHistory(summary, docsProject, remoteConsoleProject);
  writeSummary(historyEntry);

  console.log('[remote] publish complete');
  console.log(`[remote] docs: ${docsResult.productionUrl ?? docsResult.deploymentUrl ?? 'unavailable'}`);
  console.log(
    `[remote] remote console: ${
      remoteConsoleResult.productionUrl ?? remoteConsoleResult.deploymentUrl ?? 'unavailable'
    }`,
  );
  console.log(`[remote] archive: ${historyEntry.archive?.id ?? 'n/d'}`);
  console.log(`[remote] summary: ${outputSummaryPath}`);
}

main();
