/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';

export const legacy_ar: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_ar: PluginTipsSection = {
  tip: {
    add_manifest: 'أضف manifest.json لـ Plugin OS (schemaVersion zavorth.plugin-os.v1) في الحزمة.',
    bind_all_capabilities: 'اربط كل capability عبر ctx.bindCapability أو bindTool أو bindChannel أو bindMemoryBackend أو bindProvider.',
    bind_capability: 'استدعِ ctx.bindCapability(...) لكل capability معلنة في manifest.json.',
    clear_block: 'الإضافة محظورة. أزل الحظر: zavorth plugins trust {{pluginId}} review --yes',
    declare_capabilities: 'أعلن عن capability واحدة على الأقل في manifest.capabilities (مثل main.run).',
    declare_capability: 'أضف capability {{cap}} إلى manifest.json أو أعلنها عبر definePlugin tools: {}.',
    enable_plugin: 'نفّذ: zavorth plugins enable {{pluginId}} --yes أو وافق / امنح الثقة.',
    entrypoint_module: 'تأكد أن manifest.entrypoint.module يشير إلى ملف موجود (عادة ./index.js).',
    export_function: 'يجب أن يكون التصدير المحلول دالة register(ctx) أو وحدة بها handler.',
    export_register: 'صدّر `register` أو `createZavorthModule` من index.js (CommonJS: module.exports = { register }).',
    fast_register: 'أبقِ register() سريعًا دون I/O شبكي حاجب عند التحميل.',
    install_enable: 'ثبّت وفعّل: zavorth plugins install <path> --yes && zavorth plugins enable {{pluginId}} --yes',
  },
};
