/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_bn: PluginTipsSection = {
  tip: {
    bind_capability: 'manifest.json-এ ঘোষিত প্রতিটি capability-এর জন্য ctx.bindCapability(...) কল করুন।',
    enable_plugin: 'চালান: zavorth plugins enable {{pluginId}} --yes অথবা অনুমোদন / trusted সেট করুন।',
    export_register: 'index.js থেকে `register` বা `createZavorthModule` এক্সপোর্ট করুন (CommonJS: module.exports = { register }).',
  },
};

export const catalog_bn: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_bn,
};
