/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_cs: PluginTipsSection = {
  tip: {
    bind_capability: 'Zavolejte ctx.bindCapability(...) pro každou capability v manifest.json.',
    enable_plugin: 'Spusťte: zavorth plugins enable {{pluginId}} --yes nebo schvalte / trusted.',
    export_register: 'Exportujte `register` nebo `createZavorthModule` z index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_cs: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_cs,
};
