/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_el: PluginTipsSection = {
  tip: {
    bind_capability: 'Καλέστε ctx.bindCapability(...) για κάθε capability στο manifest.json.',
    enable_plugin: 'Εκτελέστε: zavorth plugins enable {{pluginId}} --yes ή εγκρίνετε / trusted.',
    export_register: 'Εξάγετε `register` ή `createZavorthModule` από το index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_el: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_el,
};
