/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_fa: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_fa: PluginTipsSection = {
  tip: {
    bind_capability: 'برای هر capability در manifest.json تابع ctx.bindCapability(...) را فراخوانی کنید.',
    enable_plugin: 'اجرا کنید: zavorth plugins enable {{pluginId}} --yes یا تأیید / trusted.',
    export_register: 'از index.js تابع `register` یا `createZavorthModule` را صادر کنید (CommonJS: module.exports = { register }).',
  },
};

export const catalog_fa: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_fa,
  pluginTips: tips_fa,
};
