/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_he: PluginTipsSection = {
  tip: {
    bind_capability: 'קראו ל-ctx.bindCapability(...) עבור כל capability ב-manifest.json.',
    enable_plugin: 'הריצו: zavorth plugins enable {{pluginId}} --yes או אשרו / trusted.',
    export_register: 'ייצאו `register` או `createZavorthModule` מ-index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_he: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_he,
};
