/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_hi: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_hi: PluginTipsSection = {
  tip: {
    add_manifest: 'पैकेज में Plugin OS manifest.json (schemaVersion zavorth.plugin-os.v1) जोड़ें।',
    bind_all_capabilities: 'प्रत्येक capability को ctx.bindCapability, bindTool, bindChannel, bindMemoryBackend या bindProvider से बाँधें।',
    bind_capability: 'manifest.json में घोषित प्रत्येक capability के लिए ctx.bindCapability(...) कॉल करें।',
    clear_block: 'प्लगिन अवरुद्ध है। हटाएँ: zavorth plugins trust {{pluginId}} review --yes',
    declare_capabilities: 'manifest.capabilities में कम से कम एक capability घोषित करें (जैसे main.run).',
    declare_capability: 'capability {{cap}} को manifest.json में जोड़ें या definePlugin tools: {} से घोषित करें।',
    enable_plugin: 'चलाएँ: zavorth plugins enable {{pluginId}} --yes या अनुमोदन / trusted सेट करें।',
    entrypoint_module: 'सुनिश्चित करें कि manifest.entrypoint.module किसी मौजूदा फ़ाइल (आमतौर पर ./index.js) को इंगित करे।',
    export_function: 'रिज़ॉल्व्ड export एक register(ctx) फ़ंक्शन या handler वाला मॉड्यूल होना चाहिए।',
    export_register: 'index.js से `register` या `createZavorthModule` निर्यात करें (CommonJS: module.exports = { register }).',
    fast_register: 'register() को तेज़ रखें और लोड समय पर ब्लॉकिंग नेटवर्क I/O से बचें।',
    install_enable: 'इंस्टॉल और सक्षम करें: zavorth plugins install <path> --yes && zavorth plugins enable {{pluginId}} --yes',
  },
};

export const catalog_hi: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_hi,
  pluginTips: tips_hi,
};
