/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_id: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_id: PluginTipsSection = {
  tip: {
    bind_capability: 'Panggil ctx.bindCapability(...) untuk setiap capability di manifest.json.',
    enable_plugin: 'Jalankan: zavorth plugins enable {{pluginId}} --yes atau setujui / percayai plugin.',
    export_register: 'Ekspor `register` atau `createZavorthModule` dari index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_id: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_id,
  pluginTips: tips_id,
};
