/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LocalizationCatalog, SupportedLocale } from '../../localeContracts.js';
import { legacy_ar, tips_ar } from './ar.js';
import { legacy_de, tips_de } from './de.js';
import { legacy_en, tips_en } from './en.js';
import { legacy_es, tips_es } from './es.js';
import { legacy_fa, tips_fa, catalog_fa } from './fa.js';
import { legacy_fr, tips_fr } from './fr.js';
import { legacy_hi, tips_hi, catalog_hi } from './hi.js';
import { legacy_id, tips_id, catalog_id } from './id.js';
import { legacy_it, tips_it } from './it.js';
import { legacy_ja, tips_ja } from './ja.js';
import { legacy_ko, tips_ko } from './ko.js';
import { legacy_nl, tips_nl, catalog_nl } from './nl.js';
import { legacy_pl, tips_pl, catalog_pl } from './pl.js';
import { legacy_pt, tips_pt } from './pt.js';
import { legacy_ru, tips_ru } from './ru.js';
import { legacy_th, tips_th, catalog_th } from './th.js';
import { legacy_tr, tips_tr } from './tr.js';
import { legacy_uk, tips_uk } from './uk.js';
import { legacy_vi, tips_vi, catalog_vi } from './vi.js';
import { legacy_zh, tips_zh } from './zh.js';
import { legacy_zh_hant, tips_zh_hant } from './zh-hant.js';
import { tips_bn, catalog_bn } from './bn.js';
import { tips_cs, catalog_cs } from './cs.js';
import { tips_el, catalog_el } from './el.js';
import { tips_he, catalog_he } from './he.js';
import { tips_ms, catalog_ms } from './ms.js';
import { tips_ro, catalog_ro } from './ro.js';
import { tips_sv, catalog_sv } from './sv.js';

/** Legacy and plugin-tip sections layered onto builtin locale catalogs. */
export interface LegacyCatalogExtension {
  legacy?: LocalizationCatalog['legacy'];
  pluginTips?: LocalizationCatalog['pluginTips'];
}

/** Migrated legacy data for builtin locales that shipped translations before unification. */
export const LEGACY_CATALOG_EXTENSIONS: Partial<Record<SupportedLocale, LegacyCatalogExtension>> = {
  'en': { legacy: legacy_en, pluginTips: tips_en, },
  'pt': { legacy: legacy_pt, pluginTips: tips_pt, },
  'es': { legacy: legacy_es, pluginTips: tips_es, },
  'fr': { legacy: legacy_fr, pluginTips: tips_fr, },
  'de': { legacy: legacy_de, pluginTips: tips_de, },
  'it': { legacy: legacy_it, pluginTips: tips_it, },
  'ja': { legacy: legacy_ja, pluginTips: tips_ja, },
  'ko': { legacy: legacy_ko, pluginTips: tips_ko, },
  'ru': { legacy: legacy_ru, pluginTips: tips_ru, },
  'ar': { legacy: legacy_ar, pluginTips: tips_ar, },
  'tr': { legacy: legacy_tr, pluginTips: tips_tr, },
  'uk': { legacy: legacy_uk, pluginTips: tips_uk, },
  'zh': { legacy: legacy_zh, pluginTips: tips_zh, },
  'zh-hant': { legacy: legacy_zh_hant, pluginTips: tips_zh_hant, },
};

interface DynamicCatalogRegistrar {
  registerDynamicCatalog(locale: string, catalog: LocalizationCatalog): void;
}

/**
 * Locales carried solely through migrated data (no builtin catalog); the
 * src/i18n compatibility facade registers them so pre-unification locale
 * preferences keep resolving.
 */
export function registerLegacyDynamicCatalogs(registrar: DynamicCatalogRegistrar): void {
  registrar.registerDynamicCatalog('bn', catalog_bn);
  registrar.registerDynamicCatalog('cs', catalog_cs);
  registrar.registerDynamicCatalog('el', catalog_el);
  registrar.registerDynamicCatalog('fa', catalog_fa);
  registrar.registerDynamicCatalog('fa-ir', catalog_fa);
  registrar.registerDynamicCatalog('he', catalog_he);
  registrar.registerDynamicCatalog('hi', catalog_hi);
  registrar.registerDynamicCatalog('hi-in', catalog_hi);
  registrar.registerDynamicCatalog('id', catalog_id);
  registrar.registerDynamicCatalog('id-id', catalog_id);
  registrar.registerDynamicCatalog('ms', catalog_ms);
  registrar.registerDynamicCatalog('nl', catalog_nl);
  registrar.registerDynamicCatalog('nl-nl', catalog_nl);
  registrar.registerDynamicCatalog('pl', catalog_pl);
  registrar.registerDynamicCatalog('pl-pl', catalog_pl);
  registrar.registerDynamicCatalog('ro', catalog_ro);
  registrar.registerDynamicCatalog('sv', catalog_sv);
  registrar.registerDynamicCatalog('th', catalog_th);
  registrar.registerDynamicCatalog('th-th', catalog_th);
  registrar.registerDynamicCatalog('vi', catalog_vi);
  registrar.registerDynamicCatalog('vi-vn', catalog_vi);
}
