/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';

export const legacy_it: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_it: PluginTipsSection = {
  tip: {
    add_manifest: 'Aggiungi un manifest.json Plugin OS (schemaVersion zavorth.plugin-os.v1) nel pacchetto.',
    bind_all_capabilities: 'Collega ogni capability con ctx.bindCapability, bindTool, bindChannel, bindMemoryBackend o bindProvider.',
    bind_capability: 'Chiama ctx.bindCapability(...) per ogni capability dichiarata in manifest.json.',
    clear_block: 'Plugin bloccato. Sblocca con: zavorth plugins trust {{pluginId}} review --yes',
    declare_capabilities: 'Dichiara almeno una capability in manifest.capabilities (es. main.run).',
    declare_capability: 'Aggiungi la capability {{cap}} a manifest.json o dichiarala con definePlugin tools: {}.',
    enable_plugin: 'Esegui: zavorth plugins enable {{pluginId}} --yes oppure approva / confida nel plugin.',
    entrypoint_module: 'Assicurati che manifest.entrypoint.module punti a un file esistente (di solito ./index.js).',
    export_function: 'L\'export risolto deve essere una funzione register(ctx) o un modulo con handler.',
    export_register: 'Esporta `register` o `createZavorthModule` da index.js (CommonJS: module.exports = { register }).',
    fast_register: 'Mantieni register() veloce e senza I/O di rete bloccante al caricamento.',
    install_enable: 'Installa e abilita: zavorth plugins install <path> --yes && zavorth plugins enable {{pluginId}} --yes',
  },
};
