/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_ms: PluginTipsSection = {
  tip: {
    bind_capability: 'Panggil ctx.bindCapability(...) untuk setiap capability dalam manifest.json.',
    enable_plugin: 'Jalankan: zavorth plugins enable {{pluginId}} --yes atau luluskan / trusted.',
    export_register: 'Eksport `register` atau `createZavorthModule` dari index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_ms: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_ms,
};
