/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_nl: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  quickstart: {
    cancelled: 'Installatie geannuleerd. Geen wijzigingen aangebracht.',
    channels: {
      discord_token: 'Discord bot-token, laat leeg om later in te stellen',
      email_smtp: 'E-mail SMTP URL, laat leeg om later in te stellen',
      slack_token: 'Slack bot-token, laat leeg om later in te stellen',
      telegram_token: 'Telegram bot-token',
      telegram_users: 'Toegestane Telegram gebruikers-ID\'s, komma-gescheiden',
      title: 'Communicatievlakken',
    },
    config_handling: {
      keep: 'Huidige waarden behouden',
      prompt: 'Hoe bestaande configuratie verwerken...',
      reset: 'Resetten voor installatie',
      review: 'Beoordelen en bijwerken',
    },
    config_issues: {
      doctor_hint: 'Voer "zavorth doctor" uit in een andere terminal.',
      env_not_found: '.env-bestand niet gevonden — provider moet worden geconfigureerd',
      env_unreadable: '.env-bestand bestaat maar kan niet worden gelezen',
      no_api_keys: 'Geen API-sleutels gevonden in .env',
      run_doctor: 'zavorth doctor uitvoeren om problemen op te lossen...',
      title: 'Configuratieproblemen',
    },
    existing_config: {
      channels: 'Kanalen: {value}',
      home: 'Home: {value}',
      model: 'Model: {value}',
      provider: 'Provider: {value}',
      title: 'Bestaande configuratie gedetecteerd',
    },
    gateway: {
      installed: 'Runtime service is al geïnstalleerd',
      not_installed: 'Runtime service',
      reinstall: 'Herinstallatiecommando weergeven',
      skip: 'Nu overslaan',
      start_cmd: 'Startcommando weergeven',
      title: 'Runtime service',
    },
    hatch: {
      browser: 'Starten in ZavorthControl',
      later: 'Later starten',
      prompt: 'Hoe wilt u de agent starten na installatie...',
      terminal: 'Starten in Terminal',
      title: 'Agent starten',
    },
    headless: {
      cmd_apply: '  zavorth setup --non-interactive --apply    Standaardwaarden toepassen',
      cmd_dry: '  zavorth setup --dry-run                    Voorbeeld zonder schrijven',
      cmd_json: '  zavorth setup --json                       Output in JSON-formaat',
      docker_hint: '  Docker:       docker run -it zavorth setup',
      message: 'Installatie vereist een interactieve terminal (TTY).',
      non_interactive: 'Niet-interactieve opties:',
      or_run: 'Of voer installatie uit vanuit een interactieve sessie:',
      ssh_hint: '  SSH met TTY:  ssh -t user@host',
    },
    home: {
      choose_custom: 'Eigen homepad kiezen',
      keep_current: 'Huidig ZAVORTH_HOME behouden',
      path_prompt: 'ZAVORTH_HOME-pad',
      prompt: 'Waar moet Zavorth deze instantie opslaan...',
      use_isolated: 'Geïsoleerd home naast het project',
    },
    hooks: {
      hint: 'uitgeschakeld tot beoordeling en activering',
      prompt: 'Automatiseringssjablonen voorbereiden...',
      title: 'Automatisering',
    },
    memory: {
      custom: 'Aangepast pad',
      documents: 'Documenten',
      downloads: 'Downloads',
      local_metadata: 'Lokale metadata (voorkeuren, goedkeuringen, gebruikssignalen)',
      local_summary: 'Lokale samenvattingen (korte project/context-samenvattingen)',
      off: 'Uit (geen geheugen gebruiken tijdens installatie)',
      prompt: 'Geheugenmodus...',
      skip: 'Nu overslaan',
      title: 'Geheugen',
      vault_scope: 'Geheugenscan-bereik...',
      whole_pc: 'Hele PC',
    },
    migration: {
      complete: 'Migratie voltooid. Geïmporteerde instellingen beoordelen.',
      path_prompt: 'Pad naar de agent werkmap:',
      prompt: 'Instellingen migreren van een andere AI-agent...',
      skipped: 'Migratie overgeslagen of mislukt. Voer later uit: zavorth migrate',
    },
    mode: {
      blank: 'Blanco',
      blank_hint: 'minimaal — elke functie apart inschakelen',
      complete: 'Volledige installatie',
      complete_hint: 'alle stappen — provider, kanalen, vaardigheden, geheugen',
      prompt_first_run: 'Hoe wilt u instellen...',
      prompt_reconfigure: 'Hoe wilt u opnieuw configureren...',
      quickstart: 'Snelle start',
      quickstart_hint: 'snel — alleen provider, de rest later',
      safe: 'Veilige modus',
      safe_hint: 'strikte goedkeuringen, lokale standaardwaarden',
    },
    provider: {
      all_providers: 'Alle native provider-routes',
      api_key_prompt: 'Plak uw {provider} API-sleutel (laat leeg om over te slaan):',
      auto_detected: 'API-sleutel voor {provider} gevonden.',
      auto_selected: 'Gebruik {provider} met model {model}.',
      manual_prompt: 'Provider naam (bijv. openai, anthropic)',
      models_prompt: 'Selecteer een model voor {provider}:',
      more: 'Meer providers...',
      none_found: 'Geen LLM provider API-sleutel gevonden in omgevingsvariabelen.',
      select_prompt: 'Welke provider wilt u gebruiken...',
      skip: 'Nu overslaan',
      skip_hint: 'later instellen met zavorth providers',
      test_failed: 'API-sleutel test mislukt. Corrigeer later met: zavorth providers',
      testing: 'API-sleutel testen...',
      verified: 'API-sleutel geverifieerd.',
    },
    search: {
      brave: 'Brave Search',
      google: 'Google Search',
      local: 'Lokaal (geen API-sleutel nodig)',
      prompt: 'Welke zoekprovider...',
      skip: 'Nu overslaan',
      title: 'Web zoeken',
    },
    section: {
      title: 'Installatie — {section}',
    },
    security: {
      confirm_first_run: 'Welkom! Klaar om Zavorth in te stellen...',
      confirm_reconfigure: 'Bestaande Zavorth-installatie opnieuw configureren...',
      short: 'Zavorth leidt natuurlijke taal naar modellen, kanalen en lokale gereedschappen. Gevoelige acties vereisen jouw goedkeuring.',
    },
    skill_governance: {
      casual: 'Informeel',
      casual_hint: 'aanbevolen voor persoonlijk gebruik; snelle import',
      governed: 'Bestuurd',
      governed_hint: 'striktere bedrijfsreview voor risico, licentie, audit',
      prompt: 'Hoe geïmporteerde vaardigheden verwerken...',
    },
    summary: {
      backup: 'Back-up: {value}',
      channels_label: 'Kanalen: {value}',
      env_updated: '.env bijgewerkt ({count} sleutels)',
      governance: 'Vaardigheidsbestuur: {value}',
      memory_label: 'Geheugen: {value}',
      model: 'Model: {value}',
      next_steps: 'Volgende stappen:',
      provider: 'Provider: {value}',
      step_channels: '  zavorth channels      Verbind messagingplatforms',
      step_chat: '  zavorth chat          Begin een gesprek met de agent',
      step_doctor: '  zavorth doctor        Controleer systeemgezondheid',
      step_providers: '  zavorth providers     Wijzig of voeg providers toe',
      title: 'Installatie voltooid',
    },
    wake_detector: {
      args_prompt: 'Wake detector argumenten',
      command_prompt: 'Wake detector commando',
      custom_command: 'Aangepast detectorcommando',
      default_local: 'Standaard lokale detector',
      disabled: 'Uit laten',
      prompt: 'Echo wake-word instelling inschakelen...',
    },
    welcome: {
      banner_line1: 'AI Agent Runtime',
      banner_line2: 'Bestuurd. Lokaal. Van jou.',
      subtitle: 'Laten we alles instellen.',
      title: 'Welkom bij Zavorth',
    },
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_nl: PluginTipsSection = {
  tip: {
    bind_capability: 'Roep ctx.bindCapability(...) aan voor elke capability in manifest.json.',
    enable_plugin: 'Voer uit: zavorth plugins enable {{pluginId}} --yes of geef goedkeuring / trusted trust.',
    export_register: 'Exporteer `register` of `createZavorthModule` uit index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_nl: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_nl,
  pluginTips: tips_nl,
};
