/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_pl: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  quickstart: {
    cancelled: 'Konfiguracja anulowana. Nie wprowadzono zmian.',
    channels: {
      discord_token: 'Token bota Discord, zostaw puste do późniejszej konfiguracji',
      email_smtp: 'URL SMTP emaila, zostaw puste do późniejszej konfiguracji',
      slack_token: 'Token bota Slack, zostaw puste do późniejszej konfiguracji',
      telegram_token: 'Token bota Telegram',
      telegram_users: 'Dozwolone ID użytkowników Telegram, oddzielone przecinkami',
      title: 'Powierzchnie komunikacji',
    },
    config_handling: {
      keep: 'Zachowaj obecne wartości',
      prompt: 'Jak obsłużyć istniejącą konfigurację...',
      reset: 'Zresetuj przed konfiguracją',
      review: 'Przejrzyj i zaktualizuj',
    },
    config_issues: {
      doctor_hint: 'Uruchom "zavorth doctor" w innym terminalu.',
      env_not_found: 'Plik .env nie istnieje — wymagana konfiguracja dostawcy',
      env_unreadable: 'Plik .env istnieje, ale nie można go odczytać',
      no_api_keys: 'Nie znaleziono kluczy API w .env',
      run_doctor: 'Uruchomić zavorth doctor, aby naprawić problemy...',
      title: 'Problemy z konfiguracją',
    },
    existing_config: {
      channels: 'Kanały: {value}',
      home: 'Katalog główny: {value}',
      model: 'Model: {value}',
      provider: 'Dostawca: {value}',
      title: 'Wykryto istniejącą konfigurację',
    },
    gateway: {
      installed: 'Usługa runtime już zainstalowana',
      not_installed: 'Usługa runtime',
      reinstall: 'Pokaż komendę reinstalacji',
      skip: 'Pomiń teraz',
      start_cmd: 'Pokaż komendę uruchomienia',
      title: 'Usługa runtime',
    },
    hatch: {
      browser: 'Uruchom w ZavorthControl',
      later: 'Uruchom później',
      prompt: 'Jak uruchomić agenta po konfiguracji...',
      terminal: 'Uruchom w terminalu',
      title: 'Uruchom agenta',
    },
    headless: {
      cmd_apply: '  zavorth setup --non-interactive --apply    Zastosuj wartości domyślne',
      cmd_dry: '  zavorth setup --dry-run                    Podgląd bez zapisu',
      cmd_json: '  zavorth setup --json                       Wyjście w formacie JSON',
      docker_hint: '  Docker:     docker run -it zavorth setup',
      message: 'Konfiguracja wymaga interaktywnego terminala (TTY).',
      non_interactive: 'Opcje nieinteraktywne:',
      or_run: 'Lub uruchom konfigurację z sesji interaktywnej:',
      ssh_hint: '  SSH z TTY:  ssh -t user@host',
    },
    home: {
      choose_custom: 'Wybierz własną ścieżkę',
      keep_current: 'Zachowaj obecne ZAVORTH_HOME',
      path_prompt: 'Ścieżka ZAVORTH_HOME',
      prompt: 'Gdzie przechowywać tę instancję...',
      use_isolated: 'Izolowany katalog obok projektu',
    },
    hooks: {
      hint: 'wyłączone do czasu przeglądu i aktywacji',
      prompt: 'Przygotować szablony automatyzacji...',
      title: 'Automatyzacja',
    },
    memory: {
      custom: 'Własna ścieżka',
      documents: 'Dokumenty',
      downloads: 'Pobrane',
      local_metadata: 'Lokalne metadane (preferencje, zatwierdzenia, sygnały użycia)',
      local_summary: 'Lokalne podsumowania (krótkie podsumowania projektu/kontekstu)',
      off: 'Wył (nie używaj pamięci podczas konfiguracji)',
      prompt: 'Tryb pamięci...',
      skip: 'Pomiń teraz',
      title: 'Pamięć',
      vault_scope: 'Zakres skanowania pamięci...',
      whole_pc: 'Cały komputer',
    },
    migration: {
      complete: 'Migracja zakończona. Przejrzyj zaimportowane ustawienia.',
      path_prompt: 'Ścieżka do katalogu workspace agenta:',
      prompt: 'Migrować ustawienia z innego agenta AI...',
      skipped: 'Migracja pominięta lub nieudana. Uruchom później: zavorth migrate',
    },
    mode: {
      blank: 'Czysta strona',
      blank_hint: 'minimalne — włączaj każdą funkcję osobno',
      complete: 'Pełna konfiguracja',
      complete_hint: 'wszystkie kroki — dostawca, kanały, umiejętności, pamięć',
      prompt_first_run: 'Jak chcesz skonfigurować...',
      prompt_reconfigure: 'Jak chcesz przekonfigurować...',
      quickstart: 'Szybki start',
      quickstart_hint: 'szybko — tylko dostawca, reszta później',
      safe: 'Tryb bezpieczny',
      safe_hint: 'surowe zatwierdzenia, domyślne ustawienia lokalne',
    },
    provider: {
      all_providers: 'Wszystkie natywne trasy dostawców',
      api_key_prompt: 'Wklej klucz API {provider} (zostaw puste, aby pominąć):',
      auto_detected: 'Znaleziono klucz API dla {provider}.',
      auto_selected: 'Używam {provider} z modelem {model}.',
      manual_prompt: 'Nazwa dostawcy (np. openai, anthropic)',
      models_prompt: 'Wybierz model dla {provider}:',
      more: 'Więcej dostawców...',
      none_found: 'Nie znaleziono klucza API dostawcy LLM w zmiennych środowiskowych.',
      select_prompt: 'Którego dostawcy użyć...',
      skip: 'Pomiń teraz',
      skip_hint: 'skonfiguruj później przez zavorth providers',
      test_failed: 'Test klucza API nieudany. Napraw później: zavorth providers',
      testing: 'Testowanie klucza API...',
      verified: 'Klucz API zweryfikowany.',
    },
    search: {
      brave: 'Brave Search',
      google: 'Google Search',
      local: 'Lokalny (bez klucza API)',
      prompt: 'Jaki dostawca wyszukiwania...',
      skip: 'Pomiń teraz',
      title: 'Wyszukiwanie',
    },
    section: {
      title: 'Konfiguracja — {section}',
    },
    security: {
      confirm_first_run: 'Witaj! Gotowy do skonfigurowania Zavorth...',
      confirm_reconfigure: 'Przekonfigurować istniejącą instalację Zavorth...',
      short: 'Zavorth kieruje język naturalny do modeli, kanałów i narzędzi lokalnych. Wrażliwe działania wymagają Twojej zgody.',
    },
    skill_governance: {
      casual: 'Swobodny',
      casual_hint: 'zalecany do użytku osobistego; szybki import',
      governed: 'Zarządzany',
      prompt: 'Jak obsługiwać zaimportowane umiejętności...',
    },
    summary: {
      backup: 'Kopia zapasowa: {value}',
      channels_label: 'Kanały: {value}',
      env_updated: '.env zaktualizowany ({count} kluczy)',
      governance: 'Zarządzanie umiejętnościami: {value}',
      memory_label: 'Pamięć: {value}',
      model: 'Model: {value}',
      next_steps: 'Następne kroki:',
      provider: 'Dostawca: {value}',
      step_channels: '  zavorth channels      Połącz platformy komunikacyjne',
      step_chat: '  zavorth chat          Zacznij rozmowę z agentem',
      step_doctor: '  zavorth doctor        Sprawdź stan systemu',
      step_providers: '  zavorth providers     Zmień lub dodaj dostawców',
      title: 'Konfiguracja zakończona',
    },
    wake_detector: {
      args_prompt: 'Argumenty detektora budzenia',
      command_prompt: 'Komenda detektora budzenia',
      custom_command: 'Niestandardowa komenda detektora',
      default_local: 'Domyślny detektor lokalny',
      disabled: 'Wyłącz',
      prompt: 'Włączyć konfigurację słowa budzącego Echo...',
    },
    welcome: {
      banner_line1: 'Runtime agenta AI',
      banner_line2: 'Zarządzane. Lokalne. Twoje.',
      subtitle: 'Skonfigurujmy wszystko.',
      title: 'Witamy w Zavorth',
    },
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_pl: PluginTipsSection = {
  tip: {
    bind_capability: 'Wywołaj ctx.bindCapability(...) dla każdej capability z manifest.json.',
    enable_plugin: 'Uruchom: zavorth plugins enable {{pluginId}} --yes lub zatwierdź / zaufaj wtyczce.',
    export_register: 'Wyeksportuj `register` lub `createZavorthModule` z index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_pl: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_pl,
  pluginTips: tips_pl,
};
