/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_ro: PluginTipsSection = {
  tip: {
    bind_capability: 'Apelați ctx.bindCapability(...) pentru fiecare capability din manifest.json.',
    enable_plugin: 'Rulați: zavorth plugins enable {{pluginId}} --yes sau aprobați / trusted.',
    export_register: 'Exportați `register` sau `createZavorthModule` din index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_ro: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_ro,
};
