/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const tips_sv: PluginTipsSection = {
  tip: {
    bind_capability: 'Anropa ctx.bindCapability(...) för varje capability i manifest.json.',
    enable_plugin: 'Kör: zavorth plugins enable {{pluginId}} --yes eller godkänn / trusted trust.',
    export_register: 'Exportera `register` eller `createZavorthModule` från index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_sv: LocalizationCatalog = {
  ...coreEnglishCatalog,
  pluginTips: tips_sv,
};
