/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_th: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  quickstart: {
    cancelled: 'การตั้งค่าถูกยกเลิก ไม่มีการเปลี่ยนแปลงใดๆ',
    channels: {
      discord_token: 'โทเค็นบอท Discord ว่างไว้เพื่อตั้งค่าทีหลัง',
      email_smtp: 'URL SMTP อีเมล ว่างไว้เพื่อตั้งค่าทีหลัง',
      slack_token: 'โทเค็นบอท Slack ว่างไว้เพื่อตั้งค่าทีหลัง',
      telegram_token: 'โทเค็นบอท Telegram',
      telegram_users: 'รหัสผู้ใช้ Telegram ที่อนุญาต คั่นด้วยจุลภาค',
      title: 'ช่องทางสื่อสาร',
    },
    config_handling: {
      keep: 'เก็บค่าปัจจุบัน',
      prompt: 'จัดการการตั้งค่าที่มีอยู่อย่างไร...',
      reset: 'รีเซ็ตก่อนตั้งค่า',
      review: 'ตรวจสอบและอัปเดต',
    },
    config_issues: {
      doctor_hint: 'รัน "zavorth doctor" ในเทอร์มินัลอื่น',
      env_not_found: 'ไม่พบไฟล์ .env — ต้องตั้งค่าผู้ให้บริการ',
      env_unreadable: 'ไฟล์ .env มีอยู่แต่อ่านไม่ได้',
      no_api_keys: 'ไม่พบ API key ใน .env',
      run_doctor: 'รัน zavorth doctor เพื่อแก้ไขปัญหา...',
      title: 'ปัญหาการตั้งค่า',
    },
    existing_config: {
      channels: 'ช่องทาง: {value}',
      home: 'โฮม: {value}',
      model: 'โมเดล: {value}',
      provider: 'ผู้ให้บริการ: {value}',
      title: 'ตรวจพบการตั้งค่าที่มีอยู่',
    },
    gateway: {
      installed: 'บริการรันไทม์ติดตั้งแล้ว',
      not_installed: 'บริการรันไทม์',
      reinstall: 'แสดงคำสั่งติดตั้งใหม่',
      skip: 'ข้ามตอนนี้',
      start_cmd: 'แสดงคำสั่งเริ่มต้น',
      title: 'บริการรันไทม์',
    },
    hatch: {
      browser: 'เริ่มใน ZavorthControl',
      later: 'เริ่มทีหลัง',
      prompt: 'ต้องการเริ่ม agent อย่างไรหลังตั้งค่า...',
      terminal: 'เริ่มในเทอร์มินัล',
      title: 'เริ่มต้น agent',
    },
    headless: {
      cmd_apply: '  zavorth setup --non-interactive --apply    ใช้ค่าเริ่มต้นโดยเงียบ',
      cmd_dry: '  zavorth setup -- dry-run                   ดูตัวอย่างโดยไม่เขียน',
      cmd_json: '  zavorth setup --json                       ผลลัพธ์แบบ JSON',
      docker_hint: '  Docker:          docker run -it zavorth setup',
      message: 'การตั้งค่าต้องใช้เทอร์มินัลแบบโต้ตอบ (TTY)',
      non_interactive: 'ตัวเลือกที่ไม่ใช่แบบโต้ตอบ:',
      or_run: 'หรือรันการตั้งค่าจากเซสชันแบบโต้ตอบ:',
      ssh_hint: '  SSH พร้อม TTY:  ssh -t user@host',
    },
    home: {
      choose_custom: 'เลือกพาธโฮมกำหนดเอง',
      keep_current: 'เก็บ ZAVORTH_HOME ปัจจุบัน',
      path_prompt: 'พาธ ZAVORTH_HOME',
      prompt: 'เก็บ instance นี้ไว้ที่ไหน...',
      use_isolated: 'ใช้โฮมแยกข้างโปรเจกต์',
    },
    hooks: {
      hint: 'ปิดอยู่จนกว่าจะตรวจสอบและเปิดใช้งาน',
      prompt: 'เตรียมเทมเพลตอัตโนมัติ...',
      title: 'อัตโนมัติ',
    },
    memory: {
      custom: 'พาธกำหนดเอง',
      documents: 'เอกสาร',
      downloads: 'ดาวน์โหลด',
      local_metadata: 'ข้อมูลเมตาท้องถิ่น (ความชอบ การอนุมัติ สัญญาณการใช้งาน)',
      local_summary: 'สรุปท้องถิ่น (สรุปสั้นของโปรเจกต์/บริบท)',
      off: 'ปิด (ไม่ใช้ความจำระหว่างตั้งค่า)',
      prompt: 'โหมดความจำ...',
      skip: 'ข้ามตอนนี้',
      title: 'ความจำ',
      vault_scope: 'ขอบเขตการสแกนความจำ...',
      whole_pc: 'ทั้งพีซี',
    },
    migration: {
      complete: 'การย้ายเสร็จสมบูรณ์ ตรวจสอบการตั้งค่าที่นำเข้า',
      path_prompt: 'พาธโฟลเดอร์ workspace ของ agent:',
      prompt: 'ย้ายการตั้งค่าจาก agent AI อื่น...',
      skipped: 'การย้ายถูกข้ามหรือล้มเหลว รันทีหลัง: zavorth migrate',
    },
    mode: {
      blank: 'หน้าว่าง',
      blank_hint: 'น้อยที่สุด — เปิดใช้งานทีละฟีเจอร์',
      complete: 'ตั้งค่าครบถ้วน',
      complete_hint: 'ทุกขั้นตอน — ผู้ให้บริการ ช่องทาง ทักษะ ความจำ',
      prompt_first_run: 'ต้องการตั้งค่าอย่างไร...',
      prompt_reconfigure: 'ต้องการตั้งค่าใหม่อย่างไร...',
      quickstart: 'เริ่มต้นเร็ว',
      quickstart_hint: 'เร็ว — เฉพาะผู้ให้บริการ ที่เหลือทีหลัง',
      safe: 'โหมดปลอดภัย',
      safe_hint: 'การอนุมัติที่เข้มงวด ค่าเริ่มต้นระดับท้องถิ่น',
    },
    provider: {
      all_providers: 'ทุกเส้นทาง provider ดั้งเดิม',
      api_key_prompt: 'วาง API key ของ {provider} (เว้นว่างเพื่อข้าม):',
      auto_detected: 'พบ API key สำหรับ {provider}',
      auto_selected: 'ใช้ {provider} กับโมเดล {model}',
      manual_prompt: 'ชื่อผู้ให้บริการ (เช่น openai, anthropic)',
      models_prompt: 'เลือกโมเดลสำหรับ {provider}:',
      more: 'ผู้ให้บริการเพิ่มเติม...',
      none_found: 'ไม่พบ API key ของ LLM provider ในตัวแปรสภาพแวดล้อม',
      select_prompt: 'ต้องการใช้ผู้ให้บริการใด...',
      skip: 'ข้ามตอนนี้',
      skip_hint: 'ตั้งค่าทีหลังด้วย zavorth providers',
      test_failed: 'การทดสอบ API key ล้มเหลว แก้ไขทีหลังด้วย: zavorth providers',
      testing: 'กำลังทดสอบ API key...',
      verified: 'API key ผ่านการตรวจสอบ',
    },
    search: {
      brave: 'Brave Search',
      google: 'Google Search',
      local: 'ท้องถิ่น (ไม่ต้องใช้ API key)',
      prompt: 'ผู้ให้บริการค้นหาใด...',
      skip: 'ข้ามตอนนี้',
      title: 'ค้นหาเว็บ',
    },
    section: {
      title: 'ตั้งค่า — {section}',
    },
    security: {
      confirm_first_run: 'ยินดีต้อนรับ! พร้อมตั้งค่า Zavorth หรือยัง...',
      confirm_reconfigure: 'ตั้งค่า Zavorth ที่มีอยู่ใหม่...',
      short: 'Zavorth กำหนดเส้นทางภาษาธรรมชาติไปยังโมเดล ช่องทาง และเครื่องมือท้องถิ่น การกระทำที่ละเอียดอ่อนต้องได้รับอนุมัติจากคุณ',
    },
    skill_governance: {
      casual: 'ไม่เป็นทางการ',
      casual_hint: 'แนะนำสำหรับการใช้งานส่วนตัว นำเข้าเร็ว',
      governed: 'กำกับดูแล',
      governed_hint: 'การตรวจสอบองค์กรที่เข้มงวดสำหรับความเสี่ยง ลิขสิทธิ์ การตรวจสอบ',
      prompt: 'จัดการทักษะที่นำเข้าอย่างไร...',
    },
    summary: {
      backup: 'สำเนาข้อมูล: {value}',
      channels_label: 'ช่องทาง: {value}',
      env_updated: '.env อัปเดตแล้ว ({count} คีย์)',
      governance: 'การกำกับดูแลทักษะ: {value}',
      memory_label: 'ความจำ: {value}',
      model: 'โมเดล: {value}',
      next_steps: 'ขั้นตอนถัดไป:',
      provider: 'ผู้ให้บริการ: {value}',
      step_channels: '  zavorth channels      เชื่อมต่อแพลตฟอร์มส่งข้อความ',
      step_chat: '  zavorth chat          เริ่มสนทนากับ agent',
      step_doctor: '  zavorth doctor        ตรวจสอบสถานะระบบ',
      step_providers: '  zavorth providers     เปลี่ยนหรือเพิ่มผู้ให้บริการ',
      title: 'ตั้งค่าเสร็จสมบูรณ์',
    },
    wake_detector: {
      args_prompt: 'อาร์กิวเมนต์เครื่องตรวจจับ wake',
      command_prompt: 'คำสั่งเครื่องตรวจจับ wake',
      custom_command: 'คำสั่งเครื่องตรวจจับกำหนดเอง',
      default_local: 'เครื่องตรวจจับท้องถิ่นเริ่มต้น',
      disabled: 'ปิดไว้',
      prompt: 'เปิดใช้งานการตั้งค่า Wake word Echo...',
    },
    welcome: {
      banner_line1: 'รันไทม์เอเจนต์ AI',
      banner_line2: 'กำกับดูแล ระดับท้องถิ่น เป็นของคุณ',
      subtitle: 'มาตั้งค่าทุกอย่างกัน',
      title: 'ยินดีต้อนรับสู่ Zavorth',
    },
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_th: PluginTipsSection = {
  tip: {
    bind_capability: 'เรียก ctx.bindCapability(...) สำหรับทุก capability ใน manifest.json',
    enable_plugin: 'รัน: zavorth plugins enable {{pluginId}} --yes หรืออนุมัติ / ตั้ง trusted',
    export_register: 'ส่งออก `register` หรือ `createZavorthModule` จาก index.js (CommonJS: module.exports = { register })',
  },
};

export const catalog_th: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_th,
  pluginTips: tips_th,
};
