/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';

export const legacy_tr: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  quickstart: {
    cancelled: 'Kurulum iptal edildi. Hiçbir değişiklik yapılmadı.',
    channels: {
      discord_token: 'Discord bot jetonu, sonra yapılandırmak için boş bırakın',
      email_smtp: 'E-posta SMTP URL\'si, sonra yapılandırmak için boş bırakın',
      slack_token: 'Slack bot jetonu, sonra yapılandırmak için boş bırakın',
      telegram_token: 'Telegram bot jetonu',
      telegram_users: 'İzin verilen Telegram kullanıcı ID\'leri, virgülle ayrılmış',
      title: 'İletişim yüzeyleri',
    },
    config_handling: {
      keep: 'Mevcut değerleri koru',
      prompt: 'Mevcut yapılandırma nasıl işlensin...',
      reset: 'Kurulumdan önce sıfırla',
      review: 'Gözden geçir ve güncelle',
    },
    config_issues: {
      doctor_hint: 'Başka bir terminalde "zavorth doctor" çalıştırın.',
      env_not_found: '.env dosyası bulunamadı — sağlayıcı yapılandırılmalı',
      env_unreadable: '.env dosyası var ama okunamıyor',
      no_api_keys: '.env\'de API anahtarı bulunamadı',
      run_doctor: 'Sorunları düzeltmek için zavorth doctor çalıştırılsın mı...',
      title: 'Yapılandırma sorunları',
    },
    existing_config: {
      channels: 'Kanallar: {value}',
      home: 'Ana dizin: {value}',
      model: 'Model: {value}',
      provider: 'Sağlayıcı: {value}',
      title: 'Mevcut yapılandırma algılandı',
    },
    gateway: {
      installed: 'Çalışma zamanı hizmeti zaten kurulu',
      not_installed: 'Çalışma zamanı hizmeti',
      reinstall: 'Yeniden kurulum komutunu göster',
      skip: 'Şu an atla',
      start_cmd: 'Başlatma komutunu göster',
      title: 'Çalışma zamanı hizmeti',
    },
    hatch: {
      browser: 'ZavorthControl\'da başlat',
      later: 'Sonra başlat',
      prompt: 'Kurulumdan sonra agent\'ı nasıl başlatmak istersiniz...',
      terminal: 'Terminal\'de başlat',
      title: 'Agent\'ı başlat',
    },
    headless: {
      cmd_apply: '  zavorth setup --non-interactive --apply    Varsayılanları sessizce uygula',
      cmd_dry: '  zavorth setup --dry-run                    Yazmadan önizleme',
      cmd_json: '  zavorth setup --json                       JSON formatında çıktı',
      docker_hint: '  Docker:       docker run -it zavorth setup',
      message: 'Kurulum etkileşimli bir terminal (TTY) gerektirir.',
      non_interactive: 'Etkileşim dışı seçenekler:',
      or_run: 'Veya etkileşimli oturumdan kurulumu çalıştırın:',
      ssh_hint: '  SSH ile TTY:  ssh -t user@host',
    },
    home: {
      choose_custom: 'Özel ev yolu seç',
      keep_current: 'Mevcut ZAVORTH_HOME\'u koru',
      path_prompt: 'ZAVORTH_HOME yolu',
      prompt: 'Bu örneği nereye saklamak istersiniz...',
      use_isolated: 'Projenin yanında izole ev kullan',
    },
    hooks: {
      hint: 'incelenip etkinleştirilene kadar devre dışı',
      prompt: 'Otomasyon şablonları hazırlansın mı...',
      title: 'Otomasyon',
    },
    memory: {
      custom: 'Özel yol',
      documents: 'Belgeler',
      downloads: 'İndirmeler',
      local_metadata: 'Yerel meta veriler (tercihler, onaylar, kullanım sinyalleri)',
      local_summary: 'Yerel özetler (kısa proje/bağlam özetleri)',
      off: 'Kapalı (kurulum sırasında bellek kullanma)',
      prompt: 'Bellek modu...',
      skip: 'Şu an atla',
      title: 'Bellek',
      vault_scope: 'Bellek tarama kapsamı...',
      whole_pc: 'Tüm PC',
    },
    migration: {
      complete: 'Taşıma tamamlandı. İçe aktarılan ayarları inceleyin.',
      path_prompt: 'Agent çalışma alanı klasörü yolu:',
      prompt: 'Başka bir AI agent\'tan ayarlar taşınsın mı...',
      skipped: 'Atlandı veya başarısız oldu. Daha sonra çalıştırın: zavorth migrate',
    },
    mode: {
      blank: 'Boş Sayfa',
      blank_hint: 'minimal — her özelliği ayrı ayrı etkinleştirin',
      complete: 'Tam Kurulum',
      complete_hint: 'tüm adımlar — sağlayıcı, kanallar, beceriler, bellek',
      prompt_first_run: 'Nasıl kurmak istersiniz...',
      prompt_reconfigure: 'Nasıl yeniden yapılandırmak istersiniz...',
      quickstart: 'Hızlı Başlangıç',
      quickstart_hint: 'hızlı — sadece sağlayıcı, geri kalanı sonra',
      safe: 'Güvenli Mod',
      safe_hint: 'katı onaylar, yerel varsayılanlar',
    },
    provider: {
      all_providers: 'Tüm yerel sağlayıcı yolları',
      api_key_prompt: '{provider} API anahtarınızı yapıştırın (boş bırakarak atlayın):',
      auto_detected: '{provider} için API anahtarı bulundu.',
      auto_selected: '{provider} kullanılıyor, model {model}.',
      manual_prompt: 'Sağlayıcı adı (ör: openai, anthropic)',
      models_prompt: '{provider} için model seçin:',
      more: 'Daha fazla sağlayıcı...',
      none_found: 'Ortam değişkenlerinde LLM sağlayıcı API anahtarı bulunamadı.',
      select_prompt: 'Hangi sağlayıcıyı kullanmak istersiniz...',
      skip: 'Şu an atla',
      skip_hint: 'daha sonra zavorth providers ile yapılandırın',
      test_failed: 'API anahtarı testi başarısız. Daha sonra zavorth providers ile düzeltin',
      testing: 'API anahtarı test ediliyor...',
      verified: 'API anahtarı doğrulandı.',
    },
    search: {
      brave: 'Brave Search',
      google: 'Google Search',
      local: 'Yerel (API anahtarı gerekmez)',
      prompt: 'Hangi arama sağlayıcısı...',
      skip: 'Şu an atla',
      title: 'Web arama',
    },
    section: {
      title: 'Kurulum — {section}',
    },
    security: {
      confirm_first_run: 'Hoş geldiniz! Zavorth\'u kurmaya hazır mısınız...',
      confirm_reconfigure: 'Mevcut Zavorth kurulumunu yeniden yapılandırmak ister misiniz...',
      short: 'Zavorth doğal dili modellere, kanallara ve yerel araçlara yönlendirir. Hassas eylemler sizin onayınızı gerektirir.',
    },
    skill_governance: {
      casual: 'Günlük',
      casual_hint: 'kişisel kullanım için önerilen; hızlı içe aktarma',
      governed: 'Yönetimli',
      governed_hint: 'risk, lisans, denetim için katı kurumsal inceleme',
      prompt: 'İçe aktarılan beceriler nasıl işlensin...',
    },
    summary: {
      backup: 'Yedekleme: {value}',
      channels_label: 'Kanallar: {value}',
      env_updated: '.env güncellendi ({count} anahtar)',
      governance: 'Beceri yönetimi: {value}',
      memory_label: 'Bellek: {value}',
      model: 'Model: {value}',
      next_steps: 'Sonraki adımlar:',
      provider: 'Sağlayıcı: {value}',
      step_channels: '  zavorth channels      Mesajlaşma platformlarını bağlayın',
      step_chat: '  zavorth chat          Agent ile konuşmaya başlayın',
      step_doctor: '  zavorth doctor        Sistem sağlığını kontrol edin',
      step_providers: '  zavorth providers     Sağlayıcıları değiştirin veya ekleyin',
      title: 'Kurulum tamamlandı',
    },
    wake_detector: {
      args_prompt: 'Uyanma algılayıcı bağımsız değişkenleri',
      command_prompt: 'Uyanma algılayıcı komutu',
      custom_command: 'Özel algılayıcı komutu',
      default_local: 'Varsayılan yerel algılayıcı',
      disabled: 'Kapalı kalsın',
      prompt: 'Echo kelime algılama kurulumu etkinleştirilsin mi...',
    },
    welcome: {
      banner_line1: 'AI Agent Çalışma Zamanı',
      banner_line2: 'Yönetimli. Yerel. Sizin.',
      subtitle: 'Her şeyi配置layalım.',
      title: 'Zavorth\'a Hoş Geldiniz',
    },
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_tr: PluginTipsSection = {
  tip: {
    bind_capability: 'manifest.json içinde tanımlı her capability için ctx.bindCapability(...) çağırın.',
    enable_plugin: 'Çalıştırın: zavorth plugins enable {{pluginId}} --yes veya onay / trusted verin.',
    export_register: 'index.js dosyasından `register` veya `createZavorthModule` dışa aktarın (CommonJS: module.exports = { register }).',
  },
};
