/* eslint-disable */
// AUTO-GENERATED by scripts/merge-legacy-i18n-catalogs.mjs - do not edit by hand.
import type { LegacyCatalogSection, LocalizationCatalog, PluginTipsSection } from '../../localeContracts.js';
import { en } from '../en.js';

const coreEnglishCatalog = (({ legacy: _legacy, pluginTips: _tips, ...coreSections }) => coreSections)(en);

export const legacy_vi: LegacyCatalogSection = {
  cli: {
  },
  common: {
  },
  desktop: {
  },
  errors: {
  },
  onboarding: {
  },
  quickstart: {
    cancelled: 'Cấu hình đã bị hủy. Không có thay đổi nào được thực hiện.',
    channels: {
      discord_token: 'Token bot Discord, để trống để cấu hình sau',
      email_smtp: 'URL SMTP email, để trống để cấu hình sau',
      slack_token: 'Token bot Slack, để trống để cấu hình sau',
      telegram_token: 'Token bot Telegram',
      telegram_users: 'ID người dùng Telegram được phép, phân cách bằng dấu phẩy',
      title: 'Giao diện truyền thông',
    },
    config_handling: {
      keep: 'Giữ giá trị hiện tại',
      prompt: 'Xử lý cấu hình hiện có như thế nào...',
      reset: 'Đặt lại trước khi cấu hình',
      review: 'Xem xét và cập nhật',
    },
    config_issues: {
      doctor_hint: 'Chạy "zavorth doctor" trong terminal khác.',
      env_not_found: 'Không tìm thấy file .env — cần cấu hình nhà cung cấp',
      env_unreadable: 'File .env tồn tại nhưng không đọc được',
      no_api_keys: 'Không tìm thấy API key trong .env',
      run_doctor: 'Chạy zavorth doctor để sửa lỗi...',
      title: 'Vấn đề cấu hình',
    },
    existing_config: {
      channels: 'Kênh: {value}',
      home: 'Thư mục gốc: {value}',
      model: 'Mô hình: {value}',
      provider: 'Nhà cung cấp: {value}',
      title: 'Phát hiện cấu hình hiện có',
    },
    gateway: {
      installed: 'Dịch vụ runtime đã được cài đặt',
      not_installed: 'Dịch vụ runtime',
      reinstall: 'Hiện lệnh cài đặt lại',
      skip: 'Bỏ qua bây giờ',
      start_cmd: 'Hiện lệnh khởi động',
      title: 'Dịch vụ runtime',
    },
    hatch: {
      browser: 'Khởi động trong ZavorthControl',
      later: 'Khởi động sau',
      prompt: 'Bạn muốn khởi động agent như thế nào sau khi cấu hình...',
      terminal: 'Khởi động trong Terminal',
      title: 'Khởi động agent',
    },
    headless: {
      cmd_apply: '  zavorth setup --non-interactive --apply    Áp dụng mặc định im lặng',
      cmd_dry: '  zavorth setup --dry-run                    Xem trước không ghi',
      cmd_json: '  zavorth setup --json                       Xuất định dạng JSON',
      docker_hint: '  Docker:       docker run -it zavorth setup',
      message: 'Cấu hình yêu cầu terminal tương tác (TTY).',
      non_interactive: 'Tùy chọn không tương tác:',
      or_run: 'Hoặc chạy cấu hình từ phiên bản tương tác:',
      ssh_hint: '  SSH với TTY:  ssh -t user@host',
    },
    home: {
      choose_custom: 'Chọn đường dẫn tùy chỉnh',
      keep_current: 'Giữ ZAVORTH_HOME hiện tại',
      path_prompt: 'Đường dẫn ZAVORTH_HOME',
      prompt: 'Lưu instance này ở đâu...',
      use_isolated: 'Thư mục cô lập bên cạnh dự án',
    },
    hooks: {
      hint: 'tắt cho đến khi xem xét và kích hoạt',
      prompt: 'Chuẩn bị mẫu tự động hóa...',
      title: 'Tự động hóa',
    },
    memory: {
      custom: 'Đường dẫn tùy chỉnh',
      documents: 'Tài liệu',
      downloads: 'Tải xuống',
      local_metadata: 'Siêu dữ liệu cục bộ (sở thích, phê duyệt, tín hiệu sử dụng)',
      local_summary: 'Tóm tắt cục bộ (tóm tắt ngắn dự án/ngữ cảnh)',
      off: 'Tắt (không dùng bộ nhớ khi cấu hình)',
      prompt: 'Chế độ bộ nhớ...',
      skip: 'Bỏ qua bây giờ',
      title: 'Bộ nhớ',
      vault_scope: 'Phạm vi quét bộ nhớ...',
      whole_pc: 'Toàn bộ PC',
    },
    migration: {
      complete: 'Di chuyển hoàn tất. Xem xét các cài đặt đã nhập.',
      path_prompt: 'Đường dẫn thư mục workspace của agent:',
      prompt: 'Di chuyển cài đặt từ agent AI khác...',
      skipped: 'Di chuyển bị bỏ qua hoặc thất bại. Chạy sau: zavorth migrate',
    },
    mode: {
      blank: 'Trang trống',
      blank_hint: 'tối thiểu — kích hoạt từng tính năng riêng',
      complete: 'Cấu hình đầy đủ',
      complete_hint: 'tất cả các bước — nhà cung cấp, kênh, kỹ năng, bộ nhớ',
      prompt_first_run: 'Bạn muốn cấu hình như thế nào...',
      prompt_reconfigure: 'Bạn muốn cấu hình lại như thế nào...',
      quickstart: 'Bắt đầu nhanh',
      quickstart_hint: 'nhanh — chỉ nhà cung cấp, phần còn lại sau',
      safe: 'Chế độ an toàn',
      safe_hint: 'phê duyệt nghiêm ngặt, mặc định ưu tiên cục bộ',
    },
    provider: {
      all_providers: 'Tất cả route nhà cung cấp gốc',
      api_key_prompt: 'Dán API key {provider} (để trống để bỏ qua):',
      auto_detected: 'Tìm thấy API key cho {provider}.',
      auto_selected: 'Sử dụng {provider} với mô hình {model}.',
      manual_prompt: 'Tên nhà cung cấp (vd: openai, anthropic)',
      models_prompt: 'Chọn mô hình cho {provider}:',
      more: 'Thêm nhà cung cấp...',
      none_found: 'Không tìm thấy API key nhà cung cấp LLM trong biến môi trường.',
      select_prompt: 'Bạn muốn sử dụng nhà cung cấp nào...',
      skip: 'Bỏ qua şimdi',
      skip_hint: 'cấu hình sau bằng zavorth providers',
      test_failed: 'Kiểm tra API key thất bại. Sửa sau bằng: zavorth providers',
      testing: 'Đang kiểm tra API key...',
      verified: 'API key đã được xác minh.',
    },
    search: {
      brave: 'Brave Search',
      google: 'Google Search',
      local: 'Cục bộ (không cần API key)',
      prompt: 'Nhà cung cấp tìm kiếm nào...',
      skip: 'Bỏ qua şimdi',
      title: 'Tìm kiếm web',
    },
    section: {
      title: 'Cấu hình — {section}',
    },
    security: {
      confirm_first_run: 'Chào mừng! Sẵn sàng cấu hình Zavorth...',
      confirm_reconfigure: 'Cấu hình lại cài đặt Zavorth hiện có...',
      short: 'Zavorth định tuyến ngôn ngữ tự nhiên đến mô hình, kênh và công cụ cục bộ. Hành động nhạy cảm cần sự chấp thuận của bạn.',
    },
    skill_governance: {
      casual: 'Thân mật',
      casual_hint: 'đề xuất cho sử dụng cá nhân; nhập khẩu nhanh',
      governed: 'Quản trị',
      governed_hint: 'đánh giá doanh nghiệp nghiêm ngặt cho rủi ro, giấy phép',
      prompt: 'Xử lý kỹ năng nhập khẩu như thế nào...',
    },
    summary: {
      backup: 'Sao lưu: {value}',
      channels_label: 'Kênh: {value}',
      env_updated: '.env đã cập nhật ({count} khóa)',
      governance: 'Quản trị kỹ năng: {value}',
      memory_label: 'Bộ nhớ: {value}',
      model: 'Mô hình: {value}',
      next_steps: 'Các bước tiếp theo:',
      provider: 'Nhà cung cấp: {value}',
      step_channels: '  zavorth channels      Kết nối nền tảng nhắn tin',
      step_chat: '  zavorth chat          Bắt đầu trò chuyện với agent',
      step_doctor: '  zavorth doctor        Kiểm tra sức khỏe hệ thống',
      step_providers: '  zavorth providers     Thay đổi hoặc thêm nhà cung cấp',
      title: 'Cấu hình hoàn tất',
    },
    wake_detector: {
      args_prompt: 'Tham số bộ phát hiện đánh thức',
      command_prompt: 'Lệnh bộ phát hiện đánh thức',
      custom_command: 'Lệnh bộ phát hiện tùy chỉnh',
      default_local: 'Bộ phát hiện cục bộ mặc định',
      disabled: 'Giữ tắt',
      prompt: 'Bật thiết lập từ khóa đánh thức Echo...',
    },
    welcome: {
      banner_line1: 'Runtime Agent AI',
      banner_line2: 'Được quản lý. Ưu tiên cục bộ. Của bạn.',
      subtitle: 'Hãy cấu hình tất cả.',
      title: 'Chào mừng đến với Zavorth',
    },
  },
  services: {
  },
  telegram: {
  },
  zavorthControl: {
  },
};

export const tips_vi: PluginTipsSection = {
  tip: {
    bind_capability: 'Gọi ctx.bindCapability(...) cho mỗi capability khai báo trong manifest.json.',
    enable_plugin: 'Chạy: zavorth plugins enable {{pluginId}} --yes hoặc phê duyệt / tin cậy plugin.',
    export_register: 'Xuất `register` hoặc `createZavorthModule` từ index.js (CommonJS: module.exports = { register }).',
  },
};

export const catalog_vi: LocalizationCatalog = {
  ...coreEnglishCatalog,
  legacy: legacy_vi,
  pluginTips: tips_vi,
};
