import type {
  AgentToolSecurityDefinition,
} from './AgentSecurityPolicyEngine.js';
import {
  normalizeAgentToolSecurityDefinition,
} from './AgentSecurityPolicyEngine.js';

export const NATIVE_AGENT_TOOL_SECURITY_DEFINITIONS: AgentToolSecurityDefinition[] = [
  {
    toolName: 'get_datetime',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reads local clock information only.',
  },
  {
    toolName: 'web_search',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Fetches public web evidence and returns it as untrusted content.',
  },
  {
    toolName: 'read_file',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reads local text files through filesystem policy checks.',
  },
  {
    toolName: 'list_directory',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Lists local directory entries through filesystem policy checks.',
  },
  {
    toolName: 'workspace.read',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reads files inside the governed workspace.',
  },
  {
    toolName: 'workspace.list',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Lists files inside the governed workspace.',
  },
  {
    toolName: 'create_file',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Creates or writes a local file.',
  },
  {
    toolName: 'workspace.write',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Writes a file inside the governed workspace.',
  },
  {
    toolName: 'workspace.edit',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Edits a file inside the governed workspace.',
  },
  {
    toolName: 'workspace.apply_patch',
    surface: 'native-tool',
    capabilities: ['filesystem', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Applies a patch inside the governed workspace.',
  },
  {
    toolName: 'workspace.command.propose',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Proposes a command for execution inside the workspace.',
  },
  {
    toolName: 'workspace.command.run',
    surface: 'native-tool',
    capabilities: ['shell', 'filesystem', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Runs a previously proposed and approved command inside the workspace.',
  },
  {
    toolName: 'workspace.host_command.propose',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Proposes a host command for execution inside the workspace using Host Power Mode.',
  },
  {
    toolName: 'workspace.host_command.run',
    surface: 'native-tool',
    capabilities: ['shell', 'filesystem', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Runs a previously proposed and approved host command inside the workspace.',
  },
  {
    toolName: 'workspace.task_mandate.propose',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Proposes a task mandate for execution inside the workspace.',
  },
  {
    toolName: 'remote_shell',
    surface: 'native-tool',
    capabilities: ['shell', 'filesystem', 'destructive'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Runs allowlisted host commands without a subshell.',
  },
  {
    toolName: 'run_sandbox_code',
    surface: 'native-tool',
    capabilities: ['sandbox', 'shell', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes code in a selected sandbox runtime.',
  },
  {
    toolName: 'desktop_automation',
    surface: 'native-tool',
    capabilities: ['desktop', 'destructive'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Controls local desktop UI automation.',
  },
  {
    toolName: 'echo_hands',
    surface: 'native-tool',
    capabilities: ['desktop', 'browser', 'external-send', 'destructive'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Runs supervised Echo Hands local actions.',
  },
  {
    toolName: 'query_external_ai',
    surface: 'native-tool',
    capabilities: ['network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Sends prompts or links to an external AI provider.',
  },
  {
    toolName: 'generate_image',
    surface: 'native-tool',
    capabilities: ['network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Sends image prompts to an external generation provider.',
  },
  {
    toolName: 'analyze_media',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Analyzes untrusted media artifacts and may call model providers.',
  },
  {
    toolName: 'semantic_memory',
    surface: 'native-tool',
    capabilities: ['memory', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Reads or writes durable user memory.',
  },
  {
    toolName: 'enable_mnemos',
    surface: 'native-tool',
    capabilities: ['configuration', 'memory'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Changes memory capability configuration.',
  },
  {
    toolName: 'plan_mnemos_scope',
    surface: 'native-tool',
    capabilities: ['configuration', 'memory', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Builds a confirmable Mnemos scan scope proposal without changing configuration.',
  },
  {
    toolName: 'configure_llm_profile',
    surface: 'native-tool',
    capabilities: ['configuration', 'credential'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Changes default provider/model configuration.',
  },
  {
    toolName: 'zavorth_action',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Routes first-class Zavorth action lookup, preview, apply and receipts through the governed Action Harness. Mutation is approval-gated inside the gateway.',
  },
  {
    toolName: 'auto_skill_creator',
    surface: 'native-tool',
    capabilities: ['skill', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Creates local declarative skill manifests.',
  },
  {
    toolName: 'agent_manager',
    surface: 'native-tool',
    capabilities: ['external-send', 'shell', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Registers, lists, removes, and discovers external agents. Supports natural language input for agent discovery.',
  },
  {
    toolName: 'capability_discovery',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Discovers all capabilities Zavorth has. Read-only, no side effects.',
  },
  {
    toolName: 'nodes',
    surface: 'native-tool',
    capabilities: ['desktop', 'filesystem', 'shell', 'network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Lists, previews and queues governed Node Mesh companion invocations.',
  },
  {
    toolName: 'workspace.pty.propose',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Proposes a new interactive PTY terminal session.',
  },
  {
    toolName: 'workspace.pty.write',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Writes input to an active interactive PTY terminal session. Governed by PtyInputPolicyService.',
  },
  {
    toolName: 'workspace.pty.terminate',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Terminates an active interactive PTY terminal session.',
  },
  {
    toolName: 'generate_video',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Generates videos from text prompts or reference images.',
  },
  {
    toolName: 'kanban_board',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Manages Kanban boards for task organization.',
  },
  {
    toolName: 'skill_feedback',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Collects skill execution feedback for self-improvement.',
  },
  {
    toolName: 'batch_trajectory',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes multiple agent trajectories in parallel and compares results.',
  },
  {
    toolName: 'terminal_backend',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes commands in different terminal backends.',
  },
  {
    toolName: 'send_email',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Sends emails via configured SMTP.',
  },
  {
    toolName: 'calendar_event',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Manages calendar events.',
  },
  {
    toolName: 'code_review',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Performs code review with structured feedback.',
  },
  {
    toolName: 'database_query',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes queries on local SQLite databases.',
  },
  {
    toolName: 'zavorth_cron_scheduler',
    surface: 'native-tool',
    capabilities: ['configuration', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Creates and manages scheduled cron jobs with risk scoring.',
  },
  {
    toolName: 'zavorth_delegate',
    surface: 'native-tool',
    capabilities: ['sandbox', 'skill'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Delegates tasks to governed subagents with batch support.',
  },
  {
    toolName: 'zavorth_computer_use',
    surface: 'native-tool',
    capabilities: ['desktop', 'shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Controls desktop via screenshot, click, type, scroll, drag.',
  },
  {
    toolName: 'zavorth_voice_mode',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Manages voice sessions with STT, TTS, and wake word detection.',
  },
  {
    toolName: 'zavorth_session_search',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Searches past conversations and sessions.',
  },
  {
    toolName: 'zavorth_channel_send',
    surface: 'native-tool',
    capabilities: ['external-send', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Sends messages to 26+ messaging channels.',
  },
  {
    toolName: 'zavorth_document_extractor',
    surface: 'native-tool',
    capabilities: ['filesystem', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Extracts text from PDF, DOCX, XLSX, CSV, HTML documents.',
  },
  {
    toolName: 'zavorth_tts',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Converts text to speech using multiple backends.',
  },
  {
    toolName: 'zavorth_stt',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Converts speech to text using multiple backends.',
  },
  {
    toolName: 'zavorth_receipt_search',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Searches and audits action receipts.',
  },
  {
    toolName: 'zavorth_policy_enforcer',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Checks actions against governance policies.',
  },
  {
    toolName: 'zavorth_api_client',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Governed HTTP client with EgressGuard.',
  },
  {
    toolName: 'zavorth_trajectory_export',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Exports execution trajectories for training.',
  },
  {
    toolName: 'zavorth_security_guidance',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Provides security guidance, OWASP Top 10, code scanning.',
  },
  {
    toolName: 'zavorth_novita',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Novita AI provider for open-source models.',
  },
  {
    toolName: 'zavorth_replicate',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Replicate ML model execution.',
  },
  {
    toolName: 'zavorth_huggingface',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'HuggingFace Inference API.',
  },
  {
    toolName: 'zavorth_firecrawl',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Firecrawl web scraping and extraction.',
  },
  {
    toolName: 'zavorth_fal',
    surface: 'native-tool',
    capabilities: ['network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'fal.ai image generation.',
  },
  {
    toolName: 'zavorth_comfyui',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem', 'sandbox'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'ComfyUI local image generation.',
  },
  {
    toolName: 'zavorth_searxng',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'SearXNG private meta-search engine.',
  },
  {
    toolName: 'zavorth_runway',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Runway ML video generation.',
  },
  {
    toolName: 'zavorth_spotify',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Spotify music player control.',
  },
  {
    toolName: 'zavorth_docker_compose',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Docker Compose multi-container management.',
  },
  {
    toolName: 'zavorth_code_intelligence',
    surface: 'native-tool',
    capabilities: ['filesystem', 'shell'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Code analysis, formatting, linting, and symbol extraction.',
  },
  {
    toolName: 'zavorth_ssh_tunnel',
    surface: 'native-tool',
    capabilities: ['network', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'SSH tunnel creation and management.',
  },
  {
    toolName: 'zavorth_chart_generator',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Chart and visualization generation from data.',
  },
  {
    toolName: 'zavorth_file_watcher',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'File system change monitoring and event logging.',
  },
  {
    toolName: 'zavorth_network',
    surface: 'native-tool',
    capabilities: ['network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Network diagnostics — DNS, port scan, ping, traceroute, WHOIS.',
  },
  {
    toolName: 'zavorth_webhook_receiver',
    surface: 'native-tool',
    capabilities: ['network', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'HTTP webhook endpoint creation and request logging.',
  },
  {
    toolName: 'zavorth_mcp_marketplace',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'MCP server marketplace — discover, install, manage MCP servers.',
  },
  {
    toolName: 'zavorth_skill_marketplace',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Skill marketplace — discover, install, publish, and manage Zavorth skills.',
  },
  {
    toolName: 'zavorth_git_lock',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Manage git file locks to prevent conflicts between concurrent subagents.',
  },
  {
    toolName: 'zavorth_agent_governance',
    surface: 'native-tool',
    capabilities: ['local-observation', 'audit'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Agent governance — runtime guardrails, compliance checks, audit trails.',
  },
  {
    toolName: 'zavorth_rag_builder',
    surface: 'native-tool',
    capabilities: ['filesystem', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'RAG pipeline builder — chunk, embed, index, query with source verification.',
  },
  {
    toolName: 'zavorth_agent_eval',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Agent evaluation — benchmark quality, run test suites, generate reports.',
  },
  {
    toolName: 'zavorth_privacy_vault',
    surface: 'native-tool',
    capabilities: ['filesystem', 'encryption'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Privacy vault — encrypted storage for secrets with audit logging.',
  },
  {
    toolName: 'zavorth_multi_repo',
    surface: 'native-tool',
    capabilities: ['filesystem', 'shell', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Multi-repo operations — clone, sync, diff, PR across multiple Git repos.',
  },
  {
    toolName: 'zavorth_doc_provider',
    surface: 'native-tool',
    capabilities: ['network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Live documentation provider — fetch up-to-date docs for any library.',
  },
  {
    toolName: 'zavorth_prompt_library',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Prompt library — optimized templates by task with versioning and quality tracking.',
  },
  {
    toolName: 'zavorth_token_budget',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Token budget manager — track, limit, and optimize token usage.',
  },
  {
    toolName: 'zavorth_memory_graph',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Memory knowledge graph — semantic connections between facts, concepts, events.',
  },
  {
    toolName: 'zavorth_sandbox_cloud',
    surface: 'native-tool',
    capabilities: ['shell', 'network', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Cloud sandbox — execute code in remote isolated environments.',
  },
  {
    toolName: 'zavorth_workflow_builder',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Visual workflow builder — create and execute complex workflows via API.',
  },
  {
    toolName: 'zavorth_edge_computing',
    surface: 'native-tool',
    capabilities: ['network', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Edge computing — deploy code to edge networks (Cloudflare, Deno, Vercel).',
  },
  {
    toolName: 'zavorth_browser_automation',
    surface: 'native-tool',
    capabilities: ['browser', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced browser automation via Playwright.',
  },
  {
    toolName: 'zavorth_code_formatter',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Code formatting with prettier, black, rustfmt, gofmt.',
  },
  {
    toolName: 'zavorth_dependency_analyzer',
    surface: 'native-tool',
    capabilities: ['filesystem', 'network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Dependency analysis — outdated, vulnerabilities, licenses.',
  },
  {
    toolName: 'zavorth_git_advanced',
    surface: 'native-tool',
    capabilities: ['filesystem', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced git operations — bisect, blame, stash, rebase.',
  },
  {
    toolName: 'zavorth_data_science',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Data science operations — statistics, correlation, regression.',
  },
  {
    toolName: 'zavorth_ml_ops',
    surface: 'native-tool',
    capabilities: ['filesystem', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'ML operations — train, evaluate, deploy, monitor.',
  },
  {
    toolName: 'zavorth_container_manager',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Container management — Docker ps, logs, exec, build, compose.',
  },
  {
    toolName: 'zavorth_database_admin',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Database admin — query, schema, backup, restore, migrate.',
  },
  {
    toolName: 'zavorth_filesystem_advanced',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced file operations — watch, compress, batch rename, dedup.',
  },
  {
    toolName: 'zavorth_network_diagnostics',
    surface: 'native-tool',
    capabilities: ['network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Network diagnostics — traceroute, port scan, DNS, SSL check.',
  },
  {
    toolName: 'zavorth_security_scanner',
    surface: 'native-tool',
    capabilities: ['filesystem', 'network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Security scanning — CVE, secrets, SAST, config audit.',
  },
  {
    toolName: 'zavorth_cloud_storage',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Cloud storage — S3, GCS, Azure Blob operations.',
  },
  {
    toolName: 'zavorth_email_advanced',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced email — IMAP read, SMTP send, templates, bulk.',
  },
  {
    toolName: 'zavorth_calendar_advanced',
    surface: 'native-tool',
    capabilities: ['network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced calendar — Google, Outlook, recurring events.',
  },
  {
    toolName: 'zavorth_notification',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Notifications — desktop, Slack, Discord, Telegram, webhook.',
  },
  {
    toolName: 'zavorth_api_builder',
    surface: 'native-tool',
    capabilities: ['filesystem', 'network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'API builder — OpenAPI spec, endpoints, mock server, tests.',
  },
  {
    toolName: 'zavorth_terminal_backends',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced terminal with 6 backends: local, docker, ssh, wsl, singularity, modal.',
  },
  {
    toolName: 'llm_router',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Per-task model routing with fallback chains and cost budget.',
  },
  {
    toolName: 'context_compressor',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Context compression with 4 strategies (conservative, balanced, aggressive, fact-only).',
  },
  {
    toolName: 'reasoning_effort',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reasoning effort configuration with 10 task profiles.',
  },
  {
    toolName: 'prompt_cache',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Prompt caching with common prefix extraction.',
  },
  {
    toolName: 'llm_self_edit_context',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Self-editing context management inspired by Chroma Context-1.',
  },
  {
    toolName: 'llm_model_switcher',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Model switching with cost optimization and 8 model profiles.',
  },
  {
    toolName: 'llm_drift_detector',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Drift detection for topic, repetition, quality, and hallucination risk.',
  },
  {
    toolName: 'streaming_llm',
    surface: 'service',
    capabilities: ['network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Real-time LLM response streaming from 6 providers.',
  },
  {
    toolName: 'auto_skill_generator',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Auto-generates skills from workflow patterns.',
  },
  {
    toolName: 'zavorth_vision',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Vision intelligence — image analysis via multi-provider.',
  },
  {
    toolName: 'zavorth_audio_analyzer',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Audio intelligence — transcription via multi-provider.',
  },
  {
    toolName: 'zavorth_video_analyzer',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Video intelligence — analysis via multi-provider.',
  },
  {
    toolName: 'usage_analytics',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Usage tracking with cost and latency metrics.',
  },
  {
    toolName: 'cost_analytics',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Cost analysis by provider, model, and task type.',
  },
  {
    toolName: 'quality_metrics',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Quality metrics with feedback tracking.',
  },
  {
    toolName: 'multi_user',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Multi-user management with roles and permissions.',
  },
  {
    toolName: 'shared_workspace',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Shared workspace management with member access.',
  },
  {
    toolName: 'role_based_access',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Role-based access control with policies.',
  },
  {
    toolName: 'circuit_breaker',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Circuit breaker pattern for provider resilience.',
  },
  {
    toolName: 'retry_service',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Intelligent retry with exponential backoff.',
  },
  {
    toolName: 'health_check',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Component health monitoring and status tracking.',
  },
  {
    toolName: 'backup_service',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Backup and restore with path validation.',
  },
  {
    toolName: 'plugin_marketplace',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Plugin marketplace with discovery, install, and ratings.',
  },
  {
    toolName: 'document_intelligence',
    surface: 'service',
    capabilities: ['filesystem', 'network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Document analysis with multi-format support and LLM language detection.',
  },
  {
    toolName: 'code_intelligence',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Code analysis with metrics, functions, classes, and issues detection.',
  },
  {
    toolName: 'data_pipeline',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Data pipeline with extract, transform, load, filter, aggregate, sort.',
  },
  {
    toolName: 'notification_center',
    surface: 'service',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Notification center with multi-channel support.',
  },
  {
    toolName: 'version_control',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Version control for files with commit, revert, diff, tag.',
  },
  {
    toolName: 'memory_supermemory',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Semantic memory with compression and consolidation.',
  },
  {
    toolName: 'memory_byterover',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Memory with auto-categorization and entity extraction.',
  },
  {
    toolName: 'memory_hindsight',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Decision tracking with outcome-based learning.',
  },
  {
    toolName: 'memory_holographic',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Multi-path memory retrieval (topic, time, emotion, context).',
  },
  {
    toolName: 'memory_retaindb',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Memory with retention policies (forever, expire, keep_last).',
  },
  {
    toolName: 'memory_semantic_cache',
    surface: 'service',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Semantic cache with topic-based retrieval.',
  },
  {
    toolName: 'companion_ios',
    surface: 'service',
    capabilities: ['network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'iOS companion app integration.',
  },
  {
    toolName: 'companion_android',
    surface: 'service',
    capabilities: ['network'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Android companion app integration.',
  },
  {
    toolName: 'terminal_backends',
    surface: 'native-tool',
    capabilities: ['local-observation', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Manages and executes commands across multiple terminal backends.',
  },
  {
    toolName: 'zavorth_file_system_advanced',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Advanced filesystem operations.',
  },
  {
    toolName: 'streaming_byte_guard',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Guards against unlimited stream consumption from providers.',
  },
  {
    toolName: 'auth_rate_limiter',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Rate limiting for authentication attempts.',
  },
  {
    toolName: 'mcp_plugin_tools',
    surface: 'native-tool',
    capabilities: ['mcp', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Exposes Zavorth tools via MCP protocol for external clients.',
  },
  {
    toolName: 'url_safety',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'URL safety validation with DNS resolution and SSRF protection.',
  },
  {
    toolName: 'model_fallback_chain',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Multi-candidate model fallback with per-provider cooldown.',
  },
  {
    toolName: 'session_persistence',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'SQLite-backed session persistence for runtime state.',
  },
  {
    toolName: 'session_search_fts5',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Full-text search across sessions with zero LLM cost.',
  },
  {
    toolName: 'session_search',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Canonical full-text session search (Session Continuum / FTS).',
  },
  {
    toolName: 'sessions.search',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Alias for canonical session search.',
  },
  {
    toolName: 'mixture_of_agents',
    surface: 'native-tool',
    capabilities: ['local-observation', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Multi-model consensus orchestration.',
  },
  {
    toolName: 'browser_cdp_supervisor',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Persistent browser control via CDP WebSocket.',
  },
  {
    toolName: 'mcp_oauth_manager',
    surface: 'native-tool',
    capabilities: ['network', 'credential_or_config'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'OAuth 2.1 token management for MCP servers.',
  },
  {
    toolName: 'llm_fallback_router',
    surface: 'native-tool',
    capabilities: ['local-observation', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Integrated LLM routing with progressive fallback.',
  },
  {
    toolName: 'persistent_memory_bridge',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Bridge between InfiniteMemoryCompressor and disk persistence.',
  },
  {
    toolName: 'moa_with_fallback',
    surface: 'native-tool',
    capabilities: ['local-observation', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Mixture of Agents with integrated fallback routing.',
  },
  {
    toolName: 'browser_cdp_control',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Browser control via CDP WebSocket.',
  },
  {
    toolName: 'rbac_engine',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Role-Based Access Control engine for permission management.',
  },
  {
    toolName: 'abac_engine',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Attribute-Based Access Control engine for policy evaluation.',
  },
  {
    toolName: 'access_control',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Integrated access control combining RBAC and ABAC.',
  },
];

export const BOOTSTRAP_NATIVE_TOOL_SECURITY_MANIFEST = [
  { className: 'UnifiedSearchTool', toolName: 'web_search' },
  { className: 'CreateFileTool', toolName: 'create_file' },
  { className: 'ReadFileTool', toolName: 'read_file' },
  { className: 'ListDirectoryTool', toolName: 'list_directory' },
  { className: 'WorkspaceReadTool', toolName: 'workspace.read' },
  { className: 'WorkspaceListTool', toolName: 'workspace.list' },
  { className: 'WorkspaceWriteTool', toolName: 'workspace.write' },
  { className: 'WorkspaceEditTool', toolName: 'workspace.edit' },
  { className: 'WorkspaceApplyPatchTool', toolName: 'workspace.apply_patch' },
  { className: 'WorkspaceCommandProposeTool', toolName: 'workspace.command.propose' },
  { className: 'WorkspaceCommandRunTool', toolName: 'workspace.command.run' },
  { className: 'HostCommandProposeTool', toolName: 'workspace.host_command.propose' },
  { className: 'HostCommandRunTool', toolName: 'workspace.host_command.run' },
  { className: 'PtySessionProposeTool', toolName: 'workspace.pty.propose' },
  { className: 'PtyWriteTool', toolName: 'workspace.pty.write' },
  { className: 'PtyTerminateTool', toolName: 'workspace.pty.terminate' },
  { className: 'WorkspaceTaskMandateProposeTool', toolName: 'workspace.task_mandate.propose' },
  { className: 'DateTimeTool', toolName: 'get_datetime' },
  { className: 'RemoteShellTool', toolName: 'remote_shell' },
  { className: 'QueryExternalAiTool', toolName: 'query_external_ai' },
  { className: 'SandboxExecutionTool', toolName: 'run_sandbox_code' },
  { className: 'Mem0Tool', toolName: 'semantic_memory' },
  { className: 'DesktopAutomationTool', toolName: 'desktop_automation' },
  { className: 'PlanMnemosScopeTool', toolName: 'plan_mnemos_scope' },
  { className: 'EnableMnemosTool', toolName: 'enable_mnemos' },
  { className: 'EchoHandsTool', toolName: 'echo_hands' },
  { className: 'ConfigureLlmProfileTool', toolName: 'configure_llm_profile' },
  { className: 'ZavorthActionTool', toolName: 'zavorth_action' },
  { className: 'AutoSkillCreatorTool', toolName: 'auto_skill_creator' },
  { className: 'ImageGenerationTool', toolName: 'generate_image' },
  { className: 'MediaAnalysisTool', toolName: 'analyze_media' },
  { className: 'NodeMeshTool', toolName: 'nodes' },
  { className: 'VideoGenerationTool', toolName: 'generate_video' },
  { className: 'KanbanTool', toolName: 'kanban_board' },
  { className: 'SkillFeedbackCollectorTool', toolName: 'skill_feedback' },
  { className: 'BatchTrajectoryTool', toolName: 'batch_trajectory' },
  { className: 'MultiBackendTerminalTool', toolName: 'terminal_backend' },
  { className: 'EmailTool', toolName: 'send_email' },
  { className: 'CalendarTool', toolName: 'calendar_event' },
  { className: 'CodeReviewTool', toolName: 'code_review' },
  { className: 'DatabaseQueryTool', toolName: 'database_query' },
  { className: 'ZavorthCronSchedulerTool', toolName: 'zavorth_cron_scheduler' },
  { className: 'ZavorthDelegateTool', toolName: 'zavorth_delegate' },
  { className: 'ZavorthComputerUseTool', toolName: 'zavorth_computer_use' },
  { className: 'ZavorthVoiceModeTool', toolName: 'zavorth_voice_mode' },
  { className: 'ZavorthSessionSearchTool', toolName: 'zavorth_session_search' },
  { className: 'ZavorthChannelSendTool', toolName: 'zavorth_channel_send' },
  { className: 'ZavorthDocumentExtractorTool', toolName: 'zavorth_document_extractor' },
  { className: 'ZavorthTtsTool', toolName: 'zavorth_tts' },
  { className: 'ZavorthSttTool', toolName: 'zavorth_stt' },
  { className: 'ZavorthReceiptSearchTool', toolName: 'zavorth_receipt_search' },
  { className: 'ZavorthPolicyEnforcerTool', toolName: 'zavorth_policy_enforcer' },
  { className: 'ZavorthApiClientTool', toolName: 'zavorth_api_client' },
  { className: 'ZavorthTrajectoryExportTool', toolName: 'zavorth_trajectory_export' },
  { className: 'SecurityGuidanceService', toolName: 'zavorth_security_guidance' },
  { className: 'ProviderNovitaTool', toolName: 'zavorth_novita' },
  { className: 'ProviderReplicateTool', toolName: 'zavorth_replicate' },
  { className: 'ProviderHuggingFaceTool', toolName: 'zavorth_huggingface' },
  { className: 'WebFirecrawlTool', toolName: 'zavorth_firecrawl' },
  { className: 'ImageGenFalTool', toolName: 'zavorth_fal' },
  { className: 'ImageGenComfyUITool', toolName: 'zavorth_comfyui' },
  { className: 'SearchSearXNGTool', toolName: 'zavorth_searxng' },
  { className: 'VideoGenRunwayTool', toolName: 'zavorth_runway' },
  { className: 'SpotifyPlayerTool', toolName: 'zavorth_spotify' },
  { className: 'ZavorthDockerComposeTool', toolName: 'zavorth_docker_compose' },
  { className: 'ZavorthCodeIntelligenceTool', toolName: 'zavorth_code_intelligence' },
  { className: 'ZavorthSshTunnelTool', toolName: 'zavorth_ssh_tunnel' },
  { className: 'ZavorthChartGeneratorTool', toolName: 'zavorth_chart_generator' },
  { className: 'ZavorthFileWatcherTool', toolName: 'zavorth_file_watcher' },
  { className: 'ZavorthNetworkTool', toolName: 'zavorth_network' },
  { className: 'ZavorthWebhookReceiverTool', toolName: 'zavorth_webhook_receiver' },
  { className: 'ZavorthMcpMarketplaceTool', toolName: 'zavorth_mcp_marketplace' },
  { className: 'ZavorthSkillMarketplaceTool', toolName: 'zavorth_skill_marketplace' },
  { className: 'ZavorthGitLockTool', toolName: 'zavorth_git_lock' },
  { className: 'ZavorthAgentGovernanceTool', toolName: 'zavorth_agent_governance' },
  { className: 'ZavorthRagBuilderTool', toolName: 'zavorth_rag_builder' },
  { className: 'ZavorthAgentEvalTool', toolName: 'zavorth_agent_eval' },
  { className: 'ZavorthPrivacyVaultTool', toolName: 'zavorth_privacy_vault' },
  { className: 'ZavorthMultiRepoTool', toolName: 'zavorth_multi_repo' },
  { className: 'ZavorthDocProviderTool', toolName: 'zavorth_doc_provider' },
  { className: 'ZavorthPromptLibraryTool', toolName: 'zavorth_prompt_library' },
  { className: 'ZavorthTokenBudgetTool', toolName: 'zavorth_token_budget' },
  { className: 'ZavorthMemoryGraphTool', toolName: 'zavorth_memory_graph' },
  { className: 'ZavorthSandboxCloudTool', toolName: 'zavorth_sandbox_cloud' },
  { className: 'ZavorthWorkflowBuilderTool', toolName: 'zavorth_workflow_builder' },
  { className: 'ZavorthEdgeComputingTool', toolName: 'zavorth_edge_computing' },
  { className: 'ZavorthBrowserAutomationTool', toolName: 'zavorth_browser_automation' },
  { className: 'ZavorthCodeFormatterTool', toolName: 'zavorth_code_formatter' },
  { className: 'ZavorthDependencyAnalyzerTool', toolName: 'zavorth_dependency_analyzer' },
  { className: 'ZavorthGitAdvancedTool', toolName: 'zavorth_git_advanced' },
  { className: 'ZavorthDataScienceTool', toolName: 'zavorth_data_science' },
  { className: 'ZavorthMlOpsTool', toolName: 'zavorth_ml_ops' },
  { className: 'ZavorthContainerManagerTool', toolName: 'zavorth_container_manager' },
  { className: 'ZavorthDatabaseAdminTool', toolName: 'zavorth_database_admin' },
  { className: 'ZavorthFileSystemAdvancedTool', toolName: 'zavorth_file_system_advanced' },
  { className: 'ZavorthNetworkDiagnosticsTool', toolName: 'zavorth_network_diagnostics' },
  { className: 'ZavorthSecurityScannerTool', toolName: 'zavorth_security_scanner' },
  { className: 'ZavorthCloudStorageTool', toolName: 'zavorth_cloud_storage' },
  { className: 'ZavorthEmailAdvancedTool', toolName: 'zavorth_email_advanced' },
  { className: 'ZavorthCalendarAdvancedTool', toolName: 'zavorth_calendar_advanced' },
  { className: 'ZavorthNotificationTool', toolName: 'zavorth_notification' },
  { className: 'ZavorthApiBuilderTool', toolName: 'zavorth_api_builder' },
  { className: 'ZavorthTerminalBackendsTool', toolName: 'terminal_backends' },
  { className: 'AgentManagerTool', toolName: 'agent_manager' },
  { className: 'CapabilityDiscoveryTool', toolName: 'capability_discovery' },
  { className: 'LLMRouterService', toolName: 'llm_router' },
  { className: 'ContextCompressorService', toolName: 'context_compressor' },
  { className: 'ReasoningEffortService', toolName: 'reasoning_effort' },
  { className: 'PromptCacheService', toolName: 'prompt_cache' },
  { className: 'LLMSelfEditContextService', toolName: 'llm_self_edit_context' },
  { className: 'LLMModelSwitcherService', toolName: 'llm_model_switcher' },
  { className: 'LLMDriftDetectorService', toolName: 'llm_drift_detector' },
  { className: 'StreamingLLMService', toolName: 'streaming_llm' },
  { className: 'AutoSkillGeneratorService', toolName: 'auto_skill_generator' },
  { className: 'ZavorthVisionService', toolName: 'zavorth_vision' },
  { className: 'ZavorthAudioAnalyzerService', toolName: 'zavorth_audio_analyzer' },
  { className: 'ZavorthVideoAnalyzerService', toolName: 'zavorth_video_analyzer' },
  { className: 'UsageAnalyticsService', toolName: 'usage_analytics' },
  { className: 'CostAnalyticsService', toolName: 'cost_analytics' },
  { className: 'QualityMetricsService', toolName: 'quality_metrics' },
  { className: 'MultiUserService', toolName: 'multi_user' },
  { className: 'SharedWorkspaceService', toolName: 'shared_workspace' },
  { className: 'RoleBasedAccessService', toolName: 'role_based_access' },
  { className: 'CircuitBreakerService', toolName: 'circuit_breaker' },
  { className: 'RetryService', toolName: 'retry_service' },
  { className: 'HealthCheckService', toolName: 'health_check' },
  { className: 'BackupService', toolName: 'backup_service' },
  { className: 'ZavorthPluginMarketplaceService', toolName: 'plugin_marketplace' },
  { className: 'DocumentIntelligenceService', toolName: 'document_intelligence' },
  { className: 'CodeIntelligenceService', toolName: 'code_intelligence' },
  { className: 'DataPipelineService', toolName: 'data_pipeline' },
  { className: 'NotificationCenterService', toolName: 'notification_center' },
  { className: 'VersionControlService', toolName: 'version_control' },
  { className: 'MemorySupermemoryService', toolName: 'memory_supermemory' },
  { className: 'MemoryByteroverService', toolName: 'memory_byterover' },
  { className: 'MemoryHindsightService', toolName: 'memory_hindsight' },
  { className: 'MemoryHolographicService', toolName: 'memory_holographic' },
  { className: 'MemoryRetainDBService', toolName: 'memory_retaindb' },
  { className: 'MemorySemanticCacheService', toolName: 'memory_semantic_cache' },
  { className: 'CompanionIOSService', toolName: 'companion_ios' },
  { className: 'CompanionAndroidService', toolName: 'companion_android' },
  { className: 'StreamingByteGuard', toolName: 'streaming_byte_guard' },
  { className: 'AuthRateLimiter', toolName: 'auth_rate_limiter' },
  { className: 'McpPluginToolsServer', toolName: 'mcp_plugin_tools' },
  { className: 'UrlSafetyService', toolName: 'url_safety' },
  { className: 'ModelFallbackChain', toolName: 'model_fallback_chain' },
  { className: 'SessionPersistenceStore', toolName: 'session_persistence' },
  { className: 'SessionSearchFts5Tool', toolName: 'session_search' },
  { className: 'MixtureOfAgents', toolName: 'mixture_of_agents' },
  { className: 'BrowserCdpSupervisor', toolName: 'browser_cdp_supervisor' },
  { className: 'McpOAuthManager', toolName: 'mcp_oauth_manager' },
  { className: 'LLMFallbackRouter', toolName: 'llm_fallback_router' },
  { className: 'PersistentMemoryBridge', toolName: 'persistent_memory_bridge' },
  { className: 'MoAWithFallback', toolName: 'moa_with_fallback' },
  { className: 'BrowserCdpSupervisorTool', toolName: 'browser_cdp_control' },
  { className: 'McpOAuthManagerTool', toolName: 'mcp_oauth_manager' },
  { className: 'RbacEngine', toolName: 'rbac_engine' },
  { className: 'AbacEngine', toolName: 'abac_engine' },
  { className: 'AccessControlService', toolName: 'access_control' },
] as const;

const NATIVE_DEFINITIONS_BY_NAME = new Map(
  NATIVE_AGENT_TOOL_SECURITY_DEFINITIONS.map((definition) => [
    definition.toolName.toLowerCase(),
    normalizeAgentToolSecurityDefinition({ ...definition, source: 'explicit' }),
  ]),
);

export function listExplicitNativeToolSecurityNames(): string[] {
  return Array.from(NATIVE_DEFINITIONS_BY_NAME.keys()).sort();
}

export function findMissingExplicitNativeToolSecurityDefinitions(toolNames: string[]): string[] {
  return Array.from(
    new Set(
      toolNames
        .map((toolName) => String(toolName || '').trim().toLowerCase())
        .filter(Boolean)
        .filter((toolName) => !NATIVE_DEFINITIONS_BY_NAME.has(toolName)),
    ),
  ).sort();
}

export function assertExplicitNativeToolSecurityDefinitions(toolNames: string[]): void {
  const missing = findMissingExplicitNativeToolSecurityDefinitions(toolNames);
  if (missing.length > 0) {
    throw new Error(
      `Missing explicit native tool security definition(s): ${missing.join(', ')}. `
      + 'Add them to NATIVE_AGENT_TOOL_SECURITY_DEFINITIONS before exposing the tool.',
    );
  }
}

export function createMcpAgentToolSecurityDefinition(
  toolName: string,
  description = 'External MCP tool exposed to the local agent runtime.',
): AgentToolSecurityDefinition {
  return normalizeAgentToolSecurityDefinition({
    toolName,
    surface: 'mcp-tool',
    capabilities: ['mcp', 'network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description,
    source: 'inferred',
  });
}

export function createFallbackAgentToolSecurityDefinition(
  toolName: string,
  description = 'Registered tool without an explicit security definition.',
): AgentToolSecurityDefinition {
  return normalizeAgentToolSecurityDefinition({
    toolName,
    surface: 'unknown',
    capabilities: ['unknown'],
    defaultRisk: 'forbidden',
    requiresConfirmation: false,
    description,
    source: 'fallback',
  });
}

export function resolveDefaultAgentToolSecurityDefinition(
  toolName: string,
  description?: string,
): AgentToolSecurityDefinition {
  const normalized = String(toolName || '').trim().toLowerCase();
  const known = NATIVE_DEFINITIONS_BY_NAME.get(normalized);
  if (known) {
    return {
      ...known,
      capabilities: [...known.capabilities],
    };
  }

  return createFallbackAgentToolSecurityDefinition(toolName, description);
}


