import type {
  AgentToolSecurityDefinition,
} from './AgentSecurityPolicyEngine.js';
import {
  normalizeAgentToolSecurityDefinition,
} from './AgentSecurityPolicyEngine.js';

export const NATIVE_AGENT_TOOL_SECURITY_DEFINITIONS: AgentToolSecurityDefinition[] = [
  {
    toolName: 'get_datetime',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reads local clock information only.',
  },
  {
    toolName: 'web_search',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Fetches public web evidence and returns it as untrusted content.',
  },
  {
    toolName: 'read_file',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reads local text files through filesystem policy checks.',
  },
  {
    toolName: 'list_directory',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Lists local directory entries through filesystem policy checks.',
  },
  {
    toolName: 'workspace.read',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Reads files inside the governed workspace.',
  },
  {
    toolName: 'workspace.list',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Lists files inside the governed workspace.',
  },
  {
    toolName: 'create_file',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Creates or writes a local file.',
  },
  {
    toolName: 'workspace.write',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Writes a file inside the governed workspace.',
  },
  {
    toolName: 'workspace.edit',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Edits a file inside the governed workspace.',
  },
  {
    toolName: 'workspace.apply_patch',
    surface: 'native-tool',
    capabilities: ['filesystem', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Applies a patch inside the governed workspace.',
  },
  {
    toolName: 'workspace.command.propose',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Proposes a command for execution inside the workspace.',
  },
  {
    toolName: 'workspace.command.run',
    surface: 'native-tool',
    capabilities: ['shell', 'filesystem', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Runs a previously proposed and approved command inside the workspace.',
  },
  {
    toolName: 'workspace.host_command.propose',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Proposes a host command for execution inside the workspace using Host Power Mode.',
  },
  {
    toolName: 'workspace.host_command.run',
    surface: 'native-tool',
    capabilities: ['shell', 'filesystem', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Runs a previously proposed and approved host command inside the workspace.',
  },
  {
    toolName: 'workspace.task_mandate.propose',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Proposes a task mandate for execution inside the workspace.',
  },
  {
    toolName: 'remote_shell',
    surface: 'native-tool',
    capabilities: ['shell', 'filesystem', 'destructive'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Runs allowlisted host commands without a subshell.',
  },
  {
    toolName: 'run_sandbox_code',
    surface: 'native-tool',
    capabilities: ['sandbox', 'shell', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes code in a selected sandbox runtime.',
  },
  {
    toolName: 'desktop_automation',
    surface: 'native-tool',
    capabilities: ['desktop', 'destructive'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Controls local desktop UI automation.',
  },
  {
    toolName: 'echo_hands',
    surface: 'native-tool',
    capabilities: ['desktop', 'browser', 'external-send', 'destructive'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Runs supervised Echo Hands local actions.',
  },
  {
    toolName: 'query_external_ai',
    surface: 'native-tool',
    capabilities: ['network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Sends prompts or links to an external AI provider.',
  },
  {
    toolName: 'generate_image',
    surface: 'native-tool',
    capabilities: ['network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Sends image prompts to an external generation provider.',
  },
  {
    toolName: 'analyze_media',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Analyzes untrusted media artifacts and may call model providers.',
  },
  {
    toolName: 'semantic_memory',
    surface: 'native-tool',
    capabilities: ['memory', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Reads or writes durable user memory.',
  },
  {
    toolName: 'enable_mnemos',
    surface: 'native-tool',
    capabilities: ['configuration', 'memory'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Changes memory capability configuration.',
  },
  {
    toolName: 'plan_mnemos_scope',
    surface: 'native-tool',
    capabilities: ['configuration', 'memory', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Builds a confirmable Mnemos scan scope proposal without changing configuration.',
  },
  {
    toolName: 'configure_llm_profile',
    surface: 'native-tool',
    capabilities: ['configuration', 'credential'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Changes default provider/model configuration.',
  },
  {
    toolName: 'zavorth_action',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Routes first-class Zavorth action lookup, preview, apply and receipts through the governed Action Harness. Mutation is approval-gated inside the gateway.',
  },
  {
    toolName: 'auto_skill_creator',
    surface: 'native-tool',
    capabilities: ['skill', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Creates local declarative skill manifests.',
  },
  {
    toolName: 'nodes',
    surface: 'native-tool',
    capabilities: ['desktop', 'filesystem', 'shell', 'network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Lists, previews and queues governed Node Mesh companion invocations.',
  },
  {
    toolName: 'workspace.pty.propose',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Proposes a new interactive PTY terminal session.',
  },
  {
    toolName: 'workspace.pty.write',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Writes input to an active interactive PTY terminal session. Governed by PtyInputPolicyService.',
  },
  {
    toolName: 'workspace.pty.terminate',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Terminates an active interactive PTY terminal session.',
  },
  {
    toolName: 'generate_video',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Generates videos from text prompts or reference images.',
  },
  {
    toolName: 'kanban_board',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Manages Kanban boards for task organization.',
  },
  {
    toolName: 'skill_feedback',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Collects skill execution feedback for self-improvement.',
  },
  {
    toolName: 'batch_trajectory',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes multiple agent trajectories in parallel and compares results.',
  },
  {
    toolName: 'terminal_backend',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes commands in different terminal backends.',
  },
  {
    toolName: 'send_email',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'dangerous',
    requiresConfirmation: true,
    description: 'Sends emails via configured SMTP.',
  },
  {
    toolName: 'calendar_event',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Manages calendar events.',
  },
  {
    toolName: 'code_review',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Performs code review with structured feedback.',
  },
  {
    toolName: 'database_query',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Executes queries on local SQLite databases.',
  },
  {
    toolName: 'zavorth_cron_scheduler',
    surface: 'native-tool',
    capabilities: ['configuration', 'filesystem'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Creates and manages scheduled cron jobs with risk scoring.',
  },
  {
    toolName: 'zavorth_delegate',
    surface: 'native-tool',
    capabilities: ['sandbox', 'skill'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Delegates tasks to governed subagents with batch support.',
  },
  {
    toolName: 'zavorth_computer_use',
    surface: 'native-tool',
    capabilities: ['desktop', 'shell', 'destructive'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Controls desktop via screenshot, click, type, scroll, drag.',
  },
  {
    toolName: 'zavorth_voice_mode',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Manages voice sessions with STT, TTS, and wake word detection.',
  },
  {
    toolName: 'zavorth_session_search',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Searches past conversations and sessions.',
  },
  {
    toolName: 'zavorth_channel_send',
    surface: 'native-tool',
    capabilities: ['external-send', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Sends messages to 26+ messaging channels.',
  },
  {
    toolName: 'zavorth_document_extractor',
    surface: 'native-tool',
    capabilities: ['filesystem', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Extracts text from PDF, DOCX, XLSX, CSV, HTML documents.',
  },
  {
    toolName: 'zavorth_tts',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Converts text to speech using multiple backends.',
  },
  {
    toolName: 'zavorth_stt',
    surface: 'native-tool',
    capabilities: ['network', 'local-observation'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Converts speech to text using multiple backends.',
  },
  {
    toolName: 'zavorth_receipt_search',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Searches and audits action receipts.',
  },
  {
    toolName: 'zavorth_policy_enforcer',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Checks actions against governance policies.',
  },
  {
    toolName: 'zavorth_api_client',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Governed HTTP client with EgressGuard.',
  },
  {
    toolName: 'zavorth_trajectory_export',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Exports execution trajectories for training.',
  },
  {
    toolName: 'zavorth_security_guidance',
    surface: 'native-tool',
    capabilities: ['local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Provides security guidance, OWASP Top 10, code scanning.',
  },
  {
    toolName: 'zavorth_novita',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Novita AI provider for open-source models.',
  },
  {
    toolName: 'zavorth_replicate',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Replicate ML model execution.',
  },
  {
    toolName: 'zavorth_huggingface',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'HuggingFace Inference API.',
  },
  {
    toolName: 'zavorth_firecrawl',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Firecrawl web scraping and extraction.',
  },
  {
    toolName: 'zavorth_fal',
    surface: 'native-tool',
    capabilities: ['network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'fal.ai image generation.',
  },
  {
    toolName: 'zavorth_comfyui',
    surface: 'native-tool',
    capabilities: ['network', 'filesystem', 'sandbox'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'ComfyUI local image generation.',
  },
  {
    toolName: 'zavorth_searxng',
    surface: 'native-tool',
    capabilities: ['network', 'untrusted-input'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'SearXNG private meta-search engine.',
  },
  {
    toolName: 'zavorth_runway',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Runway ML video generation.',
  },
  {
    toolName: 'zavorth_spotify',
    surface: 'native-tool',
    capabilities: ['network', 'external-send'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Spotify music player control.',
  },
  {
    toolName: 'zavorth_docker_compose',
    surface: 'native-tool',
    capabilities: ['shell', 'destructive', 'network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Docker Compose multi-container management.',
  },
  {
    toolName: 'zavorth_code_intelligence',
    surface: 'native-tool',
    capabilities: ['filesystem', 'shell'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Code analysis, formatting, linting, and symbol extraction.',
  },
  {
    toolName: 'zavorth_ssh_tunnel',
    surface: 'native-tool',
    capabilities: ['network', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'SSH tunnel creation and management.',
  },
  {
    toolName: 'zavorth_chart_generator',
    surface: 'native-tool',
    capabilities: ['filesystem'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'Chart and visualization generation from data.',
  },
  {
    toolName: 'zavorth_file_watcher',
    surface: 'native-tool',
    capabilities: ['filesystem', 'local-observation'],
    defaultRisk: 'safe',
    requiresConfirmation: false,
    description: 'File system change monitoring and event logging.',
  },
  {
    toolName: 'zavorth_network',
    surface: 'native-tool',
    capabilities: ['network'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'Network diagnostics — DNS, port scan, ping, traceroute, WHOIS.',
  },
  {
    toolName: 'zavorth_webhook_receiver',
    surface: 'native-tool',
    capabilities: ['network', 'shell'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description: 'HTTP webhook endpoint creation and request logging.',
  },
];

export const BOOTSTRAP_NATIVE_TOOL_SECURITY_MANIFEST = [
  { className: 'UnifiedSearchTool', toolName: 'web_search' },
  { className: 'CreateFileTool', toolName: 'create_file' },
  { className: 'ReadFileTool', toolName: 'read_file' },
  { className: 'ListDirectoryTool', toolName: 'list_directory' },
  { className: 'WorkspaceReadTool', toolName: 'workspace.read' },
  { className: 'WorkspaceListTool', toolName: 'workspace.list' },
  { className: 'WorkspaceWriteTool', toolName: 'workspace.write' },
  { className: 'WorkspaceEditTool', toolName: 'workspace.edit' },
  { className: 'WorkspaceApplyPatchTool', toolName: 'workspace.apply_patch' },
  { className: 'WorkspaceCommandProposeTool', toolName: 'workspace.command.propose' },
  { className: 'WorkspaceCommandRunTool', toolName: 'workspace.command.run' },
  { className: 'HostCommandProposeTool', toolName: 'workspace.host_command.propose' },
  { className: 'HostCommandRunTool', toolName: 'workspace.host_command.run' },
  { className: 'PtySessionProposeTool', toolName: 'workspace.pty.propose' },
  { className: 'PtyWriteTool', toolName: 'workspace.pty.write' },
  { className: 'PtyTerminateTool', toolName: 'workspace.pty.terminate' },
  { className: 'WorkspaceTaskMandateProposeTool', toolName: 'workspace.task_mandate.propose' },
  { className: 'DateTimeTool', toolName: 'get_datetime' },
  { className: 'RemoteShellTool', toolName: 'remote_shell' },
  { className: 'QueryExternalAiTool', toolName: 'query_external_ai' },
  { className: 'SandboxExecutionTool', toolName: 'run_sandbox_code' },
  { className: 'Mem0Tool', toolName: 'semantic_memory' },
  { className: 'DesktopAutomationTool', toolName: 'desktop_automation' },
  { className: 'PlanMnemosScopeTool', toolName: 'plan_mnemos_scope' },
  { className: 'EnableMnemosTool', toolName: 'enable_mnemos' },
  { className: 'EchoHandsTool', toolName: 'echo_hands' },
  { className: 'ConfigureLlmProfileTool', toolName: 'configure_llm_profile' },
  { className: 'ZavorthActionTool', toolName: 'zavorth_action' },
  { className: 'AutoSkillCreatorTool', toolName: 'auto_skill_creator' },
  { className: 'ImageGenerationTool', toolName: 'generate_image' },
  { className: 'MediaAnalysisTool', toolName: 'analyze_media' },
  { className: 'NodeMeshTool', toolName: 'nodes' },
  { className: 'VideoGenerationTool', toolName: 'generate_video' },
  { className: 'KanbanTool', toolName: 'kanban_board' },
  { className: 'SkillFeedbackCollectorTool', toolName: 'skill_feedback' },
  { className: 'BatchTrajectoryTool', toolName: 'batch_trajectory' },
  { className: 'MultiBackendTerminalTool', toolName: 'terminal_backend' },
  { className: 'EmailTool', toolName: 'send_email' },
  { className: 'CalendarTool', toolName: 'calendar_event' },
  { className: 'CodeReviewTool', toolName: 'code_review' },
  { className: 'DatabaseQueryTool', toolName: 'database_query' },
  { className: 'ZavorthCronSchedulerTool', toolName: 'zavorth_cron_scheduler' },
  { className: 'ZavorthDelegateTool', toolName: 'zavorth_delegate' },
  { className: 'ZavorthComputerUseTool', toolName: 'zavorth_computer_use' },
  { className: 'ZavorthVoiceModeTool', toolName: 'zavorth_voice_mode' },
  { className: 'ZavorthSessionSearchTool', toolName: 'zavorth_session_search' },
  { className: 'ZavorthChannelSendTool', toolName: 'zavorth_channel_send' },
  { className: 'ZavorthDocumentExtractorTool', toolName: 'zavorth_document_extractor' },
  { className: 'ZavorthTtsTool', toolName: 'zavorth_tts' },
  { className: 'ZavorthSttTool', toolName: 'zavorth_stt' },
  { className: 'ZavorthReceiptSearchTool', toolName: 'zavorth_receipt_search' },
  { className: 'ZavorthPolicyEnforcerTool', toolName: 'zavorth_policy_enforcer' },
  { className: 'ZavorthApiClientTool', toolName: 'zavorth_api_client' },
  { className: 'ZavorthTrajectoryExportTool', toolName: 'zavorth_trajectory_export' },
  { className: 'SecurityGuidanceService', toolName: 'zavorth_security_guidance' },
  { className: 'ProviderNovitaTool', toolName: 'zavorth_novita' },
  { className: 'ProviderReplicateTool', toolName: 'zavorth_replicate' },
  { className: 'ProviderHuggingFaceTool', toolName: 'zavorth_huggingface' },
  { className: 'WebFirecrawlTool', toolName: 'zavorth_firecrawl' },
  { className: 'ImageGenFalTool', toolName: 'zavorth_fal' },
  { className: 'ImageGenComfyUITool', toolName: 'zavorth_comfyui' },
  { className: 'SearchSearXNGTool', toolName: 'zavorth_searxng' },
  { className: 'VideoGenRunwayTool', toolName: 'zavorth_runway' },
  { className: 'SpotifyPlayerTool', toolName: 'zavorth_spotify' },
  { className: 'ZavorthDockerComposeTool', toolName: 'zavorth_docker_compose' },
  { className: 'ZavorthCodeIntelligenceTool', toolName: 'zavorth_code_intelligence' },
  { className: 'ZavorthSshTunnelTool', toolName: 'zavorth_ssh_tunnel' },
  { className: 'ZavorthChartGeneratorTool', toolName: 'zavorth_chart_generator' },
  { className: 'ZavorthFileWatcherTool', toolName: 'zavorth_file_watcher' },
  { className: 'ZavorthNetworkTool', toolName: 'zavorth_network' },
  { className: 'ZavorthWebhookReceiverTool', toolName: 'zavorth_webhook_receiver' },
] as const;

const NATIVE_DEFINITIONS_BY_NAME = new Map(
  NATIVE_AGENT_TOOL_SECURITY_DEFINITIONS.map((definition) => [
    definition.toolName.toLowerCase(),
    normalizeAgentToolSecurityDefinition({ ...definition, source: 'explicit' }),
  ]),
);

export function listExplicitNativeToolSecurityNames(): string[] {
  return Array.from(NATIVE_DEFINITIONS_BY_NAME.keys()).sort();
}

export function findMissingExplicitNativeToolSecurityDefinitions(toolNames: string[]): string[] {
  return Array.from(
    new Set(
      toolNames
        .map((toolName) => String(toolName || '').trim().toLowerCase())
        .filter(Boolean)
        .filter((toolName) => !NATIVE_DEFINITIONS_BY_NAME.has(toolName)),
    ),
  ).sort();
}

export function assertExplicitNativeToolSecurityDefinitions(toolNames: string[]): void {
  const missing = findMissingExplicitNativeToolSecurityDefinitions(toolNames);
  if (missing.length > 0) {
    throw new Error(
      `Missing explicit native tool security definition(s): ${missing.join(', ')}. `
      + 'Add them to NATIVE_AGENT_TOOL_SECURITY_DEFINITIONS before exposing the tool.',
    );
  }
}

export function createMcpAgentToolSecurityDefinition(
  toolName: string,
  description = 'External MCP tool exposed to the local agent runtime.',
): AgentToolSecurityDefinition {
  return normalizeAgentToolSecurityDefinition({
    toolName,
    surface: 'mcp-tool',
    capabilities: ['mcp', 'network', 'external-send', 'untrusted-input'],
    defaultRisk: 'review',
    requiresConfirmation: true,
    description,
    source: 'inferred',
  });
}

export function createFallbackAgentToolSecurityDefinition(
  toolName: string,
  description = 'Registered tool without an explicit security definition.',
): AgentToolSecurityDefinition {
  return normalizeAgentToolSecurityDefinition({
    toolName,
    surface: 'unknown',
    capabilities: ['unknown'],
    defaultRisk: 'forbidden',
    requiresConfirmation: false,
    description,
    source: 'fallback',
  });
}

export function resolveDefaultAgentToolSecurityDefinition(
  toolName: string,
  description?: string,
): AgentToolSecurityDefinition {
  const normalized = String(toolName || '').trim().toLowerCase();
  const known = NATIVE_DEFINITIONS_BY_NAME.get(normalized);
  if (known) {
    return {
      ...known,
      capabilities: [...known.capabilities],
    };
  }

  return createFallbackAgentToolSecurityDefinition(toolName, description);
}


