import path from 'path';
import { config } from '../../config/index.js';
import type { CapabilityManifest } from '../CapabilityLifecycleService.js';

const DEFAULT_TTLS = {
  remoteSidecar: 15 * 60 * 1000,
  publicTunnel: 10 * 60 * 1000,
  sandbox: 5 * 60 * 1000,
  visualQa: 24 * 60 * 60 * 1000,
};

export function buildCapabilityManifests(): CapabilityManifest[] {
  return [
    {
      id: 'core-runtime',
      label: 'Core runtime',
      description: 'Database, main runtime, local zavorthControl, Telegram, approvals, and selfmod.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 260, diskMb: 280, processCount: 1, notes: 'Main Zavorth process.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps only the base runtime online.',
    },
    {
      id: 'maintenance-automation',
      label: 'Maintenance automation',
      description: 'Recurring Zavorth maintenance routine.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 8, processCount: 0, notes: 'Lightweight in-memory timers.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Zavorth remains operational without recurring maintenance.',
    },
    {
      id: 'daily-report',
      label: 'Daily report',
      description: 'Daily operational summary sent to operators.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 16, diskMb: 4, processCount: 0, notes: 'Report schedule and composition.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Daily report remains in manual mode.',
    },
    {
      id: 'remote',
      label: 'Remote sidecars',
      description: 'AIGateway, remote ZavorthBridge, brokers, and advanced watchers.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.remoteSidecar,
      estimatedFootprint: { ramIdleMb: 240, diskMb: 1024, processCount: 3, notes: 'May open worktrees, node hosts, and keepalives.' },
      provisioningRecipe: {
        dependencies: ['sql.js'],
        commands: ['npm run ops:remote:keepalive'],
        notes: 'Provisions remote sidecars and bridges.',
      },
      cleanupPaths: [
        config.AIGatewaySidecarWorktreeDir,
        config.ZavorthTerminalSidecarWorktreeDir,
        config.AIGatewaySidecarLogFile,
        config.ZavorthTerminalSidecarLogFile,
        config.AIGatewaySidecarStatusFile,
        config.ZavorthTerminalSidecarStatusFile,
        config.zavorthBridgePublicTunnelStateFile,
        config.zavorthBridgePublicTunnelLogFile,
        config.zavorthPublicTunnelStateFile,
        config.zavorthPublicTunnelLogFile,
      ],
      fallbackBehavior: 'Runs only the local core and exposes remote mode under approval.',
    },
    {
      id: 'zavorth-bridge-remote',
      label: 'ZavorthBridge Remote',
      description: 'Remote ZavorthBridge sidecar for shell, auxiliary control UI, and visual integrations.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.remoteSidecar,
      estimatedFootprint: { ramIdleMb: 96, diskMb: 512, processCount: 1, notes: 'zavorth-terminal dev server and ephemeral sidecar artifacts.' },
      provisioningRecipe: {
        commands: ['npm run sidecars:status', 'npm run integrations:doctor -- --id zavorth-terminal'],
        notes: 'On demand; the core profile keeps it dormant until there is a real need.',
      },
      cleanupPaths: [
        config.ZavorthTerminalSidecarLogFile,
        config.ZavorthTerminalSidecarStatusFile,
        config.ZavorthTerminalSidecarWorktreeDir,
      ],
      fallbackBehavior: 'Keeps operation in the main Gateway without starting the remote ZavorthBridge sidecar.',
    },
    {
      id: 'media',
      label: 'Media tooling',
      description: 'Transcription, TTS, video, and PDF parsing on demand.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 96, diskMb: 512, processCount: 0, notes: 'Audio, ffmpeg, and PDF packages.' },
      provisioningRecipe: {
        dependencies: ['msedge-tts', 'ffmpeg-static', 'pdf-parse', 'youtube-dl-exec'],
        notes: 'Downloads multimedia binaries and libraries only when required.',
      },
      cleanupPaths: [],
      fallbackBehavior: 'Keeps text responses and guides multimedia enablement.',
    },
    {
      id: 'qa',
      label: 'QA visual',
      description: 'Visual smoke tests, browser profiles, and ephemeral QA outputs.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.visualQa,
      estimatedFootprint: { ramIdleMb: 160, diskMb: 1024, processCount: 1, notes: 'Playwright, browsers, and temporary artifacts.' },
      provisioningRecipe: {
        commands: ['npm run test:web:visual:real'],
        notes: 'Provisions visual QA only when explicitly required.',
      },
      cleanupPaths: [
        path.resolve(config.projectRoot, 'data', 'runtime', 'visual-smoke'),
      ],
      fallbackBehavior: 'Keeps textual smoke coverage and suggests visual QA under approval.',
    },
    {
      id: 'sandbox',
      label: 'Sandbox',
      description: 'Docker/Firecracker sandbox layers on demand.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.sandbox,
      estimatedFootprint: { ramIdleMb: 192, diskMb: 1536, processCount: 1, notes: 'May start a microVM or Docker sandbox.' },
      provisioningRecipe: {
        commands: ['npm run sandbox:doctor', 'npm run sandbox:firecracker:bootstrap'],
        notes: 'Provisions only when the operator approves a more expensive isolation track.',
      },
      cleanupPaths: [
        path.resolve(config.projectRoot, 'data', 'firecracker'),
      ],
      fallbackBehavior: 'Runs in guarded local mode without expanding heavy isolation.',
    },
    {
      id: 'public-tunnel',
      label: 'Public tunnel',
      description: 'Public tunnel for remote runtime and controlled exposure.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.publicTunnel,
      estimatedFootprint: { ramIdleMb: 32, diskMb: 32, processCount: 1, notes: 'cloudflared and tunnel state.' },
      provisioningRecipe: {
        commands: ['npm run ops:public:tunnel'],
        notes: 'On demand and always with approval.',
      },
      cleanupPaths: [
        config.zavorthBridgePublicTunnelStateFile,
        config.zavorthBridgePublicTunnelLogFile,
        config.zavorthPublicTunnelStateFile,
        config.zavorthPublicTunnelLogFile,
      ],
      fallbackBehavior: 'Keeps access local only.',
    },
    {
      id: 'rollout-readiness',
      label: 'Rollout readiness gate',
      description: 'Local-first gate for local, beta, production, or rollback-only rollout.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 12, diskMb: 16, processCount: 0, notes: 'Reads lightweight snapshots; deep checks run only with --refresh.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps rollout in local/rollback mode with warnings until gates close.',
    },
    {
      id: 'natural-setup',
      label: 'Natural setup agent',
      description: 'Plans natural channel setup without applying side effects through GET.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 18, diskMb: 12, processCount: 0, notes: 'Local planner and secret masking.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Shows checklist and applicable plan only with approval.',
    },
    {
      id: 'trust-plane',
      label: 'Trust Plane policy OS',
      description: 'Canonical permission plan, policy diffs, and decisions before sensitive mutations.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 14, diskMb: 24, processCount: 0, notes: 'Reads local policy and permission ledger.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps permissions in safe/deny mode until approval exists.',
    },
    {
      id: 'watch-mode',
      label: 'Supervised Watch Mode',
      description: 'Lazy visual computer-use with strict approval, screenshot TTL, and run limit.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: 10 * 60 * 1000,
      estimatedFootprint: { ramIdleMb: 180, diskMb: 250, processCount: 1, notes: 'Browser/desktop automation and ephemeral screenshots.' },
      provisioningRecipe: {
        commands: ['npm run ops:watch-mode -- --preview start'],
        notes: 'Real start only through an approved mutation plan.',
      },
      cleanupPaths: [
        path.resolve(config.projectRoot, 'data', 'runtime', 'watch-mode-screenshots'),
      ],
      fallbackBehavior: 'Keeps textual read and requests approval before visual automation.',
    },
    {
      id: 'eval-observability',
      label: 'Eval + observability regression gate',
      description: 'Scorecards, telemetry ledger, and regression gate to block production with critical regressions.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 20, diskMb: 64, processCount: 0, notes: 'Local JSONL telemetry; external sinks remain dormant.' },
      provisioningRecipe: null,
      cleanupPaths: [
        config.telemetryEventsFile,
      ],
      fallbackBehavior: 'Uses local telemetry and eval history without activating external sinks.',
    },
    {
      id: 'recurring-automation',
      label: 'Recurring automations',
      description: 'Recurring scheduler with budgets, retries, concurrency, and auto-pause.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 100, processCount: 0, notes: 'Lightweight timers; core lists/previews without starting the loop.' },
      provisioningRecipe: {
        commands: ['npm run ops:automations -- --preview'],
        notes: 'Loops are active only in ops/full and with approval/budget.',
      },
      cleanupPaths: [
        config.automationDeliveryReportFile,
        config.automationWebhookOutboxFile,
      ],
      fallbackBehavior: 'In core, creates preview and leaves recurring execution dormant.',
    },
    {
      id: 'discord',
      label: 'Discord gateway',
      description: 'First-class Discord gateway.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 36, diskMb: 12, processCount: 0, notes: 'Optional gateway through token/bridge.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps Telegram and zavorthControl as primary surfaces.',
    },
    {
      id: 'whatsapp',
      label: 'WhatsApp gateway',
      description: 'First-class WhatsApp gateway.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 28, diskMb: 8, processCount: 0, notes: 'Optional WhatsApp channel gateway.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'slack',
      label: 'Slack gateway',
      description: 'First-class Slack gateway.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 28, diskMb: 8, processCount: 0, notes: 'Optional Slack channel gateway.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'signal',
      label: 'Signal gateway',
      description: 'First-class Signal bridge via signal-cli.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 8, processCount: 0, notes: 'Local bridge with supervised outbox.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'imessage',
      label: 'iMessage gateway',
      description: 'Experimental iMessage bridge through macOS Node Host.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 8, processCount: 0, notes: 'Local/macOS bridge with guardrails.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'teams',
      label: 'Teams gateway',
      description: 'First-class Microsoft Teams gateway.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 28, diskMb: 8, processCount: 0, notes: 'Supervised webhook/outbox for Teams.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'email',
      label: 'Email gateway',
      description: 'Email channel fallback for notifications and approvals.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 20, diskMb: 8, processCount: 0, notes: 'SMTP/IMAP with supervised outbox.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
  ];
}
