import path from 'path';
import { config } from '../../config/index.js';
import type { CapabilityManifest } from '../CapabilityLifecycleService.js';

const DEFAULT_TTLS = {
  remoteSidecar: 15 * 60 * 1000,
  publicTunnel: 10 * 60 * 1000,
  sandbox: 5 * 60 * 1000,
  visualQa: 24 * 60 * 60 * 1000,
};

export function buildCapabilityManifests(): CapabilityManifest[] {
  return [
    {
      id: 'core-runtime',
      label: 'Core runtime',
      description: 'Banco, runtime principal, zavorthControl local, Telegram, approvals e selfmod.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 260, diskMb: 280, processCount: 1, notes: 'Processo principal do Zavorth.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Mantem apenas o runtime base online.',
    },
    {
      id: 'maintenance-automation',
      label: 'Maintenance automation',
      description: 'Rotina de manutencao recorrente do Zavorth.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 8, processCount: 0, notes: 'Timers leves em memoria.' },
      provisioningRecipe: null,
      fallbackBehavior: 'O Zavorth segue operacional sem manutencao recorrente.',
    },
    {
      id: 'daily-report',
      label: 'Daily report',
      description: 'Resumo diario operacional enviado aos operatores.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 16, diskMb: 4, processCount: 0, notes: 'Agenda e composicao do relatorio.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Relatorio diario fica em modo manual.',
    },
    {
      id: 'remote',
      label: 'Remote sidecars',
      description: 'AIGateway, ZavorthBridge remoto, brokers e watchers avancados.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.remoteSidecar,
      estimatedFootprint: { ramIdleMb: 240, diskMb: 1024, processCount: 3, notes: 'Pode abrir worktrees, node hosts e keepalives.' },
      provisioningRecipe: {
        dependencies: ['sql.js'],
        commands: ['npm run ops:remote:keepalive'],
        notes: 'Provisiona sidecars e bridges remotos.',
      },
      cleanupPaths: [
        config.AIGatewaySidecarWorktreeDir,
        config.ZavorthTerminalSidecarWorktreeDir,
        config.AIGatewaySidecarLogFile,
        config.ZavorthTerminalSidecarLogFile,
        config.AIGatewaySidecarStatusFile,
        config.ZavorthTerminalSidecarStatusFile,
        config.zavorthBridgePublicTunnelStateFile,
        config.zavorthBridgePublicTunnelLogFile,
        config.zavorthPublicTunnelStateFile,
        config.zavorthPublicTunnelLogFile,
      ],
      fallbackBehavior: 'Executa apenas o core local e expoe modo remoto sob approval.',
    },
    {
      id: 'zavorth-bridge-remote',
      label: 'ZavorthBridge Remote',
      description: 'Sidecar remoto do ZavorthBridge para shell/zavorthControl UI auxiliar e integracoes visuais.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.remoteSidecar,
      estimatedFootprint: { ramIdleMb: 96, diskMb: 512, processCount: 1, notes: 'Dev server do zavorth-terminal e artefatos efemeros do sidecar.' },
      provisioningRecipe: {
        commands: ['npm run sidecars:status', 'npm run integrations:doctor -- --id zavorth-terminal'],
        notes: 'Sob demanda; o perfil core o mantem dormente ate haver necessidade real.',
      },
      cleanupPaths: [
        config.ZavorthTerminalSidecarLogFile,
        config.ZavorthTerminalSidecarStatusFile,
        config.ZavorthTerminalSidecarWorktreeDir,
      ],
      fallbackBehavior: 'Mantem a operacao no Gateway principal sem subir o sidecar remoto do ZavorthBridge.',
    },
    {
      id: 'media',
      label: 'Media tooling',
      description: 'Transcricao, TTS, video e parse de PDFs sob demanda.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 96, diskMb: 512, processCount: 0, notes: 'Pacotes de audio, ffmpeg e PDF.' },
      provisioningRecipe: {
        dependencies: ['msedge-tts', 'ffmpeg-static', 'pdf-parse', 'youtube-dl-exec'],
        notes: 'Baixa binarios e libs multimidia apenas quando exigidos.',
      },
      cleanupPaths: [],
      fallbackBehavior: 'Mantem respostas textuais e orienta a habilitaction da trilha multimidia.',
    },
    {
      id: 'qa',
      label: 'QA visual',
      description: 'Smoke visual, perfis de navegador e outputs efemeros de QA.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.visualQa,
      estimatedFootprint: { ramIdleMb: 160, diskMb: 1024, processCount: 1, notes: 'Playwright, browsers e artefatos temporarys.' },
      provisioningRecipe: {
        commands: ['npm run test:web:visual:real'],
        notes: 'Provisiona QA visual apenas quando explicitamente exigido.',
      },
      cleanupPaths: [
        path.resolve(config.projectRoot, 'data', 'runtime', 'visual-smoke'),
      ],
      fallbackBehavior: 'Mantem smoke textual e sugere QA visual sob approval.',
    },
    {
      id: 'sandbox',
      label: 'Sandbox',
      description: 'Camadas de sandbox Docker/Firecracker sob demanda.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.sandbox,
      estimatedFootprint: { ramIdleMb: 192, diskMb: 1536, processCount: 1, notes: 'Pode subir microVM ou Docker sandbox.' },
      provisioningRecipe: {
        commands: ['npm run sandbox:doctor', 'npm run sandbox:firecracker:bootstrap'],
        notes: 'Provisiona somente quando o operador aprova uma trilha de isolamento mais cara.',
      },
      cleanupPaths: [
        path.resolve(config.projectRoot, 'data', 'firecracker'),
      ],
      fallbackBehavior: 'Executa no modo local guardado sem expandir isolamento pesado.',
    },
    {
      id: 'public-tunnel',
      label: 'Public tunnel',
      description: 'Tunel publico para runtime remoto e exposicao controlada.',
      availability: 'optional',
      activationMode: 'sidecar',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: DEFAULT_TTLS.publicTunnel,
      estimatedFootprint: { ramIdleMb: 32, diskMb: 32, processCount: 1, notes: 'cloudflared e estado do tunel.' },
      provisioningRecipe: {
        commands: ['npm run ops:public:tunnel'],
        notes: 'Sob demanda e sempre com approval.',
      },
      cleanupPaths: [
        config.zavorthBridgePublicTunnelStateFile,
        config.zavorthBridgePublicTunnelLogFile,
        config.zavorthPublicTunnelStateFile,
        config.zavorthPublicTunnelLogFile,
      ],
      fallbackBehavior: 'Mantem acesso apenas local.',
    },
    {
      id: 'rollout-readiness',
      label: 'Rollout readiness gate',
      description: 'Gate local-first para promover rollout local, beta, production ou rollback-only.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 12, diskMb: 16, processCount: 0, notes: 'Le snapshots leves; checks profundos so com --refresh.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Mantem rollout em modo local/rollback com warnings ate fechar os gates.',
    },
    {
      id: 'natural-setup',
      label: 'Natural setup agent',
      description: 'Planeja setup de canais em linguagem natural sem aplicar side effects via GET.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 18, diskMb: 12, processCount: 0, notes: 'Planner local e mascaramento de secrets.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Mostra checklist e plano aplicavel somente com approval.',
    },
    {
      id: 'trust-plane',
      label: 'Trust Plane policy OS',
      description: 'Plano canonico de permissoes, policy diffs e decisions antes de mutacoes sensiveis.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 14, diskMb: 24, processCount: 0, notes: 'Le policy local e permission ledger.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Mantem permissoes em safe/deny ate haver approval.',
    },
    {
      id: 'watch-mode',
      label: 'Supervised Watch Mode',
      description: 'Computer-use visual lazy, com strict approval, TTL de screenshots e limite de run.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: 10 * 60 * 1000,
      estimatedFootprint: { ramIdleMb: 180, diskMb: 250, processCount: 1, notes: 'Browser/desktop automation e screenshots efemeros.' },
      provisioningRecipe: {
        commands: ['npm run ops:watch-mode -- --preview start'],
        notes: 'Start real somente via mutation plan aprovado.',
      },
      cleanupPaths: [
        path.resolve(config.projectRoot, 'data', 'runtime', 'watch-mode-screenshots'),
      ],
      fallbackBehavior: 'Mantem leitura textual e pede approval antes de automacao visual.',
    },
    {
      id: 'eval-observability',
      label: 'Eval + observability regression gate',
      description: 'Scorecards, telemetry ledger e regression gate para bloquear production com regressao critica.',
      availability: 'core',
      activationMode: 'builtin',
      approvalRequired: false,
      enabledByDefaultProfiles: ['core', 'ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 20, diskMb: 64, processCount: 0, notes: 'Telemetry local JSONL; sinks externos permanecem dormentes.' },
      provisioningRecipe: null,
      cleanupPaths: [
        config.telemetryEventsFile,
      ],
      fallbackBehavior: 'Usa telemetry local e historico de eval sem ativar sinks externos.',
    },
    {
      id: 'recurring-automation',
      label: 'Recurring automations',
      description: 'Scheduler recorrente com budgets, retries, concurrency e auto-pause.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: true,
      enabledByDefaultProfiles: ['ops', 'full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 100, processCount: 0, notes: 'Timers leves; core lista/previsualiza sem iniciar loop.' },
      provisioningRecipe: {
        commands: ['npm run ops:automations -- --preview'],
        notes: 'Loops ativos so em ops/full e com approval/budget.',
      },
      cleanupPaths: [
        config.automationDeliveryReportFile,
        config.automationWebhookOutboxFile,
      ],
      fallbackBehavior: 'No core, cria preview e deixa execucao recorrente dormente.',
    },
    {
      id: 'discord',
      label: 'Discord gateway',
      description: 'Gateway first-class do Discord.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 36, diskMb: 12, processCount: 0, notes: 'Gateway opcional por token/bridge.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Mantem Telegram e zavorthControl como superficies primarias.',
    },
    {
      id: 'whatsapp',
      label: 'WhatsApp gateway',
      description: 'Gateway first-class do WhatsApp.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 28, diskMb: 8, processCount: 0, notes: 'Gateway opcional do canal WhatsApp.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'slack',
      label: 'Slack gateway',
      description: 'Gateway first-class do Slack.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 28, diskMb: 8, processCount: 0, notes: 'Gateway opcional do canal Slack.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'signal',
      label: 'Signal gateway',
      description: 'Bridge first-class do Signal via signal-cli.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 8, processCount: 0, notes: 'Bridge local com outbox supervisionado.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'imessage',
      label: 'iMessage gateway',
      description: 'Bridge experimental do iMessage via Node Host macOS.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 24, diskMb: 8, processCount: 0, notes: 'Bridge local/macOS com guardrails.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'teams',
      label: 'Teams gateway',
      description: 'Gateway first-class do Microsoft Teams.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 28, diskMb: 8, processCount: 0, notes: 'Webhook/outbox supervisionado para Teams.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
    {
      id: 'email',
      label: 'Email gateway',
      description: 'Canal fallback de Email para notificacoes e approvals.',
      availability: 'optional',
      activationMode: 'lazy',
      approvalRequired: false,
      enabledByDefaultProfiles: ['full'],
      idleTtlMs: null,
      estimatedFootprint: { ramIdleMb: 20, diskMb: 8, processCount: 0, notes: 'SMTP/IMAP com outbox supervisionado.' },
      provisioningRecipe: null,
      fallbackBehavior: 'Keeps the other channels online.',
    },
  ];
}
