/**
 * Connection command copy resolution backed by the unified localization system.
 *
 * Locales without a hand-curated `connections` section in the builtin catalogs
 * are layered here at runtime so every supported locale resolves translated
 * connect/disconnect command copy. The chain stays identical to every other
 * section: exact locale tag, then one-shot AI translation persisted by
 * ZavorthOnDemandTranslationService, then English.
 */

import type { ConnectionTranslations, LocalizationCatalog } from './localeContracts.js';
import { ZavorthLocalizationService } from './ZavorthLocalizationService.js';
import { createGatewayAwareLocalizationService } from './gatewaySupport.js';

export const CONNECTIONS_CATALOG_EXTENSIONS: Partial<Record<string, ConnectionTranslations>> = {
  bg: {
    title: 'Универсална подсистема за връзки',
    connectedSuccess: 'Успешно свързано с **{target}**!',
    disconnectedSuccess: 'Прекъсната връзка с **{target}**. Локалните идентификационни данни са изтрити.',
    alreadyConnected: 'Целта **{target}** вече е свързана (статус: `connected`).',
    notConnected: "Няма активна връзка с '{target}'.",
    unrecognizedTarget: "Целта '{target}' не е разпозната.",
    rateLimitExceeded: 'Превишен лимит на честотата: можете да изпълнявате най-много 10 команди за връзка на минута. Моля, изчакайте.',
    apiKeyPrompt: 'За да свържете **{target}**, предоставете вашия {label}:\n`/connect {id} <вашият_ключ>`',
    localPathPrompt: 'За да свържете **{target}**, посочете пътя към локалната директория:\n`/connect {id} /път/до/{kind}`',
    oauthDeviceCodePrompt: 'За да завършите упълномощаването на устройството за **{target}**:\n1. Отворете: {url}\n2. Въведете кода за свързване: `{code}`',
    catalogTitle: 'Каталог на наличните връзки',
    noActiveConnections: 'Не са намерени активни връзки.\n\n• Свържете интеграция: `/connect <цел>`\n• Прегледайте каталога: `/connections catalog`',
    usageConnect: '**Употреба на командата Connect:**\n`/connect <цел> [идентификационни_данни]`\n\n**Примери:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /път/до/vault`\n\nИзползвайте `/connections catalog`, за да видите всички налични цели.',
    usageDisconnect: 'Употреба: `/disconnect <цел>`\nПример: `/disconnect stripe`',
    handshakeInProgress: 'Вече има извършващ се опит за връзка с тази цел.',
    pathVerificationFailed: '❌ Неуспешна проверка на пътя за **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Неуспешна проверка на ключа за **{target}**: {details}',
    oauthClickLink: '🔗 **Свързване с {target}:**\nКликнете върху връзката по-долу, за да упълномощите Zavorth:\n[Упълномощаване на {target}]({url})',
    oauthEnded: '⚠️ OAuth упълномощаването за **{target}** приключи: {details}',
    activeConnectionsHeader: '**Вашите активни връзки ({count}):**',
    catalogEmpty: 'В момента няма налични цели в каталога за връзки.',
    statusHeader: '**Състояние на работоспособността на връзките:**',
    statusEmpty: 'Няма активни връзки, за които да се отчете състояние.',
    guidanceLabel: '💡 **Насоки:**',
    reconnectHint: '• Свържете отново или актуализирайте идентификационните данни: `/connect {target} <нови_данни>`',
    disconnectHint: '• Прекъснете връзката: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Локалната директория е проверена: `{path}`',
    credentialsVaultSuffix: 'Идентификационните данни са криптирани и безопасно съхранени в трезора.',
    secretStoreFailed: '❌ Неуспешно съхранение на криптираните идентификационни данни за **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Свързване с {target} (Device Code Flow):**\n1. Отворете връзката за упълномощаване: {url}\n2. Потвърдете упълномощаването в браузъра си.\n3. Zavorth ще завърши ръкостискането автоматично.',
    missingDeviceVerificationUrl: 'Липсва URL за проверка на устройството',
    oauthConnectedSuccess: '✅ Успешно свързано с **{target}** чрез OAuth2!',
    oauthExchangeFailed: '❌ Неуспешен обмен на OAuth токени за **{target}**: {details}',
    oauthListenerFailed: '⚠️ Неуспешно стартиране на слушателя за OAuth обратни повиквания: {details}',
    oauthConfigActive: 'OAuth конфигурацията за **{target}** е активна.',
    catalogConnectHint: 'За да свържете която и да е цел, напишете: `/connect <цел>`',
    statusLabel: 'Статус',
    healthLabel: 'Работоспособност',
    authLabel: 'Удостоверяване',
    connectedAtLabel: 'Свързано на',
    disconnectServiceHint: '• Прекъснете връзката на услуга: `/disconnect <цел>`',
  },
  cs: {
    title: 'Univerzální subsystém připojení',
    connectedSuccess: 'Úspěšně připojeno k **{target}**!',
    disconnectedSuccess: 'Odpojeno od **{target}**. Místní pověření byla vymazána.',
    alreadyConnected: 'Cíl **{target}** je již připojen (stav: `connected`).',
    notConnected: "Žádné aktivní připojení k '{target}'.",
    unrecognizedTarget: "Cíl '{target}' nebyl rozpoznán.",
    rateLimitExceeded: 'Překročen limit frekvence: za minutu lze provést maximálně 10 příkazů připojení. Počkejte prosím.',
    apiKeyPrompt: 'Pro připojení **{target}** zadejte svůj {label}:\n`/connect {id} <vasek_klic>`',
    localPathPrompt: 'Pro připojení **{target}** zadejte cestu k místnímu adresáři:\n`/connect {id} /cesta/k/{kind}`',
    oauthDeviceCodePrompt: 'Pro dokončení autorizace zařízení pro **{target}**:\n1. Otevřete: {url}\n2. Zadejte párovací kód: `{code}`',
    catalogTitle: 'Katalog dostupných připojení',
    noActiveConnections: 'Nebyla nalezena žádná aktivní připojení.\n\n• Připojte integraci: `/connect <cil>`\n• Zobrazte katalog: `/connections catalog`',
    usageConnect: '**Použití příkazu Connect:**\n`/connect <cil> [povereni]`\n\n**Příklady:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /cesta/k/vault`\n\nPomocí `/connections catalog` zobrazíte všechny dostupné cíle.',
    usageDisconnect: 'Použití: `/disconnect <cil>`\nPříklad: `/disconnect stripe`',
    handshakeInProgress: 'Pro tento cíl již probíhá pokus o připojení.',
    pathVerificationFailed: '❌ Ověření cesty pro **{target}** se nezdařilo: {details}',
    apiKeyVerificationFailed: '❌ Ověření klíče pro **{target}** se nezdařilo: {details}',
    oauthClickLink: '🔗 **Připojit {target}:**\nKliknutím na odkaz níže autorizujete Zavorth:\n[Autorizovat {target}]({url})',
    oauthEnded: '⚠️ OAuth autorizace pro **{target}** skončila: {details}',
    activeConnectionsHeader: '**Vaše aktivní připojení ({count}):**',
    catalogEmpty: 'V katalogu připojení aktuálně nejsou žádné cíle.',
    statusHeader: '**Stav integrity připojení:**',
    statusEmpty: 'Žádná aktivní připojení k zobrazení stavu.',
    guidanceLabel: '💡 **Návod:**',
    reconnectHint: '• Znovu připojit nebo aktualizovat pověření: `/connect {target} <nova_povereni>`',
    disconnectHint: '• Odpojit: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Místní adresář ověřen: `{path}`',
    credentialsVaultSuffix: 'Pověření byla zašifrována a bezpečně uložena do trezoru.',
    secretStoreFailed: '❌ Uložení šifrovaných pověření pro **{target}** se nezdařilo: {details}',
    deviceCodeFlowInstructions: '🔑 **Připojit {target} (Device Code Flow):**\n1. Otevřete autorizační odkaz: {url}\n2. Potvrďte autorizaci v prohlížeči.\n3. Zavorth dokončí handshake automaticky.',
    missingDeviceVerificationUrl: 'Chybí URL pro ověření zařízení',
    oauthConnectedSuccess: '✅ Úspěšně připojeno k **{target}** přes OAuth2!',
    oauthExchangeFailed: '❌ Výměna OAuth tokenů pro **{target}** se nezdařila: {details}',
    oauthListenerFailed: '⚠️ Spuštění posluchače OAuth callbacků se nezdařilo: {details}',
    oauthConfigActive: 'Konfigurace OAuth pro **{target}** je aktivní.',
    catalogConnectHint: 'Pro připojení libovolného cíle napište: `/connect <cil>`',
    statusLabel: 'Stav',
    healthLabel: 'Integrita',
    authLabel: 'Ověření',
    connectedAtLabel: 'Připojeno',
    disconnectServiceHint: '• Odpojit službu: `/disconnect <cil>`',
  },
  da: {
    title: 'Universelt forbindelsessubsystem',
    connectedSuccess: 'Forbundet til **{target}** med succes!',
    disconnectedSuccess: 'Afbrudt fra **{target}**. Lokale legitimationsoplysninger slettet.',
    alreadyConnected: 'Målet **{target}** er allerede forbundet (status: `connected`).',
    notConnected: "Ingen aktiv forbindelse til '{target}'.",
    unrecognizedTarget: "Målet '{target}' blev ikke genkendt.",
    rateLimitExceeded: 'Hastighedsgrænse overskredet: du kan udføre højst 10 forbindelseskommandoer pr. minut. Vent venligst.',
    apiKeyPrompt: 'For at forbinde **{target}**, angiv din {label}:\n`/connect {id} <din_noegle>`',
    localPathPrompt: 'For at forbinde **{target}**, angiv stien til den lokale mappe:\n`/connect {id} /sti/til/{kind}`',
    oauthDeviceCodePrompt: 'For at fuldføre enhedsgodkendelse for **{target}**:\n1. Åbn: {url}\n2. Indtast parringskoden: `{code}`',
    catalogTitle: 'Katalog over tilgængelige forbindelser',
    noActiveConnections: 'Ingen aktive forbindelser fundet.\n\n• Forbind en integration: `/connect <maal>`\n• Se tilgængelig katalog: `/connections catalog`',
    usageConnect: '**Brug af Connect-kommandoen:**\n`/connect <maal> [legitimationsoplysninger]`\n\n**Eksempler:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /sti/til/vault`\n\nBrug `/connections catalog` for at se alle tilgængelige mål.',
    usageDisconnect: 'Brug: `/disconnect <maal>`\nEksempel: `/disconnect stripe`',
    handshakeInProgress: 'Der kører allerede et forbindelsesforsøg for dette mål.',
    pathVerificationFailed: '❌ Sti-verifikation mislykkedes for **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Nøgleverifikation mislykkedes for **{target}**: {details}',
    oauthClickLink: '🔗 **Forbind {target}:**\nKlik på linket nedenfor for at godkende Zavorth:\n[Godkend {target}]({url})',
    oauthEnded: '⚠️ OAuth-godkendelse for **{target}** er afsluttet: {details}',
    activeConnectionsHeader: '**Dine aktive forbindelser ({count}):**',
    catalogEmpty: 'Der er i øjeblikket ingen mål i forbindelseskataloget.',
    statusHeader: '**Forbindelses-sundhedsstatus:**',
    statusEmpty: 'Ingen aktive forbindelser at rapportere status for.',
    guidanceLabel: '💡 **Vejledning:**',
    reconnectHint: '• Genforbind eller opdater legitimationsoplysninger: `/connect {target} <nye_oplysninger>`',
    disconnectHint: '• Afbryd: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Lokal mappe verificeret: `{path}`',
    credentialsVaultSuffix: 'Legitimationsoplysninger krypteret og sikkert gemt i vault.',
    secretStoreFailed: '❌ Lagring af krypterede legitimationsoplysninger for **{target}** mislykkedes: {details}',
    deviceCodeFlowInstructions: '🔑 **Forbind {target} (Device Code Flow):**\n1. Åbn autorisationslinket: {url}\n2. Bekræft godkendelsen i din browser.\n3. Zavorth fuldfører handshake automatisk.',
    missingDeviceVerificationUrl: 'Enhedsverifikations-URL mangler',
    oauthConnectedSuccess: '✅ Forbundet til **{target}** med succes via OAuth2!',
    oauthExchangeFailed: '❌ OAuth-tokenudveksling for **{target}** mislykkedes: {details}',
    oauthListenerFailed: '⚠️ Start af OAuth-callback-lytter mislykkedes: {details}',
    oauthConfigActive: 'OAuth-konfiguration for **{target}** er aktiv.',
    catalogConnectHint: 'For at forbinde ethvert mål, skriv: `/connect <maal>`',
    statusLabel: 'Status',
    healthLabel: 'Sundhed',
    authLabel: 'Auth',
    connectedAtLabel: 'Forbundet',
    disconnectServiceHint: '• Afbryd en tjeneste: `/disconnect <maal>`',
  },
  el: {
    title: 'Καθολικό υποσύστημα συνδέσεων',
    connectedSuccess: 'Επιτυχής σύνδεση με **{target}**!',
    disconnectedSuccess: 'Αποσύνδεση από **{target}**. Τα τοπικά διαπιστευτήρια διαγράφηκαν.',
    alreadyConnected: 'Ο στόχος **{target}** είναι ήδη συνδεδεμένος (κατάσταση: `connected`).',
    notConnected: "Δεν υπάρχει ενεργή σύνδεση με το '{target}'.",
    unrecognizedTarget: "Ο στόχος '{target}' δεν αναγνωρίστηκε.",
    rateLimitExceeded: 'Υπέρβαση ορίου ρυθμού: μπορείτε να εκτελέσετε το πολύ 10 εντολές σύνδεσης ανά λεπτό. Περιμένετε.',
    apiKeyPrompt: 'Για να συνδεθείτε με **{target}**, δώστε το {label} σας:\n`/connect {id} <το_κλειδι_σας>`',
    localPathPrompt: 'Για να συνδεθείτε με **{target}**, καθορίστε τη διαδρομή του τοπικού καταλόγου:\n`/connect {id} /διαδρομή/{kind}`',
    oauthDeviceCodePrompt: 'Για να ολοκληρώσετε την εξουσιοδότηση της συσκευής για **{target}**:\n1. Ανοίξτε: {url}\n2. Εισαγάγετε τον κωδικό σύζευξης: `{code}`',
    catalogTitle: 'Κατάλογος διαθέσιμων συνδέσεων',
    noActiveConnections: 'Δεν βρέθηκαν ενεργές συνδέσεις.\n\n• Συνδέστε μια ενσωμάτωση: `/connect <στόχος>`\n• Δείτε τον διαθέσιμο κατάλογο: `/connections catalog`',
    usageConnect: '**Χρήση της εντολής Connect:**\n`/connect <στόχος> [διαπιστευτήρια]`\n\n**Παραδείγματα:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /διαδρομή/vault`\n\nΧρησιμοποιήστε το `/connections catalog` για να δείτε όλους τους διαθέσιμους στόχους.',
    usageDisconnect: 'Χρήση: `/disconnect <στόχος>`\nΠαράδειγμα: `/disconnect stripe`',
    handshakeInProgress: 'Υπάρχει ήδη μια προσπάθεια σύνδεσης σε εξέλιξη για αυτόν τον στόχο.',
    pathVerificationFailed: '❌ Η επαλήθευση διαδρομής απέτυχε για **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Η επαλήθευση κλειδιού απέτυχε για **{target}**: {details}',
    oauthClickLink: '🔗 **Σύνδεση {target}:**\nΚάντε κλικ στον παρακάτω σύνδεσμο για να εξουσιοδοτήσετε το Zavorth:\n[Εξουσιοδότηση {target}]({url})',
    oauthEnded: '⚠️ Η εξουσιοδότηση OAuth για **{target}** ολοκληρώθηκε: {details}',
    activeConnectionsHeader: '**Οι ενεργές συνδέσεις σας ({count}):**',
    catalogEmpty: 'Δεν υπάρχουν διαθέσιμοι στόχοι στον κατάλογο συνδέσεων αυτή τη στιγμή.',
    statusHeader: '**Κατάσταση υγείας συνδέσεων:**',
    statusEmpty: 'Δεν υπάρχουν ενεργές συνδέσεις για αναφορά κατάστασης.',
    guidanceLabel: '💡 **Καθοδήγηση:**',
    reconnectHint: '• Επανασύνδεση ή ενημέρωση διαπιστευτηρίων: `/connect {target} <νέα_διαπιστευτήρια>`',
    disconnectHint: '• Αποσύνδεση: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Ο τοπικός κατάλογος επαληθεύτηκε: `{path}`',
    credentialsVaultSuffix: 'Τα διαπιστευτήρια κρυπτογραφήθηκαν και αποθηκεύτηκαν με ασφάλεια στο vault.',
    secretStoreFailed: '❌ Αποτυχία αποθήκευσης κρυπτογραφημένων διαπιστευτηρίων για **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Σύνδεση {target} (Device Code Flow):**\n1. Ανοίξτε τον σύνδεσμο εξουσιοδότησης: {url}\n2. Επιβεβαιώστε την εξουσιοδότηση στο πρόγραμμα περιήγησης.\n3. Το Zavorth θα ολοκληρώσει το handshake αυτόματα.',
    missingDeviceVerificationUrl: 'Λείπει το URL επαλήθευσης συσκευής',
    oauthConnectedSuccess: '✅ Επιτυχής σύνδεση με **{target}** μέσω OAuth2!',
    oauthExchangeFailed: '❌ Αποτυχία ανταλλαγής διακριτικών OAuth για **{target}**: {details}',
    oauthListenerFailed: '⚠️ Αποτυχία εκκίνησης του listener επανάκλησης OAuth: {details}',
    oauthConfigActive: 'Η διαμόρφωση OAuth για **{target}** είναι ενεργή.',
    catalogConnectHint: 'Για να συνδεθείτε με οποιονδήποτε στόχο, πληκτρολογήστε: `/connect <στόχος>`',
    statusLabel: 'Κατάσταση',
    healthLabel: 'Υγεία',
    authLabel: 'Έλεγχος',
    connectedAtLabel: 'Συνδεδεμένο στις',
    disconnectServiceHint: '• Αποσύνδεση υπηρεσίας: `/disconnect <στόχος>`',
  },
  fa: {
    title: 'زیرسیستم اتصال سراسری',
    connectedSuccess: 'اتصال به **{target}** با موفقیت انجام شد!',
    disconnectedSuccess: 'اتصال از **{target}** قطع شد. اعتبارنامه‌های محلی پاک شدند.',
    alreadyConnected: 'هدف **{target}** از قبل متصل است (وضعیت: `connected`).',
    notConnected: "اتصال فعالی به '{target}' وجود ندارد.",
    unrecognizedTarget: "هدف '{target}' شناخته نشد.",
    rateLimitExceeded: 'محدودیت نرخ تجاوز شد: حداکثر ۱۰ دستور اتصال در دقیقه مجاز است. لطفاً صبر کنید.',
    apiKeyPrompt: 'برای اتصال به **{target}**، {label} خود را وارد کنید:\n`/connect {id} <کلید_شما>`',
    localPathPrompt: 'برای اتصال به **{target}**، مسیر دایرکتوری محلی را مشخص کنید:\n`/connect {id} /مسیر/{kind}`',
    oauthDeviceCodePrompt: 'برای تکمیل مجوز دستگاه برای **{target}**:\n۱. باز کنید: {url}\n۲. کد جفت‌سازی را وارد کنید: `{code}`',
    catalogTitle: 'کاتالوگ اتصالات موجود',
    noActiveConnections: 'اتصال فعالی یافت نشد.\n\n• اتصال یک یکپارچه‌سازی: `/connect <هدف>`\n• مشاهده کاتالوگ موجود: `/connections catalog`',
    usageConnect: '**روش استفاده از دستور Connect:**\n`/connect <هدف> [اعتبارنامه]`\n\n**مثال‌ها:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /مسیر/vault`\n\nبرای مشاهده همه اهداف موجود از `/connections catalog` استفاده کنید.',
    usageDisconnect: 'روش استفاده: `/disconnect <هدف>`\nمثال: `/disconnect stripe`',
    handshakeInProgress: 'در حال حاضر تلاش اتصالی برای این هدف در جریان است.',
    pathVerificationFailed: '❌ تأیید مسیر برای **{target}** ناموفق بود: {details}',
    apiKeyVerificationFailed: '❌ تأیید کلید برای **{target}** ناموفق بود: {details}',
    oauthClickLink: '🔗 **اتصال {target}:**\nبرای مجوز دادن به Zavorth روی پیوند زیر کلیک کنید:\n[مجوز {target}]({url})',
    oauthEnded: '⚠️ مجوز OAuth برای **{target}** پایان یافت: {details}',
    activeConnectionsHeader: '**اتصال‌های فعال شما ({count}):**',
    catalogEmpty: 'در حال حاضر هدفی در کاتالوگ اتصالات موجود نیست.',
    statusHeader: '**وضعیت سلامت اتصالات:**',
    statusEmpty: 'اتصال فعالی برای گزارش وضعیت وجود ندارد.',
    guidanceLabel: '💡 **راهنما:**',
    reconnectHint: '• اتصال مجدد یا به‌روزرسانی اعتبارنامه‌ها: `/connect {target} <اعتبارنامه_جدید>`',
    disconnectHint: '• قطع اتصال: `/disconnect {target}`',
    localPathVerifiedSuffix: 'دایرکتوری محلی تأیید شد: `{path}`',
    credentialsVaultSuffix: 'اعتبارنامه‌ها رمزنگاری و به‌صورت امن در گاوصندوق ذخیره شدند.',
    secretStoreFailed: '❌ ذخیره اعتبارنامه‌های رمزنگاری‌شده برای **{target}** ناموفق بود: {details}',
    deviceCodeFlowInstructions: '🔑 **اتصال {target} (جریان کد دستگاه):**\n۱. پیوند مجوز را باز کنید: {url}\n۲. مجوز را در مرورگر خود تأیید کنید.\n۳. Zavorth به‌طور خودکار دست‌دهی را تکمیل می‌کند.',
    missingDeviceVerificationUrl: 'URL تأیید دستگاه وجود ندارد',
    oauthConnectedSuccess: '✅ اتصال به **{target}** از طریق OAuth2 با موفقیت انجام شد!',
    oauthExchangeFailed: '❌ تبادل توکن OAuth برای **{target}** ناموفق بود: {details}',
    oauthListenerFailed: '⚠️ راه‌اندازی شنونده بازخورد OAuth ناموفق بود: {details}',
    oauthConfigActive: 'پیکربندی OAuth برای **{target}** فعال است.',
    catalogConnectHint: 'برای اتصال به هر هدف، تایپ کنید: `/connect <هدف>`',
    statusLabel: 'وضعیت',
    healthLabel: 'سلامت',
    authLabel: 'احراز هویت',
    connectedAtLabel: 'اتصال در',
    disconnectServiceHint: '• قطع اتصال سرویس: `/disconnect <هدف>`',
  },
  fi: {
    title: 'Universaali yhteysalijärjestelmä',
    connectedSuccess: 'Yhdistetty kohteeseen **{target}** onnistuneesti!',
    disconnectedSuccess: 'Yhteys kohteesta **{target}** katkaistu. Paikalliset tunnistetiedot poistettu.',
    alreadyConnected: 'Kohde **{target}** on jo yhdistetty (tila: `connected`).',
    notConnected: "Ei aktiivista yhteyttä kohteeseen '{target}'.",
    unrecognizedTarget: "Kohdetta '{target}' ei tunnistettu.",
    rateLimitExceeded: 'Nopeusrajoitus ylitetty: voit suorittaa enintään 10 yhteyskomentoa minuutissa. Odota hetki.',
    apiKeyPrompt: 'Yhdistä **{target}** antamalla {label}:\n`/connect {id} <oma_avain>`',
    localPathPrompt: 'Yhdistä **{target}** määrittämällä paikallisen hakemiston polku:\n`/connect {id} /polku/{kind}`',
    oauthDeviceCodePrompt: 'Suorita laitevaltuutus loppuun kohteelle **{target}**:\n1. Avaa: {url}\n2. Anna parituskoodi: `{code}`',
    catalogTitle: 'Saatavilla olevien yhteyksien luettelo',
    noActiveConnections: 'Aktiivisia yhteyksiä ei löytynyt.\n\n• Yhdistä integraatio: `/connect <kohde>`\n• Näytä saatava luettelo: `/connections catalog`',
    usageConnect: '**Connect-komennon käyttö:**\n`/connect <kohde> [tunnistetiedot]`\n\n**Esimerkit:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /polku/vault`\n\nKatso kaikki saatavat kohteet komennolla `/connections catalog`.',
    usageDisconnect: 'Käyttö: `/disconnect <kohde>`\nEsimerkki: `/disconnect stripe`',
    handshakeInProgress: 'Tälle kohteelle on jo käynnissä yhteysyritys.',
    pathVerificationFailed: '❌ Polun vahvistus epäonnistui kohteelle **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Avaimen vahvistus epäonnistui kohteelle **{target}**: {details}',
    oauthClickLink: '🔗 **Yhdistä {target}:**\nValtuuta Zavorth napsauttamalla alla olevaa linkkiä:\n[Valtuuta {target}]({url})',
    oauthEnded: '⚠️ OAuth-valtuutus kohteelle **{target}** päättyi: {details}',
    activeConnectionsHeader: '**Aktiiviset yhteytesi ({count}):**',
    catalogEmpty: 'Yhteysluettelossa ei ole tällä hetkellä saatavia kohteita.',
    statusHeader: '**Yhteyksien kunnon tila:**',
    statusEmpty: 'Ei aktiivisia yhteyksiä, joista raportoida tila.',
    guidanceLabel: '💡 **Ohje:**',
    reconnectHint: '• Yhdistä uudelleen tai päivitä tunnistetiedot: `/connect {target} <uudet_tiedot>`',
    disconnectHint: '• Katkaise yhteys: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Paikallinen hakemisto vahvistettu: `{path}`',
    credentialsVaultSuffix: 'Tunnistetiedot salattu ja tallennettu turvallisesti holviin.',
    secretStoreFailed: '❌ Salattujen tunnistetietojen tallennus kohteelle **{target}** epäonnistui: {details}',
    deviceCodeFlowInstructions: '🔑 **Yhdistä {target} (Device Code -virta):**\n1. Avaa valtuutuslinkki: {url}\n2. Vahvista valtuutus selaimessasi.\n3. Zavorth suorittaa handshaken automaattisesti.',
    missingDeviceVerificationUrl: 'Laitteen vahvistus-URL puuttuu',
    oauthConnectedSuccess: '✅ Yhdistetty kohteeseen **{target}** OAuth2:n kautta!',
    oauthExchangeFailed: '❌ OAuth-tokenien vaihto kohteelle **{target}** epäonnistui: {details}',
    oauthListenerFailed: '⚠️ OAuth-paluukutsukuuntelijan käynnistys epäonnistui: {details}',
    oauthConfigActive: 'OAuth-kokoonpano kohteelle **{target}** on aktiivinen.',
    catalogConnectHint: 'Yhdistä mikä tahansa kohde kirjoittamalla: `/connect <kohde>`',
    statusLabel: 'Tila',
    healthLabel: 'Kunto',
    authLabel: 'Todennus',
    connectedAtLabel: 'Yhdistetty',
    disconnectServiceHint: '• Katkaise palvelun yhteys: `/disconnect <kohde>`',
  },
  he: {
    title: 'מערכת חיבורים אוניברסלית',
    connectedSuccess: 'התחברת בהצלחה אל **{target}**!',
    disconnectedSuccess: 'התנתקת מ-{target}. פרטי הכניסה המקומיים נמחקו.',
    alreadyConnected: 'היעד **{target}** כבר מחובר (סטטוס: `connected`).',
    notConnected: "אין חיבור פעיל אל '{target}'.",
    unrecognizedTarget: "היעד '{target}' אינו מזוהה.",
    rateLimitExceeded: 'חריגה ממגבלת הקצב: ניתן לבצע עד 10 פקודות חיבור בדקה. נא להמתין.',
    apiKeyPrompt: 'כדי להתחבר אל **{target}**, ספק את ה-{label} שלך:\n`/connect {id} <המפתח_שלך>`',
    localPathPrompt: 'כדי להתחבר אל **{target}**, ציין את נתיב הספרייה המקומית:\n`/connect {id} /נתיב/{kind}`',
    oauthDeviceCodePrompt: 'כדי להשלים את הרשאת המכשיר עבור **{target}**:\n1. פתח: {url}\n2. הזן את קוד ההתאמה: `{code}`',
    catalogTitle: 'קטלוג החיבורים הזמינים',
    noActiveConnections: 'לא נמצאו חיבורים פעילים.\n\n• חבר אינטגרציה: `/connect <יעד>`\n• צפה בקטלוג הזמין: `/connections catalog`',
    usageConnect: '**שימוש בפקודת Connect:**\n`/connect <יעד> [פרטי_כניסה]`\n\n**דוגמאות:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /נתיב/vault`\n\nהשתמש ב-`/connections catalog` כדי לראות את כל היעדים הזמינים.',
    usageDisconnect: 'שימוש: `/disconnect <יעד>`\nדוגמה: `/disconnect stripe`',
    handshakeInProgress: 'כבר קיים ניסיון חיבור מתבצע עבור יעד זה.',
    pathVerificationFailed: '❌ אימות הנתיב נכשל עבור **{target}**: {details}',
    apiKeyVerificationFailed: '❌ אימות המפתח נכשל עבור **{target}**: {details}',
    oauthClickLink: '🔗 **חיבור {target}:**\nלחץ על הקישור למטה כדי להראות ל-Zavorth הרשאה:\n[הרשאה ל-{target}]({url})',
    oauthEnded: '⚠️ הרשאת OAuth עבור **{target}** הסתיימה: {details}',
    activeConnectionsHeader: '**החיבורים הפעילים שלך ({count}):**',
    catalogEmpty: 'אין יעדים זמינים בקטלוג החיבורים כרגע.',
    statusHeader: '**סטטוס תקינות החיבורים:**',
    statusEmpty: 'אין חיבורים פעילים לדיווח סטטוס.',
    guidanceLabel: '💡 **הנחיה:**',
    reconnectHint: '• חיבור מחדש או עדכון פרטי כניסה: `/connect {target} <פרטים_חדשים>`',
    disconnectHint: '• התנתק: `/disconnect {target}`',
    localPathVerifiedSuffix: 'הספרייה המקומית אומתה: `{path}`',
    credentialsVaultSuffix: 'פרטי הכניסה הוצפנו ונשמרו בבטחה בכספת.',
    secretStoreFailed: '❌ אחסון פרטי הכניסה המוצפנים עבור **{target}** נכשל: {details}',
    deviceCodeFlowInstructions: '🔑 **חיבור {target} (זרימת קוד מכשיר):**\n1. פתח את קישור ההרשאה: {url}\n2. אשר את ההרשאה בדפדפן שלך.\n3. Zavorth ישלים את הלחיצת יד אוטומטית.',
    missingDeviceVerificationUrl: 'חסר URL לאימות מכשיר',
    oauthConnectedSuccess: '✅ התחברת בהצלחה אל **{target}** דרך OAuth2!',
    oauthExchangeFailed: '❌ החלפת טוקני OAuth עבור **{target}** נכשלה: {details}',
    oauthListenerFailed: '⚠️ הפעלת מאזין הקריאה החוזרת OAuth נכשלה: {details}',
    oauthConfigActive: 'הגדרות OAuth עבור **{target}** פעילות.',
    catalogConnectHint: 'כדי להתחבר לכל יעד, הקלד: `/connect <יעד>`',
    statusLabel: 'סטטוס',
    healthLabel: 'תקינות',
    authLabel: 'אימות',
    connectedAtLabel: 'התחבר ב-',
    disconnectServiceHint: '• ניתוק שירות: `/disconnect <יעד>`',
  },
  hi: {
    title: 'यूनिवर्सल कनेक्शन उपप्रणाली',
    connectedSuccess: '**{target}** से सफलतापूर्वक जुड़ा!',
    disconnectedSuccess: '**{target}** से कनेक्शन हटाया गया। स्थानीय क्रेडेंशियल हटा दिए गए।',
    alreadyConnected: 'लक्ष्य **{target}** पहले से जुड़ा है (स्थिति: `connected`)।',
    notConnected: "'{target}' से कोई सक्रिय कनेक्शन नहीं।",
    unrecognizedTarget: "'{target}' लक्ष्य पहचाना नहीं गया।",
    rateLimitExceeded: 'दर सीमा पार हो गई: आप प्रति मिनट अधिकतम 10 कनेक्शन कमांड चला सकते हैं। कृपया प्रतीक्षा करें।',
    apiKeyPrompt: '**{target}** से जुड़ने के लिए, अपना {label} प्रदान करें:\n`/connect {id} <आपकी_कुंजी>`',
    localPathPrompt: '**{target}** से जुड़ने के लिए, स्थानीय निर्देशिका का पथ निर्दिष्ट करें:\n`/connect {id} /पथ/{kind}`',
    oauthDeviceCodePrompt: '**{target}** के लिए डिवाइस प्राधिकरण पूरा करने के लिए:\n1. खोलें: {url}\n2. पेयरिंग कोड दर्ज करें: `{code}`',
    catalogTitle: 'उपलब्ध कनेक्शन कैटलॉग',
    noActiveConnections: 'कोई सक्रिय कनेक्शन नहीं मिला।\n\n• एकीकरण जोड़ें: `/connect <लक्ष्य>`\n• उपलब्ध कैटलॉग देखें: `/connections catalog`',
    usageConnect: '**Connect कमांड का उपयोग:**\n`/connect <लक्ष्य> [क्रेडेंशियल]`\n\n**उदाहरण:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /पथ/vault`\n\nसभी उपलब्ध लक्ष्य देखने के लिए `/connections catalog` का उपयोग करें।',
    usageDisconnect: 'उपयोग: `/disconnect <लक्ष्य>`\nउदाहरण: `/disconnect stripe`',
    handshakeInProgress: 'इस लक्ष्य के लिए एक कनेक्शन प्रयास पहले से चल रहा है।',
    pathVerificationFailed: '❌ **{target}** के लिए पथ सत्यापन विफल: {details}',
    apiKeyVerificationFailed: '❌ **{target}** के लिए कुंजी सत्यापन विफल: {details}',
    oauthClickLink: '🔗 **{target} से जुड़ें:**\nZavorth को प्राधिकृत करने के लिए नीचे दिए लिंक पर क्लिक करें:\n[{target} प्राधिकृत करें]({url})',
    oauthEnded: '⚠️ **{target}** के लिए OAuth प्राधिकरण समाप्त हुआ: {details}',
    activeConnectionsHeader: '**आपके सक्रिय कनेक्शन ({count}):**',
    catalogEmpty: 'वर्तमान में कनेक्शन कैटलॉग में कोई लक्ष्य उपलब्ध नहीं है।',
    statusHeader: '**कनेक्शन स्वास्थ्य स्थिति:**',
    statusEmpty: 'स्थिति रिपोर्ट करने के लिए कोई सक्रिय कनेक्शन नहीं।',
    guidanceLabel: '💡 **मार्गदर्शन:**',
    reconnectHint: '• पुनः कनेक्ट करें या क्रेडेंशियल अपडेट करें: `/connect {target} <नए_क्रेडेंशियल>`',
    disconnectHint: '• डिस्कनेक्ट करें: `/disconnect {target}`',
    localPathVerifiedSuffix: 'स्थानीय निर्देशिका सत्यापित: `{path}`',
    credentialsVaultSuffix: 'क्रेडेंशियल एन्क्रिप्ट किए गए और वॉल्ट में सुरक्षित रूप से संग्रहीत।',
    secretStoreFailed: '❌ **{target}** के लिए एन्क्रिप्टेड क्रेडेंशियल संग्रहीत करने में विफल: {details}',
    deviceCodeFlowInstructions: '🔑 **{target} से जुड़ें (डिवाइस कोड फ्लो):**\n1. प्राधिकरण लिंक खोलें: {url}\n2. अपने ब्राउज़र में प्राधिकरण की पुष्टि करें।\n3. Zavorth स्वचालित रूप से हैंडशेक पूरा करेगा।',
    missingDeviceVerificationUrl: 'डिवाइस सत्यापन URL अनुपलब्ध है',
    oauthConnectedSuccess: '✅ OAuth2 के माध्यम से **{target}** से सफलतापूर्वक जुड़ा!',
    oauthExchangeFailed: '❌ **{target}** के लिए OAuth टोकन विनिमय विफल: {details}',
    oauthListenerFailed: '⚠️ OAuth कॉलबैक लिसनर प्रारंभ करने में विफल: {details}',
    oauthConfigActive: '**{target}** के लिए OAuth कॉन्फ़िगरेशन सक्रिय है।',
    catalogConnectHint: 'किसी भी लक्ष्य से जुड़ने के लिए टाइप करें: `/connect <लक्ष्य>`',
    statusLabel: 'स्थिति',
    healthLabel: 'स्वास्थ्य',
    authLabel: 'प्रमाणीकरण',
    connectedAtLabel: 'कनेक्ट समय',
    disconnectServiceHint: '• सेवा डिस्कनेक्ट करें: `/disconnect <लक्ष्य>`',
  },
  id: {
    title: 'Subsistem Koneksi Universal',
    connectedSuccess: 'Berhasil terhubung ke **{target}**!',
    disconnectedSuccess: 'Terputus dari **{target}**. Kredensial lokal dibersihkan.',
    alreadyConnected: 'Target **{target}** sudah terhubung (status: `connected`).',
    notConnected: "Tidak ada koneksi aktif ke '{target}'.",
    unrecognizedTarget: "Target '{target}' tidak dikenali.",
    rateLimitExceeded: 'Batas kecepatan terlampaui: Anda dapat menjalankan maksimal 10 perintah koneksi per menit. Mohon tunggu.',
    apiKeyPrompt: 'Untuk terhubung ke **{target}**, berikan {label} Anda:\n`/connect {id} <kunci_anda>`',
    localPathPrompt: 'Untuk terhubung ke **{target}**, tentukan jalur direktori lokal:\n`/connect {id} /jalur/ke/{kind}`',
    oauthDeviceCodePrompt: 'Untuk menyelesaikan otorisasi perangkat untuk **{target}**:\n1. Buka: {url}\n2. Masukkan kode pemasangan: `{code}`',
    catalogTitle: 'Katalog Koneksi yang Tersedia',
    noActiveConnections: 'Tidak ada koneksi aktif ditemukan.\n\n• Hubungkan integrasi: `/connect <target>`\n• Lihat katalog yang tersedia: `/connections catalog`',
    usageConnect: '**Penggunaan Perintah Connect:**\n`/connect <target> [kredensial]`\n\n**Contoh:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /jalur/ke/vault`\n\nGunakan `/connections catalog` untuk melihat semua target yang tersedia.',
    usageDisconnect: 'Penggunaan: `/disconnect <target>`\nContoh: `/disconnect stripe`',
    handshakeInProgress: 'Sudah ada upaya koneksi yang sedang berlangsung untuk target ini.',
    pathVerificationFailed: '❌ Verifikasi jalur gagal untuk **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Verifikasi kunci gagal untuk **{target}**: {details}',
    oauthClickLink: '🔗 **Hubungkan {target}:**\nKlik tautan di bawah untuk mengotorisasi Zavorth:\n[Otorisasi {target}]({url})',
    oauthEnded: '⚠️ Otorisasi OAuth untuk **{target}** berakhir: {details}',
    activeConnectionsHeader: '**Koneksi Aktif Anda ({count}):**',
    catalogEmpty: 'Saat ini tidak ada target yang tersedia dalam katalog koneksi.',
    statusHeader: '**Status Kesehatan Koneksi:**',
    statusEmpty: 'Tidak ada koneksi aktif untuk melaporkan status.',
    guidanceLabel: '💡 **Panduan:**',
    reconnectHint: '• Hubungkan kembali atau perbarui kredensial: `/connect {target} <kredensial_baru>`',
    disconnectHint: '• Putuskan: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Direktori lokal terverifikasi: `{path}`',
    credentialsVaultSuffix: 'Kredensial dienkripsi dan disimpan dengan aman di vault.',
    secretStoreFailed: '❌ Penyimpanan kredensial terenkripsi gagal untuk **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Hubungkan {target} (Alur Kode Perangkat):**\n1. Buka tautan otorisasi: {url}\n2. Konfirmasi otorisasi di peramban Anda.\n3. Zavorth akan menyelesaikan handshake secara otomatis.',
    missingDeviceVerificationUrl: 'URL verifikasi perangkat tidak ada',
    oauthConnectedSuccess: '✅ Berhasil terhubung ke **{target}** melalui OAuth2!',
    oauthExchangeFailed: '❌ Pertukaran token OAuth gagal untuk **{target}**: {details}',
    oauthListenerFailed: '⚠️ Gagal memulai listener callback OAuth: {details}',
    oauthConfigActive: 'Konfigurasi OAuth untuk **{target}** aktif.',
    catalogConnectHint: 'Untuk menghubungkan target apa pun, ketik: `/connect <target>`',
    statusLabel: 'Status',
    healthLabel: 'Kesehatan',
    authLabel: 'Otentikasi',
    connectedAtLabel: 'Terhubung pada',
    disconnectServiceHint: '• Putuskan layanan: `/disconnect <target>`',
  },
  ms: {
    title: 'Subsistem Sambungan Sejagat',
    connectedSuccess: 'Berjaya disambungkan ke **{target}**!',
    disconnectedSuccess: 'Diputuskan daripada **{target}**. Kredensial setempat dibersihkan.',
    alreadyConnected: 'Sasaran **{target}** sudah disambungkan (status: `connected`).',
    notConnected: "Tiada sambungan aktif ke '{target}'.",
    unrecognizedTarget: "Sasaran '{target}' tidak dikenali.",
    rateLimitExceeded: 'Had kadar melebihi: anda boleh melaksanakan maksimum 10 arahan sambungan seminit. Sila tunggu.',
    apiKeyPrompt: 'Untuk menyambung ke **{target}**, berikan {label} anda:\n`/connect {id} <kunci_anda>`',
    localPathPrompt: 'Untuk menyambung ke **{target}**, nyatakan laluan direktori setempat:\n`/connect {id} /laluan/{kind}`',
    oauthDeviceCodePrompt: 'Untuk melengkapkan kebenaran peranti untuk **{target}**:\n1. Buka: {url}\n2. Masukkan kod pemasangan: `{code}`',
    catalogTitle: 'Katalog Sambungan Tersedia',
    noActiveConnections: 'Tiada sambungan aktif ditemui.\n\n• Sambungkan integrasi: `/connect <sasaran>`\n• Lihat katalog tersedia: `/connections catalog`',
    usageConnect: '**Penggunaan Arahan Connect:**\n`/connect <sasaran> [kredensial]`\n\n**Contoh:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /laluan/vault`\n\nGunakan `/connections catalog` untuk melihat semua sasaran yang tersedia.',
    usageDisconnect: 'Penggunaan: `/disconnect <sasaran>`\nContoh: `/disconnect stripe`',
    handshakeInProgress: 'Sudah ada percubaan sambungan yang sedang berjalan untuk sasaran ini.',
    pathVerificationFailed: '❌ Pengesahan laluan gagal untuk **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Pengesahan kunci gagal untuk **{target}**: {details}',
    oauthClickLink: '🔗 **Sambung {target}:**\nKlik pautan di bawah untuk memberi kebenaran kepada Zavorth:\n[Beri Kebenaran {target}]({url})',
    oauthEnded: '⚠️ Kebenaran OAuth untuk **{target}** tamat: {details}',
    activeConnectionsHeader: '**Sambungan Aktif Anda ({count}):**',
    catalogEmpty: 'Tiada sasaran tersedia dalam katalog sambungan pada masa ini.',
    statusHeader: '**Status Kesihatan Sambungan:**',
    statusEmpty: 'Tiada sambungan aktif untuk melaporkan status.',
    guidanceLabel: '💡 **Panduan:**',
    reconnectHint: '• Sambung semula atau kemas kini kredensial: `/connect {target} <kredensial_baru>`',
    disconnectHint: '• Putuskan: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Direktori setempat disahkan: `{path}`',
    credentialsVaultSuffix: 'Kredensial disulitkan dan disimpan dengan selamat dalam peti besi.',
    secretStoreFailed: '❌ Penyimpanan kredensial disulitkan gagal untuk **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Sambung {target} (Aliran Kod Peranti):**\n1. Buka pautan kebenaran: {url}\n2. Sahkan kebenaran dalam pelayar anda.\n3. Zavorth akan melengkapkan handshake secara automatik.',
    missingDeviceVerificationUrl: 'URL pengesahan peranti tiada',
    oauthConnectedSuccess: '✅ Berjaya disambungkan ke **{target}** melalui OAuth2!',
    oauthExchangeFailed: '❌ Pertukaran token OAuth gagal untuk **{target}**: {details}',
    oauthListenerFailed: '⚠️ Gagal memulakan pendengar panggilan balik OAuth: {details}',
    oauthConfigActive: 'Konfigurasi OAuth untuk **{target}** aktif.',
    catalogConnectHint: 'Untuk menyambung mana-mana sasaran, taip: `/connect <sasaran>`',
    statusLabel: 'Status',
    healthLabel: 'Kesihatan',
    authLabel: 'Pengesahan',
    connectedAtLabel: 'Disambungkan pada',
    disconnectServiceHint: '• Putuskan perkhidmatan: `/disconnect <sasaran>`',
  },
  nl: {
    title: 'Universeel verbindingssubsysteem',
    connectedSuccess: 'Verbonden met **{target}**!',
    disconnectedSuccess: 'Verbinding met **{target}** verbroken. Lokale inloggegevens gewist.',
    alreadyConnected: 'Doel **{target}** is al verbonden (status: `connected`).',
    notConnected: "Geen actieve verbinding met '{target}'.",
    unrecognizedTarget: "Doel '{target}' niet herkend.",
    rateLimitExceeded: 'Snelheidslimiet overschreden: je kunt maximaal 10 verbindingsopdrachten per minuut uitvoeren. Wacht even.',
    apiKeyPrompt: 'Om **{target}** te verbinden, geef je {label} op:\n`/connect {id} <jouw_sleutel>`',
    localPathPrompt: 'Om **{target}** te verbinden, geef je het pad van de lokale map op:\n`/connect {id} /pad/naar/{kind}`',
    oauthDeviceCodePrompt: 'Om apparaatautorisatie voor **{target}** te voltooien:\n1. Open: {url}\n2. Voer de koppelcode in: `{code}`',
    catalogTitle: 'Catalogus van beschikbare verbindingen',
    noActiveConnections: 'Geen actieve verbindingen gevonden.\n\n• Verbind een integratie: `/connect <doel>`\n• Bekijk de beschikbare catalogus: `/connections catalog`',
    usageConnect: '**Gebruik van Connect-opdracht:**\n`/connect <doel> [inloggegevens]`\n\n**Voorbeelden:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /pad/naar/vault`\n\nGebruik `/connections catalog` om alle beschikbare doelen te bekijken.',
    usageDisconnect: 'Gebruik: `/disconnect <doel>`\nVoorbeeld: `/disconnect stripe`',
    handshakeInProgress: 'Voor dit doel is al een verbindingspoging bezig.',
    pathVerificationFailed: '❌ Padverificatie mislukt voor **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Sleutelverificatie mislukt voor **{target}**: {details}',
    oauthClickLink: '🔗 **Verbind {target}:**\nKlik op de onderstaande link om Zavorth te autoriseren:\n[Autoriseer {target}]({url})',
    oauthEnded: '⚠️ OAuth-autorisatie voor **{target}** beëindigd: {details}',
    activeConnectionsHeader: '**Jouw actieve verbindingen ({count}):**',
    catalogEmpty: 'Er zijn momenteel geen doelen beschikbaar in de verbindingscatalogus.',
    statusHeader: '**Gezondheidsstatus van verbindingen:**',
    statusEmpty: 'Geen actieve verbindingen om status over te rapporteren.',
    guidanceLabel: '💡 **Richtlijn:**',
    reconnectHint: '• Opnieuw verbinden of inloggegevens bijwerken: `/connect {target} <nieuwe_gegevens>`',
    disconnectHint: '• Verbreken: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Lokale map geverifieerd: `{path}`',
    credentialsVaultSuffix: 'Inloggegevens versleuteld en veilig opgeslagen in de kluis.',
    secretStoreFailed: '❌ Opslaan van versleutelde inloggegevens mislukt voor **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Verbind {target} (Device Code-stroom):**\n1. Open de autorisatielink: {url}\n2. Bevestig de autorisatie in je browser.\n3. Zavorth voltooit de handshake automatisch.',
    missingDeviceVerificationUrl: 'Apparaatverificatie-URL ontbreekt',
    oauthConnectedSuccess: '✅ Verbonden met **{target}** via OAuth2!',
    oauthExchangeFailed: '❌ OAuth-tokenuitwisseling mislukt voor **{target}**: {details}',
    oauthListenerFailed: '⚠️ Starten van OAuth-callback-listener mislukt: {details}',
    oauthConfigActive: 'OAuth-configuratie voor **{target}** is actief.',
    catalogConnectHint: 'Om elk doel te verbinden, typ: `/connect <doel>`',
    statusLabel: 'Status',
    healthLabel: 'Gezondheid',
    authLabel: 'Auth',
    connectedAtLabel: 'Verbonden op',
    disconnectServiceHint: '• Dienst verbreken: `/disconnect <doel>`',
  },
  no: {
    title: 'Universelt tilkoblingssubsystem',
    connectedSuccess: 'Koblet til **{target}** med suksess!',
    disconnectedSuccess: 'Koblet fra **{target}**. Lokale legitimasjonsopplysninger slettet.',
    alreadyConnected: 'Målet **{target}** er allerede koblet til (status: `connected`).',
    notConnected: "Ingen aktiv tilkobling til '{target}'.",
    unrecognizedTarget: "Målet '{target}' ble ikke gjenkjent.",
    rateLimitExceeded: 'Fartsgrense overskredet: du kan utføre maksimalt 10 tilkoblingskommandoer per minutt. Vent litt.',
    apiKeyPrompt: 'For å koble til **{target}**, oppgi din {label}:\n`/connect {id} <din_nokkel>`',
    localPathPrompt: 'For å koble til **{target}**, oppgi banen til den lokale mappen:\n`/connect {id} /bane/til/{kind}`',
    oauthDeviceCodePrompt: 'For å fullføre enhetsautorisasjon for **{target}**:\n1. Åpne: {url}\n2. Angi paringskoden: `{code}`',
    catalogTitle: 'Katalog over tilgjengelige tilkoblinger',
    noActiveConnections: 'Ingen aktive tilkoblinger funnet.\n\n• Koble til en integrasjon: `/connect <mål>`\n• Se tilgjengelig katalog: `/connections catalog`',
    usageConnect: '**Bruk av Connect-kommandoen:**\n`/connect <mål> [legitimasjon]`\n\n**Eksempler:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /bane/til/vault`\n\nBruk `/connections catalog` for å se alle tilgjengelige mål.',
    usageDisconnect: 'Bruk: `/disconnect <mål>`\nEksempel: `/disconnect stripe`',
    handshakeInProgress: 'Det pågår allerede et tilkoblingsforsøk for dette målet.',
    pathVerificationFailed: '❌ Bateverifisering mislyktes for **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Nøkkelverifisering mislyktes for **{target}**: {details}',
    oauthClickLink: '🔗 **Koble til {target}:**\nKlikk på lenken nedenfor for å autorisere Zavorth:\n[Autoriser {target}]({url})',
    oauthEnded: '⚠️ OAuth-autorisasjon for **{target}** er avsluttet: {details}',
    activeConnectionsHeader: '**Dine aktive tilkoblinger ({count}):**',
    catalogEmpty: 'Det er for øyeblikket ingen mål i tilkoblingskatalogen.',
    statusHeader: '**Tilkoblingshelsestatus:**',
    statusEmpty: 'Ingen aktive tilkoblinger å rapportere status for.',
    guidanceLabel: '💡 **Veiledning:**',
    reconnectHint: '• Koble til på nytt eller oppdater legitimasjon: `/connect {target} <nye_opplysninger>`',
    disconnectHint: '• Koble fra: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Lokal mappe verifisert: `{path}`',
    credentialsVaultSuffix: 'Legitimasjon kryptert og trygt lagret i hvelvet.',
    secretStoreFailed: '❌ Lagring av kryptert legitimasjon mislyktes for **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Koble til {target} (Device Code-strøm):**\n1. Åpne autorisasjonslenken: {url}\n2. Bekreft autorisasjonen i nettleseren din.\n3. Zavorth fullfører handshaken automatisk.',
    missingDeviceVerificationUrl: 'Enhetsverifiserings-URL mangler',
    oauthConnectedSuccess: '✅ Koblet til **{target}** med suksess via OAuth2!',
    oauthExchangeFailed: '❌ OAuth-tokenutveksling mislyktes for **{target}**: {details}',
    oauthListenerFailed: '⚠️ Start av OAuth-tilbakeringingslytter mislyktes: {details}',
    oauthConfigActive: 'OAuth-konfigurasjon for **{target}** er aktiv.',
    catalogConnectHint: 'For å koble til ethvert mål, skriv: `/connect <mål>`',
    statusLabel: 'Status',
    healthLabel: 'Helse',
    authLabel: 'Auth',
    connectedAtLabel: 'Koblet til',
    disconnectServiceHint: '• Koble fra en tjeneste: `/disconnect <mål>`',
  },
  phi: {
    title: 'Universal Connection Subsystem',
    connectedSuccess: 'Matagumpay na nakakonekta sa **{target}**!',
    disconnectedSuccess: 'Naalis ang koneksyon sa **{target}**. Tinanggal ang lokal na mga kredensyal.',
    alreadyConnected: 'Ang target na **{target}** ay nakakonekta na (status: `connected`).',
    notConnected: "Walang aktibong koneksyon sa '{target}'.",
    unrecognizedTarget: "Hindi nakilala ang target na '{target}'.",
    rateLimitExceeded: 'Lumampas sa limitasyon ng rate: maaari kang magpatakbo ng hindi hihigit sa 10 command ng koneksyon bawat minuto. Mangyaring maghintay.',
    apiKeyPrompt: 'Upang kumonekta sa **{target}**, ibigay ang iyong {label}:\n`/connect {id} <iyong_susi>`',
    localPathPrompt: 'Upang kumonekta sa **{target}**, tukuyin ang landas ng lokal na direktoryo:\n`/connect {id} /landas/patungo/{kind}`',
    oauthDeviceCodePrompt: 'Upang makumpleto ang awtorisasyon ng device para sa **{target}**:\n1. Buksan: {url}\n2. Ilagay ang pairing code: `{code}`',
    catalogTitle: 'Katalogo ng Magagamit na Koneksyon',
    noActiveConnections: 'Walang nakitang aktibong koneksyon.\n\n• Kumonekta ng integrasyon: `/connect <target>`\n• Tingnan ang magagamit na katalogo: `/connections catalog`',
    usageConnect: '**Paggamit ng Connect Command:**\n`/connect <target> [kredensyal]`\n\n**Mga Halimbawa:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /landas/vault`\n\nGamitin ang `/connections catalog` upang makita ang lahat ng magagamit na target.',
    usageDisconnect: 'Paggamit: `/disconnect <target>`\nHalimbawa: `/disconnect stripe`',
    handshakeInProgress: 'Mayroon nang nagpapatuloy na pagtatangkang kumonekta para sa target na ito.',
    pathVerificationFailed: '❌ Nabigo ang pagpapatunay ng landas para sa **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Nabigo ang pagpapatunay ng susi para sa **{target}**: {details}',
    oauthClickLink: '🔗 **Kumonekta sa {target}:**\nI-click ang link sa ibaba upang bigyan ng awtorisasyon ang Zavorth:\n[Bigyan ng Awtorisasyon {target}]({url})',
    oauthEnded: '⚠️ Natapos ang awtorisasyon ng OAuth para sa **{target}**: {details}',
    activeConnectionsHeader: '**Ang Iyong Mga Aktibong Koneksyon ({count}):**',
    catalogEmpty: 'Walang magagamit na target sa katalogo ng koneksyon sa kasalukuyan.',
    statusHeader: '**Katayuan ng Kalusugan ng Koneksyon:**',
    statusEmpty: 'Walang aktibong koneksyon upang mag-ulat ng katayuan.',
    guidanceLabel: '💡 **Gabay:**',
    reconnectHint: '• Kumonekta muli o i-update ang mga kredensyal: `/connect {target} <bagong_kredensyal>`',
    disconnectHint: '• Magdiskonekta: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Napatunayan ang lokal na direktoryo: `{path}`',
    credentialsVaultSuffix: 'Na-encrypt at ligtas na naimbak ang mga kredensyal sa vault.',
    secretStoreFailed: '❌ Nabigo ang pag-iimbak ng naka-encrypt na mga kredensyal para sa **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Kumonekta sa {target} (Device Code Flow):**\n1. Buksan ang link ng awtorisasyon: {url}\n2. Kumpirmahin ang awtorisasyon sa iyong browser.\n3. Awtomatikong kukumpletuhin ng Zavorth ang handshake.',
    missingDeviceVerificationUrl: 'Kulang ang URL ng pagpapatunay ng device',
    oauthConnectedSuccess: '✅ Matagumpay na nakakonekta sa **{target}** sa pamamagitan ng OAuth2!',
    oauthExchangeFailed: '❌ Nabigo ang palitan ng OAuth token para sa **{target}**: {details}',
    oauthListenerFailed: '⚠️ Nabigo ang pagsisimula ng OAuth callback listener: {details}',
    oauthConfigActive: 'Aktibo ang OAuth configuration para sa **{target}**.',
    catalogConnectHint: 'Upang kumonekta sa anumang target, i-type: `/connect <target>`',
    statusLabel: 'Katayuan',
    healthLabel: 'Kalusugan',
    authLabel: 'Pagpapatunay',
    connectedAtLabel: 'Konektado noong',
    disconnectServiceHint: '• Magdiskonekta ng serbisyo: `/disconnect <target>`',
  },
  pl: {
    title: 'Uniwersalny podsystem połączeń',
    connectedSuccess: 'Pomyślnie połączono z **{target}**!',
    disconnectedSuccess: 'Rozłączono z **{target}**. Lokalne poświadczenia usunięte.',
    alreadyConnected: 'Cel **{target}** jest już połączony (status: `connected`).',
    notConnected: "Brak aktywnego połączenia z '{target}'.",
    unrecognizedTarget: "Cel '{target}' nie został rozpoznany.",
    rateLimitExceeded: 'Przekroczono limit częstotliwości: można wykonać maksymalnie 10 poleceń połączenia na minutę. Proszę czekać.',
    apiKeyPrompt: 'Aby połączyć się z **{target}**, podaj swój {label}:\n`/connect {id} <twoj_klucz>`',
    localPathPrompt: 'Aby połączyć się z **{target}**, podaj ścieżkę do lokalnego katalogu:\n`/connect {id} /sciezka/do/{kind}`',
    oauthDeviceCodePrompt: 'Aby ukończyć autoryzację urządzenia dla **{target}**:\n1. Otwórz: {url}\n2. Wprowadź kod parowania: `{code}`',
    catalogTitle: 'Katalog dostępnych połączeń',
    noActiveConnections: 'Nie znaleziono aktywnych połączeń.\n\n• Połącz integrację: `/connect <cel>`\n• Zobacz dostępny katalog: `/connections catalog`',
    usageConnect: '**Użycie polecenia Connect:**\n`/connect <cel> [poświadczenia]`\n\n**Przykłady:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /sciezka/do/vault`\n\nUżyj `/connections catalog`, aby zobaczyć wszystkie dostępne cele.',
    usageDisconnect: 'Użycie: `/disconnect <cel>`\nPrzykład: `/disconnect stripe`',
    handshakeInProgress: 'Dla tego celu trwa już próba połączenia.',
    pathVerificationFailed: '❌ Weryfikacja ścieżki nie powiodła się dla **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Weryfikacja klucza nie powiodła się dla **{target}**: {details}',
    oauthClickLink: '🔗 **Połącz {target}:**\nKliknij poniższy link, aby autoryzować Zavorth:\n[Autoryzuj {target}]({url})',
    oauthEnded: '⚠️ Autoryzacja OAuth dla **{target}** zakończona: {details}',
    activeConnectionsHeader: '**Twoje aktywne połączenia ({count}):**',
    catalogEmpty: 'Obecnie nie ma celów w katalogu połączeń.',
    statusHeader: '**Stan kondycji połączeń:**',
    statusEmpty: 'Brak aktywnych połączeń do raportowania stanu.',
    guidanceLabel: '💡 **Wskazówka:**',
    reconnectHint: '• Połącz ponownie lub zaktualizuj poświadczenia: `/connect {target} <nowe_dane>`',
    disconnectHint: '• Rozłącz: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Lokalny katalog zweryfikowany: `{path}`',
    credentialsVaultSuffix: 'Poświadczenia zaszyfrowane i bezpiecznie przechowywane w sejfie.',
    secretStoreFailed: '❌ Zapisanie zaszyfrowanych poświadczeń nie powiodło się dla **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Połącz {target} (Device Code Flow):**\n1. Otwórz link autoryzacji: {url}\n2. Potwierdź autoryzację w przeglądarce.\n3. Zavorth automatycznie ukończy handshake.',
    missingDeviceVerificationUrl: 'Brak URL weryfikacji urządzenia',
    oauthConnectedSuccess: '✅ Pomyślnie połączono z **{target}** przez OAuth2!',
    oauthExchangeFailed: '❌ Wymiana tokenów OAuth nie powiodła się dla **{target}**: {details}',
    oauthListenerFailed: '⚠️ Uruchomienie nasłuchiwacza wywołań zwrotnych OAuth nie powiodło się: {details}',
    oauthConfigActive: 'Konfiguracja OAuth dla **{target}** jest aktywna.',
    catalogConnectHint: 'Aby połączyć dowolny cel, wpisz: `/connect <cel>`',
    statusLabel: 'Status',
    healthLabel: 'Kondycja',
    authLabel: 'Uwierzytelnianie',
    connectedAtLabel: 'Połączono',
    disconnectServiceHint: '• Rozłącz usługę: `/disconnect <cel>`',
  },
  ro: {
    title: 'Subsistem universal de conexiuni',
    connectedSuccess: 'Conectat cu succes la **{target}**!',
    disconnectedSuccess: 'Deconectat de la **{target}**. Credențialele locale au fost șterse.',
    alreadyConnected: 'Ținta **{target}** este deja conectată (stare: `connected`).',
    notConnected: "Nicio conexiune activă la '{target}'.",
    unrecognizedTarget: "Ținta '{target}' nu a fost recunoscută.",
    rateLimitExceeded: 'Limită de frecvență depășită: puteți executa maximum 10 comenzi de conexiune pe minut. Vă rugăm să așteptați.',
    apiKeyPrompt: 'Pentru a vă conecta la **{target}**, furnizați {label}:\n`/connect {id} <cheia_dvs>`',
    localPathPrompt: 'Pentru a vă conecta la **{target}**, specificați calea directorului local:\n`/connect {id} /cale/{kind}`',
    oauthDeviceCodePrompt: 'Pentru a finaliza autorizarea dispozitivului pentru **{target}**:\n1. Deschideți: {url}\n2. Introduceți codul de asociere: `{code}`',
    catalogTitle: 'Catalogul conexiunilor disponibile',
    noActiveConnections: 'Nu au fost găsite conexiuni active.\n\n• Conectați o integrare: `/connect <țintă>`\n• Vedeți catalogul disponibil: `/connections catalog`',
    usageConnect: '**Utilizarea comenzii Connect:**\n`/connect <țintă> [credențiale]`\n\n**Exemple:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /cale/vault`\n\nFolosiți `/connections catalog` pentru a vedea toate țintele disponibile.',
    usageDisconnect: 'Utilizare: `/disconnect <țintă>`\nExemplu: `/disconnect stripe`',
    handshakeInProgress: 'Există deja o încercare de conectare în curs pentru această țintă.',
    pathVerificationFailed: '❌ Verificarea căii a eșuat pentru **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Verificarea cheii a eșuat pentru **{target}**: {details}',
    oauthClickLink: '🔗 **Conectați {target}:**\nFaceți clic pe linkul de mai jos pentru a autoriza Zavorth:\n[Autorizați {target}]({url})',
    oauthEnded: '⚠️ Autorizarea OAuth pentru **{target}** s-a încheiat: {details}',
    activeConnectionsHeader: '**Conexiunile dvs. active ({count}):**',
    catalogEmpty: 'Momentan nu există ținte disponibile în catalogul de conexiuni.',
    statusHeader: '**Starea de sănătate a conexiunilor:**',
    statusEmpty: 'Nicio conexiune activă pentru a raporta starea.',
    guidanceLabel: '💡 **Îndrumare:**',
    reconnectHint: '• Reconectați sau actualizați credențialele: `/connect {target} <noi_credențiale>`',
    disconnectHint: '• Deconectați: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Directorul local verificat: `{path}`',
    credentialsVaultSuffix: 'Credențialele au fost criptate și stocate în siguranță în seif.',
    secretStoreFailed: '❌ Stocarea credențialelor criptate a eșuat pentru **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Conectați {target} (Flux Device Code):**\n1. Deschideți linkul de autorizare: {url}\n2. Confirmați autorizarea în browser.\n3. Zavorth va finaliza handshake-ul automat.',
    missingDeviceVerificationUrl: 'Lipsește URL-ul de verificare a dispozitivului',
    oauthConnectedSuccess: '✅ Conectat cu succes la **{target}** prin OAuth2!',
    oauthExchangeFailed: '❌ Schimbul de token-uri OAuth a eșuat pentru **{target}**: {details}',
    oauthListenerFailed: '⚠️ Pornirea ascultătorului de callback OAuth a eșuat: {details}',
    oauthConfigActive: 'Configurația OAuth pentru **{target}** este activă.',
    catalogConnectHint: 'Pentru a conecta orice țintă, tastați: `/connect <țintă>`',
    statusLabel: 'Stare',
    healthLabel: 'Sănătate',
    authLabel: 'Autentificare',
    connectedAtLabel: 'Conectat la',
    disconnectServiceHint: '• Deconectați un serviciu: `/disconnect <țintă>`',
  },
  sk: {
    title: 'Univerzálny subsystém pripojení',
    connectedSuccess: 'Úspešne pripojené k **{target}**!',
    disconnectedSuccess: 'Odpojené od **{target}**. Miestne poverenia boli vymazané.',
    alreadyConnected: 'Cieľ **{target}** je už pripojený (stav: `connected`).',
    notConnected: "Žiadne aktívne pripojenie k '{target}'.",
    unrecognizedTarget: "Cieľ '{target}' nebol rozpoznaný.",
    rateLimitExceeded: 'Prekročený limit frekvencie: za minútu možno vykonať najviac 10 príkazov pripojenia. Počkajte prosím.',
    apiKeyPrompt: 'Pre pripojenie k **{target}** zadajte svoj {label}:\n`/connect {id} <vas_kľuc>`',
    localPathPrompt: 'Pre pripojenie k **{target}** zadajte cestu k miestnemu adresáru:\n`/connect {id} /cesta/k/{kind}`',
    oauthDeviceCodePrompt: 'Pre dokončenie autorizácie zariadenia pre **{target}**:\n1. Otvorte: {url}\n2. Zadajte párovací kód: `{code}`',
    catalogTitle: 'Katalóg dostupných pripojení',
    noActiveConnections: 'Nenašli sa žiadne aktívne pripojenia.\n\n• Pripojte integráciu: `/connect <cieľ>`\n• Zobrazte katalóg: `/connections catalog`',
    usageConnect: '**Použitie príkazu Connect:**\n`/connect <cieľ> [poverenia]`\n\n**Príklady:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /cesta/k/vault`\n\nPomocou `/connections catalog` zobrazíte všetky dostupné ciele.',
    usageDisconnect: 'Použitie: `/disconnect <cieľ>`\nPríklad: `/disconnect stripe`',
    handshakeInProgress: 'Pre tento cieľ už prebieha pokus o pripojenie.',
    pathVerificationFailed: '❌ Overenie cesty pre **{target}** zlyhalo: {details}',
    apiKeyVerificationFailed: '❌ Overenie kľúča pre **{target}** zlyhalo: {details}',
    oauthClickLink: '🔗 **Pripojiť {target}:**\nKliknutím na odkaz nižšie autorizujete Zavorth:\n[Autorizovať {target}]({url})',
    oauthEnded: '⚠️ Autorizácia OAuth pre **{target}** sa skončila: {details}',
    activeConnectionsHeader: '**Vaše aktívne pripojenia ({count}):**',
    catalogEmpty: 'V katalógu pripojení momentálne nie sú žiadne ciele.',
    statusHeader: '**Stav integrity pripojení:**',
    statusEmpty: 'Žiadne aktívne pripojenia na zobrazenie stavu.',
    guidanceLabel: '💡 **Návod:**',
    reconnectHint: '• Znova pripojiť alebo aktualizovať poverenia: `/connect {target} <nove_poverenia>`',
    disconnectHint: '• Odpojiť: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Miestny adresár overený: `{path}`',
    credentialsVaultSuffix: 'Poverenia boli zašifrované a bezpečne uložené do trezora.',
    secretStoreFailed: '❌ Uloženie šifrovaných poverení pre **{target}** zlyhalo: {details}',
    deviceCodeFlowInstructions: '🔑 **Pripojiť {target} (Device Code Flow):**\n1. Otvorte autorizačný odkaz: {url}\n2. Potvrďte autorizáciu v prehliadači.\n3. Zavorth dokončí handshake automaticky.',
    missingDeviceVerificationUrl: 'Chýba URL na overenie zariadenia',
    oauthConnectedSuccess: '✅ Úspešne pripojené k **{target}** cez OAuth2!',
    oauthExchangeFailed: '❌ Výmena tokenov OAuth pre **{target}** zlyhala: {details}',
    oauthListenerFailed: '⚠️ Spustenie počúvania OAuth callbackov zlyhalo: {details}',
    oauthConfigActive: 'Konfigurácia OAuth pre **{target}** je aktívna.',
    catalogConnectHint: 'Pre pripojenie ľubovoľného cieľa napíšte: `/connect <cieľ>`',
    statusLabel: 'Stav',
    healthLabel: 'Integrita',
    authLabel: 'Overenie',
    connectedAtLabel: 'Pripojené',
    disconnectServiceHint: '• Odpojiť službu: `/disconnect <cieľ>`',
  },
  sv: {
    title: 'Universellt anslutningssubsystem',
    connectedSuccess: 'Ansluten till **{target}**!',
    disconnectedSuccess: 'Frånkopplad från **{target}**. Lokala autentiseringsuppgifter rensade.',
    alreadyConnected: 'Målet **{target}** är redan anslutet (status: `connected`).',
    notConnected: "Ingen aktiv anslutning till '{target}'.",
    unrecognizedTarget: "Målet '{target}' kändes inte igen.",
    rateLimitExceeded: 'Hastighetsgräns överskriden: du kan utföra högst 10 anslutningskommandon per minut. Vänta en stund.',
    apiKeyPrompt: 'För att ansluta till **{target}**, ange din {label}:\n`/connect {id} <din_nyckel>`',
    localPathPrompt: 'För att ansluta till **{target}**, ange sökvägen till den lokala katalogen:\n`/connect {id} /sokvag/till/{kind}`',
    oauthDeviceCodePrompt: 'För att slutföra enhetsauktorisering för **{target}**:\n1. Öppna: {url}\n2. Ange parningskoden: `{code}`',
    catalogTitle: 'Katalog över tillgängliga anslutningar',
    noActiveConnections: 'Inga aktiva anslutningar hittades.\n\n• Anslut en integration: `/connect <mål>`\n• Visa tillgänglig katalog: `/connections catalog`',
    usageConnect: '**Användning av Connect-kommandot:**\n`/connect <mål> [uppgifter]`\n\n**Exempel:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /sokvag/vault`\n\nAnvänd `/connections catalog` för att se alla tillgängliga mål.',
    usageDisconnect: 'Användning: `/disconnect <mål>`\nExempel: `/disconnect stripe`',
    handshakeInProgress: 'Det pågår redan ett anslutningsförsök för detta mål.',
    pathVerificationFailed: '❌ Sökvägsverifiering misslyckades för **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Nyckelverifiering misslyckades för **{target}**: {details}',
    oauthClickLink: '🔗 **Anslut {target}:**\nKlicka på länken nedan för att auktorisera Zavorth:\n[Auktorisera {target}]({url})',
    oauthEnded: '⚠️ OAuth-auktorisering för **{target}** avslutad: {details}',
    activeConnectionsHeader: '**Dina aktiva anslutningar ({count}):**',
    catalogEmpty: 'Det finns för närvarande inga mål i anslutningskatalogen.',
    statusHeader: '**Hälsostatus för anslutningar:**',
    statusEmpty: 'Inga aktiva anslutningar att rapportera status för.',
    guidanceLabel: '💡 **Vägledning:**',
    reconnectHint: '• Återanslut eller uppdatera uppgifter: `/connect {target} <nya_uppgifter>`',
    disconnectHint: '• Koppla från: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Lokal katalog verifierad: `{path}`',
    credentialsVaultSuffix: 'Uppgifterna krypterade och säkert lagrade i valvet.',
    secretStoreFailed: '❌ Lagring av krypterade uppgifter misslyckades för **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Anslut {target} (Device Code-flöde):**\n1. Öppna auktoriseringslänken: {url}\n2. Bekräfta auktoriseringen i webbläsaren.\n3. Zavorth slutför handskakningen automatiskt.',
    missingDeviceVerificationUrl: 'URL för enhetsverifiering saknas',
    oauthConnectedSuccess: '✅ Ansluten till **{target}** via OAuth2!',
    oauthExchangeFailed: '❌ OAuth-tokenutbyte misslyckades för **{target}**: {details}',
    oauthListenerFailed: '⚠️ Start av OAuth-återuppringningslyssnare misslyckades: {details}',
    oauthConfigActive: 'OAuth-konfigurationen för **{target}** är aktiv.',
    catalogConnectHint: 'För att ansluta valfritt mål, skriv: `/connect <mål>`',
    statusLabel: 'Status',
    healthLabel: 'Hälsa',
    authLabel: 'Auth',
    connectedAtLabel: 'Ansluten',
    disconnectServiceHint: '• Koppla från en tjänst: `/disconnect <mål>`',
  },
  th: {
    title: 'ระบบย่อยการเชื่อมต่อสากล',
    connectedSuccess: 'เชื่อมต่อกับ **{target}** สำเร็จแล้ว!',
    disconnectedSuccess: 'ตัดการเชื่อมต่อจาก **{target}** ลบข้อมูลรับรองในเครื่องแล้ว',
    alreadyConnected: 'เป้าหมาย **{target}** เชื่อมต่ออยู่แล้ว (สถานะ: `connected`)',
    notConnected: "ไม่มีการเชื่อมต่อที่ใช้งานกับ '{target}'",
    unrecognizedTarget: "ไม่รู้จักเป้าหมาย '{target}'",
    rateLimitExceeded: 'เกินขีดจำกัดอัตรา: คุณสามารถรันคำสั่งเชื่อมต่อได้สูงสุด 10 ครั้งต่อนาที กรุณารอสักครู่',
    apiKeyPrompt: 'เพื่อเชื่อมต่อกับ **{target}** โปรดระบุ {label} ของคุณ:\n`/connect {id} <คีย์ของคุณ>`',
    localPathPrompt: 'เพื่อเชื่อมต่อกับ **{target}** โปรดระบุเส้นทางของไดเรกทอรีในเครื่อง:\n`/connect {id} /เส้นทาง/{kind}`',
    oauthDeviceCodePrompt: 'เพื่อเสร็จสิ้นการอนุญาตอุปกรณ์สำหรับ **{target}**:\n1. เปิด: {url}\n2. ป้อนรหัสจับคู่: `{code}`',
    catalogTitle: 'แคตตาล็อกการเชื่อมต่อที่พร้อมใช้งาน',
    noActiveConnections: 'ไม่พบการเชื่อมต่อที่ใช้งานอยู่\n\n• เชื่อมต่ออินทิเกรชัน: `/connect <เป้าหมาย>`\n• ดูแคตตาล็อกที่พร้อมใช้งาน: `/connections catalog`',
    usageConnect: '**วิธีใช้คำสั่ง Connect:**\n`/connect <เป้าหมาย> [ข้อมูลรับรอง]`\n\n**ตัวอย่าง:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /เส้นทาง/vault`\n\nใช้ `/connections catalog` เพื่อดูเป้าหมายทั้งหมดที่มี',
    usageDisconnect: 'วิธีใช้: `/disconnect <เป้าหมาย>`\nตัวอย่าง: `/disconnect stripe`',
    handshakeInProgress: 'มีการพยายามเชื่อมต่อสำหรับเป้าหมายนี้อยู่แล้ว',
    pathVerificationFailed: '❌ การตรวจสอบเส้นทางล้มเหลวสำหรับ **{target}**: {details}',
    apiKeyVerificationFailed: '❌ การตรวจสอบคีย์ล้มเหลวสำหรับ **{target}**: {details}',
    oauthClickLink: '🔗 **เชื่อมต่อ {target}:**\nคลิกลิงก์ด้านล่างเพื่ออนุญาต Zavorth:\n[อนุญาต {target}]({url})',
    oauthEnded: '⚠️ การอนุญาต OAuth สำหรับ **{target}** สิ้นสุดลง: {details}',
    activeConnectionsHeader: '**การเชื่อมต่อที่ใช้งานของคุณ ({count}):**',
    catalogEmpty: 'ไม่มีเป้าหมายในแคตตาล็อกการเชื่อมต่อในขณะนี้',
    statusHeader: '**สถานะสุขภาพของการเชื่อมต่อ:**',
    statusEmpty: 'ไม่มีการเชื่อมต่อที่ใช้งานอยู่ให้รายงานสถานะ',
    guidanceLabel: '💡 **คำแนะนำ:**',
    reconnectHint: '• เชื่อมต่อใหม่หรืออัปเดตข้อมูลรับรอง: `/connect {target} <ข้อมูลใหม่>`',
    disconnectHint: '• ตัดการเชื่อมต่อ: `/disconnect {target}`',
    localPathVerifiedSuffix: 'ไดเรกทอรีในเครื่องตรวจสอบแล้ว: `{path}`',
    credentialsVaultSuffix: 'ข้อมูลรับรองถูกเข้ารหัสและเก็บไว้อย่างปลอดภัยในห้องนิรภัย',
    secretStoreFailed: '❌ การจัดเก็บข้อมูลรับรองที่เข้ารหัสล้มเหลวสำหรับ **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **เชื่อมต่อ {target} (Device Code Flow):**\n1. เปิดลิงก์อนุญาต: {url}\n2. ยืนยันการอนุญาตในเบราว์เซอร์ของคุณ\n3. Zavorth จะดำเนินการ handshake ให้เสร็จสิ้นโดยอัตโนมัติ',
    missingDeviceVerificationUrl: 'ไม่พบ URL การตรวจสอบอุปกรณ์',
    oauthConnectedSuccess: '✅ เชื่อมต่อกับ **{target}** สำเร็จผ่าน OAuth2!',
    oauthExchangeFailed: '❌ การแลกเปลี่ยนโทเค็น OAuth ล้มเหลวสำหรับ **{target}**: {details}',
    oauthListenerFailed: '⚠️ การเริ่ม listener เรียกกลับ OAuth ล้มเหลว: {details}',
    oauthConfigActive: 'การกำหนดค่า OAuth สำหรับ **{target}** ใช้งานอยู่',
    catalogConnectHint: 'เพื่อเชื่อมต่อเป้าหมายใด ๆ ให้พิมพ์: `/connect <เป้าหมาย>`',
    statusLabel: 'สถานะ',
    healthLabel: 'สุขภาพ',
    authLabel: 'การรับรอง',
    connectedAtLabel: 'เชื่อมต่อเมื่อ',
    disconnectServiceHint: '• ตัดการเชื่อมต่อบริการ: `/disconnect <เป้าหมาย>`',
  },
  vi: {
    title: 'Hệ thống con kết nối phổ quát',
    connectedSuccess: 'Đã kết nối thành công với **{target}**!',
    disconnectedSuccess: 'Đã ngắt kết nối khỏi **{target}**. Thông tin xác thực cục bộ đã bị xóa.',
    alreadyConnected: 'Mục tiêu **{target}** đã được kết nối (trạng thái: `connected`).',
    notConnected: "Không có kết nối đang hoạt động với '{target}'.",
    unrecognizedTarget: "Không nhận ra mục tiêu '{target}'.",
    rateLimitExceeded: 'Đã vượt giới hạn tốc độ: bạn có thể chạy tối đa 10 lệnh kết nối mỗi phút. Vui lòng chờ.',
    apiKeyPrompt: 'Để kết nối với **{target}**, hãy cung cấp {label} của bạn:\n`/connect {id} <khóa_của_bạn>`',
    localPathPrompt: 'Để kết nối với **{target}**, hãy chỉ định đường dẫn thư mục cục bộ:\n`/connect {id} /duong/dan/{kind}`',
    oauthDeviceCodePrompt: 'Để hoàn tất ủy quyền thiết bị cho **{target}**:\n1. Mở: {url}\n2. Nhập mã ghép nối: `{code}`',
    catalogTitle: 'Danh mục kết nối khả dụng',
    noActiveConnections: 'Không tìm thấy kết nối đang hoạt động.\n\n• Kết nối tích hợp: `/connect <mục_tiêu>`\n• Xem danh mục khả dụng: `/connections catalog`',
    usageConnect: '**Cách dùng lệnh Connect:**\n`/connect <mục_tiêu> [thông_tin_xác_thực]`\n\n**Ví dụ:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /duong/dan/vault`\n\nDùng `/connections catalog` để xem tất cả mục tiêu khả dụng.',
    usageDisconnect: 'Cách dùng: `/disconnect <mục_tiêu>`\nVí dụ: `/disconnect stripe`',
    handshakeInProgress: 'Đã có một nỗ lực kết nối đang diễn ra cho mục tiêu này.',
    pathVerificationFailed: '❌ Xác minh đường dẫn thất bại cho **{target}**: {details}',
    apiKeyVerificationFailed: '❌ Xác minh khóa thất bại cho **{target}**: {details}',
    oauthClickLink: '🔗 **Kết nối {target}:**\nNhấp vào liên kết bên dưới để ủy quyền cho Zavorth:\n[Ủy quyền {target}]({url})',
    oauthEnded: '⚠️ Ủy quyền OAuth cho **{target}** đã kết thúc: {details}',
    activeConnectionsHeader: '**Các kết nối đang hoạt động của bạn ({count}):**',
    catalogEmpty: 'Hiện không có mục tiêu nào trong danh mục kết nối.',
    statusHeader: '**Trạng thái sức khỏe kết nối:**',
    statusEmpty: 'Không có kết nối đang hoạt động để báo cáo trạng thái.',
    guidanceLabel: '💡 **Hướng dẫn:**',
    reconnectHint: '• Kết nối lại hoặc cập nhật thông tin xác thực: `/connect {target} <thông_tin_mới>`',
    disconnectHint: '• Ngắt kết nối: `/disconnect {target}`',
    localPathVerifiedSuffix: 'Thư mục cục bộ đã được xác minh: `{path}`',
    credentialsVaultSuffix: 'Thông tin xác thực đã được mã hóa và lưu an toàn trong kho.',
    secretStoreFailed: '❌ Lưu thông tin xác thực được mã hóa thất bại cho **{target}**: {details}',
    deviceCodeFlowInstructions: '🔑 **Kết nối {target} (Luồng Mã Thiết bị):**\n1. Mở liên kết ủy quyền: {url}\n2. Xác nhận ủy quyền trong trình duyệt của bạn.\n3. Zavorth sẽ tự động hoàn tất handshake.',
    missingDeviceVerificationUrl: 'Thiếu URL xác minh thiết bị',
    oauthConnectedSuccess: '✅ Đã kết nối thành công với **{target}** qua OAuth2!',
    oauthExchangeFailed: '❌ Trao đổi mã thông báo OAuth thất bại cho **{target}**: {details}',
    oauthListenerFailed: '⚠️ Khởi động trình lắng nghe callback OAuth thất bại: {details}',
    oauthConfigActive: 'Cấu hình OAuth cho **{target}** đang hoạt động.',
    catalogConnectHint: 'Để kết nối bất kỳ mục tiêu nào, hãy gõ: `/connect <mục_tiêu>`',
    statusLabel: 'Trạng thái',
    healthLabel: 'Sức khỏe',
    authLabel: 'Xác thực',
    connectedAtLabel: 'Kết nối lúc',
    disconnectServiceHint: '• Ngắt kết nối dịch vụ: `/disconnect <mục_tiêu>`',
  },
  bn: {
    title: 'সার্বজনীন সংযোগ উপ-সিস্টেম',
    connectedSuccess: '**{target}**-এর সাথে সফলভাবে সংযুক্ত হয়েছে!',
    disconnectedSuccess: '**{target}** থেকে সংযোগ বিচ্ছিন্ন হয়েছে। স্থানীয় শংকাপত্র মুছে ফেলা হয়েছে।',
    alreadyConnected: 'টার্গেট **{target}** ইতিমধ্যে সংযুক্ত (স্ট্যাটাস: `connected`)।',
    notConnected: "'{target}' এর সাথে কোনো সক্রিয় সংযোগ নেই।",
    unrecognizedTarget: "'{target}' টার্গেট চেনা যায়নি।",
    rateLimitExceeded: 'রেট সীমা অতিক্রম করেছে: আপনি প্রতি মিনিটে সর্বোচ্চ ১০টি সংযোগ কমান্ড চালাতে পারেন। অনুগ্রহ করে অপেক্ষা করুন।',
    apiKeyPrompt: '**{target}**-এর সাথে সংযোগ করতে, আপনার {label} দিন:\n`/connect {id} <আপনার_কী>`',
    localPathPrompt: '**{target}**-এর সাথে সংযোগ করতে, স্থানীয় ডিরেক্টরির পথ নির্দিষ্ট করুন:\n`/connect {id} /পথ/{kind}`',
    oauthDeviceCodePrompt: '**{target}**-এর জন্য ডিভাইস অনুমোদন সম্পূর্ণ করতে:\n১. খুলুন: {url}\n২. পেয়ারিং কোড লিখুন: `{code}`',
    catalogTitle: 'উপলব্ধ সংযোগ ক্যাটালগ',
    noActiveConnections: 'কোনো সক্রিয় সংযোগ পাওয়া যায়নি।\n\n• একটি ইন্টিগ্রেশন সংযুক্ত করুন: `/connect <টার্গেট>`\n• উপলব্ধ ক্যাটালগ দেখুন: `/connections catalog`',
    usageConnect: '**Connect কমান্ডের ব্যবহার:**\n`/connect <টার্গেট> [শংকাপত্র]`\n\n**উদাহরণ:**\n• `/connect github`\n• `/connect stripe sk_live_...`\n• `/connect obsidian /পথ/vault`\n\nসব উপলব্ধ টার্গেট দেখতে `/connections catalog` ব্যবহার করুন।',
    usageDisconnect: 'ব্যবহার: `/disconnect <টার্গেট>`\nউদাহরণ: `/disconnect stripe`',
    handshakeInProgress: 'এই টার্গেটের জন্য ইতিমধ্যে একটি সংযোগ প্রচেষ্টা চলছে।',
    pathVerificationFailed: '❌ **{target}**-এর জন্য পথ যাচাই ব্যর্থ হয়েছে: {details}',
    apiKeyVerificationFailed: '❌ **{target}**-এর জন্য কী যাচাই ব্যর্থ হয়েছে: {details}',
    oauthClickLink: '🔗 **{target} সংযুক্ত করুন:**\nZavorth অনুমোদন করতে নিচের লিঙ্কটিতে ক্লিক করুন:\n[{target} অনুমোদন]({url})',
    oauthEnded: '⚠️ **{target}**-এর জন্য OAuth অনুমোদন শেষ হয়েছে: {details}',
    activeConnectionsHeader: '**আপনার সক্রিয় সংযোগ ({count}):**',
    catalogEmpty: 'বর্তমানে সংযোগ ক্যাটালগে কোনো টার্গেট উপলব্ধ নেই।',
    statusHeader: '**সংযোগ স্বাস্থ্য অবস্থা:**',
    statusEmpty: 'অবস্থা জানানোর জন্য কোনো সক্রিয় সংযোগ নেই।',
    guidanceLabel: '💡 **নির্দেশনা:**',
    reconnectHint: '• পুনরায় সংযোগ করুন বা শংকাপত্র আপডেট করুন: `/connect {target} <নতুন_শংকাপত্র>`',
    disconnectHint: '• সংযোগ বিচ্ছিন্ন করুন: `/disconnect {target}`',
    localPathVerifiedSuffix: 'স্থানীয় ডিরেক্টরি যাচাই করা হয়েছে: `{path}`',
    credentialsVaultSuffix: 'শংকাপত্র এনক্রিপ্ট করা হয়েছে এবং ভল্টে নিরাপদে সংরক্ষণ করা হয়েছে।',
    secretStoreFailed: '❌ **{target}**-এর জন্য এনক্রিপ্ট করা শংকাপত্র সংরক্ষণ ব্যর্থ হয়েছে: {details}',
    deviceCodeFlowInstructions: '🔑 **{target} সংযুক্ত করুন (ডিভাইস কোড ফ্লো):**\n১. অনুমোদন লিঙ্কটি খুলুন: {url}\n২. আপনার ব্রাউজারে অনুমোদন নিশ্চিত করুন।\n৩. Zavorth স্বয়ংক্রিয়ভাবে হ্যান্ডশেক সম্পূর্ণ করবে।',
    missingDeviceVerificationUrl: 'ডিভাইস যাচাই URL অনুপস্থিত',
    oauthConnectedSuccess: '✅ OAuth2-এর মাধ্যমে **{target}**-এর সাথে সফলভাবে সংযুক্ত হয়েছে!',
    oauthExchangeFailed: '❌ **{target}**-এর জন্য OAuth টোকেন বিনিময় ব্যর্থ হয়েছে: {details}',
    oauthListenerFailed: '⚠️ OAuth কলব্যাক লিসেনার শুরু করতে ব্যর্থ: {details}',
    oauthConfigActive: '**{target}**-এর জন্য OAuth কনফিগারেশন সক্রিয়।',
    catalogConnectHint: 'যেকোনো টার্গেট সংযোগ করতে টাইপ করুন: `/connect <টার্গেট>`',
    statusLabel: 'অবস্থা',
    healthLabel: 'স্বাস্থ্য',
    authLabel: 'প্রমাণীকরণ',
    connectedAtLabel: 'সংযুক্ত সময়',
    disconnectServiceHint: '• একটি পরিষেবা বিচ্ছিন্ন করুন: `/disconnect <টার্গেট>`',
  },
};

/**
 * Build a localization service that also carries the hand-curated `connections`
 * sections for every supported locale, layered onto the resolved
 * builtin/gateway/legacy catalogs.
 */
export function createConnectionsAwareLocalizationService(): ZavorthLocalizationService {
  const service = createGatewayAwareLocalizationService();

  for (const [localeTag, section] of Object.entries(CONNECTIONS_CATALOG_EXTENSIONS)) {
    const base: LocalizationCatalog = service.getCatalog(localeTag);
    service.registerDynamicCatalog(localeTag, { ...base, connections: section });
  }

  return service;
}
